<div class="catalogue_item_c">
<style>
.catalogue_item_c {
background-color:#F3F3F3;
}
.catalogue_item_cont_m
{
	/*background-color:#FFFFFF;*/
	background: #fff
	border:1px solid lightgray;
	color:#000000;
	margin:0;
	padding: 0;
	width: 100%;
	height: 100%;
}
.header_liver{
	width: 980px;
	height: 322px;
	margin: 10px auto;
}
.front_liver{
	width: 457px;
	height: 305px;
	margin: 20px auto;
}
.info_liver{
	width: 980px;
	margin: 20px auto;
	font-family: Comic sans ms;
	font-size: 12pt;
}
.info_liver p{
	text-align: justify;
	text-indent: 30px;	
}
.info_liver li{
	list-style: circle;
	margin-left: 50px;
	text-align: left;
}
.wedd_prop{
	font-size: 14pt;
	text-decoration: underline;
	font-weight: bold;
	font-style: italic;
	color: #663300;
}
.wedd_prop_red{
	font-size: 12pt;
	font-weight: bold;
	font-style: italic;
	color: #ff0000;
}
.conf_liver_14{
	font-size: 14pt;
}
.conf_liver_text{
	width: 620px;
	float: left;
}
.conf_liver_img{
	width: 300px;
	height: 225px;
	float: right;
	margin: 20px;
}
.liver_clear{
	clear: both;
}
.info_liver_table{
	border: #000 solid 1px;
	font-family: Times new roman;
	font-size: 12pt;
	color: #000;
	width: 90%;
	margin: 20px auto;
	border-collapse: collapse;
}
.info_liver_table td{
	border: #000 solid 1px;
	border-collapse: collapse;
	text-align: center;
}
</style>

<?php
if ($_GET['pm'] == 1) 
{
?>
<div class="catalogue_item_cont_m">
<div class="header_liv">
	<img src="root/610_liverpool/logo.jpg" alt="Liverpool art restaurant hotel">
</div>
<div class="front_liver">
	<img src="root/610_liverpool/top.jpg" alt="Liverpool fasad">
</div>
<div class="info_liver">
	<p>Art-Hotel «Liverpool» is located in the heart of largest and fastest growing cities in Ukraine - Donetsk. Non-standard name influenced the design of rooms, reception and exterior facade of the building, which was built in 2007. In close proximity to the hotel is located one of the best stadiums in Europe “Donbass Arena”, which will be held Euro 2012! Close to hotel - the Cathedral and within walking distance - the exhibition center "Expo-Donbass". Due to its advantageous location, you can quickly get to any restaurant, cafe, business and shopping centers, and nightclubs. If you don`t want to go anywhere - visit Live music bar, which is located on the hotel. Art-restaurant - is not only a place to eat, but also places where performing famous singers and DJ`s.</p>
    <p>In the evening you can relax in the hotel. Here are rooms for any guest, regardless of his mood and financial capabilities. All categories of rooms are equipped with shower, air conditioning, desk lamp, telephone, TV.</p>
    <center><b>Additional services</b></center>
    <ul>
    	<li>art restaurant/bar;</li>
        <li>2 conference halls;</li>
        <li>free parking;</li>
        <li>concierge;</li>
        <li>transfer from one person to the group, car rental;</li>
        <li>courier delivery; </li>
        <li>booking air, rail and bus tickets; </li>
        <li>laundry;</li>
        <li>free luggage storage;</li>
        <li>printing and scanning, facsimile, international phone communications;</li>
        <li>free Wi-Fi in the rooms;</li>
        <li>booking tables at restaurants; </li>
        <li>booking tickets in concert halls (on arrival); </li>
        <li>currency exchange;</li>
        <li>iron and ironing board, hair dryer.</li>
    </ul>
    <center class="wedd_prop">Wedding proposal in Art-hotel Liverpool! </center>
    <p>Wedding is one of the most brilliant, beautiful, exciting and important events in the lives of everyone! So let the memories of this festive day will remain forever in your hearts and will be linked with the atmosphere of warmth and love that you get from staying in “Liverpool”! Liverpool staff will gladly help pick up a first class menu for the banquet in a restaurant to complement the already bright rooms with a unique design.</p>
    <center class="wedd_prop_red">Wedding Package for Honeymooners includes:</center>
    <ul>
    	<li>Accommodation in lux room.</li>
        <li>Specially wedding decorated rooms. </li>
        <li>Present from hotel (fruits and champagne).</li>
        <li>Breakfast in the room.</li>
        <li>Early check-in.</li>
        <li>Late checkout (until 18:00). </li>
    </ul>
    <p><b>Package Price:</b></p>
    <p>If staying in a room «Liverpool» - 1070 UAH.</p>
    <p>If staying in a room «G. Britain» - 960 UAH.</p>
    <p><i>Besides Wedding package includes accommodation wedding guests with a 10% discount in all types of rooms!</i></p>
    <center class="conf_liver_14"><b>Conference service in "Liverpool"</b></center>
    <p>Liverpool is always happy to meet business people, accommodate guests in the hotel rooms, feed in the art restaurant and helps arrange a ceremony, conferences, seminars, trainings.</p>
    <center><b>Conference Hall Wonderland</b></center>
    <div class="conf_liver_text">
    	<p>Great place for celebrations (weddings, birthdays, banquets, etc.) as well as training and seminars. Maximum capacity 80-100 persons. This hall with unique design, which may change depending on the customer request. “Wonderland” is equipped with a microphone, screen, projector with the ability to connect to a PC and a flip chart.</p>
        <p>The cost of renting the conference room 450 UAH per hour and include: presentation equipment (1 radio microphone, 1 flip chart, screen), furniture placement, wireless internet access.</p>
    </div>
    <div class="conf_liver_img">
    	<img src="root/610_liverpool/conference.jpg">
    </div>
    <center class="liver_clear"><b>Catering</b></center>
    <p>Everyone who wants to have the opportunity to order coffee break (from 50 UAH per person) and dinner (from 150 UAH per person) can do this in our restaurant. Depending on the order of feeding the participants cost of renting the conference room can be reduced.</p>
    <center><b><i>Price list</i></b></center>
    <table class="info_liver_table" width="100%">
    	<tr valign="top">
        	<td width="40%"><b>Types of rooms</b></td>
            <td width="20%"><b>Number of rooms</b></td>
            <td width="20%"><b>Room rates for 1 person. per day, UAH.</b></td>
            <td width="20%"><b>Room rates for 2 person. per day, UAH.<b></td>
        </tr>
        <tr valign="top">
        	<td width="40%"><b>ECONOM KING</b><br><img src="root/610_liverpool/room01.jpg" alt="econom king"></td>
            <td width="20%">21</td>
            <td width="20%">495</td>
            <td width="20%">543</td>
        </tr>
        <tr valign="top">
        	<td width="40%"><b>STANDART KING</b><br><img src="root/610_liverpool/room02.jpg" alt="econom king"></td>
            <td width="20%">13</td>
            <td width="20%">560</td>
            <td width="20%">595</td>
        </tr>
        <tr valign="top">
        	<td width="40%"><b>EXECUTIVE KING</b><br><img src="root/610_liverpool/room03.jpg" alt="econom king"></td>
            <td width="20%">21</td>
            <td width="20%">593</td>
            <td width="20%">630</td>
        </tr>
        <tr valign="top">
        	<td width="40%"><b>TWIN</b><br><img src="root/610_liverpool/room04.jpg" alt="econom king"></td>
            <td width="20%">25</td>
            <td width="20%">550</td>
            <td width="20%">550</td>
        </tr>
        <tr valign="top">
        	<td width="40%"><b>TRIPLE</b><br><img src="root/610_liverpool/room05.jpg" alt="econom king"></td>
            <td width="20%">5</td>
            <td width="20%">585</td>
            <td width="20%">585</td>
        </tr>
        <tr valign="top">
        	<td width="40%"><b>JUNIOR SUITE</b><br><img src="root/610_liverpool/room06.jpg" alt="econom king"></td>
            <td width="20%">9</td>
            <td width="20%">610</td>
            <td width="20%">655</td>
        </tr>
        <tr valign="top"><td colspan="4"><b>Executive brand rooms</b></td></tr>
        <tr valign="top">
        	<td width="40%"><b>Liverpool</b><br><img src="root/610_liverpool/room07.jpg" alt="econom king"></td>
            <td width="20%">1</td>
            <td width="20%">995</td>
            <td width="20%">995</td>
        </tr>
        <tr valign="top">
        	<td width="40%"><b>G. Britain</b><br><img src="root/610_liverpool/room08.jpg" alt="econom king"></td>
            <td width="20%">1</td>
            <td width="20%">895</td>
            <td width="20%">895</td>
        </tr>
        <tr valign="top">
        	<td width="40%"><b>Brand rooms </b><br><img src="root/610_liverpool/room09.jpg" alt="econom king"></td>
            <td width="20%">1</td>
            <td width="20%">688</td>
            <td width="20%">715</td>
        </tr>
         <tr valign="top"><td colspan="4"><b>* The room rate includes breakfast (30 UAH per person)</b></td></tr>
    </table>
    <center><b>We look forward to you!</b></center>
    <center>For all inquiries please contact:</center>
	<center>Commercial Manager in art-hotel Liverpool</center>
	<center>Helena Tarasova</center>
    <br>
    <center>+38(095)300-44-54</center>
    <br>
    <br>
    <br>
    <br>
    <center>131 v, Artema st., Donetsk, 83015</center>
    <center>phone/fax: +38 (062)312-54-74 (75)</center>
	<center>e-mail: cm@liverpool.com.ua</center>
	<center>www.liverpool.com.ua</center>
</div>
</div>
<?
}
?>
</div>

