<div class="catalogue_item_c">

<style>



<!--

.folding{cursor:hand;font-weight:bold}

-->



#acc {

list-style: none;

}



#acc .acc-section {

background: white;

margin: 0px;

overflow: hidden;

}



element.style {

height: 0px;

}



.catalogue_item_cont p {

color:#000000;

text-align:justify;

text-indent:0px;

line-height:20px;

margin:0px;

}



.catalogue_item_cont_m {

background-color:#FFFFFF;

border:1px solid lightgray;

color:#000000;

margin:0;

margin:15px 10px 10px;

width:980px;

}



.catalogue_item_cont {

background-color:#ffffff;

border-top:1px solid lightgray;

margin:0 0 7px 10px;

width:980px;

color:#000000;

}

.catalogue_item_c {

background-color:#F3F3F3;

}



.catalogue_item_cont a {

color:#000000;

}



.catalogue_item_cont a:hover {

color:#000000;

text-decoration:underline;

}



.catalogue_item_mp_a {

left:3px;

position:relative;

}



#mm_menu {position:relative;left:610px;width:225px;text-align:center;} 



#div_st {padding:0 0px;position:relative;height:1180px;}



@media all and (-webkit-min-device-pixel-ratio:10000),

not all and (-webkit-min-device-pixel-ratio:0) {

 #div_st {height:1120px;}

}



#div_st2 {padding:0 0px;position:relative;height:1100px;}



@media all and (-webkit-min-device-pixel-ratio:10000),

not all and (-webkit-min-device-pixel-ratio:0) {

 #div_st2 {height:1100px;}

}



#div_st3 {padding:0 0px;position:relative;height:1300px;}



@media all and (-webkit-min-device-pixel-ratio:10000),

not all and (-webkit-min-device-pixel-ratio:0) {

 #div_st3 {height:1300px;}

}



/*

td#i_up {font-weight:bold;text-align:center;}

td#i_up1 {font-weight:bold;text-decoration:underline;}

td#i_first {width:510px;text-align:center;font-size:16px;}

td#i_second {width:75px;font-size:14px;}

td#i_third {width:50px;font-size:14px;}

table#i_table tr {height:35px;}

*/



div{

	display:block;

	font-family:Arial, Helvetica, sans-serif;

	font:Arial, Helvetica, sans-serif;

}



.sequ_container {

	background:#ffefec;

	width:800px;

	height:100%;

	margin:0px;

	padding:0px;

	margin-left:90px;

}



.sequ_left {

	position:relative;

	float:left;

	width:95%;

	font-size:16px;

	padding:15px;

}



.sequ_right {

	position:relative;

	float:left;

	width:10%;

	padding:20px;

	bottom:20px;

}



.reds {

	color:red;

}



p#p_j {

	text-align:justify;

}



p#p_low {

	text-align:justify;

	text-transform:lowercase;

}



.sequ_acc-mid {

	position:relative;

	float:left;

	width:96%;

	font-size:16px;

	padding:15px;

}



.sequ_con_mid {

	position:relative;

	float:left;

	width:96%;

	font-size:24px;

	padding:15px;

}





#main_patison {
				width:980px;
				margin:10px auto 50px auto;
				overflow:hidden;
				}
#menu_patison {
		margin:3px auto 3px auto;
		height:60px;
		}
#menu_patison ul {list-style:none; margin:0 50px 0 110px; }
#menu_patison li {
			float:left;
			display:block;
			padding:0 10px 0 10px;
			}
#menu_patison a {
			padding:15px 10px 0 10px;
			font-size:24px;	
			font-family:Georgia;
			color:#000;
			text-decoration:none;		
		}
#menu_patison a:hover {
			padding:15px 10px 0 10px;
			font-size:24px;	
			font-family:Georgia;
			color:#92de05;
			text-decoration:none;		
		}		
#content_patison {
			width:960px;
			margin:0 auto 10px auto;
			overflow:hidden;
		}		
#left_patison { 
		width:251px;
		float:left;
		overflow:hidden;
		}
		
#ufo_patison {
		width:241px;
		height:328px;
		background-color:#dbdbdb;
		border:5px solid #92de05;
		}
#ufo_patison img {margin:0 10px 0 30px;}
#phone_patison {
			width:241px;
			background-color:#dbdbdb;
			border:5px solid #92de05;
			text-align:center;
			margin:10px 0 0 0;
			padding:20px 0 25px 0;
		}
#phone_patison p {font-size:18px; padding:0; margin:0;}
#phone_patison a {color:#000; font-size:18px; text-decoration:none;}	
#phone_patison a:hover {color:#000; font-size:18px; text-decoration:underline;}			
#baner_patison {
			margin:10px 0 0 0;
			width:241px;
			border:5px solid #92de05;
		}
#baner_patison img {padding:0;}				
#reft_patison {
		width:699px;
		float:right;
		overflow:hidden;
		}
		
#logo_patison {
		background-image:url(../root/msite/patison/logo.jpg);
		width:689px;
		height:328px;
		border:5px solid #92de05;
		}
		
#nav_patison 	{
		margin:220px auto 30px auto;
		text-align:center;
		font-size:16px;
		font-family:Tahoma;
		padding:0;		
		}
#nav_patison p{padding:0; margin:0}
#nav_patison img {padding-left:3px;}
#nav_patison a {color:#000; text-decoration:none; font-size:14px; font-weight:bold;}
#nav_patison a:hover {color:#000; text-decoration:none;}

#text_patison {
		margin:10px 0 0 0;
		width:689px;
		overflow:hidden;
		border:5px solid #92de05;
		text-align:center;
		font-size:18px;
		}		
#text_patison p {text-align:justify; padding:0 15px 0 15px;}		
#text_patison a {font-size:18px; color:#000; text-decoration:none;}		
#text_patison h1 {font-size:24px; text-decoration:underline; margin:40px 0 20px 0;}	
#text_patison img {border:3px solid #92de05;}

#uslugi_patison {margin:10px 0 60px 0;}
#uslugi_patison p {padding:1px 15px 0 15px; margin:0;}
#uslugi_patison h3 {font-size:18px; margin:10px 0 10px 0;}

#footer_patison {width:60px; margin:10px auto 15px auto; border:1px solid #92de05;}





</style>

<?php

if ($_GET['pm'] == 1) 

{

?>

<div class="catalogue_item_cont_m"> 

	<div id="div_st">

		<div id="main_patison">
		
        
        <div id="menu_patison">
     				<br />
        		 <ul>
          
                	
                    <li><a href="index.php?business_full=540&pm=1">УСЛУГИ</a></li>
                    <li><a href="index.php?business_full=540&pm=2.html">НАРУЖНАЯ РЕКЛАМА</a></li>
                    <li><a href="index.php?business_full=540&pm=3">НАШИ РАБОТЫ</a></li>
               </ul>   
        </div>

		<div id="content_patison">
        				<div id="left_patison">
                        	<div id="ufo_patison">
                            <img src="../root/msite/patison/ufo.jpg" />
                            </div>
                            
                            <div id="phone_patison">
                            
                            <p>+38 062 348 88 80</p>
							<p>+38 062 330 90 09</p>
							<p>+38 050 474 25 44</p>
							<p>+38 067 644 05 03</p>
							<p>+38 093 303 90 09</p><br />
							<a href="http://www.patison.com.ua">http://www.patison.com.ua</a>
							<a href="mailto:dir@patison.com.ua">dir@patison.com.ua</a>
                            
                            </div>
                            
                            <div id="baner_patison">
                            <img src="../root/msite/patison/P_240x400.gif" />
                            </div>
                            
                        </div>

						<div id="reft_patison">
                        	
                            <div id="logo_patison">
                            	<div id="nav_patison">
            						<p><a href="#">размещение наружной рекламы на рекламных плоскостях</a></p> <p><a href="#">биллборды</a><img src="../root/msite/patison/chek.gif" />
                					<a href="#">бэклайты</a><img src="../root/msite/patison/chek.gif" />
                					<a href="#">растяжки</a><img src="../root/msite/patison/chek.gif" />
                					<a href="#">ситилайты</a><img src="../root/msite/patison/chek.gif" />
                					<a href="#">лайтбоксы</a><img src="../root/msite/patison/chek.gif" />
                					<a href="#">магистральные щиты</a></p>  
                					<p><a href="#">призматроны</a><img src="../root/msite/patison/chek.gif" />
                					<a href="#">пилларсы</a><img src="../root/msite/patison/chek.gif" />
                					<a href="#">видеоборды</a><img src="../root/msite/patison/chek.gif" />
                					<a href="#">брендмауэры</a><img src="../root/msite/patison/chek.gif" />
               						<a href="#">суперсайт</a></p> 
               						<p><a href="#">брендмобили</a><img src="../root/msite/patison/chek.gif" /> 
                					<a href="#">автоборды</a></p>
          						</div>
                            </div>
                            
                            <div style="background-image:url(../root/msite/patison/bg_color_patison.jpg);" id="text_patison">
                            			<h1>УСЛУГИ</h1>
                                   		<div id="uslugi_patison">
                                      <h3>Рекламные кампании на территории Украины.</h3> 
<p>- местные</p> 
<p>- региональные</p> 
<p>- масштабные</p> 
<p>- общеукраинские</p> 
<p>- политические</p> 

<h3>Обращаясь к нам Вы получаете абсолютно бесплатно:</h3> 
<p>- консультацию по вопросам и проблемам размещения наружной рекламы семь дней в неделю</p> 
<p>- профессиональный подбор индивидуальной адресной программы наружных рекламных носителей </p>
<p>- комплексно разработанную рекламную кампанию по наружной рекламе </p>
<p>- разработку и оптимизацию рекламного бюджета </p>

<h3>В рамках проведения рекламной кампании на территории Украины мы предлагаем: </h3>
<p>- оригинальную идею рекламного сюжета </p>
<p>- разработку дизайна рекламного изображения</p> 
<p>- качественную печать </p>
<p>- размещение на рекламном щите в любом из городов Украины от крупного областного центра до поселка городского типа </p>
<p>- предоставление фотоотчета </p>         
</div>                                              
                                    
                            </div>
                         
		</div>

		

</div>





		</div> <!-- sequ_container -->

	</div>  <!-- div_st -->

</div> <!-- cat_ite_cont_m -->

<?php

}

else

   if ($_GET['pm'] == 2)

   {

?>

<div class="catalogue_item_cont_m"> 

	<div id="main_patison">
		
        
        <div id="menu_patison">
     				<br />
        		 <ul>
          
                	
                    <li><a href="index.php?business_full=540&pm=1">УСЛУГИ</a></li>
                    <li><a href="index.php?business_full=540&pm=2.html">НАРУЖНАЯ РЕКЛАМА</a></li>
                    <li><a href="index.php?business_full=540&pm=3">НАШИ РАБОТЫ</a></li>
               </ul>   
        </div>

		<div id="content_patison">
        				<div id="left_patison">
                        	<div id="ufo_patison">
                            <img src="../root/msite/patison/ufo.jpg" />
                            </div>
                            
                            <div id="phone_patison">
                            
                            <p>+38 062 348 88 80</p>
							<p>+38 062 330 90 09</p>
							<p>+38 050 474 25 44</p>
							<p>+38 067 644 05 03</p>
							<p>+38 093 303 90 09</p><br />
							<a href="http://www.patison.com.ua">http://www.patison.com.ua</a>
							<a href="mailto:dir@patison.com.ua">dir@patison.com.ua</a>
                            
                            </div>
                            
                            <div id="baner_patison">
                            <img src="../root/msite/patison/P_240x400.gif" />
                            </div>
                            
                        </div>

						<div id="reft_patison">
                        	
                            <div id="logo_patison">
                            	<div id="nav_patison">
            						<p><a href="#">размещение наружной рекламы на рекламных плоскостях</a></p> <p><a href="#">биллборды</a><img src="../root/msite/patison/chek.gif" />
                					<a href="#">бэклайты</a><img src="../root/msite/patison/chek.gif" />
                					<a href="#">растяжки</a><img src="../root/msite/patison/chek.gif" />
                					<a href="#">ситилайты</a><img src="../root/msite/patison/chek.gif" />
                					<a href="#">лайтбоксы</a><img src="../root/msite/patison/chek.gif" />
                					<a href="#">магистральные щиты</a></p>  
                					<p><a href="#">призматроны</a><img src="../root/msite/patison/chek.gif" />
                					<a href="#">пилларсы</a><img src="../root/msite/patison/chek.gif" />
                					<a href="#">видеоборды</a><img src="../root/msite/patison/chek.gif" />
                					<a href="#">брендмауэры</a><img src="../root/msite/patison/chek.gif" />
               						<a href="#">суперсайт</a></p> 
               						<p><a href="#">брендмобили</a><img src="../root/msite/patison/chek.gif" /> 
                					<a href="#">автоборды</a></p>
          						</div>
                            </div>
                            
                            <div style="background-image:url(../root/msite/patison/bg_color_patison.jpg);" id="text_patison">
                            			<h1>НАРУЖНАЯ РЕКЛАМА</h1>
                                       
                                    <p>Агентство наружной рекламы ООО "Патисон" предлагает комплексные услуги по проведению рекламных кампаний на наружных рекламных щитах по всей территории Украины. </p>

<p>На нашем сайте Вы найдете более 50000 рекламных плоскостей во Всех крупных городах, областных центрах, поселках городского типа и на трассах. При подготовке рекламной кампании Вам не прийдется обращаться к десятку рекламных агентств за информацией о рекламных конструкциях. Все рекламные щиты (билборды, ситилайты, брендмауэры, троллы, растяжки, автоборды, брендмобили, нестандартные конструкции, мегаборды) на сайте <a href="http://www.patison.com.ua">www.patison.com.ua</a></p>
 <p>Интернет-магазин рекламных плоскостей «Patison» всегда готов предложить любую свободную рекламную плоскость на территории Украины. Простой и понятный интерфейс навигационной системы поможет Вам самостоятельно выбрать тип рекламной плоскости, стоимость, период размещения, город и адрес для размещения рекламы. На протяжении нескольких лет плодотворной работы наши специалисты накапливали информацию и опыт для того, чтобы сейчас заказ на размещение рекламы требовал от Вас минимальных усилий. Чёткая и профессиональная работа менеджеров позволяет предоставить услуги на самом высоком уровне, что увеличивает количество наших постоянных клиентов.</p>

<p>Опытные и приветливые менеджеры подберут для Вас предложение рекламных плоскостей по запросу в день обращения.</p>
<p>Профессионализм менеджеров позволяет проводить масштабные рекламные кампании сразу в нескольких городах одновременно.</p>
<p>Рекламное агентство Patison существует для удобства маркетологов, менеджеров по рекламе и Руководителей компаний.</p>
<p>Мы готовы предоставить полноценную и законченную услугу по размещению рекламы на рекламных конструкциях в Украине.</p>

<p>Разработка идеи и подготовка дизайна рекламного сюжета любой сложности.</p>
<p>Печать рекламных постеров и банеров для наружной рекламы.</p>
<p>Поклейка рекламного материала на наружные рекламные носители и предоставление фотоотчета</p>
<p>Обслуживание рекламных конструкций и смена сюжета в процессе проведения рекламной кампании</p>

<p>Наша цель – создание максимально удобной и доступной базы рекламных плоскостей для того, чтобы управление рекламной компанией стало для Вас простым и приятным делом. Мы заинтересованы в успешных рекламных кампаниях и высокой отдаче от нашей работы.</p>
<p>Мы стремимся предоставить самые эффективные рекламные щиты, которые будут максимально подходить именно Вашей компании и вашему виду деятельности. </p>

<p>Будем рады видеть Вас в числе наших клиентов</p>

                                    
                            </div>
                            
                        </div>

		</div>

</div>

		
</div> <!-- cat_ite_cont_m -->

<?php

}

else

   if ($_GET['pm'] == 3)

   {

?>

<div class="catalogue_item_cont_m"> 

	<div id="main_patison">
		
        
        <div id="menu_patison">
     				<br />
        		 <ul>
          
                	
                    <li><a href="index.php?business_full=540&pm=1">УСЛУГИ</a></li>
                    <li><a href="index.php?business_full=540&pm=2.html">НАРУЖНАЯ РЕКЛАМА</a></li>
                    <li><a href="index.php?business_full=540&pm=3">НАШИ РАБОТЫ</a></li>
               </ul>   
        </div>

		<div id="content_patison">
        				<div id="left_patison">
                        	<div id="ufo_patison">
                            <img src="../root/msite/patison/ufo.jpg" />
                            </div>
                            
                            <div id="phone_patison">
                            
                            <p>+38 062 348 88 80</p>
							<p>+38 062 330 90 09</p>
							<p>+38 050 474 25 44</p>
							<p>+38 067 644 05 03</p>
							<p>+38 093 303 90 09</p><br />
							<a href="http://www.patison.com.ua">http://www.patison.com.ua</a>
							<a href="mailto:dir@patison.com.ua">dir@patison.com.ua</a>
                            
                            </div>
                            
                            <div id="baner_patison">
                            <img src="../root/msite/patison/P_240x400.gif" />
                            </div>
                            
                        </div>

						<div id="reft_patison">
                        	
                            <div id="logo_patison">
                            	<div id="nav_patison">
            						<p><a href="#">размещение наружной рекламы на рекламных плоскостях</a></p> <p><a href="#">биллборды</a><img src="../root/msite/patison/chek.gif" />
                					<a href="#">бэклайты</a><img src="../root/msite/patison/chek.gif" />
                					<a href="#">растяжки</a><img src="../root/msite/patison/chek.gif" />
                					<a href="#">ситилайты</a><img src="../root/msite/patison/chek.gif" />
                					<a href="#">лайтбоксы</a><img src="../root/msite/patison/chek.gif" />
                					<a href="#">магистральные щиты</a></p>  
                					<p><a href="#">призматроны</a><img src="../root/msite/patison/chek.gif" />
                					<a href="#">пилларсы</a><img src="../root/msite/patison/chek.gif" />
                					<a href="#">видеоборды</a><img src="../root/msite/patison/chek.gif" />
                					<a href="#">брендмауэры</a><img src="../root/msite/patison/chek.gif" />
               						<a href="#">суперсайт</a></p> 
               						<p><a href="#">брендмобили</a><img src="../root/msite/patison/chek.gif" /> 
                					<a href="#">автоборды</a></p>
          						</div>
                            </div>
                            
                            <div style="background-image:url(../root/msite/patison/bg_color_patison.jpg);" id="text_patison">
                            			<h1>НАШИ РАБОТЫ</h1>
                                        
                                        
                                        <div>
                                        <img src="../root/msite/patison/Florence.jpg" />
                                        <p style="text-align:center; padding:0; margin:1px 0 30px 0;">Дизайн для развлекательного комплекса "Флоренция"</p>
                                        </div>
                                   	
                                       <div>
                                        <img src="../root/msite/patison/Powerlifting5.jpg" />
                                        <p style="text-align:center; padding:0; margin:1px 0 30px 0;">Дизайн для сети спортивных клубов "SportMax"</p>
                                        </div>
                                        
                                        
                                         <div>
                                        <img src="../root/msite/patison/1662.jpg" />
                                        <p style="text-align:center; padding:0; margin:1px 0 30px 0;">Дизайн для магазина одежды</p>
                                        </div>
                                        
                                        
                                         <div>
                                        <img src="../root/msite/patison/Wine1.jpg"  />
                                        <p style="text-align:center; padding:0; margin:1px 0 30px 0;">Дизайн для "Виномания"</p>
                                        </div>                                          
                                    
                                    	  <div>
                                        <img src="../root/msite/patison/Karnizi-(2).jpg"  />
                                        <p style="text-align:center; padding:0; margin:1px 0 30px 0;">Дизайн для "Карнизы и жалюзи"</p>
                                        </div>        
                                        
                                          <div>
                                        <img src="../root/msite/patison/JCB.jpg"  />
                                        <p style="text-align:center; padding:0; margin:1px 0 30px 0;">Дизайн для "JCB"</p>
                                        </div>        
                                        
                                          <div>
                                        <img src="../root/msite/patison/HoReCa_big_board.jpg"  />
                                        <p style="text-align:center; padding:0; margin:1px 0 30px 0;">Дизайн для "Horeca"</p>
                                        </div>        
                                        
                                          <div>
                                        <img src="../root/msite/patison/Estrella.jpg"  />
                                        <p style="text-align:center; padding:0; margin:1px 0 30px 0;">Дизайн для "La primera Estrella"</p>
                                        </div>        
                               
                             
                               	<table id="footer_patison" border="1" cellspacing="0" cellpadding="0">
  <tr>
    <td style="border:1px solid #92de05; background-color:#999;"><a href="index.php?business_full=540&pm=3">1</a></td>
    <td style="border:1px solid #92de05;"><a href="index.php?business_full=540&pm=4">2</a></td>
  </tr>
</table>

                             
                                        
                            </div>
                          
                            
                        </div>

		</div>

		

</div>

</div> <!-- cat_ite_cont_m -->

<?php

}

else

   if ($_GET['pm'] == 4)

   {

?>

<div class="catalogue_item_cont_m"> 

		<div id="menu_patison">
     				<br />
        		 <ul>
          
                	
                    <li><a href="index.php?business_full=540&pm=1">УСЛУГИ</a></li>
                    <li><a href="index.php?business_full=540&pm=2.html">НАРУЖНАЯ РЕКЛАМА</a></li>
                    <li><a href="index.php?business_full=540&pm=3">НАШИ РАБОТЫ</a></li>
               </ul>   
        </div>

		<div id="content_patison">
        				<div id="left_patison">
                        	<div id="ufo_patison">
                            <img src="../root/msite/patison/ufo.jpg" />
                            </div>
                            
                            <div id="phone_patison">
                            
                            <p>+38 062 348 88 80</p>
							<p>+38 062 330 90 09</p>
							<p>+38 050 474 25 44</p>
							<p>+38 067 644 05 03</p>
							<p>+38 093 303 90 09</p><br />
							<a href="http://www.patison.com.ua">http://www.patison.com.ua</a>
							<a href="mailto:dir@patison.com.ua">dir@patison.com.ua</a>
                            
                            </div>
                            
                            <div id="baner_patison">
                            <img src="../root/msite/patison/P_240x400.gif" />
                            </div>
                            
                        </div>

						<div id="reft_patison">
                        	
                            <div id="logo_patison">
                            	<div id="nav_patison">
            						<p><a href="#">размещение наружной рекламы на рекламных плоскостях</a></p> <p><a href="#">биллборды</a><img src="../root/msite/patison/chek.gif" />
                					<a href="#">бэклайты</a><img src="../root/msite/patison/chek.gif" />
                					<a href="#">растяжки</a><img src="../root/msite/patison/chek.gif" />
                					<a href="#">ситилайты</a><img src="../root/msite/patison/chek.gif" />
                					<a href="#">лайтбоксы</a><img src="../root/msite/patison/chek.gif" />
                					<a href="#">магистральные щиты</a></p>  
                					<p><a href="#">призматроны</a><img src="../root/msite/patison/chek.gif" />
                					<a href="#">пилларсы</a><img src="../root/msite/patison/chek.gif" />
                					<a href="#">видеоборды</a><img src="../root/msite/patison/chek.gif" />
                					<a href="#">брендмауэры</a><img src="../root/msite/patison/chek.gif" />
               						<a href="#">суперсайт</a></p> 
               						<p><a href="#">брендмобили</a><img src="../root/msite/patison/chek.gif" /> 
                					<a href="#">автоборды</a></p>
          						</div>
                            </div>
                            
                            <div style="background-image:url(../root/msite/patison/bg_color_patison.jpg);" id="text_patison">
                            			<h1>НАШИ РАБОТЫ</h1>
                                        
                                        
                                        <div>
                                        <img src="../root/msite/patison/Lightbox_zoo_2_print.jpg" />
                                        <p style="text-align:center; padding:0; margin:1px 0 30px 0;">Дизайн для зоомагазина "Зоология"</p>
                                        </div>
                                   	
                                       <div>
                                        <img src="../root/msite/patison/Logos1.jpg" />
                                        <p style="text-align:center; padding:0; margin:1px 0 30px 0;">Дизайн для ООО "Логос-плюс"</p>
                                        </div>
                                        
                                        
                                         <div>
                                        <img src="../root/msite/patison/Seminar2.jpg" />
                                        <p style="text-align:center; padding:0; margin:1px 0 30px 0;">Дизайн для семинаров</p>
                                        </div>
                                        
                                        
                                         <div>
                                        <img src="../root/msite/patison/tas3.jpg"  />
                                        <p style="text-align:center; padding:0; margin:1px 0 30px 0;">Дизайн для "ТАС"</p>
                                        </div>                                          
                                    
                                    	  <div>
                                        <img src="../root/msite/patison/TD2_2.jpg" />
                                        <p style="text-align:center; padding:0; margin:1px 0 30px 0;">Дизайн для "Торговый Дизайн"</p>
                                        </div>        
                                        
                                          <div>
                                        <img src="../root/msite/patison/Teplovodosnab.jpg"  />
                                        <p style="text-align:center; padding:0; margin:1px 0 30px 0;">Дизайн для "Тепловодоснабжения"</p>
                                        </div>        
                                        
                                          <div>
                                        <img src="../root/msite/patison/3-.jpg" />
                                        <p style="text-align:center; padding:0; margin:1px 0 30px 0;">Дизайн для поздравительных открыток</p>
                                        </div>        
                                        
                               
                             
                               	<table id="footer_patison" border="1" cellspacing="0" cellpadding="0">
  <tr>
    <td style="border:1px solid #92de05;"><a href="index.php?business_full=540&pm=3">1</a></td>
    <td style="border:1px solid #92de05;   background-color:#999;"><a href="index.php?business_full=540&pm=4">2</a></td>
  </tr>
</table>

                             
                                        
                            </div>
                          
                            
                        </div>

		</div>

		

</div>

</div> <!-- cat_ite_cont_m -->

<?php

   } 

?>







<div id="catalogue_item_menu">

<div class="catalogue_item_mp_a">

<a href="index.php?section_id=32&amp;business=1">Категория:</a></div>

</div>

<div class="catalogue_item_cont">

<a href="index.php?section_id=2&amp;business=1">бизнес</a>

 / 

<a href="index.php?section_id=32&amp;business=1">предприятия</a>

 / 

<a href="index.php?section_id=368&business=2">услуги</a>

 / 

<a href="index.php?section_id=371&business=2">рекламные агенства</a>

</div>





<div id="catalogue_item_menu">

<div class="catalogue_item_mp_a">

<a href="">Фотогалерея:</a></div>

</div>

<div class="catalogue_item_cont">

</div>

<div id="catalogue_item_menu">

<div class="catalogue_item_mp_a">

<a href="">Контактная информация:</div>

</div>

 <div class="catalogue_item_cont">

 		 <table width="100%">

			<tbody>

 			<tr>

			<!--	<td><img class="main_sec_image" src="" width="60" height="60" border="0" alt="" /></td>-->

				<td>Адрес:</td>

				<td>Телефон:</td>

				<td>Факс:</td>

				<td>E-mail:</td>

				<td>Веб-сайт:</td>

			</tr>

			<tr>

				<td>83114 , Донецк , Университетская, 80 В, , офис 401 </td>

				<td>+38(062)3488880</td>

				<td></td>

				<td>E-mail: dir@patison.com.ua</td>

				<td>www.patison.com.ua</td>



			</tr>

			</tbody> 

		 </table> 		

	 </div>

</div>  





