<div class="catalogue_item_c">
<style>

<!--
.folding{cursor:hand;font-weight:bold}
-->

@charset "utf-8";
/* CSS Document */

body {
	/*font-family:Georgia, "Times New Roman", Times, serif;*/
	background: white;
	margin: 0;
	padding: 0;
	color: #567300;
	font-size: 10pt;
	line-height:1.4em;
	border: none;
}

.catalogue_item_cont p {
color:#000000;
text-align:justify;
text-indent:0px;
line-height:20px;
margin:0px;
}

.catalogue_item_cont_m {
background-color:#FFFFFF;
border:1px solid lightgray;
color:#000000;
margin:0;
margin:15px 10px 0px 0px;
width:980px;
}
.catalogue_item_cont {
background-color:#ffffff;
border-top:1px solid lightgray;
margin:0 0 0px 10px;
width:980px;
color:#000000;
}
.catalogue_item_c {
background-color:#F3F3F3;
}

.catalogue_item_cont a {
color:#000000;
}
.catalogue_item_cont a:hover {
color:#000000;
text-decoration:underline;
}
.catalogue_item_mp_a {
left:3px;
position:relative;
}

.m_h1, m_h2 {
	float:left;
	width:100%;
	text-align:center;
	color:#ddefb5;
	background:#567300;
	padding:6px 0;
	font-family:Georgia, "Times New Roman", Times, serif;	
}
.m_h1 {font-size:14pt;}
.m_h2 {font-size:12pt;
		font-family:Georgia, "Times New Roman", Times, serif;}

.moh {
		font-family:Georgia, "Times New Roman", Times, serif;
}

.moh a {
		color: #040b7f;
		font-family:Georgia, "Times New Roman", Times, serif;
}
.moh a:hover{
	color: #040b7f;
	text-decoration: none;
	font-family:Georgia, "Times New Roman", Times, serif;
}
.moh p {
		text-indent:12pt; margin:0 0 5px 0;
		font-family:Georgia, "Times New Roman", Times, serif;
}

.moh_tab {
	font-family:Georgia, "Times New Roman", Times, serif;
}

.clearer{clear: both;}

#container_all {
	width:100%;
	margin:0 0 0 0;
	position:relative;
	float:left;
}

#container_in {
	width:700px;
	margin:0 auto;
	position:relative;
	float:left;
	left:15%;
}

#cont1 {
	float:left;
	width:650px;
	margin: 0 auto;
	background:url(../root/msite/mohito/imgs/bg_1.jpg) repeat;
	padding:0 25px;
}

#cont2 {
	float:left;
	width:630px;
	margin: 0;
	background:url(../root/msite/mohito/imgs/bg_2.jpg) repeat;
	padding:0 10px;
}

.header {
	float:left;
	width:630px;
	height:180px;
	background:#e3faf0 url(../root/msite/mohito/imgs/header.jpg) no-repeat center;
}

.center {
	position:relative;
	float:left;
	width:100%;
	background:#eaf9c2;
}

.menu {
	float:left;
	width:130px;
	background:#eaf9c2;
}

.menu a {
	display:block;
	float:left;
	width:120px;
	background:#81ad00;
	color:#e4e9d2;
	margin:0 0 1px 0;
	padding:10px 0 10px 10px;
	font-style:italic;
	font-size:12pt;
	font-family:Georgia, "Times New Roman", Times, serif;
}

.menu a:hover {color:#2e4404;}

.text_box {
	float:left;
	width:495px;
	background:#fff;
	border:1px solid #ccc;
	padding: 0 0 5px 0;
}

.text_box p {margin:0 5px 5px 5px;
			font-family:Georgia, "Times New Roman", Times, serif;}
.text_box img {
	float:left;
	margin:5px 3px;
}

.footer {
	float:left;
	width:100%;
	height:9px;
	background:url(../root/msite/mohito/imgs/bottom.jpg) repeat-x;
}

.red {color:#F00; font-size:larger; font-weight:bold; font-style:italic;}

table.menu_list {float:left; margin:0 15px;
				font-family:Georgia, "Times New Roman", Times, serif;
				}
table.menu_list th {text-align:center; font-weight:bold; margin:10px 0 0 0;}
table.menu_list td, table.menu_list th {padding:2px 0;}

/*------------------------------------------------------*/

</style>
<?php
if ($_GET['pm'] == 1) 
{
?>
<div class="catalogue_item_cont_m"> 
<div id="container_all">
<div id="container_in">
<div id="cont1">
	<div id="cont2">

        <h1 class="m_h1">Mojito club - клубное сердце Донецка</h1>
        <div class="header"></div>
        <div class="clearer"></div>
        
        <div class="center">
        <div class="menu">
        	<a class="moh" href="http://eurodonetsk.com/index.php?business_full=406&pm=1">Главная</a>
            <a class="moh" href="http://eurodonetsk.com/index.php?business_full=406&pm=2">Меню</a>
            <a class="moh" href="http://eurodonetsk.com/index.php?business_full=406&pm=3">Контакты</a>
        </div>
        
        <div class="text_box">
        	<h2 class="m_h2">Большой выбор вариаций на тему самого<br/> популярного коктейля в мире - МОХИТО!</h2>
            
<p class="moh"><span class="red">Мохито Клуб</span> –  это атмосферное заведение. Одно из немногих мест нашего города, где 
отдыхаешь всей душой, всем сердцем. Здесь сказали твердое «нет» жесткому формату. Только уютная атмосфера, прекрасная кухня, отличные коктейли, музыка для души и, конечно, наше гостеприимство!  В какое время Вы сюда не  придете, здесь всегда легкая уютная атмосфера клуба, всегда только близкие по духу люди, удивительно вкусная кухня и музыка, созданная  для отдыха.</p>

<div class="clearer"></div>
<img src="../root/msite/mohito/imgs/m02.jpg" width="177" height="117" alt="мохито" />
<img src="../root/msite/mohito/imgs/m01.jpg" width="124" height="117" alt="мохито клуб" />
<img src="../root/msite/mohito/imgs/m03.jpg" width="175" height="117" alt="мохито" />
<div class="clearer"></div>

<p class="moh"> Будет ли это утренняя встреча для глотка кофе с приятелем или подругой в 
  meeting-баре, бизнес-ланч с деловым партнером, беседу с которым стоит 
  провести в неформальной обстановке или зажигательный вечер в компании 
  друзей — «Мохито Клуб» создаст атмосферу высочайшего комфорта и отличной 
  кухни. Ведь основная наша задача – это сделать максимально комфортное пребывание наших гостей с акцентом на хорошей кухне и культуре потребления алкогольных напитков.</p>
<p class="moh">В Донецке немного  мест, где кухня отличается таким разнообразием: 
здесь и Европа,  и Япония и, конечно, славянская кухня рождают новые 
удивительные сочетания, а по - настоящему правильные коктейли и 
действительно правильная музыка создают атмосферу полного комфорта для 
Вас и Ваших друзей.</p>

<p class="moh">Проведите здесь романтический вечер — кулинарная дипломатия нашего 
шеф-повара в сочетании с прекрасной картой вин найдут путь к сердцу 
Вашей дамы, а нежнейшие десерты и большой выбор вариаций  приготовления самого популярного  коктейля мира - Мохито оставят у Вас незабываемые впечатления об этом вечере.</p>
<br />
<p class="red" style="text-align:center;">Берите всех своих друзей и приходите в «Мохито Клуб», самый уютный 
клуб-ресторан в сердце Донецка!</p>
<br /><br />
<p class="moh">Наш адрес - ул. Артема, 125а. <br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Расписание работы: 11:00 - до 00:00, в 
выходные - до 1:00!</p>
<br />
<p class="moh">Тел.: (062) 305-50-05, (099) 503 46 49.</p>
<div id="same_img" style="position:relative; float:left; left:74%; bottom:50px;"><img align="right" src="../root/msite/mohito/imgs/mite.png" /></div>
               
        </div>    
        </div>
        
        <div class="footer"></div>
	</div>
</div>
</div>
</div>
<?php
}
else
   if ($_GET['pm'] == 2)
   {
?>
<div class="catalogue_item_cont_m"> 
<div id="container_all">
<div id="container_in">
<div id="cont1">
	<div id="cont2">

        <h1 class="m_h1">Mojito club - клубное сердце Донецка</h1>
        <div class="header"></div>
        <div class="clearer"></div>
        
        <div class="center">
        <div class="menu">
        	<a class="moh" href="http://eurodonetsk.com/index.php?business_full=406&pm=1">Главная</a>
            <a class="moh" href="http://eurodonetsk.com/index.php?business_full=406&pm=2">Меню</a>
            <a class="moh" href="http://eurodonetsk.com/index.php?business_full=406&pm=3">Контакты</a>
        </div>
        
        <div class="text_box">
        <h2 class="m_h2">Кухня и напитки в Mojito Club<br/> заслуживают отдельного рассказа!</h2>
                  
	<table class="menu_list">            
	<tr><th colspan="3">Итальянская страничка</th></tr>                                                                                                                       
    <tr><td></td><td>Вес грамм</td><td>Цена</td></tr>
	<tr><td>Каннеллони фаршированные телятиной и моцареллой</td><td>	250 </td><td> 60,00</td></tr>
	<tr><td>Лазанья "Болоньезе"	</td><td>300</td><td>	60,00</td></tr>
	<tr><td>Лазанья с морепродуктами</td><td>300</td><td>	60,00</td></tr>
	<tr><td>Спагетти "Карбонара"</td><td>	250</td><td>	42,00</td></tr>
	<tr><td>Спагетти с соусом "Болоньезе"</td><td>	250</td><td>	45,00</td></tr>
	<tr><td>Спагетти с телятиной</td><td>	250</td><td>45,00</td></tr>
	<tr><td>Тальятелли с грибным соусом	</td><td>250</td><td>	38,00</td></tr>
	<tr><td>Тальятелли с морепродуктами	</td><td>250	</td><td>55,00</td></tr>
	<tr><td>Фетучини по-охотничьи</td><td>	250</td><td>	45,00</td></tr>
	<tr><td>Ризотто с лесными грибами</td><td>	250	</td><td>38,00</td></tr>
	<tr><td>Ризотто с морепродуктами</td><td>	250</td><td>	55,00</td></tr> 
    
    
    <tr><th colspan="3">Пицца</th></tr>
            
    <tr><td>Пицца «Маргарита»<br/> Классическое сочетание томатного соуса, базилика и сыра «Моцарелла»	</td><td>400</td><td>	38,00</td></tr>
    <tr><td>Пицца с курицей и ананасом</td><td>	450	</td><td>41,00</td></tr>
    <tr><td>Пицца с салями</td><td>	450</td><td>	44,99</td></tr>
    <tr><td>Пицца «Четыре сыра» «Дор-Блю», «Пармезан», «Моцарелла», «Камамбер»</td><td>	450	</td><td>49,99</td></tr>
    <tr><td>Пицца с морепродуктами</td><td>	450	</td><td>49,99</td></tr>
    <tr><td>Пицца « Дьябло»<br/> Острая пицца со свининой и овощами	</td><td>450</td><td>	44,99</td></tr>
    <tr><td>Вегетарианская пицца</td><td>	450	</td><td>39,99</td></tr>

	<tr><th colspan="3">Японская кухня</th></tr>                                                                                                                       
    <tr><td></td><td>Вес грамм</td><td>Цена</td></tr>
	<tr><td>Роллы «Калифорния»</td><td>	180 </td><td> 65,00</td></tr>
	<tr><td>Ролл «Дракон»</td><td>180</td><td>	75,00</td></tr>
	<tr><td>Маки лосось</td><td>110</td><td>	25,00</td></tr>
	<tr><td>Маки тунец		</td><td>110</td><td>	46,99</td></tr>
	<tr><td>Маки угорь</td><td>120</td><td>	34,99</td></tr>
	<tr><td>Суши лосось</td><td>35</td><td>14,00</td></tr>
	<tr><td>Суши тунец	</td><td>35</td><td>	20,00</td></tr>
	<tr><td>Суши угорь</td><td>35</td><td>15,00</td></tr>  
   
    <tr><th colspan="3">Холодные закуски</th></tr>
            
    <tr><td><b>Карпаччо из лосося</b><br /> Тонко нарезанное филе лосося с сочными листьями салата, заправкой из оливкового масла и сока лимона	</td><td>180</td><td>	79,99</td></tr>
    <tr><td><b>Карпаччо из телятины</b><br /> Тонко нарезанная нежная говяжья вырезка с оливковым маслом, бальзамическим  уксусом, соком лимона и сыром «Пармезан»</td><td>	200	</td><td>59,99</td></tr>
    <tr><td>Сельдь с маринованным луком и теплым картофелем</td><td>	280</td><td>	30,00</td></tr>
    <tr><td><b>«Мясное изобилие»</b> из буженины, говяжьего и куриного рулетов собственного производства</td><td>	180	</td><td>58,00</td></tr>
    <tr><td><b>Сырное плато</b> из сыров «Камамбер», «Дор-Блю», «Радомер», «Фетаки» с миндалем, инжиром и виноградом</td><td>	200	</td><td>74,99</td></tr>
    <tr><td><b>Коктейль из креветок</b><br/> Нежные очищенные креветки с кисло-сладким томатным соусом	</td><td>100/75</td><td>54,99</td></tr>
    <tr><td><b>Закуска под водочку</b><br/> сало, соленый огурец, помидор, квашенная капуста, баклажаны</td><td>	500/25	</td><td>50,00</td></tr>
    <tr><td><b>Чипсы с соусами "Сальса" и "Гуакамоли"</b><br/> Исконно мексиканская закуска к пиву	</td><td>100/50/505</td><td>59,99</td></tr>
    <tr><td>Махан</td><td>	100	</td><td>30,00</td></tr>

	<tr><th colspan="3">Салаты</th></tr>
     
    <tr><td></td><td>Вес грамм</td><td>Цена</td></tr>        
    <tr><td><b>Салат из морепродуктов</b><br /> Мидии, креветки, кальмары с сочными листьями салата, болгарским перцем и лимонным соусом</td><td>250	</td><td>	59,99</td></tr>
    <tr><td><b>Салат из семги и королевских  креветок</b><br /> Оригинальное сочетание сёмги ,креветок и отварных овощей с майонезной заправкой </td><td>	270		</td><td>49,99</td></tr>
    <tr><td>Салат «Цезарь» с сёмгой и креветками<br />Хрустящие листья салата «Айсберг» со слабосолёной сёмгой и креветками, сыром «Пармезан», томатами «Черри» и крутонами под классическим соусом «Цезарь»</td><td>	250	</td><td>	58,99</td></tr>
    <tr><td><b>Салат «Цезарь» с куриной грудкой</b> Хрустящие листья салата «Айсберг» с куриной грудкой, томатами «Черри», сыром «Пармезан» и крутонами под классическим соусом «Цезарь»</td><td>	250	</td><td>47,99</td></tr>
    <tr><td><b>Салат «Цезарь» с беконом</b>Хрустящие листья салата «Айсберг» с беконом, сыром «Пармезан», томатами «Черри» и крутонами
под классическим соусом «Цезарь»</td><td>	250		</td><td>49,99</td></tr>
    <tr><td><b>Салат из теплой телятины</b><br/> Обжаренные ломтики телячьей вырезки с сыром «Моцарелла», томатами, сельдереем, сладким перцем, листьями салата с оливково-бальзамическим соусом	</td><td>250	</td><td>52,99</td></tr>
    <tr><td><b>Салат «Гастрономическое изобилие»</b><br/> Удивительное сочетание копченого куриного филе, ветчины и овощей под пикантным соусом</td><td>	270		</td><td>44,99</td></tr>
    <tr><td><b>Салат классический «Столичный»</b><br/> Нежное куриное филе в сочетании с солеными огурцами, картофелем, яйцом на листьях салата с соусом «Майонез»	</td><td>250	</td><td>30,00</td></tr>  
     <tr><td><b>Салат из нежной куриной печени </b><br /> Нежная куриная печень обжаренная с соевым соусом в сочетании с овощами и грушей образует совершенство вкуса!</td><td>250	</td><td>	39,99</td></tr>
    <tr><td><b>Салат из теплой утиной грудки</b><br /> Сочная утиная грудка с листьями салата,  авокадо, кедровыми орешками, под соусом из  фруктового уксуса и орехового масла </td><td>	250		</td><td>49,99</td></tr>
    <tr><td><b>Салат мясной</b><br />Классический салатик из нежной отварной телятины, соленого огурчика, картофеля, яйца, горошка, под соусом «Майонез»</td><td>	250	</td><td>	36,00</td></tr>
    <tr><td><b>Салат «Капрезо»</b> Классический итальянский салат с сыром «Моцарелла», томатами, сочным миксом салатов под соусом «Песто»</td><td>	250	</td><td>59,99</td></tr>
    <tr><td><b>Салат с тунцом и авокадо</b>Обжаренные ломтики тунца, авокадо, помидоров «Черри» с сочными листьями салата «Айсберг»</td><td>	240		</td><td>66,99</td></tr>
    <tr><td><b>Салат «Греческий»		</b><br/> Классический салат из свежих овощей с сыром «Фетаки», маслинами с оливково-лимонным соусом.	</td><td>250	</td><td>42,99</td></tr>
    <tr><td><b>Куриный салат с йогуртом</b><br/>Куриное филе с хрустящими листьями салата и соусом на основе йогурта</td><td>	250		</td><td>41,99</td></tr>
    <tr><td><b>Салат «Сельский»</b><br/> Прекрасное сочетание овощей, грибов, с ароматной заправкой на основе домашнего масла	</td><td>250	</td><td>39,99</td></tr>

	<tr><th colspan="3"> Горячие  закуски </th></tr>
    
    <tr><td></td><td>Вес грамм</td><td>Цена</td></tr>        
    <tr><td><b>Морепродукты запеченные под сливочно-сырным соусом</b> </td><td>150		</td><td>	47,99</td></tr>
    <tr><td><b>Мидии жареные с луком и пряными травами</b></td><td>	180		</td><td>46,99	</td></tr>
    <tr><td><b>Рулетики из пелингаса с сыром</b><br />Филе пелингаса фаршированное сыром с классическим рыбным соусом</td><td>	150/50		</td><td>	37,99</td></tr>
    <tr><td><b>Креветки королевские в беконе</b> </td><td>	150		</td><td>59,99</td></tr>
    <tr><td><b>Креветки коктейльные в коньячном соусе</b></td><td>	200			</td><td>39,99</td></tr>
    <tr><td><b>Креветки королевские с чесноком и пряными травами</b></td><td>150		</td><td>54,99</td></tr>
    <tr><td><b>Крокеты из морепродуктов</b><br/> Нежный фарш из морепродуктов обжаренный во фритюре с соусом</td><td>	175/50	</td><td>	59,99</td></tr>
    <tr><td><b>Куриные крылышки барбекю</b><br/> Куриные крылья, протушенные в ароматном соусе барбекю</td><td>300	</td><td>38,00</td></tr>  
    <tr><td><b>Куриные крылышки «Баффало»</b><br /> Хрустящие куриные крылышки с острым соусом</td><td>250/50</td><td>	39,99</td></tr>
    <tr><td><b>Курочка в миндале</b><br /> Нежное куриное филе в панировке из миндаля с пикантным соусом</td><td>	230/50		</td><td>42,99</td></tr>
    <tr><td><b>Классический жульен из курицы и грибов</b><br />Подается в хрустящей корзиночке</td><td>	150		</td><td>	29,99</td></tr>
    <tr><td><b>Микс из колбасок</b> Три вида колбасок с ароматным коньячным соусом</td><td>	300/50		</td><td>59,99</td></tr>
    <tr><td><b>Классическая итальянская закуска</b>Сочетание баклажана, помидора и сыра «Моцарелла» с томатным соусом</td><td>	200/50		</td><td>59,99</td></tr>
    <tr><td><b>Овощи- гриль		</b><br/>болгарский перец, баклажан, початки кукурузы ,лук  помидор, шампиньон	</td><td>400		</td><td>64,99</td></tr>
    
    <tr><th colspan="3">  Первые блюда </th></tr>
    
    <tr><td></td><td>Вес грамм</td><td>Цена</td></tr>        
    <tr><td><b>Борщ украинский с пампушками</b> </td><td>300/50	</td><td>	27,00</td></tr>
    <tr><td><b>Солянка домашняя</b> </td><td>	300		</td><td>30,00	</td></tr>
    <tr><td><b>Суп сливочный с телятиной</b></td><td>	300		</td><td>	29,99</td></tr>
    <tr><td><b>Суп томатный со свининой</b> </td><td>	300			</td><td>24,99</td></tr>
    <tr><td><b>Суп-лапша домашняя с курицей</b></td><td>	300				</td><td>24,99</td></tr>
    <tr><td><b>Сливочный суп из лосося с креветками</b>></td><td>300		</td><td>49,99</td></tr>
    <tr><td><b>Суп тайский с морепродуктами</b> </td><td>	300	</td><td>	49,99	</td></tr>
    <tr><td><b>Уха по-царски с расстегаями </b></td><td>300/50</td><td>54,99</td></tr>  
    <tr><td><b>Крем-суп из брокколи с сыром "Пармезан"</b></td><td>300</td><td>	29,99</td></tr>
    <tr><td><b>Крем-суп из шампиньонов </b></td><td>	300		</td><td>	29,99</td></tr>
    
    <tr><th colspan="3"> Рыбные блюда </th></tr>
    
    <tr><td></td><td>Вес грамм</td><td>Цена</td></tr>        
    <tr><td><b>Дорадо запеченная в соли</b><br />Запекается по особому рецепту в морской соли. Подается разделанной на филе с отварным картофелем.</td><td>1шт./150</td><td>94,99</td></tr>
    <tr><td><b>Карп в сметанном соусе</b><br />Филе карпа протушенное  в сметанном соусе. Подается с овощами на пару</td><td>	180		</td><td>46,99	</td></tr>
    <tr><td><b>Рулетики из пелингаса с сыром</b><br />Филе пелингаса фаршированное сыром с классическим рыбным соусом</td><td>1шт./150/50		</td><td>	79,99</td></tr>
    <tr><td><b>Мятный сибас</b><br />Сибас маринованный по особому рецепту с мятой. Подается с рисом и мятным соусом </td><td>1шт./100/50	</td><td>89,99</td></tr>
    <tr><td><b>Паэлья с морепродуктами</b><br />Классическая испанская паэлья</td><td>	300		</td><td>59,99</td></tr>
    <tr><td><b>Пелингас в кунжуте</b><br />Филе пелингаса панированное в кунжуте. Подается с гарниром из спаржевой фасоли</td><td>180/50		</td><td>44,99</td></tr>
    <tr><td><b>Речная форель в миндальном соусе</b><br/> Форель фаршированная морепродуктами с классическим миндальным соусом</td><td>	1шт./70</td><td>	84,99</td></tr>
    <tr><td><b>Семга по-средиземноморски</b><br/> Стейк из семги фаршированный оливками, томатами, и базиликом. Подается с картофельным пюре</td><td>250/100</td><td>129,99</td></tr>  
    <tr><td><b>Тарелка рыбака</b><br /> Креветки, мидии, семга,  пелингас, морской гребешок в сливочном соусе</td><td>240</td><td>	129,99</td></tr>
    
    <tr><th colspan="3">Горячие блюда из птицы, кролика</th></tr>
    
    <tr><td></td><td>Вес грамм</td><td>Цена</td></tr>        
    <tr><td><b>Грудка цыпленка фаршированная беконом, грибами и сыром с соусом "Тар-тар"</b></td><td>260</td><td>	49,99</td></tr>
    <tr><td><b>Карри из курицы</b><br />Классическое сочетание курицы с соусом «Карри» и риса</td><td>	200/100		</td><td>49,99	</td></tr>
    <tr><td><b>Утиная ножка с вишневым соусом и фруктами</b></td><td>230	</td><td>	59,99	</td></tr>
    <tr><td><b>Утиная грудка по-пекински</b><br />Маринованная по особому рецепту. Подается с овощами</td><td>130/100		</td><td>64,99</td></tr>
    <tr><td><b>Перепела табака</b></td><td>	1шт./100/20	</td><td>69,99</td></tr>
    <tr><td><b>Кролик тушеный с овощами в сметанно-винном соусе</b></td><td>350		</td><td>59,99	</td></tr>
 
	<tr><th colspan="3">Горячие блюда из телятины </th></tr>
    
    <tr><td></td><td>Вес грамм</td><td>Цена</td></tr>        
    <tr><td><b>Стейк по-селянски</b><br />Подается с легким салатом, обжаренным картофелем и луком-фри</td><td>200/100/50</td><td>69,99</td></tr>
    <tr><td><b>Стейк по-американски</b><br />Подается с катрофелем фри и овощами-гриль</td><td>	200/100/50		</td><td>69,99	</td></tr>
    <tr><td><b>Стейк по-азиатски</b><br />Прожаренный с восточными специями. Подается с овощным гарниром</td><td>200/150			</td><td>74,99</td></tr>
    <tr><td><b>Медальоны в гранатовом соусе</b></td><td>150/50	</td><td>69,99</td></tr>
    <tr><td><b>Медальоны из телятины с сыром «Камамбер» </td><td>150/50		</td><td>74,99</td></tr>
    <tr><td><b>Охотничья сковорода</b><br />Ассорти из телятины, свинины и курицы с овощами в соусе «Деми-Глясс»</td><td>300		</td><td>	74,99</td></tr>
    <tr><td><b>Бычьи яйца в сметанно-грибном соусе</b></td><td>	150/50	</td><td>49,99</td></tr>
    
    <tr><th colspan="3">Горячие блюда из свинины</th></tr>
    
    <tr><td></td><td>Вес грамм</td><td>Цена</td></tr>        
    <tr><td><b>Свиная отбивная на ребре с горчичным соусом</b></td><td>180/50/20</td><td>69,99</td></tr>
    <tr><td><b>Стейк из свиной шеи с сырным соусом  «Дор-Блю»</b></td><td>	150/50/50		</td><td>69,99	</td></tr>
    <tr><td><b>Свиные ребрышки барбекю</b></td><td>200/100			</td><td>	69,99</td></tr>
    <tr><td><b>Свиные медальоны с луком-порей</b><br />Подаются с ореховым соусом и гарниром</td><td>150/50/50</td><td>74,99</td></tr>
		
    <tr><th colspan="3">Гарниры</th></tr>
    
    <tr><td></td><td>Вес грамм</td><td>Цена</td></tr>        
    <tr><td><b>Картофель фри</b></td><td>150</td><td>16,99</td></tr>
    <tr><td><b>Картофельное пюре</b></td><td>	150		</td><td>16,99</td></tr>
    <tr><td><b>Картофель жареный по-домашнему с луком и салом</b></td><td>150			</td><td>	19,99</td></tr>
    <tr><td><b>Картофель по-селянски  запеченный с чесноком</b></td><td>150	</td><td>19,99</td></tr>
    <tr><td><b>Рис с овощами</b></td><td>150	</td><td>19,99</td></tr>
    
    <tr><th colspan="3">Десерты</th></tr>
    
    <tr><td></td><td>Вес грамм</td><td>Цена</td></tr>        
    <tr><td><b>Теплый шоколадный тортик с мороженным</b></td><td>150	</td><td>34,99</td></tr>
    <tr><td><b>Тирамису	</b></td><td>	120			</td><td>34,99</td></tr>
    <tr><td><b>Чиз-кейк</b></td><td>120		</td><td>	34,99</td></tr>
    
    <tr><th colspan="3">Популярные Мохито</th></tr>
    
    <tr><td></td><td>Вес грамм</td><td>Цена</td></tr>        
    <tr><td colspan="2"><b>Мохито</b> (Лайм, мята свежая, сахар тростниковый, ром, ликер зеленая мята)</td><td>50,00</td></tr>
    <tr><td colspan="2"><b>Мохито кубинский </b>(Ром кубинский, лимонный фреш, мята, сахар, содовая, кубики льда)</td><td>50,00</td></tr>
	<tr><td colspan="2"><b>Мохито фроузен </b>(Ром кубинский, лимонный фреш, мята, сахар тростниковый, содовая)</td><td>50,00</td></tr>
    <tr><td colspan="2"><b>Мохито коблер </b>(Ром кубинский, лимонный фреш, киви, яблоко, клюква, апельсин)</td><td>55,00</td></tr>
    <tr><td colspan="2"><b>Мохито малиновый </b>( Лайм, мята свежая, сахар тростниковый, ром, клубника свежая, содовая)</td><td>55,00</td></tr>
    <tr><td colspan="2"><b>Мохито киви </b>(Ром  кубинский, лимонный фреш, мята, свежий киви)</td><td>58,00</td></tr>
    <tr><td colspan="2"><b>Клубный Мохито </b>(Лайм, мята свежая, сахар тростниковый, ликер зеленая мята, ром, Спрайт)</td><td>65,00</td></tr>
    <tr><td colspan="2"><b>Мохито золотое яблоко </b>( Лайм, мята свежая, мед, яблоко свежее, ликер яблоко, ром, Спрайт)</td><td>60,00</td></tr>
    <tr><td colspan="2"><b>Мятный Джулеп </b>(Мята свежая, сахар тростниковый, Джим Бим, Спрайт)</td><td>45,00</td></tr>
    <tr><td colspan="2"><b>Легалито </b>( Легалайз,лимонный фреш, сахар тростниковый, мята, спрайт, лайм)</td><td>45,00</td></tr>
    
    <tr><th colspan="3">Безалкогольные коктейли</th></tr>
    
    <tr><td></td><td>Вес грамм</td><td>Цена</td></tr>        
    <tr><td colspan="2"><b>Мохито б.а. </b>(Лайм, мята, сахар тросниковый, спрайт)</td><td>40,00</td></tr>
    <tr><td colspan="2"><b>Мохито Кубинский б.а. </b>( Лимонный фреш, мята, сахар тростниковый, спрайт)</td><td>35,00</td></tr>
	<tr><td colspan="2"><b>Мохито Фроузен б.а.</b>(Лимонный фреш, мята, сахар тростниковый,  содовая)</td><td>40,00</td></tr>
    <tr><td colspan="2"><b>Мохито киви б.а. </b>(Лимон фреш, мята, мед, содовая, свежий киви)</td><td>50,00</td></tr>
    <tr><td colspan="2"><b>Энерджи мохито б.а.</b>(Лайм, мята, сахар тростниковый, Red Bull)</td><td>55,00</td></tr>

    </table>           
        </div>    
        </div>
        
        <div class="footer"></div>
	</div>
</div>
</div>
</div>
<?php
}
else
   if ($_GET['pm'] == 3)
   {
?>
<div class="catalogue_item_cont_m"> 
<div id="container_all">
<div id="container_in">
<div id="cont1">
	<div id="cont2">

        <h1 class="m_h1">Mojito club - ресторан в самом сердце Донецка</h1>
        <div class="header"></div>
        <div class="clearer"></div>
        
        <div class="center">
        <div class="menu">
        	<a class="moh" href="http://eurodonetsk.com/index.php?business_full=406&pm=1">Главная</a>
            <a class="moh" href="http://eurodonetsk.com/index.php?business_full=406&pm=2">Меню</a>
            <a class="moh" href="http://eurodonetsk.com/index.php?business_full=406&pm=3">Контакты</a>
        </div>
        
        <div class="text_box">
        	<h2 class="m_h2">Кухня и напитки в Mojito club<br/> заслуживают отдельного рассказа!</h2>
            
<p class="moh" style="text-align:center;">Наш адрес: ул.Артема, 125а.</p>

<p class="moh" style="text-align:center;">Расписание работы: с 11:00 до 00:00<br/>
В выходные - до 1:00!</p>

<p class="moh" style="text-align:center;">Тел.: (062) 305-50-05, (099) 503-46-49   </p> 
<div class="clearer"></div>

			<div id="div_st">
        <script src="http://api-maps.yandex.ru/1.1/index.xml?key=AAmDzUsBAAAARkVWCAIAXzMCgKN58_MQUqB134Sdp-unCH0AAAAAAAAAAACbJlz2mcKc4anRgbxx6LBZ5BHPyg==" type="text/javascript"></script>
    <script type="text/javascript">
        window.onload = function () {
            var map = new YMaps.Map(document.getElementById("YMapsID"));
            map.setCenter(new YMaps.GeoPoint(37.804799,48.006815), 16);
			
            var content = document.createElement('span');
            content.innerHTML = "Ресторан «Mojito club»";
            map.openBalloon(new YMaps.GeoPoint(37.804799,48.006815), content);

            map.addControl(new YMaps.ToolBar());
            map.addControl(new YMaps.Zoom());
            map.addControl(new YMaps.MiniMap());
            map.addControl(new YMaps.ScaleLine());
        }
    </script>


	 <div id="YMapsID" style="width:90%; height:450px; position:relative; float:left; top:20px; left:40px; z-index:20; margin-bottom:40px;"></div>
   </div>

<div class="clearer"></div>   
       <div id="same_img" style="position:relative; float:left; left:74%; bottom:10px;"><img align="right" src="../root/msite/mohito/imgs/mite.png" /></div>

        </div>    
        </div>
        
        <div class="footer"></div>
	</div>
</div>
</div>
</div>
</div>
<?php
   } 
?>



<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="index.php?section_id=32&amp;business=1">Категория:</a></div>
</div>
<div class="catalogue_item_cont">
<a href="index.php?section_id=2&amp;business=1">бизнес</a>
 / 
<a href="index.php?section_id=32&amp;business=1">предприятия</a>
 / 
<a href="index.php?section_id=389&amp;business=2">отдых и развлечения</a>
 / 
<a href="index.php?section_id=390&amp;business=2">кафе и рестораны</a>
</div>


<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="">Фотогалегея:</a></div>
</div>
<div class="catalogue_item_cont">
</div>
<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="">Контактная информация:</a></div>
</div>
 <div class="catalogue_item_cont">
 		 <table width="100%">
			<tbody>
 			<tr>
			<!--	<td><img class="main_sec_image" src="" width="60" height="60" border="0" alt="" /></td>-->
				<td>Адрес:</td>
				<td>Телефон:</td>
				<td>Факс:</td>
				<td>E-mail:</td>
				<td>Веб-сайт:</td>
			</tr>
			<tr>
				<td>г. Донецк<br> ул.Артёма, 125а.</td>
				<td>(062) 305-50-05, (099) 503 46 49.</td>
				<td></td>
				<td></td>
				<td></td>

			</tr>
			</tbody> 
		 </table> 		
	 </div>
	 
</div> 
