<div class="catalogue_item_c">
<style>

<!--
.folding{cursor:hand;font-weight:bold}
-->

@charset "utf-8";
/* CSS Document */

body {
	font-family:Georgia, "Times New Roman", Times, serif;
	background: white;
	margin: 0;
	padding: 0;
	color: #567300;
	font-size: 10pt;
	line-height:1.4em;
	border: none;
}

.catalogue_item_cont p {
color:#000000;
text-align:justify;
text-indent:0px;
line-height:20px;
margin:0px;
}

.catalogue_item_cont_m {
background-color:#FFFFFF;
border:1px solid lightgray;
color:#000000;
margin:0;
margin:15px 10px 0px 0px;
width:980px;
height:100%;
}
.catalogue_item_cont {
background-color:#ffffff;
border-top:1px solid lightgray;
margin:0 0 0px 10px;
width:980px;
color:#000000;
}
.catalogue_item_c {
background-color:#F3F3F3;
}

.catalogue_item_cont a {
color:#000000;
}
.catalogue_item_cont a:hover {
color:#000000;
text-decoration:underline;
}
.catalogue_item_mp_a {
left:3px;
position:relative;
}

h1, h2 {
	float:left;
	width:100%;
	text-align:center;
	color:#ddefb5;
	background:#567300;
	padding:6px 0;	
}
h1 {font-size:14pt;}
h2 {font-size:12pt;}

a {color: #040b7f;}
a:hover{
	color: #040b7f;
	text-decoration: none;
}
p {text-indent:12pt; margin:0 0 5px 0;}

.clearer{clear: both;}

#container_all {
	width:100%;
	margin:0 0 0 0;
	position:relative;
	float:left;
}

#container_in {
	width:700px;
	margin:0 auto;
	position:relative;
	float:left;
	left:15%;
}

#cont1 {
	float:left;
	width:650px;
	margin: 0 auto;
	background:url(../root/msite/mohito/imgs/bg_1.jpg) repeat;
	padding:0 25px;
}

#cont2 {
	float:left;
	width:630px;
	margin: 0;
	background:url(../root/msite/mohito/imgs/bg_2.jpg) repeat;
	padding:0 10px;
}

.header {
	float:left;
	width:630px;
	height:180px;
	background:#e3faf0 url(../root/msite/mohito/imgs/header.jpg) no-repeat center;
}

.center {
	position:relative;
	float:left;
	width:100%;
	background:#eaf9c2;
}

.menu {
	float:left;
	width:130px;
	background:#eaf9c2;
}

.menu a {
	display:block;
	float:left;
	width:120px;
	background:#81ad00;
	color:#e4e9d2;
	margin:0 0 1px 0;
	padding:10px 0 10px 10px;
	font-style:italic;
	font-size:12pt;
}

.menu a:hover {color:#2e4404;}

.text_box {
	float:left;
	width:495px;
	background:#fff;
	border:1px solid #ccc;
	padding: 0 0 5px 0;
}

.text_box p {margin:0 5px 5px 5px;}
.text_box img {
	float:left;
	margin:5px 3px;
}

.footer {
	float:left;
	width:100%;
	height:9px;
	background:url(../root/msite/mohito/imgs/bottom.jpg) repeat-x;
}

.red {color:#F00; font-size:larger; font-weight:bold; font-style:italic;}

table.menu_list {float:left; margin:0 15px;}
table.menu_list th {text-align:center; font-weight:bold; margin:10px 0 0 0;}
table.menu_list td, table.menu_list th {padding:2px 0;}

/*------------------------------------------------------*/

</style>
<?php
if ($_GET['pm'] == 1) 
{
?>
<div class="catalogue_item_cont_m"> 
	<div id="container_all">
		<div id="container_in">
			<div id="cont1">
				<div id="cont2">
			
					<h1>Mojito club is a club heart of Donetsk!</h1>
					<div class="header"></div>
					<div class="clearer"></div>
					
					<div class="center">
					<div class="menu">
					<a href="http://eurodonetsk.com/index.php?business_full=407&pm=1">Main</a>
					<a href="http://eurodonetsk.com/index.php?business_full=407&pm=2">Menu</a>
					<a href="http://eurodonetsk.com/index.php?business_full=407&pm=3">Contacts</a>
					</div>
					
					<div class="text_box">
			<h2>Lots of variations on the most popular<br/> cocktail in the world - MOJITO</h2>
						
			<p><span class="red">Mojito club</span> –  A loose atmosphere reigns at the club. One can feel refreshment of mind and body here. The fixed format is absent at Mojito club.  Whenever you come here, cosy atmosphere of the club, kindred spirits, excellent cuisine, perfect cocktails and music for a soul are waiting for you. </p>
			
			<div class="clearer"></div>
			<img src="../root/msite/mohito/imgs/m02.jpg" width="177" height="117" alt="мохито" />
			<img src="../root/msite/mohito/imgs/m01.jpg" width="124" height="117" alt="мохито клуб" />
			<img src="../root/msite/mohito/imgs/m03.jpg" width="175" height="117" alt="мохито" />
			<div class="clearer"></div>
			
			<p> No matter whether it would be a tea meeting with friends at meeting-bar, or business lunch with business associate, or dancing party in a circle of friends – Mojito Club will create the atmosphere of great comfort and perfect cuisine. It is a well known fact that our main task is to make your residence at our club as comfortable as possible, making an emphasis on good cuisine and drinking culture.</p>
			<p>There are few places at Donetsk, where cuisine is so notable for such variety: European, Japanese and, of course, Slavic cuisines give rise to new combination of tastes, and perfect cocktails with soft music create atmosphere of full comfort for you and your friends. </p>
			
			<p>Spend your romantic evening at our club – culinary diplomacy of our chief cook combined with excellent wine list will contrive to reach your woman’s heart; and delicate desserts and the variety of popular cocktail – Mojito – will leave great impression about this evening.</p>
			<br />
			<p class="red" style="text-align:center;">Invite all your friends at Mojito Club, the cosiest club-restaurant in Donetsk heart!</p>
			<br /><br />
			<p>Address: 125a, Artema Street, Donetsk city <br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Working hours: from 11 AM till 12 PM, Weekends: till 1 PM</p>
			<br />
			<p>Tel. (062) 305-50-05, (099) 503 46 49.</p>
			<div id="same_img" style="position:relative; float:left; left:74%; bottom:50px;"><img align="right" src="../root/msite/mohito/imgs/mite.png" /></div>
							   
								</div>    <!-- text_box -->
								<div class="footer"></div>
							</div>	<!-- center -->
						
					
					</div> <!-- cont2 -->
			</div> <!-- cont1 -->
		</div> <!-- container_in -->
	</div> <!-- container_all -->
</div> <!-- cont_m -->
<?php
}
else
   if ($_GET['pm'] == 2)
   {
?>
<div class="catalogue_item_cont_m"> 
	<div id="container_all">
		<div id="container_in">
			<div id="cont1">
				<div id="cont2">
			
					<h1>Mojito club is a club heart of Donetsk!</h1>
					<div class="header"></div>
					<div class="clearer"></div>
					
					<div class="center">
					<div class="menu">
					<a href="http://eurodonetsk.com/index.php?business_full=407&pm=1">Main</a>
					<a href="http://eurodonetsk.com/index.php?business_full=407&pm=2">Menu</a>
					<a href="http://eurodonetsk.com/index.php?business_full=407&pm=3">Contacts</a>
					</div>
					
					<div class="text_box">
					<h2>the cuisine and drinks at Mojito club<br/> deserve high attention</h2>
							  
				<table class="menu_list">            
				<tr><th colspan="3">Italian menu</th></tr>                                                                                                                       
				<tr><td></td><td>Weight, g</td><td>Price, UAH</td></tr>
				<tr><td>Cannelloni stuffed with veal and mozzarella</td><td>	250 </td><td> 60,00</td></tr>
				<tr><td>Lasagna alla Bolognese</td><td>300</td><td>	60,00</td></tr>
				<tr><td>Seafood Lasagna</td><td>300</td><td>	60,00</td></tr>
				<tr><td>Spaghetti alla Carbonara</td><td>	250</td><td>	42,00</td></tr>
				<tr><td>Italian Spaghetti Bolognese</td><td>	250</td><td>	45,00</td></tr>
				<tr><td>Spaghetti with veal</td><td>	250</td><td>45,00</td></tr>
				<tr><td>Tagliatelle with mushroom sauce</td><td>250</td><td>	38,00</td></tr>
				<tr><td>Seafood tagliatelle</td><td>250	</td><td>55,00</td></tr>
				<tr><td>Hunting style Fettuccine</td><td>	250</td><td>	45,00</td></tr>
				<tr><td>Risotto with field mushrooms</td><td>	250	</td><td>38,00</td></tr>
				<tr><td>Seafood Risotto</td><td>	250</td><td>	55,00</td></tr> 
				
				
				<tr><th colspan="3">PIZZA</th></tr>
						
				<tr><td>“Margarita”<br/> (Tomato sauce, basil, Mozzarella cheese)	</td><td>400</td><td>	38,00</td></tr>
				<tr><td>Pizza with chicken and pineapple</td><td>	450	</td><td>41,00</td></tr>
				<tr><td>Pizza with salami</td><td>	450</td><td>	44,99</td></tr>
				<tr><td>“Four cheeses” Pizza (Dor Blue, Parmesan, Mozzarella, Camembert)</td><td>	450	</td><td>49,99</td></tr>
				<tr><td>Seafood Pizza</td><td>	450	</td><td>49,99</td></tr>
				<tr><td>“Diablo”<br/>(Spicy pizza with pork and vegetables)</td><td>450</td><td>	44,99</td></tr>
				<tr><td>Vegetarian pizza</td><td>	450	</td><td>39,99</td></tr>
			
				<tr><th colspan="3">Japanese cuisine</th></tr>                                                                                                                       
				<tr><td></td><td>Weight, g</td><td>Price, UAH</td></tr>
				<tr><td>California rolls</td><td>	180 </td><td> 65,00</td></tr>
				<tr><td>Dragon rolls</td><td>180</td><td>	75,00</td></tr>
				<tr><td>Maki salmon</td><td>110</td><td>	25,00</td></tr>
				<tr><td>Maki tuna		</td><td>110</td><td>	46,99</td></tr>
				<tr><td>Maki eel</td><td>120</td><td>	34,99</td></tr>
				<tr><td>Salmon rolls</td><td>35</td><td>14,00</td></tr>
				<tr><td>Tuna rolls	</td><td>35</td><td>	20,00</td></tr>
				<tr><td>Eel rolls</td><td>35</td><td>15,00</td></tr>  
			   
				<tr><th colspan="3">Cold Starters</th></tr>
						
				<tr><td><b>Salmon Carpaccio</b><br />(Sliced salmon fillet with leaf lettuce, dressed with olive oil and lemon juice) </td><td>180</td><td>	79,99</td></tr>
				<tr><td><b>Veal Carpaccio</b><br />(Sliced fillets of beef with olive, oil balsamic vinegar, lemon juice, Parmesan cheese)</td><td>	200	</td><td>59,99</td></tr>
				<tr><td>Herring with pickled onions and potatoes</td><td>	280</td><td>	30,00</td></tr>
				<tr><td><b>Meat profusion</b> (Homemade ham, beef and chicken rolls)</td><td>	180	</td><td>58,00</td></tr>
				<tr><td><b>Cheese platter</b> (Camembert, DorBlu, Radamer, Fetaki cheeses with almond, figs and grapes)</td><td>	200	</td><td>74,99</td></tr>
				<tr><td><b>Shrimps cocktail</b><br/> (Tender shrimps with sour-sweet tomato sauce)	</td><td>100/75</td><td>54,99</td></tr>
				<tr><td><b>Vodka snacks</b><br/>(Salted lard, pickled cucumber, tomatoes, sauerkraut,  eggplants)</td><td>	500/25	</td><td>50,00</td></tr>
				<tr><td><b>Crisps with Salsa and Guacamole sauce</b>	</td><td>100/50/505</td><td>59,99</td></tr>
				<tr><td>Makhan </td><td>	100	</td><td>30,00</td></tr>
			
				<tr><th colspan="3">Salads</th></tr>
				 
				<tr><td></td><td>Weight, g</td><td>Price, UAH</td></tr>        
				<tr><td><b>Seafood salad</b><br /> (Mussels, shrimps, calamari, leaf lettuce, dressed with lemon sauce)</td><td>250	</td><td>	59,99</td></tr>
				<tr><td><b>Salad with royal shrimps and salmon</b><br /> (Salmon, shrimps, boiled vegetables, mayonnaise sauce) </td><td>	270		</td><td>49,99</td></tr>
				<tr><td>«Caesar» Salad with salmon and shrimps<br />(Iceberg salad, light-salted salmon and shrimps, Parmesan cheese,                                                                       Cherry tomatoes, croûtons. Served with special sauce)</td><td>	250	</td><td>	58,99</td></tr>
				<tr><td><b> Chicken «Caesar» Salad </b>(Iceberg salad with chicken breast, Cherry tomatoes,                                                                          Parmesan cheese, croûtons. Served with special sauce)</td><td>	250	</td><td>47,99</td></tr>
				<tr><td><b>«Caesar» Salad with bacon</b>(Iceberg salad with bacon, Cherry tomatoes,                                                                          Parmesan cheese, croûtons. Served with special sauce) </td><td>	250		</td><td>49,99</td></tr>
				<tr><td><b>Warm salad with veal  </b><br/> (Roasted fillet of veal with Mozzarella cheese, tomatoes,                                                                                  celery, sweet pepper, lettuce, olive sauce)	</td><td>250	</td><td>52,99</td></tr>
				<tr><td><b>"Abundance" Salad</b><br/> (Smoked chicken fillet, ham, vegetables, dressed with pungent sauce)</td><td>	270		</td><td>44,99</td></tr>
				<tr><td><b>Russian salad</b><br/> (chicken fillet, pickled cucumbers, potatoes, eggs, leaf lettuce, mayonnaise sauce)</td><td>250	</td><td>30,00</td></tr>  
				 <tr><td><b>Salad with chicken liver  </b><br /> (Roasted chicken liver with soy sauce, vegetables, pear)</td><td>250	</td><td>	39,99</td></tr>
				<tr><td><b>Warm salad with duck breast </b><br /> (Duck breast with leaf lettuce,avocado, pine nuts, dressed with fruit vinegar and  nut oil )</td><td>	250		</td><td>49,99</td></tr>
				<tr><td><b>Meat salad</b><br />(Boiled veal, pickled cucumber, potato, eggs, edible peas, dressed with  mayonnaise sauce)</td><td>	250	</td><td>	36,00</td></tr>
				<tr><td><b>Italian salad</b>(Classical Italian salad with Mozzarella cheese, tomatoes, mixed salads, dressed with  Pesto sauce)</td><td>	250	</td><td>59,99</td></tr>
				<tr><td><b>Salad with tuna and avocado</b>(Roasted sliced tuna, avocado, cherry tomatoes, Iceberg salad )</td><td>	240		</td><td>66,99</td></tr>
				<tr><td><b>Grecian salad		</b><br/> (Traditional Grecian salad with Feta cheese, olives, dressed with olive-lemon sauce)	</td><td>250	</td><td>42,99</td></tr>
				<tr><td><b>Chicken salad with yoghurt</b><br/>(Chicken fillet with leaf lettuce, yoghurt sauce)</td><td>	250		</td><td>41,99</td></tr>
				<tr><td><b>Country salad </b><br/>(Vegetables, mushrooms, flavored dressing with homemade oil)</td><td>250	</td><td>39,99</td></tr>
			
				<tr><th colspan="3"> Hot Starters </th></tr>
				
				<tr><td></td><td>Weight, g</td><td>Price, UAH</td></tr>        
				<tr><td><b>Seafoods baked  with creamy cheese sauce</b> </td><td>150		</td><td>	47,99</td></tr>
				<tr><td><b>Roasted mussels with onion and  herbs</b></td><td>	180		</td><td>46,99	</td></tr>
				<tr><td><b>Red-finned mullet rolls with cheese</b><br />(Red - finned mullet fillet stuffed with cheese. Served with fish sauce)</td><td>	150/50		</td><td>	37,99</td></tr>
				<tr><td><b>Royal shrimps with garlic and herbs</b> </td><td>	150		</td><td>54,99</td></tr>
				<tr><td><b>Seafood croquette</b>(Fried minced seafoods with sauce)</td><td>	175/50			</td><td>59,99</td></tr>
				<tr><td><b>Barbecue chicken wings</b>(Chicken wings, stewed  in barbecue sauce )</td><td>300		</td><td>38,99</td></tr>
				<tr><td><b>Spicy Buffalo Wings</b><br />(Spicy chicken wings with sauce)</td><td>250/50</td><td>	39,99</td></tr>
				<tr><td><b>Chicken  with almonds</b><br /> ( Chicken fillet in almond crumbs, served with spicy sauce)</td><td>	230/50		</td><td>42,99</td></tr>
				<tr><td><b>Chicken julienne</b><br />(Mushrooms and chicken  in Sour cream Sauce. Served in tartlet)</td><td>	230/50	</td><td>	42,99</td></tr>
				<tr><td><b>Sausage mix</b> (Three kinds of sausages, served with cognac sauce)</td><td>	300/50		</td><td>59,99</td></tr>
				<tr><td><b>Classic Italian appetizer</b>(Eggplant, tomatoes, Mozzarella  cheese, with tomato sauce)</td><td>	200/50		</td><td>59,99</td></tr>
				<tr><td><b>Grilled vegetables		</b><br/>(Sweet pepper, eggplant, corncobs, onion, tomatoes, champignons)</td><td>400		</td><td>64,99</td></tr>
				
				<tr><th colspan="3">  FIRST COURSES </th></tr>
				
				<tr><td></td><td>Weight, g</td><td>Price, UAH</td></tr>        
				<tr><td><b>UKRAINIAN BORSCH  with  pampushka</b>( A deep red beet and cabbage soup) </td><td>300/50	</td><td>	27,00</td></tr>
				<tr><td><b>Homemade “Solyanka”</b>(a thick, spicy and sour soup) </td><td>	300		</td><td>30,00	</td></tr>
				<tr><td><b>Veal cream-soup  </b></td><td>	300		</td><td>	29,99</td></tr>
				<tr><td><b>Tomato soup  with pork</b> </td><td>	300			</td><td>24,99</td></tr>
				<tr><td><b>Homemade noodle soup with chicken</b></td><td>	300				</td><td>24,99</td></tr>
				<tr><td><b>Cream of salmon soup with shrimps</b>></td><td>300		</td><td>49,99</td></tr>
				<tr><td><b>Thai soup  with seafoods</b> </td><td>	300	</td><td>	49,99	</td></tr>
				<tr><td><b>Ukha po tsarski  with rasstegais</b>(A clear Russian fish soup made with the minimum of vegetables and the maximum of different varieties of fish) </td><td>300/50</td><td>54,99</td></tr>  
				<tr><td><b>Cream of Broccoli Soup with Parmesan cheese</b></td><td>300</td><td>	29,99</td></tr>
				<tr><td><b>Cream of Mushroom Soup</b></td><td>	300		</td><td>	29,99</td></tr>
				
				<tr><th colspan="3"> Fish dishes </th></tr>
				
				<tr><td></td><td>Weight, g</td><td>Price, UAH</td></tr>        
				<tr><td><b>Dorado baked in salt</b><br />(Dorado baked in sea salt, served eviscerated  with boiled potato)</td><td>1unit/150</td><td>94,99</td></tr>
				<tr><td><b>Carp with Sour Cream Sauce<br /> (Carp fillet, stewed  with sour cream sauce. Served with vegetables)</td><td>1 unit/150/50	</td><td>79,99	</td></tr>
				<tr><td><b>Mint Sea Bass</b><br />(Marinated Sea Bass with mint. Served with rice and mint sauce)</td><td>1unit/100/50</td><td>89,99</td></tr>
				<tr><td><b>Paella  with seafoods</b><br />(Classic paella Spanish recipe)</td><td>	300		</td><td>59,99</td></tr>
				<tr><td><b>Haarder in sesame </b><br />(Haarder fillet coat with sesame seeds. Served with asparagus beans ) </td><td>180/50		</td><td>44,99</td></tr>
				<tr><td><b>River trout with almond sauce</b><br/> (Trout, stuffed with seafoods. Served with almond sauce)</td><td>	1 unit/70</td><td>	84,99</td></tr>
				<tr><td><b>Salmon a'la Mediterranean  Sea</b><br/> (Salmon steak, stuffed with olives, tomatoes and basil. Served with mashed potatoes)</td><td>250/100</td><td>129,99</td></tr>  
				<tr><td><b>Seafood platter</b><br />(Shrimps, mussels, salmon, haarder, deep-sea scallop with cream sauce)</td><td>240</td><td>	129,99</td></tr>
				
				<tr><th colspan="3">Poultry  and rabbit dishes</th></tr>
				
				<tr><td></td><td>Weight, g</td><td>Price, UAH</td></tr>        
				<tr><td><b>Chicken breast stuffed with bacon,                                                          mushrooms and cheese, served with Tar Tar sauce</b></td><td>260</td><td>	49,99</td></tr>
				<tr><td><b>Chicken Curry</b><br />(Best combination of chicken with Curry sauce and rice)</td><td>	200/100		</td><td>49,99	</td></tr>
				<tr><td><b>Duck leg with cherry sauce and fruits</b></td><td>230	</td><td>	59,99	</td></tr>
				<tr><td><b>Peking Roast Duck</b><br />(Marinated duck breast, served with vegetables)</td><td>130/100		</td><td>64,99</td></tr>
				<tr><td><b>Georgian-style quail</b></td><td>	1 unit /100/20  	</td><td>69,99</td></tr>
				<tr><td><b>Rabbit stewed with vegetables and sour cream/wine sauce</b></td><td>350		</td><td>59,99	</td></tr>
			 
				<tr><th colspan="3">Veal Dishes  </th></tr>
				
				<tr><td></td><td>Weight, g</td><td>Price, UAH</td></tr>        
				<tr><td><b>Country  Steak </b><br />(Served with salad, fried potato, onion)</td><td>200/100/50</td><td>69,99</td></tr>
				<tr><td><b>American Steak</b><br />(Served with Fries and grilled vegetables)</td><td>	200/100/50		</td><td>69,99	</td></tr>
				<tr><td><b>Asian Steak</b><br />(Roasted veal steak  with spices. Served with vegetable ragout)</td><td>200/150			</td><td>69,99</td></tr>
				<tr><td><b>Veal medallions with pomegranate sauce</b></td><td>150/50	</td><td>69,99</td></tr>
				<tr><td><b>Veal medallions with Camembert cheese</td><td>150/50		</td><td>74,99</td></tr>
				<tr><td><b>Meat platter </b><br />Veal, pork, chicken with vegetables and Demi-glace sauce)</td><td>300		</td><td>	74,99</td></tr>
				<tr><td><b>Rocky Mountain Oyster with Mushroom Sauce and Sour Cream</b></td><td>	150/50	</td><td>49,99</td></tr>
				
				<tr><th colspan="3">Pork dishes </th></tr>
				
				<tr><td></td><td>Weight, g</td><td>Price, UAH</td></tr>        
				<tr><td><b>Bone-in pork chop  with mustard sauce</b></td><td>180/50/20</td><td>69,99</td></tr>
				<tr><td><b>Pork neck steak  with Dorblue sauce</b></td><td>	150/50/50		</td><td>69,99	</td></tr>
				<tr><td><b>Barbecue pork ribs                                           200/100                69,99</b></td><td>200/100			</td><td>	69,99</td></tr>
				<tr><td><b>Pork medallions with wild leek </b><br />(Served with Peanut sauce and garnish)</td><td>150/50/50</td><td>74,99</td></tr>
					
				<tr><th colspan="3">Garnish</th></tr>
				
				<tr><td></td><td>Weight, g</td><td>Price, UAH</td></tr>        
				<tr><td><b>Fries</b></td><td>150</td><td>16,99</td></tr>
				<tr><td><b>Mashed potatoes</b></td><td>	150		</td><td>16,99</td></tr>
				<tr><td><b>Home style fried potato with onion and salo (Bacon)</b></td><td>150			</td><td>	19,99</td></tr>
				<tr><td><b>Country style potato, baked with garlic</b></td><td>150	</td><td>19,99</td></tr>
				<tr><td><b>Rice with vegetables</b></td><td>150	</td><td>19,99</td></tr>
				
				<tr><th colspan="3">Dessert</th></tr>
				
				<tr><td></td><td>Weight, g</td><td>Price, UAH</td></tr>        
				<tr><td><b>Warm chocolate cake with ice-cream</b></td><td>150	</td><td>34,99</td></tr>
				<tr><td><b>Tiramisù	</b></td><td>	120			</td><td>34,99</td></tr>
				<tr><td><b>Cheese cake</b></td><td>120		</td><td>	34,99</td></tr>
				
				<tr><th colspan="3">Popular Mojito</th></tr>
				
				<tr><td></td><td>Weight, g</td><td>Price, UAH</td></tr>        
				<tr><td colspan="2"><b>Mojito</b> (Lime, fresh mint leaves, cane sugar, Rum, Mint Liqueur)</td><td>50,00</td></tr>
				<tr><td colspan="2"><b>Cuban Mojito</b>(Cuban Rum, Lemon juice, mint, sugar, club soda, ice-cubes)</td><td>50,00</td></tr>
				<tr><td colspan="2"><b>Frozen Mojito  </b>(Cuban Rum, lemon juice, mint, cane sugar, club soda)</td><td>50,00</td></tr>
				<tr><td colspan="2"><b>Cobbler Mojito </b>(Cuban Rum, lemon juice, kiwi, apple, cranberry, orange)</td><td>55,00</td></tr>
				<tr><td colspan="2"><b>Raspberry Mojito </b>( Lime, fresh mint leaves, cane sugar, Rum, fresh strawberry, club soda)</td><td>55,00</td></tr>
				<tr><td colspan="2"><b>Kiwi Mojito </b>(Cuban Rum, lemon juice, fresh mint leaves, fresh kiwi)</td><td>58,00</td></tr>
				<tr><td colspan="2"><b>Club Mojito </b>(Lime, fresh mint leaves, cane sugar,  Mint Liqueur, Rum, Sprite)</td><td>65,00</td></tr>
				<tr><td colspan="2"><b>Green Apple Mojito  </b>(Lime, fresh mint leaves, honey, fresh apple, apple-flavoured liqueur, Rum, Sprite)</td><td>60,00</td></tr>
				<tr><td colspan="2"><b>Mint Julep </b>(fresh mint leaves, cane sugar, Jim Beam, Sprite)</td><td>45,00</td></tr>
				<tr><td colspan="2"><b>Legalito </b>(Legalize, lemon juice, cane sugar, mint, Sprite, lime)</td><td>45,00</td></tr>
				
				<tr><th colspan="3">Non-alcoholic cocktails</th></tr>
				
				<tr><td></td><td>Weight, g</td><td>Price, UAH</td></tr>        
				<tr><td colspan="2"><b>Mojito n\a</b>(Lime, mint, cane sugar, Sprite)</td><td>40,00</td></tr>
				<tr><td colspan="2"><b>Cuban Mojito n\a</b>(Lemon juice, mint, sugar, club Sprite, ice-cubes)</td><td>35,00</td></tr>
				<tr><td colspan="2"><b>Frozen Mojito n\a </b>(Lemon juice, mint, cane sugar,  club soda )</td><td>40,00</td></tr>
				<tr><td colspan="2"><b>Kiwi Mojito n\a  </b>(Lemon juice, mint, honey, club soda, fresh kiwi)</td><td>50,00</td></tr>
				<tr><td colspan="2"><b>Energy Mojito n\a </b>(Lemon juice, mint, cane sugar, Red Bull)</td><td>55,00</td></tr>
			
				</table>           
					</div>    
					</div>
					</div>
				<div class="footer"></div>
				
			</div>
		</div>
	</div>
</div>
<?php
}
else
   if ($_GET['pm'] == 3)
   {
?>
<div class="catalogue_item_cont_m"> 
<div id="container_all">
<div id="container_in">
<div id="cont1">
	<div id="cont2">

        <h1>Mojito club is a club heart of Donetsk!</h1>
        <div class="header"></div>
        <div class="clearer"></div>
        
        <div class="center">
        <div class="menu">
        	<a href="http://eurodonetsk.com/index.php?business_full=407&pm=1">Main</a>
            <a href="http://eurodonetsk.com/index.php?business_full=407&pm=2">Menu</a>
            <a href="http://eurodonetsk.com/index.php?business_full=407&pm=3">Contacts</a>
        </div>
        
        <div class="text_box">
        	<h2>the cuisine and drinks at Mojito club<br/> deserve high attention</h2>
            
<p style="text-align:center;">Address: 125a, Artema Street, Donetsk city</p>

<p style="text-align:center;">Working hours: from 11 AM till 12 PM<br/>
Weekends: till 1 PM</p>

<p style="text-align:center;">Tel. (062) 305-50-05, (099) 503 46 49.</p> 
<div class="clearer"></div>

			<div id="div_st">
        <script src="http://api-maps.yandex.ru/1.1/index.xml?key=AAmDzUsBAAAARkVWCAIAXzMCgKN58_MQUqB134Sdp-unCH0AAAAAAAAAAACbJlz2mcKc4anRgbxx6LBZ5BHPyg==" type="text/javascript"></script>
    <script type="text/javascript">
        window.onload = function () {
            var map = new YMaps.Map(document.getElementById("YMapsID"));
            map.setCenter(new YMaps.GeoPoint(37.804799,48.006815), 16);
			
            var content = document.createElement('span');
            content.innerHTML = "Restaurant «Mojito club»";
            map.openBalloon(new YMaps.GeoPoint(37.804799,48.006815), content);

            map.addControl(new YMaps.ToolBar());
            map.addControl(new YMaps.Zoom());
            map.addControl(new YMaps.MiniMap());
            map.addControl(new YMaps.ScaleLine());
        }
    </script>


	 <div id="YMapsID" style="width:90%; height:450px; position:relative; float:left; top:20px; left:40px; z-index:20; margin-bottom:40px;"></div>
   </div>

<div class="clearer"></div>   
       <div id="same_img" style="position:relative; float:left; left:74%; bottom:10px;"><img align="right" src="../root/msite/mohito/imgs/mite.png" /></div>

        </div>    
        </div>
      </div>
        <div class="footer"></div> 
		
	</div>
</div>
</div>
</div>
<?php
   } 
?>



<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="index.php?section_id=32&amp;business=1">Категория:</a></div>
</div>
<div class="catalogue_item_cont">
<a href="index.php?section_id=2&amp;business=1">бизнес</a>
 / 
<a href="index.php?section_id=32&amp;business=1">предприятия</a>
 / 
<a href="index.php?section_id=389&amp;business=2">отдых и развлечения</a>
 / 
<a href="index.php?section_id=390&amp;business=2">кафе и рестораны</a>
</div>


<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="">Фотогалегея:</a></div>
</div>
<div class="catalogue_item_cont">
</div>
<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="">Контактная информация:</a></div>
</div>
 <div class="catalogue_item_cont">
 		 <table width="100%">
			<tbody>
 			<tr>
			<!--	<td><img class="main_sec_image" src="" width="60" height="60" border="0" alt="" /></td>-->
				<td>Адрес:</td>
				<td>Телефон:</td>
				<td>Факс:</td>
				<td>E-mail:</td>
				<td>Веб-сайт:</td>
			</tr>
			<tr>
				<td>125a, Artema Street<br /> Donetsk city</td>
				<td>(062) 305-50-05, (099) 503 46 49.</td>
				<td></td>
				<td></td>
				<td></td>

			</tr>
			</tbody> 
		 </table> 		
	 </div>
</div> 
