<div class="catalogue_item_c">

<style>



<!--

.folding{cursor:hand;font-weight:bold}

-->



.catalogue_item_cont p {

color:#000000;

text-align:justify;

text-indent:0px;

line-height:20px;

margin:0px;

}



.catalogue_item_cont_m {

background-color:#FFFFFF;

border:1px solid lightgray;

color:#000000;

margin:0;

margin:15px 10px 10px;

width:980px;

}



.catalogue_item_cont {

background-color:#ffffff;

border-top:1px solid lightgray;

margin:0 0 7px 10px;

width:980px;

color:#000000;

}

.catalogue_item_c {

background-color:#F3F3F3;

}



.catalogue_item_cont a {

color:#000000;

}



.catalogue_item_cont a:hover {

color:#000000;

text-decoration:underline;

}



.catalogue_item_mp_a {

left:3px;

position:relative;

}



#mm_menu {position:relative;left:610px;width:225px;text-align:center;} 



#div_st {padding:0 0px;position:relative;height:955px;}



@media all and (-webkit-min-device-pixel-ratio:10000),

not all and (-webkit-min-device-pixel-ratio:0) {

 #div_st {height:955px;}

}

#div_st2 {padding:0 0px;position:relative;height:6750px;}



@media all and (-webkit-min-device-pixel-ratio:10000),

not all and (-webkit-min-device-pixel-ratio:0) {

 #div_st2 {height:6750px;}

}

#div_st3 {padding:0 0px;position:relative;height:800px;}



@media all and (-webkit-min-device-pixel-ratio:10000),

not all and (-webkit-min-device-pixel-ratio:0) {

 #div_st3 {height:869px;}

}



div {

	display:block;

}



.sequ_container {

	width:100%;

	height:100%;

	margin:0px;

	padding:0px;

}



.background_div {

	width:980px;

	height:950px;

	background-image:url('../root/msite/coffee/background.png');

}



.logo {

	position:absolute;

	float:right;

	right:80px;

	top:70px;

	background-image:url('../root/msite/coffee/logo.png');

	background-repeat:no-repeat;

	width:335px;

	height:168px;

}



.girl {

	position:absolute;

	float:right;

	right:47px;

	top:685px;

	background-image:url('../root/msite/coffee/girl.png');

	width:363px;

	height:201px;

}



.text_r {

	position:relative;

	float:right;

	width:390px;

	right:45px;

	top:265px;

}



#p_adv {

	font-family:Adventure;

	font:Adventure;	

	font-size:10pt;

	font-weight:bold;

	letter-spacing:1px;

	text-align:right;

	color:#775e4b;

}



.cup {

	position:absolute;

	float:left;

	left:10px;

	top:10px;

	background-image:url('../root/msite/coffee/cup.png');

	width:285px;

	height:236px;

}



@font-face {

	font-family:Adventure;

	src:url(http://www.eurodonetsk.com/public_html/root/msite/coffee/adventure_font.ttf);

}



.sil {

	position:relative;

	float:left;

	width:250px;

	left:30px;

	top:400px;

	font-family:Adventure;

	src:url(http://www.eurodonetsk.com/public_html/root/msite/coffee/adventure_font.ttf);

	font:Adventure;	

	font-size:16pt;

	font-weight:bold;

	font-style:bold;

	letter-spacing:1px;

	color:#775e4b;

}



.mid_pho {

	position:absolute;

	float:left;

	left:285px;

	top:120px;

	background-image:url('../root/msite/coffee/mid_pho.png');

	width:276px;

	height:760px;

}



.girl2 {

	position:absolute;

	float:right;

	right:50px;

	top:6485px;

	background-image:url('../root/msite/coffee/girl.png');

	width:363px;

	height:201px;

}



.background_div2 {

	position:relative;

	float:left;

	display:block;

	width:980px;

	height:6750px;

	background-image:url('../root/msite/coffee/menu_bg.png');

}



.menu {

	position:relative;

	float:right;

	width:540px;

	right:45px;

	top:265px;

	font-family:Adventure;

	src:url(http://www.eurodonetsk.com/public_html/root/msite/coffee/adventure_font.ttf);

	font:Adventure;	

	font-size:16pt;

	font-weight:bold;

	font-style:bold;

	letter-spacing:1px;

	color:#775e4b;

}



.tab {

	font-size:12pt;

	text-align:left;

}



.menu_2 {

	position:relative;

	float:right;

	width:594px;

	right:45px;

	top:265px;

	font-family:Adventure;

	src:url(http://www.eurodonetsk.com/public_html/root/msite/coffee/adventure_font.ttf);

	font:Adventure;	

	font-size:16pt;

	font-weight:bold;

	font-style:bold;

	letter-spacing:1px;

	color:#775e4b;

}

*{padding:0; margin:0}

#main_miradent {	width:980px;
					margin:10px auto 10px auto;
					background-color:#f1f1f1;
					border-bottom:5px solid #f1f1f1;
				}
#menu_miradent {	
					margin:43px 0 0 0;
					height:50px;		
				}		
#menu_miradent ul { list-style:none;}
#menu_miradent li { float:left; margin:2px 1px 0 1px; height:50px; }
#menu_miradent span {text-align:center; font-size:16px;}
#menu_miradent a { 
			color:#e0532e; 
			text-decoration:none; 
			font-size:18px; 
			background-image: url(../root/msite/miradent/button.png); 
			display:block; 
			height:50px;
			width:90px; 
			text-align:center; 
			}			
#menu_miradent a:hover { 
				color:#e0532e; 
				text-decoration:none; 
				font-size:18px; 
				background-image: url(../root/msite/miradent/button_hover.png); 
				display:block; 
				height:50px; 
				text-align:center;
				width:90px; 
				}
#mir_miradent a { 
			color:#e0532e; 
			text-decoration:none; 
			font-size:18px; 
			background-image: url(../root/msite/miradent/button.png); background-repeat:no-repeat;
			display:block; 
			height:50px;
			width:140px; 
			text-align:center; 
			padding:15px 0 5px 0;
			}
			
#mir_miradent a:hover 	{ 
				color:#e0532e; 
				text-decoration:none; 
				font-size:18px; 
				background-image: url(../root/msite/miradent/button_hover.png);  background-repeat:no-repeat;
				display:block; 
				height:50px; 
				text-align:center;
				width:140px; 
				padding:15px 0 5px 0;
				}



#blic_miradent a { 
			color:#e0532e; 
			text-decoration:none; 
			font-size:18px; 
			background-image: url(../root/msite/miradent/button.png); background-repeat:no-repeat;
			display:block; 
			height:50px;
			width:140px; 
			text-align:center; 
			padding:5px 0 5px 0;
			}
#blic_miradent a:hover 	{ 
				color:#e0532e; 
				text-decoration:none; 
				font-size:18px; 
				background-image: url(../root/msite/miradent/button_hover.png);  	background-repeat:no-repeat;
				display:block; 
				height:50px; 
				text-align:center;
				width:140px; 
				padding:5px 0 5px 0;
				}
			
			
#link_r_miradent li { float:left; margin:2px 1px 0 1px; height:50px; width:120px;}

#link_r_miradent a { 
			color:#e0532e; 
			text-decoration:none; 
			font-size:18px; 
			background-image: url(../root/msite/miradent/buttonkont.png); 
			display:block; 
			height:50px; 
			text-align:center; 
			width:120px;
			filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src="./file's/buttonkont.png", sizingMethod='crop');//background:;
			}
			
#link_r_miradent a:hover { 
			color:#e0532e; 
			text-decoration:none; 
			font-size:18px; 
			background-image: url(../root/msite/miradent/buttonkont_hover.png); 
			display:block; 
			height:50px;
			width:120px; 
			text-align:center; 
			filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src="./file's/buttonkont_hover.png", sizingMethod='crop');//background:; 
			}


										/* --LEFT BUTTOM--*/

#tab_content_miradent {
		margin:0 auto 10px auto;
		background-color:#FFF;
		font-family:Georgia, "Times New Roman", Times, serif;
	}
	
#left_content_miradent {
		width:260px;
		vertical-align:top;
	}
		
#left_content_miradent span {
			text-align:center;  
			}
#left_content_miradent a { 
			color:#e0532e; 
			text-decoration:none; 
			font-size:22px; 
			background-image: url(../root/msite/miradent/oval.jpg); 
			background-repeat:no-repeat; 
			display:block; 
			height:250px; 
			width:250; 
			text-align:center; 
			border:none;
			padding:15px 0 0 0;
			filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src="./file's/zub.png", sizingMethod='crop');//background:;
			}	
	
#left_content_miradent a:hover { 
				color:#e0532e; 
				text-decoration:none; 
				font-size:20px;
				font-style:italic;
				font-weight:bold; 
				background-image: url(../root/msite/miradent/oval_hover.jpg); 
				background-repeat:no-repeat; 
				display:block; 
				height:250px; 
				width:250; 
				text-align:center;
				border:none; 
				filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src="./file's/zub_hover.png", sizingMethod='crop');//background:;
				}
#left_content_miradent a:active { 
				color:#000; 
				text-decoration:none; 
				font-size:20px;
				font-style:italic;
				font-weight:bold; 
				background-image: url(../root/msite/miradent/oval_hover.jpg); 
				background-repeat:no-repeat; 
				display:block; 
				height:250px; 
				width:250; 
				text-align:center;
				border:none; 
				filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src="./file's/zub_hover.png", sizingMethod='crop');//background:;
				}


												/* --TEXT_CONTENT--*/
												
#text_content_miradent p {	
			padding:15px 25px 15px 5px;
			font-size:20px;
			font-family:Times New Roman;
			text-align: justify;
			}
#text_content_miradent hr{ width:85%; color:#006; margin:5px auto 5px auto;}			
#text_content_miradent span { font-size:16px; font-style:italic; font-weight:900; padding:5px 0 0 5px;}
#text_content_miradent h3 { font-size:22px;
			font-family:Helvetica;
			padding:50px 0 0 5px;
			text-align:center;
			text-decoration:underline;
     		}

#text_content_miradent h1 {font-size:20px; margin:25px 0 10px 0; text-align:center;}
#text_content_miradent h6 {font-size:18px; text-align:center; font-weight:400; color:#0C0;}
#text_content_miradent h4 {font-size:18px; text-align:center; font-weight:bold; color:#0C0;}
#text_content_miradent h2 {	color: #00C;
			text-align:left;
			font-size:16px;
			padding:5px 0  3px 5px;
			}
#text_content_miradent h5 {font-size:16px; font-style:italic; font-weight:900; padding:5px 0 0 5px;}			
#text_content_miradent ul  {padding:0 0 0 20px;}				
#text_content_miradent li {font-size:16px; font-family:"Myriad Pro"; padding:5px 25px 5px 10px;}
#text_content_miradent a {text-decoration:none; padding:5px 10px 15px 15px; color:#006;}
#text_content_miradent a:hover {text-decoration:underline;} 

#est_rev_content_miradent {display:none;}
#otbel_content_miradent {display:none;}
#ortoped_content_miradent {display:none;}

#price_miradent {
					width:90%;
					margin:30px auto 40px auto;
					color:#003;
					font-family:Arial, Helvetica, sans-serif;
				 }
#price_miradent h3 {
					color:#0C0; 
					font-size:16px; 
					text-align:left; 
					padding:0; 
					text-decoration:none;
					}
#price_miradent h1 {
					color:#0C0; 
					font-size:17px; 
					text-align:center; 
					padding:5px 0;
					}


</style>

<?php

if ($_GET['pm'] == 1) 

{

?>

<script language="javascript" type="text/javascript">
	function show_hide(objectID){
		var object=document.getElementById(objectID);
		if (object.style.display=='none')
			object.style.display='block';
			else
			object.style.display='none';
			return;
	}
</script>

<div class="catalogue_item_cont_m"> 

	<div id="main_miradent">
				<table background="../root/msite/miradent/upper.jpg" height="380px" width="980px" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td style="padding:35px 0 0 40px;" height="125px"><a href="index.html"><img src="../root/msite/miradent/logo.png" border="0" align="left" alt="Стоматология Мирадент (Донецк, Укрина)"/></a></td>
  </tr>
   <tr>
    <td>
    	<p align="left" style="font-size:20px; padding:5px 0 0 10px;font-weight:600; font-family:Times New Roman;">г. Донецк, пр-т Мира, 2</p> 
		<p align="left" style="font-size:20px; padding:5px 0 0 10px; font-weight:600; font-family:Times New Roman;">тел: 062 381-18-24; моб: 050 696-47-70</p>
		<p align="left" style="font-size:20px; padding:5px 0 0 10px;font-weight:600; font-family:Times New Roman;">МЦ «Блиц»: г. Донецк ул. Раздольная, 13</p>
		<p align="left" style="font-size:20px; padding:5px 0 0 10px; font-weight:600; font-family:Times New Roman;">тел: 062 389-33-04; моб: 050 057-43-78</p>      </td>
  </tr>
  <tr>
    <td height="50px">
    			<div id="menu_miradent">
                		<ul>
                        	<li id="mir_miradent"><a href="index.php?business_full=490&pm=2"><span style="text-align:center; font-size:18px; font-family:Times New Roman;">МИРАДЕНТ</span></a></li>
                            <li id="blic_miradent"><a href="index.php?business_full=490&pm=1"><span style="text-align:center; font-size:18px; font-family:Times New Roman;">Мед. центр</span> <span style="text-align:center; font-size:18px; font-family:Times New Roman;">БЛИЦ</span></a></li>
                            <li><a href="index.php?business_full=490&pm=3"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;">О нас</span></a></li>
                            <li><a href="index.php?business_full=490&pm=4"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;">Цены</span></a></li>
                            <li><a href="index.php?business_full=490&pm=5"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;">Вакансии</span></a></li>
                            <li id="link_r_miradent"><a href="index.php?business_full=490&pm=6"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;">Контакты</span></a></li>
                        </ul>
                </div>       
    </td>
  </tr>
</table>
<table id="tab_content_miradent" width="970px" align="center" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td id="left_content_miradent">
     <br />
      <a href="javascript:show_hide('est_rev_content_miradent')"><br /><br /><br /><span>Эстетическая</span><br /><span>Реставрация</span></a>
        	  	<br />
      <a href="javascript:show_hide('otbel_content_miradent')"><br /><br /><br /><span>Отбеливание</span><br /><span>системой</span><br /><span>"Beyond"</span></a> 
        	    <br />
   	  <a href="javascript:show_hide('ortoped_content_miradent')"><br /><br /><br /><span>Эндодонтическое</span><br /><span>лечение</span></a>
    </td>
    <td valign="top">
      <div id="text_content_miradent">
      <div id="est_rev_content_miradent">
     <h3>ЭСТЕТИЧЕСКАЯ РЕСТАВРАЦИЯ ЗУБОВ</h3>
    <p>Высокоразвитая цивилизация ставит перед стоматологом требования не только борьбы с болью и восстановления жевательной функции. Не менее важно в настоящее время сохранение и воссоздание неповторимой красоты здоровых зубов.</p>
   <p>Эту роль выполняет <strong>эстетическая реставрация</strong> – восстановление изначального цвета, формы и размера зуба.</p> 
   <p>Материалы для реставрации по твердости и прочности аналогичны твердым тканям зуба. Они разрабатываются в разных оттенках, что делает возможным воспроизвести в эстетической конструкции цветовые переливы природного живого зуба.</p>
   <p>Композиционные фотополимерные материалы послойно наносятся на подготовленный зуб в соответствии с цветом и структурой утраченных зубных тканей и отверждаются специальной лампой.</p>
   <p><span>Безболезненность, надежность, красота и естественность – вот цели профессионалов эстетической стоматологии!</span></p>

<h2>Эстетическая реставрация зубов : технологии.</h2>
<p>В  современном мире  космических технологий, высокой моды, открытых информационных границ безукоризненная улыбка открывает человеку безграничные возможности в личном общении и карьерном росте. 
Зубы человека отличаются сложностью и разнообразием формы, неповторимой структурой, богатством передачи цвета, блеском, прозрачностью. Все эти качества стоматолог стремится воссоздать в художественной реставрации, чтобы придать Вашей улыбке красоту и естественность.</p>
<p>Современные высокооснащенные лаборатории ведущих мировых фирм стоматологической продукции постоянно работают над созданием и усовершенствованием материалов для реставрации зубов. Многочисленный арсенал этих средств составляют фотополимерные материалы для восстановления жевательных групп зубов (в том числе, армированные - упроченные), жидкотекучие фотополимеры для плотной адаптации к поверхности, универсальные – для пломбирования любых зубных дефектов, материалы для художественной реставрации. Последние соответствуют тканям зуба по прочности и твердости, позволяют точно передать структурные цветовые переходы, опалесценцию и флюоресценцию зубной поверхности.</p>
<p>Обработка зуба под фотополимерные реставрации производится максимально щадяще. Сцепление материала с поверхностью осуществляется за счет микропроникновения связывающего агента (бонда) в межкристаллические пространства и обеспечивает так называемое интимное прикрепление.</p>
 <p>Если зуб значительно разрушен, его укрепляют по показаниям анкерным или световолоконным штифтом.
Фотоматериал послойно накладывается на зуб в соответствии со структурой утраченных зубных тканей, повторяя их цвет. Каждый слой отдельно отверждается  светом специальной лампы. Это делает конструкцию еще более прочной. Моделируя поверхность зуба, стоматолог повторяет бугорки, бороздки и другие элементы, характерные для строения здоровых зубов конкретного человека. Готовая реставрация корректируется по прикусу и полируется до блеска.</p> 
<p><strong>Художественная реставрация зубов</strong> подарит Вам здоровую улыбку и уверенность в собственной неповторимости.</p>
 <hr />
	</div>
    
  <div id="otbel_content_miradent">
	<h3>ОТБЕЛИВАНИЕ ЗУБОВ</h3>
    <p>Большинство людей в современном мире придает значение здоровью зубов и их внешнему виду! Сделайте свою улыбку неотразимой! Если Вы хотите иметь белые зубы и сногсшибательную улыбку, тогда <strong>система Бейонд</strong> – Ваш верный выбор. Ваша улыбка станет сияющей и белоснежной всего за 30 минут! Отбеливающая система обеспечивает максимально возможный эффект даже если ваши зубы потемнели от курения, употребления напитков, содержащих красители, утратили природную белизну вследствие применения лекарственных препаратов, таких как тетрациклин или покрылись пятнами из-за употребления антибиотиков, избытка фтора.</p>
<p><strong>Система</strong> «<strong>Beyond Whitening Accelerator</strong>» - лучший выбор для достижения белоснежной и здоровой улыбки быстро и эффективно. Всего лишь за один курс отбеливания убираются пятна, которые образовывались годами, цвет зубов улучшается в среднем на 10-14 оттенков. Степень улучшения цвета зубов пациент выбирает по своему желанию и согласно рекомендациям стоматолога. Инновационная программа акселератора позволяет подобрать каждому пациенту индивидуальный режим интенсивности отбеливания.</p>
<p>Процедура отбеливания по системе <strong>Бейонд</strong> заключается в нанесении специального отбеливающего геля на поверхность зубов, а затем его активации с помощью холодного света лампы «<strong>Beyond Whitening Accelerator</strong>». Отбеливающий гель основан на 35% перекиси водорода и других компонентах, которые улучшают результат, предупреждают возникновение чувствительности и укрепляют зубную эмаль.</p> 
<p>Процесс отбеливания зубов возможен благодаря способности пероксида водорода свободно проникать сквозь эмаль и распространяться по всем частям зуба. Пероксиды под воздействием активатора (акселератора) распадаются на кислородные радикалы, которые затем мигрируют между эмалевыми  призмами, разлагая любые окрашенные молекулы, структура зуба при этом не затрагивается. Эмаль, дентин, связующие материалы и пломбы не повреждаются отбеливающими веществами.</p>
<p><strong>Преимущества отбеливающей системы</strong> <strong>Бейонд</strong> над всеми существующих на мировом рынке системами отбеливания:</p>
		<ul>
        	<li>Комфортность и удобство: не требует никаких предварительных процедур, за исключением профессиональной гигиенической чистки; одномоментное отбеливание 16-20 зубов в течение 30 минут. Кратковременность процедуры исключает возникновение раздражения десен и околозубных тканей. Акселератор отбеливания работает в режиме низкой температуры, что снижает риск возникновения чувствительности зубов. </li>
            <li>Безопасность: акселератор отбеливания – мощная галогеновая лампа, излучающая холодный голубой свет, который фильтруется 12 000 световодами и системой оптических линз. Вредное ультрафиолетовое и инфракрасное излучение отсеивается, не достигая поверхности зубов. Излучение холодного света снижает уровень вредных бактерий в полости рта эффективнее дезинфицирующего ополаскивателя.</li>
        </ul>    
<p>При соблюдении всех рекомендаций по уходу за отбеленными зубами и использовании средств для поддержания эффекта в домашних условиях ваши зубы будут выглядеть прекрасно как после самой процедуры, так и на протяжении нескольких лет!</p>
<p>
<span><strong>Beyond Power Whitening System</strong> – самая мощная система косметического <strong>отбеливания зубов</strong> в настоящее время, это передовая технология, гарантирующая безопасность, комфорт и результативность. Подробнее о системе отбеливания на сайте </span><a href="http://beyonddent.com.ua">www.beyonddent.com.ua.</a></p>
<h2>ЗУБНЫЕ УКРАШЕНИЯ.</h2>
<p>В настоящее время широкой популярностью у людей самых разных возрастов пользуются<strong> зубные украшения</strong> – <strong>скайсы</strong>. Это могут быть простые стразы, кристаллы Сваровски или алмазы в золотой оправе. Разнообразие их формы и цвета дает возможность подобрать  для Вас нечто особенное.</p> 
<p>Украшения крепятся  на зубы без препаровки, т.е не нарушая структуру эмали, при помощи специального стоматологического фиксирующего материала . Снять украшение можно в любой момент, после чего зубы имеют свой первоначальный вид.</p>
<p>Скайсы способны подчеркнуть Вашу индивидуальность, сделать улыбку блистательной и неотразимой!</p>
 <hr />
	</div>    


 <div id="ortoped_content_miradent">

<h3>ЭНДОДОНТИЧЕСКОЕ ЛЕЧЕНИЕ</h3>
<p>Если вовремя не вылечить кариес, болезнь может распространиться на пульпу зуба (внутризубной нерв) и далее – на связочный аппарат зуба и костную ткань челюсти. Как следствие – сильные боли, отек, воспаление и удаление зуба.</p>  
<p><strong>Эндодонтическое лечение</strong> – это комплекс мероприятий, направленных на борьбу с инфекцией внутри зуба и возвращение зубу возможности нормально функционировать. <strong>Эндодонтия</strong> – одна из важнейших областей терапевтической стоматологии.  Она требует от специалиста четкого знания сложной анатомии корневых каналов и строгого соблюдения последовательности определенных манипуляций в процессе лечения.</p>
<p>Врач-эндодонт выполняет ряд задач:</p>
	<ul>
    	<li>обеспечение доступа к корневым каналам,</li>
        <li>прохождение канала до верхушки корня,</li>
        <li>удаление из канала инфицированных и мертвых тканей,</li>
        <li>придание каналу формы, необходимой для правильного пломбирования,</li>
        <li>медикаментозная обработка канала с целью окончательного удаления болезнетворных бактерий,</li>
        <li>герметичное запечатывание (пломбирование) канала специальными наполнителями.</li>
	</ul>
	
    <p>В сложных и запущенных случаях не удается провести лечение корней в одно посещение: бывает необходимо оставление открытого зуба, наложение лекарственного средства под временную пломбу либо временное пломбирование канала лечебной пастой.</p>
<p>Каждый этап эндодонтического лечения выполняется с применением новейшего оборудования, инструментов, материалов.</p> 
<p>Современная стоматология мирового уровня МИРАДЕНТ располагает значительным арсеналом средств и методов качественного и надежного лечения корней. Правильность лечения контролируется и подтверждается с помощью специального прибора – апекслокатора и рентгеновских снимков, выполняемых на высокотехнологичной рентгенустановке.</p>
<p>Метод подготовки и заполнения корневых каналов выбирается в зависимости от их формы и строения, диагноза и течения заболевания, а также от способа последующего восстановления зуба в целом.</p>

<p><strong>Стоматология МИРАДЕНТ</strong> применяем самые прогрессивные технологии <strong>обработки и пломбирования каналов</strong>, гарантирующие продление жизни и здоровья зубов на долгий срок, а также возможность их использования в различных ортопедических конструкциях.</p>

<h2>Обработка корневых каналов : технологии.</h2>
<p>Кариес зубов, распространяясь, вызывает воспаление пульпы зуба и околокорневой костной ткани. Современная стоматология позволяет спасти большинство таких зубов, не допустить их удаления.</p>
<p>Лечение в таких случаях заключается в специальной обработке и герметичном <strong>пломбировании каналов корня зуба</strong>. Обработка каналов направлена на удаление из канала инфицированных тканей и придание каналу формы, необходимой для проникновения лекарства и правильного пломбирования.</p>
<p>Каналы имеют сложную форму, ответвления, часто встречаются тонкие, изогнутые, труднопроходимые каналы. Для их обработки используются специальные ручные и вращающиеся инструменты, позволяющие убрать из просвета воспаленные ткани, сделать стенки гладкими. В процессе обработки канал промывается специальными антисептическими растворами, нейтрализующими болезнетворные бактерии.</p>
<p>На протяжении всей работы стоматолог координирует свои действия по показаниям специального прибора – апекслокатора, при необходимости проводит дополнительный контроль с помощью рентгеновского снимка.</p>

<p>Правильная  предварительная обработка обеспечивает последующее качественное пломбирование канала и сохранение  зуба на длительный срок.</p>

<h2>Повторное эндодонтическое лечение : технологии.</h2>
<p>Нередко пациенты обращаются к стоматологу по поводу зубов, которые уже были ранее  пролечены эндодонтически в  другой клинике. Такие зубы нуждаются в повторном эндодонтическом лечении, и чаще всего их удается спасти.</p>
<p>Перед тем как поступить к перелечиванию канала, специалист изучает рентгеновский снимок. <strong>Повторное эндодонтическое лечение</strong> заключается в удалении из канала старого пломбировочного материала, прохождение и формирование канала на всю длину, обработка лечебными дезинфицирующими растворами и плотное пломбирование канала до верхушки по одной из современных методик. </p>
<p>Способ повторного лечения зависит от того, какой пломбировочный материал находится в канале, от формы и проходимости канала.  Для удаления из канала старой пломбировочной массы используются специально разработанные вращающиеся никель-титановые инструменты. В сложных случаях, когда каналы были прежде заполнены цементом, применяется ультразвуковой аппарат с соответствующими насадками. Ультразвук дробит застывший цемент и способствует его выведению. Кроме того, он во много раз усиливает бактерицидное  действие дезинфицирующий средств, увеличивает шансы на успех в лечении. </p>
<p>Герметичное  заполнение подготовленного корневого канала с последующим восстановлением зуба фотополимерным материалом позволяет остановить воспалительные явления в костной ткани челюсти, предотвратить обострение процесса и удаление зуба.</p>

<h2>Пломбирование корневого канала : технологии.</h2>
<p><strong>Пломбирование каналов</strong> является логическим итогом <strong>эндодонтического лечения</strong>. Наиболее верный шанс клинического успеха достигается тогда, когда система корневых каналов полностью, со всей своей сложностью, будет запломбирована на своем полном апикальном и латеральном протяжении.</p>
<p>Большинство современных методик пломбирования заключаются в плотном закрытии канала гуттаперчей с использованием силера – наполнителя – лечебной пасты, застывающей в канале после пломбирования.  Речь идет о методах латеральной конденсации гуттаперчи, конусного штифта, центрированной и вертикальной конденсации горячей гуттаперчи. Эти методики отличаются по степени уплотнения и распространения, способу введения, сложности, необходимости специального оборудования и стоимости. </p>
<p>При латеральной конденсации в канал, заполненный силером, вводится основной гуттаперчевый штифт, плотно закрывающий верхушечное отверстие. Далее, он уплотняется специальным инструментом и вводится следующий один штифт. Процедура повторяется до тех пор, пока просвет канала, имеющий конусную форму, не будет заполнен на всем протяжении. </p>
<p>Если канал предварительно обработан и сформирован с помощью специальной системы вращающихся инструментов, имеется возможность заполнить его с помощью одного конусного гуттаперчевого штифта, точно соответствующего форме подготовленного канала. Штифт идеально запечатывает верхушечное отверстие и весь просвет канала, делает ненужным введение  и уплотнение множества дополнительных штифтов. Это значительно сокращает процедуру, не отражаясь на ее качестве.</p> 
<p>В настоящее время мало кто из стоматологов отрицает наличие микроканальцев и множественных ответвлений корневого канала, которые также нуждаются в пломбировании.  Именно поэтому разработаны методики  <strong>3-D (трехмерной)</strong> <strong>обтурации</strong>.</p>
<p>Техника обтурации центрированной конденсацией (термафил) действенно и эффективно продвигает пломбирующие материалы через систему корневого канала движением конденсирующего устройства (предварительно нагретого носителя) в центре термопластического материала, такого как гуттаперча. Пломбирующий материал, смазанный силером, смещается в сторону коронки, так как конденсирующее устройство движется к верхушке, создавая эффект тока материала на стенки основного канала. Это пломбирует боковые канальцы, дополнительные канальцы, бороздки, петли, ответвления и перешейкипо ходу инструмента. Для работы в этой технике дополнительно требуются гуттаперчевые обтураторы на носителе и специальное устройство для их разогрева.</p>
<p>Для техники постоянной волны (Є&Q+ Plus) выбирается электрически нагреваемый уплотнитель - плаггер (Sybron Endo), соответствующей  конусности. Стенки канала смазываются силером, подготовленный гуттаперчевый штифт вводится до верхушки. Излишки гуттаперчи специальным образом убираются , а плаггер уплотняет гуттаперчу до уровня 4мм от верхушечного отвертстия, обеспечивая максимальное проникновение материала во все ответвления и канальцы, герметизируя все возможные пути распространения бактерий. <strong>Пломбирование верхних 2\3 канала</strong> выполняется при помощи пистолета или новым, встроенным, машинным пресс-шприцем.</p>
<p>Раньше было сложно запломбировать систему корневого канала в трехмерном измерении. Сейчас  этот надежный метод, предполагающий наличие дополнительной дорогостоящей аппаратуры и грамотного специалиста, полностью оправдывает возложенные на него ожидания. Кроме гуттаперчи, <strong>для пломбирования каналов</strong> применяются недавно разработанные материалы (эпифания, резилон, ПроРут МТА), которые используются по показаниям в соответствующих техниках пломбирования и значительно расширяют возможности сохранения зубов, рекомендованных к удалению. </p>
<h2> Аппаратные методы диагностики</h2>
    <p>Для постановки точного диагноза и подтверждения качества лечения в стоматологической клинике МИРАДЕНТ проводятся рентгенологические исследования на современном оборудовании.</p>
<p>Стоматологические установки оснащены интраоральными камерами Vista Cam ведущего немецкого производителя – фирмы Durr Dental. 
Камера многократно увеличивает изображение и переводит его на плоский экран. Это позволяет стоматологу рассмотреть мельчайшие детали на рабочем поле, а также продемонстрировать пациенту элементы зубных отложений, скрытые кариозные полости, исходное состояние больного зуба, этапы и результат проведения реставрации.</p>
<p>С помощью интраоральной камеры можно получить фотоснимки зубов до и после стоматологических процедур.  
Использование интраоральной камеры повышает информированность пациента  о ходе проводимых лечебных действий,  позволяет пациенту чувствовать себя спокойнее и увереннее на приеме у стоматолога.</p>  
 <hr />      
</div>

    
      <p><strong>Кариес</strong> – патологический процесс постепенного разрушения твердых тканей зуба, который приводит к разрушению эмали и дентина. Начинается с растворения минеральных веществ зуба и приводит к образованию дефекта в виде кариозной полости. В зависимости от глубины и степени распространения поражения твердых тканей зуба, выделяют четыре стадии кариеса: </p>
<p>- начальный – кариозное пятно;</p>
<p>- поверхностный – нарушение эмали, небольшой дефект;</p>
<p>- средний – разрушение верхних твердых тканей зуба, с возникновением болевых ощущений;</p>
<p>- глубокий – разрушение глубоких слоев твердых тканей зуба, прилегающих к пульпе, и формирование обширной кариозной полости.</p>
<p>Если не обратиться к стоматологу на ранних стадиях, скорее всего кариес перейдет  в глубокий.  Лечение на этой стадии потребует уже более серьезного вмешательства.</p>
<p>Современные обезболивающие препараты, используемые в стоматологической клинике МИРАДЕНТ, делают процесс лечения совершенно безболезненным. Оттенки пломбировочных материалов подбираются под цвет зуба.</p>
<p>Так же <strong>заболевания эмали и дентина</strong> могут возникать под действием внешних агрессивных факторов или внутренних причин.  Основными из них являются : генетическая предрасположенность, воздействие экологических факторов, стрессы, системные заболевания организма,  недостаточная гигиена ротовой полости, потребление большого количества сахара, дефицит витаминов и минералов, отсутствие фтора в воде .</p>
</div>
    </td>
  </tr>
</table>

















</div>

</div> <!-- cat_ite_cont_m -->

<?php

}

else

   if ($_GET['pm'] == 2)

   {

?>

<script language="javascript" type="text/javascript">
	function show_hide(objectID){
		var object=document.getElementById(objectID);
		if (object.style.display=='none')
			object.style.display='block';
			else
			object.style.display='none';
			return;
	}
</script>

<div class="catalogue_item_cont_m"> 

	<div id="main_miradent">
				<table background="../root/msite/miradent/upper.jpg" height="380px" width="980px" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td style="padding:35px 0 0 40px;" height="125px"><a href="index.html"><img src="../root/msite/miradent/logo.png" border="0" align="left"/></a></td>
  </tr>
   <tr>
    <td>
    	<p align="left" style="font-size:20px; padding:5px 0 0 10px;font-weight:600; font-family:Times New Roman;">г. Донецк, пр-т Мира, 2</p> 
		<p align="left" style="font-size:20px; padding:5px 0 0 10px; font-weight:600; font-family:Times New Roman;">тел: 062 381-18-24; моб: 050 696-47-70</p>
		<p align="left" style="font-size:20px; padding:5px 0 0 10px;font-weight:600; font-family:Times New Roman;">МЦ «Блиц»: г. Донецк ул. Раздольная, 13</p>
		<p align="left" style="font-size:20px; padding:5px 0 0 10px; font-weight:600; font-family:Times New Roman;">тел: 062 389-33-04; моб: 050 057-43-78</p>      </td>
  </tr>
  <tr>
    <td height="50px">
    			<div id="menu_miradent">
                		<ul>
                        	<li id="mir_miradent"><a href="index.php?business_full=490&pm=2"><span style="text-align:center; font-size:18px; font-family:Times New Roman;">МИРАДЕНТ</span></a></li>
                            <li id="blic_miradent"><a href="index.php?business_full=490&pm=1"><span style="text-align:center; font-size:18px; font-family:Times New Roman;">Мед. центр</span> <span style="text-align:center; font-size:18px; font-family:Times New Roman;">БЛИЦ</span></a></li>
                            <li><a href="index.php?business_full=490&pm=3"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;">О нас</span></a></li>
                            <li><a href="index.php?business_full=490&pm=4"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;">Цены</span></a></li>
                            <li><a href="index.php?business_full=490&pm=5"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;">Вакансии</span></a></li>
                            <li id="link_r_miradent"><a href="index.php?business_full=490&pm=6"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;">Контакты</span></a></li>
                        </ul>
                </div>       
    </td>
  </tr>
</table>
<table id="tab_content_miradent" width="970px" align="center" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td id="left_content_miradent">
     <br />
      <a href="javascript:show_hide('est_rev_content_miradent')"><br /><br /><br /><span>Эстетическая</span><br /><span>Реставрация</span></a>
        	  	<br />
      <a href="javascript:show_hide('otbel_content_miradent')"><br /><br /><br /><span>Отбеливание</span><br /><span>системой</span><br /><span>"Beyond"</span></a> 
        	    <br />
   	  <a href="javascript:show_hide('ortoped_content_miradent')"><br /><br /><br /><span>Эндодонтическое</span><br /><span>лечение</span></a>
    </td>
    <td valign="top">
      <div id="text_content_miradent">
      <div id="est_rev_content_miradent">
    <h3>ЭСТЕТИЧЕСКАЯ РЕСТАВРАЦИЯ ЗУБОВ</h3>
    <p>Высокоразвитая цивилизация ставит перед стоматологом требования не только борьбы с болью и восстановления жевательной функции. Не менее важно в настоящее время сохранение и воссоздание неповторимой красоты здоровых зубов.</p>
   <p>Эту роль выполняет <strong>эстетическая реставрация</strong> – восстановление изначального цвета, формы и размера зуба.</p> 
   <p>Материалы для реставрации по твердости и прочности аналогичны твердым тканям зуба. Они разрабатываются в разных оттенках, что делает возможным воспроизвести в эстетической конструкции цветовые переливы природного живого зуба.</p>
   <p>Композиционные фотополимерные материалы послойно наносятся на подготовленный зуб в соответствии с цветом и структурой утраченных зубных тканей и отверждаются специальной лампой.</p>
   <p><span>Безболезненность, надежность, красота и естественность – вот цели профессионалов эстетической стоматологии!</span></p>

<h2>Эстетическая реставрация зубов : технологии.</h2>
<p>В  современном мире  космических технологий, высокой моды, открытых информационных границ безукоризненная улыбка открывает человеку безграничные возможности в личном общении и карьерном росте. 
Зубы человека отличаются сложностью и разнообразием формы, неповторимой структурой, богатством передачи цвета, блеском, прозрачностью. Все эти качества стоматолог стремится воссоздать в художественной реставрации, чтобы придать Вашей улыбке красоту и естественность.</p>
<p>Современные высокооснащенные лаборатории ведущих мировых фирм стоматологической продукции постоянно работают над созданием и усовершенствованием материалов для реставрации зубов. Многочисленный арсенал этих средств составляют фотополимерные материалы для восстановления жевательных групп зубов (в том числе, армированные - упроченные), жидкотекучие фотополимеры для плотной адаптации к поверхности, универсальные – для пломбирования любых зубных дефектов, материалы для художественной реставрации. Последние соответствуют тканям зуба по прочности и твердости, позволяют точно передать структурные цветовые переходы, опалесценцию и флюоресценцию зубной поверхности.</p>
<p>Обработка зуба под фотополимерные реставрации производится максимально щадяще. Сцепление материала с поверхностью осуществляется за счет микропроникновения связывающего агента (бонда) в межкристаллические пространства и обеспечивает так называемое интимное прикрепление.</p>
 <p>Если зуб значительно разрушен, его укрепляют по показаниям анкерным или световолоконным штифтом.
Фотоматериал послойно накладывается на зуб в соответствии со структурой утраченных зубных тканей, повторяя их цвет. Каждый слой отдельно отверждается  светом специальной лампы. Это делает конструкцию еще более прочной. Моделируя поверхность зуба, стоматолог повторяет бугорки, бороздки и другие элементы, характерные для строения здоровых зубов конкретного человека. Готовая реставрация корректируется по прикусу и полируется до блеска.</p> 
<p><strong>Художественная реставрация зубов</strong> подарит Вам здоровую улыбку и уверенность в собственной неповторимости.</p>
 <hr />
	</div>
    
  <div id="otbel_content_miradent">
	<h3>ОТБЕЛИВАНИЕ ЗУБОВ</h3>
    <p>Большинство людей в современном мире придает значение здоровью зубов и их внешнему виду! Сделайте свою улыбку неотразимой! Если Вы хотите иметь белые зубы и сногсшибательную улыбку, тогда <strong>система Бейонд</strong> – Ваш верный выбор. Ваша улыбка станет сияющей и белоснежной всего за 30 минут! Отбеливающая система обеспечивает максимально возможный эффект даже если ваши зубы потемнели от курения, употребления напитков, содержащих красители, утратили природную белизну вследствие применения лекарственных препаратов, таких как тетрациклин или покрылись пятнами из-за употребления антибиотиков, избытка фтора.</p>
<p><strong>Система</strong> «<strong>Beyond Whitening Accelerator</strong>» - лучший выбор для достижения белоснежной и здоровой улыбки быстро и эффективно. Всего лишь за один курс отбеливания убираются пятна, которые образовывались годами, цвет зубов улучшается в среднем на 10-14 оттенков. Степень улучшения цвета зубов пациент выбирает по своему желанию и согласно рекомендациям стоматолога. Инновационная программа акселератора позволяет подобрать каждому пациенту индивидуальный режим интенсивности отбеливания.</p>
<p>Процедура отбеливания по системе <strong>Бейонд</strong> заключается в нанесении специального отбеливающего геля на поверхность зубов, а затем его активации с помощью холодного света лампы «<strong>Beyond Whitening Accelerator</strong>». Отбеливающий гель основан на 35% перекиси водорода и других компонентах, которые улучшают результат, предупреждают возникновение чувствительности и укрепляют зубную эмаль.</p> 
<p>Процесс отбеливания зубов возможен благодаря способности пероксида водорода свободно проникать сквозь эмаль и распространяться по всем частям зуба. Пероксиды под воздействием активатора (акселератора) распадаются на кислородные радикалы, которые затем мигрируют между эмалевыми  призмами, разлагая любые окрашенные молекулы, структура зуба при этом не затрагивается. Эмаль, дентин, связующие материалы и пломбы не повреждаются отбеливающими веществами.</p>
<p><strong>Преимущества отбеливающей системы</strong> <strong>Бейонд</strong> над всеми существующих на мировом рынке системами отбеливания:</p>
		<ul>
        	<li>Комфортность и удобство: не требует никаких предварительных процедур, за исключением профессиональной гигиенической чистки; одномоментное отбеливание 16-20 зубов в течение 30 минут. Кратковременность процедуры исключает возникновение раздражения десен и околозубных тканей. Акселератор отбеливания работает в режиме низкой температуры, что снижает риск возникновения чувствительности зубов. </li>
            <li>Безопасность: акселератор отбеливания – мощная галогеновая лампа, излучающая холодный голубой свет, который фильтруется 12 000 световодами и системой оптических линз. Вредное ультрафиолетовое и инфракрасное излучение отсеивается, не достигая поверхности зубов. Излучение холодного света снижает уровень вредных бактерий в полости рта эффективнее дезинфицирующего ополаскивателя.</li>
        </ul>    
<p>При соблюдении всех рекомендаций по уходу за отбеленными зубами и использовании средств для поддержания эффекта в домашних условиях ваши зубы будут выглядеть прекрасно как после самой процедуры, так и на протяжении нескольких лет!</p>
<p>
<span><strong>Beyond Power Whitening System</strong> – самая мощная система косметического <strong>отбеливания зубов</strong> в настоящее время, это передовая технология, гарантирующая безопасность, комфорт и результативность. Подробнее о системе отбеливания на сайте </span><a href="http://beyonddent.com.ua">www.beyonddent.com.ua.</a></p>
<h2>ЗУБНЫЕ УКРАШЕНИЯ.</h2>
<p>В настоящее время широкой популярностью у людей самых разных возрастов пользуются<strong> зубные украшения</strong> – <strong>скайсы</strong>. Это могут быть простые стразы, кристаллы Сваровски или алмазы в золотой оправе. Разнообразие их формы и цвета дает возможность подобрать  для Вас нечто особенное.</p> 
<p>Украшения крепятся  на зубы без препаровки, т.е не нарушая структуру эмали, при помощи специального стоматологического фиксирующего материала . Снять украшение можно в любой момент, после чего зубы имеют свой первоначальный вид.</p>
<p>Скайсы способны подчеркнуть Вашу индивидуальность, сделать улыбку блистательной и неотразимой!</p>
 <hr />
	</div>    


 <div id="ortoped_content_miradent">

<h3>ЭНДОДОНТИЧЕСКОЕ ЛЕЧЕНИЕ</h3>
<p>Если вовремя не вылечить кариес, болезнь может распространиться на пульпу зуба (внутризубной нерв) и далее – на связочный аппарат зуба и костную ткань челюсти. Как следствие – сильные боли, отек, воспаление и удаление зуба.</p>  
<p><strong>Эндодонтическое лечение</strong> – это комплекс мероприятий, направленных на борьбу с инфекцией внутри зуба и возвращение зубу возможности нормально функционировать. <strong>Эндодонтия</strong> – одна из важнейших областей терапевтической стоматологии.  Она требует от специалиста четкого знания сложной анатомии корневых каналов и строгого соблюдения последовательности определенных манипуляций в процессе лечения.</p>
<p>Врач-эндодонт выполняет ряд задач:</p>
	<ul>
    	<li>обеспечение доступа к корневым каналам,</li>
        <li>прохождение канала до верхушки корня,</li>
        <li>удаление из канала инфицированных и мертвых тканей,</li>
        <li>придание каналу формы, необходимой для правильного пломбирования,</li>
        <li>медикаментозная обработка канала с целью окончательного удаления болезнетворных бактерий,</li>
        <li>герметичное запечатывание (пломбирование) канала специальными наполнителями.</li>
	</ul>
	
    <p>В сложных и запущенных случаях не удается провести лечение корней в одно посещение: бывает необходимо оставление открытого зуба, наложение лекарственного средства под временную пломбу либо временное пломбирование канала лечебной пастой.</p>
<p>Каждый этап эндодонтического лечения выполняется с применением новейшего оборудования, инструментов, материалов.</p> 
<p>Современная стоматология мирового уровня МИРАДЕНТ располагает значительным арсеналом средств и методов качественного и надежного лечения корней. Правильность лечения контролируется и подтверждается с помощью специального прибора – апекслокатора и рентгеновских снимков, выполняемых на высокотехнологичной рентгенустановке.</p>
<p>Метод подготовки и заполнения корневых каналов выбирается в зависимости от их формы и строения, диагноза и течения заболевания, а также от способа последующего восстановления зуба в целом.</p>

<p><strong>Стоматология МИРАДЕНТ</strong> применяем самые прогрессивные технологии <strong>обработки и пломбирования каналов</strong>, гарантирующие продление жизни и здоровья зубов на долгий срок, а также возможность их использования в различных ортопедических конструкциях.</p>

<h2>Обработка корневых каналов : технологии.</h2>
<p>Кариес зубов, распространяясь, вызывает воспаление пульпы зуба и околокорневой костной ткани. Современная стоматология позволяет спасти большинство таких зубов, не допустить их удаления.</p>
<p>Лечение в таких случаях заключается в специальной обработке и герметичном <strong>пломбировании каналов корня зуба</strong>. Обработка каналов направлена на удаление из канала инфицированных тканей и придание каналу формы, необходимой для проникновения лекарства и правильного пломбирования.</p>
<p>Каналы имеют сложную форму, ответвления, часто встречаются тонкие, изогнутые, труднопроходимые каналы. Для их обработки используются специальные ручные и вращающиеся инструменты, позволяющие убрать из просвета воспаленные ткани, сделать стенки гладкими. В процессе обработки канал промывается специальными антисептическими растворами, нейтрализующими болезнетворные бактерии.</p>
<p>На протяжении всей работы стоматолог координирует свои действия по показаниям специального прибора – апекслокатора, при необходимости проводит дополнительный контроль с помощью рентгеновского снимка.</p>

<p>Правильная  предварительная обработка обеспечивает последующее качественное пломбирование канала и сохранение  зуба на длительный срок.</p>

<h2>Повторное эндодонтическое лечение : технологии.</h2>
<p>Нередко пациенты обращаются к стоматологу по поводу зубов, которые уже были ранее  пролечены эндодонтически в  другой клинике. Такие зубы нуждаются в повторном эндодонтическом лечении, и чаще всего их удается спасти.</p>
<p>Перед тем как поступить к перелечиванию канала, специалист изучает рентгеновский снимок. <strong>Повторное эндодонтическое лечение</strong> заключается в удалении из канала старого пломбировочного материала, прохождение и формирование канала на всю длину, обработка лечебными дезинфицирующими растворами и плотное пломбирование канала до верхушки по одной из современных методик. </p>
<p>Способ повторного лечения зависит от того, какой пломбировочный материал находится в канале, от формы и проходимости канала.  Для удаления из канала старой пломбировочной массы используются специально разработанные вращающиеся никель-титановые инструменты. В сложных случаях, когда каналы были прежде заполнены цементом, применяется ультразвуковой аппарат с соответствующими насадками. Ультразвук дробит застывший цемент и способствует его выведению. Кроме того, он во много раз усиливает бактерицидное  действие дезинфицирующий средств, увеличивает шансы на успех в лечении. </p>
<p>Герметичное  заполнение подготовленного корневого канала с последующим восстановлением зуба фотополимерным материалом позволяет остановить воспалительные явления в костной ткани челюсти, предотвратить обострение процесса и удаление зуба.</p>

<h2>Пломбирование корневого канала : технологии.</h2>
<p><strong>Пломбирование каналов</strong> является логическим итогом <strong>эндодонтического лечения</strong>. Наиболее верный шанс клинического успеха достигается тогда, когда система корневых каналов полностью, со всей своей сложностью, будет запломбирована на своем полном апикальном и латеральном протяжении.</p>
<p>Большинство современных методик пломбирования заключаются в плотном закрытии канала гуттаперчей с использованием силера – наполнителя – лечебной пасты, застывающей в канале после пломбирования.  Речь идет о методах латеральной конденсации гуттаперчи, конусного штифта, центрированной и вертикальной конденсации горячей гуттаперчи. Эти методики отличаются по степени уплотнения и распространения, способу введения, сложности, необходимости специального оборудования и стоимости. </p>
<p>При латеральной конденсации в канал, заполненный силером, вводится основной гуттаперчевый штифт, плотно закрывающий верхушечное отверстие. Далее, он уплотняется специальным инструментом и вводится следующий один штифт. Процедура повторяется до тех пор, пока просвет канала, имеющий конусную форму, не будет заполнен на всем протяжении. </p>
<p>Если канал предварительно обработан и сформирован с помощью специальной системы вращающихся инструментов, имеется возможность заполнить его с помощью одного конусного гуттаперчевого штифта, точно соответствующего форме подготовленного канала. Штифт идеально запечатывает верхушечное отверстие и весь просвет канала, делает ненужным введение  и уплотнение множества дополнительных штифтов. Это значительно сокращает процедуру, не отражаясь на ее качестве.</p> 
<p>В настоящее время мало кто из стоматологов отрицает наличие микроканальцев и множественных ответвлений корневого канала, которые также нуждаются в пломбировании.  Именно поэтому разработаны методики  <strong>3-D (трехмерной)</strong> <strong>обтурации</strong>.</p>
<p>Техника обтурации центрированной конденсацией (термафил) действенно и эффективно продвигает пломбирующие материалы через систему корневого канала движением конденсирующего устройства (предварительно нагретого носителя) в центре термопластического материала, такого как гуттаперча. Пломбирующий материал, смазанный силером, смещается в сторону коронки, так как конденсирующее устройство движется к верхушке, создавая эффект тока материала на стенки основного канала. Это пломбирует боковые канальцы, дополнительные канальцы, бороздки, петли, ответвления и перешейкипо ходу инструмента. Для работы в этой технике дополнительно требуются гуттаперчевые обтураторы на носителе и специальное устройство для их разогрева.</p>
<p>Для техники постоянной волны (Є&Q+ Plus) выбирается электрически нагреваемый уплотнитель - плаггер (Sybron Endo), соответствующей  конусности. Стенки канала смазываются силером, подготовленный гуттаперчевый штифт вводится до верхушки. Излишки гуттаперчи специальным образом убираются , а плаггер уплотняет гуттаперчу до уровня 4мм от верхушечного отвертстия, обеспечивая максимальное проникновение материала во все ответвления и канальцы, герметизируя все возможные пути распространения бактерий. <strong>Пломбирование верхних 2\3 канала</strong> выполняется при помощи пистолета или новым, встроенным, машинным пресс-шприцем.</p>
<p>Раньше было сложно запломбировать систему корневого канала в трехмерном измерении. Сейчас  этот надежный метод, предполагающий наличие дополнительной дорогостоящей аппаратуры и грамотного специалиста, полностью оправдывает возложенные на него ожидания. Кроме гуттаперчи, <strong>для пломбирования каналов</strong> применяются недавно разработанные материалы (эпифания, резилон, ПроРут МТА), которые используются по показаниям в соответствующих техниках пломбирования и значительно расширяют возможности сохранения зубов, рекомендованных к удалению. </p>
<h2> Аппаратные методы диагностики</h2>
    <p>Для постановки точного диагноза и подтверждения качества лечения в стоматологической клинике МИРАДЕНТ проводятся рентгенологические исследования на современном оборудовании.</p>
<p>Стоматологические установки оснащены интраоральными камерами Vista Cam ведущего немецкого производителя – фирмы Durr Dental. 
Камера многократно увеличивает изображение и переводит его на плоский экран. Это позволяет стоматологу рассмотреть мельчайшие детали на рабочем поле, а также продемонстрировать пациенту элементы зубных отложений, скрытые кариозные полости, исходное состояние больного зуба, этапы и результат проведения реставрации.</p>
<p>С помощью интраоральной камеры можно получить фотоснимки зубов до и после стоматологических процедур.  
Использование интраоральной камеры повышает информированность пациента  о ходе проводимых лечебных действий,  позволяет пациенту чувствовать себя спокойнее и увереннее на приеме у стоматолога.</p>  
 <hr />      
</div>

    
    <h3>ПРОФЕССИОНАЛЬНАЯ ГИГИЕНА</h3>
      <p><strong>Профессиональная гигиена</strong> в настоящее время является важнейшим элементом комплексного лечения, а также неотъемлемой составляющей терапии и профилактики таких стоматологических заболеваний как кариес, заболевания тканей пародонта: гингивит, пародонтит.</p>
 <p>Регулярный и правильный уход за полостью рта в домашних условиях имеет большое значение, но по эффективности он гораздо ниже профессионального. Достаточно сложно самостоятельно обеспечить полноценную чистку межзубных промежутков или вычистить налет в труднодоступных участках полости рта, вследствие чего в этих зонах накапливаются зубные отложения.</p> 
<p><strong>Зубные отложения</strong> – это органические вещества с присоединившимися бактериями и продуктами их жизнедеятельности. Образуясь в околодесневой зоне, они склонны к накапливанию еще большего количества налета и создают условия для образования поддесневых отложений (так называемого зубного камня), которые имеют более жесткую структуру и вызывают воспаление околозубных тканей - пародонтит.</p> 
<p><strong>Профессиональная чистка зубов</strong> проводится в несколько этапов, и  заключается в следующем: </p>
<p>- удаление над- и -поддесневых отложений при помощи ультразвукового скалера, </p>
<p>- сглаживание поверхности корня (по показаниям),</p>
<p>-  удаление мягкого зубного налета специальными щетками. При больших скоплениях зубного налета дополнительно может использоваться содоструйный аппарат, который безопасно чистит и механически отбеливает зубы при помощи струи аэрозоля, состоящего из воды и абразивного средства,</p>
<p>- полировка всех зубов абразивными пастами. </p>
<p>После снятия зубного налёта особенно эффективно применение препаратов, которые насыщают ткани зуба минералами, снимают чувствительность зубов и укрепляют эмаль.</p>
      <p><strong>Обязательным этапом профессиональной гигиены полости рта</strong> является флюоризация зубов с использованием фторсодержащих гелей, лаков и ополаскивателей.  Фтор является более активным элементом, чем кальций. Он включается  в кристаллическую решетку эмали, укрепляет ее, делает более устойчивой к кариесу, уменьшает повышенную чувствительность. Применение препаратов фтора с целью профилактики кариеса особенно эффективно после проведения профессиональной чистки зубов.</p>
<p>Квалифицированный специалист обучает пациента принципам индивидуальной гигиены, при необходимости дает пациенту рекомендации по использованию дополнительных средств по уходу за полостью рта.</p>
<p>Рекомендовано 1-3 раза в год посещать стоматолога с целью оценки состояния зубов и околозубных тканей, а также проведения профессиональной гигиены полости рта.</p>




<h3>ТЕРАПИЯ</h3>

<h2>1. Лечение кариеса зубов.</h2>
    <p><strong>Кариес</strong> – заболевание зубов микробной природы, при котором повреждаются твердые ткани (эмаль и дентин). В зубе образуется полость, могут возникать болевые ощущения от сладкого, холодного, горячего, во время еды.</p>
 <p>Если зуб вовремя не пролечить, разрушение достигнет пульпы зуба (внутризубного нерва). Воспаление пульпы может сопровождаться острой невыносимой болью.</p>
    <p><strong>Лечение кариеса зубов</strong> заключается в иссечении поврежденных участков с помощью современного высокоскоростного оборудования в технике щадящего препарирования. Это позволяет максимально сохранить здоровые ткани и продлить жизнь зубов.</p> 
     <p>Все процедуры проводятся под анестезией и  совершенно безболезненны. </p>
     <p>Подготовленная полость заполняется пломбировочным материалом. При глубоком кариесе на дно подготовленной полости ставится лечебная прокладка, позволяющая защитить пульпу зуба от воспаления.</p> 
   <p>Современные пломбировочные материалы имеют прочное сцепление с эмалью и дентином, способны выдерживать жевательную нагрузку, позволяют полностью восстановить цвет и форму здорового зуба.</p>

<h2>2. Обезболивание.</h2>  
       <p>Скажите решительное «НЕТ!» страху и боли!</p>
<p>Все стоматологические процедуры проводятся «под прикрытием» современных обезболивающих средств.</p>
<p>Квалифицированные специалисты владеют передовыми методиками проведения анестезии. Всегда есть возможность выбора препаратов, соответствующих особенностям Вашего организма и характеру предстоящих лечебных мероприятий.</p>
<p>Безболезненное, комфортное проведение стоматологических процедур – прямой путь к успешному результату в  лечении!</p>


<h3>ОРТОПЕДИЧЕСКОЕ ЛЕЧЕНИЕ</h3>
<p>Частичная или полная утрата  зубов, значительноу их разрушение, нарушение эстетической целостности и функциональности зубного ряда являются основными показаниями к <strong>протезированию</strong>. В стоматологической клинике "<strong>МИРАДЕНТ</strong>" практикуются современные методы съемного (частичные и полные <strong>пластиночные протезы</strong>, <strong>бюгельные протезы</strong>) и несъемного (<strong>металлокерамические и безметалловые коронки</strong>, <strong>мостовидные протезы</strong>;  <strong>керамические вкладки</strong>, <strong>виниры</strong>). Выполняются подготовительные реставрации зубов  внутрикорневыми металлическими вкладками. Для изготовления протезов используются только высококачественные материалы ведущих фирм производителей Германии, Франции, Японии.</p>
<h2>Металлокерамические конструкции</h2>
<p><strong>Металлокерамические коронки</strong> показаны при разрушении коронковой части зуба более чем на 1\2 части, в целях  изменения формы и цвета зуба (при невозможности выполнить это методом прямой реставрации фотокомпозитами). Это один из самых популярных видов несъемного зубного протезирования благодаря своим наиболее приближенным к естественным зубам физико-механическим свойствам, высоким эстетическим параметрам, прочности и долговечности.</p> 
<p>Металлокерамические зубные коронки представляют собой металлический колпачек (отлитый из специальных стоматологических гипоалергенных сплавов) с керамической облицовкой. Протезы изготавливаются по индивидуальной модели с  максимальным восстановлением анатомической формы,  учетом особенностей прикуса и распределения жевательной нагрузки. Благодаря современным методам подготовки зубов под несъемное протезирование и высококлассным технологиям изготовления протезов, коронки покрывают зубы с высокой точностью, что исключает воспалительные процессы в околозубных тканях, попадание пищи под коронки и развитие кариозных процессов. Средний срок службы современной металлокерамики на неблагородном сплаве около 12-15 лет.</p>

<h2>Безметалловая керамика</h2>
<p><strong>Безметалловая керамика</strong> — новейшее достижение в косметической стоматологии. Как видно из самого названия, коронки из этого материала выполняются без содержания металла. </p>
<p>Применение безметалловой керамики позволяет изготавливать легкие, надежные и эстетичные протезы. Эта технология на сегодняшний день названа ведущими стоматологами мира самой безвредной и гипоаллергенной для организма человека. Из безметалловой керамики изготавливают коронки (зуб обрабатывается полностью), виниры (обрабатывается только передняя часть зуба), керамические вкладки и накладки (инлэй, онлэй) в тех случаях, когда необходимо заменить старые обширные пломбы и продлить жизнь зуба с минимальными потерями твердых тканей. Протезы и микропротезы из безметалловой керамики изготавливаются строго в соответствии с формой и цветом зубов пациента.</p>
 	<p>Безметалловая керамика имеет ту же степень преломления света, что и эмаль зуба, что позволяет добиться максимально эстетического вида протезируемых зубов. Наряду с этим безметалловые конструкции производятся из особо прочной керамической массы, что дает возможность протезировать зубы, поддающиеся большим  жевательным нагрузкам.</p>

<h2>Виниры</h2>
<p><strong>Керамические виниры</strong> – одно из последних достижений современной  стоматологии, позволяющее получить идеальный эстетический результат. Это  тонкие керамические пластинки толщиной 0,5-0,7 мм, которые фиксируются специальным цементом  на передней поверхности зубов, позволяя сохранить нетронутой внутреннюю часть.</p>
<p>Не смотря на тонкость, керамические виниры обладают высокой прочностью и цветостойкостью, что позволяет восполнять большие дефекты эмали (эрозии, значительная потеря зубной ткани в пришеечной области), изменить цвет депульпированных или пигментированных зубов, не поддающихся отбеливанию. Использование виниров позволяет придать зубам желаемую форму, применяя максимально щадящее препарирование. Виниры также выступают в роли альтернативного способа закрытия диастемы.
Процесс изготовления керамических виниров занимает одну неделю. Пациенту потребуется всего два непродолжительных визита к стоматологу. Во время первого визита проводится подготовка зуба, снятие слепка, определение  цвета  винира и постановка временной пломбы. Во время второго визита стоматолог примеряет, и после припасовки фиксирует винир. </p>

 	<h2>Бюгельные протезы</h2>
<p><strong>Бюгельный протез</strong> - это реальная альтернатива съемным пластиночным протезам. Этот вид протезирования используется при невозможности восполнения зубного ряда несъемными протезами ввиду отсутствия большого количества зубов или наличии концевых дефектов. Он обладает более высокими эстетическими и функциональными качествами. Эстетичность данного протеза заключается в использовании замковых креплений к опорным керамическим зубам, что обеспечивает надежную фиксацию и делает его незаметным в полости рта. Правильный выбор конструкции позволяет равномерно распределить жевательную нагрузку на опорные зубы и на слизистую оболочку, чем обеспечивается долговечность оставшихся зубов при восполнении жевательной функции.</p>

 	<h2>Съемные протезы</h2>
<p><strong>Протезирование  съемными протезами</strong> – один из вариантов лечения в случае полной или частичной утраты своих собственных зубов. Зубные протезы — это пластмассовая пластина с искусственными зубами, которая крепится на деснах и челюстных выступах благодаря эффекту присасывания. </p>
<p>Благодаря современным технологиям зубные протезы изготавливают из качественного  материала (стоматологической акриловой пластмассы), который надолго сохраняет прочность, цвет, плотность и форму. </p>
<p>Для каждого пациента подбирается индивидуальный, подходящий по форме, размеру и цвету зубной набор.</p>



<h3>ИМПЛАНТАЦИЯ</h3>

 	<p><strong>Имплантация</strong> - это метод вживления искусственного корня (имплантата) в верхнюю или нижнюю челюсть. Имплантаты используются в качестве опор, на которые фиксируются либо коронки (полноценно заменяющие утраченные зубы), либо мостовидные керамические протезы. Конструкция имплантата состоит из двух основных частей - самого имплантата, который представляет собой титановый винт (выполняющий функцию корня зуба), вживляемый в челюсть хирургическим путем и абатмента (выполняющего функцию культи зуба), изготовленного также из титана, который присоединяется к имплантату после периода приживления.К абатменту, в свою очередь, прикрепляется коронка, несущая функцию протеза или сам протез.</p>
<p>Метод имплантации имеет ряд существенных преимуществ перед традиционными методами протезирования и дает возможность пациентам получить зубные протезы неотличимые ни по внешнему виду, ни по функции от своих собственных зубов.</p>

<p><strong>Преимущества имплантации</strong>:</p>
<p>- имплантаты позволяют замещать дефекты зубного ряда без обточки соседних зубов;</p>
<p>- имплантатами можно замещать дефекты зубного ряда любой протяженности и локализации; </p>
<p>- внедрение в кость имплантатов останавливает рассасывание кости в области отсутствующего зуба (или зубов), имитируя физиологическую нагрузку на костную ткань, как естественные зубы; </p>
<p>- возможность изготовления несъемных конструкций даже на полностью беззубых челюстях.</p>

<p><strong>Установка имплантатов</strong> проводится хирургом-стоматологом под местной анестезией. В некоторых случаях установка имплантата возможна сразу же после удаления больного зуба.  Сама процедура установки обычно занимает небольшое количество времени, а для периода заживления (остеорегенерации) понадобится в  среднем от 3 до 6 месяцев. В этот период имплантат должен сжиться с костной тканью. По результатам установки и заживления  переходят к следующему этапу: ортопедическому (установка абатмента и изготовление протезов или коронок). Ортопедические конструкции фиксируются на абатменты при помощи специального цемента.</p>
</div>
    </td>
  </tr>
</table>

















</div>


</div> <!-- cat_ite_cont_m -->

<?php

}

else

   if ($_GET['pm'] == 3)

   {

?>

<script language="javascript" type="text/javascript">
	function show_hide(objectID){
		var object=document.getElementById(objectID);
		if (object.style.display=='none')
			object.style.display='block';
			else
			object.style.display='none';
			return;
	}
</script>

<div class="catalogue_item_cont_m"> 

	<div id="main_miradent">
				<table background="../root/msite/miradent/upper.jpg" height="380px" width="980px" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td style="padding:35px 0 0 40px;" height="125px"><a href="index.html"><img src="../root/msite/miradent/logo.png" border="0" align="left"/></a></td>
  </tr>
   <tr>
    <td>
    	<p align="left" style="font-size:20px; padding:5px 0 0 10px;font-weight:600; font-family:Times New Roman;">г. Донецк, пр-т Мира, 2</p> 
		<p align="left" style="font-size:20px; padding:5px 0 0 10px; font-weight:600; font-family:Times New Roman;">тел: 062 381-18-24; моб: 050 696-47-70</p>
		<p align="left" style="font-size:20px; padding:5px 0 0 10px;font-weight:600; font-family:Times New Roman;">МЦ «Блиц»: г. Донецк ул. Раздольная, 13</p>
		<p align="left" style="font-size:20px; padding:5px 0 0 10px; font-weight:600; font-family:Times New Roman;">тел: 062 389-33-04; моб: 050 057-43-78</p>      </td>
  </tr>
  <tr>
    <td height="50px">
    			<div id="menu_miradent">
                		<ul>
                        	<li id="mir_miradent"><a href="index.php?business_full=490&pm=2"><span style="text-align:center; font-size:18px; font-family:Times New Roman;">МИРАДЕНТ</span></a></li>
                            <li id="blic_miradent"><a href="index.php?business_full=490&pm=1"><span style="text-align:center; font-size:18px; font-family:Times New Roman;">Мед. центр</span> <span style="text-align:center; font-size:18px; font-family:Times New Roman;">БЛИЦ</span></a></li>
                            <li><a href="index.php?business_full=490&pm=3"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;">О нас</span></a></li>
                            <li><a href="index.php?business_full=490&pm=4"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;">Цены</span></a></li>
                            <li><a href="index.php?business_full=490&pm=5"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;">Вакансии</span></a></li>
                            <li id="link_r_miradent"><a href="index.php?business_full=490&pm=6"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;">Контакты</span></a></li>
                        </ul>
                </div>       
    </td>
  </tr>
</table>
<table id="tab_content_miradent" width="970px" align="center" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td id="left_content_miradent">
     <br />
      <a href="javascript:show_hide('est_rev_content_miradent')"><br /><br /><br /><span>Эстетическая</span><br /><span>Реставрация</span></a>
        	  	<br />
      <a href="javascript:show_hide('otbel_content_miradent')"><br /><br /><br /><span>Отбеливание</span><br /><span>системой</span><br /><span>"Beyond"</span></a> 
        	    <br />
   	  <a href="javascript:show_hide('ortoped_content_miradent')"><br /><br /><br /><span>Эндодонтическое</span><br /><span>лечение</span></a>
    </td>
    <td valign="top">
      <div id="text_content_miradent">
      <div id="est_rev_content_miradent">
      <h3>ЭСТЕТИЧЕСКАЯ РЕСТАВРАЦИЯ ЗУБОВ</h3>
    <p>Высокоразвитая цивилизация ставит перед стоматологом требования не только борьбы с болью и восстановления жевательной функции. Не менее важно в настоящее время сохранение и воссоздание неповторимой красоты здоровых зубов.</p>
   <p>Эту роль выполняет <strong>эстетическая реставрация</strong> – восстановление изначального цвета, формы и размера зуба.</p> 
   <p>Материалы для реставрации по твердости и прочности аналогичны твердым тканям зуба. Они разрабатываются в разных оттенках, что делает возможным воспроизвести в эстетической конструкции цветовые переливы природного живого зуба.</p>
   <p>Композиционные фотополимерные материалы послойно наносятся на подготовленный зуб в соответствии с цветом и структурой утраченных зубных тканей и отверждаются специальной лампой.</p>
   <p><span>Безболезненность, надежность, красота и естественность – вот цели профессионалов эстетической стоматологии!</span></p>

<h2>Эстетическая реставрация зубов : технологии.</h2>
<p>В  современном мире  космических технологий, высокой моды, открытых информационных границ безукоризненная улыбка открывает человеку безграничные возможности в личном общении и карьерном росте. 
Зубы человека отличаются сложностью и разнообразием формы, неповторимой структурой, богатством передачи цвета, блеском, прозрачностью. Все эти качества стоматолог стремится воссоздать в художественной реставрации, чтобы придать Вашей улыбке красоту и естественность.</p>
<p>Современные высокооснащенные лаборатории ведущих мировых фирм стоматологической продукции постоянно работают над созданием и усовершенствованием материалов для реставрации зубов. Многочисленный арсенал этих средств составляют фотополимерные материалы для восстановления жевательных групп зубов (в том числе, армированные - упроченные), жидкотекучие фотополимеры для плотной адаптации к поверхности, универсальные – для пломбирования любых зубных дефектов, материалы для художественной реставрации. Последние соответствуют тканям зуба по прочности и твердости, позволяют точно передать структурные цветовые переходы, опалесценцию и флюоресценцию зубной поверхности.</p>
<p>Обработка зуба под фотополимерные реставрации производится максимально щадяще. Сцепление материала с поверхностью осуществляется за счет микропроникновения связывающего агента (бонда) в межкристаллические пространства и обеспечивает так называемое интимное прикрепление.</p>
 <p>Если зуб значительно разрушен, его укрепляют по показаниям анкерным или световолоконным штифтом.
Фотоматериал послойно накладывается на зуб в соответствии со структурой утраченных зубных тканей, повторяя их цвет. Каждый слой отдельно отверждается  светом специальной лампы. Это делает конструкцию еще более прочной. Моделируя поверхность зуба, стоматолог повторяет бугорки, бороздки и другие элементы, характерные для строения здоровых зубов конкретного человека. Готовая реставрация корректируется по прикусу и полируется до блеска.</p> 
<p><strong>Художественная реставрация зубов</strong> подарит Вам здоровую улыбку и уверенность в собственной неповторимости.</p>
 <hr />
	</div>
    
  <div id="otbel_content_miradent">
	<h3>ОТБЕЛИВАНИЕ ЗУБОВ</h3>
    <p>Большинство людей в современном мире придает значение здоровью зубов и их внешнему виду! Сделайте свою улыбку неотразимой! Если Вы хотите иметь белые зубы и сногсшибательную улыбку, тогда <strong>система Бейонд</strong> – Ваш верный выбор. Ваша улыбка станет сияющей и белоснежной всего за 30 минут! Отбеливающая система обеспечивает максимально возможный эффект даже если ваши зубы потемнели от курения, употребления напитков, содержащих красители, утратили природную белизну вследствие применения лекарственных препаратов, таких как тетрациклин или покрылись пятнами из-за употребления антибиотиков, избытка фтора.</p>
<p><strong>Система</strong> «<strong>Beyond Whitening Accelerator</strong>» - лучший выбор для достижения белоснежной и здоровой улыбки быстро и эффективно. Всего лишь за один курс отбеливания убираются пятна, которые образовывались годами, цвет зубов улучшается в среднем на 10-14 оттенков. Степень улучшения цвета зубов пациент выбирает по своему желанию и согласно рекомендациям стоматолога. Инновационная программа акселератора позволяет подобрать каждому пациенту индивидуальный режим интенсивности отбеливания.</p>
<p>Процедура отбеливания по системе <strong>Бейонд</strong> заключается в нанесении специального отбеливающего геля на поверхность зубов, а затем его активации с помощью холодного света лампы «<strong>Beyond Whitening Accelerator</strong>». Отбеливающий гель основан на 35% перекиси водорода и других компонентах, которые улучшают результат, предупреждают возникновение чувствительности и укрепляют зубную эмаль.</p> 
<p>Процесс отбеливания зубов возможен благодаря способности пероксида водорода свободно проникать сквозь эмаль и распространяться по всем частям зуба. Пероксиды под воздействием активатора (акселератора) распадаются на кислородные радикалы, которые затем мигрируют между эмалевыми  призмами, разлагая любые окрашенные молекулы, структура зуба при этом не затрагивается. Эмаль, дентин, связующие материалы и пломбы не повреждаются отбеливающими веществами.</p>
<p><strong>Преимущества отбеливающей системы</strong> <strong>Бейонд</strong> над всеми существующих на мировом рынке системами отбеливания:</p>
		<ul>
        	<li>Комфортность и удобство: не требует никаких предварительных процедур, за исключением профессиональной гигиенической чистки; одномоментное отбеливание 16-20 зубов в течение 30 минут. Кратковременность процедуры исключает возникновение раздражения десен и околозубных тканей. Акселератор отбеливания работает в режиме низкой температуры, что снижает риск возникновения чувствительности зубов. </li>
            <li>Безопасность: акселератор отбеливания – мощная галогеновая лампа, излучающая холодный голубой свет, который фильтруется 12 000 световодами и системой оптических линз. Вредное ультрафиолетовое и инфракрасное излучение отсеивается, не достигая поверхности зубов. Излучение холодного света снижает уровень вредных бактерий в полости рта эффективнее дезинфицирующего ополаскивателя.</li>
        </ul>    
<p>При соблюдении всех рекомендаций по уходу за отбеленными зубами и использовании средств для поддержания эффекта в домашних условиях ваши зубы будут выглядеть прекрасно как после самой процедуры, так и на протяжении нескольких лет!</p>
<p>
<span><strong>Beyond Power Whitening System</strong> – самая мощная система косметического <strong>отбеливания зубов</strong> в настоящее время, это передовая технология, гарантирующая безопасность, комфорт и результативность. Подробнее о системе отбеливания на сайте </span><a href="http://beyonddent.com.ua">www.beyonddent.com.ua.</a></p>
<h2>ЗУБНЫЕ УКРАШЕНИЯ.</h2>
<p>В настоящее время широкой популярностью у людей самых разных возрастов пользуются<strong> зубные украшения</strong> – <strong>скайсы</strong>. Это могут быть простые стразы, кристаллы Сваровски или алмазы в золотой оправе. Разнообразие их формы и цвета дает возможность подобрать  для Вас нечто особенное.</p> 
<p>Украшения крепятся  на зубы без препаровки, т.е не нарушая структуру эмали, при помощи специального стоматологического фиксирующего материала . Снять украшение можно в любой момент, после чего зубы имеют свой первоначальный вид.</p>
<p>Скайсы способны подчеркнуть Вашу индивидуальность, сделать улыбку блистательной и неотразимой!</p>
 <hr />
	</div>    


 <div id="ortoped_content_miradent">

<h3>ЭНДОДОНТИЧЕСКОЕ ЛЕЧЕНИЕ</h3>
<p>Если вовремя не вылечить кариес, болезнь может распространиться на пульпу зуба (внутризубной нерв) и далее – на связочный аппарат зуба и костную ткань челюсти. Как следствие – сильные боли, отек, воспаление и удаление зуба.</p>  
<p><strong>Эндодонтическое лечение</strong> – это комплекс мероприятий, направленных на борьбу с инфекцией внутри зуба и возвращение зубу возможности нормально функционировать. <strong>Эндодонтия</strong> – одна из важнейших областей терапевтической стоматологии.  Она требует от специалиста четкого знания сложной анатомии корневых каналов и строгого соблюдения последовательности определенных манипуляций в процессе лечения.</p>
<p>Врач-эндодонт выполняет ряд задач:</p>
	<ul>
    	<li>обеспечение доступа к корневым каналам,</li>
        <li>прохождение канала до верхушки корня,</li>
        <li>удаление из канала инфицированных и мертвых тканей,</li>
        <li>придание каналу формы, необходимой для правильного пломбирования,</li>
        <li>медикаментозная обработка канала с целью окончательного удаления болезнетворных бактерий,</li>
        <li>герметичное запечатывание (пломбирование) канала специальными наполнителями.</li>
	</ul>
	
    <p>В сложных и запущенных случаях не удается провести лечение корней в одно посещение: бывает необходимо оставление открытого зуба, наложение лекарственного средства под временную пломбу либо временное пломбирование канала лечебной пастой.</p>
<p>Каждый этап эндодонтического лечения выполняется с применением новейшего оборудования, инструментов, материалов.</p> 
<p>Современная стоматология мирового уровня МИРАДЕНТ располагает значительным арсеналом средств и методов качественного и надежного лечения корней. Правильность лечения контролируется и подтверждается с помощью специального прибора – апекслокатора и рентгеновских снимков, выполняемых на высокотехнологичной рентгенустановке.</p>
<p>Метод подготовки и заполнения корневых каналов выбирается в зависимости от их формы и строения, диагноза и течения заболевания, а также от способа последующего восстановления зуба в целом.</p>

<p><strong>Стоматология МИРАДЕНТ</strong> применяем самые прогрессивные технологии <strong>обработки и пломбирования каналов</strong>, гарантирующие продление жизни и здоровья зубов на долгий срок, а также возможность их использования в различных ортопедических конструкциях.</p>

<h2>Обработка корневых каналов : технологии.</h2>
<p>Кариес зубов, распространяясь, вызывает воспаление пульпы зуба и околокорневой костной ткани. Современная стоматология позволяет спасти большинство таких зубов, не допустить их удаления.</p>
<p>Лечение в таких случаях заключается в специальной обработке и герметичном <strong>пломбировании каналов корня зуба</strong>. Обработка каналов направлена на удаление из канала инфицированных тканей и придание каналу формы, необходимой для проникновения лекарства и правильного пломбирования.</p>
<p>Каналы имеют сложную форму, ответвления, часто встречаются тонкие, изогнутые, труднопроходимые каналы. Для их обработки используются специальные ручные и вращающиеся инструменты, позволяющие убрать из просвета воспаленные ткани, сделать стенки гладкими. В процессе обработки канал промывается специальными антисептическими растворами, нейтрализующими болезнетворные бактерии.</p>
<p>На протяжении всей работы стоматолог координирует свои действия по показаниям специального прибора – апекслокатора, при необходимости проводит дополнительный контроль с помощью рентгеновского снимка.</p>

<p>Правильная  предварительная обработка обеспечивает последующее качественное пломбирование канала и сохранение  зуба на длительный срок.</p>

<h2>Повторное эндодонтическое лечение : технологии.</h2>
<p>Нередко пациенты обращаются к стоматологу по поводу зубов, которые уже были ранее  пролечены эндодонтически в  другой клинике. Такие зубы нуждаются в повторном эндодонтическом лечении, и чаще всего их удается спасти.</p>
<p>Перед тем как поступить к перелечиванию канала, специалист изучает рентгеновский снимок. <strong>Повторное эндодонтическое лечение</strong> заключается в удалении из канала старого пломбировочного материала, прохождение и формирование канала на всю длину, обработка лечебными дезинфицирующими растворами и плотное пломбирование канала до верхушки по одной из современных методик. </p>
<p>Способ повторного лечения зависит от того, какой пломбировочный материал находится в канале, от формы и проходимости канала.  Для удаления из канала старой пломбировочной массы используются специально разработанные вращающиеся никель-титановые инструменты. В сложных случаях, когда каналы были прежде заполнены цементом, применяется ультразвуковой аппарат с соответствующими насадками. Ультразвук дробит застывший цемент и способствует его выведению. Кроме того, он во много раз усиливает бактерицидное  действие дезинфицирующий средств, увеличивает шансы на успех в лечении. </p>
<p>Герметичное  заполнение подготовленного корневого канала с последующим восстановлением зуба фотополимерным материалом позволяет остановить воспалительные явления в костной ткани челюсти, предотвратить обострение процесса и удаление зуба.</p>

<h2>Пломбирование корневого канала : технологии.</h2>
<p><strong>Пломбирование каналов</strong> является логическим итогом <strong>эндодонтического лечения</strong>. Наиболее верный шанс клинического успеха достигается тогда, когда система корневых каналов полностью, со всей своей сложностью, будет запломбирована на своем полном апикальном и латеральном протяжении.</p>
<p>Большинство современных методик пломбирования заключаются в плотном закрытии канала гуттаперчей с использованием силера – наполнителя – лечебной пасты, застывающей в канале после пломбирования.  Речь идет о методах латеральной конденсации гуттаперчи, конусного штифта, центрированной и вертикальной конденсации горячей гуттаперчи. Эти методики отличаются по степени уплотнения и распространения, способу введения, сложности, необходимости специального оборудования и стоимости. </p>
<p>При латеральной конденсации в канал, заполненный силером, вводится основной гуттаперчевый штифт, плотно закрывающий верхушечное отверстие. Далее, он уплотняется специальным инструментом и вводится следующий один штифт. Процедура повторяется до тех пор, пока просвет канала, имеющий конусную форму, не будет заполнен на всем протяжении. </p>
<p>Если канал предварительно обработан и сформирован с помощью специальной системы вращающихся инструментов, имеется возможность заполнить его с помощью одного конусного гуттаперчевого штифта, точно соответствующего форме подготовленного канала. Штифт идеально запечатывает верхушечное отверстие и весь просвет канала, делает ненужным введение  и уплотнение множества дополнительных штифтов. Это значительно сокращает процедуру, не отражаясь на ее качестве.</p> 
<p>В настоящее время мало кто из стоматологов отрицает наличие микроканальцев и множественных ответвлений корневого канала, которые также нуждаются в пломбировании.  Именно поэтому разработаны методики  <strong>3-D (трехмерной)</strong> <strong>обтурации</strong>.</p>
<p>Техника обтурации центрированной конденсацией (термафил) действенно и эффективно продвигает пломбирующие материалы через систему корневого канала движением конденсирующего устройства (предварительно нагретого носителя) в центре термопластического материала, такого как гуттаперча. Пломбирующий материал, смазанный силером, смещается в сторону коронки, так как конденсирующее устройство движется к верхушке, создавая эффект тока материала на стенки основного канала. Это пломбирует боковые канальцы, дополнительные канальцы, бороздки, петли, ответвления и перешейкипо ходу инструмента. Для работы в этой технике дополнительно требуются гуттаперчевые обтураторы на носителе и специальное устройство для их разогрева.</p>
<p>Для техники постоянной волны (Є&Q+ Plus) выбирается электрически нагреваемый уплотнитель - плаггер (Sybron Endo), соответствующей  конусности. Стенки канала смазываются силером, подготовленный гуттаперчевый штифт вводится до верхушки. Излишки гуттаперчи специальным образом убираются , а плаггер уплотняет гуттаперчу до уровня 4мм от верхушечного отвертстия, обеспечивая максимальное проникновение материала во все ответвления и канальцы, герметизируя все возможные пути распространения бактерий. <strong>Пломбирование верхних 2\3 канала</strong> выполняется при помощи пистолета или новым, встроенным, машинным пресс-шприцем.</p>
<p>Раньше было сложно запломбировать систему корневого канала в трехмерном измерении. Сейчас  этот надежный метод, предполагающий наличие дополнительной дорогостоящей аппаратуры и грамотного специалиста, полностью оправдывает возложенные на него ожидания. Кроме гуттаперчи, <strong>для пломбирования каналов</strong> применяются недавно разработанные материалы (эпифания, резилон, ПроРут МТА), которые используются по показаниям в соответствующих техниках пломбирования и значительно расширяют возможности сохранения зубов, рекомендованных к удалению. </p>
<h2> Аппаратные методы диагностики</h2>
    <p>Для постановки точного диагноза и подтверждения качества лечения в стоматологической клинике МИРАДЕНТ проводятся рентгенологические исследования на современном оборудовании.</p>
<p>Стоматологические установки оснащены интраоральными камерами Vista Cam ведущего немецкого производителя – фирмы Durr Dental. 
Камера многократно увеличивает изображение и переводит его на плоский экран. Это позволяет стоматологу рассмотреть мельчайшие детали на рабочем поле, а также продемонстрировать пациенту элементы зубных отложений, скрытые кариозные полости, исходное состояние больного зуба, этапы и результат проведения реставрации.</p>
<p>С помощью интраоральной камеры можно получить фотоснимки зубов до и после стоматологических процедур.  
Использование интраоральной камеры повышает информированность пациента  о ходе проводимых лечебных действий,  позволяет пациенту чувствовать себя спокойнее и увереннее на приеме у стоматолога.</p>  
 <hr />      
</div>

    <h3>СТОМАТОЛОГИЯ МИРАДЕНТ : О НАС</h3>  
<p><strong>Стоматология МИРАДЕНТ</strong> основана в г. Донецке в 2001 году  на базе современного оборудования для лечения и диагностики, передовых технологий и высокого уровня стоматологических услуг.  Расположена клиника в центре г.Донецка на пр-те Мира 2.</p>
<p>Основополагающей целью создания стоматологической клиники <strong>МИРАДЕНТ</strong> является оказание квалифицированной стоматологической помощи пациентам.  Залог  успешной работы стоматологического кабинета  в профессионализме, комплексной диагностике и лечении, в индивидуальном подходе  к каждому клиенту.  </p>
<p> Коллектив стоматологии <strong>МИРАДЕНТ</strong> представляет собой группу высококвалифицированных специалистов с опытом работы от 5 до 20 лет: врачи высшей и первой категории, специализирующиеся в таких областях как терапевтическая стоматология, ортопедическая стоматология, эндодонтия, ассистенты  и медсестеры.</p>
 <p>Основными принципами деятельности стоматологической клиники <strong>МИРАДЕНТ</strong> являются: постановка правильного диагноза, осуществление профессионального лечения и организация профилактических мероприятий для пациентов, доверительное отношение к каждому пациенту, комфортная обстановка и внимание персонала, компетентность специалистов и их ответственное отношение к каждой выполненной манипуляции, постоянное обновление материально-технической базы и усовершенствование знаний и навыков.</p>
<p>В клинике <strong>МИРАДЕНТ</strong> ведется <strong>терапевтический</strong>, <strong>эндодонтический</strong>, <strong>ортопедический</strong> приём пациентов, а также успешно используется <strong>галогенное отбеливание</strong>, которое имеет большое преимущество перед традиционным.
В нашей стоматологии Вы можете получить весь спектр стоматологических услуг на самом высоком уровне: <strong>безболезненное лечение кариеса</strong>,  <strong>эстетическая реставрация зубов</strong>, <strong>отбеливание</strong>, <strong>профилактическая чистка зубов</strong>, <strong>лечение заболеваний пародонта</strong>, <strong>эндодонтическое лечение зубов</strong>, <strong>ортопедическое лечение</strong>. </p>
<p>Многолетний опыт работы сотрудников стоматологии <strong>МИРАДЕНТ</strong> показывает, что до 80% посетителей, получив первую консультацию  в нашей клинике,  стали нашими постоянными пациентами благодаря высокому качеству оказываемых услуг, доступным  ценам и серьезному отношению к вопросам медицинской профилактики. Немаловажным, располагающим пациентов фактором является добросовестное выполнение санитарно-гигиенических норм и требований: основная масса материалов и инструментария – одноразового использования, инструментарий для многоразового использования проходит многократную предстерилизaционную обработку  современными дезинфицирующими средствами и несколько видов стерилизации.</p>
<p>Стоматологическую клинику <strong>МИРАДЕНТ</strong> стоит посетить даже при отсутствии острой потребности в стоматологической помощи с целью  получения консультации врача и <strong>бесплатного комплексного профосмотра</strong>.  Пациент может получить предварительную информацию об услугах и их стоимости у администратора клиники, а также предварительно записаться на  осмотр, консультацию или лечение к врачу соответствующей специальности как по телефону, так и лично. </p>
  <p>Перед приемом, пациент заполняет стоматологическую карту и соглашение с клиникой на проведение лечения (эндодонтического, терапевтического, ортопедического, косметического). В стоматологической карте фиксируются гарантийные обязательства клиники перед пациентом. 
<strong>Стоматология МИРАДЕНТ</strong> предлагает своим клиентам различные варианты оплаты услуг: наличный и безналичный расчет (прямые платежи через страховые компании).</p>
</div>
    </td>
  </tr>
</table>

















</div>

</div> <!-- cat_ite_cont_m -->

<?php

}

else

   if ($_GET['pm'] == 4)

   {

?>

<script language="javascript" type="text/javascript">
	function show_hide(objectID){
		var object=document.getElementById(objectID);
		if (object.style.display=='none')
			object.style.display='block';
			else
			object.style.display='none';
			return;
	}
</script>

<div class="catalogue_item_cont_m"> 

	<div id="main_miradent">
				<table background="../root/msite/miradent/upper.jpg" height="380px" width="980px" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td style="padding:35px 0 0 40px;" height="125px"><a href="index.html"><img src="../root/msite/miradent/logo.png" border="0" align="left"/></a></td>
  </tr>
   <tr>
    <td>
    	<p align="left" style="font-size:20px; padding:5px 0 0 10px;font-weight:600; font-family:Times New Roman;">г. Донецк, пр-т Мира, 2</p> 
		<p align="left" style="font-size:20px; padding:5px 0 0 10px; font-weight:600; font-family:Times New Roman;">тел: 062 381-18-24; моб: 050 696-47-70</p>
		<p align="left" style="font-size:20px; padding:5px 0 0 10px;font-weight:600; font-family:Times New Roman;">МЦ «Блиц»: г. Донецк ул. Раздольная, 13</p>
		<p align="left" style="font-size:20px; padding:5px 0 0 10px; font-weight:600; font-family:Times New Roman;">тел: 062 389-33-04; моб: 050 057-43-78</p>      </td>
  </tr>
  <tr>
    <td height="50px">
    			<div id="menu_miradent">
                		<ul>
                        	<li id="mir_miradent"><a href="index.php?business_full=490&pm=2"><span style="text-align:center; font-size:18px; font-family:Times New Roman;">МИРАДЕНТ</span></a></li>
                            <li id="blic_miradent"><a href="index.php?business_full=490&pm=1"><span style="text-align:center; font-size:18px; font-family:Times New Roman;">Мед. центр</span> <span style="text-align:center; font-size:18px; font-family:Times New Roman;">БЛИЦ</span></a></li>
                            <li><a href="index.php?business_full=490&pm=3"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;">О нас</span></a></li>
                            <li><a href="index.php?business_full=490&pm=4"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;">Цены</span></a></li>
                            <li><a href="index.php?business_full=490&pm=5"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;">Вакансии</span></a></li>
                            <li id="link_r_miradent"><a href="index.php?business_full=490&pm=6"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;">Контакты</span></a></li>
                        </ul>
                </div>       
    </td>
  </tr>
</table>
<table id="tab_content_miradent" width="970px" align="center" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td id="left_content_miradent">
     <br />
      <a href="javascript:show_hide('est_rev_content_miradent')"><br /><br /><br /><span>Эстетическая</span><br /><span>Реставрация</span></a>
        	  	<br />
      <a href="javascript:show_hide('otbel_content_miradent')"><br /><br /><br /><span>Отбеливание</span><br /><span>системой</span><br /><span>"Beyond"</span></a> 
        	    <br />
   	  <a href="javascript:show_hide('ortoped_content_miradent')"><br /><br /><br /><span>Эндодонтическое</span><br /><span>лечение</span></a>
    </td>
    <td valign="top">
      <div id="text_content_miradent">
      <div id="est_rev_content_miradent">
      <h3>ЭСТЕТИЧЕСКАЯ РЕСТАВРАЦИЯ ЗУБОВ</h3>
    <p>Высокоразвитая цивилизация ставит перед стоматологом требования не только борьбы с болью и восстановления жевательной функции. Не менее важно в настоящее время сохранение и воссоздание неповторимой красоты здоровых зубов.</p>
   <p>Эту роль выполняет <strong>эстетическая реставрация</strong> – восстановление изначального цвета, формы и размера зуба.</p> 
   <p>Материалы для реставрации по твердости и прочности аналогичны твердым тканям зуба. Они разрабатываются в разных оттенках, что делает возможным воспроизвести в эстетической конструкции цветовые переливы природного живого зуба.</p>
   <p>Композиционные фотополимерные материалы послойно наносятся на подготовленный зуб в соответствии с цветом и структурой утраченных зубных тканей и отверждаются специальной лампой.</p>
   <p><span>Безболезненность, надежность, красота и естественность – вот цели профессионалов эстетической стоматологии!</span></p>

<h2>Эстетическая реставрация зубов : технологии.</h2>
<p>В  современном мире  космических технологий, высокой моды, открытых информационных границ безукоризненная улыбка открывает человеку безграничные возможности в личном общении и карьерном росте. 
Зубы человека отличаются сложностью и разнообразием формы, неповторимой структурой, богатством передачи цвета, блеском, прозрачностью. Все эти качества стоматолог стремится воссоздать в художественной реставрации, чтобы придать Вашей улыбке красоту и естественность.</p>
<p>Современные высокооснащенные лаборатории ведущих мировых фирм стоматологической продукции постоянно работают над созданием и усовершенствованием материалов для реставрации зубов. Многочисленный арсенал этих средств составляют фотополимерные материалы для восстановления жевательных групп зубов (в том числе, армированные - упроченные), жидкотекучие фотополимеры для плотной адаптации к поверхности, универсальные – для пломбирования любых зубных дефектов, материалы для художественной реставрации. Последние соответствуют тканям зуба по прочности и твердости, позволяют точно передать структурные цветовые переходы, опалесценцию и флюоресценцию зубной поверхности.</p>
<p>Обработка зуба под фотополимерные реставрации производится максимально щадяще. Сцепление материала с поверхностью осуществляется за счет микропроникновения связывающего агента (бонда) в межкристаллические пространства и обеспечивает так называемое интимное прикрепление.</p>
 <p>Если зуб значительно разрушен, его укрепляют по показаниям анкерным или световолоконным штифтом.
Фотоматериал послойно накладывается на зуб в соответствии со структурой утраченных зубных тканей, повторяя их цвет. Каждый слой отдельно отверждается  светом специальной лампы. Это делает конструкцию еще более прочной. Моделируя поверхность зуба, стоматолог повторяет бугорки, бороздки и другие элементы, характерные для строения здоровых зубов конкретного человека. Готовая реставрация корректируется по прикусу и полируется до блеска.</p> 
<p><strong>Художественная реставрация зубов</strong> подарит Вам здоровую улыбку и уверенность в собственной неповторимости.</p>
 <hr />
	</div>
    
  <div id="otbel_content_miradent">
	<h3>ОТБЕЛИВАНИЕ ЗУБОВ</h3>
    <p>Большинство людей в современном мире придает значение здоровью зубов и их внешнему виду! Сделайте свою улыбку неотразимой! Если Вы хотите иметь белые зубы и сногсшибательную улыбку, тогда <strong>система Бейонд</strong> – Ваш верный выбор. Ваша улыбка станет сияющей и белоснежной всего за 30 минут! Отбеливающая система обеспечивает максимально возможный эффект даже если ваши зубы потемнели от курения, употребления напитков, содержащих красители, утратили природную белизну вследствие применения лекарственных препаратов, таких как тетрациклин или покрылись пятнами из-за употребления антибиотиков, избытка фтора.</p>
<p><strong>Система</strong> «<strong>Beyond Whitening Accelerator</strong>» - лучший выбор для достижения белоснежной и здоровой улыбки быстро и эффективно. Всего лишь за один курс отбеливания убираются пятна, которые образовывались годами, цвет зубов улучшается в среднем на 10-14 оттенков. Степень улучшения цвета зубов пациент выбирает по своему желанию и согласно рекомендациям стоматолога. Инновационная программа акселератора позволяет подобрать каждому пациенту индивидуальный режим интенсивности отбеливания.</p>
<p>Процедура отбеливания по системе <strong>Бейонд</strong> заключается в нанесении специального отбеливающего геля на поверхность зубов, а затем его активации с помощью холодного света лампы «<strong>Beyond Whitening Accelerator</strong>». Отбеливающий гель основан на 35% перекиси водорода и других компонентах, которые улучшают результат, предупреждают возникновение чувствительности и укрепляют зубную эмаль.</p> 
<p>Процесс отбеливания зубов возможен благодаря способности пероксида водорода свободно проникать сквозь эмаль и распространяться по всем частям зуба. Пероксиды под воздействием активатора (акселератора) распадаются на кислородные радикалы, которые затем мигрируют между эмалевыми  призмами, разлагая любые окрашенные молекулы, структура зуба при этом не затрагивается. Эмаль, дентин, связующие материалы и пломбы не повреждаются отбеливающими веществами.</p>
<p><strong>Преимущества отбеливающей системы</strong> <strong>Бейонд</strong> над всеми существующих на мировом рынке системами отбеливания:</p>
		<ul>
        	<li>Комфортность и удобство: не требует никаких предварительных процедур, за исключением профессиональной гигиенической чистки; одномоментное отбеливание 16-20 зубов в течение 30 минут. Кратковременность процедуры исключает возникновение раздражения десен и околозубных тканей. Акселератор отбеливания работает в режиме низкой температуры, что снижает риск возникновения чувствительности зубов. </li>
            <li>Безопасность: акселератор отбеливания – мощная галогеновая лампа, излучающая холодный голубой свет, который фильтруется 12 000 световодами и системой оптических линз. Вредное ультрафиолетовое и инфракрасное излучение отсеивается, не достигая поверхности зубов. Излучение холодного света снижает уровень вредных бактерий в полости рта эффективнее дезинфицирующего ополаскивателя.</li>
        </ul>    
<p>При соблюдении всех рекомендаций по уходу за отбеленными зубами и использовании средств для поддержания эффекта в домашних условиях ваши зубы будут выглядеть прекрасно как после самой процедуры, так и на протяжении нескольких лет!</p>
<p>
<span><strong>Beyond Power Whitening System</strong> – самая мощная система косметического <strong>отбеливания зубов</strong> в настоящее время, это передовая технология, гарантирующая безопасность, комфорт и результативность. Подробнее о системе отбеливания на сайте </span><a href="http://beyonddent.com.ua">www.beyonddent.com.ua.</a></p>
<h2>ЗУБНЫЕ УКРАШЕНИЯ.</h2>
<p>В настоящее время широкой популярностью у людей самых разных возрастов пользуются<strong> зубные украшения</strong> – <strong>скайсы</strong>. Это могут быть простые стразы, кристаллы Сваровски или алмазы в золотой оправе. Разнообразие их формы и цвета дает возможность подобрать  для Вас нечто особенное.</p> 
<p>Украшения крепятся  на зубы без препаровки, т.е не нарушая структуру эмали, при помощи специального стоматологического фиксирующего материала . Снять украшение можно в любой момент, после чего зубы имеют свой первоначальный вид.</p>
<p>Скайсы способны подчеркнуть Вашу индивидуальность, сделать улыбку блистательной и неотразимой!</p>
 <hr />
	</div>    


 <div id="ortoped_content_miradent">

<h3>ЭНДОДОНТИЧЕСКОЕ ЛЕЧЕНИЕ</h3>
<p>Если вовремя не вылечить кариес, болезнь может распространиться на пульпу зуба (внутризубной нерв) и далее – на связочный аппарат зуба и костную ткань челюсти. Как следствие – сильные боли, отек, воспаление и удаление зуба.</p>  
<p><strong>Эндодонтическое лечение</strong> – это комплекс мероприятий, направленных на борьбу с инфекцией внутри зуба и возвращение зубу возможности нормально функционировать. <strong>Эндодонтия</strong> – одна из важнейших областей терапевтической стоматологии.  Она требует от специалиста четкого знания сложной анатомии корневых каналов и строгого соблюдения последовательности определенных манипуляций в процессе лечения.</p>
<p>Врач-эндодонт выполняет ряд задач:</p>
	<ul>
    	<li>обеспечение доступа к корневым каналам,</li>
        <li>прохождение канала до верхушки корня,</li>
        <li>удаление из канала инфицированных и мертвых тканей,</li>
        <li>придание каналу формы, необходимой для правильного пломбирования,</li>
        <li>медикаментозная обработка канала с целью окончательного удаления болезнетворных бактерий,</li>
        <li>герметичное запечатывание (пломбирование) канала специальными наполнителями.</li>
	</ul>
	
    <p>В сложных и запущенных случаях не удается провести лечение корней в одно посещение: бывает необходимо оставление открытого зуба, наложение лекарственного средства под временную пломбу либо временное пломбирование канала лечебной пастой.</p>
<p>Каждый этап эндодонтического лечения выполняется с применением новейшего оборудования, инструментов, материалов.</p> 
<p>Современная стоматология мирового уровня МИРАДЕНТ располагает значительным арсеналом средств и методов качественного и надежного лечения корней. Правильность лечения контролируется и подтверждается с помощью специального прибора – апекслокатора и рентгеновских снимков, выполняемых на высокотехнологичной рентгенустановке.</p>
<p>Метод подготовки и заполнения корневых каналов выбирается в зависимости от их формы и строения, диагноза и течения заболевания, а также от способа последующего восстановления зуба в целом.</p>

<p><strong>Стоматология МИРАДЕНТ</strong> применяем самые прогрессивные технологии <strong>обработки и пломбирования каналов</strong>, гарантирующие продление жизни и здоровья зубов на долгий срок, а также возможность их использования в различных ортопедических конструкциях.</p>

<h2>Обработка корневых каналов : технологии.</h2>
<p>Кариес зубов, распространяясь, вызывает воспаление пульпы зуба и околокорневой костной ткани. Современная стоматология позволяет спасти большинство таких зубов, не допустить их удаления.</p>
<p>Лечение в таких случаях заключается в специальной обработке и герметичном <strong>пломбировании каналов корня зуба</strong>. Обработка каналов направлена на удаление из канала инфицированных тканей и придание каналу формы, необходимой для проникновения лекарства и правильного пломбирования.</p>
<p>Каналы имеют сложную форму, ответвления, часто встречаются тонкие, изогнутые, труднопроходимые каналы. Для их обработки используются специальные ручные и вращающиеся инструменты, позволяющие убрать из просвета воспаленные ткани, сделать стенки гладкими. В процессе обработки канал промывается специальными антисептическими растворами, нейтрализующими болезнетворные бактерии.</p>
<p>На протяжении всей работы стоматолог координирует свои действия по показаниям специального прибора – апекслокатора, при необходимости проводит дополнительный контроль с помощью рентгеновского снимка.</p>

<p>Правильная  предварительная обработка обеспечивает последующее качественное пломбирование канала и сохранение  зуба на длительный срок.</p>

<h2>Повторное эндодонтическое лечение : технологии.</h2>
<p>Нередко пациенты обращаются к стоматологу по поводу зубов, которые уже были ранее  пролечены эндодонтически в  другой клинике. Такие зубы нуждаются в повторном эндодонтическом лечении, и чаще всего их удается спасти.</p>
<p>Перед тем как поступить к перелечиванию канала, специалист изучает рентгеновский снимок. <strong>Повторное эндодонтическое лечение</strong> заключается в удалении из канала старого пломбировочного материала, прохождение и формирование канала на всю длину, обработка лечебными дезинфицирующими растворами и плотное пломбирование канала до верхушки по одной из современных методик. </p>
<p>Способ повторного лечения зависит от того, какой пломбировочный материал находится в канале, от формы и проходимости канала.  Для удаления из канала старой пломбировочной массы используются специально разработанные вращающиеся никель-титановые инструменты. В сложных случаях, когда каналы были прежде заполнены цементом, применяется ультразвуковой аппарат с соответствующими насадками. Ультразвук дробит застывший цемент и способствует его выведению. Кроме того, он во много раз усиливает бактерицидное  действие дезинфицирующий средств, увеличивает шансы на успех в лечении. </p>
<p>Герметичное  заполнение подготовленного корневого канала с последующим восстановлением зуба фотополимерным материалом позволяет остановить воспалительные явления в костной ткани челюсти, предотвратить обострение процесса и удаление зуба.</p>

<h2>Пломбирование корневого канала : технологии.</h2>
<p><strong>Пломбирование каналов</strong> является логическим итогом <strong>эндодонтического лечения</strong>. Наиболее верный шанс клинического успеха достигается тогда, когда система корневых каналов полностью, со всей своей сложностью, будет запломбирована на своем полном апикальном и латеральном протяжении.</p>
<p>Большинство современных методик пломбирования заключаются в плотном закрытии канала гуттаперчей с использованием силера – наполнителя – лечебной пасты, застывающей в канале после пломбирования.  Речь идет о методах латеральной конденсации гуттаперчи, конусного штифта, центрированной и вертикальной конденсации горячей гуттаперчи. Эти методики отличаются по степени уплотнения и распространения, способу введения, сложности, необходимости специального оборудования и стоимости. </p>
<p>При латеральной конденсации в канал, заполненный силером, вводится основной гуттаперчевый штифт, плотно закрывающий верхушечное отверстие. Далее, он уплотняется специальным инструментом и вводится следующий один штифт. Процедура повторяется до тех пор, пока просвет канала, имеющий конусную форму, не будет заполнен на всем протяжении. </p>
<p>Если канал предварительно обработан и сформирован с помощью специальной системы вращающихся инструментов, имеется возможность заполнить его с помощью одного конусного гуттаперчевого штифта, точно соответствующего форме подготовленного канала. Штифт идеально запечатывает верхушечное отверстие и весь просвет канала, делает ненужным введение  и уплотнение множества дополнительных штифтов. Это значительно сокращает процедуру, не отражаясь на ее качестве.</p> 
<p>В настоящее время мало кто из стоматологов отрицает наличие микроканальцев и множественных ответвлений корневого канала, которые также нуждаются в пломбировании.  Именно поэтому разработаны методики  <strong>3-D (трехмерной)</strong> <strong>обтурации</strong>.</p>
<p>Техника обтурации центрированной конденсацией (термафил) действенно и эффективно продвигает пломбирующие материалы через систему корневого канала движением конденсирующего устройства (предварительно нагретого носителя) в центре термопластического материала, такого как гуттаперча. Пломбирующий материал, смазанный силером, смещается в сторону коронки, так как конденсирующее устройство движется к верхушке, создавая эффект тока материала на стенки основного канала. Это пломбирует боковые канальцы, дополнительные канальцы, бороздки, петли, ответвления и перешейкипо ходу инструмента. Для работы в этой технике дополнительно требуются гуттаперчевые обтураторы на носителе и специальное устройство для их разогрева.</p>
<p>Для техники постоянной волны (Є&Q+ Plus) выбирается электрически нагреваемый уплотнитель - плаггер (Sybron Endo), соответствующей  конусности. Стенки канала смазываются силером, подготовленный гуттаперчевый штифт вводится до верхушки. Излишки гуттаперчи специальным образом убираются , а плаггер уплотняет гуттаперчу до уровня 4мм от верхушечного отвертстия, обеспечивая максимальное проникновение материала во все ответвления и канальцы, герметизируя все возможные пути распространения бактерий. <strong>Пломбирование верхних 2\3 канала</strong> выполняется при помощи пистолета или новым, встроенным, машинным пресс-шприцем.</p>
<p>Раньше было сложно запломбировать систему корневого канала в трехмерном измерении. Сейчас  этот надежный метод, предполагающий наличие дополнительной дорогостоящей аппаратуры и грамотного специалиста, полностью оправдывает возложенные на него ожидания. Кроме гуттаперчи, <strong>для пломбирования каналов</strong> применяются недавно разработанные материалы (эпифания, резилон, ПроРут МТА), которые используются по показаниям в соответствующих техниках пломбирования и значительно расширяют возможности сохранения зубов, рекомендованных к удалению. </p>
<h2> Аппаратные методы диагностики</h2>
    <p>Для постановки точного диагноза и подтверждения качества лечения в стоматологической клинике МИРАДЕНТ проводятся рентгенологические исследования на современном оборудовании.</p>
<p>Стоматологические установки оснащены интраоральными камерами Vista Cam ведущего немецкого производителя – фирмы Durr Dental. 
Камера многократно увеличивает изображение и переводит его на плоский экран. Это позволяет стоматологу рассмотреть мельчайшие детали на рабочем поле, а также продемонстрировать пациенту элементы зубных отложений, скрытые кариозные полости, исходное состояние больного зуба, этапы и результат проведения реставрации.</p>
<p>С помощью интраоральной камеры можно получить фотоснимки зубов до и после стоматологических процедур.  
Использование интраоральной камеры повышает информированность пациента  о ходе проводимых лечебных действий,  позволяет пациенту чувствовать себя спокойнее и увереннее на приеме у стоматолога.</p>  
 <hr />      
</div>

   <h3>СТОМАТОЛОГИЯ МИРАДЕНТ : ЦЕНЫ</h3>
<h1>Осмотр и консультация врача – бесплатно!</h1>
<h4>ПРЕЙСКУРАНТ </h4>
<h6>на отдельные виды стоматологических услуг</h6>


<table id="price_miradent" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td><h3>Подготовка зуба к протезированию</h3></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><h3>Восстановление культи зуба</h3></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td> - вкладка металлическая неразборная NPG </td>
    <td>350-400</td>
  </tr>
  <tr>
    <td>-вкладка металлическая  NPG разборная</td>
    <td>450-550</td>
  </tr>
  <tr>
    <td><h3>Изготовление несъемных протезов</h3></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>Стальная штампованная коронка</td>
    <td>250</td>
  </tr>
  <tr>
    <td>Зуб литой стальной в мостовидном протезе</td>
    <td>250</td>
  </tr>
  <tr>
    <td>Зуб литой,  облицованный фасеткой</td>
    <td>300</td>
  </tr>
  <tr>
    <td>Коронка с облицовкой из пластмассы</td>
    <td>400</td>
  </tr>
  <tr>
    <td>Коронка литая из КХС</td>
    <td>400</td>
  </tr>
  <tr>
    <td>Коронка литая из NPG (желтый металл)</td>
    <td>350-400</td>
  </tr>
  <tr>
    <td>Металлокерамическая коронка</td>
    <td>800</td>
  </tr>
  <tr>
    <td>Зуб металлокерамический</td>
    <td>800</td>
  </tr>
  <tr>
    <td>Вкладка керамическая безметалловая</td>
    <td>800</td>
  </tr>
  <tr>
    <td>Безметалловая керамика (винир-коронка) Ivoclar  Pom</td>
    <td>1200-1500</td>
  </tr>
  <tr>
    <td><h3>Изготовление съемных протезов</h3></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>Частичный съемный протез</td>
    <td>800</td>
  </tr>
  <tr>
    <td>Полный съемный протез</td>
    <td>800</td>
  </tr>
  <tr>
    <td>Изготовление индивидуальной ложки  (по показаниям)</td>
    <td>100</td>
  </tr>
  <tr>
    <td><h3>Изготовление бюгельных протезов</h3></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>Бюгельный (опирающийся)  протез</td>
    <td>3500</td>
  </tr>
  <tr>
    <td>Замковое крепление (аттачмен) в бюгельном протезе</td>
    <td>300</td>
  </tr>
  <tr>
    <td><h1>ТЕРАПИЯ</h1></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><h3>Анестезия карпульным шприцем:</h3></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>Септанест (Франция)</td>
    <td>30</td>
  </tr>
  <tr>
    <td>Убистезин (Германия)</td>
    <td>35</td>
  </tr>
  <tr>
    <td>Мепивастезин (Германия)</td>
    <td>30</td>
  </tr>
  <tr>
    <td>Ультракаин (Германия)</td>
    <td>35</td>
  </tr>
  <tr>
    <td>Артифрин-здоровье-форте</td>
    <td>25</td>
  </tr>
  <tr>
    <td>Артикаин</td>
    <td>25</td>
  </tr>
  <tr>
    <td><h3>Лечение осложненного кариеса (пульпит, периодонтит)</h3></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>однокорневого зуба (Epiphany + гуттаперча)</td>
    <td>300-350</td>
  </tr>
  <tr>
    <td>двухкорневого зуба (Epiphany + гуттаперча)</td>
    <td>350-400</td>
  </tr>
  <tr>
    <td>трехкорневого зуба (Epiphany + гуттаперча)</td>
    <td>450-500;</td>
  </tr>
  <tr>
    <td>однокорневого зуба (AH Plus + гуттаперча)</td>
    <td>300-350</td>
  </tr>
  <tr>
    <td>двухкорневого зуба (AH Plus + гуттаперча)</td>
    <td>350-400</td>
  </tr>
  <tr>
    <td>трехкорневого зуба (AH Plus + гуттаперча)</td>
    <td>450-500</td>
  </tr>
  <tr>
    <td>однокорневого зуба (горячая гуттаперча Є&Q+ Plus )</td>
    <td>400</td>
  </tr>
  <tr>
    <td>двухкорневого зуба (горячая гуттаперча Є&Q+ Plus)</td>
    <td>500</td>
  </tr>
  <tr>
    <td>трехкорневого зуба (горячая гуттаперча Є&Q+ Plus)</td>
    <td>600</td>
  </tr>
  <tr>
    <td><h3>Наложение пломбы из фотополимеризующегося материала</h3></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>«Градиа Дайрект» (Япония)</td>
    <td>250-350</td>
  </tr>
  <tr>
    <td>«Амелоген Универсал» (США)</td>
    <td>250-350</td>
  </tr>
  <tr>
    <td>«Карисма» (Германия)</td>
    <td>230-300</td>
  </tr>
  <tr>
    <td>«Карисма Опал» (Германия)</td>
    <td>270-370</td>
  </tr>
  <tr>
    <td>«Солитер» (Германия)</td>
    <td>250-350</td>
  </tr>
  <tr>
    <td>«Тетрик Церам» (Германия)</td>
    <td>250-350</td>
  </tr>
  <tr>
    <td>«Эстет Х-НD» (Германия)</td>
    <td>270-370</td>
  </tr>
  <tr>
    <td>«Энемел Плюс» (Италия)</td>
    <td>350-450</td>
  </tr>
  <tr>
    <td><h3>Реставрация коронковой части зуба:</h3></td>
    <td>&nbsp;</td>
  </tr>
   <tr>
    <td>«Филтек суприм», «Эстет Х-HD», «Карисма Опал»,  «Градиа Дайрект»</td>
    <td>З50-500</td>
  </tr>
   <tr>
    <td>«Энемел Плюс»</td>
    <td>600-700</td>
  </tr>
   <tr>
    <td><h3>Снятие зубных отложений:</h3></td>
    <td>&nbsp;</td>
  </tr>
   <tr>
    <td>ультразвуковой пьезоскайлер</td>
    <td>250-350</td>
  </tr>
   <tr>
    <td>содоструйный аппарат Air Flow</td>
    <td>350-450</td>
  </tr>
   <tr>
    <td><h3>Отбеливание зубов:</h3></td>
    <td>&nbsp;</td>
  </tr>
   <tr>
    <td>Система «Опалесценс Екстра» Ультрадент (США)</td>
    <td>30 1 ед/1 пос</td>
  </tr>
   <tr>
    <td>Система «Макс 5» Бейонд  ПОЛЮС (США):</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>- одномоментное отбеливание всех зубов фронтального ряда в одно посещение</td>
    <td>1200-1400</td>
  </tr>
  <tr>
    <td>- отбеливание одного зуба (точечное)(США)</td>
    <td>60 1ед/1пос</td>
  </tr>
</table>
 
</div>
    </td>
  </tr>
</table>

















</div>


</div> <!-- cat_ite_cont_m -->

<?php

}

else

   if ($_GET['pm'] == 5)

   {

?>

<script language="javascript" type="text/javascript">
	function show_hide(objectID){
		var object=document.getElementById(objectID);
		if (object.style.display=='none')
			object.style.display='block';
			else
			object.style.display='none';
			return;
	}
</script>

<div class="catalogue_item_cont_m"> 

	<div id="main_miradent">
				<table background="../root/msite/miradent/upper.jpg" height="380px" width="980px" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td style="padding:35px 0 0 40px;" height="125px"><a href="index.html"><img src="../root/msite/miradent/logo.png" border="0" align="left"/></a></td>
  </tr>
   <tr>
    <td>
    	<p align="left" style="font-size:20px; padding:5px 0 0 10px;font-weight:600; font-family:Times New Roman;">г. Донецк, пр-т Мира, 2</p> 
		<p align="left" style="font-size:20px; padding:5px 0 0 10px; font-weight:600; font-family:Times New Roman;">тел: 062 381-18-24; моб: 050 696-47-70</p>
		<p align="left" style="font-size:20px; padding:5px 0 0 10px;font-weight:600; font-family:Times New Roman;">МЦ «Блиц»: г. Донецк ул. Раздольная, 13</p>
		<p align="left" style="font-size:20px; padding:5px 0 0 10px; font-weight:600; font-family:Times New Roman;">тел: 062 389-33-04; моб: 050 057-43-78</p>      </td>
  </tr>
  <tr>
    <td height="50px">
    			<div id="menu_miradent">
                		<ul>
                        	<li id="mir_miradent"><a href="index.php?business_full=490&pm=2"><span style="text-align:center; font-size:18px; font-family:Times New Roman;">МИРАДЕНТ</span></a></li>
                            <li id="blic_miradent"><a href="index.php?business_full=490&pm=1"><span style="text-align:center; font-size:18px; font-family:Times New Roman;">Мед. центр</span> <span style="text-align:center; font-size:18px; font-family:Times New Roman;">БЛИЦ</span></a></li>
                            <li><a href="index.php?business_full=490&pm=3"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;">О нас</span></a></li>
                            <li><a href="index.php?business_full=490&pm=4"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;">Цены</span></a></li>
                            <li><a href="index.php?business_full=490&pm=5"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;">Вакансии</span></a></li>
                            <li id="link_r_miradent"><a href="index.php?business_full=490&pm=6"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;">Контакты</span></a></li>
                        </ul>
                </div>       
    </td>
  </tr>
</table>
<table id="tab_content_miradent" width="970px" align="center" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td id="left_content_miradent">
     <br />
      <a href="javascript:show_hide('est_rev_content_miradent')"><br /><br /><br /><span>Эстетическая</span><br /><span>Реставрация</span></a>
        	  	<br />
      <a href="javascript:show_hide('otbel_content_miradent')"><br /><br /><br /><span>Отбеливание</span><br /><span>системой</span><br /><span>"Beyond"</span></a> 
        	    <br />
   	  <a href="javascript:show_hide('ortoped_content_miradent')"><br /><br /><br /><span>Эндодонтическое</span><br /><span>лечение</span></a>
    </td>
    <td valign="top">
      <div id="text_content_miradent">
      <div id="est_rev_content_miradent">
      <h3>ЭСТЕТИЧЕСКАЯ РЕСТАВРАЦИЯ ЗУБОВ</h3>
    <p>Высокоразвитая цивилизация ставит перед стоматологом требования не только борьбы с болью и восстановления жевательной функции. Не менее важно в настоящее время сохранение и воссоздание неповторимой красоты здоровых зубов.</p>
   <p>Эту роль выполняет <strong>эстетическая реставрация</strong> – восстановление изначального цвета, формы и размера зуба.</p> 
   <p>Материалы для реставрации по твердости и прочности аналогичны твердым тканям зуба. Они разрабатываются в разных оттенках, что делает возможным воспроизвести в эстетической конструкции цветовые переливы природного живого зуба.</p>
   <p>Композиционные фотополимерные материалы послойно наносятся на подготовленный зуб в соответствии с цветом и структурой утраченных зубных тканей и отверждаются специальной лампой.</p>
   <p><span>Безболезненность, надежность, красота и естественность – вот цели профессионалов эстетической стоматологии!</span></p>

<h2>Эстетическая реставрация зубов : технологии.</h2>
<p>В  современном мире  космических технологий, высокой моды, открытых информационных границ безукоризненная улыбка открывает человеку безграничные возможности в личном общении и карьерном росте. 
Зубы человека отличаются сложностью и разнообразием формы, неповторимой структурой, богатством передачи цвета, блеском, прозрачностью. Все эти качества стоматолог стремится воссоздать в художественной реставрации, чтобы придать Вашей улыбке красоту и естественность.</p>
<p>Современные высокооснащенные лаборатории ведущих мировых фирм стоматологической продукции постоянно работают над созданием и усовершенствованием материалов для реставрации зубов. Многочисленный арсенал этих средств составляют фотополимерные материалы для восстановления жевательных групп зубов (в том числе, армированные - упроченные), жидкотекучие фотополимеры для плотной адаптации к поверхности, универсальные – для пломбирования любых зубных дефектов, материалы для художественной реставрации. Последние соответствуют тканям зуба по прочности и твердости, позволяют точно передать структурные цветовые переходы, опалесценцию и флюоресценцию зубной поверхности.</p>
<p>Обработка зуба под фотополимерные реставрации производится максимально щадяще. Сцепление материала с поверхностью осуществляется за счет микропроникновения связывающего агента (бонда) в межкристаллические пространства и обеспечивает так называемое интимное прикрепление.</p>
 <p>Если зуб значительно разрушен, его укрепляют по показаниям анкерным или световолоконным штифтом.
Фотоматериал послойно накладывается на зуб в соответствии со структурой утраченных зубных тканей, повторяя их цвет. Каждый слой отдельно отверждается  светом специальной лампы. Это делает конструкцию еще более прочной. Моделируя поверхность зуба, стоматолог повторяет бугорки, бороздки и другие элементы, характерные для строения здоровых зубов конкретного человека. Готовая реставрация корректируется по прикусу и полируется до блеска.</p> 
<p><strong>Художественная реставрация зубов</strong> подарит Вам здоровую улыбку и уверенность в собственной неповторимости.</p>
 <hr />
	</div>
    
  <div id="otbel_content_miradent">
	<h3>ОТБЕЛИВАНИЕ ЗУБОВ</h3>
    <p>Большинство людей в современном мире придает значение здоровью зубов и их внешнему виду! Сделайте свою улыбку неотразимой! Если Вы хотите иметь белые зубы и сногсшибательную улыбку, тогда <strong>система Бейонд</strong> – Ваш верный выбор. Ваша улыбка станет сияющей и белоснежной всего за 30 минут! Отбеливающая система обеспечивает максимально возможный эффект даже если ваши зубы потемнели от курения, употребления напитков, содержащих красители, утратили природную белизну вследствие применения лекарственных препаратов, таких как тетрациклин или покрылись пятнами из-за употребления антибиотиков, избытка фтора.</p>
<p><strong>Система</strong> «<strong>Beyond Whitening Accelerator</strong>» - лучший выбор для достижения белоснежной и здоровой улыбки быстро и эффективно. Всего лишь за один курс отбеливания убираются пятна, которые образовывались годами, цвет зубов улучшается в среднем на 10-14 оттенков. Степень улучшения цвета зубов пациент выбирает по своему желанию и согласно рекомендациям стоматолога. Инновационная программа акселератора позволяет подобрать каждому пациенту индивидуальный режим интенсивности отбеливания.</p>
<p>Процедура отбеливания по системе <strong>Бейонд</strong> заключается в нанесении специального отбеливающего геля на поверхность зубов, а затем его активации с помощью холодного света лампы «<strong>Beyond Whitening Accelerator</strong>». Отбеливающий гель основан на 35% перекиси водорода и других компонентах, которые улучшают результат, предупреждают возникновение чувствительности и укрепляют зубную эмаль.</p> 
<p>Процесс отбеливания зубов возможен благодаря способности пероксида водорода свободно проникать сквозь эмаль и распространяться по всем частям зуба. Пероксиды под воздействием активатора (акселератора) распадаются на кислородные радикалы, которые затем мигрируют между эмалевыми  призмами, разлагая любые окрашенные молекулы, структура зуба при этом не затрагивается. Эмаль, дентин, связующие материалы и пломбы не повреждаются отбеливающими веществами.</p>
<p><strong>Преимущества отбеливающей системы</strong> <strong>Бейонд</strong> над всеми существующих на мировом рынке системами отбеливания:</p>
		<ul>
        	<li>Комфортность и удобство: не требует никаких предварительных процедур, за исключением профессиональной гигиенической чистки; одномоментное отбеливание 16-20 зубов в течение 30 минут. Кратковременность процедуры исключает возникновение раздражения десен и околозубных тканей. Акселератор отбеливания работает в режиме низкой температуры, что снижает риск возникновения чувствительности зубов. </li>
            <li>Безопасность: акселератор отбеливания – мощная галогеновая лампа, излучающая холодный голубой свет, который фильтруется 12 000 световодами и системой оптических линз. Вредное ультрафиолетовое и инфракрасное излучение отсеивается, не достигая поверхности зубов. Излучение холодного света снижает уровень вредных бактерий в полости рта эффективнее дезинфицирующего ополаскивателя.</li>
        </ul>    
<p>При соблюдении всех рекомендаций по уходу за отбеленными зубами и использовании средств для поддержания эффекта в домашних условиях ваши зубы будут выглядеть прекрасно как после самой процедуры, так и на протяжении нескольких лет!</p>
<p>
<span><strong>Beyond Power Whitening System</strong> – самая мощная система косметического <strong>отбеливания зубов</strong> в настоящее время, это передовая технология, гарантирующая безопасность, комфорт и результативность. Подробнее о системе отбеливания на сайте </span><a href="http://beyonddent.com.ua">www.beyonddent.com.ua.</a></p>
<h2>ЗУБНЫЕ УКРАШЕНИЯ.</h2>
<p>В настоящее время широкой популярностью у людей самых разных возрастов пользуются<strong> зубные украшения</strong> – <strong>скайсы</strong>. Это могут быть простые стразы, кристаллы Сваровски или алмазы в золотой оправе. Разнообразие их формы и цвета дает возможность подобрать  для Вас нечто особенное.</p> 
<p>Украшения крепятся  на зубы без препаровки, т.е не нарушая структуру эмали, при помощи специального стоматологического фиксирующего материала . Снять украшение можно в любой момент, после чего зубы имеют свой первоначальный вид.</p>
<p>Скайсы способны подчеркнуть Вашу индивидуальность, сделать улыбку блистательной и неотразимой!</p>
 <hr />
	</div>    


 <div id="ortoped_content_miradent">

<h3>ЭНДОДОНТИЧЕСКОЕ ЛЕЧЕНИЕ</h3>
<p>Если вовремя не вылечить кариес, болезнь может распространиться на пульпу зуба (внутризубной нерв) и далее – на связочный аппарат зуба и костную ткань челюсти. Как следствие – сильные боли, отек, воспаление и удаление зуба.</p>  
<p><strong>Эндодонтическое лечение</strong> – это комплекс мероприятий, направленных на борьбу с инфекцией внутри зуба и возвращение зубу возможности нормально функционировать. <strong>Эндодонтия</strong> – одна из важнейших областей терапевтической стоматологии.  Она требует от специалиста четкого знания сложной анатомии корневых каналов и строгого соблюдения последовательности определенных манипуляций в процессе лечения.</p>
<p>Врач-эндодонт выполняет ряд задач:</p>
	<ul>
    	<li>обеспечение доступа к корневым каналам,</li>
        <li>прохождение канала до верхушки корня,</li>
        <li>удаление из канала инфицированных и мертвых тканей,</li>
        <li>придание каналу формы, необходимой для правильного пломбирования,</li>
        <li>медикаментозная обработка канала с целью окончательного удаления болезнетворных бактерий,</li>
        <li>герметичное запечатывание (пломбирование) канала специальными наполнителями.</li>
	</ul>
	
    <p>В сложных и запущенных случаях не удается провести лечение корней в одно посещение: бывает необходимо оставление открытого зуба, наложение лекарственного средства под временную пломбу либо временное пломбирование канала лечебной пастой.</p>
<p>Каждый этап эндодонтического лечения выполняется с применением новейшего оборудования, инструментов, материалов.</p> 
<p>Современная стоматология мирового уровня МИРАДЕНТ располагает значительным арсеналом средств и методов качественного и надежного лечения корней. Правильность лечения контролируется и подтверждается с помощью специального прибора – апекслокатора и рентгеновских снимков, выполняемых на высокотехнологичной рентгенустановке.</p>
<p>Метод подготовки и заполнения корневых каналов выбирается в зависимости от их формы и строения, диагноза и течения заболевания, а также от способа последующего восстановления зуба в целом.</p>

<p><strong>Стоматология МИРАДЕНТ</strong> применяем самые прогрессивные технологии <strong>обработки и пломбирования каналов</strong>, гарантирующие продление жизни и здоровья зубов на долгий срок, а также возможность их использования в различных ортопедических конструкциях.</p>

<h2>Обработка корневых каналов : технологии.</h2>
<p>Кариес зубов, распространяясь, вызывает воспаление пульпы зуба и околокорневой костной ткани. Современная стоматология позволяет спасти большинство таких зубов, не допустить их удаления.</p>
<p>Лечение в таких случаях заключается в специальной обработке и герметичном <strong>пломбировании каналов корня зуба</strong>. Обработка каналов направлена на удаление из канала инфицированных тканей и придание каналу формы, необходимой для проникновения лекарства и правильного пломбирования.</p>
<p>Каналы имеют сложную форму, ответвления, часто встречаются тонкие, изогнутые, труднопроходимые каналы. Для их обработки используются специальные ручные и вращающиеся инструменты, позволяющие убрать из просвета воспаленные ткани, сделать стенки гладкими. В процессе обработки канал промывается специальными антисептическими растворами, нейтрализующими болезнетворные бактерии.</p>
<p>На протяжении всей работы стоматолог координирует свои действия по показаниям специального прибора – апекслокатора, при необходимости проводит дополнительный контроль с помощью рентгеновского снимка.</p>

<p>Правильная  предварительная обработка обеспечивает последующее качественное пломбирование канала и сохранение  зуба на длительный срок.</p>

<h2>Повторное эндодонтическое лечение : технологии.</h2>
<p>Нередко пациенты обращаются к стоматологу по поводу зубов, которые уже были ранее  пролечены эндодонтически в  другой клинике. Такие зубы нуждаются в повторном эндодонтическом лечении, и чаще всего их удается спасти.</p>
<p>Перед тем как поступить к перелечиванию канала, специалист изучает рентгеновский снимок. <strong>Повторное эндодонтическое лечение</strong> заключается в удалении из канала старого пломбировочного материала, прохождение и формирование канала на всю длину, обработка лечебными дезинфицирующими растворами и плотное пломбирование канала до верхушки по одной из современных методик. </p>
<p>Способ повторного лечения зависит от того, какой пломбировочный материал находится в канале, от формы и проходимости канала.  Для удаления из канала старой пломбировочной массы используются специально разработанные вращающиеся никель-титановые инструменты. В сложных случаях, когда каналы были прежде заполнены цементом, применяется ультразвуковой аппарат с соответствующими насадками. Ультразвук дробит застывший цемент и способствует его выведению. Кроме того, он во много раз усиливает бактерицидное  действие дезинфицирующий средств, увеличивает шансы на успех в лечении. </p>
<p>Герметичное  заполнение подготовленного корневого канала с последующим восстановлением зуба фотополимерным материалом позволяет остановить воспалительные явления в костной ткани челюсти, предотвратить обострение процесса и удаление зуба.</p>

<h2>Пломбирование корневого канала : технологии.</h2>
<p><strong>Пломбирование каналов</strong> является логическим итогом <strong>эндодонтического лечения</strong>. Наиболее верный шанс клинического успеха достигается тогда, когда система корневых каналов полностью, со всей своей сложностью, будет запломбирована на своем полном апикальном и латеральном протяжении.</p>
<p>Большинство современных методик пломбирования заключаются в плотном закрытии канала гуттаперчей с использованием силера – наполнителя – лечебной пасты, застывающей в канале после пломбирования.  Речь идет о методах латеральной конденсации гуттаперчи, конусного штифта, центрированной и вертикальной конденсации горячей гуттаперчи. Эти методики отличаются по степени уплотнения и распространения, способу введения, сложности, необходимости специального оборудования и стоимости. </p>
<p>При латеральной конденсации в канал, заполненный силером, вводится основной гуттаперчевый штифт, плотно закрывающий верхушечное отверстие. Далее, он уплотняется специальным инструментом и вводится следующий один штифт. Процедура повторяется до тех пор, пока просвет канала, имеющий конусную форму, не будет заполнен на всем протяжении. </p>
<p>Если канал предварительно обработан и сформирован с помощью специальной системы вращающихся инструментов, имеется возможность заполнить его с помощью одного конусного гуттаперчевого штифта, точно соответствующего форме подготовленного канала. Штифт идеально запечатывает верхушечное отверстие и весь просвет канала, делает ненужным введение  и уплотнение множества дополнительных штифтов. Это значительно сокращает процедуру, не отражаясь на ее качестве.</p> 
<p>В настоящее время мало кто из стоматологов отрицает наличие микроканальцев и множественных ответвлений корневого канала, которые также нуждаются в пломбировании.  Именно поэтому разработаны методики  <strong>3-D (трехмерной)</strong> <strong>обтурации</strong>.</p>
<p>Техника обтурации центрированной конденсацией (термафил) действенно и эффективно продвигает пломбирующие материалы через систему корневого канала движением конденсирующего устройства (предварительно нагретого носителя) в центре термопластического материала, такого как гуттаперча. Пломбирующий материал, смазанный силером, смещается в сторону коронки, так как конденсирующее устройство движется к верхушке, создавая эффект тока материала на стенки основного канала. Это пломбирует боковые канальцы, дополнительные канальцы, бороздки, петли, ответвления и перешейкипо ходу инструмента. Для работы в этой технике дополнительно требуются гуттаперчевые обтураторы на носителе и специальное устройство для их разогрева.</p>
<p>Для техники постоянной волны (Є&Q+ Plus) выбирается электрически нагреваемый уплотнитель - плаггер (Sybron Endo), соответствующей  конусности. Стенки канала смазываются силером, подготовленный гуттаперчевый штифт вводится до верхушки. Излишки гуттаперчи специальным образом убираются , а плаггер уплотняет гуттаперчу до уровня 4мм от верхушечного отвертстия, обеспечивая максимальное проникновение материала во все ответвления и канальцы, герметизируя все возможные пути распространения бактерий. <strong>Пломбирование верхних 2\3 канала</strong> выполняется при помощи пистолета или новым, встроенным, машинным пресс-шприцем.</p>
<p>Раньше было сложно запломбировать систему корневого канала в трехмерном измерении. Сейчас  этот надежный метод, предполагающий наличие дополнительной дорогостоящей аппаратуры и грамотного специалиста, полностью оправдывает возложенные на него ожидания. Кроме гуттаперчи, <strong>для пломбирования каналов</strong> применяются недавно разработанные материалы (эпифания, резилон, ПроРут МТА), которые используются по показаниям в соответствующих техниках пломбирования и значительно расширяют возможности сохранения зубов, рекомендованных к удалению. </p>
<h2> Аппаратные методы диагностики</h2>
    <p>Для постановки точного диагноза и подтверждения качества лечения в стоматологической клинике МИРАДЕНТ проводятся рентгенологические исследования на современном оборудовании.</p>
<p>Стоматологические установки оснащены интраоральными камерами Vista Cam ведущего немецкого производителя – фирмы Durr Dental. 
Камера многократно увеличивает изображение и переводит его на плоский экран. Это позволяет стоматологу рассмотреть мельчайшие детали на рабочем поле, а также продемонстрировать пациенту элементы зубных отложений, скрытые кариозные полости, исходное состояние больного зуба, этапы и результат проведения реставрации.</p>
<p>С помощью интраоральной камеры можно получить фотоснимки зубов до и после стоматологических процедур.  
Использование интраоральной камеры повышает информированность пациента  о ходе проводимых лечебных действий,  позволяет пациенту чувствовать себя спокойнее и увереннее на приеме у стоматолога клиники МИРАДЕНТ.</p>  
 <hr />      
</div>

   <h3>СТОМАТОЛОГИЯ МИРАДЕНТ (Украина, Донецк): ВАКАНСИИ</h3>
<p>Стоматологической клинике на постоянную работу требуется врач-стоматолог с опытом работы от 5 лет. Наличие личной лицензии врача приветствуется.</p>
</div>
    </td>
  </tr>
</table>

















</div>


</div> <!-- cat_ite_cont_m -->

<?php

}

else

   if ($_GET['pm'] == 6)

   {

?>

<script language="javascript" type="text/javascript">
	function show_hide(objectID){
		var object=document.getElementById(objectID);
		if (object.style.display=='none')
			object.style.display='block';
			else
			object.style.display='none';
			return;
	}
</script>

<div class="catalogue_item_cont_m"> 

	<div id="main_miradent">
				<table background="../root/msite/miradent/upper.jpg" height="380px" width="980px" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td style="padding:35px 0 0 40px;" height="125px"><a href="index.html"><img src="../root/msite/miradent/logo.png" border="0" align="left"/></a></td>
  </tr>
   <tr>
    <td>
    	<p align="left" style="font-size:20px; padding:5px 0 0 10px;font-weight:600; font-family:Times New Roman;">г. Донецк, пр-т Мира, 2</p> 
		<p align="left" style="font-size:20px; padding:5px 0 0 10px; font-weight:600; font-family:Times New Roman;">тел: 062 381-18-24; моб: 050 696-47-70</p>
		<p align="left" style="font-size:20px; padding:5px 0 0 10px;font-weight:600; font-family:Times New Roman;">МЦ «Блиц»: г. Донецк ул. Раздольная, 13</p>
		<p align="left" style="font-size:20px; padding:5px 0 0 10px; font-weight:600; font-family:Times New Roman;">тел: 062 389-33-04; моб: 050 057-43-78</p>      </td>
  </tr>
  <tr>
    <td height="50px">
    			<div id="menu_miradent">
                		<ul>
                        	<li id="mir_miradent"><a href="index.php?business_full=490&pm=2"><span style="text-align:center; font-size:18px; font-family:Times New Roman;">МИРАДЕНТ</span></a></li>
                            <li id="blic_miradent"><a href="index.php?business_full=490&pm=1"><span style="text-align:center; font-size:18px; font-family:Times New Roman;">Мед. центр</span> <span style="text-align:center; font-size:18px; font-family:Times New Roman;">БЛИЦ</span></a></li>
                            <li><a href="index.php?business_full=490&pm=3"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;">О нас</span></a></li>
                            <li><a href="index.php?business_full=490&pm=4"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;">Цены</span></a></li>
                            <li><a href="index.php?business_full=490&pm=5"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;">Вакансии</span></a></li>
                            <li id="link_r_miradent"><a href="index.php?business_full=490&pm=6"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;">Контакты</span></a></li>
                        </ul>
                </div>       
    </td>
  </tr>
</table>
<table id="tab_content_miradent" width="970px" align="center" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td id="left_content_miradent">
     <br />
      <a href="javascript:show_hide('est_rev_content_miradent')"><br /><br /><br /><span>Эстетическая</span><br /><span>Реставрация</span></a>
        	  	<br />
      <a href="javascript:show_hide('otbel_content_miradent')"><br /><br /><br /><span>Отбеливание</span><br /><span>системой</span><br /><span>"Beyond"</span></a> 
        	    <br />
   	  <a href="javascript:show_hide('ortoped_content_miradent')"><br /><br /><br /><span>Эндодонтическое</span><br /><span>лечение</span></a>
    </td>
    <td valign="top">
      <div id="text_content_miradent">
      <div id="est_rev_content_miradent">
      <h3>ЭСТЕТИЧЕСКАЯ РЕСТАВРАЦИЯ ЗУБОВ</h3>
    <p>Высокоразвитая цивилизация ставит перед стоматологом требования не только борьбы с болью и восстановления жевательной функции. Не менее важно в настоящее время сохранение и воссоздание неповторимой красоты здоровых зубов.</p>
   <p>Эту роль выполняет эстетическая реставрация – восстановление изначального цвета, формы и размера зуба.</p> 
   <p>Материалы для реставрации по твердости и прочности аналогичны твердым тканям зуба. Они разрабатываются в разных оттенках, что делает возможным воспроизвести в эстетической конструкции цветовые переливы природного живого зуба.</p>
   <p>Композиционные фотополимерные материалы послойно наносятся на подготовленный зуб в соответствии с цветом и структурой утраченных зубных тканей и отверждаются специальной лампой.</p>
   <p><span>Безболезненность, надежность, красота и естественность – вот цели профессионалов эстетической стоматологии!</span></p>

<h2>Эстетическая реставрация зубов : технологии.</h2>
<p>В  современном мире  космических технологий, высокой моды, открытых информационных границ безукоризненная улыбка открывает человеку безграничные возможности в личном общении и карьерном росте. 
Зубы человека отличаются сложностью и разнообразием формы, неповторимой структурой, богатством передачи цвета, блеском, прозрачностью. Все эти качества стоматолог стремится воссоздать в художественной реставрации, чтобы придать Вашей улыбке красоту и естественность.</p>
<p>Современные высокооснащенные лаборатории ведущих мировых фирм стоматологической продукции постоянно работают над созданием и усовершенствованием материалов для реставрации зубов. Многочисленный арсенал этих средств составляют фотополимерные материалы для восстановления жевательных групп зубов (в том числе, армированные - упроченные), жидкотекучие фотополимеры для плотной адаптации к поверхности, универсальные – для пломбирования любых зубных дефектов, материалы для художественной реставрации. Последние соответствуют тканям зуба по прочности и твердости, позволяют точно передать структурные цветовые переходы, опалесценцию и флюоресценцию зубной поверхности.</p>
<p>Обработка зуба под фотополимерные реставрации производится максимально щадяще. Сцепление материала с поверхностью осуществляется за счет микропроникновения связывающего агента (бонда) в межкристаллические пространства и обеспечивает так называемое интимное прикрепление.</p>
 <p>Если зуб значительно разрушен, его укрепляют по показаниям анкерным или световолоконным штифтом.
Фотоматериал послойно накладывается на зуб в соответствии со структурой утраченных зубных тканей, повторяя их цвет. Каждый слой отдельно отверждается  светом специальной лампы. Это делает конструкцию еще более прочной. Моделируя поверхность зуба, стоматолог повторяет бугорки, бороздки и другие элементы, характерные для строения здоровых зубов конкретного человека. Готовая реставрация корректируется по прикусу и полируется до блеска.</p> 
<p><strong>Художественная реставрация зубов</strong> подарит Вам здоровую улыбку и уверенность в собственной неповторимости.</p>
 <hr />
	</div>
    
  <div id="otbel_content_miradent">
	<h3>ОТБЕЛИВАНИЕ ЗУБОВ</h3>
    <p>Большинство людей в современном мире придает значение здоровью зубов и их внешнему виду! Сделайте свою улыбку неотразимой! Если Вы хотите иметь белые зубы и сногсшибательную улыбку, тогда система Бейонд – Ваш верный выбор. Ваша улыбка станет сияющей и белоснежной всего за 30 минут! Отбеливающая система обеспечивает максимально возможный эффект даже если ваши зубы потемнели от курения, употребления напитков, содержащих красители, утратили природную белизну вследствие применения лекарственных препаратов, таких как тетрациклин или покрылись пятнами из-за употребления антибиотиков, избытка фтора.</p>
<p>Система «Beyond Whitening Accelerator» - лучший выбор для достижения белоснежной и здоровой улыбки быстро и эффективно. Всего лишь за один курс отбеливания убираются пятна, которые образовывались годами, цвет зубов улучшается в среднем на 10-14 оттенков. Степень улучшения цвета зубов пациент выбирает по своему желанию и согласно рекомендациям стоматолога. Инновационная программа акселератора позволяет подобрать каждому пациенту индивидуальный режим интенсивности отбеливания.</p>
<p>Процедура отбеливания по системе Бейонд заключается в нанесении специального отбеливающего геля на поверхность зубов, а затем его активации с помощью холодного света лампы «Beyond Whitening Accelerator». Отбеливающий гель основан на 35% перекиси водорода и других компонентах, которые улучшают результат, предупреждают возникновение чувствительности и укрепляют зубную эмаль.</p> 
<p>Процесс отбеливания зубов возможен благодаря способности пероксида водорода свободно проникать сквозь эмаль и распространяться по всем частям зуба. Пероксиды под воздействием активатора (акселератора) распадаются на кислородные радикалы, которые затем мигрируют между эмалевыми  призмами, разлагая любые окрашенные молекулы, структура зуба при этом не затрагивается. Эмаль, дентин, связующие материалы и пломбы не повреждаются отбеливающими веществами.</p>
<p>Преимущества отбеливающей системы Бейонд над всеми существующих на мировом рынке системами отбеливания:</p>
		<ul>
        	<li>Комфортность и удобство: не требует никаких предварительных процедур, за исключением профессиональной гигиенической чистки; одномоментное отбеливание 16-20 зубов в течение 30 минут. Кратковременность процедуры исключает возникновение раздражения десен и околозубных тканей. Акселератор отбеливания работает в режиме низкой температуры, что снижает риск возникновения чувствительности зубов. </li>
            <li>Безопасность: акселератор отбеливания – мощная галогеновая лампа, излучающая холодный голубой свет, который фильтруется 12 000 световодами и системой оптических линз. Вредное ультрафиолетовое и инфракрасное излучение отсеивается, не достигая поверхности зубов. Излучение холодного света снижает уровень вредных бактерий в полости рта эффективнее дезинфицирующего ополаскивателя.</li>
        </ul>    
<p>При соблюдении всех рекомендаций по уходу за отбеленными зубами и использовании средств для поддержания эффекта в домашних условиях ваши зубы будут выглядеть прекрасно как после самой процедуры, так и на протяжении нескольких лет!</p>
<p>
<span>Beyond Power Whitening System – самая мощная система косметического отбеливания зубов в настоящее время, это передовая технология, гарантирующая безопасность, комфорт и результативность. Подробнее о системе отбеливания на сайте </span><a href="http://beyonddent.com.ua">www.beyonddent.com.ua.</a></p>
<h2>ЗУБНЫЕ УКРАШЕНИЯ.</h2>
<p>В настоящее время широкой популярностью у людей самых разных возрастов пользуются зубные украшения – скайсы. Это могут быть простые стразы, кристаллы Сваровски или алмазы в золотой оправе. Разнообразие их формы и цвета дает возможность подобрать  для Вас нечто особенное.</p> 
<p>Украшения крепятся  на зубы без препаровки, т.е не нарушая структуру эмали, при помощи специального стоматологического фиксирующего материала . Снять украшение можно в любой момент, после чего зубы имеют свой первоначальный вид.</p>
<p>Скайсы способны подчеркнуть Вашу индивидуальность, сделать улыбку блистательной и неотразимой!</p>
 <hr />
	</div>    


 <div id="ortoped_content_miradent">

<h3>ЭНДОДОНТИЧЕСКОЕ ЛЕЧЕНИЕ</h3>
<p>Если вовремя не вылечить кариес, болезнь может распространиться на пульпу зуба (внутризубной нерв) и далее – на связочный аппарат зуба и костную ткань челюсти. Как следствие – сильные боли, отек, воспаление и удаление зуба.</p>  
<p><strong>Эндодонтическое лечение</strong> – это комплекс мероприятий, направленных на борьбу с инфекцией внутри зуба и возвращение зубу возможности нормально функционировать. <strong>Эндодонтия</strong> – одна из важнейших областей терапевтической стоматологии.  Она требует от специалиста четкого знания сложной анатомии корневых каналов и строгого соблюдения последовательности определенных манипуляций в процессе лечения.</p>
<p>Врач-эндодонт выполняет ряд задач:</p>
	<ul>
    	<li>обеспечение доступа к корневым каналам,</li>
        <li>прохождение канала до верхушки корня,</li>
        <li>удаление из канала инфицированных и мертвых тканей,</li>
        <li>придание каналу формы, необходимой для правильного пломбирования,</li>
        <li>медикаментозная обработка канала с целью окончательного удаления болезнетворных бактерий,</li>
        <li>герметичное запечатывание (пломбирование) канала специальными наполнителями.</li>
	</ul>
	
    <p>В сложных и запущенных случаях не удается провести лечение корней в одно посещение: бывает необходимо оставление открытого зуба, наложение лекарственного средства под временную пломбу либо временное пломбирование канала лечебной пастой.</p>
<p>Каждый этап эндодонтического лечения выполняется с применением новейшего оборудования, инструментов, материалов.</p> 
<p>Современная стоматология мирового уровня МИРАДЕНТ располагает значительным арсеналом средств и методов качественного и надежного лечения корней. Правильность лечения контролируется и подтверждается с помощью специального прибора – апекслокатора и рентгеновских снимков, выполняемых на высокотехнологичной рентгенустановке.</p>
<p>Метод подготовки и заполнения корневых каналов выбирается в зависимости от их формы и строения, диагноза и течения заболевания, а также от способа последующего восстановления зуба в целом.</p>

<p><strong>Стоматология МИРАДЕНТ</strong> применяем самые прогрессивные технологии <strong>обработки и пломбирования каналов</strong>, гарантирующие продление жизни и здоровья зубов на долгий срок, а также возможность их использования в различных ортопедических конструкциях.</p>

<h2>Обработка корневых каналов : технологии.</h2>
<p>Кариес зубов, распространяясь, вызывает воспаление пульпы зуба и околокорневой костной ткани. Современная стоматология позволяет спасти большинство таких зубов, не допустить их удаления.</p>
<p>Лечение в таких случаях заключается в специальной обработке и герметичном <strong>пломбировании каналов корня зуба</strong>. Обработка каналов направлена на удаление из канала инфицированных тканей и придание каналу формы, необходимой для проникновения лекарства и правильного пломбирования.</p>
<p>Каналы имеют сложную форму, ответвления, часто встречаются тонкие, изогнутые, труднопроходимые каналы. Для их обработки используются специальные ручные и вращающиеся инструменты, позволяющие убрать из просвета воспаленные ткани, сделать стенки гладкими. В процессе обработки канал промывается специальными антисептическими растворами, нейтрализующими болезнетворные бактерии.</p>
<p>На протяжении всей работы стоматолог координирует свои действия по показаниям специального прибора – апекслокатора, при необходимости проводит дополнительный контроль с помощью рентгеновского снимка.</p>

<p>Правильная  предварительная обработка обеспечивает последующее качественное пломбирование канала и сохранение  зуба на длительный срок.</p>

<h2>Повторное эндодонтическое лечение : технологии.</h2>
<p>Нередко пациенты обращаются к стоматологу по поводу зубов, которые уже были ранее  пролечены эндодонтически в  другой клинике. Такие зубы нуждаются в повторном эндодонтическом лечении, и чаще всего их удается спасти.</p>
<p>Перед тем как поступить к перелечиванию канала, специалист изучает рентгеновский снимок. <strong>Повторное эндодонтическое лечение</strong> заключается в удалении из канала старого пломбировочного материала, прохождение и формирование канала на всю длину, обработка лечебными дезинфицирующими растворами и плотное пломбирование канала до верхушки по одной из современных методик. </p>
<p>Способ повторного лечения зависит от того, какой пломбировочный материал находится в канале, от формы и проходимости канала.  Для удаления из канала старой пломбировочной массы используются специально разработанные вращающиеся никель-титановые инструменты. В сложных случаях, когда каналы были прежде заполнены цементом, применяется ультразвуковой аппарат с соответствующими насадками. Ультразвук дробит застывший цемент и способствует его выведению. Кроме того, он во много раз усиливает бактерицидное  действие дезинфицирующий средств, увеличивает шансы на успех в лечении. </p>
<p>Герметичное  заполнение подготовленного корневого канала с последующим восстановлением зуба фотополимерным материалом позволяет остановить воспалительные явления в костной ткани челюсти, предотвратить обострение процесса и удаление зуба.</p>

<h2>Пломбирование корневого канала : технологии.</h2>
<p><strong>Пломбирование каналов</strong> является логическим итогом <strong>эндодонтического лечения</strong>. Наиболее верный шанс клинического успеха достигается тогда, когда система корневых каналов полностью, со всей своей сложностью, будет запломбирована на своем полном апикальном и латеральном протяжении.</p>
<p>Большинство современных методик пломбирования заключаются в плотном закрытии канала гуттаперчей с использованием силера – наполнителя – лечебной пасты, застывающей в канале после пломбирования.  Речь идет о методах латеральной конденсации гуттаперчи, конусного штифта, центрированной и вертикальной конденсации горячей гуттаперчи. Эти методики отличаются по степени уплотнения и распространения, способу введения, сложности, необходимости специального оборудования и стоимости. </p>
<p>При латеральной конденсации в канал, заполненный силером, вводится основной гуттаперчевый штифт, плотно закрывающий верхушечное отверстие. Далее, он уплотняется специальным инструментом и вводится следующий один штифт. Процедура повторяется до тех пор, пока просвет канала, имеющий конусную форму, не будет заполнен на всем протяжении. </p>
<p>Если канал предварительно обработан и сформирован с помощью специальной системы вращающихся инструментов, имеется возможность заполнить его с помощью одного конусного гуттаперчевого штифта, точно соответствующего форме подготовленного канала. Штифт идеально запечатывает верхушечное отверстие и весь просвет канала, делает ненужным введение  и уплотнение множества дополнительных штифтов. Это значительно сокращает процедуру, не отражаясь на ее качестве.</p> 
<p>В настоящее время мало кто из стоматологов отрицает наличие микроканальцев и множественных ответвлений корневого канала, которые также нуждаются в пломбировании.  Именно поэтому разработаны методики  <strong>3-D (трехмерной)</strong> <strong>обтурации</strong>.</p>
<p>Техника обтурации центрированной конденсацией (термафил) действенно и эффективно продвигает пломбирующие материалы через систему корневого канала движением конденсирующего устройства (предварительно нагретого носителя) в центре термопластического материала, такого как гуттаперча. Пломбирующий материал, смазанный силером, смещается в сторону коронки, так как конденсирующее устройство движется к верхушке, создавая эффект тока материала на стенки основного канала. Это пломбирует боковые канальцы, дополнительные канальцы, бороздки, петли, ответвления и перешейкипо ходу инструмента. Для работы в этой технике дополнительно требуются гуттаперчевые обтураторы на носителе и специальное устройство для их разогрева.</p>
<p>Для техники постоянной волны (Є&Q+ Plus) выбирается электрически нагреваемый уплотнитель - плаггер (Sybron Endo), соответствующей  конусности. Стенки канала смазываются силером, подготовленный гуттаперчевый штифт вводится до верхушки. Излишки гуттаперчи специальным образом убираются , а плаггер уплотняет гуттаперчу до уровня 4мм от верхушечного отвертстия, обеспечивая максимальное проникновение материала во все ответвления и канальцы, герметизируя все возможные пути распространения бактерий. <strong>Пломбирование верхних 2\3 канала</strong> выполняется при помощи пистолета или новым, встроенным, машинным пресс-шприцем.</p>
<p>Раньше было сложно запломбировать систему корневого канала в трехмерном измерении. Сейчас  этот надежный метод, предполагающий наличие дополнительной дорогостоящей аппаратуры и грамотного специалиста, полностью оправдывает возложенные на него ожидания. Кроме гуттаперчи, <strong>для пломбирования каналов</strong> применяются недавно разработанные материалы (эпифания, резилон, ПроРут МТА), которые используются по показаниям в соответствующих техниках пломбирования и значительно расширяют возможности сохранения зубов, рекомендованных к удалению. </p>
<h2> Аппаратные методы диагностики</h2>
    <p>Для постановки точного диагноза и подтверждения качества лечения в стоматологической клинике МИРАДЕНТ проводятся рентгенологические исследования на современном оборудовании.</p>
<p>Стоматологические установки оснащены интраоральными камерами Vista Cam ведущего немецкого производителя – фирмы Durr Dental. 
Камера многократно увеличивает изображение и переводит его на плоский экран. Это позволяет стоматологу рассмотреть мельчайшие детали на рабочем поле, а также продемонстрировать пациенту элементы зубных отложений, скрытые кариозные полости, исходное состояние больного зуба, этапы и результат проведения реставрации.</p>
<p>С помощью интраоральной камеры можно получить фотоснимки зубов до и после стоматологических процедур.  
Использование интраоральной камеры повышает информированность пациента  о ходе проводимых лечебных действий,  позволяет пациенту чувствовать себя спокойнее и увереннее на приеме у стоматолога.</p>  
 <hr />      
</div>

     <h3>СТОМАТОЛОГИЯ МИРАДЕНТ (Украина, Донецк) : КОНТАКТЫ</h3>
<p>Донецк, пр-т Мира 2, Стоматология Мирадент, т. 062-381-18-24, м. 050-696-47-70.</p>
<p>График работы:  пн-пт 8-00 до 18-00;  сб- 8-00 до  16-00; вых-воскресенье.</p>
<p>Донецк, ул.Раздольная 13, МЦ «Блиц», т.062- 389-33-04, м. 050-057-43-78.</p>
<p>График работы:  пн-пт с 9-00 до 20--00; сб- 9-00 до  18-00; вых-воскресенье.</p><br />
	
    <div id="div_st4">

					<script src="http://api-maps.yandex.ru/1.1/index.xml?key=AAmDzUsBAAAARkVWCAIAXzMCgKN58_MQUqB134Sdp-unCH0AAAAAAAAAAACbJlz2mcKc4anRgbxx6LBZ5BHPyg==" type="text/javascript"></script>

						<script type="text/javascript">

						window.onload = function () {

							var map = new YMaps.Map(document.getElementById("YMapsID"));

							map.setCenter(new YMaps.GeoPoint(37.796288,48.017299), 16);



							var content = document.createElement('span');

							content.innerHTML = "Стоматология МИРАДЕНТ";

							map.openBalloon(new YMaps.GeoPoint(37.796288,48.017299), content);



							map.addControl(new YMaps.ToolBar());

							map.addControl(new YMaps.Zoom());

							map.addControl(new YMaps.MiniMap());

							map.addControl(new YMaps.ScaleLine());

						}

    </script>





	 <div id="YMapsID" style="width:60%; height:300px; position:relative; float:centr; top:20px; left: 140px; z-index:20; margin-bottom:40px;"></div>

   </div>
</div>
    </td>
  </tr>
</table>

















</div>


</div> <!-- cat_ite_cont_m -->

<?php

   } 

?>







<div id="catalogue_item_menu">

<div class="catalogue_item_cont">



<a href="index.php?section_id=2&amp;business=1">бизнес</a>



 / 



<a href="index.php?section_id=32&amp;business=1">предприятия</a>



 / 



<a href="index.php?section_id=387&amp;business=2">Медицина</a>



 / 



<a href="index.php?section_id=511&business=2">Стоматология</a>



</div>





<div id="catalogue_item_menu">

<div class="catalogue_item_mp_a">

<a href="">Фотогалерея:</a></div>

</div>

<div class="catalogue_item_cont">

</div>

<div id="catalogue_item_menu">

<div class="catalogue_item_mp_a">

<a href="">Контактная информация:</div>

</div>

 <div class="catalogue_item_cont">

 		 <table width="100%">

			<tbody>

 			<tr>

			<!--	<td><img class="main_sec_image" src="" width="60" height="60" border="0" alt="" /></td>-->

				<td>Адрес:</td>

				<td>Телефон:</td>

				<td>Факс:</td>

				<td>E-mail:</td>

				<td>Веб-сайт:</td>

			</tr>

			<tr>

				<td>пр. Гурова 20<br /></td>

				<td>тел. (062) 335-16-39</td>

				<td></td>

				<td></td>

				<td></td>



			</tr>

			</tbody> 

		 </table> 		

  </div>

</div>  





