<div class="catalogue_item_c">
<style>

<!--
.folding{cursor:hand;font-weight:bold}
-->

img {
border:none;	
}

b {
	
}

.acc {
}
#acc {
	list-style: none outside none;
    margin: 0 auto 40px;
    width: 480px;
}

.acc-section {
background: white;
margin: 0px;
overflow: hidden;
}

#acc .acc-content {
    border-style: none solid solid;
}

element.style {
height: 0px;
}

div {
	display:block;
}

p {
	font-family:Arial, Helvetica, sans-serif;
	font:Arial, Helvetica, sans-serif;
}

h3 {
display:block;
}

a {
	text-decoration:none;
	border:none;
}

.sequ_conteiner{
	width:100%;
}

.sequ_up { 
height:105 px;
width:100%;
position:relative;
float:left;
margin:0;
background:#264c7b;
}

.sequ_p_up_2 {
	color:#FFF;
	font-size:20 px;
	text-align:justify;
	line-height: 1 px;
	letter-spacing: 2 px;
}

.sequ_p_up_3 {
	color:#FFF;
	font-size:16 px;
	text-align:justify;
	line-height: 1 px;
	letter-spacing: 5 px;
}

.sequ_stroke {
width: 100%;
background-color:#edecea;
height:33px;
text-align:right;
padding:0;
position:relative;
float:left;
margin: -10 0 0 0;
}

.sequ_main_menu {
	position:relative;
	float:left;
	min-height:458;
	max-height:458;
	height:100%;
	background-color:#264c7b;
	padding:5px;
}
/*onas*/
.sequ_a_1 {
	width:135px;
	position:relative;
	float:right;
	margin-right:6px;
}
/*uslu*/
.sequ_a_2 {
	width:135px;
	position:relative;
	float:right;
	margin-right:6px;
	
}
/*kont*/
.sequ_a_3 {
	width:135px;
	position:relative;
	float:right;
	
}

.sequ_podmain{
width:955px;
height:20px;
position:relative;
float:left;
left:20px;
padding:5px;
background-color:#264c7b;
color:#FFF;
font-family:Arial, Helvetica, sans-serif;
font-size:13px;
text-align:center;
}

.sequ_text {
	width:100%;
	position:relative;
	float:left;
	text-indent: 20px;
}

.sequ_footer {
	width:990px;
	height:35;
	position:relative;
	float:left;
	background-color:#264c7b;
	color:#000;
	font-family:Tahoma, Geneva, sans-serif;
	font-size:14px;
	text-align:right;
	padding:5px;
}
</style>
<?php
if ($_GET['pm'] == 1) 
{
?>
<div class="catalogue_item_cont_m"> 
<div class="sequ_conteiner">
    <div class="sequ_up">
		<div style="position:relative; float:left; padding:10px; top:10px; left:50px;"><img src="../root/msite/kardio/ser.png"/></div>
		<div style="position:relative; float:left; left:80px; top:48px; color:#FFF;	font-size:24px; text-align:justify; line-height:1px; letter-spacing:14px;">Частный приём</div>
		<div style="position:relative; float:left; left:240px; top:50px; color:#FFF;	font-size:12px;  line-height:1.2; text-align:right;"><span>тел. (066) 907-94-66</span><br />
<div style="color:#95b7e2;">Г. Донецк, Калининский район, Пр. Ильича, 14-Е <br />
<div style="letter-spacing:2px;">(ДОКТМО, больница им. Калинина),</div>
Медицинский центр «ГЕРЦ», 7 этаж, кабинет 715.</div></div>
		<div style="position:relative; float:left; clear:left; left:190px; top:-32px; color:#FFF;	font-size:24px; text-align:justify; line-height:1px; letter-spacing:1px; text-transform:uppercase;"><b>Кардиолога-терапевта</b></div>
		<div style="position:relative; float:left; clear:left; left:190px; top:-17px; color:#FFF; margin-bottom:10px;	font-size:16px; text-align:justify; line-height:1px; letter-spacing:6px;">Медицинский центр "Герц"</div>
    	<!--
		<div style="position:relative; float:left; clear:left; margin-bottom:10; padding:0; left:20; width:100%;"><img src="../root/msite/kardio/up.png" align="left" width="100%" height="105" /></div>
		-->
    </div>
    <div class="sequ_stroke"> 
        <div style="padding:6px; bottom: -10px; color:#264c7b; font-family:'Times New Roman', Times, serif; font-size:20px;">
        Сердце - это ключевой орган в организме человека</div>
        </div>
    <div class="sequ_main_menu">
    	<div style="background: url(../root/msite/kardio/neb.jpg); width:100%; height:452px; position:relative; float:left;">
        	<div style="position:relative; float:left; left:25; width:370;"><img src="../root/msite/kardio/dev.png" align="left" width="367" height="450" /></div>
			<div style="position:relative; float:right; padding:0px;">
				<div class="sequ_a_3"><a href="http://eurodonetsk.com/index.php?business_full=404&pm=3"><img src="../root/msite/kardio/ko.jpg" width="135" height="36" /></a></div>
				<div class="sequ_a_2"><a href="http://eurodonetsk.com/index.php?business_full=404&pm=2"><img src="../root/msite/kardio/se.jpg" width="135" height="36" /></a></div>
				<div class="sequ_a_1"><a href="http://eurodonetsk.com/index.php?business_full=404&pm=1"><img src="../root/msite/kardio/us_on.jpg" width="135" height="36" /></a></div>
			</div>
            
            <div style="padding-top: 100; text-align:left; font-style:italic; color:#264c7b; font:Tahoma, Geneva, sans-serif; font-family:Tahoma, Geneva, sans-serif; font-size:22px; line-height:1.4; padding-left:390; margin-top:100;"><br /><br />Наша жизнь и наше здоровье напрямую зависят от его состояния. Именно поэтому опасение приобрести заболевание сердца является одним из самых распространенных и самых сильных страхов человека. С любыми жалобами на боли в области сердца следует обращаться к кардиологу для выяснения причины ваших жалоб и прояснения серьезности ситуации!</div>       
        </div>
    </div>
    <div class="sequ_podmain">
    <b>В нашем центре Вы можете пройти полное диагностическое обследование сердечно-сосудистой системы.</b>
    </div>
	
	<!-- Основной текст -->
	
    <div class="sequ_text">
    	<div style="position:relative; float:left; width:100%;">
			<div id="left_block_sequ_text" style="position:relative; float:left; width:48%; padding:6px;">
				<div style="position:relative; float:left; width:100%; text-align:left; font-family:'Trebuchet MS', Arial, Helvetica, sans-serif; line-height:1; font-style:italic; font-size:18px; margin-bottom:15px; margin-top:20px;"><b>В нашем центре используется самое современное медицинское оборудование, позволяющее наиболее точно выявить ту или иную патологию, поставить точный диагноз и назначить необходимое лечение.<br /><br /><br /><br /></b>
				</div>
                <div style="position:relative; float:left; width:100%; text-align:left; text-indent: 20; font-family:'Trebuchet MS', Arial, Helvetica, sans-serif; line-height:1; font-style:italic; font-size:18px; color:#900; margin-bottom:15px;"><b>Наши специалисты работают по современным отечественным и международным стандартам и протоколам диагностики, лечения и профилактики заболеваний сердечно-сосудистых заболеваний, основанных на принципах доказательной медицины.<br /><br /><br /><br /></b>
           		</div>
                <div style="position:relative; float:left;  width:100%; text-align:left; font-family:'Trebuchet MS', Arial, Helvetica, sans-serif; line-height:1; font-style:italic; font-size:18px; color:#900;">
                <b>	<div style=" font-size:16px; color:#264c7b;">Пенсионерам - скидка 20%</div> 
                    <div style="text-indent:150px; font-size:14px; color:black;"> (консультация кардиолога, ЭКГ)</div>
                    <div style=" font-size:16px; color:#264c7b;">Участникам войны и детям войны - скидка 35%</div>
                    <div style="text-indent:150px; font-size:14px; color:black;">(консультация кардиолога, ЭКГ)</div>
                    <div style="margin-top:10px; font-size:16px; color:#264c7b; text-transform:uppercase;">Подробнее на вкладке услуги
                    </div>
                </b>
                </div>
			</div>
            <div id="right_block_sequ_text" style="position:relative; float:right; width:48%; padding:6px;">
				<div style="position:relative; float:left; margin-top:-512; color:#900; font-size:24px; text-align=:left;">10 причин записаться на прием к кардиологу:</div>
					<b><div style="position:relative; float:left; font-size:24px; text-align=:left; font-size:11px; text-align:left;">
						
					1. Вас беспокоят боли в области сердца при физической нагрузке или без таковой. <br />
					 <img src="../root/msite/kardio/uhi.jpg" width="150" height="113"; align="right" />
					2. Вас беспокоит одышка при физической нагрузке, отеки голеней и стоп. <br />
					 
					3. Вы ощущаете усиленное сердцебиение или перебои в работе сердца. <br />
					 
					4. У вас частый (более 90 ударов в минуту) либо редкий (менее 55 ударов в минуту) пульс. <br />
					 
					5. У вас периодически или постоянно повышается артериальное давление свыше 140/90 мм. рт. ст.<br />
					
					6. Вам более 40 лет и Вы ни разу не обращались к кардиологу. <br />
					 
					7. Вы страдаете сахарным диабетом либо заболеванием щитовидной железы. <br />
					 
					8. Вы перенесли инсульт. <br />
					 
					9. Вы курите. <br />
					 
					10. У Вас избыточная масса тела.<br /><br />
					</div>
					
            
            
			<div style="position:relative; float:left; clear:left; margin-top:-512; padding-right:30; padding-top: 5; font-size:24px; text-align=:left; font-size:11px; text-align:left;">
                Консультация кардиолога необходима для выявления патологии сердечно-сосудистой системы, определения активности и клинической стадии заболевания, своевременного назначения лечения и мероприятий по профилактике прогрессирования заболевания и его осложнений. <br /><br />

Первичный осмотр кардиолога включает в себя сбор и конкретизацию жалоб, осмотр (перкуссия, аускультация, определение пульса, артериального давления ), сбор анамнеза, оценку проведенных ранее исследований (ЭКГ,УЗИ сердца, анализов крови и др.), назначение дополнительных обследований при необходимости, постановку основного диагноза, определение сопутствующей патологии, назначение соответствующей терапии, диетических рекомендаций и рекомендаций по изменению образа жизни.<br /><br />

Повторный осмотр кардиолога включает в себя постановку окончательного диагноза на основании объективного осмотра и данных дополнительных исследований, контроль эффективности лечения и корректировку терапии, если это необходимо.<br /><br />

Контрольная бесплатная консультация включает в себя то же, что и повторный осмотр. Главная задача контрольных посещений врача – это контроль за выполнением рекомендаций, контроль эффективности лечения и его коррекция.

                </div></b>
                
        </div>
     </div>
       
    </div>
</div>

</div>
<?php
}
else
   if ($_GET['pm'] == 2)
   {
?>
<div class="catalogue_item_cont_m"> 
<div class="sequ_conteiner">
    <div class="sequ_up">
		<div style="position:relative; float:left; padding:10px; top:10px; left:50px;"><img src="../root/msite/kardio/ser.png"/></div>
		<div style="position:relative; float:left; left:80px; top:48px; color:#FFF;	font-size:24px; text-align:justify; line-height:1px; letter-spacing:14px;">Частный приём</div>
		<div style="position:relative; float:left; left:240px; top:50px; color:#FFF;	font-size:12px;  line-height:1.2; text-align:right;"><span>тел. (066) 907-94-66</span><br />
<div style="color:#95b7e2;">Г. Донецк, Калининский район, Пр. Ильича, 14-Е <br />
<div style="letter-spacing:2px;">(ДОКТМО, больница им. Калинина),</div>
Медицинский центр «ГЕРЦ», 7 этаж, кабинет 715.</div></div>
		<div style="position:relative; float:left; clear:left; left:190px; top:-32px; color:#FFF;	font-size:24px; text-align:justify; line-height:1px; letter-spacing:1px; text-transform:uppercase;"><b>Кардиолога-терапевта</b></div>
		<div style="position:relative; float:left; clear:left; left:190px; top:-17px; color:#FFF; margin-bottom:10px;	font-size:16px; text-align:justify; line-height:1px; letter-spacing:6px;">Медицинский центр "Герц"</div>
    	<!--
		<div style="position:relative; float:left; clear:left; margin-bottom:10; padding:0; left:20; width:100%;"><img src="../root/msite/kardio/up.png" align="left" width="100%" height="105" /></div>
		-->
    </div>
    <div class="sequ_stroke"> 
        <div style="padding:6px; bottom: -10px; color:#264c7b; font-family:'Times New Roman', Times, serif; font-size:20px;">
        Сердце - это ключевой орган в организме человека</div>
        </div>
    <div class="sequ_main_menu">
    	<div style="background: url(../root/msite/kardio/neb.jpg); width:100%; height:452px; position:relative; float:left;">
        	<div style="position:relative; float:left; left:25; width:370;"><img src="../root/msite/kardio/dev.png" align="left" width="367" height="450" /></div>
			<div style="position:relative; float:right; padding:0px;">
				<div class="sequ_a_3"><a href="http://eurodonetsk.com/index.php?business_full=404&pm=3"><img src="../root/msite/kardio/ko.jpg" width="135" height="36" /></a></div>
				<div class="sequ_a_2"><a href="http://eurodonetsk.com/index.php?business_full=404&pm=2"><img src="../root/msite/kardio/se_on.jpg" width="135" height="36" /></a></div>
				<div class="sequ_a_1"><a href="http://eurodonetsk.com/index.php?business_full=404&pm=1"><img src="../root/msite/kardio/us.jpg" width="135" height="36" /></a></div>
			</div>
            
            <div style="padding-top: 100; text-align:left; font-style:italic; color:#264c7b; font:Tahoma, Geneva, sans-serif; font-family:Tahoma, Geneva, sans-serif; font-size:22px; line-height:1.4; padding-left:390; margin-top:100;"><br /><br />Наша жизнь и наше здоровье напрямую зависят от его состояния. Именно поэтому опасение приобрести заболевание сердца является одним из самых распространенных и самых сильных страхов человека. С любыми жалобами на боли в области сердца следует обращаться к кардиологу для выяснения причины ваших жалоб и прояснения серьезности ситуации!</div>       
        </div>
    </div>
    <div class="sequ_podmain">
    <b>В нашем центре Вы можете пройти полное диагностическое обследование сердечно-сосудистой системы.</b>
    </div>
	
	<!-- Основной текст -->
	
    <div class="sequ_text">
    	<div style="position:relative; float:left; width:100%;">
			<div id="cenyt_block1_sequ_text" style="position:relative; float:left; width:95%; padding:6px; left:25px;">
				<div style="position:relative; float:left; width:100%; text-align:left; font-family:'Trebuchet MS', Arial, Helvetica, sans-serif; line-height:1; font-style:italic; font-size:15px; padding-bottom:15px;"><b>Наши специалисты помогут вам оценить состояние сердечно-сосудистой системы, устранить факторы риска сердечно-сосудистых заболеваний, провести профилактику и лечение выявленных заболеваний и их возможных осложнений.</b>
				</div>
                <div style="position:relative; float:left; width:100%; text-align:left; text-indent: 20; font-family:'Trebuchet MS', Arial, Helvetica, sans-serif; line-height:1; font-style:italic; font-size:15px; color:#264c7b;"><b>На базе центра возможно проведение полного диагностического обследования все органов и систем с использованием современного профессионального медицинского оборудования квалифицированными специалистами.</b>
           		</div>
			</div>
			<div id="left_block_sequ_text" style="position:relative; float:left; text-align:left; text-indent: 20px; font-family:'Trebuchet MS', Arial, Helvetica, sans-serif; line-height:1; font-style:italic; font-size:20px; color:#264c7b; width:30%; left:30px;">
			У нас Вы можете пройти полное диагностическое обследование сердечно-сосудистой системы: 
				<div style="color:black; font-size:15px; padding:15px; line-height:1.8;">
				<ul type="disc">
					<li>- элекетрокардиографию (ЭКГ);</li>
					<li>- суточное (холтеровское) мониторирование ЭКГ;</li>
					<li>- УЗИ сердца; </li>
					<li>- нагрузочные пробы; </li>
					<li>- лабораторное обследование. </li>
				</ul>
				</div>
				<div style="position:relative; float:left;  width:100%; text-align:left; font-family:'Trebuchet MS', Arial, Helvetica, sans-serif; line-height:1; font-style:italic; font-size:18px; color:#900;">
                <b>	
					<div style="padding-top:10px; padding-bottom:7px; font-size:16px; color:#264c7b;">Пенсионерам - скидка 20%</div> 
                    <div style="text-indent:70px; font-size:14px; color:black;"> (консультация кардиолога, ЭКГ)</div>
                    <div style="padding-top:16px; padding-bottom:7px; font-size:16px; color:#264c7b;">Участникам войны и детям войны - скидка 35%</div>
                    <div style="text-indent:70px; font-size:14px; color:black;">(консультация кардиолога, ЭКГ)</div>
                    <div style="margin-top:10px; font-size:16px; color:#264c7b; text-transform:uppercase;">Подробнее на вкладке услуги
                    </div>
                </b>
                </div>
			</div>
			<div id="centr_block_sequ_text" style="position:relative; float:left; text-align:left; text-indent:20px; font-family:'Trebuchet MS', Arial, Helvetica, sans-serif; line-height:1; font-style:italic; font-size:14px; color:#264c7b; width:50%; left:30px;">
			<table width="100%" cellpadding="50" cellspacing="0" border="2">
			<tbody>
				<tr style=" text-align:center;">
					<td width="70%">
						Наименование услуги
					</td>
					<td width="30%" style="text-align:center;">
						Стоимость, грн
					</td>
				</tr>
				<tr>
					<td>
						Вызов врача на дом (консультация + ЭКГ)
					</td>
					<td style="text-align:center;">
						350
					</td>
				</tr>	
				<tr>
					<td>
						Первичный прием кардиолога-семейного врача 
					</td>
					<td style="text-align:center;">
						150
					</td>
				</tr>   
				<tr>
					<td>
						Повторный прием кардиолога-семейного врача
					</td>
					<td style="text-align:center;">
						100
					</td>
				</tr>
				<tr>
					<td>
						Контрольные консультации по результатам лечения 	 
					</td>
					<td style="text-align:center;">
						Бесплатно
					</td>
				</tr>   
				<tr>
					<td>
						Первичный прием терапевта-кардиолога, к. мед. н., доцента 	         	 
					</td>
					<td style="text-align:center;">
						250
					</td>
				</tr>    
				<tr>
					<td>
						Повторный прием терапевта-кардиолога, к. мед. н., доцента  	         	 
					</td>
					<td style="text-align:center;">
						175
					</td>
				</tr>
				<tr>
					<td>
						Электрокардиограмма (ЭКГ) с расшифровкой         	 
					</td>
					<td style="text-align:center;">
						50
					</td>
				</tr> 
				<tr>
					<td>
						Холтеровское мониторирование ЭКГ 	        	 
					</td>
					<td style="text-align:center;">
						250
					</td>
				</tr>           
			</tbody>
			</table>
					<div style="color:black; font-size:14px; padding:5px;">
					<ul id="acc" class="acc">         
                        <li>              
                            <h3 style="text-align:left;">
                            <b style="color:#900; font-size:20px;"><img src="../root/msite/kardio/heart.png" width="20px" height="20px" />
                            Вызов врача на дом
                            </b>
                            </h3>              
                             <div class="acc-section" style="height: auto; ">               
                              <div class="acc-content">                
                               <ul class="acc"> 
							   <b>
                                <p>           
	     Платный вызов врача – прекрасная альтернатива государственного медицинского обслуживания, когда Вам нужен медицинский специалист с выездом на дом. Воспользуйтесь нашей услугой и наш специалист (терапевт или кардиолог) приедет к Вам в условленное время.<br />
&nbsp;&nbsp;&nbsp;Мы предоставляем следующие медицинские услуги: <br />
• медицинская консультация (терапевт, кардиолог);<br />
• осмотр пациента;<br />
• проведение электрокардиографии (ЭКГ)<br />
• холтеровское мониторирование ЭКГ<br />
• постановка диагноза<br />
• назначение лечения			
								</p>
								</b>
                       		  </ul>  
                      		 </div> 			 
                     		</div> 		 
                      </li> 		
		 			  <li>              
						<h3 style="text-align:left;">
                        <b style="color:#900; font-size:20px;">
                        <img src="../root/msite/kardio/heart.png" width="20px" height="20px" /> Электрокардиография (ЭКГ)
                        </b>
                        </h3>              
                             <div class="acc-section" style="height:0px;">               
                              <div class="acc-content">                
                               <ul class="acc"> 	
							   <b>	
                                <p>
	     Электрокардиография (ЭКГ) – графическое изображение электрических процессов, происходящих в сердце – основной метод диагностики заболеваний сердечно-сосудистой системы. Несомненными плюсами ЭКГ являются: высокая информативность, неинвазивность, простота выполнения, общедоступность и безопасность. 
         						</p>
                                <p>
 Электрокардиография относится к обязательным общеклиническим методам диагностики, которые проводятся пациенту вне зависимости от предварительного диагноза. 
 								</p>
                                <p>
 ЭКГ – незаменимый метод диагностики ишемической болезни сердца (ИБС) и ее типичных проявлений: стенокардии и инфаркта миокарда. Также эта методика является хорошим подспорьем в диагностике электролитных нарушений (нарушений обмена кальция, калия и др.) и внесердечной патологии, например, заболеваний легких. Несмотря на свою высокую диагностическую ценность, электрокардиограмма не может нам дать полную картину физиологических и патологических процессов, происходящих в сердце. Связано это, главным образом, с кратковременностью записи ЭКГ и регистрацией ее в покое. Поэтому для повышения эффективности данного метода при диагностике стенокардии напряжения, безболевой ишемии, аритмий и др. применяются модифицированные методики: суточное мониторирование ЭКГ, велоэргометрия, тредмилл.
								</p>
							   </b>
                               </ul>	 		  
                             </div> 			 
                           </div> 		 
		 			   </li> 	
                       <li>              
					   <h3 style="text-align:left;">
                       <b style="color:#900; font-size:20px;">
                       <img src="../root/msite/kardio/heart.png" width="20px" height="20px" />					                       Холтеровское мониторирование (ЭКГ) 
                       </b>
                       </h3>              
                         <div class="acc-section" style="height:0px;">               
                          <div class="acc-content">                
                           <ul class="acc"> 	
						   <b>
                            <p>
	     Холтеровское мониторирование - это метод функциональной диагностики, с помощью которого осуществляется запись ЭКГ (электрокардиограммы) непрерывно в течение суток. Для этого используется носимый портативный регистратор (холтер), который производит круглосуточную запись электрокардиограммы и передачу информации о работе сердца за сутки в компьютер. 
Специальная программа обеспечивает выявление и анализ всех видов нарушения сердечного ритма, болевых и без болевых приступов ишемии миокарда. Этот метод позволяет не только точно поставить диагноз, но и существенно повысить эффективность лечения сердечно-сосудистых заболеваний (гипертония, инфаркт, атеросклероз, миокардит, аритмии, вегето-сосудистая дистония). 
							</p>
                            <p>
Для чего проводится холтеровское мониторирование?
							</p>
                            <p>
Холтеровское мониторирование используется для оценки работы сердца, выявления изменений и нарушений в функционировании сердечно-сосудистой системы. Суточное холтеровское мониторирование выявляет практически все возможные нарушения в работе сердечно-сосудистой системы в течение суток, что невозможно при обследовании другими способами кардиологической диагностики.
							</p>
							</b>
						  </ul>
                        </div> 			 
                     </div> 		 
					</li> 		 
				</ul>
					<script type="text/javascript">
					 var parentAccordion=new TINY.accordion.slider("parentAccordion");
					 parentAccordion.init("acc","h3",false,0);
					 var nestedAccordion=new TINY.accordion.slider("nestedAccordion");
					 nestedAccordion.init("nested","h3",true,0,"acc-selected");
					</script> 	
				</div>
				
			</div>
			<div id="right_block_sequ_text" style="position:relative; float:left; text-align:left; text-indent: 0px; font-family:'Trebuchet MS', Arial, Helvetica, sans-serif; line-height:1.2; font-style:italic; font-size:13px; color:#900; width:15%; left:35px;">
			<div>Не относитесь легкомысленно к своему здоровью.
Прислушайтесь к своему сердцу и проконсультируйтесь у врача-кардиолога! </div>
				<div style="margin-top:15px; margin-bottom:15px; padding:5px;"><img align="right" src="../root/msite/kardio/usl_1.jpg" width="140px" height="90px" /></div>
				<div style="padding:5px;"><br /><br /><br /><br /><br /><img align="right" src="../root/msite/kardio/usl_2.jpg" width="140px" height="90px" /></div>
				<div style="padding:5px;"><br /><br /><br /><br /><br /><br /><img align="right" src="../root/msite/kardio/usl_3.jpg" width="140px" height="90px" />&nbsp;</div>
			</div>
			
        </div>
     </div>
       
    </div>
</div>
<?php
}
else
   if ($_GET['pm'] == 3)
   {
?>
<div class="catalogue_item_cont_m"> 
<div class="sequ_conteiner">
   <div class="sequ_up">
		<div style="position:relative; float:left; padding:10px; top:10px; left:50px;"><img src="../root/msite/kardio/ser.png"/></div>
		<div style="position:relative; float:left; left:80px; top:48px; color:#FFF;	font-size:24px; text-align:justify; line-height:1px; letter-spacing:14px;">Частный приём</div>
		<div style="position:relative; float:left; left:240px; top:50px; color:#FFF;	font-size:12px;  line-height:1.2; text-align:right;"><span>тел. (066) 907-94-66</span><br />
<div style="color:#95b7e2;">Г. Донецк, Калининский район, Пр. Ильича, 14-Е <br />
<div style="letter-spacing:2px;">(ДОКТМО, больница им. Калинина),</div>
Медицинский центр «ГЕРЦ», 7 этаж, кабинет 715.</div></div>
		<div style="position:relative; float:left; clear:left; left:190px; top:-32px; color:#FFF;	font-size:24px; text-align:justify; line-height:1px; letter-spacing:1px; text-transform:uppercase;"><b>Кардиолога-терапевта</b></div>
		<div style="position:relative; float:left; clear:left; left:190px; top:-17px; color:#FFF; margin-bottom:10px;	font-size:16px; text-align:justify; line-height:1px; letter-spacing:6px;">Медицинский центр "Герц"</div>
    	<!--
		<div style="position:relative; float:left; clear:left; margin-bottom:10; padding:0; left:20; width:100%;"><img src="../root/msite/kardio/up.png" align="left" width="100%" height="105" /></div>
		-->
    </div>
    <div class="sequ_stroke"> 
        <div style="padding:6px; bottom: -10px; color:#264c7b; font-family:'Times New Roman', Times, serif; font-size:20px;">
        Сердце - это ключевой орган в организме человека</div>
        </div>
    <div class="sequ_main_menu">
    	<div style="background: url(../root/msite/kardio/neb.jpg); width:100%; height:452px; position:relative; float:left;">
        	<div style="position:relative; float:left; left:25; width:370;"><img src="../root/msite/kardio/dev.png" align="left" width="367" height="450" /></div>
			<div style="position:relative; float:right; padding:0px;">
				<div class="sequ_a_3"><a href="http://eurodonetsk.com/index.php?business_full=404&pm=3"><img src="../root/msite/kardio/ko_on.jpg" width="135" height="36" /></a></div>
				<div class="sequ_a_2"><a href="http://eurodonetsk.com/index.php?business_full=404&pm=2"><img src="../root/msite/kardio/se.jpg" width="135" height="36" /></a></div>
				<div class="sequ_a_1"><a href="http://eurodonetsk.com/index.php?business_full=404&pm=1"><img src="../root/msite/kardio/us.jpg" width="135" height="36" /></a></div>
			</div>
            
            <div style="padding-top: 100; text-align:left; font-style:italic; color:#264c7b; font:Tahoma, Geneva, sans-serif; font-family:Tahoma, Geneva, sans-serif; font-size:22px; line-height:1.4; padding-left:390; margin-top:100;"><br /><br />Наша жизнь и наше здоровье напрямую зависят от его состояния. Именно поэтому опасение приобрести заболевание сердца является одним из самых распространенных и самых сильных страхов человека. С любыми жалобами на боли в области сердца следует обращаться к кардиологу для выяснения причины ваших жалоб и прояснения серьезности ситуации!</div>       
        </div>
    </div>
    <div class="sequ_podmain">
    <b>В нашем центре Вы можете пройти полное диагностическое обследование сердечно-сосудистой системы.</b>
    </div>
	
	<!-- Основной текст -->
	
    <div class="sequ_text">
    	<div style="position:relative; float:left; width:100%;">
			<div id="left_block_sequ_text" style="position:relative; float:left; width:50%; padding:16px; left:25px; text-align:left; font-style:italic; color:black; font:Tahoma, Geneva, sans-serif; font-family:Tahoma, Geneva, sans-serif; font-size:18px; text-indent:0px;">
			<b style="line-height:1.7;">
			Г. Донецк, Калининский район, Пр. Ильича, 14-Е <br />
			ДОКТМО, больница им. Калинина), <br />
			Медицинский центр «ГЕРЦ», 7 этаж, <br />
			 кабинет 715. <br />
			<b style="color:#900;">http://www.cardiology.at.ua</b> <br />
			Прием больных ведется ежедневно  <br />
			с понедельника по пятницу <br />
			с 8:00 по 16:00 <br />
			по предварительной записи <br />
			по телефону: 066-907-94-66. <br />
			</b>
							<div style="position:relative; float:left;  width:60%; text-align:left; font-family:'Trebuchet MS', Arial, Helvetica, sans-serif; line-height:1; font-style:italic; font-size:18px; color:#900;">
                <b>	
					<div style="padding-top:50px; padding-bottom:7px; font-size:16px; color:#264c7b;">Пенсионерам - скидка 20%</div> 
                    <div style="text-indent:30px; font-size:14px; color:black;"> (консультация кардиолога, ЭКГ)</div>
                    <div style="padding-top:16px; padding-bottom:7px; font-size:16px; color:#264c7b;">Участникам войны и детям войны - скидка 35%</div>
                    <div style="text-indent:30px; font-size:14px; color:black;">(консультация кардиолога, ЭКГ)</div>
                    <div style="margin-top:10px; font-size:16px; color:#264c7b; text-transform:uppercase;">Подробнее на вкладке услуги
                    </div>
               </b>
               				 </div>
			</div>
			
		<div id="photo_sequ_bottom" style="position:relative; float:left; margin-top:15px; left:50px;"><img src="../root/msite/kardio/photo.jpg" width="365px" height="484px" align="right" /></div>
		
			<div id="div_st">
        <script src="http://api-maps.yandex.ru/1.1/index.xml?key=AAmDzUsBAAAARkVWCAIAXzMCgKN58_MQUqB134Sdp-unCH0AAAAAAAAAAACbJlz2mcKc4anRgbxx6LBZ5BHPyg==" type="text/javascript"></script>
    <script type="text/javascript">
        window.onload = function () {
            var map = new YMaps.Map(document.getElementById("YMapsID"));
            map.setCenter(new YMaps.GeoPoint(37.824874,48.002321), 17);

            var content = document.createElement('span');
            content.innerHTML = "Медицинский центр «Герц»";
            map.openBalloon(new YMaps.GeoPoint(37.824174,48.002221), content);

            map.addControl(new YMaps.ToolBar());
            map.addControl(new YMaps.Zoom());
            map.addControl(new YMaps.MiniMap());
            map.addControl(new YMaps.ScaleLine());
        }
    </script>


	 <div id="YMapsID" style="width:90%; height:450px; position:relative; float:left; top:20px; left:40px; z-index:20; margin-bottom:40px;"></div>
   </div>


			
			
			
			
			
        </div>
    </div>
       
    </div>
</div>

<?php
   } 
?>



<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="index.php?section_id=32&amp;business=1">Категория:</a></div>
</div>
<div class="catalogue_item_cont">
<a href="index.php?section_id=2&amp;business=1">бизнес</a>
 / 
<a href="index.php?section_id=32&amp;business=1">предприятия</a>
 / 
<a href="index.php?section_id=387&amp;business=2">Медицина</a>
 / 
<a href="index.php?section_id=512&amp;business=2">Кардиология</a>
</div>


<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="">Фотогалегея:</a></div>
</div>
<div class="catalogue_item_cont">
</div>
<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="">Контактная информация:</div>
</div>
 <div class="catalogue_item_cont">
 		 <table width="100%">
			<tbody>
 			<tr>
			<!--	<td><img class="main_sec_image" src="" width="60" height="60" border="0" alt="" /></td>-->
				<td>Адрес:</td>
				<td>Телефон:</td>
				<td>Факс:</td>
				<td>E-mail:</td>
				<td>Веб-сайт:</td>
			</tr>
			<tr>
				<td>Г. Донецк, Калининский район,<br /> Пр. Ильича, 14-Е <br />
			ДОКТМО, больница им. Калинина), <br />
			Медицинский центр «ГЕРЦ», 7 этаж, <br />
			 кабинет 715.</td>
				<td>066-907-94-66.</td>
				<td></td>
				<td></td>
				<td></td>

			</tr>
			</tbody> 
		 </table> 		
	 </div>
</div>  


