<div class="catalogue_item_c">

<style>



<!--

.folding{cursor:hand;font-weight:bold}

-->



.catalogue_item_cont p {

color:#000000;

text-align:justify;

text-indent:0px;

line-height:20px;

margin:0px;

}



.catalogue_item_cont_m {

background-color:#FFFFFF;

border:1px solid lightgray;

color:#000000;

margin:0;

margin:15px 10px 10px;

width:980px;

}



.catalogue_item_cont {

background-color:#ffffff;

border-top:1px solid lightgray;

margin:0 0 7px 10px;

width:980px;

color:#000000;

}

.catalogue_item_c {

background-color:#F3F3F3;

}



.catalogue_item_cont a {

color:#000000;

}



.catalogue_item_cont a:hover {

color:#000000;

text-decoration:underline;

}



.catalogue_item_mp_a {

left:3px;

position:relative;

}



#mm_menu {position:relative;left:610px;width:225px;text-align:center;} 



#div_st {padding:0 0px;position:relative;height:955px;}



@media all and (-webkit-min-device-pixel-ratio:10000),

not all and (-webkit-min-device-pixel-ratio:0) {

 #div_st {height:955px;}

}

#div_st2 {padding:0 0px;position:relative;height:6750px;}



@media all and (-webkit-min-device-pixel-ratio:10000),

not all and (-webkit-min-device-pixel-ratio:0) {

 #div_st2 {height:6750px;}

}

#div_st3 {padding:0 0px;position:relative;height:800px;}



@media all and (-webkit-min-device-pixel-ratio:10000),

not all and (-webkit-min-device-pixel-ratio:0) {

 #div_st3 {height:869px;}

}



div {

	display:block;

}



.sequ_container {

	width:100%;

	height:100%;

	margin:0px;

	padding:0px;

}



.background_div {

	width:980px;

	height:950px;

	background-image:url('../root/msite/coffee/background.png');

}



.logo {

	position:absolute;

	float:right;

	right:80px;

	top:70px;

	background-image:url('../root/msite/coffee/logo.png');

	background-repeat:no-repeat;

	width:335px;

	height:168px;

}



.girl {

	position:absolute;

	float:right;

	right:47px;

	top:685px;

	background-image:url('../root/msite/coffee/girl.png');

	width:363px;

	height:201px;

}



.text_r {

	position:relative;

	float:right;

	width:390px;

	right:45px;

	top:265px;

}



#p_adv {

	font-family:Adventure;

	font:Adventure;	

	font-size:10pt;

	font-weight:bold;

	letter-spacing:1px;

	text-align:right;

	color:#775e4b;

}



.cup {

	position:absolute;

	float:left;

	left:10px;

	top:10px;

	background-image:url('../root/msite/coffee/cup.png');

	width:285px;

	height:236px;

}



@font-face {

	font-family:Adventure;

	src:url(http://www.eurodonetsk.com/public_html/root/msite/coffee/adventure_font.ttf);

}



.sil {

	position:relative;

	float:left;

	width:250px;

	left:30px;

	top:400px;

	font-family:Adventure;

	src:url(http://www.eurodonetsk.com/public_html/root/msite/coffee/adventure_font.ttf);

	font:Adventure;	

	font-size:16pt;

	font-weight:bold;

	font-style:bold;

	letter-spacing:1px;

	color:#775e4b;

}



.mid_pho {

	position:absolute;

	float:left;

	left:285px;

	top:120px;

	background-image:url('../root/msite/coffee/mid_pho.png');

	width:276px;

	height:760px;

}



.girl2 {

	position:absolute;

	float:right;

	right:50px;

	top:6485px;

	background-image:url('../root/msite/coffee/girl.png');

	width:363px;

	height:201px;

}



.background_div2 {

	position:relative;

	float:left;

	display:block;

	width:980px;

	height:6750px;

	background-image:url('../root/msite/coffee/menu_bg.png');

}



.menu {

	position:relative;

	float:right;

	width:540px;

	right:45px;

	top:265px;

	font-family:Adventure;

	src:url(http://www.eurodonetsk.com/public_html/root/msite/coffee/adventure_font.ttf);

	font:Adventure;	

	font-size:16pt;

	font-weight:bold;

	font-style:bold;

	letter-spacing:1px;

	color:#775e4b;

}



.tab {


	font-size:12pt;

	text-align:left;

}



.menu_2 {

	position:relative;

	float:right;

	width:594px;

	right:45px;

	top:265px;

	font-family:Adventure;

	src:url(http://www.eurodonetsk.com/public_html/root/msite/coffee/adventure_font.ttf);

	font:Adventure;	

	font-size:16pt;

	font-weight:bold;

	font-style:bold;

	letter-spacing:1px;

	color:#775e4b;

}

*{padding:0; margin:0}

#main_miradent {	width:980px;
					margin:10px auto 10px auto;
					background-color:#f1f1f1;
					border-bottom:5px solid #f1f1f1;
				}
#menu_miradent {	
					margin:43px 0 0 0;
					height:50px;		
				}		
#menu_miradent ul { list-style:none;}
#menu_miradent li { float:left; margin:2px 1px 0 1px; height:50px; }
#menu_miradent span {text-align:center; font-size:16px;}
#menu_miradent a { 
			color:#e0532e; 
			text-decoration:none; 
			font-size:18px; 
			background-image: url(../root/msite/miradent/button.png); 
			display:block; 
			height:50px;
			width:90px; 
			text-align:center; 
			}			
#menu_miradent a:hover { 
				color:#e0532e; 
				text-decoration:none; 
				font-size:18px; 
				background-image: url(../root/msite/miradent/button_hover.png); 
				display:block; 
				height:50px; 
				text-align:center;
				width:90px; 
				}
#mir_miradent a { 
			color:#e0532e; 
			text-decoration:none; 
			font-size:18px; 
			background-image: url(../root/msite/miradent/button.png); background-repeat:no-repeat;
			display:block; 
			height:50px;
			width:140px; 
			text-align:center; 
			padding:15px 0 5px 0;
			}
			
#mir_miradent a:hover 	{ 
				color:#e0532e; 
				text-decoration:none; 
				font-size:18px; 
				background-image: url(../root/msite/miradent/button_hover.png);  background-repeat:no-repeat;
				display:block; 
				height:50px; 
				text-align:center;
				width:140px; 
				padding:15px 0 5px 0;
				}



#blic_miradent a { 
			color:#e0532e; 
			text-decoration:none; 
			font-size:18px; 
			background-image: url(../root/msite/miradent/button.png); background-repeat:no-repeat;
			display:block; 
			height:50px;
			width:140px; 
			text-align:center; 
			padding:5px 0 5px 0;
			}
#blic_miradent a:hover 	{ 
				color:#e0532e; 
				text-decoration:none; 
				font-size:18px; 
				background-image: url(../root/msite/miradent/button_hover.png);  	background-repeat:no-repeat;
				display:block; 
				height:50px; 
				text-align:center;
				width:140px; 
				padding:5px 0 5px 0;
				}
			
			
#link_r_miradent li { float:left; margin:2px 1px 0 1px; height:50px; width:120px;}

#link_r_miradent a { 
			color:#e0532e; 
			text-decoration:none; 
			font-size:18px; 
			background-image: url(../root/msite/miradent/buttonkont.png); 
			display:block; 
			height:50px; 
			text-align:center; 
			width:120px;
			filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src="./file's/buttonkont.png", sizingMethod='crop');//background:;
			}
			
#link_r_miradent a:hover { 
			color:#e0532e; 
			text-decoration:none; 
			font-size:18px; 
			background-image: url(../root/msite/miradent/buttonkont_hover.png); 
			display:block; 
			height:50px;
			width:120px; 
			text-align:center; 
			filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src="./file's/buttonkont_hover.png", sizingMethod='crop');//background:; 
			}


										/* --LEFT BUTTOM--*/

#tab_content_miradent {
		margin:0 auto 10px auto;
		background-color:#FFF;
		font-family:Georgia, "Times New Roman", Times, serif;
	}
	
#left_content_miradent {
		width:260px;
		vertical-align:top;
	}
		
#left_content_miradent span {
			text-align:center;  
			}
#left_content_miradent a { 
			color:#e0532e; 
			text-decoration:none; 
			font-size:22px; 
			background-image: url(../root/msite/miradent/oval.jpg); 
			background-repeat:no-repeat; 
			display:block; 
			height:250px; 
			width:250; 
			text-align:center; 
			border:none;
			padding:15px 0 0 0;
			filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src="./file's/zub.png", sizingMethod='crop');//background:;
			}	
	
#left_content_miradent a:hover { 
				color:#e0532e; 
				text-decoration:none; 
				font-size:20px;
				font-style:italic;
				font-weight:bold; 
				background-image: url(../root/msite/miradent/oval_hover.jpg); 
				background-repeat:no-repeat; 
				display:block; 
				height:250px; 
				width:250; 
				text-align:center;
				border:none; 
				filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src="./file's/zub_hover.png", sizingMethod='crop');//background:;
				}
#left_content_miradent a:active { 
				color:#000; 
				text-decoration:none; 
				font-size:20px;
				font-style:italic;
				font-weight:bold; 
				background-image: url(../root/msite/miradent/oval_hover.jpg); 
				background-repeat:no-repeat; 
				display:block; 
				height:250px; 
				width:250; 
				text-align:center;
				border:none; 
				filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src="./file's/zub_hover.png", sizingMethod='crop');//background:;
				}


												/* --TEXT_CONTENT--*/
												
#text_content_miradent p {	
			padding:15px 25px 15px 5px;
			font-size:20px;
			font-family:Times New Roman;
			text-align: justify;
			}
#text_content_miradent hr{ width:85%; color:#006; margin:5px auto 5px auto;}			
#text_content_miradent span { font-size:16px; font-style:italic; font-weight:900; padding:5px 0 0 5px;}
#text_content_miradent h3 { font-size:22px;
			font-family:Helvetica;
			padding:50px 0 0 5px;
			text-align:center;
			text-decoration:underline;
     		}

#text_content_miradent h1 {font-size:20px; margin:25px 0 10px 0; text-align:center;}
#text_content_miradent h6 {font-size:18px; text-align:center; font-weight:400; color:#0C0;}
#text_content_miradent h4 {font-size:18px; text-align:center; font-weight:bold; color:#0C0;}
#text_content_miradent h2 {	color: #00C;
			text-align:left;
			font-size:16px;
			padding:5px 0  3px 5px;
			}
#text_content_miradent h5 {font-size:16px; font-style:italic; font-weight:900; padding:5px 0 0 5px;}			
#text_content_miradent ul  {padding:0 0 0 20px;}				
#text_content_miradent li {font-size:16px; font-family:"Myriad Pro"; padding:5px 25px 5px 10px;}
#text_content_miradent a {text-decoration:none; padding:5px 10px 15px 15px; color:#006;}
#text_content_miradent a:hover {text-decoration:underline;} 

#est_rev_content_miradent {display:none;}
#otbel_content_miradent {display:none;}
#ortoped_content_miradent {display:none;}

#price_miradent {
					width:90%;
					margin:30px auto 40px auto;
					color:#003;
					font-family:Arial, Helvetica, sans-serif;
				 }
#price_miradent h3 {
					color:#0C0; 
					font-size:16px; 
					text-align:left; 
					padding:0; 
					text-decoration:none;
					}
#price_miradent h1 {
					color:#0C0; 
					font-size:17px; 
					text-align:center; 
					padding:5px 0;
					}


</style>

<?php

if ($_GET['pm'] == 1) 

{

?>

<script language="javascript" type="text/javascript">
	function show_hide(objectID){
		var object=document.getElementById(objectID);
		if (object.style.display=='none')
			object.style.display='block';
			else
			object.style.display='none';
			return;
	}
</script>

<div class="catalogue_item_cont_m"> 

	<div id="main_miradent">
				<table background="../root/msite/miradent/upper.jpg" height="380px" width="980px" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td style="padding:35px 0 0 40px;" height="125px"><a href="index.html"><img src="../root/msite/miradent/logo_eng.png" border="0" align="left" alt="Dentistry Miradent (Ukraine, Donetsk)"/></a></td>
  </tr>
   <tr>
    <td>
    	<p align="left" style="font-size:20px; padding:5px 0 0 10px;font-weight:600; font-family:Times New Roman;">Donetsk city, Mira broad street, 2</p> 
		<p align="left" style="font-size:20px; padding:5px 0 0 10px; font-weight:600; font-family:Times New Roman;">t.: +38  062-381-18-24; m.: +38 050-696-47-70</p>
		<p align="left" style="font-size:20px; padding:5px 0 0 10px;font-weight:600; font-family:Times New Roman;">DC «Blic»: Donetsk city, Razdolnaya street, 13</p>
		<p align="left" style="font-size:20px; padding:5px 0 0 10px; font-weight:600; font-family:Times New Roman;">t.: +38 062 389-33-04; м.: +38 050 057-43-78</p>      </td>
  </tr>
  <tr>
    <td height="50px">
    			<div id="menu_miradent">
                		<ul>
                        	<li id="mir_miradent"><a href="index.php?business_full=491&pm=2"><span style="text-align:center; font-size:18px; position:relative; top:-12px; font-family:Times New Roman;">Dentistry</span> <span style="text-align:center; font-size:18px; position:relative; top:-12px;">MIRADENT</span></a></li>
                            <li><a href="index.php?business_full=491&pm=1"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;"> MC BLIC </span></a></li>
                            <li><a href="index.php?business_full=491&pm=3"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;"> About us </span></a></li>
                            <li><a href="index.php?business_full=491&pm=4"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;"> Price </span></a></li>
                            <li><a href="index.php?business_full=491&pm=5"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;"> Vacancies </span></a></li>
                            <li id="link_r_miradent"><a href="index.php?business_full=491&pm=6"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;"> Contacts </span></a></li>
                        </ul>
                </div>       
    </td>
  </tr>
</table>
<table id="tab_content_miradent" width="970px" align="center" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td id="left_content_miradent">
     <br />
      <a href="javascript:show_hide('est_rev_content_miradent')"><br /><br /><br /><span style="position:relative; top:10px;">Aesthetic <br />restoration</span></a>
        	  	<br />
      <a href="javascript:show_hide('otbel_content_miradent')"><br /><br /><br /><span style="position:relative; top:10px;">Bleaching<br />"Beyond"</span></a> 
        	    <br />
   	  <a href="javascript:show_hide('ortoped_content_miradent')"><br /><br /><br /><span style="position:relative; top:10px;">Root canal<br />treatment</span></a>
    </td>
    <td valign="top">
      <div id="text_content_miradent">
      <div id="est_rev_content_miradent">
      <h3>Esthetic tooth restoration</h3>   
  <p>Highly developed civilization has  demands to dentists not just to strive with pain but also to restore masticatory function. Nowadays it's quite important to save and to recreate the beauty of healthy teeth. This role is for <strong>esthetic restoration</strong>. The main function of it is restoration of the initial tooth color, size and shape.</p>
<p><strong>Dental restorative materials</strong> has analogy structure with strong tooth tissues. It is designed in different tints that allows to reproduce in esthetic restoration colored tinges of natural teeth. <strong>Polymer material</strong>  are spreaded in layers on ready teeth in compliance with color and shape of lost tooth tissues with the help of special lamp.</p>
<p>Painless, reliability, and beauty is the aim of esthetic restoration.</p>
<h2>Esthetic tooth restoration : Technology</h2>
<p>In modern life of new technologies perfect smile opens boundless opportunity for person in his/her private life and career growth. People's tooth are different in complexity and variety of forms, structures etc. All this properties the dentist tries to recreate in art restoration, to make your smile natural and beauty.</p>
<p>Modern laboratories of international leading companies creates and improves materials for restoration.
Among all the materials there are photopolymer for restoration of tooth masticatory groups, fluid photopolymer for surface adaptation, universal photopolymer for filling of  any tooth defects, materials for artistic restoration. </p>
<p>Photopolymer restoration of tooth treatment is very spared. Connection between material and surface is realized by penetration of binding agent to intercrystalline voids and provides so called intimate attachment. Teeth is consolidated by fiber pin in case of teeth destruction.
  <strong>Artistic tooth restoration</strong> gives you healthy smile and confidence in your specificity.</p>

<hr />
	</div>
    
  <div id="otbel_content_miradent">
	<h3>Tooth bleaching</h3> 
<p>A lot of people in modern life pay attention to the health of  their tooth  and it's appearance! Make your smile perfect! If you want to have a white tooth and a great smile than choose the <strong>Beyond system</strong>. Your smile become white and shine in <strong>30 minutes</strong>. The bleaching system will provide the most possible effect even if your tooth are got dark because of smocking, having drinks that contains dyestuff, lost it's natural bleach because of having medicine such as tetracycline or if it get covered with spots because of  antibiotic's usage, surplus of fluorine.</p>
<p>The system «<strong>Beyond Whitening Accelerator</strong>» is the best choice for reaching white and health smile in a short period of time. The spots are removed, the color of tooth will be improved on 10-14 tints, just after the first use. The level of tooth color improvement depends on patient's desire and doctor's advice. The innovation  program of accelerator allows to select the individual procedure of bleaching to each patient.</p>
<p>The <strong>system Beyond</strong> consists in process of putting special bleaching gel on surface of tooth and it's activation with the help of cold light of lamp «<strong>Beyond Whitening Accelerator</strong>». <strong>Bleaching gel</strong> consists of hydrogen peroxide (35 percent) and other components that improves the result, warns rise of sensitivity and strengthen enamel.</p>
<p>The process of <strong>dental bleaching</strong> is possible because of  hydrogen peroxide penetration through enamel and spreading all over the teeth. Enamel, dentin, connecting materials and plugs are not damaged by bleaching.</p>

<p><strong>The advantages of bleaching system Beyond:</strong></p>
	<p>- Comfort and convenience: Has no claims of preliminary procedures with the exception of occupational hygiene's cleaning; single-engine bleaching of 16-20 tooth during 30 minutes. This procedure excludes  gum irritation and periodont. Accelerator of bleaching works by means of law temperature that decrease the rise of tooth sensitivity.</p>
<p>Improved gel's formula has pH, selected in imitation of pH saliva, it is safe for enamel.</p>
	<p>- Security: accelerator bleaching is powerful halogen lamp, that radiant cold blue light filtered by 12 000 conduits and by the system of optical lens. Bad ultraviolet and infrared radiation is cleared away without any harm for surface of tooth.</p>
<p>In case of observing all recommendation in looking after dental bleaching and use all remedies at home, your tooth will be excellent. </p>


<p> <strong>Beyond Power Whitening System</strong> – is the most powerful system of cosmetic dental bleaching and it is leading technology that guarantees safe and comfort. More details about the system on web site <a href="#">www.beyonddent.com.ua</a>.</p>


<h2>Tooth Decoration</h2>
<p>Nowadays <strong>tooth decoration "skies"</strong> has  huge popularity among people of different age. It can be usual strass, Swarowsky crystal or diamonds in gold setting. Variety of it's shape and color gives an opportunity to select something special for you.</p>
<p>Decoration is fixed on teeth without any disturbance for structure of enamel, with the help of special dental fixative material.</p>
<p>It is possible to take the decoration off at any time. With the help of skies it is possible to underline your individuality and make your smile brilliant!</p>
<hr />   
</div>

<div id="ortoped_content_miradent">
<h3>Root canal treatment </h3>
<p>If the treatment of carious tooth is not in time disease may spread to dental pulp and later to ligamentous teeth apparatus and bony part of jaw. As a result there is hard pain, edema, inflammation and removal of tooth.</p>
<p><strong>Endodontic treatment</strong> is set of activities directed at conflict with infection inside the teeth and gives opportunity to  the teeth normal functioning.</p>
<p><strong>Root canal treatment</strong> is one of the most important area of preventive dentistry.</p>
<p><strong>Endodonic dentyst is responsible fo</strong>r:</p>
<p>- Provision with access to root canal;</p>
<p>- Canal's passing to the top of root;</p>
<p>- Removal of infected and  dead tissues from the canal;</p>
<p>- Gives form for canal that is necessary for correct filling;</p>
<p>- Medical canal's treatment to the final removal of pathogenic bacterias;</p>
<p>- Filling the canal with special excipient.</p>
<p>In difficult and neglected cases it is impossible to treat the canal at one visit. Sometimes it is necessary to left the teeth opened, put medicine under provisional filling. All stages of root canal treatment are performed with latest device, instruments and materials. 
Modern international <strong>dentistry Miradent</strong> has  considerable store of remedies and methods of qualitative and reliable root treatment. Correctness of  treatment is controlled and supported by special device, namely apexlocator and  roentgenogram.</p> 
<p>Method of preparation and filling of root canal is selected according to it's structure,   form and diagnosis. 
We use the most progressive technologies of canal's treatment and filling that  guarantees  prolongation of tooth health and life.</p>

                        <h2>Root canal treatment : Technologies</h2>
<p>Tooth caries causes the tooth pulp inflammation and  juxtahilar bone tissue. Modern dentistry Miradent allows to save such teeth without removing.
Treatment in such cases consists in <strong>special airtight filling of canal root teeth</strong>. Canal's treatment pointed at the removal of canal's infected tissues, form's conferring necessary to penetration of medicine and correct filling. </p>
<p>Canal's are of complex form. It can be thin, bent, barely passable. It is used a special manual and revolving instruments, giving an opportunity to remove inflamed tissues from clearance, to make smooth walls. In treatment process the canal is cleaned with special antiseptic agent tat neutralized pathogenic bacteria.  </p>
<p>Correct preliminary treatment supplies qualitative canal's filling and teeth saving for a long time. </p>
<h2>Secondary root canal treatment : Technologies</h2>
<p>Quite often patients visit the dentist with tooth that was treated in other clinic. In such case the teeth is in need of <strong>secondary canal root treated</strong> and more often it's possible to save it.</p>   
<p>Before repeated treatment specialist have to inspect roentgenogram. The treatment consists in removing old filling from canal, processing with disinfectant solution and compact filling.</p>
<p>The way of secondary treatment depends on <strong>filling material</strong> in canal. For removing an old filling mass it is used special designed nickel- titanic instruments. In  complicated cases in which the canal was filled with cement it is used  ultrasonic instrument with appropriate attachments. Ultrasonic crashes hard cement and remove it. Hermetic filling of root canal allows to stop the inflammatory process in bone tissue jaw. </p>

          <h2>Filling root canal : Technologies</h2>
<p>Filling root canal is logical conclusion of <strong>root canal treatment</strong>. The most real chance of clinical success is reached when the system of root canal filled on it's full apical and lateral extent.</p>
<p>The majority of modern filling methods consists in compact canal closing with gutta-percha with the use of medical paste, that harden in canal after filling. </p>
<p>With lateral condensation the canal filled with siler and then the main pin is injected which tightly close the  top of surface. Later on it is compacted with the help of special instrument and the next pin is injected. The procedure is repeated until the space of cone-shaped canal will be fully filled.</p>
<p>In case the canal was treated beforehand  with the help of special  revolving instruments it is possible to fill the cave with one conical gutta-percha pin. The pin perfectly closed all canal's space. </p>
<p>Nowadays a few dentists deny the presence of microtubule and a great number of root canal branches that also have to be filled. Exactly because of it  methods of <strong>3-D  obturation</strong> is designed.</p>
<p><strong>Technology of obturation</strong> is an effective advancement of the filling through the system of root canal by moving  condensing device in the center of thermoplastic material. In this technology it is necessary to have additional gutta-percha obturator and special devices for it's heating. 
For the technology of permanent wave (Є&Q+ Plus) electrical heating consolidator, namely plagger (Sybron Endo) is selected. Walls of the canal are smeared with siler and ready gutta-percha pin is injected till the top. Excess of gutta-percha are removed and plagger compacts gutta-percha till 4mm level from the top of cavity that seales hermetically all ways of bacteria's spreading.</p>
<p>Earlier, it was difficult to fill the system of root canal in 3-D dimension. Nowadays this reliable method fully justifies all estimated expectancies. Apart from gutta-percha it is used recently developed materials such as (epiphany, rezilony, proroot MTA) that gives more opportunities to save the teeth. </p>
<h2>Methods of apparatus diagnostics.</h2>
<p>For the statement of exact diagnosis and confirmation of treatment quality <strong>dentistry Miradent</strong> i<strong>s used  radiologic research with modern device</strong>. 
Dental installation of Miradent are equipped with interoral cameras Vista Cam of leading German manufacturer Durr Dental.</p>
<p>Camera iteratively increased the image and shows it on flat screen. Miradent dentist has an opportunity to examine the smallest details and demonstrate the elements of dental deposit to the patient, hidden carious cavity, stages and results of restoration. With the help of inter oral camera it is possible to get teeth photograph before and after dental procedures.</p>
  <hr />  
</div>

   <h3>Occupational hygiene</h3>
<p>Nowadays <strong>Occupational hygiene</strong> is the most important element of complex treatment, and also it is an integral part of therapy and prevention of such dental diseases as caries, disease of periodontium tissue (gingivitis, periodontitis). </p>
<p>It is import to have regular and correct care for oral cavity at home but it is less effective than professional one. It is quite difficult to provide full cleaning interdental      spaces or scrub patch in the difficult to access places of oral cavity, in consequence in this zone the dental deposit appears. </p>
<p><strong>Cavity deposit</strong> – it is an organic substances with the consecutive bacteria and the product of it's vital activity. Appeared in gingival zone, it's collect more patch and create atmosphere for formation of subgingival deposit (dental calculus), that cause inflammation of periodont – periodontitis. </p>
<p><strong>Professional tooth cleaning has several stages</strong>: </p>
<p> - removal of gingival deposit with the help of real time pulse-echo system;</p>
<p> - abrasion of root;</p>
<p>- removal of malacotic dental deposit with the help of special brushes. It's possible to use soda-jet device having a lot of dental deposit, that clean safely and mechanically bleaching tooth with the help of aerosol jet, that contains of water and abrasive remedy;</p>
<p> - tooth polishing with abrasive paste.</p>
<p>After removal of dental deposit it is especially effective the usage of preparation that sates teeth tissue with minerals and takes away  dental sensitivity, strengthen enamel.</p>
<p>The important stage of occupation hygiene of oral cavity is dental fluorite using fluorine-containing gels, varnishes and rinses. Fluorine is more active element, than calcium. It is join in lattice of enamel, strengthen it, make it more steady to caries, decrease heightened sensitivity and more effective after professional tooth brushing.</p>
<p>Qualified dentist of Miradent instructs the patient in principles of personal hygiene and gives  information in use of   additional remedy in oral cavity care.</p>
<p>It is recommended to visit the dentist 1-3 times a year to control tooth state and have an occupational hygiene of oral cavity.</p>


<h3>Therapy</h3>
<h2>1. Dental caries treatment</h2>
<p><strong>Caries</strong> is tooth disease that leads to injury hard tissues (enamel and dentin). The cave is formed in teeth and brings painful feeling because of sweet, cold and hot during having a meal. If the teeth is not treated in time, the destruction will reach dental pulp. Pulp's inflammation is accompanied by sharp pain. <strong>Dental caries treatment</strong> consists in excision of defective parts with the help of modern high-speed equipment. It allows to safe healthy tooth tissues.</p>
<p>All the procedures are conducted with the help of anesthesia that is absolutely painless. </p>
<p>Advanced cavity is filled in by filling material. In case of deep caries medical packing is placed on the floor of cavity that allows to protect dental pulp. </p>
<p><strong>Modern filling material</strong> has strong confluence with enamel and dentine, that is able to stand masticatory work and allows to restore color and shape of healthy teeth. </p>
<h2>2. Dental anesthetics</h2> 
<p>Say decidedly "NO" to Fear and Pain! </p>
<p>All dental procedures are conducted with the help of modern anesthetizes. Qualified specialists mastered the leading methodologies of  conducting anesthesia. There are a lot of preparation that corresponds the  peculiarities of your  organism. </p>
<p>Painless and comfortable conducting of dental procedures is the straight way to successful result in treatment! </p>





<h3>Orthopaedic treatment</h3>
<p>Partial or full loss of tooth, considerable destruction, violation of esthetic integrity are the basic statements to prosthetics. In dentistry <strong>Miradent</strong> it is practiced  full and partial laminar dental prosthesis, ceramic-metal and non-metallic coronas, bridge prosthesis,vinirs. Preparatory tooth restoration are performed with root metallic insert. Production of prosthesis used by highly qualitative materials of leading manufacturer German,France, Japan .</p>

<h2>Ceramic-metal constructions</h2>
<p><strong>Ceramic-metal corona</strong> is used in ½ part of teeth destruction to change it's form and color. It is the most popular kind of fixed tooth replacement, because of it's physical-mechanical properties that is very close to natural teeth.</p>
<p><strong>Ceramic-metal dental corona</strong> consists of metal cover with ceramic lining. Prosthetics are made individually with full anatomic form restoration, peculiarities of bite, distribution of masticatory load. Thanks to modern methods of teeth preparation to fixed prosthetics, coronas are covered tooth with high exactness that exclude inflammation in periodont, getting meal under corona and developing of carious process. Average service of modern ceramic-metal corona is about 12-15 years.</p>

<h2>Ceramic-non-metal constructions.</h2>
<p><strong>Ceramic-non-metal corona</strong> is the latest achievements in cosmetic dentistry. Coronas are made without any substance of metal. </p>
<p>Use of ceramic-non-metal allows to produce light and esthetically acceptable prosthetics. Nowadays this technology is considered to be the most harmless and  hypoallergenic for person's organism. Out of ceramic-non-metal coronas are produced (teeth is fully treated), vinirs (front part of teeth is treated), ceramic insert and lining (inlay, onlay) in case to prolong teeth life with minimal loss of strong tissues. Prosthetics and micro prosthetics of ceramic-non-metal are made strictly in compliance with form and color of patient's teeth. </p>
<p>Ceramic-non-metal has the same degree refraction of light as teeth enamel that permits to get esthetic look of prosthetics teeth.</p>

<h2>Vinirs</h2>
<p><strong>Ceramic vinirs</strong> is one of the latest achievements of modern dentistry that allows to get   the perfect esthetic result. Thin ceramic plate that fixed by special cement on the front teeth surface allows not to make any harm for inner part.</p>
<p>In spite of ceramic venir thinness it has high durability and color fastness that allows   to take away a  huge defects of enamel, to change pulpless and pigmented tooth. Use of vinirs help to have a desirable tooth shape applying spared preparation. Vinirs also play s role of alternative ways of diastem's closing.</p>
<p>Process of vinir's production takes a week. Patient has to visit dentist twice. During the first visit it performs the realization of teeth preparation, demounting of mould, identification of vinirs color, putting of provisional filling. During the second visit the dentist tries it and then fixed vinir.</p>
 
   <h2>Clasp dental prosthesis</h2>
<p><strong>Clasp dental prosthesis</strong> is a real alternative for demountable laminar dental prosthesis.  This kind of prosthetics is used by impossibility of filling tooth line by fixed prosthetics because of teeth absence. It owns more high esthetic and functional qualities. Esthetics quality of prosthesis consists in use of  locking clamp to supporting ceramic tooth that provides reliable fixation and makes it unnoticeable in oral cavity. Correct choice of construction gives an opportunity to distribute masticatory load on carrying tooth and mucous tunic.</p>

<h2>Demountable prosthesis</h2>
<p><strong>Demountable prosthesis</strong> is used in case of full or partial loss of natural tooth. Dental prosthesis is a plastic plate with artificial tooth that is fastened to jaw by sticking.  <strong>Dental prosthesis</strong> is made of qualitative material (stomatological acrylic plastic), that saves durability, color, shape and density for a long period of time. </p>





<h3>Dental implants</h3>
<p>It is method of root artificial implantation in upper/lo<strong>wer jaw. Dental</strong> implants are used as a support on which corona or bridge ceramic prosthesis are fixed. <strong>Implant's construction consists</strong> of two basic parts: </p>
<p>- implant which composed of titanic screw fulfilling the function of dental root;</p>
<p>- abatment fulfilling the function of dental culty that attaches to implant.</p>
 <p>Abatment is atteched to corona having a function of implant.</p>
<p>Method of implantation has numeral advantages in comparison with traditional methods and gives an opportunity to get dental prosthesis that has no differences in appearance and in functions with natural tooth.</p>

<p>Advantages of dental implants</p>
<p> - Implants allows to conceal defects of tooth level without turning neighboring tooth;</p>
<p> - Implants allows to conceal defects of tooth level of any extension and localization;</p>
<p> - Production of fixed constructions even on completely toothless jaws.</p>
<p>Dental surgeon places implants with local anesthesia. Sometimes implants are placed immediately after removal of diseased teeth. The procedure of placing takes a little time, but the period of healing takes 3-6 months. In this period implant has to get acclimated to bone tissue. Later on prosthesis are produced and abatment is placed. Orthopaedic constructions are fixed on abatment with the help of special cement.</p>
</div>
    </td>
  </tr>
</table>

















</div>

</div> <!-- cat_ite_cont_m -->

<?php

}

else

   if ($_GET['pm'] == 2)

   {

?>

<script language="javascript" type="text/javascript">
	function show_hide(objectID){
		var object=document.getElementById(objectID);
		if (object.style.display=='none')
			object.style.display='block';
			else
			object.style.display='none';
			return;
	}
</script>

<div class="catalogue_item_cont_m"> 

	<div id="main_miradent">
				<table background="../root/msite/miradent/upper.jpg" height="380px" width="980px" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td style="padding:35px 0 0 40px;" height="125px"><a href="index.html"><img src="../root/msite/miradent/logo_eng.png" border="0" align="left" alt="Dentistry Miradent (Ukraine, Donetsk)"/></a></td>
  </tr>
   <tr>
    <td>
    	<p align="left" style="font-size:20px; padding:5px 0 0 10px;font-weight:600; font-family:Times New Roman;">Donetsk city, Mira broad street, 2</p> 
		<p align="left" style="font-size:20px; padding:5px 0 0 10px; font-weight:600; font-family:Times New Roman;">t.: +38  062-381-18-24; m.: +38 050-696-47-70</p>
		<p align="left" style="font-size:20px; padding:5px 0 0 10px;font-weight:600; font-family:Times New Roman;">DC «Blic»: Donetsk city, Razdolnaya street, 13</p>
		<p align="left" style="font-size:20px; padding:5px 0 0 10px; font-weight:600; font-family:Times New Roman;">t.: +38 062 389-33-04; м.: +38 050 057-43-78</p>      </td>
  </tr>
  <tr>
    <td height="50px">
    			<div id="menu_miradent">
                		<ul>
                        	<li id="mir_miradent"><a href="index.php?business_full=491&pm=2"><span style="text-align:center; font-size:18px; position:relative; top:-12px; font-family:Times New Roman;">Dentistry</span> <span style="text-align:center; font-size:18px; position:relative; top:-12px;">MIRADENT</span></a></li>
                            <li><a href="index.php?business_full=491&pm=1"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;"> MC BLIC </span></a></li>
                            <li><a href="index.php?business_full=491&pm=3"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;"> About us </span></a></li>
                            <li><a href="index.php?business_full=491&pm=4"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;"> Price </span></a></li>
                            <li><a href="index.php?business_full=491&pm=5"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;"> Vacancies </span></a></li>
                            <li id="link_r_miradent"><a href="index.php?business_full=491&pm=6"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;"> Contacts </span></a></li>
                        </ul>
                </div>       
    </td>
  </tr>
</table>
<table id="tab_content_miradent" width="970px" align="center" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td id="left_content_miradent">
     <br />
      <a href="javascript:show_hide('est_rev_content_miradent')"><br /><br /><br /><span style="position:relative; top:10px;">Aesthetic <br />restoration</span></a>
        	  	<br />
      <a href="javascript:show_hide('otbel_content_miradent')"><br /><br /><br /><span style="position:relative; top:10px;">Bleaching<br />"Beyond"</span></a> 
        	    <br />
   	  <a href="javascript:show_hide('ortoped_content_miradent')"><br /><br /><br /><span style="position:relative; top:10px;">Root canal<br />treatment</span></a>
    </td>
    <td valign="top">
      <div id="text_content_miradent">
      <div id="est_rev_content_miradent">
      <h3>Esthetic tooth restoration</h3>   
  <p>Highly developed civilization has  demands to dentists not just to strive with pain but also to restore masticatory function. Nowadays it's quite important to save and to recreate the beauty of healthy teeth. This role is for <strong>esthetic restoration</strong>. The main function of it is restoration of the initial tooth color, size and shape.</p>
<p><strong>Dental restorative materials</strong> has analogy structure with strong tooth tissues. It is designed in different tints that allows to reproduce in esthetic restoration colored tinges of natural teeth. <strong>Polymer material</strong>  are spreaded in layers on ready teeth in compliance with color and shape of lost tooth tissues with the help of special lamp.</p>
<p>Painless, reliability, and beauty is the aim of esthetic restoration.</p>
<h2>Esthetic tooth restoration : Technology</h2>
<p>In modern life of new technologies perfect smile opens boundless opportunity for person in his/her private life and career growth. People's tooth are different in complexity and variety of forms, structures etc. All this properties the dentist tries to recreate in art restoration, to make your smile natural and beauty.</p>
<p>Modern laboratories of international leading companies creates and improves materials for restoration.
Among all the materials there are photopolymer for restoration of tooth masticatory groups, fluid photopolymer for surface adaptation, universal photopolymer for filling of  any tooth defects, materials for artistic restoration. </p>
<p>Photopolymer restoration of tooth treatment is very spared. Connection between material and surface is realized by penetration of binding agent to intercrystalline voids and provides so called intimate attachment. Teeth is consolidated by fiber pin in case of teeth destruction.
  <strong>Artistic tooth restoration</strong> gives you healthy smile and confidence in your specificity.</p>

<hr />
	</div>
    
  <div id="otbel_content_miradent">
	<h3>Tooth bleaching</h3> 
<p>A lot of people in modern life pay attention to the health of  their tooth  and it's appearance! Make your smile perfect! If you want to have a white tooth and a great smile than choose the <strong>Beyond system</strong>. Your smile become white and shine in <strong>30 minutes</strong>. The bleaching system will provide the most possible effect even if your tooth are got dark because of smocking, having drinks that contains dyestuff, lost it's natural bleach because of having medicine such as tetracycline or if it get covered with spots because of  antibiotic's usage, surplus of fluorine.</p>
<p>The system «<strong>Beyond Whitening Accelerator</strong>» is the best choice for reaching white and health smile in a short period of time. The spots are removed, the color of tooth will be improved on 10-14 tints, just after the first use. The level of tooth color improvement depends on patient's desire and doctor's advice. The innovation  program of accelerator allows to select the individual procedure of bleaching to each patient.</p>
<p>The <strong>system Beyond</strong> consists in process of putting special bleaching gel on surface of tooth and it's activation with the help of cold light of lamp «<strong>Beyond Whitening Accelerator</strong>». <strong>Bleaching gel</strong> consists of hydrogen peroxide (35 percent) and other components that improves the result, warns rise of sensitivity and strengthen enamel.</p>
<p>The process of <strong>dental bleaching</strong> is possible because of  hydrogen peroxide penetration through enamel and spreading all over the teeth. Enamel, dentin, connecting materials and plugs are not damaged by bleaching.</p>

<p><strong>The advantages of bleaching system Beyond:</strong></p>
	<p>- Comfort and convenience: Has no claims of preliminary procedures with the exception of occupational hygiene's cleaning; single-engine bleaching of 16-20 tooth during 30 minutes. This procedure excludes  gum irritation and periodont. Accelerator of bleaching works by means of law temperature that decrease the rise of tooth sensitivity.</p>
<p>Improved gel's formula has pH, selected in imitation of pH saliva, it is safe for enamel.</p>
	<p>- Security: accelerator bleaching is powerful halogen lamp, that radiant cold blue light filtered by 12 000 conduits and by the system of optical lens. Bad ultraviolet and infrared radiation is cleared away without any harm for surface of tooth.</p>
<p>In case of observing all recommendation in looking after dental bleaching and use all remedies at home, your tooth will be excellent. </p>


<p> <strong>Beyond Power Whitening System</strong> – is the most powerful system of cosmetic dental bleaching and it is leading technology that guarantees safe and comfort. More details about the system on web site <a href="#">www.beyonddent.com.ua</a>.</p>


<h2>Tooth Decoration</h2>
<p>Nowadays <strong>tooth decoration "skies"</strong> has  huge popularity among people of different age. It can be usual strass, Swarowsky crystal or diamonds in gold setting. Variety of it's shape and color gives an opportunity to select something special for you.</p>
<p>Decoration is fixed on teeth without any disturbance for structure of enamel, with the help of special dental fixative material.</p>
<p>It is possible to take the decoration off at any time. With the help of skies it is possible to underline your individuality and make your smile brilliant!</p>
<hr />   
</div>

<div id="ortoped_content_miradent">
<h3>Root canal treatment </h3>
<p>If the treatment of carious tooth is not in time disease may spread to dental pulp and later to ligamentous teeth apparatus and bony part of jaw. As a result there is hard pain, edema, inflammation and removal of tooth.</p>
<p><strong>Endodontic treatment</strong> is set of activities directed at conflict with infection inside the teeth and gives opportunity to  the teeth normal functioning.</p>
<p><strong>Root canal treatment</strong> is one of the most important area of preventive dentistry.</p>
<p><strong>Endodonic dentyst is responsible fo</strong>r:</p>
<p>- Provision with access to root canal;</p>
<p>- Canal's passing to the top of root;</p>
<p>- Removal of infected and  dead tissues from the canal;</p>
<p>- Gives form for canal that is necessary for correct filling;</p>
<p>- Medical canal's treatment to the final removal of pathogenic bacterias;</p>
<p>- Filling the canal with special excipient.</p>
<p>In difficult and neglected cases it is impossible to treat the canal at one visit. Sometimes it is necessary to left the teeth opened, put medicine under provisional filling. All stages of root canal treatment are performed with latest device, instruments and materials. 
Modern international <strong>dentistry Miradent</strong> has  considerable store of remedies and methods of qualitative and reliable root treatment. Correctness of  treatment is controlled and supported by special device, namely apexlocator and  roentgenogram.</p> 
<p>Method of preparation and filling of root canal is selected according to it's structure,   form and diagnosis. 
We use the most progressive technologies of canal's treatment and filling that  guarantees  prolongation of tooth health and life.</p>

                        <h2>Root canal treatment : Technologies</h2>
<p>Tooth caries causes the tooth pulp inflammation and  juxtahilar bone tissue. Modern dentistry Miradent allows to save such teeth without removing.
Treatment in such cases consists in <strong>special airtight filling of canal root teeth</strong>. Canal's treatment pointed at the removal of canal's infected tissues, form's conferring necessary to penetration of medicine and correct filling. </p>
<p>Canal's are of complex form. It can be thin, bent, barely passable. It is used a special manual and revolving instruments, giving an opportunity to remove inflamed tissues from clearance, to make smooth walls. In treatment process the canal is cleaned with special antiseptic agent tat neutralized pathogenic bacteria.  </p>
<p>Correct preliminary treatment supplies qualitative canal's filling and teeth saving for a long time. </p>
<h2>Secondary root canal treatment : Technologies</h2>
<p>Quite often patients visit the dentist with tooth that was treated in other clinic. In such case the teeth is in need of <strong>secondary canal root treated</strong> and more often it's possible to save it.</p>   
<p>Before repeated treatment specialist have to inspect roentgenogram. The treatment consists in removing old filling from canal, processing with disinfectant solution and compact filling.</p>
<p>The way of secondary treatment depends on <strong>filling material</strong> in canal. For removing an old filling mass it is used special designed nickel- titanic instruments. In  complicated cases in which the canal was filled with cement it is used  ultrasonic instrument with appropriate attachments. Ultrasonic crashes hard cement and remove it. Hermetic filling of root canal allows to stop the inflammatory process in bone tissue jaw. </p>

          <h2>Filling root canal : Technologies</h2>
<p>Filling root canal is logical conclusion of <strong>root canal treatment</strong>. The most real chance of clinical success is reached when the system of root canal filled on it's full apical and lateral extent.</p>
<p>The majority of modern filling methods consists in compact canal closing with gutta-percha with the use of medical paste, that harden in canal after filling. </p>
<p>With lateral condensation the canal filled with siler and then the main pin is injected which tightly close the  top of surface. Later on it is compacted with the help of special instrument and the next pin is injected. The procedure is repeated until the space of cone-shaped canal will be fully filled.</p>
<p>In case the canal was treated beforehand  with the help of special  revolving instruments it is possible to fill the cave with one conical gutta-percha pin. The pin perfectly closed all canal's space. </p>
<p>Nowadays a few dentists deny the presence of microtubule and a great number of root canal branches that also have to be filled. Exactly because of it  methods of <strong>3-D  obturation</strong> is designed.</p>
<p><strong>Technology of obturation</strong> is an effective advancement of the filling through the system of root canal by moving  condensing device in the center of thermoplastic material. In this technology it is necessary to have additional gutta-percha obturator and special devices for it's heating. 
For the technology of permanent wave (Є&Q+ Plus) electrical heating consolidator, namely plagger (Sybron Endo) is selected. Walls of the canal are smeared with siler and ready gutta-percha pin is injected till the top. Excess of gutta-percha are removed and plagger compacts gutta-percha till 4mm level from the top of cavity that seales hermetically all ways of bacteria's spreading.</p>
<p>Earlier, it was difficult to fill the system of root canal in 3-D dimension. Nowadays this reliable method fully justifies all estimated expectancies. Apart from gutta-percha it is used recently developed materials such as (epiphany, rezilony, proroot MTA) that gives more opportunities to save the teeth. </p>
<h2>Methods of apparatus diagnostics.</h2>
<p>For the statement of exact diagnosis and confirmation of treatment quality <strong>dentistry Miradent</strong> i<strong>s used  radiologic research with modern device</strong>. 
Dental installation of Miradent are equipped with interoral cameras Vista Cam of leading German manufacturer Durr Dental.</p>
<p>Camera iteratively increased the image and shows it on flat screen. Miradent dentist has an opportunity to examine the smallest details and demonstrate the elements of dental deposit to the patient, hidden carious cavity, stages and results of restoration. With the help of inter oral camera it is possible to get teeth photograph before and after dental procedures.</p>
  <hr />  
</div>

    <p><strong>Caries</strong> is a pathological process of strong teeth tissues gradual destruction, that leads to  enamel's and dentine's destruction. It begins with solution of mineral tooth substances  and leads to defect's formation, namely carious cavity. Depending on the depth and  degree of the strong tooth tissues affection it is possible to mark out four  stages of caries: </p>
<p>- Initial – carious spot;</p>
<p>- Superficial – enamel disturbance, small defect;</p>
<p>- Middle– Destruction of the top strong tooth tissues with the appearance of painful sensation;</p>
<p>- Deep – Destruction of the deep layer in the strong tooth tissues, that contiguous to pulp and the formation of vast carious cavity;</p>
<p> Not to have doctor's advice in time, caries leads to tooth destruction. In such a case treatment needs more serious interference.</p>
<p>Modern anesthetic preparation that are used in dental clinic Miradent provides absolutely painless treatment. Tints of filling materials are selected in tooth color.</p>
<p><strong>Enamel and dentine diseases</strong> may also appeared under the pressure of outer aggressive factor either under the pressure of inner motives. The basic reasons are: genetic predisposition, impact of ecological factors, stress, systemic diseases of organism, lack of oral cavity hygiene, consumption of a big quantity of sugar, shortage of vitamins and of minerals, absence of fluorine in water.</p>
</div>
    </td>
  </tr>
</table>

















</div>


</div> <!-- cat_ite_cont_m -->

<?php

}

else

   if ($_GET['pm'] == 3)

   {

?>

<script language="javascript" type="text/javascript">
	function show_hide(objectID){
		var object=document.getElementById(objectID);
		if (object.style.display=='none')
			object.style.display='block';
			else
			object.style.display='none';
			return;
	}
</script>

<div class="catalogue_item_cont_m"> 

	<div id="main_miradent">
				<table background="../root/msite/miradent/upper.jpg" height="380px" width="980px" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td style="padding:35px 0 0 40px;" height="125px"><a href="index.html"><img src="../root/msite/miradent/logo_eng.png" border="0" align="left" alt="Dentistry Miradent (Ukraine, Donetsk)"/></a></td>
  </tr>
   <tr>
    <td>
    	<p align="left" style="font-size:20px; padding:5px 0 0 10px;font-weight:600; font-family:Times New Roman;">Donetsk city, Mira broad street, 2</p> 
		<p align="left" style="font-size:20px; padding:5px 0 0 10px; font-weight:600; font-family:Times New Roman;">t.: +38  062-381-18-24; m.: +38 050-696-47-70</p>
		<p align="left" style="font-size:20px; padding:5px 0 0 10px;font-weight:600; font-family:Times New Roman;">DC «Blic»: Donetsk city, Razdolnaya street, 13</p>
		<p align="left" style="font-size:20px; padding:5px 0 0 10px; font-weight:600; font-family:Times New Roman;">t.: +38 062 389-33-04; м.: +38 050 057-43-78</p>      </td>
  </tr>
  <tr>
    <td height="50px">
    			<div id="menu_miradent">
                		<ul>
                        	<li id="mir_miradent"><a href="index.php?business_full=491&pm=2"><span style="text-align:center; font-size:18px; position:relative; top:-12px; font-family:Times New Roman;">Dentistry</span> <span style="text-align:center; font-size:18px; position:relative; top:-12px;">MIRADENT</span></a></li>
                            <li><a href="index.php?business_full=491&pm=1"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;"> MC BLIC </span></a></li>
                            <li><a href="index.php?business_full=491&pm=3"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;"> About us </span></a></li>
                            <li><a href="index.php?business_full=491&pm=4"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;"> Price </span></a></li>
                            <li><a href="index.php?business_full=491&pm=5"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;"> Vacancies </span></a></li>
                            <li id="link_r_miradent"><a href="index.php?business_full=491&pm=6"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;"> Contacts </span></a></li>
                        </ul>
                </div>       
    </td>
  </tr>
</table>
<table id="tab_content_miradent" width="970px" align="center" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td id="left_content_miradent">
     <br />
      <a href="javascript:show_hide('est_rev_content_miradent')"><br /><br /><br /><span style="position:relative; top:10px;">Aesthetic <br />restoration</span></a>
        	  	<br />
      <a href="javascript:show_hide('otbel_content_miradent')"><br /><br /><br /><span style="position:relative; top:10px;">Bleaching<br />"Beyond"</span></a> 
        	    <br />
   	  <a href="javascript:show_hide('ortoped_content_miradent')"><br /><br /><br /><span style="position:relative; top:10px;">Root canal<br />treatment</span></a>
    </td>
    <td valign="top">
      <div id="text_content_miradent">
      <div id="est_rev_content_miradent">
      <h3>Esthetic tooth restoration</h3>   
  <p>Highly developed civilization has  demands to dentists not just to strive with pain but also to restore masticatory function. Nowadays it's quite important to save and to recreate the beauty of healthy teeth. This role is for <strong>esthetic restoration</strong>. The main function of it is restoration of the initial tooth color, size and shape.</p>
<p><strong>Dental restorative materials</strong> has analogy structure with strong tooth tissues. It is designed in different tints that allows to reproduce in esthetic restoration colored tinges of natural teeth. <strong>Polymer material</strong>  are spreaded in layers on ready teeth in compliance with color and shape of lost tooth tissues with the help of special lamp.</p>
<p>Painless, reliability, and beauty is the aim of esthetic restoration.</p>
<h2>Esthetic tooth restoration : Technology</h2>
<p>In modern life of new technologies perfect smile opens boundless opportunity for person in his/her private life and career growth. People's tooth are different in complexity and variety of forms, structures etc. All this properties the dentist tries to recreate in art restoration, to make your smile natural and beauty.</p>
<p>Modern laboratories of international leading companies creates and improves materials for restoration.
Among all the materials there are photopolymer for restoration of tooth masticatory groups, fluid photopolymer for surface adaptation, universal photopolymer for filling of  any tooth defects, materials for artistic restoration. </p>
<p>Photopolymer restoration of tooth treatment is very spared. Connection between material and surface is realized by penetration of binding agent to intercrystalline voids and provides so called intimate attachment. Teeth is consolidated by fiber pin in case of teeth destruction.
  <strong>Artistic tooth restoration</strong> gives you healthy smile and confidence in your specificity.</p>

<hr />
	</div>
    
  <div id="otbel_content_miradent">
	<h3>Tooth bleaching</h3> 
<p>A lot of people in modern life pay attention to the health of  their tooth  and it's appearance! Make your smile perfect! If you want to have a white tooth and a great smile than choose the <strong>Beyond system</strong>. Your smile become white and shine in <strong>30 minutes</strong>. The bleaching system will provide the most possible effect even if your tooth are got dark because of smocking, having drinks that contains dyestuff, lost it's natural bleach because of having medicine such as tetracycline or if it get covered with spots because of  antibiotic's usage, surplus of fluorine.</p>
<p>The system «<strong>Beyond Whitening Accelerator</strong>» is the best choice for reaching white and health smile in a short period of time. The spots are removed, the color of tooth will be improved on 10-14 tints, just after the first use. The level of tooth color improvement depends on patient's desire and doctor's advice. The innovation  program of accelerator allows to select the individual procedure of bleaching to each patient.</p>
<p>The <strong>system Beyond</strong> consists in process of putting special bleaching gel on surface of tooth and it's activation with the help of cold light of lamp «<strong>Beyond Whitening Accelerator</strong>». <strong>Bleaching gel</strong> consists of hydrogen peroxide (35 percent) and other components that improves the result, warns rise of sensitivity and strengthen enamel.</p>
<p>The process of <strong>dental bleaching</strong> is possible because of  hydrogen peroxide penetration through enamel and spreading all over the teeth. Enamel, dentin, connecting materials and plugs are not damaged by bleaching.</p>

<p><strong>The advantages of bleaching system Beyond:</strong></p>
	<p>- Comfort and convenience: Has no claims of preliminary procedures with the exception of occupational hygiene's cleaning; single-engine bleaching of 16-20 tooth during 30 minutes. This procedure excludes  gum irritation and periodont. Accelerator of bleaching works by means of law temperature that decrease the rise of tooth sensitivity.</p>
<p>Improved gel's formula has pH, selected in imitation of pH saliva, it is safe for enamel.</p>
	<p>- Security: accelerator bleaching is powerful halogen lamp, that radiant cold blue light filtered by 12 000 conduits and by the system of optical lens. Bad ultraviolet and infrared radiation is cleared away without any harm for surface of tooth.</p>
<p>In case of observing all recommendation in looking after dental bleaching and use all remedies at home, your tooth will be excellent. </p>


<p> <strong>Beyond Power Whitening System</strong> – is the most powerful system of cosmetic dental bleaching and it is leading technology that guarantees safe and comfort. More details about the system on web site <a href="#">www.beyonddent.com.ua</a>.</p>


<h2>Tooth Decoration</h2>
<p>Nowadays <strong>tooth decoration "skies"</strong> has  huge popularity among people of different age. It can be usual strass, Swarowsky crystal or diamonds in gold setting. Variety of it's shape and color gives an opportunity to select something special for you.</p>
<p>Decoration is fixed on teeth without any disturbance for structure of enamel, with the help of special dental fixative material.</p>
<p>It is possible to take the decoration off at any time. With the help of skies it is possible to underline your individuality and make your smile brilliant!</p>
<hr />   
</div>

<div id="ortoped_content_miradent">
<h3>Root canal treatment </h3>
<p>If the treatment of carious tooth is not in time disease may spread to dental pulp and later to ligamentous teeth apparatus and bony part of jaw. As a result there is hard pain, edema, inflammation and removal of tooth.</p>
<p><strong>Endodontic treatment</strong> is set of activities directed at conflict with infection inside the teeth and gives opportunity to  the teeth normal functioning.</p>
<p><strong>Root canal treatment</strong> is one of the most important area of preventive dentistry.</p>
<p><strong>Endodonic dentyst is responsible fo</strong>r:</p>
<p>- Provision with access to root canal;</p>
<p>- Canal's passing to the top of root;</p>
<p>- Removal of infected and  dead tissues from the canal;</p>
<p>- Gives form for canal that is necessary for correct filling;</p>
<p>- Medical canal's treatment to the final removal of pathogenic bacterias;</p>
<p>- Filling the canal with special excipient.</p>
<p>In difficult and neglected cases it is impossible to treat the canal at one visit. Sometimes it is necessary to left the teeth opened, put medicine under provisional filling. All stages of root canal treatment are performed with latest device, instruments and materials. 
Modern international <strong>dentistry Miradent</strong> has  considerable store of remedies and methods of qualitative and reliable root treatment. Correctness of  treatment is controlled and supported by special device, namely apexlocator and  roentgenogram.</p> 
<p>Method of preparation and filling of root canal is selected according to it's structure,   form and diagnosis. 
We use the most progressive technologies of canal's treatment and filling that  guarantees  prolongation of tooth health and life.</p>

                        <h2>Root canal treatment : Technologies</h2>
<p>Tooth caries causes the tooth pulp inflammation and  juxtahilar bone tissue. Modern dentistry Miradent allows to save such teeth without removing.
Treatment in such cases consists in <strong>special airtight filling of canal root teeth</strong>. Canal's treatment pointed at the removal of canal's infected tissues, form's conferring necessary to penetration of medicine and correct filling. </p>
<p>Canal's are of complex form. It can be thin, bent, barely passable. It is used a special manual and revolving instruments, giving an opportunity to remove inflamed tissues from clearance, to make smooth walls. In treatment process the canal is cleaned with special antiseptic agent tat neutralized pathogenic bacteria.  </p>
<p>Correct preliminary treatment supplies qualitative canal's filling and teeth saving for a long time. </p>
<h2>Secondary root canal treatment : Technologies</h2>
<p>Quite often patients visit the dentist with tooth that was treated in other clinic. In such case the teeth is in need of <strong>secondary canal root treated</strong> and more often it's possible to save it.</p>   
<p>Before repeated treatment specialist have to inspect roentgenogram. The treatment consists in removing old filling from canal, processing with disinfectant solution and compact filling.</p>
<p>The way of secondary treatment depends on <strong>filling material</strong> in canal. For removing an old filling mass it is used special designed nickel- titanic instruments. In  complicated cases in which the canal was filled with cement it is used  ultrasonic instrument with appropriate attachments. Ultrasonic crashes hard cement and remove it. Hermetic filling of root canal allows to stop the inflammatory process in bone tissue jaw. </p>

          <h2>Filling root canal : Technologies</h2>
<p>Filling root canal is logical conclusion of <strong>root canal treatment</strong>. The most real chance of clinical success is reached when the system of root canal filled on it's full apical and lateral extent.</p>
<p>The majority of modern filling methods consists in compact canal closing with gutta-percha with the use of medical paste, that harden in canal after filling. </p>
<p>With lateral condensation the canal filled with siler and then the main pin is injected which tightly close the  top of surface. Later on it is compacted with the help of special instrument and the next pin is injected. The procedure is repeated until the space of cone-shaped canal will be fully filled.</p>
<p>In case the canal was treated beforehand  with the help of special  revolving instruments it is possible to fill the cave with one conical gutta-percha pin. The pin perfectly closed all canal's space. </p>
<p>Nowadays a few dentists deny the presence of microtubule and a great number of root canal branches that also have to be filled. Exactly because of it  methods of <strong>3-D  obturation</strong> is designed.</p>
<p><strong>Technology of obturation</strong> is an effective advancement of the filling through the system of root canal by moving  condensing device in the center of thermoplastic material. In this technology it is necessary to have additional gutta-percha obturator and special devices for it's heating. 
For the technology of permanent wave (Є&Q+ Plus) electrical heating consolidator, namely plagger (Sybron Endo) is selected. Walls of the canal are smeared with siler and ready gutta-percha pin is injected till the top. Excess of gutta-percha are removed and plagger compacts gutta-percha till 4mm level from the top of cavity that seales hermetically all ways of bacteria's spreading.</p>
<p>Earlier, it was difficult to fill the system of root canal in 3-D dimension. Nowadays this reliable method fully justifies all estimated expectancies. Apart from gutta-percha it is used recently developed materials such as (epiphany, rezilony, proroot MTA) that gives more opportunities to save the teeth. </p>
<h2>Methods of apparatus diagnostics.</h2>
<p>For the statement of exact diagnosis and confirmation of treatment quality <strong>dentistry Miradent</strong> i<strong>s used  radiologic research with modern device</strong>. 
Dental installation of Miradent are equipped with interoral cameras Vista Cam of leading German manufacturer Durr Dental.</p>
<p>Camera iteratively increased the image and shows it on flat screen. Miradent dentist has an opportunity to examine the smallest details and demonstrate the elements of dental deposit to the patient, hidden carious cavity, stages and results of restoration. With the help of inter oral camera it is possible to get teeth photograph before and after dental procedures.</p>
  <hr />  
</div>

  <h3>Dentistry Miradent : About us </h3>
<p><strong>Dentistry Miradent</strong> was founded in Donetsk (Ukraine) in 2001 on basis of modern equipment for the treatment and diagnostics,using the leading technology and high level of dental services. It is situated in the center of Donetsk, broad street Mira, 2.</p>
<p> The basic aim of the dentistry clinic <strong>Miradent</strong> creation is rendering of qualified dental treatment to patients. The pledge successful work of dental room is professionalism, complex diagnostic and treatment with the individual attitude towards every client.</p>
<p>The <strong>Miradent</strong> dentistry group is highly qualified specialists with work experience from 5 to 20 years. There are doctors of the first category, who specialize in such  spheres as therapeutic, orthopedic dentistry, root canal treatment and also assistants, nurses.</p>
<p>The main principles of the dentistry clinic <strong>Miradent</strong> activity are: putting correct diagnosis, realization of professional treatment and organization of preventive measures. There is careful attitude toward patient, comfortable atmosphere, competent specialists, regular renovation of material and technical basis,  knowledges and skills improvement in the Miradent dentistry. </p>
<p>In <strong>Miradent</strong> clinic there are <strong>therapeutic</strong>, <strong>orthopedic</strong> reception of patient, <strong>root canal treatment</strong> and also<strong> halogen bleaching of tooth</strong>, that has advantage compared to traditional ones. </p>
<p>In <strong>Miradent</strong> dentistry It is possible to take full spectrum of dental service on the highest level namely painless  caries treatment, esthetic tooth restoration, bleaching, preventive tooth cleaning, periodontist treatment, root canal and orthopedic treatment.</p>
<p><strong>Miradent</strong> dentist's long work experience shows that about 80 percent of  visitors, taking the first advice in the clinic, became our constant patients, thanks to the quality of services rendered, available prices. Of no small importance the fact of accomplishment sanitary and hygienic norms and requirements. The basis mass of materials and instruments (disposal/reusable instruments) has a frequent sterilization.</p>
<p>Everybody should visit <strong>dentistry Miradent</strong> even without any pressure in dental treatment to take free doctor's advice and complex examination. The patient has an opportunity to take information about services and it's prices, to sign up for the the doctor's examination at the clinic's administrator  by  telephone or personally. </p>
<p>Before  reception, the patient fill in the dental form and the clinic agreement on treatment' realization (therapeutic, orthopedic, cosmetology, root canal treatment). The warranty to patient
 is recorded in the dental form.</p>
<p>The dentistry offers payment in cash and clearing (direct payment through insurance companies).</p>
</div>
    </td>
  </tr>
</table>

















</div>

</div> <!-- cat_ite_cont_m -->

<?php

}

else

   if ($_GET['pm'] == 4)

   {

?>

<script language="javascript" type="text/javascript">
	function show_hide(objectID){
		var object=document.getElementById(objectID);
		if (object.style.display=='none')
			object.style.display='block';
			else
			object.style.display='none';
			return;
	}
</script>

<div class="catalogue_item_cont_m"> 

	<div id="main_miradent">
				<table background="../root/msite/miradent/upper.jpg" height="380px" width="980px" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td style="padding:35px 0 0 40px;" height="125px"><a href="index.html"><img src="../root/msite/miradent/logo_eng.png" border="0" align="left" alt="Dentistry Miradent (Ukraine, Donetsk)"/></a></td>
  </tr>
   <tr>
    <td>
    	<p align="left" style="font-size:20px; padding:5px 0 0 10px;font-weight:600; font-family:Times New Roman;">Donetsk city, Mira broad street, 2</p> 
		<p align="left" style="font-size:20px; padding:5px 0 0 10px; font-weight:600; font-family:Times New Roman;">t.: +38  062-381-18-24; m.: +38 050-696-47-70</p>
		<p align="left" style="font-size:20px; padding:5px 0 0 10px;font-weight:600; font-family:Times New Roman;">DC «Blic»: Donetsk city, Razdolnaya street, 13</p>
		<p align="left" style="font-size:20px; padding:5px 0 0 10px; font-weight:600; font-family:Times New Roman;">t.: +38 062 389-33-04; м.: +38 050 057-43-78</p>      </td>
  </tr>
  <tr>
    <td height="50px">
    			<div id="menu_miradent">
                		<ul>
                        	<li id="mir_miradent"><a href="index.php?business_full=491&pm=2"><span style="text-align:center; font-size:18px; position:relative; top:-12px; font-family:Times New Roman;">Dentistry</span> <span style="text-align:center; font-size:18px; position:relative; top:-12px;">MIRADENT</span></a></li>
                            <li><a href="index.php?business_full=491&pm=1"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;"> MC BLIC </span></a></li>
                            <li><a href="index.php?business_full=491&pm=3"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;"> About us </span></a></li>
                            <li><a href="index.php?business_full=491&pm=4"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;"> Price </span></a></li>
                            <li><a href="index.php?business_full=491&pm=5"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;"> Vacancies </span></a></li>
                            <li id="link_r_miradent"><a href="index.php?business_full=491&pm=6"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;"> Contacts </span></a></li>
                        </ul>
                </div>       
    </td>
  </tr>
</table>
<table id="tab_content_miradent" width="970px" align="center" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td id="left_content_miradent">
     <br />
      <a href="javascript:show_hide('est_rev_content_miradent')"><br /><br /><br /><span style="position:relative; top:10px;">Aesthetic <br />restoration</span></a>
        	  	<br />
      <a href="javascript:show_hide('otbel_content_miradent')"><br /><br /><br /><span style="position:relative; top:10px;">Bleaching<br />"Beyond"</span></a> 
        	    <br />
   	  <a href="javascript:show_hide('ortoped_content_miradent')"><br /><br /><br /><span style="position:relative; top:10px;">Root canal<br />treatment</span></a>
    </td>
    <td valign="top">
      <div id="text_content_miradent">
      <div id="est_rev_content_miradent">
      <h3>Esthetic tooth restoration</h3>   
  <p>Highly developed civilization has  demands to dentists not just to strive with pain but also to restore masticatory function. Nowadays it's quite important to save and to recreate the beauty of healthy teeth. This role is for <strong>esthetic restoration</strong>. The main function of it is restoration of the initial tooth color, size and shape.</p>
<p><strong>Dental restorative materials</strong> has analogy structure with strong tooth tissues. It is designed in different tints that allows to reproduce in esthetic restoration colored tinges of natural teeth. <strong>Polymer material</strong>  are spreaded in layers on ready teeth in compliance with color and shape of lost tooth tissues with the help of special lamp.</p>
<p>Painless, reliability, and beauty is the aim of esthetic restoration.</p>
<h2>Esthetic tooth restoration : Technology</h2>
<p>In modern life of new technologies perfect smile opens boundless opportunity for person in his/her private life and career growth. People's tooth are different in complexity and variety of forms, structures etc. All this properties the dentist tries to recreate in art restoration, to make your smile natural and beauty.</p>
<p>Modern laboratories of international leading companies creates and improves materials for restoration.
Among all the materials there are photopolymer for restoration of tooth masticatory groups, fluid photopolymer for surface adaptation, universal photopolymer for filling of  any tooth defects, materials for artistic restoration. </p>
<p>Photopolymer restoration of tooth treatment is very spared. Connection between material and surface is realized by penetration of binding agent to intercrystalline voids and provides so called intimate attachment. Teeth is consolidated by fiber pin in case of teeth destruction.
  <strong>Artistic tooth restoration</strong> gives you healthy smile and confidence in your specificity.</p>

<hr />
	</div>
    
  <div id="otbel_content_miradent">
	<h3>Tooth bleaching</h3> 
<p>A lot of people in modern life pay attention to the health of  their tooth  and it's appearance! Make your smile perfect! If you want to have a white tooth and a great smile than choose the <strong>Beyond system</strong>. Your smile become white and shine in <strong>30 minutes</strong>. The bleaching system will provide the most possible effect even if your tooth are got dark because of smocking, having drinks that contains dyestuff, lost it's natural bleach because of having medicine such as tetracycline or if it get covered with spots because of  antibiotic's usage, surplus of fluorine.</p>
<p>The system «<strong>Beyond Whitening Accelerator</strong>» is the best choice for reaching white and health smile in a short period of time. The spots are removed, the color of tooth will be improved on 10-14 tints, just after the first use. The level of tooth color improvement depends on patient's desire and doctor's advice. The innovation  program of accelerator allows to select the individual procedure of bleaching to each patient.</p>
<p>The <strong>system Beyond</strong> consists in process of putting special bleaching gel on surface of tooth and it's activation with the help of cold light of lamp «<strong>Beyond Whitening Accelerator</strong>». <strong>Bleaching gel</strong> consists of hydrogen peroxide (35 percent) and other components that improves the result, warns rise of sensitivity and strengthen enamel.</p>
<p>The process of <strong>dental bleaching</strong> is possible because of  hydrogen peroxide penetration through enamel and spreading all over the teeth. Enamel, dentin, connecting materials and plugs are not damaged by bleaching.</p>

<p><strong>The advantages of bleaching system Beyond:</strong></p>
	<p>- Comfort and convenience: Has no claims of preliminary procedures with the exception of occupational hygiene's cleaning; single-engine bleaching of 16-20 tooth during 30 minutes. This procedure excludes  gum irritation and periodont. Accelerator of bleaching works by means of law temperature that decrease the rise of tooth sensitivity.</p>
<p>Improved gel's formula has pH, selected in imitation of pH saliva, it is safe for enamel.</p>
	<p>- Security: accelerator bleaching is powerful halogen lamp, that radiant cold blue light filtered by 12 000 conduits and by the system of optical lens. Bad ultraviolet and infrared radiation is cleared away without any harm for surface of tooth.</p>
<p>In case of observing all recommendation in looking after dental bleaching and use all remedies at home, your tooth will be excellent. </p>


<p> <strong>Beyond Power Whitening System</strong> – is the most powerful system of cosmetic dental bleaching and it is leading technology that guarantees safe and comfort. More details about the system on web site <a href="#">www.beyonddent.com.ua</a>.</p>


<h2>Tooth Decoration</h2>
<p>Nowadays <strong>tooth decoration "skies"</strong> has  huge popularity among people of different age. It can be usual strass, Swarowsky crystal or diamonds in gold setting. Variety of it's shape and color gives an opportunity to select something special for you.</p>
<p>Decoration is fixed on teeth without any disturbance for structure of enamel, with the help of special dental fixative material.</p>
<p>It is possible to take the decoration off at any time. With the help of skies it is possible to underline your individuality and make your smile brilliant!</p>
<hr />   
</div>

<div id="ortoped_content_miradent">
<h3>Root canal treatment </h3>
<p>If the treatment of carious tooth is not in time disease may spread to dental pulp and later to ligamentous teeth apparatus and bony part of jaw. As a result there is hard pain, edema, inflammation and removal of tooth.</p>
<p><strong>Endodontic treatment</strong> is set of activities directed at conflict with infection inside the teeth and gives opportunity to  the teeth normal functioning.</p>
<p><strong>Root canal treatment</strong> is one of the most important area of preventive dentistry.</p>
<p><strong>Endodonic dentyst is responsible fo</strong>r:</p>
<p>- Provision with access to root canal;</p>
<p>- Canal's passing to the top of root;</p>
<p>- Removal of infected and  dead tissues from the canal;</p>
<p>- Gives form for canal that is necessary for correct filling;</p>
<p>- Medical canal's treatment to the final removal of pathogenic bacterias;</p>
<p>- Filling the canal with special excipient.</p>
<p>In difficult and neglected cases it is impossible to treat the canal at one visit. Sometimes it is necessary to left the teeth opened, put medicine under provisional filling. All stages of root canal treatment are performed with latest device, instruments and materials. 
Modern international <strong>dentistry Miradent</strong> has  considerable store of remedies and methods of qualitative and reliable root treatment. Correctness of  treatment is controlled and supported by special device, namely apexlocator and  roentgenogram.</p> 
<p>Method of preparation and filling of root canal is selected according to it's structure,   form and diagnosis. 
We use the most progressive technologies of canal's treatment and filling that  guarantees  prolongation of tooth health and life.</p>

                        <h2>Root canal treatment : Technologies</h2>
<p>Tooth caries causes the tooth pulp inflammation and  juxtahilar bone tissue. Modern dentistry Miradent allows to save such teeth without removing.
Treatment in such cases consists in <strong>special airtight filling of canal root teeth</strong>. Canal's treatment pointed at the removal of canal's infected tissues, form's conferring necessary to penetration of medicine and correct filling. </p>
<p>Canal's are of complex form. It can be thin, bent, barely passable. It is used a special manual and revolving instruments, giving an opportunity to remove inflamed tissues from clearance, to make smooth walls. In treatment process the canal is cleaned with special antiseptic agent tat neutralized pathogenic bacteria.  </p>
<p>Correct preliminary treatment supplies qualitative canal's filling and teeth saving for a long time. </p>
<h2>Secondary root canal treatment : Technologies</h2>
<p>Quite often patients visit the dentist with tooth that was treated in other clinic. In such case the teeth is in need of <strong>secondary canal root treated</strong> and more often it's possible to save it.</p>   
<p>Before repeated treatment specialist have to inspect roentgenogram. The treatment consists in removing old filling from canal, processing with disinfectant solution and compact filling.</p>
<p>The way of secondary treatment depends on <strong>filling material</strong> in canal. For removing an old filling mass it is used special designed nickel- titanic instruments. In  complicated cases in which the canal was filled with cement it is used  ultrasonic instrument with appropriate attachments. Ultrasonic crashes hard cement and remove it. Hermetic filling of root canal allows to stop the inflammatory process in bone tissue jaw. </p>

          <h2>Filling root canal : Technologies</h2>
<p>Filling root canal is logical conclusion of <strong>root canal treatment</strong>. The most real chance of clinical success is reached when the system of root canal filled on it's full apical and lateral extent.</p>
<p>The majority of modern filling methods consists in compact canal closing with gutta-percha with the use of medical paste, that harden in canal after filling. </p>
<p>With lateral condensation the canal filled with siler and then the main pin is injected which tightly close the  top of surface. Later on it is compacted with the help of special instrument and the next pin is injected. The procedure is repeated until the space of cone-shaped canal will be fully filled.</p>
<p>In case the canal was treated beforehand  with the help of special  revolving instruments it is possible to fill the cave with one conical gutta-percha pin. The pin perfectly closed all canal's space. </p>
<p>Nowadays a few dentists deny the presence of microtubule and a great number of root canal branches that also have to be filled. Exactly because of it  methods of <strong>3-D  obturation</strong> is designed.</p>
<p><strong>Technology of obturation</strong> is an effective advancement of the filling through the system of root canal by moving  condensing device in the center of thermoplastic material. In this technology it is necessary to have additional gutta-percha obturator and special devices for it's heating. 
For the technology of permanent wave (Є&Q+ Plus) electrical heating consolidator, namely plagger (Sybron Endo) is selected. Walls of the canal are smeared with siler and ready gutta-percha pin is injected till the top. Excess of gutta-percha are removed and plagger compacts gutta-percha till 4mm level from the top of cavity that seales hermetically all ways of bacteria's spreading.</p>
<p>Earlier, it was difficult to fill the system of root canal in 3-D dimension. Nowadays this reliable method fully justifies all estimated expectancies. Apart from gutta-percha it is used recently developed materials such as (epiphany, rezilony, proroot MTA) that gives more opportunities to save the teeth. </p>
<h2>Methods of apparatus diagnostics.</h2>
<p>For the statement of exact diagnosis and confirmation of treatment quality <strong>dentistry Miradent</strong> i<strong>s used  radiologic research with modern device</strong>. 
Dental installation of Miradent are equipped with interoral cameras Vista Cam of leading German manufacturer Durr Dental.</p>
<p>Camera iteratively increased the image and shows it on flat screen. Miradent dentist has an opportunity to examine the smallest details and demonstrate the elements of dental deposit to the patient, hidden carious cavity, stages and results of restoration. With the help of inter oral camera it is possible to get teeth photograph before and after dental procedures.</p>
  <hr />  
</div>
<h3>Dentistry Miradent : Price list </h3>

<h1>Examination and doctor's advice is free of charge!</h1>
<h4>Dental clinic Miradent : price list </h4>
<h6>on separate kinds of dental services</h6>

    <table id="price_miradent" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td><h3>Teeth preparation to prosthetics</h3></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><h3>Recovery of teeth culty</h3></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td> - metallic non separable inset NPG  </td>
    <td>350-400</td>
  </tr>
  <tr>
    <td> - metallic collapsible inset  NPG</td>
    <td>450-550</td>
  </tr>
  <tr>
    <td><h3>Production of fixed artificial limb</h3></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>Steel stamped corona</td>
    <td>250</td>
  </tr>
  <tr>
    <td>Cast steel dental bridge</td>
    <td>250</td>
  </tr>
  <tr>
    <td>Cast teeth, lined with facet</td>
    <td>300</td>
  </tr>
  <tr>
    <td>Corona with plastic lining</td>
    <td>400</td>
  </tr>
  <tr>
    <td>Corona casted by KHS</td>
    <td>400</td>
  </tr>
  <tr>
    <td>Corona casted by NPG (yellow metal)</td>
    <td>350-400</td>
  </tr>
  <tr>
    <td>Ceramic-metal corona</td>
    <td>800</td>
  </tr>
  <tr>
    <td>Ceramic-metal teeth</td>
    <td>800</td>
  </tr>
  <tr>
    <td>Non-metallic ceramic inset</td>
    <td>800</td>
  </tr>
  <tr>
    <td>Non-metallic ceramic (vinir-corona) Ivoclar  Pom</td>
    <td>1200-1500</td>
  </tr>
  <tr>
    <td><h3>Production of removable artificial limb</h3></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>Partial removable artificial limb</td>
    <td>800</td>
  </tr>
  <tr>
    <td>Full removable artificial limb</td>
    <td>800</td>
  </tr>
  <tr>
    <td>Production of individual spoon</td>
    <td>100</td>
  </tr>
  <tr>
    <td><h3>Production of clasp dental prosthesis</h3></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>Clasp dental prosthesis (supported)</td>
    <td>3500</td>
  </tr>
  <tr>
    <td>Fastening in clasp dental prosthesis</td>
    <td>300</td>
  </tr>
  <tr>
    <td><h1>Therapy</h1></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><h3>Anesthesia carpul syringe:</h3></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>Steptanest (France)</td>
    <td>30</td>
  </tr>
  <tr>
    <td>Ubistezin (Germany)</td>
    <td>35</td>
  </tr>
  <tr>
    <td>Mepivastezine (Germany)</td>
    <td>30</td>
  </tr>
  <tr>
    <td>Ultracaine (Germany)</td>
    <td>35</td>
  </tr>
  <tr>
    <td>Artizin-health-forte</td>
    <td>25</td>
  </tr>
  <tr>
    <td>Articaine</td>
    <td>25</td>
  </tr>
  <tr>
    <td><h3>Treatment of  complicated caries (pulp,periodentitis)</h3></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>single-rooted tooth (Epiphany + gutta-percha)</td>
    <td>300-350</td>
  </tr>
  <tr>
    <td>double-rooted tooth(Epiphany + gutta-percha)</td>
    <td>350-400</td>
  </tr>
  <tr>
    <td>triple-rooted tooth (Epiphany + gutta-percha)</td>
    <td>450-500</td>
  </tr>
  <tr>
    <td>single-rooted tooth (AH Plus + gutta-percha)</td>
    <td>300-350</td>
  </tr>
  <tr>
    <td>double-rooted tooth (AH Plus + gutta-percha)</td>
    <td>350-400</td>
  </tr>
  <tr>
    <td>triple-rooted tooth (AH Plus + gutta-percha)</td>
    <td>450-500</td>
  </tr>
  <tr>
    <td>single-rooted tooth (hot gutta-percha Є&Q+ Plus )</td>
    <td>400</td>
  </tr>
  <tr>
    <td>double-rooted tooth (hot gutta-percha Є&Q+ Plus)</td>
    <td>500</td>
  </tr>
  <tr>
    <td>triple-rooted tooth (hot gutta-percha Є&Q+ Plus)</td>
    <td>600</td>
  </tr>
  <tr>
    <td><h3>Suture of a plug consisting of photopolymerize material:</h3></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>«Gradia Direct»(Japan)</td>
    <td>250-350</td>
  </tr>
  <tr>
    <td>«Amelogel Universal» (USA)</td>
    <td>250-350</td>
  </tr>
  <tr>
    <td>«Karisma» (Germany)</td>
    <td>230-300</td>
  </tr>
  <tr>
    <td>«Karisma Opal» (Germany)</td>
    <td>270-370</td>
  </tr>
  <tr>
    <td>«Soliter» (Germay)</td>
    <td>250-350</td>
  </tr>
  <tr>
    <td>«Tetrikceram» (Germany)</td>
    <td>250-350</td>
  </tr>
  <tr>
    <td>«Estet Х-НD» (Germany)</td>
    <td>270-370</td>
  </tr>
  <tr>
    <td>«Enemel Plus» (Italy)</td>
    <td>350-450</td>
  </tr>
  <tr>
    <td><h3>Restoration of corona's part of teeth:</h3></td>
    <td>&nbsp;</td>
  </tr>
   <tr>
    <td>«Feeltek suprim», «Estet Х-HD», «Karima Opal»,  «Gradia Direct» etc.</td>
    <td>З50-500</td>
  </tr>
   <tr>
    <td>«Enemel Plus»</td>
    <td>600-700</td>
  </tr>
   <tr>
    <td><h3>Removal of teeth scurf:</h3></td>
    <td>&nbsp;</td>
  </tr>
   <tr>
    <td>Ultrasonic</td>
    <td>250-350</td>
  </tr>
   <tr>
    <td>soda-jet device Air Flow</td>
    <td>350-450</td>
  </tr>
   <tr>
    <td><h3>Dental bleaching:</h3></td>
    <td>&nbsp;</td>
  </tr>
   <tr>
    <td>System  «Opalescence Extra» «Ultradent»(USA)</td>
    <td>30 1 unit/1visit</td>
  </tr>
   <tr>
    <td>System «Max 5» Beyond pole (USA)</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td> - Single-engine bleaching of all front teeth</td>
    <td>1200-1400</td>
  </tr>
  <tr>
    <td> - Bleaching of one tooth (dotty)</td>
    <td>60 1unit/visit</td>
  </tr>
</table>

    
</div>
    </td>
  </tr>
</table>

















</div>


</div> <!-- cat_ite_cont_m -->

<?php

}

else

   if ($_GET['pm'] == 5)

   {

?>

<script language="javascript" type="text/javascript">
	function show_hide(objectID){
		var object=document.getElementById(objectID);
		if (object.style.display=='none')
			object.style.display='block';
			else
			object.style.display='none';
			return;
	}
</script>

<div class="catalogue_item_cont_m"> 

	<div id="main_miradent">
				<table background="../root/msite/miradent/upper.jpg" height="380px" width="980px" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td style="padding:35px 0 0 40px;" height="125px"><a href="index.html"><img src="../root/msite/miradent/logo_eng.png" border="0" align="left" alt="Dentistry Miradent (Ukraine, Donetsk)"/></a></td>
  </tr>
   <tr>
    <td>
    	<p align="left" style="font-size:20px; padding:5px 0 0 10px;font-weight:600; font-family:Times New Roman;">Donetsk city, Mira broad street, 2</p> 
		<p align="left" style="font-size:20px; padding:5px 0 0 10px; font-weight:600; font-family:Times New Roman;">t.: +38  062-381-18-24; m.: +38 050-696-47-70</p>
		<p align="left" style="font-size:20px; padding:5px 0 0 10px;font-weight:600; font-family:Times New Roman;">DC «Blic»: Donetsk city, Razdolnaya street, 13</p>
		<p align="left" style="font-size:20px; padding:5px 0 0 10px; font-weight:600; font-family:Times New Roman;">t.: +38 062 389-33-04; м.: +38 050 057-43-78</p>      </td>
  </tr>
  <tr>
    <td height="50px">
    			<div id="menu_miradent">
                		<ul>
                        	<li id="mir_miradent"><a href="index.php?business_full=491&pm=2"><span style="text-align:center; font-size:18px; position:relative; top:-12px; font-family:Times New Roman;">Dentistry</span> <span style="text-align:center; font-size:18px; position:relative; top:-12px;">MIRADENT</span></a></li>
                            <li><a href="index.php?business_full=491&pm=1"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;"> MC BLIC </span></a></li>
                            <li><a href="index.php?business_full=491&pm=3"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;"> About us </span></a></li>
                            <li><a href="index.php?business_full=491&pm=4"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;"> Price </span></a></li>
                            <li><a href="index.php?business_full=491&pm=5"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;"> Vacancies </span></a></li>
                            <li id="link_r_miradent"><a href="index.php?business_full=491&pm=6"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;"> Contacts </span></a></li>
                        </ul>
                </div>       
    </td>
  </tr>
</table>
<table id="tab_content_miradent" width="970px" align="center" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td id="left_content_miradent">
     <br />
      <a href="javascript:show_hide('est_rev_content_miradent')"><br /><br /><br /><span style="position:relative; top:10px;">Aesthetic <br />restoration</span></a>
        	  	<br />
      <a href="javascript:show_hide('otbel_content_miradent')"><br /><br /><br /><span style="position:relative; top:10px;">Bleaching<br />"Beyond"</span></a> 
        	    <br />
   	  <a href="javascript:show_hide('ortoped_content_miradent')"><br /><br /><br /><span style="position:relative; top:10px;">Root canal<br />treatment</span></a>
    </td>
    <td valign="top">
      <div id="text_content_miradent">
      <div id="est_rev_content_miradent">
      <h3>Esthetic restoration</h3>   
  <p>Highly developed civilization has  demands to dentists not just to strive with pain but also to restore masticatory function. Nowadays it's quite important to save and to recreate the beauty of healthy teeth. This role is for esthetic restoration. The main function of it is restoration of the initial tooth color, size and shape.</p>
<p>Materials for  restoration has analogy structure with strong tooth tissues. It is designed in different tints that allows to reproduce in esthetic restoration colored tinges of natural teeth. Materials of photopolymer  are spreaded in layers on ready teeth in compliance with color and shape of lost tooth tissues with the help of special lamp.</p>
<p>Painless, reliability, and beauty is the aim of esthetic restoration.</p>
<h2>Technology of esthetic restoration of tooth</h2>
<p>In modern life of new technologies perfect smile opens boundless opportunity for person in his/her private life and career growth. People's tooth are different in complexity and variety of forms, structures etc. All this properties the dentist tries to recreate in art restoration, to make your smile natural and beauty.</p>
<p>Modern laboratories of international leading companies creates and improves materials for restoration.
Among all the materials there are photopolymer for restoration of tooth masticatory groups, fluid photopolymer for surface adaptation, universal photopolymer for filling of  any tooth defects, materials for artistic restoration. </p>
<p>Photopolymer restoration of tooth treatment is very spared. Connection between material and surface is realized by penetration of binding agent to intercrystalline voids and provides so called intimate attachment. Teeth is consolidated by fiber pin in case of teeth destruction.
Artistic restoration gives you healthy smile and confidence in your specificity.</p>

<hr />
	</div>
    
  <div id="otbel_content_miradent">
	<h3>Bleaching</h3> 
<p>A lot of people in modern life pay attention to the health of  their tooth  and it's appearance! Make your smile perfect! If you want to have a white tooth and a great smile than choose the Beyond system. Your smile become white and shine in 30 minutes. The bleaching system will provide the most possible effect even if your tooth are got dark because of smocking, having drinks that contains dyestuff, lost it's natural bleach because of having medicine such as tetracycline or if it get covered with spots because of  antibiotic's usage, surplus of fluorine.</p>
<p>The system «Beyond Whitening Accelerator» is the best choice for reaching white and health smile in a short period of time. The spots are removed, the color of tooth will be improved on 10-14 tints, just after the first use. The level of tooth color improvement depends on patient's desire and doctor's advice. The innovation  program of accelerator allows to select the individual procedure of bleaching to each patient.</p>
<p>The system Beyond consists in process of putting special bleaching gel on surface of tooth and it's activation with the help of cold light of lamp «Beyond Whitening Accelerator». Bleaching gel consists of hydrogen peroxide (35 percent) and other components that improves the result, warns rise of sensitivity and strengthen enamel.</p>
<p>The process of dental bleaching is possible because of  hydrogen peroxide penetration through enamel and spreading all over the teeth. Enamel, dentin, connecting materials and plugs are not damaged by bleaching.</p>

<p>The advantages of bleaching system Beyond:</p>
	<p>- Comfort and convenience: Has no claims of preliminary procedures with the exception of occupational hygiene's cleaning; single-engine bleaching of 16-20 tooth during 30 minutes. This procedure excludes  gum irritation and periodont. Accelerator of bleaching works by means of law temperature that decrease the rise of tooth sensitivity.</p>
<p>Improved gel's formula has pH, selected in imitation of pH saliva, it is safe for enamel.</p>
	<p>- Security: accelerator bleaching is powerful halogen lamp, that radiant cold blue light filtered by 12 000 conduits and by the system of optical lens. Bad ultraviolet and infrared radiation is cleared away without any harm for surface of tooth.</p>
<p>In case of observing all recommendation in looking after dental bleaching and use all remedies at home, your tooth will be excellent. </p>


<p> Beyond Power Whitening System – is the most powerful system of cosmetic dental bleaching and it is leading technology that guarantees safe and comfort. More details about the system on web site <a href="#">www.beyonddent.com.ua</a>.</p>


<h2>Tooth Decoration</h2>
<p>Nowadays tooth decoration "skies" has  huge popularity among people of different age. It can be usual strass, Swarowsky crystal or diamonds in gold setting. Variety of it's shape and color gives an opportunity to select something special for you.</p>
<p>Decoration is fixed on teeth without any disturbance for structure of enamel, with the help of special dental fixative material.</p>
<p>It is possible to take the decoration off at any time. With the help of skies it is possible to underline your individuality and make your smile brilliant!</p>
<hr />   
</div>

<div id="ortoped_content_miradent">
<h3>Root canal treatment</h3>
<p>If the treatment of carious tooth is not in time disease may spread to dental pulp and later to ligamentous teeth apparatus and bony part of jaw. As a result there is hard pain, edema, inflammation and removal of tooth.</p>
<p>Endodontic treatment is set of activities directed at conflict with infection inside the teeth and gives opportunity to  the teeth normal functioning.</p>
<p>Root canal treatment is one of the most important area of preventive dentistry.</p>
<p>Endodonic doctor is responsible for:</p>
<p>- Provision with access to root canal;</p>
<p>- Canal's passing to the top of root;</p>
<p>- Removal of infected and  dead tissues from the canal;</p>
<p>- Gives form for canal that is necessary for correct filling;</p>
<p>- Medical canal's treatment to the final removal of pathogenic bacterias;</p>
<p>- Filling the canal with special excipient.</p>
<p>In difficult and neglected cases it is impossible to treat the canal at one visit. Sometimes it is necessary to left the teeth opened, put medicine under provisional filling. All stages of root canal treatment are performed with latest device, instruments and materials. 
Modern international dentistry has  considerable store of remedies and methods of qualitative and reliable root treatment. Correctness of  treatment is controlled and supported by special device, namely apexlocator and  roentgenogram.</p> 
<p>Method of preparation and filling of root canal is selected according to it's structure,   form and diagnosis. 
We use the most progressive technologies of canal's treatment and filling that  guarantees  prolongation of tooth health and life.</p>

                        <h2>Technologies of root canal treatment</h2>
<p>Tooth caries causes the tooth pulp inflammation and  juxtahilar bone tissue. Modern dentistry  allows to save such teeth without removing.
Treatment in such cases consists in special airtight filling of canal root teeth. Canal's treatment pointed at the removal of canal's infected tissues, form's conferring necessary to penetration of medicine and correct filling. </p>
<p>Canal's are of complex form. It can be thin, bent, barely passable. It is used a special manual and revolving instruments, giving an opportunity to remove inflamed tissues from clearance, to make smooth walls. In treatment process the canal is cleaned with special antiseptic agent tat neutralized pathogenic bacteria.  </p>
<p>Correct preliminary treatment supplies qualitative canal's filling and teeth saving for a long time. </p>
<h2>Technologies of secondary root canal treatment</h2>
<p>Quite often patients visit the dentist with tooth that was treated in other clinic. In such case the teeth is in need of secondary canal root treated and more often it's possible to save it.</p>   
<p>Before repeated treatment specialist have to inspect roentgenogram. The treatment consists in removing old filling from canal, processing with disinfectant solution and compact filling.</p>
<p>The way of secondary treatment depends on filling material in canal. For removing an old filling mass it is used special designed nickel- titanic instruments. In  complicated cases in which the canal was filled with cement it is used  ultrasonic instrument with appropriate attachments. Ultrasonic crashes hard cement and remove it. Hermetic filling of root canal allows to stop the inflammatory process in bone tissue jaw. </p>

          <h2>Technologies of filling root canal</h2>
<p>Filling of root canal is logical conclusion of root canal treatment. The most real chance of clinical success is reached when the system of root canal filled on it's full apical and lateral extent.</p>
<p>The majority of modern filling methods consists in compact canal closing with gutta-percha with the use of medical paste, that harden in canal after filling. </p>
<p>With lateral condensation the canal filled with siler and then the main pin is injected which tightly close the  top of surface. Later on it is compacted with the help of special instrument and the next pin is injected. The procedure is repeated until the space of cone-shaped canal will be fully filled.</p>
<p>In case the canal was treated beforehand  with the help of special  revolving instruments it is possible to fill the cave with one conical gutta-percha pin. The pin perfectly closed all canal's space. </p>
<p>Nowadays a few dentists deny the presence of microtubule and a great number of root canal branches that also have to be filled. Exactly because of it  methods of 3-D  obturation is designed.</p>
<p>Technology of obturation is an effective advancement of the filling through the system of root canal by moving  condensing device in the center of thermoplastic material. In this technology it is necessary to have additional gutta-percha obturator and special devices for it's heating. 
For the technology of permanent wave (Є&Q+ Plus) electrical heating consolidator, namely plagger (Sybron Endo) is selected. Walls of the canal are smeared with siler and ready gutta-percha pin is injected till the top. Excess of gutta-percha are removed and plagger compacts gutta-percha till 4mm level from the top of cavity that seales hermetically all ways of bacteria's spreading.</p>
<p>Earlier, it was difficult to fill the system of root canal in 3-D dimension. Nowadays this reliable method fully justifies all estimated expectancies. Apart from gutta-percha it is used recently developed materials such as (epiphany, rezilony, proroot MTA) that gives more opportunities to save the teeth. </p>
<h2>Methods of apparatus diagnostics.</h2>
<p>For the statement of exact diagnosis and confirmation of treatment quality it is used  radiologic research with modern device. 
Dental installation are equipped with interoral cameras Vista Cam of leading German manufacturer Durr Dental.</p>
<p>Camera iteratively increased the image and shows it on flat screen. Dentist has an opportunity to examine the smallest details and demonstrate the elements of dental deposit to the patient, hidden carious cavity, stages and results of restoration. With the help of inter oral camera it is possible to get teeth photograph before and after dental procedures.</p>
  <hr />  
</div>

    <h3>Dentistry Miradent (Ukraine, Donetsk) : Vacancies</h3>
<p>Dental clinic is required for dentist with work experience from 5 years for regular work. The presence of personal licence is welcomed</p>
</div>
    </td>
  </tr>
</table>

















</div>


</div> <!-- cat_ite_cont_m -->

<?php

}

else

   if ($_GET['pm'] == 6)

   {

?>

<script language="javascript" type="text/javascript">
	function show_hide(objectID){
		var object=document.getElementById(objectID);
		if (object.style.display=='none')
			object.style.display='block';
			else
			object.style.display='none';
			return;
	}
</script>

<div class="catalogue_item_cont_m"> 

	<div id="main_miradent">
				<table background="../root/msite/miradent/upper.jpg" height="380px" width="980px" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td style="padding:35px 0 0 40px;" height="125px"><a href="index.html"><img src="../root/msite/miradent/logo_eng.png" border="0" align="left" alt="Dentistry Miradent (Ukraine, Donetsk)"/></a></td>
  </tr>
   <tr>
    <td>
    	<p align="left" style="font-size:20px; padding:5px 0 0 10px;font-weight:600; font-family:Times New Roman;">Donetsk city, Mira broad street, 2</p> 
		<p align="left" style="font-size:20px; padding:5px 0 0 10px; font-weight:600; font-family:Times New Roman;">t.: +38  062-381-18-24; m.: +38 050-696-47-70</p>
		<p align="left" style="font-size:20px; padding:5px 0 0 10px;font-weight:600; font-family:Times New Roman;">DC «Blic»: Donetsk city, Razdolnaya street, 13</p>
		<p align="left" style="font-size:20px; padding:5px 0 0 10px; font-weight:600; font-family:Times New Roman;">t.: +38 062 389-33-04; м.: +38 050 057-43-78</p>      </td>
  </tr>
  <tr>
    <td height="50px">
    			<div id="menu_miradent">
                		<ul>
                        	<li id="mir_miradent"><a href="index.php?business_full=491&pm=2"><span style="text-align:center; font-size:18px; position:relative; top:-12px; font-family:Times New Roman;">Dentistry</span> <span style="text-align:center; font-size:18px; position:relative; top:-12px;">MIRADENT</span></a></li>
                            <li><a href="index.php?business_full=491&pm=1"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;"> MC BLIC </span></a></li>
                            <li><a href="index.php?business_full=491&pm=3"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;"> About us </span></a></li>
                            <li><a href="index.php?business_full=491&pm=4"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;"> Price </span></a></li>
                            <li><a href="index.php?business_full=491&pm=5"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;"> Vacancies </span></a></li>
                            <li id="link_r_miradent"><a href="index.php?business_full=491&pm=6"><br /><span style="text-align:center; font-size:18px; font-family:Times New Roman;"> Contacts </span></a></li>
                        </ul>
                </div>       
    </td>
  </tr>
</table>
<table id="tab_content_miradent" width="970px" align="center" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td id="left_content_miradent">
     <br />
      <a href="javascript:show_hide('est_rev_content_miradent')"><br /><br /><br /><span style="position:relative; top:10px;">Aesthetic <br />restoration</span></a>
        	  	<br />
      <a href="javascript:show_hide('otbel_content_miradent')"><br /><br /><br /><span style="position:relative; top:10px;">Bleaching<br />"Beyond"</span></a> 
        	    <br />
   	  <a href="javascript:show_hide('ortoped_content_miradent')"><br /><br /><br /><span style="position:relative; top:10px;">Root canal<br />treatment</span></a>
    </td>
    <td valign="top">
      <div id="text_content_miradent">
      <div id="est_rev_content_miradent">
      <h3>Esthetic restoration</h3>   
  <p>Highly developed civilization has  demands to dentists not just to strive with pain but also to restore masticatory function. Nowadays it's quite important to save and to recreate the beauty of healthy teeth. This role is for esthetic restoration. The main function of it is restoration of the initial tooth color, size and shape.</p>
<p>Materials for  restoration has analogy structure with strong tooth tissues. It is designed in different tints that allows to reproduce in esthetic restoration colored tinges of natural teeth. Materials of photopolymer  are spreaded in layers on ready teeth in compliance with color and shape of lost tooth tissues with the help of special lamp.</p>
<p>Painless, reliability, and beauty is the aim of esthetic restoration.</p>
<h2>Technology of esthetic restoration of tooth</h2>
<p>In modern life of new technologies perfect smile opens boundless opportunity for person in his/her private life and career growth. People's tooth are different in complexity and variety of forms, structures etc. All this properties the dentist tries to recreate in art restoration, to make your smile natural and beauty.</p>
<p>Modern laboratories of international leading companies creates and improves materials for restoration.
Among all the materials there are photopolymer for restoration of tooth masticatory groups, fluid photopolymer for surface adaptation, universal photopolymer for filling of  any tooth defects, materials for artistic restoration. </p>
<p>Photopolymer restoration of tooth treatment is very spared. Connection between material and surface is realized by penetration of binding agent to intercrystalline voids and provides so called intimate attachment. Teeth is consolidated by fiber pin in case of teeth destruction.
Artistic restoration gives you healthy smile and confidence in your specificity.</p>

<hr />
	</div>
    
  <div id="otbel_content_miradent">
	<h3>Bleaching</h3> 
<p>A lot of people in modern life pay attention to the health of  their tooth  and it's appearance! Make your smile perfect! If you want to have a white tooth and a great smile than choose the Beyond system. Your smile become white and shine in 30 minutes. The bleaching system will provide the most possible effect even if your tooth are got dark because of smocking, having drinks that contains dyestuff, lost it's natural bleach because of having medicine such as tetracycline or if it get covered with spots because of  antibiotic's usage, surplus of fluorine.</p>
<p>The system «Beyond Whitening Accelerator» is the best choice for reaching white and health smile in a short period of time. The spots are removed, the color of tooth will be improved on 10-14 tints, just after the first use. The level of tooth color improvement depends on patient's desire and doctor's advice. The innovation  program of accelerator allows to select the individual procedure of bleaching to each patient.</p>
<p>The system Beyond consists in process of putting special bleaching gel on surface of tooth and it's activation with the help of cold light of lamp «Beyond Whitening Accelerator». Bleaching gel consists of hydrogen peroxide (35 percent) and other components that improves the result, warns rise of sensitivity and strengthen enamel.</p>
<p>The process of dental bleaching is possible because of  hydrogen peroxide penetration through enamel and spreading all over the teeth. Enamel, dentin, connecting materials and plugs are not damaged by bleaching.</p>

<p>The advantages of bleaching system Beyond:</p>
	<p>- Comfort and convenience: Has no claims of preliminary procedures with the exception of occupational hygiene's cleaning; single-engine bleaching of 16-20 tooth during 30 minutes. This procedure excludes  gum irritation and periodont. Accelerator of bleaching works by means of law temperature that decrease the rise of tooth sensitivity.</p>
<p>Improved gel's formula has pH, selected in imitation of pH saliva, it is safe for enamel.</p>
	<p>- Security: accelerator bleaching is powerful halogen lamp, that radiant cold blue light filtered by 12 000 conduits and by the system of optical lens. Bad ultraviolet and infrared radiation is cleared away without any harm for surface of tooth.</p>
<p>In case of observing all recommendation in looking after dental bleaching and use all remedies at home, your tooth will be excellent. </p>


<p> Beyond Power Whitening System – is the most powerful system of cosmetic dental bleaching and it is leading technology that guarantees safe and comfort. More details about the system on web site <a href="#">www.beyonddent.com.ua</a>.</p>


<h2>Tooth Decoration</h2>
<p>Nowadays tooth decoration "skies" has  huge popularity among people of different age. It can be usual strass, Swarowsky crystal or diamonds in gold setting. Variety of it's shape and color gives an opportunity to select something special for you.</p>
<p>Decoration is fixed on teeth without any disturbance for structure of enamel, with the help of special dental fixative material.</p>
<p>It is possible to take the decoration off at any time. With the help of skies it is possible to underline your individuality and make your smile brilliant!</p>
<hr />   
</div>

<div id="ortoped_content_miradent">
<h3>Root canal treatment </h3>
<p>If the treatment of carious tooth is not in time disease may spread to dental pulp and later to ligamentous teeth apparatus and bony part of jaw. As a result there is hard pain, edema, inflammation and removal of tooth.</p>
<p>Endodontic treatment is set of activities directed at conflict with infection inside the teeth and gives opportunity to  the teeth normal functioning.</p>
<p>Root canal treatment is one of the most important area of preventive dentistry.</p>
<p>Endodonic doctor is responsible for:</p>
<p>- Provision with access to root canal;</p>
<p>- Canal's passing to the top of root;</p>
<p>- Removal of infected and  dead tissues from the canal;</p>
<p>- Gives form for canal that is necessary for correct filling;</p>
<p>- Medical canal's treatment to the final removal of pathogenic bacterias;</p>
<p>- Filling the canal with special excipient.</p>
<p>In difficult and neglected cases it is impossible to treat the canal at one visit. Sometimes it is necessary to left the teeth opened, put medicine under provisional filling. All stages of root canal treatment are performed with latest device, instruments and materials. 
Modern international dentistry has  considerable store of remedies and methods of qualitative and reliable root treatment. Correctness of  treatment is controlled and supported by special device, namely apexlocator and  roentgenogram.</p> 
<p>Method of preparation and filling of root canal is selected according to it's structure,   form and diagnosis. 
We use the most progressive technologies of canal's treatment and filling that  guarantees  prolongation of tooth health and life.</p>

                        <h2>Technologies of root canal treatment</h2>
<p>Tooth caries causes the tooth pulp inflammation and  juxtahilar bone tissue. Modern dentistry  allows to save such teeth without removing.
Treatment in such cases consists in special airtight filling of canal root teeth. Canal's treatment pointed at the removal of canal's infected tissues, form's conferring necessary to penetration of medicine and correct filling. </p>
<p>Canal's are of complex form. It can be thin, bent, barely passable. It is used a special manual and revolving instruments, giving an opportunity to remove inflamed tissues from clearance, to make smooth walls. In treatment process the canal is cleaned with special antiseptic agent tat neutralized pathogenic bacteria.  </p>
<p>Correct preliminary treatment supplies qualitative canal's filling and teeth saving for a long time. </p>
<h2>Technologies of secondary root canal treatment</h2>
<p>Quite often patients visit the dentist with tooth that was treated in other clinic. In such case the teeth is in need of secondary canal root treated and more often it's possible to save it.</p>   
<p>Before repeated treatment specialist have to inspect roentgenogram. The treatment consists in removing old filling from canal, processing with disinfectant solution and compact filling.</p>
<p>The way of secondary treatment depends on filling material in canal. For removing an old filling mass it is used special designed nickel- titanic instruments. In  complicated cases in which the canal was filled with cement it is used  ultrasonic instrument with appropriate attachments. Ultrasonic crashes hard cement and remove it. Hermetic filling of root canal allows to stop the inflammatory process in bone tissue jaw. </p>

          <h2>Technologies of filling root canal</h2>
<p>Filling of root canal is logical conclusion of root canal treatment. The most real chance of clinical success is reached when the system of root canal filled on it's full apical and lateral extent.</p>
<p>The majority of modern filling methods consists in compact canal closing with gutta-percha with the use of medical paste, that harden in canal after filling. </p>
<p>With lateral condensation the canal filled with siler and then the main pin is injected which tightly close the  top of surface. Later on it is compacted with the help of special instrument and the next pin is injected. The procedure is repeated until the space of cone-shaped canal will be fully filled.</p>
<p>In case the canal was treated beforehand  with the help of special  revolving instruments it is possible to fill the cave with one conical gutta-percha pin. The pin perfectly closed all canal's space. </p>
<p>Nowadays a few dentists deny the presence of microtubule and a great number of root canal branches that also have to be filled. Exactly because of it  methods of 3-D  obturation is designed.</p>
<p>Technology of obturation is an effective advancement of the filling through the system of root canal by moving  condensing device in the center of thermoplastic material. In this technology it is necessary to have additional gutta-percha obturator and special devices for it's heating. 
For the technology of permanent wave (Є&Q+ Plus) electrical heating consolidator, namely plagger (Sybron Endo) is selected. Walls of the canal are smeared with siler and ready gutta-percha pin is injected till the top. Excess of gutta-percha are removed and plagger compacts gutta-percha till 4mm level from the top of cavity that seales hermetically all ways of bacteria's spreading.</p>
<p>Earlier, it was difficult to fill the system of root canal in 3-D dimension. Nowadays this reliable method fully justifies all estimated expectancies. Apart from gutta-percha it is used recently developed materials such as (epiphany, rezilony, proroot MTA) that gives more opportunities to save the teeth. </p>
<h2>Methods of apparatus diagnostics.</h2>
<p>For the statement of exact diagnosis and confirmation of treatment quality it is used  radiologic research with modern device. 
Dental installation are equipped with interoral cameras Vista Cam of leading German manufacturer Durr Dental.</p>
<p>Camera iteratively increased the image and shows it on flat screen. Dentist has an opportunity to examine the smallest details and demonstrate the elements of dental deposit to the patient, hidden carious cavity, stages and results of restoration. With the help of inter oral camera it is possible to get teeth photograph before and after dental procedures.</p>
  <hr />  
</div>

     <h3>Dentistry Miradent (Ukraine, Donetsk) : Contacts</h3>
<p>Donetsk city, Mira broad street, 2, Dentistry «Miradent», t. +38 062-381-18-24, m. +38 050-696-47-70.</p>
<p>Operating schedule: m-f from 8 to 18, sat. from 8-16, sun. - day off.</p>
<p>Donetsk city, Razdolnaya street, 13, DC «Blic» t. +38 062- 389-33-04, m. +38 050-057-43-78.</p>
<p>Operating schedule: m-f from 9 to 20, sat. from 9-18, sun. - day off.</p>
	
    <div id="div_st4">

						<script src="http://api-maps.yandex.ru/1.1/index.xml?key=AAmDzUsBAAAARkVWCAIAXzMCgKN58_MQUqB134Sdp-unCH0AAAAAAAAAAACbJlz2mcKc4anRgbxx6LBZ5BHPyg==" type="text/javascript"></script>

						<script type="text/javascript">

						window.onload = function () {

							var map = new YMaps.Map(document.getElementById("YMapsID"));

							map.setCenter(new YMaps.GeoPoint(37.796288,48.017299), 16);



							var content = document.createElement('span');

							content.innerHTML = "Dentistry «Miradent»";

							map.openBalloon(new YMaps.GeoPoint(37.796288,48.017299), content);



							map.addControl(new YMaps.ToolBar());

							map.addControl(new YMaps.Zoom());

							map.addControl(new YMaps.MiniMap());

							map.addControl(new YMaps.ScaleLine());

						}

    </script>





	 <div id="YMapsID" style="width:60%; height:300px; position:relative; float:centr; top:20px; left: 140px; z-index:20; margin-bottom:40px;"></div>

   </div>
</div>
    </td>
  </tr>
</table>

















</div>


</div> <!-- cat_ite_cont_m -->

<?php

   } 

?>







<div id="catalogue_item_menu">

<div class="catalogue_item_mp_a">

<a href="index.php?section_id=32&amp;business=1">Категория:</a></div>

</div>

<div class="catalogue_item_cont">

<a href="index.php?section_id=2&amp;business=1">бизнес</a>

 / 

<a href="index.php?section_id=32&amp;business=1">предприятия</a>

 / 

<a href="index.php?section_id=387&amp;business=2">отдых</a>

 / 

<a href="index.php?section_id=512&amp;business=2">кафе и рестораны</a>

</div>





<div id="catalogue_item_menu">

<div class="catalogue_item_mp_a">

<a href="">Фотогалерея:</a></div>

</div>

<div class="catalogue_item_cont">

</div>

<div id="catalogue_item_menu">

<div class="catalogue_item_mp_a">

<a href="">Контактная информация:</div>

</div>

 <div class="catalogue_item_cont">

 		 <table width="100%">

			<tbody>

 			<tr>

			<!--	<td><img class="main_sec_image" src="" width="60" height="60" border="0" alt="" /></td>-->

				<td>Адрес:</td>

				<td>Телефон:</td>

				<td>Факс:</td>

				<td>E-mail:</td>

				<td>Веб-сайт:</td>

			</tr>

			<tr>

				<td>пр. Гурова 20<br /></td>

				<td>тел. (062) 335-16-39</td>

				<td></td>

				<td></td>

				<td></td>



			</tr>

			</tbody> 

		 </table> 		

  </div>

</div>  





