<div class="catalogue_item_c">
<style>

<!--
.folding{cursor:hand;font-weight:bold}
-->

#acc {
list-style: none;
}

#acc .acc-section {
background: white;
margin: 0px;
overflow: hidden;
}

element.style {
height: 0px;
}

.catalogue_item_cont p {
color:#000000;
text-align:justify;
text-indent:0px;
line-height:20px;
margin:0px;
}

.catalogue_item_cont_m {
background-color:#FFFFFF;
border:1px solid lightgray;
color:#000000;
margin:0;
margin:15px 10px 10px;
width:980px;
}

.catalogue_item_cont {
background-color:#ffffff;
border-top:1px solid lightgray;
margin:0 0 7px 10px;
width:980px;
color:#000000;
}
.catalogue_item_c {
background-color:#F3F3F3;
}

.catalogue_item_cont a {
color:#000000;
}

.catalogue_item_cont a:hover {
color:#000000;
text-decoration:underline;
}

.catalogue_item_mp_a {
left:3px;
position:relative;
}

#mm_menu {position:relative;left:610px;width:225px;text-align:center;} 

#div_st {padding:0 0px;position:relative;height:1313px;}

@media all and (-webkit-min-device-pixel-ratio:10000),
not all and (-webkit-min-device-pixel-ratio:0) {
 #div_st {height:1120px;}
}

#div_st2 {padding:0 0px;position:relative;height:1313px;}

@media all and (-webkit-min-device-pixel-ratio:10000),
not all and (-webkit-min-device-pixel-ratio:0) {
 #div_st2 {height:1100px;}
}

#div_st3 {padding:0 0px;position:relative;height:1313px;}

@media all and (-webkit-min-device-pixel-ratio:10000),
not all and (-webkit-min-device-pixel-ratio:0) {
 #div_st3 {height:1150px;}
}

/*
td#i_up {font-weight:bold;text-align:center;}
td#i_up1 {font-weight:bold;text-decoration:underline;}
td#i_first {width:510px;text-align:center;font-size:16px;}
td#i_second {width:75px;font-size:14px;}
td#i_third {width:50px;font-size:14px;}
table#i_table tr {height:35px;}
*/

div{
	display:block;
	font-family:Arial, Helvetica, sans-serif;
	font:Arial, Helvetica, sans-serif;
}

.sequ_container {
	background:#ffefec;
	width:980px;
	height:100%;
	margin:0px;
	padding:0px;
	margin-left:0px;
	text-align:justify;
}

.sequ_left {
	position:relative;
	float:left;
	width:95%;
	font-size:16px;
	padding:15px;
}

.sequ_right {
	position:relative;
	float:left;
	width:10%;
	padding:20px;
	bottom:20px;
}

.reds {
	color:red;
}

p#p_j {
	text-align:justify;
}

p#p_low {
	text-align:justify;
	text-transform:lowercase;
}

.sequ_acc-mid {
	position:relative;
	float:left;
	width:96%;
	font-size:16px;
	padding:15px;
}

.sequ_con_mid {
	position:relative;
	float:left;
	width:96%;
	font-size:24px;
	padding:15px;
}

A.acc {
	background: url('../root/msite/apteka/acc.png');
	background-repeat:no-repeat; 
	display: block;
	/* width: 104px; height: 46px; */
	width: 52px; 
	height: 23px; 
}

A.acc:hover {
 background: url('../root/msite/apteka/acc_h.png');
 background-repeat:no-repeat;  
}

A.contact {
	background: url('../root/msite/apteka/contact.png');
	background-repeat:no-repeat; 
	display: block; 
	/* width: 80px; height: 80px; */
	width: 40px;
	height: 40px;
}

A.contact:hover {
 background: url('../root/msite/apteka/contact_h.png');
 background-repeat:no-repeat;  
}

A.dis {
	background: url('../root/msite/apteka/dis.png');
	background-repeat:no-repeat; 
	display: block; 
	/* width: 80px; height: 78px; */
	width: 40px; height: 39px;
}

A.dis:hover {
 background: url('../root/msite/apteka/dis_h.png');
 background-repeat:no-repeat;  
}

</style>
<?php
if ($_GET['pm'] == 1) 
{
?>
<div class="catalogue_item_cont_m"> 
	<div id="div_st">
		<div class="sequ_container">
			<div style="background: url(../root/msite/apteka/images/bg.jpg); width: 980px; height: 1313px;">

            <div style="position: absolute; margin-left: 40px; margin-top: 26px;"><img src="../root/msite/apteka/images/logo.png" /></div>
            <div style="position: absolute; margin-left: 650px; margin-top: 26px;"><img src="../root/msite/apteka/images/contact.png" /></div>
            
            
            <div style="position: absolute; margin-top: 115px; margin-left: 650px;"><a href="index.php?business_full=510&pm=1"><img src="../root/msite/apteka/images/onas.png" /></a></div>
            <div style="position: absolute; margin-top: 115px; margin-left: 746px;"><a href="index.php?business_full=510&pm=2"><img src="../root/msite/apteka/images/contacts.png" /></a></div>
            <div style="position: absolute; margin-top: 115px; margin-left: 877px;"><a href="index.php?business_full=510&pm=3"><img src="../root/msite/apteka/images/discont.png" /></a></div>
            
            
            <div style="position: absolute; margin-left: 20px; margin-top: 155px;"><img src="../root/msite/apteka/images/line.png" /></div>
            
            
            
            <div style="position: absolute; margin-left: 42px; margin-top: 172px; z-index: 10;"><img src="../root/msite/apteka/images/lb.png" /></div>
            <div style="position: absolute; margin-left: 53px; margin-top: 183px; width: 605px; height: 385px; z-index: 20;"><img src="../root/msite/apteka/images/tabletki.png" /></div>
            <div style="position: absolute; margin-left: 188px; margin-top: 480px; z-index: 30;"><img src="../root/msite/apteka/images/ttabl.png" /></div>
            
            
            
            <div style="position: absolute; margin-left: 680px; margin-top: 172px;"><img src="../root/msite/apteka/images/rb.png" /></div>
            <div style="position: absolute; margin-left: 689px; margin-top: 180px; width: 263px; height: 362px; z-index: 40;"><img src="../root/msite/apteka/images/map.png" /></div>
            
            
            <div style="position: absolute; margin-left: 20px; margin-top: 570px;"><img src="../root/msite/apteka/images/line.png" /></div>
            
            
            
            <div style="position: absolute; margin-left: 60px; margin-top: 600px; width: 780px; height: 420px;"><table border=0 style="width: 100%;"><tr><td>
            <p style="color: red; margin-left: 50px; font-size: 18pt;"><b>Аптека "Центральная" - ЭКСКЛЮЗИВНЫЙ АССОРТИМЕНТ.</b></p>
            <br />
            <p style="margin-left: 50px; font-size: 13pt;">Широкий ассортимент лекарственных препаратов и изделий медицинского назначения:</p>
            <br />
            <p style="font-size: 13pt;">- биологически-активных добавок;</p>
            <br />
            <p style="font-size: 13pt;">- лечебной косметики;</p>
            <br />
            <p style="font-size: 13pt;">- товары для детей;</p>
            <br />
            <p style="font-size: 13pt;">- предметов для санитарии и гигиены.</p>
            <br />
            <p style="font-size: 13pt; text-indent: 50px;">В аптеке "Центральная" Вы найдете все зарегистрированные в Украине лекарственные препараты, имеющиеся в наличии на фармацевтическом рынке.</p>
            <p style="font-size: 13pt; text-indent: 50px;">В ассортименте аптеки - свыше 15 000 наименований лекарственных средств, лечебной косметики, БАДов, изделий медицинского назначения и товаров для детей.</p>
            <br />
            <p style="font-size: 13pt; text-indent: 50px;">Аптека "Центральная" привозит уникальные или редко назначаемые препараты под заказ в короткий срок.</p>
            <br />
            <p style="font-size: 13pt; text-indent: 50px;">Вы ысегда сможете получить профессиональную консультацию провизоров аптеки</p>
            <br />
            <p style="font-size: 13pt; text-indent: 50px;">Аптека "Центральная" работает круглосуточно!</p>
            </td></tr></table></div>
            
            
            <div style="position: absolute; margin-top: 1214px; z-index: 60;"><img src="../root/msite/apteka/images/footer.png" /></div>
            <div style="position: absolute; margin-top: 1000px; margin-left: 692px; z-index: 70;"><img src="../root/msite/apteka/images/krest.png" /></div>

            </div>
		</div> <!-- sequ_container -->
	</div>  <!-- div_st -->
</div> <!-- cat_ite_cont_m -->
<?php
}
else
   if ($_GET['pm'] == 2)
   {
?>
<div class="catalogue_item_cont_m"> 
	<div id="div_st2">
		<div class="sequ_container">
			<div style="background: url(../root/msite/apteka/images/bg.jpg); width: 980px; height: 1313px; margin: 0 auto; top: 0;">

<div style="position: absolute; margin-left: 40px; margin-top: 26px;"><img src="../root/msite/apteka/images/logo.png" /></div>
<div style="position: absolute; margin-left: 650px; margin-top: 26px;"><img src="../root/msite/apteka/images/contact.png" /></div>


<div style="position: absolute; margin-top: 115px; margin-left: 650px;"><a href="index.php?business_full=510&pm=1"><img src="../root/msite/apteka/images/onas.png" /></a></div>
<div style="position: absolute; margin-top: 115px; margin-left: 746px;"><a href="index.php?business_full=510&pm=2"><img src="../root/msite/apteka/images/contacts.png" /></a></div>
<div style="position: absolute; margin-top: 115px; margin-left: 877px;"><a href="index.php?business_full=510&pm=3"><img src="../root/msite/apteka/images/discont.png" /></a></div>


<div style="position: absolute; margin-left: 20px; margin-top: 155px;"><img src="../root/msite/apteka/images/line.png" /></div>



<div style="position: absolute; margin-left: 100px; margin-top: 172px; z-index: 10;">
<p style="font-size: 14pt;">Справочные телефоны:<br /></p>
<p style="font-size: 14pt;">(062) 381-05-15;</p>
<p style="font-size: 14pt;">(062) 304-42-67;</p>
<p style="font-size: 14pt;">(062) 345-2-345</p>
<br /><br />
<p style="font-size: 14pt;"><b>Режим работы</b> - <b style="color: red;">круглосуточно</b></p>
<br />
<p>Аптека центральная</p>
<p>г. Донецк, 83001</p>
<p>пл. Ленина, ул. Постышева, 129</p>
</div>




<div style="position: absolute; margin-left: 530px; margin-top: 172px;">
<p style="font-size: 14pt;">А так же дополнительные <br /> мобильные телефоны для отделов:</p>
<p style="font-size: 14pt;">- отдел лекарственных средств:</p>
<p style="font-size: 14pt;">066-979-68-55</p>
<p style="font-size: 14pt;">- отдел косметики, БАДов, товаров для детей:</p>
<p style="font-size: 14pt;">066-638-34-03</p>
<p style="font-size: 14pt;">- отдел медицинских изделий:</p>
<p style="font-size: 14pt;">с 8-00 до 21-00 ч.</p>
<p style="font-size: 14pt;">без перерыва и выходных</p>
<p style="font-size: 14pt;">062 305-07-13; 095-822-62-32</p>
</div>


<div style="position: absolute; margin-left: 20px; margin-top: 430px;"><img src="../root/msite/apteka/images/line.png" /></div>



<div style="position: absolute; margin-left: 60px; margin-top: 500px; width: 780px; height: 420px;"><table border=0 style="width: 100%;"><tr><td>
<div>
				<script src="http://api-maps.yandex.ru/1.1/index.xml?key=AAmDzUsBAAAARkVWCAIAXzMCgKN58_MQUqB134Sdp-unCH0AAAAAAAAAAACbJlz2mcKc4anRgbxx6LBZ5BHPyg==" type="text/javascript"></script>
			<script type="text/javascript">
				window.onload = function () {
					var map = new YMaps.Map(document.getElementById("YMapsID"));
					map.setCenter(new YMaps.GeoPoint(37.80612,48.003484), 16);

					var content = document.createElement('span');
					content.innerHTML = "Аптека «Центральная»";
					map.openBalloon(new YMaps.GeoPoint(37.806249,48.00357), content);
		
					map.addControl(new YMaps.ToolBar());
					map.addControl(new YMaps.Zoom());
					map.addControl(new YMaps.MiniMap());
					map.addControl(new YMaps.ScaleLine());
				}
			</script>
		
		
			 <div id="YMapsID" style="width:90%; height:450px; position:relative; float:left; top:20px; left:40px; z-index:20; margin-bottom:40px;"></div>
			</div>
</td></tr></table></div>


<div style="position: absolute; margin-top: 1214px; z-index: 70;"><img src="../root/msite/apteka/images/footer.png" /></div>
<div style="position: absolute; margin-top: 1000px; margin-left: 692px; z-index: 80;"><img src="../root/msite/apteka/images/krest.png" /></div>

</div>
		</div> <!-- sequ_container -->
	</div>  <!-- div_st -->
</div> <!-- cat_ite_cont_m --><?php
}
else
   if ($_GET['pm'] == 3)
   {
?>
<div class="catalogue_item_cont_m"> 
	<div id="div_st3">
		<div class="sequ_container">
			<div style="background: url(../root/msite/apteka/images/bg.jpg); width: 980px; height: 1313px; margin: 0 auto; top: 0;">

<div style="position: absolute; margin-left: 40px; margin-top: 26px;"><img src="../root/msite/apteka/images/logo.png" /></div>
<div style="position: absolute; margin-left: 650px; margin-top: 26px;"><img src="../root/msite/apteka/images/contact.png" /></div>


<div style="position: absolute; margin-top: 115px; margin-left: 650px;"><a href="index.php?business_full=510&pm=1"><img src="../root/msite/apteka/images/onas.png" /></a></div>
<div style="position: absolute; margin-top: 115px; margin-left: 746px;"><a href="index.php?business_full=510&pm=2"><img src="../root/msite/apteka/images/contacts.png" /></a></div>
<div style="position: absolute; margin-top: 115px; margin-left: 877px;"><a href="index.php?business_full=510&pm=3"><img src="../root/msite/apteka/images/discont.png" /></a></div>


<div style="position: absolute; margin-left: 20px; margin-top: 155px;"><img src="../root/msite/apteka/images/line.png" /></div>



<div style="position: absolute; margin-left: 42px; margin-top: 172px; z-index: 10;"><img src="../root/msite/apteka/images/lb.png" /></div>
<div style="position: absolute; margin-left: 53px; margin-top: 183px; width: 605px; height: 385px; z-index: 20;"><img src="../root/msite/apteka/images/logo1.png" /></div>




<div style="position: absolute; margin-left: 680px; margin-top: 172px;"><img src="../root/msite/apteka/images/rb.png" /></div>
<div style="position: absolute; margin-left: 689px; margin-top: 180px; width: 263px; height: 362px; z-index: 40;"><img src="../root/msite/apteka/images/map.png" /></div>


<div style="position: absolute; margin-left: 20px; margin-top: 570px;"><img src="../root/msite/apteka/images/line.png" /></div>



<div style="position: absolute; margin-left: 60px; margin-top: 600px; width: 780px; height: 420px;"><table border=0 style="width: 100%;"><tr><td>
<p style="font-size: 18pt;"><b>Условия получения дисконтной карты аптеки</b> <b style="color: red;">"Центральная"</b></p>
<br />
<p style=" text-indent: 35px;;font-size: 13pt;">Для получения дисконтной карты покупателю необходимо сделать покупку или несколько покупок (подтвержденных чеками) в течении суток на сумму от 1000 грн, 1500 грн, в аптеке "Центральная".</p>
<br />
<p style="font-size: 13pt;">Размер скидки определяется суммой покупки:</p>
<br />
<div style="font-size: 20pt; z-index: 50; position: absolute; margin-top: 60px; margin-left: 330px;">1000 грн</div>
<div style="font-size: 20pt; z-index: 50; position: absolute; margin-top: 230px; margin-left: 470px;">1500 грн</div>
<div><img src="../root/msite/apteka/images/card.png" /></div>
</td></tr></table></div>


<div style="position: absolute; margin-top: 1214px; z-index: 70;"><img src="../root/msite/apteka/images/footer.png" /></div>
<div style="position: absolute; margin-top: 1000px; margin-left: 692px; z-index: 80;"><img src="../root/msite/apteka/images/krest.png" /></div>

</div>
		</div> <!-- sequ_container -->
	</div>  <!-- div_st -->
</div> <!-- cat_ite_cont_m -->
<?php
   } 
?>



<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="index.php?section_id=32&amp;business=1">Категория:</a></div>
</div>
<div class="catalogue_item_cont">
<a href="index.php?section_id=2&amp;business=1">бизнес</a>
 / 
<a href="index.php?section_id=32&amp;business=1">предприятия</a>
 / 
<a href="index.php?section_id=387&amp;business=2">медицина</a>
 / 
<a href="index.php?section_id=513">аптеки</a>
</div>


<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="">Фотогалерея:</a></div>
</div>
<div class="catalogue_item_cont">
</div>
<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="">Контактная информация:</div>
</div>
 <div class="catalogue_item_cont">
 		 <table width="100%">
			<tbody>
 			<tr>
			<!--	<td><img class="main_sec_image" src="" width="60" height="60" border="0" alt="" /></td>-->
				<td>Адрес:</td>
				<td>Телефон:</td>
				<td>Факс:</td>
				<td>E-mail:</td>
				<td>Веб-сайт:</td>
			</tr>
			<tr>
				<td>г. Донецк,  83001<br />
				пл. Ленина, <br />
				ул. Постышева, 129</td>
				<td>062-385-05-15.<br />
				066-979-68-55<br />
				345-2-345</td>
				<td></td>
				<td></td>
				<td></td>

			</tr>
			</tbody> 
		 </table> 		
	 </div>
</div>  


