<div class="catalogue_item_c">
<style>

<!-- .folding{cursor:hand;font-weight:bold} -->

#acc {
list-style: none;
}

#acc .acc-section {
background: white;
margin: 0px;
overflow: hidden;
}

element.style {
height: 0px;
}

.catalogue_item_cont p {
color:#000000;
text-align:justify;
text-indent:0px;
line-height:20px;
margin:0px;
}

.catalogue_item_cont_m {
background-color:#FFFFFF;
border:1px solid lightgray;
color:#000000;
margin:0;
margin:15px 10px 10px;
width:980px;
}

.catalogue_item_cont {
background-color:#ffffff;
border-top:1px solid lightgray;
margin:0 0 7px 10px;
width:980px;
color:#000000;
}
.catalogue_item_c {
background-color:#F3F3F3;
}

.catalogue_item_cont a {
color:#000000;
}

.catalogue_item_cont a:hover {
color:#000000;
text-decoration:underline;
}

.catalogue_item_mp_a {
left:3px;
position:relative;
}

#div_st, #div_st2, #div_st3, #div_st4, #div_st5, #div_st6, #div_st7 {
  padding:0;
  position:relative;
  background:url('../root/msite/endohealth/fon.png');
}
#div_st {height:900px;}
#div_st2 {height:740px;}
#div_st3 {height:2400px;}
#div_st4 {height:1110px;}
#div_st5 {height:4400px;}
#div_st6 {height:1450px;}
#div_st7 {height:1850px;}

div{
	display:block;
	font-family:Arial, Helvetica, sans-serif;
	font:Arial, Helvetica, sans-serif;
}

.sequ_container {
	width:800px;
	height:100%;
	margin:0px;
	padding:0px;
	margin-left:90px;
	text-align:justify;
}

#header {
  float:left;
  position:relative;
  width:100%;
  height:38px;
  padding-top:10px;
}
#header .phone {
  color:#6e7e6e;
  text-align:center;
  font-size:18px;
  font-style:italic;
  font-weight:bold;
  vertical-align:middle;
}
#header #menu {
  background:url('../root/msite/endohealth/menu.png') no-repeat left top;
  width:100%;
  height:40px;
  margin:10px auto 20px;
}
#header #menu .menu_button {
  color:#6e7e6e;
  text-decoration:none;
  font-size:18px;
  font-style:italic;
  font-weight:bold;  
}
#header #menu .menu_button:hover {
  text-decoration:underline;
}
#content {
  float:left;
  position:relative;
  width:100%;
  margin-top: 55px;
}
#content #banner {
  background-color:#056bb3;
  width:760px;
  height:200px;
  padding:0 20px;
  margin:20px 0;
}
#content #banner img {
  float:left;
  margin:0 30px 0px 50px;
}
#content #banner p {
  color:#ffffff;
  text-transform:uppercase;
  text-align:center;
  font-style:italic;
}
#content #banner .calling {
  background:url('../root/msite/endohealth/calling.png') no-repeat left top;
  float:right;
  width:100px;
  height:30px;
  padding-top:5px;
  margin:10px 25px 0 0;
  color:#6e7e6e;
  font-size:14px;
  text-transform:uppercase;
  text-align:center;
  font-style:italic;
}
#content #banner .calling:hover {
  text-decoration:underline;
}
#content #menu_about {
  width:800px;
  height:200px;
}
#content #menu_about .button_1 {
  background:url('../root/msite/endohealth/button_1.png') no-repeat left top;
  float:left;
  width:265px;
  height:200px;
}
#content #menu_about .button_2 {
  background:url('../root/msite/endohealth/button_2.png') no-repeat left top;
  float:left;
  width:265px;
  height:200px;
}
#content #menu_about .button_3 {
  background:url('../root/msite/endohealth/button_3.png') no-repeat left top;
  float:left;
  width:265px;
  height:200px;
}

#content #menu_about .button_1 .button_title,
#content #menu_about .button_2 .button_title,
#content #menu_about .button_3 .button_title {
  margin:15px 0 0 5px;
  width:100px;
  font-size:14px;
  text-transform:uppercase;
  font-style:italic;
  font-weight:bold;
}
#content #menu_about .button_1 .button_text,
#content #menu_about .button_2 .button_text,
#content #menu_about .button_3 .button_text {
  margin:10px 0px 0px 5px;
  width:150px;
  font-size:10px;
  text-transform:uppercase;
  font-style:italic;
  text-align:left;
}
#content #menu_about .more {
  background:url('../root/msite/endohealth/more.png') no-repeat left top;
  float:right;
  width:70px;
  height:20px;
  margin:10px 25px 0 0;
  padding-top:2px;
  color:#ffffff;
  font-size:10px;
  text-transform:uppercase;
  text-align:center;
  font-style:italic;
}
#content #page_content {
  width:800px;
  height:100%;
}
#content #page_content #description {
  float:left;
  width:780px;
  height:100%;
  padding:10px;
}
#content #page_content #description p {
  font-size:12px;
}
#content #page_content #description h1 {
  margin: 10px 0 5px 0;
  font-size:14px;
  text-transform:uppercase;
  font-style:italic;
}
#content #page_content #description .price {
  width:500px;
}
#content #page_content #description .price th {
  border: 1px solid #056bb3;
  width:425px;
  padding:5px;
}
#content #page_content #description .price td {
  border: 1px solid #056bb3;
  background-color:#056bb3;
  width:75px;
  padding:5px;
  color:#ffffff;
  text-align:center;
}

#content #page_content .footer_link {
  float:right;
  font-size:12px;
  text-transform:uppercase;  
}
#footer {
  float:left;
  width:100%;
  margin:10px 0;
}
#footer p {
  font-size:12px;
  font-style:italic;
}
.clear {
  clear:both;
  margin:0;
  padding:0;
}
hr {
  width:100%;
  color:#056bb3;
  margin:10px 0;
}
</style>
<?php
if ($_GET['pm'] == 1) 
{
?>
<div class="catalogue_item_cont_m"> 
	<div id="div_st">
		<div class="sequ_container">
			<div id="header">
				<table>
					<tr><td><img src="../root/msite/endohealth/logo.jpg" width="170px" height="38px" alt="EndoHealth" /></td>
						<td style="vertical-align:middle; text-align:center; height:38px; width:800px;">
						<p class="phone">[062] 311-55-97; [095] 900-32-00</p>
						</td>
					</tr>
				</table>
				<div id="menu">
					<table>
						<tr>
							<td width="198" align="center"><a class="menu_button" href="index.php?business_full=650&pm=1">О нас</a></td>
							<td><img src="../root/msite/endohealth/separator.png" width="2px" height="40px" alt="" /></td>
							<td width="200" align="center"><a class="menu_button" href="index.php?business_full=650&pm=2">Виды услуг</a></td>
							<td><img src="../root/msite/endohealth/separator.png" width="2px" height="40px" alt="" /></td>
							<td width="198" align="center"><a class="menu_button" href="index.php?business_full=650&pm=3">Прайс</a></td>
							<td><img src="../root/msite/endohealth/separator.png" width="2px" height="40px" alt="" /></td>
							<td width="198" align="center"><a class="menu_button" href="index.php?business_full=650&pm=4">Контакты</a></td>
						</tr>
					</table>
				</div><!-- #menu -->
			</div><!-- #header -->
			
			<div id="content">		
				<div id="banner">
					<img src="../root/msite/endohealth/banner.jpg" width="200px" height="200px" alt="" />
					<p style="font-size: 28px; padding-top: 15px;">Стоматология</p>
					<p style="font-size: 24px;">Endohealth</p>
					<p style="font-size: 20px;">Легко быть здоровым</p><br />
					<p style="font-size: 14px;">Наши администраторы ответят на ваши вопросы подробно и запишут на прием в удобное для вас время</p>
					<a class="calling" href="index.php?business_full=650&pm=4">Позвонить</a>
				</div><!-- #banner -->
				<br class="clear" />
				<div id="menu_about">
					<div class="button_1">
						<div class="button_title">
							<p style="color:#056bb3;">Терапевтическая стоматология</p>
						</div><!-- .button_title -->
						<div class="button_text">
							<p>Терапевтическая стоматология занимается изучением заболевания околозубных тканей, а также методами их.</p>
						</div><!-- .button_text -->
						<a class="more" href="index.php?business_full=650&pm=5">Подробнее</a>
					</div><!-- .button_1 -->
					<div class="button_2">
						<div class="button_title">
							<p style="color:#edbc29;">Ортопедическая стоматология</p>
						</div><!-- .button_title -->
						<div class="button_text">
							<p>Ортопедическая стоматология - это вид стоматологии, посвященный диагностике и лечению нарушений целосности.</p>
						</div><!-- .button_text -->
						<a class="more" href="index.php?business_full=650&pm=6">Подробнее</a>
					</div><!-- .button_2 -->
					<div class="button_3">
						<div class="button_title">
							<p style="color:#056bb3;">Эстетическая стоматология</p>
						</div><!-- .button_title -->
						<div class="button_text">
							<p>Эстетическая стоматология быстро растет, обретая все большую популярность. Красивая улыбка всегда будет привлекать внимание.</p>
						</div><!-- .button_text -->
						<a class="more" href="index.php?business_full=650&pm=7">Подробнее</a>
					</div><!-- .button_3 -->
				</div><!-- #menu_about -->
				<br class="clear" />			
				<div id="page_content">
					<div id="description">
						<p style="color:#000000;">Сегодня стало модно и престижно уделять внимание своему внешнему виду и здоровью. Здоровые зубы и прекрасная улыбка придают человеку уверенность, поднимают настроение, а также являются визитной карточкой его благополучия.</p>
						<br />
						<p style="color:#056bb3;"><b>Применение новейших материалов и современных технологий в процессе лечения зубов, контроль каждого из этапов лечения позволяют нам предлагать пациенту гарантированное качество.</b></p>
						<br />
						<p>ПОЧЕМУ ВЫБИРАЮТ ИМЕННО СТОМАТОЛОГИЮ "ENDOHEALTH"?</p>
						<p style="color:#056bb3;">-	Стоматология «Endohealth» распо¬ложена в удобном для пациентов месте в центральном районе города Донецка.</p>
						<p style="color:#056bb3;">-	У нас работают опытные специалисты, регулярно проходящие стажировки в лучших учебных центрах.</p>
						<p style="color:#056bb3;">-	Мы предоставляем самую длительную гарантию на все виды стоматологического лечения и протезирования.</p>
						<p style="color:#056bb3;">-	Cтоматология "Endohealth" отличается гибкой ценовой политикой: мы под¬би¬раем Вам лечение исходя из Ваших возможностей, но при этом гарантируем высокое качество обслуживания и лечения.</p>
						<p style="color:#056bb3;">-	Стоматология в кредит! Вы можете получить стоматологические услуги в кредит - без первоначального взноса!!!</p>
					</div><!-- #description -->
				</div><!-- #page_content -->
			</div><!-- #content -->
			<br class="clear" />
			<div id="footer">
				<hr>
				<table>
					<tr>
						<td width="500px" align="left"><p>2010 Endohealth</p></td>
						<td width="300px" align="right"><p>2010 Endohealth лечение зубов</p></td>
					</tr>
				</table>
			</div><!-- #footer -->
		</div> <!-- sequ_container -->
	</div>  <!-- div_st -->
</div> <!-- cat_ite_cont_m -->
<?php
}
else
   if ($_GET['pm'] == 2)
   {
?>
<div class="catalogue_item_cont_m"> 
	<div id="div_st2">
		<div class="sequ_container">
			<div id="header">
				<table>
					<tr><td><img src="../root/msite/endohealth/logo.jpg" width="170px" height="38px" alt="EndoHealth" /></td>
						<td style="vertical-align:middle; text-align:center; height:38px; width:800px;">
						<p class="phone">[062] 311-55-97; [095] 900-32-00</p>
						</td>
					</tr>
				</table>
				<div id="menu">
					<table>
						<tr>
							<td width="198" align="center"><a class="menu_button" href="index.php?business_full=650&pm=1">О нас</a></td>
							<td><img src="../root/msite/endohealth/separator.png" width="2px" height="40px" alt="" /></td>
							<td width="200" align="center"><a class="menu_button" href="index.php?business_full=650&pm=2">Виды услуг</a></td>
							<td><img src="../root/msite/endohealth/separator.png" width="2px" height="40px" alt="" /></td>
							<td width="198" align="center"><a class="menu_button" href="index.php?business_full=650&pm=3">Прайс</a></td>
							<td><img src="../root/msite/endohealth/separator.png" width="2px" height="40px" alt="" /></td>
							<td width="198" align="center"><a class="menu_button" href="index.php?business_full=650&pm=4">Контакты</a></td>
						</tr>
					</table>
				</div><!-- #menu -->
			</div><!-- #header -->
			
			<div id="content">		
				<div id="banner">
					<img src="../root/msite/endohealth/banner.jpg" width="200px" height="200px" alt="" />
					<p style="font-size: 28px; padding-top: 15px;">Стоматология</p>
					<p style="font-size: 24px;">Endohealth</p>
					<p style="font-size: 20px;">Легко быть здоровым</p><br />
					<p style="font-size: 14px;">Наши администраторы ответят на ваши вопросы подробно и запишут на прием в удобное для вас время</p>
					<a class="calling" href="index.php?business_full=650&pm=4">Позвонить</a>
				</div><!-- #banner -->
				<br class="clear" />
				<div id="menu_about">
					<div class="button_1">
						<div class="button_title">
							<p style="color:#056bb3;">Терапевтическая стоматология</p>
						</div><!-- .button_title -->
						<div class="button_text">
							<p>Терапевтическая стоматология занимается изучением заболевания околозубных тканей, а также методами их.</p>
						</div><!-- .button_text -->
						<a class="more" href="index.php?business_full=650&pm=5">Подробнее</a>
					</div><!-- .button_1 -->
					<div class="button_2">
						<div class="button_title">
							<p style="color:#edbc29;">Ортопедическая стоматология</p>
						</div><!-- .button_title -->
						<div class="button_text">
							<p>Ортопедическая стоматология - это вид стоматологии, посвященный диагностике и лечению нарушений целосности.</p>
						</div><!-- .button_text -->
						<a class="more" href="index.php?business_full=650&pm=6">Подробнее</a>
					</div><!-- .button_2 -->
					<div class="button_3">
						<div class="button_title">
							<p style="color:#056bb3;">Эстетическая стоматология</p>
						</div><!-- .button_title -->
						<div class="button_text">
							<p>Эстетическая стоматология быстро растет, обретая все большую популярность. Красивая улыбка всегда будет привлекать внимание.</p>
						</div><!-- .button_text -->
						<a class="more" href="index.php?business_full=650&pm=7">Подробнее</a>
					</div><!-- .button_3 -->
				</div><!-- #menu_about -->
				<br class="clear" />			
				<div id="page_content">
					<div id="description">
						<p><a href="index.php?business_full=650&pm=5">Терапевтическая стоматология</a></p>
						<p><a href="index.php?business_full=650&pm=6">Ортопедическая стоматология</a></p>
						<p><a href="index.php?business_full=650&pm=7">Эстетическая стоматология</a></p>
					</div><!-- #description -->
				</div><!-- #page_content -->
			</div><!-- #content -->
			<br class="clear" />
			<div id="footer">
				<hr>
				<table>
					<tr>
						<td width="500px" align="left"><p>2010 Endohealth</p></td>
						<td width="300px" align="right"><p>2010 Endohealth лечение зубов</p></td>
					</tr>
				</table>
			</div><!-- #footer -->
		</div> <!-- sequ_container -->
	</div>  <!-- div_st -->
</div> <!-- cat_ite_cont_m -->
<?php
}
else
   if ($_GET['pm'] == 3)
   {
?>
<div class="catalogue_item_cont_m"> 
	<div id="div_st3">
		<div class="sequ_container">
			<div id="header">
				<table>
					<tr><td><img src="../root/msite/endohealth/logo.jpg" width="170px" height="38px" alt="EndoHealth" /></td>
						<td style="vertical-align:middle; text-align:center; height:38px; width:800px;">
						<p class="phone">[062] 311-55-97; [095] 900-32-00</p>
						</td>
					</tr>
				</table>
				<div id="menu">
					<table>
						<tr>
							<td width="198" align="center"><a class="menu_button" href="index.php?business_full=650&pm=1">О нас</a></td>
							<td><img src="../root/msite/endohealth/separator.png" width="2px" height="40px" alt="" /></td>
							<td width="200" align="center"><a class="menu_button" href="index.php?business_full=650&pm=2">Виды услуг</a></td>
							<td><img src="../root/msite/endohealth/separator.png" width="2px" height="40px" alt="" /></td>
							<td width="198" align="center"><a class="menu_button" href="index.php?business_full=650&pm=3">Прайс</a></td>
							<td><img src="../root/msite/endohealth/separator.png" width="2px" height="40px" alt="" /></td>
							<td width="198" align="center"><a class="menu_button" href="index.php?business_full=650&pm=4">Контакты</a></td>
						</tr>
					</table>
				</div><!-- #menu -->
			</div><!-- #header -->
			
			<div id="content">		
				<div id="banner">
					<img src="../root/msite/endohealth/banner.jpg" width="200px" height="200px" alt="" />
					<p style="font-size: 28px; padding-top: 15px;">Стоматология</p>
					<p style="font-size: 24px;">Endohealth</p>
					<p style="font-size: 20px;">Легко быть здоровым</p><br />
					<p style="font-size: 14px;">Наши администраторы ответят на ваши вопросы подробно и запишут на прием в удобное для вас время</p>
					<a class="calling" href="index.php?business_full=650&pm=4">Позвонить</a>
				</div><!-- #banner -->
				<br class="clear" />
				<div id="menu_about">
					<div class="button_1">
						<div class="button_title">
							<p style="color:#056bb3;">Терапевтическая стоматология</p>
						</div><!-- .button_title -->
						<div class="button_text">
							<p>Терапевтическая стоматология занимается изучением заболевания околозубных тканей, а также методами их.</p>
						</div><!-- .button_text -->
						<a class="more" href="index.php?business_full=650&pm=5">Подробнее</a>
					</div><!-- .button_1 -->
					<div class="button_2">
						<div class="button_title">
							<p style="color:#edbc29;">Ортопедическая стоматология</p>
						</div><!-- .button_title -->
						<div class="button_text">
							<p>Ортопедическая стоматология - это вид стоматологии, посвященный диагностике и лечению нарушений целосности.</p>
						</div><!-- .button_text -->
						<a class="more" href="index.php?business_full=650&pm=6">Подробнее</a>
					</div><!-- .button_2 -->
					<div class="button_3">
						<div class="button_title">
							<p style="color:#056bb3;">Эстетическая стоматология</p>
						</div><!-- .button_title -->
						<div class="button_text">
							<p>Эстетическая стоматология быстро растет, обретая все большую популярность. Красивая улыбка всегда будет привлекать внимание.</p>
						</div><!-- .button_text -->
						<a class="more" href="index.php?business_full=650&pm=7">Подробнее</a>
					</div><!-- .button_3 -->
				</div><!-- #menu_about -->
				<br class="clear" />			
				<div id="page_content">
					<div id="description">
						<h1>• Первичный осмотр, манипуляции</h1>
						<table class="price">
						<tr>
							<th>Первичный осмотр пациента</th>
							<td>БЕСПЛАТНО</td>
						</tr>
						<tr>
							<th>Осмотр, консультация с выдачей справки о состоянии полости рта или с составлением плана лечения</th>
							<td>15 грн</td>
						</tr>
						<tr>
							<th>Анестезия инфильтрационная</th>
							<td>20 грн</td>
						</tr>
						<tr>
							<th>Анестезия проводниковая</th>
							<td>25 грн</td>
						</tr>
						<tr>
							<th>Анестезия интралигаментарная</th>
							<td>20 грн</td>
						</tr>						
						<tr>
							<th>Временная пломба химичекского отверждения</th>
							<td>30 грн</td>
						</tr>
						<tr>
							<th>Наложение коффердама</th>
							<td>65 грн</td>
						</tr>
						<tr>
							<th>Рентгенологический снимок</th>
							<td>20 грн</td>
						</tr>
						</table>
						<h1>• Профилактическая стоматология</h1>
						<table class="price">
						<tr>
							<th>Глубокое фторирование зубов (две челюсти) - 3 посещения</th>
							<td>320 грн</td>
						</tr>
						<tr>
							<th>Эмаль-герметизирующий ликвид ( за 1 зуб)</th>
							<td>30 грн</td>
						</tr>
						<tr>
							<th>Герметизация фиссур</th>
							<td>70 грн</td>
						</tr>
						<tr>
							<th>Снятие зубных отложений УЗ-скалером (за одну челюсть), от уровня сложности</th>
							<td>80-100-120 грн</td>
						</tr>
						<tr>
							<th>Аппаратное отбеливание в одно посещение!</th>
							<td>1400 грн</td>
						</tr>
						</table>
						<h1>• Лечение кариеса и некариозных поражений зубов</h1>
						<table class="price">
						<tr>
							<th>Терапевтический винир</th>
							<td>450 грн</td>
						</tr>
						<tr>
							<th>Пломба гелиокомпозитом - 1 поверхность</th>
							<td>100 грн</td>
						</tr>
						<tr>
							<th>Пломба гелиокомпозитом - 2 поверхности</th>
							<td>140 грн</td>
						</tr>
						<tr>
							<th>Художественная реставрация зуба</th>
							<td>350 грн</td>
						</tr>
						<tr>
							<th>Реконструкция зуба материалом GRADIA</th>
							<td>200-260-300 грн</td>
						</tr>						
						<tr>
							<th>Реконструкция зуба материалом Filtek Supreme</th>
							<td>200-260-300 грн</td>
						</tr>
						<tr>
							<th>Восстановление коронковой части зуба с целью протезирования</th>
							<td>150 грн</td>
						</tr>
						<tr>
							<th>Анкерный штифт</th>
							<td>50 грн</td>
						</tr>
						<tr>
							<th>Штифт стекловолоконный</th>
							<td>100 грн</td>
						</tr>
						<tr>
							<th>Прокладка изолирующая</th>
							<td>30 грн</td>
						</tr>
						<tr>
							<th>Прокладка лечебная</th>
							<td>30 грн</td>
						</tr>
						<tr>
							<th>Пломба Vitremer (стеклоиномерный цемент)</th>
							<td>180-200-260 грн</td>
						</tr>
						<tr>
							<th>Пломба Ketac Molar (стеклоиномерный цемент)</th>
							<td>100-130-150 грн</td>
						</tr>
						<tr>
							<th>Пломба Charisma (химический композит)</th>
							<td>100 грн</td>
						</tr>
						<tr>
							<th>Пломба Evicrol (химический композит)</th>
							<td>100 грн</td>
						</tr>
						<tr>
							<th>Пломба Latelux (фотополимер)</th>
							<td>120-150-180 грн</td>
						</tr>						
						<tr>
							<th>Пломба Charisma (фотополимер)</th>
							<td>120-150-180 грн</td>
						</tr>
						<tr>
							<th>Пломба Dyract (фотополимер)</th>
							<td>150 грн</td>
						</tr>
						<tr>
							<th>Пломба Grandia (фотополимер)</th>
							<td>200-260-300 грн</td>
						</tr>
						<tr>
							<th>Пломба Filtek Suprime (фотополимер)</th>
							<td>200-260-300 грн</td>
						</tr>
						<tr>
							<th>Premise (Kerr)</th>
							<td>200-250-300 грн</td>
						</tr>
						<tr>
							<th>Ортопедический винир</th>
							<td>2200 грн</td>
						</tr>
						</table>
						<h1>• Реставрация зуба с помощью коронок</h1>
						<table class="price">
						<tr>
							<th>коронка цельнолитая (КХС)</th>
							<td>200 грн</td>
						</tr>
						<tr>
							<th>коронка цельнокерамическая</th>
							<td>750 грн</td>
						</tr>
						<tr>
							<th>коронка металлокерамическая на имплант</th>
							<td>750 грн</td>
						</tr>
						<tr>
							<th>коронка металлокерамическая (боковой участок)</th>
							<td>600 грн</td>
						</tr>
						<tr>
							<th>коронка металлокерамическая (фронтальный участок)</th>
							<td>600 грн</td>
						</tr>
						<tr>
							<th>керамическая коронка на циркониевом каркасе</th>
							<td>2000 грн</td>
						</tr>
						<tr>
							<th>коронка булатная</th>
							<td>200 грн</td>
						</tr>
						</table>
						<h1>• Пародонтологические услуги</h1>
						<table class="price">
						<tr>
							<th>Лечебная повязка</th>
							<td>30 грн</td>
						</tr>
						<tr>
							<th>ТРАУМЕЛЬ с наложением аппликации</th>
							<td>30 грн</td>
						</tr>
						</table>
						<h1>• Косметическая стоматология</h1>
						<table class="price">
						<tr>
							<th>Аппаратное отбеливание зубов (2 челюсти)</th>
							<td>1400 грн</td>
						</tr>
						<tr>
							<th>Скайсы, стразы и другие украшения</th>
							<td>100-2000 грн</td>
						</tr>
						</table>
					</div><!-- #description -->
				</div><!-- #page_content -->
			</div><!-- #content -->
			<br class="clear" />
			<div id="footer">
				<hr>
				<table>
					<tr>
						<td width="500px" align="left"><p>2010 Endohealth</p></td>
						<td width="300px" align="right"><p>2010 Endohealth лечение зубов</p></td>
					</tr>
				</table>
			</div><!-- #footer -->
		</div> <!-- sequ_container -->
	</div>  <!-- div_st -->
</div> <!-- cat_ite_cont_m -->
<?php
   }
else
   if ($_GET['pm'] == 4)
   {
?>
<div class="catalogue_item_cont_m"> 
	<div id="div_st4">
		<div class="sequ_container">
			<div id="header">
				<table>
					<tr><td><img src="../root/msite/endohealth/logo.jpg" width="170px" height="38px" alt="EndoHealth" /></td>
						<td style="vertical-align:middle; text-align:center; height:38px; width:800px;">
						<p class="phone">[062] 311-55-97; [095] 900-32-00</p>
						</td>
					</tr>
				</table>
				<div id="menu">
					<table>
						<tr>
							<td width="198" align="center"><a class="menu_button" href="index.php?business_full=650&pm=1">О нас</a></td>
							<td><img src="../root/msite/endohealth/separator.png" width="2px" height="40px" alt="" /></td>
							<td width="200" align="center"><a class="menu_button" href="index.php?business_full=650&pm=2">Виды услуг</a></td>
							<td><img src="../root/msite/endohealth/separator.png" width="2px" height="40px" alt="" /></td>
							<td width="198" align="center"><a class="menu_button" href="index.php?business_full=650&pm=3">Прайс</a></td>
							<td><img src="../root/msite/endohealth/separator.png" width="2px" height="40px" alt="" /></td>
							<td width="198" align="center"><a class="menu_button" href="index.php?business_full=650&pm=4">Контакты</a></td>
						</tr>
					</table>
				</div><!-- #menu -->
			</div><!-- #header -->
			
			<div id="content">		
				<div id="banner">
					<img src="../root/msite/endohealth/banner.jpg" width="200px" height="200px" alt="" />
					<p style="font-size: 28px; padding-top: 15px;">Стоматология</p>
					<p style="font-size: 24px;">Endohealth</p>
					<p style="font-size: 20px;">Легко быть здоровым</p>
					<p style="font-size: 14px;">Наши администраторы ответят на ваши вопросы подробно и запишут на прием в удобное для вас время</p>
					<a class="calling" href="index.php?business_full=650&pm=4">Позвонить</a>
				</div><!-- #banner -->
				<br class="clear" />
				<div id="menu_about">
					<div class="button_1">
						<div class="button_title">
							<p style="color:#056bb3;">Терапевтическая стоматология</p>
						</div><!-- .button_title -->
						<div class="button_text">
							<p>Терапевтическая стоматология занимается изучением заболевания околозубных тканей, а также методами их.</p>
						</div><!-- .button_text -->
						<a class="more" href="index.php?business_full=650&pm=5">Подробнее</a>
					</div><!-- .button_1 -->
					<div class="button_2">
						<div class="button_title">
							<p style="color:#edbc29;">Ортопедическая стоматология</p>
						</div><!-- .button_title -->
						<div class="button_text">
							<p>Ортопедическая стоматология - это вид стоматологии, посвященный диагностике и лечению нарушений целосности.</p>
						</div><!-- .button_text -->
						<a class="more" href="index.php?business_full=650&pm=6">Подробнее</a>
					</div><!-- .button_2 -->
					<div class="button_3">
						<div class="button_title">
							<p style="color:#056bb3;">Эстетическая стоматология</p>
						</div><!-- .button_title -->
						<div class="button_text">
							<p>Эстетическая стоматология быстро растет, обретая все большую популярность. Красивая улыбка всегда будет привлекать внимание.</p>
						</div><!-- .button_text -->
						<a class="more" href="index.php?business_full=650&pm=7">Подробнее</a>
					</div><!-- .button_3 -->
				</div><!-- #menu_about -->
				<br class="clear" />			
				<div id="page_content">
					<div id="description">
						<h1>Стоматология в Донецке</h1>
						<p>(+38062)311-55-97; (+38095) 900-32-00</p>
						<br />
						<p>Сегодня стало модно и престижно уделять внимание своему внешнему виду и здоровью. Здоровые зубы и прекрасная улыбка придают человеку уверенность, поднимают настроение, а также являются визитной карточкой его благополучия.</p>
						<br />
						<p>Применение новейших материалов и современных технологий в процессе лечения зубов, контроль каждого из этапов лечения позволяют нам предлагать пациенту гарантированное качество.</p>
						<br />
						<embed width="560px" height="264px" name="plugin" src="http://www.eurodonetsk.com/root/msite/endohealth/eh_karta.swf" type="application/x-shockwave-flash">
					</div><!-- #description -->
				</div><!-- #page_content -->
			</div><!-- #content -->
			<br class="clear" />
			<div id="footer">
				<hr>
				<table>
					<tr>
						<td width="500px" align="left"><p>2010 Endohealth</p></td>
						<td width="300px" align="right"><p>2010 Endohealth лечение зубов</p></td>
					</tr>
				</table>
			</div><!-- #footer -->
		</div> <!-- sequ_container -->
	</div>  <!-- div_st -->
</div> <!-- cat_ite_cont_m -->
<?php
   }
else
   if ($_GET['pm'] == 5)
   {
?>
<div class="catalogue_item_cont_m"> 
	<div id="div_st5">
		<div class="sequ_container">
			<div id="header">
				<table>
					<tr><td><img src="../root/msite/endohealth/logo.jpg" width="170px" height="38px" alt="EndoHealth" /></td>
						<td style="vertical-align:middle; text-align:center; height:38px; width:800px;">
						<p class="phone">[062] 311-55-97; [095] 900-32-00</p>
						</td>
					</tr>
				</table>
				<div id="menu">
					<table>
						<tr>
							<td width="198" align="center"><a class="menu_button" href="index.php?business_full=650&pm=1">О нас</a></td>
							<td><img src="../root/msite/endohealth/separator.png" width="2px" height="40px" alt="" /></td>
							<td width="200" align="center"><a class="menu_button" href="index.php?business_full=650&pm=2">Виды услуг</a></td>
							<td><img src="../root/msite/endohealth/separator.png" width="2px" height="40px" alt="" /></td>
							<td width="198" align="center"><a class="menu_button" href="index.php?business_full=650&pm=3">Прайс</a></td>
							<td><img src="../root/msite/endohealth/separator.png" width="2px" height="40px" alt="" /></td>
							<td width="198" align="center"><a class="menu_button" href="index.php?business_full=650&pm=4">Контакты</a></td>
						</tr>
					</table>
				</div><!-- #menu -->
			</div><!-- #header -->
			
			<div id="content">		
				<div id="banner">
					<img src="../root/msite/endohealth/banner.jpg" width="200px" height="200px" alt="" />
					<p style="font-size: 28px; padding-top: 15px;">Стоматология</p>
					<p style="font-size: 24px;">Endohealth</p>
					<p style="font-size: 20px;">Легко быть здоровым</p>
					<p style="font-size: 14px;">Наши администраторы ответят на ваши вопросы подробно и запишут на прием в удобное для вас время</p>
					<a class="calling" href="index.php?business_full=650&pm=4">Позвонить</a>
				</div><!-- #banner -->
				<br class="clear" />
				<div id="menu_about">
					<div class="button_1">
						<div class="button_title">
							<p style="color:#056bb3;">Терапевтическая стоматология</p>
						</div><!-- .button_title -->
						<div class="button_text">
							<p>Терапевтическая стоматология занимается изучением заболевания околозубных тканей, а также методами их.</p>
						</div><!-- .button_text -->
						<a class="more" href="index.php?business_full=650&pm=5">Подробнее</a>
					</div><!-- .button_1 -->
					<div class="button_2">
						<div class="button_title">
							<p style="color:#edbc29;">Ортопедическая стоматология</p>
						</div><!-- .button_title -->
						<div class="button_text">
							<p>Ортопедическая стоматология - это вид стоматологии, посвященный диагностике и лечению нарушений целосности.</p>
						</div><!-- .button_text -->
						<a class="more" href="index.php?business_full=650&pm=6">Подробнее</a>
					</div><!-- .button_2 -->
					<div class="button_3">
						<div class="button_title">
							<p style="color:#056bb3;">Эстетическая стоматология</p>
						</div><!-- .button_title -->
						<div class="button_text">
							<p>Эстетическая стоматология быстро растет, обретая все большую популярность. Красивая улыбка всегда будет привлекать внимание.</p>
						</div><!-- .button_text -->
						<a class="more" href="index.php?business_full=650&pm=7">Подробнее</a>
					</div><!-- .button_3 -->
				</div><!-- #menu_about -->
				<br class="clear" />			
				<div id="page_content">
					<div id="description">
						<p>Терапевтическая стоматология занимается изучением заболеваний зубов и околозубных тканей, а также методами их лечения.</p>
						<h1>Строение зуба</h1>
						<p>Зуб человека состоит из корня, шейки и коронки. С помощью корня, который находится в альвеоле (челюстном углублении), зуб крепится к челюсти. Шейка зуба отделяет зуб от коронки. Она находится под краем десны и начинается там, где заканчивается слой эмали. Сразу под эмалью располагается слой дентина - ткани, из которой в основном и состоит зуб. Коронка здорового зуба выступает над краем десны. Она покрыта эмалью, самой твердой частью зуба. В коронке находится полость, переходящая в зубной канал. Полость заполнена зубной тканью – пульпой, в которой проходят нервы и сосуды.</p>
						<img src="../root/msite/endohealth/image5_001.jpg" alt="" />
						<h1>Кариес</h1>
						<p>Кариесом называют процесс разрушения структуры зуба, его деминерализации и образования открытой полости в зубе. Причины кариеса многообразны, в числе их можно выделить:</p>
						<p>- недостаточную иммунологическую устойчивость;</p>
						<p>- неправильное питание, чрезмерное употребление углеводосодержащих продуктов;</p>
						<p>- отсутствие гигиены полости рта;</p>
						<p>- проблемы с минеральным обменом веществ;</p>
						<p>- экологические факторы.</p>
						<p>Возникновение кариеса может быть спровоцировано специфическим налетом на зубах, который также называют зубной бляшкой. Она состоит из слущенного эпителия, мукополисахаридов и стрептококков.</p>
						<h1>Разновидности кариеса</h1>
						<p>По особенностям протекания кариес можно разделить на острый и хронический. По глубине распространения - на:</p>
						<p>- начальный (пятнышко);</p>
						<p>- поверхностный (разрушение эмали);</p>
						<p>- средний (полость доходить до середины дентина);</p>
						<p>- глубокий (подходящий к пульпе).</p>
						<p>Если глубокий кариес не лечить, то происходит поражение внутреннего пространства зуба. В результате могут начаться серьезные осложнения: пульпит или периодонтит.</p>
						<img src="../root/msite/endohealth/image5_002.jpg" alt="" />
						<p>При начальном кариесе какие-либо болевые ощущения отсутствуют. Спорадические болезненные ощущения возникают при поверхностном и среднем кариесе. Как правило, это происходит после или во время приема холодной/горячей/кислой/сладкой и т.п. пищи.</p>
						<h1>Лечение кариеса</h1>
						<p>Для предупреждения и лечения кариеса мы рекомендуем регулярные, профилактические посещения стоматолога два раза в год. Опытный врач выявит кариес уже на начальной стадии и проведет курс реминерализующей терапии. Зубная эмаль будет восстановлена, а кариес ликвидирован. Этапы лечения:</p>
						<p>- начальный осмотр;</p>
						<p>- анестезия;</p>
						<p>- подготовка полости зуба;</p>
						<p>- установка лечебной прокладки, которая снимает воспаление с пульпы и способствует отложению заместительного дентина;</p>
						<p>- установка изолирующей прокладки;</p>
						<p>- формирование зуба с помощью пломбировочного материала (светоотверждаемых композитов);</p>
						<p>- полировка поверхности зуба.</p>
						<h1>Некариозные поражения зубов</h1>
						<p>Обычно некариозные поражения характерны для тех участков зубов, которые к кариесу невосприимчивы. То есть, они могут проявиться на буграх, передней поверхности, а иногда они затрагивают и весь зуб целиком. Некариозные поражения делятся на две группы:</p>
						<p>- поражения, которые возникают до прорезывания зубов;</p>
						<p>- поражения после прорезывания зубов.</p>
						<p>К первой группе относятся все наследственные заболевания зубов, а также поражения зубов вследствие рахита новорожденных, их интоксикации и неправильного вскармливания.</p>
						<p>При флюорозе зубов нарушается формирование костей и эмали, которое проявляется в белых и желтоватых пятнах на зубах, их эрозии и т.п. Флюороз лечат с помощью фосфорно-кальциевых препаратов.</p>
						<p>Гипоплазия эмали – это нарушения минерализации зубов у детей в виде симметрично расположенных на них пятнышек, а также эрозии и бороздок. При лечении применяется реминерализующая терапия.</p>
						<p>К поражениям после прорезывания зубов относятся эрозии, клиновидные эффекты, пигментация зубов, их повышенная стираемость и чувствительность и т.п. Как правило, все они связаны с общим состоянием организма.</p>
						<p>Эрозия зубов часто возникает после 25-30 лет. Замечено, что женщины страдают этим заболеванием чаще мужчин. Эрозии всегда сопровождаются общим неблагоприятным состоянием организма, нарушениями в работе нервной и эндокринной систем. Первый симптом эрозии - помутнение эмали зуба, что свидетельствует о нарушении минерализации. Развитие процесса грозит постепенным разрушением эмали, когда требуется уже пломбирование зуба. В любом из случаев необходим курс укрепляющей терапии.</p>
						<img src="../root/msite/endohealth/image5_003.jpg" alt="" />
						<p>При клиновидном дефекте поражение зуба имеет характерную форму, это заболевание лечится применением реминерализующей терапии, после чего устанавливается пломба.</p>
						<p>Одним из специфических некариозных заболеваний зубов может быть их гиперчувствительность. Она также связана с нарушением их минерализации и всегда вызывается общим состоянием организма.</p>						
						<h1>Осложненные формы кариеса</h1>
						<p>Прежде всего, расскажем о пульпите. Так называется воспаление мякоти зуба в результате поражения ее микробами или вследствие травмирующего воздействия. Пульпит характеризуется резкой болью, которая обостряется от температурных раздражителей.</p>
						<img src="../root/msite/endohealth/image5_004.jpg" alt="" />
						<p>Острый пульпит имеет три стадии:</p>
						<p>- начальный пульпит (зуб «потягивает», при холодной/горячей пище возникают несильные боли);</p>
						<p>- острый или очаговый пульпит (сильная боль, чаще ночью и при смене температуры);</p>
						<p>- гнойный пульпит (дневные и ночные боли, которые отдают в соседние зубы).</p>
						<p>Через две недели острый пульпит переходит в хронический, при котором болевой синдром притупляется, но фактическое состояние зуба сильно ухудшается и может привести к язвенному или гангренозному пульпиту.</p>
						<h1>Лечение пульпита</h1>
						<p>Существует два основных метода лечения пульпита:</p>
						<p>- консервативный, при котором возможно сохранение пульпы;</p>
						<p>- хирургический, при котором пульпа удаляется, а весь канал корня заполняется пломбировочным материалом.</p>
						<p>Первый метод применяется, если воспаление пульпы обратимо, а также при пульпите, вызванном механическим травмирующим воздействием.</p>
						<p>По сути, последовательность лечения пульпита схожа с лечением кариеса. Стоматолог точно так же раскрывает кариозную полость, тщательно обрабатывает ее мягкими антисептиками. Затем в полости размещается лечебная паста и ставится временная пломба. Через несколько дней можно приступать к постоянной пломбировке зуба.</p>
						<p>Лучшая профилактика пульпита – это своевременное лечение кариеса.</p>
						<h1>Периодонтит</h1>
						<p>Периодонтит является осложнением кариеса, когда воспаляется связка, удерживающая зуб в своей ячейке. Инфекция передается от воспаленной пульпы через канал корня зубы к связке. Это заболевание может быть также следствием и некоторых травмирующих факторов.</p>
						<img src="../root/msite/endohealth/image5_005.jpg" alt="" />
						<p>Острый периодонтит начинается с небольшого очага воспаления и сопровождается сильной болью, а в случае нагноения – ухудшением общего состояния. Если острое состояние не снять, то заболевание перейдет в хроническую форму. Хронический периодонтит имеет несколько разновидностей: фиброзный, гранулирующий, гранулематозный. Каждый имеет свою специфику и особенности протекания. Лечение пареодонтита включает в себя всестороннюю обработку канала зуба и его последующее пломбирование. Лечение хронической формы проводится в несколько этапов: сначала стоматолог снимает воспаление, ставит временную, а затем уже постоянную пломбу. В некоторых случаях назначается и общее физиолечение.</p>
						<h1>Обезболивание</h1>
						<p>Любое вмешательство в полости рта у нас производится с полным обезболиванием. Различные обезболивающие гели делают безболезненным даже сам укол анастетика.</p>
						<h1>Пломбирование канала</h1>
						<p>Обработать и запломбировать корневой канал очень важно, недопломбировка каналов очень часто ведет к образованию очагов хронической инфекции в верхушечной части корня (периодонтиты). А это приводит к снятию дорогостоящих металлокерамических конструкций, устранению врачебной ошибки и осложнений, повторному лечению или удалению зуба.</p>
						<h1>Лечение каналов зуба</h1>
						<p>По данным отечественной и зарубежной стоматологической литературы, от 40 до 80% пациентов нуждаются в лечении корневых каналов (эндодонтическое лечение зубов). Нередко, внешне великолепно выглядящий зуб причиняет его обладателю мучительную боль. Только полная очистка зубного канала позволяет исключить в будущем возможность воспаления даже после хорошей пломбировки зуба.</p>
						<h1>Современные способы пломбирования зубов</h1>
						<p>Сегодня при пломбировании вылеченных зубов наибольшее распространение получила методика с использованием светоотверждаемых пломб. Помимо этой, уже ставшей традиционной технологии активно применяются абсолютно новые методы пломбирования зубов.</p>
						<h1>Профилактическая стоматология</h1>
						<p>Практически все население Земного шара страдает от болезни под названием кариес, которая приводит к разрушению зубов. Для того чтобы защитить зубы от кариеса, надо удалять налет с зубов.</p>
					</div><!-- #description -->
				</div><!-- #page_content -->
			</div><!-- #content -->
			<br class="clear" />
			<div id="footer">
				<hr>
				<table>
					<tr>
						<td width="500px" align="left"><p>2010 Endohealth</p></td>
						<td width="300px" align="right"><p>2010 Endohealth лечение зубов</p></td>
					</tr>
				</table>
			</div><!-- #footer -->
		</div> <!-- sequ_container -->
	</div>  <!-- div_st -->
</div> <!-- cat_ite_cont_m -->
<?php
   }
else
   if ($_GET['pm'] == 6)
   {
?>
<div class="catalogue_item_cont_m"> 
	<div id="div_st6">
		<div class="sequ_container">
			<div id="header">
				<table>
					<tr><td><img src="../root/msite/endohealth/logo.jpg" width="170px" height="38px" alt="EndoHealth" /></td>
						<td style="vertical-align:middle; text-align:center; height:38px; width:800px;">
						<p class="phone">[062] 311-55-97; [095] 900-32-00</p>
						</td>
					</tr>
				</table>
				<div id="menu">
					<table>
						<tr>
							<td width="198" align="center"><a class="menu_button" href="index.php?business_full=650&pm=1">О нас</a></td>
							<td><img src="../root/msite/endohealth/separator.png" width="2px" height="40px" alt="" /></td>
							<td width="200" align="center"><a class="menu_button" href="index.php?business_full=650&pm=2">Виды услуг</a></td>
							<td><img src="../root/msite/endohealth/separator.png" width="2px" height="40px" alt="" /></td>
							<td width="198" align="center"><a class="menu_button" href="index.php?business_full=650&pm=3">Прайс</a></td>
							<td><img src="../root/msite/endohealth/separator.png" width="2px" height="40px" alt="" /></td>
							<td width="198" align="center"><a class="menu_button" href="index.php?business_full=650&pm=4">Контакты</a></td>
						</tr>
					</table>
				</div><!-- #menu -->
			</div><!-- #header -->
			
			<div id="content">		
				<div id="banner">
					<img src="../root/msite/endohealth/banner.jpg" width="200px" height="200px" alt="" />
					<p style="font-size: 28px; padding-top: 15px;">Стоматология</p>
					<p style="font-size: 24px;">Endohealth</p>
					<p style="font-size: 20px;">Легко быть здоровым</p>
					<p style="font-size: 14px;">Наши администраторы ответят на ваши вопросы подробно и запишут на прием в удобное для вас время</p>
					<a class="calling" href="index.php?business_full=650&pm=4">Позвонить</a>
				</div><!-- #banner -->
				<br class="clear" />
				<div id="menu_about">
					<div class="button_1">
						<div class="button_title">
							<p style="color:#056bb3;">Терапевтическая стоматология</p>
						</div><!-- .button_title -->
						<div class="button_text">
							<p>Терапевтическая стоматология занимается изучением заболевания околозубных тканей, а также методами их.</p>
						</div><!-- .button_text -->
						<a class="more" href="index.php?business_full=650&pm=5">Подробнее</a>
					</div><!-- .button_1 -->
					<div class="button_2">
						<div class="button_title">
							<p style="color:#edbc29;">Ортопедическая стоматология</p>
						</div><!-- .button_title -->
						<div class="button_text">
							<p>Ортопедическая стоматология - это вид стоматологии, посвященный диагностике и лечению нарушений целосности.</p>
						</div><!-- .button_text -->
						<a class="more" href="index.php?business_full=650&pm=6">Подробнее</a>
					</div><!-- .button_2 -->
					<div class="button_3">
						<div class="button_title">
							<p style="color:#056bb3;">Эстетическая стоматология</p>
						</div><!-- .button_title -->
						<div class="button_text">
							<p>Эстетическая стоматология быстро растет, обретая все большую популярность. Красивая улыбка всегда будет привлекать внимание.</p>
						</div><!-- .button_text -->
						<a class="more" href="index.php?business_full=650&pm=7">Подробнее</a>
					</div><!-- .button_3 -->
				</div><!-- #menu_about -->
				<br class="clear" />			
				<div id="page_content">
					<div id="description">
						<img src="../root/msite/endohealth/image6_001.jpg" style="float:left; margin: 10px;" alt="" />
						<p>Ортопедическая стоматология – это раздел стоматологии, посвященный диагностике и лечению нарушений целостности и функции зубочелюстной системы путем протезирования или установки регулирующих аппаратов. За казенным и скучным на первый взгляд определением скрыта вся история развития этой науки. Ортопедия изначально сформировалась как раздел медицины, занимающийся устранением искривления скелета, и лишь затем появился термин «ортопедическая стоматология». Конечно же, восстановлением структуры и функции жевательного аппарата человечество занималось с незапамятных времен, но как современная наука это направление возникло и стало развиваться лишь в конце XIX века.</p>
						<p>Основой ортопедической стоматологии изначально являлось протезирование зубов. Со временем оказалось, что простое протезирование далеко не всегда решает проблему здоровья челюстно-лицевой области, т.к. дефекты и деформации довольно часто возникали вновь и вновь.</p>
						<p>Выяснилось, что лечение эффективно только при соблюдении принципов профилактики развития деформаций. Это, в свою очередь, дало толчок к изучению причин и механизмов развития дефектов и деформаций, что позволило проводить лечение заболеваний более осознанно и грамотно.</p>
						<p>Кроме того, современная ортопедическая стоматология рассматривает любое заболевание только в связи с состоянием здоровья всего организма в целом. Дело в том, что процессы, протекающие в полости рта, прямо или косвенно связаны с влиянием как внешних, так и внутренних факторов (состояния самого организма). И наоборот, развитие патологии в полости рта приводит к изменениям в работе других органов и систем. Например, нарушение жевания приводит к нарушению переваривания пищевого комка, что создает условия для развития болезней желудка и кишечника. И напротив, нарушение пищеварения или кровоснабжения приводит к недостаточности питания зуба и его окружения. В завершение вспомним древнюю поговорку: «в здоровом теле – здоровый дух». Это значит, что восстановление здоровья зубочелюстной системы сказывается не только на здоровье тела, но и на здоровье духа, т.е. улучшении общего самочувствия, настроения пациента, его социальной адаптации.</p>
						<p>Ортопедическая стоматология занимается не только восстановлением, протезированием или имплантацией зубов. Важной составной частью ортопедии является ортодонтия – раздел стоматологии, занимающийся выравниванием деформаций или аномалий зубочелюстной области. Справедливости ради следует признать, что современная ортодонтия выросла в самостоятельный раздел стоматологии. И сегодня такими вопросами, как исправление прикуса, занимаются врачи-ортодонты.</p>
						<p>Врач-ортопед обязан в совершенстве знать биомеханику зубочелюстной системы, владеть определенными разделами знаний по физике, химии, биологии (анатомии и физиологии) зубочелюстной системы, знать законы артикуляции (речь, пение, смех и т.д.), владеть навыками социальной адаптации пациентов и т.д.</p>
						<h1>Металлокерамика</h1>
						<p>Металлокерамическая коронка - это наиболее распространенная по показаниям, надежная и долговечная конструкция для протезирования зубов. Это индивидуальное ювелирное изделие, состоящее из металлического каркаса, облицованного сверху фарфоровой глазурью.</p>
						<h1>Бюгельное протезирование</h1>
						<p>Бюгельный протез - это съемная ортопедическая конструкция, нагрузка в которой распределяется не только на опорные зубы, но и на слизистую оболочку (при помощи металлического дугового каркаса). Применяется как более совершенная альтернатива частичному съемному пластиночному протезу тогда, когда в силу клинической ситуации уже невозможно изготовление несъемных мостовидных протезов.</p>
						<h1>Съемное протезирование</h1>
						<p>Съемные зубные протезы применяются, когда у пациента осталось во рту так мало зубов или оставшиеся зубы ненадежны, и невозможно их использовать для протезирования несъемными протезами (коронками и мостовидными протезами).</p>
					</div><!-- #description -->
				</div><!-- #page_content -->
			</div><!-- #content -->
			<br class="clear" />
			<div id="footer">
				<hr>
				<table>
					<tr>
						<td width="500px" align="left"><p>2010 Endohealth</p></td>
						<td width="300px" align="right"><p>2010 Endohealth лечение зубов</p></td>
					</tr>
				</table>
			</div><!-- #footer -->
		</div> <!-- sequ_container -->
	</div>  <!-- div_st -->
</div> <!-- cat_ite_cont_m -->
<?php
   }
else
   if ($_GET['pm'] == 7)
   {
?>
<div class="catalogue_item_cont_m"> 
	<div id="div_st7">
		<div class="sequ_container">
			<div id="header">
				<table>
					<tr><td><img src="../root/msite/endohealth/logo.jpg" width="170px" height="38px" alt="EndoHealth" /></td>
						<td style="vertical-align:middle; text-align:center; height:38px; width:800px;">
						<p class="phone">[062] 311-55-97; [095] 900-32-00</p>
						</td>
					</tr>
				</table>
				<div id="menu">
					<table>
						<tr>
							<td width="198" align="center"><a class="menu_button" href="index.php?business_full=650&pm=1">О нас</a></td>
							<td><img src="../root/msite/endohealth/separator.png" width="2px" height="40px" alt="" /></td>
							<td width="200" align="center"><a class="menu_button" href="index.php?business_full=650&pm=2">Виды услуг</a></td>
							<td><img src="../root/msite/endohealth/separator.png" width="2px" height="40px" alt="" /></td>
							<td width="198" align="center"><a class="menu_button" href="index.php?business_full=650&pm=3">Прайс</a></td>
							<td><img src="../root/msite/endohealth/separator.png" width="2px" height="40px" alt="" /></td>
							<td width="198" align="center"><a class="menu_button" href="index.php?business_full=650&pm=4">Контакты</a></td>
						</tr>
					</table>
				</div><!-- #menu -->
			</div><!-- #header -->

			<div id="content">		
				<div id="banner">
					<img src="../root/msite/endohealth/banner.jpg" width="200px" height="200px" alt="" />
					<p style="font-size: 28px; padding-top: 15px;">Стоматология</p>
					<p style="font-size: 24px;">Endohealth</p>
					<p style="font-size: 20px;">Легко быть здоровым</p>
					<p style="font-size: 14px;">Наши администраторы ответят на ваши вопросы подробно и запишут на прием в удобное для вас время</p>
					<a class="calling" href="index.php?business_full=650&pm=4">Позвонить</a>
				</div><!-- #banner -->
				<br class="clear" />
				<div id="menu_about">
					<div class="button_1">
						<div class="button_title">
							<p style="color:#056bb3;">Терапевтическая стоматология</p>
						</div><!-- .button_title -->
						<div class="button_text">
							<p>Терапевтическая стоматология занимается изучением заболевания околозубных тканей, а также методами их.</p>
						</div><!-- .button_text -->
						<a class="more" href="index.php?business_full=650&pm=5">Подробнее</a>
					</div><!-- .button_1 -->
					<div class="button_2">
						<div class="button_title">
							<p style="color:#edbc29;">Ортопедическая стоматология</p>
						</div><!-- .button_title -->
						<div class="button_text">
							<p>Ортопедическая стоматология - это вид стоматологии, посвященный диагностике и лечению нарушений целосности.</p>
						</div><!-- .button_text -->
						<a class="more" href="index.php?business_full=650&pm=6">Подробнее</a>
					</div><!-- .button_2 -->
					<div class="button_3">
						<div class="button_title">
							<p style="color:#056bb3;">Эстетическая стоматология</p>
						</div><!-- .button_title -->
						<div class="button_text">
							<p>Эстетическая стоматология быстро растет, обретая все большую популярность. Красивая улыбка всегда будет привлекать внимание.</p>
						</div><!-- .button_text -->
						<a class="more" href="index.php?business_full=650&pm=7">Подробнее</a>
					</div><!-- .button_3 -->
				</div><!-- #menu_about -->
				<br class="clear" />			
				<div id="page_content">
					<div id="description">
						<p>Эта область стоматологии быстро растет, обретая все большую популярность. Для многих пациентов визит к стоматологу сопряжен не с мыслями о предстоящей боли, а с желанием получить максимальное удовольствие от эстетических перемен.</p>
						<p>Красивая улыбка всегда будет привлекать внимание. Во внешнем облике человека она играет особую роль. Гармония формы, пропорций, контуров и цвета зубов лежит в основе принципов создания правильного эстетического облика. Эти принципы успешно применяются для улучшения улыбок многих пациентов.</p>
						<p>Основными составляющими эстетического облика являются оптические свойства тканей здорового зуба – это все многообразие цветовых оттенков эмали зуба, насыщенность цвета, светлота, опалесценция и блеск. При различных заболеваниях зубов, таких как флюороз, гипоплазия эмали, клиновидный дефект, при влиянии вредных условий труда эти свойства могут утрачиваться.</p>
						<p>Влияют на зубы и различные заболевания организма – нарушения желудочно-кишечного тракта, системы крови, а также неконтролируемый прием лекарств. Все это может отражаться на свойствах зубов, нарушая их внешний вид.</p>
						<p>В настоящее время современная стоматология располагает целым спектром методик, позволяющих добиться прекрасного эстетического эффекта при самых различных дефектах – изменениях цвета и формы зубов, щелях между зубами, потемневших старых пломбах и многих других дефектах. К таким методикам относятся виниры или винирные покрытия – фарфоровые пластинки толщиной с лист бумаги, закрепляемые на передней поверхности зуба и придающие ему идеальный цвет и форму. Новые системы отбеливания зубов, предназначенные как для использования в домашних условиях, так и в кабинете стоматолога, сделают ваши зубы белоснежными.</p>
						<h1>Скайсы</h1>
						<img src="../root/msite/endohealth/image7_001.jpg" style="float:left; margin: 10px;" alt="" />
						<p>Существует два способа инкрустации зубов - с нарушением эмали и без.</p>
						<p>Первым способом устанавливаются бриллианты и прочие драгоценные камни. В зубе создается углубление, в котором пломбировочным средством фиксируют украшение.</p>
						<p>Но если вы не хотите нарушать здоровую ткань зуба, используйте скайсы.</p>
						<p>Скайсы - изящные стразы из драгоценных металлов и камней, плоские, тонкие, почти невесомые. Выбор огромен - золото, хрусталь, сапфир и множество искусственных материалов, прошедших токсикологические испытания. Форма - на любой вкус. Звездочки, капельки, буквы, элегантные символы, неповторимые изделия от Svarovski… Менять их вы сможете в любое время, следуя моде и всегда находясь в центре внимания.</p>
						<img src="../root/msite/endohealth/image7_002.jpg" alt="" />
						<h1>Ультразвуковая чистка зубов</h1>
						<p>Ультразвуковая чистка зубов - это профилактика от налета и зубного камня, которая необходима практически всем. Ведь зубной камень образуется буквально у каждого и является причинами многих неприятных заболеваний. Признаки того, что зубные отложения уже мешают вам жить - жжение и зуд десен, кровоточивость, запах изо рта, воспаления десен, кариес и другие, более серьезные заболевания.</p>
						<p>С чистки должно начинается любое лечение зубов и десен. Это нужно для того, чтобы обеспечить прочное соединение между поверхностью зуба и пломбы. Кроме того, это поможет правильно определить цвет зуба при подборе оттенка пломбировочного материала.</p>
						<p>В нашей стоматологической клинике врачи безболезненно снимут зубные отложения ультразвуком. Этот комплекс мероприятий включает в себя: обработку систем корневых каналов, удаление налета (в том числе от курения, пищевых красителей), эффективное удаление поддесневого камня, глубокое промывание пародонтальных карманов, полировку поверхности зуба.</p>
						<p>Делать ультразвуковую чистку зубов рекомендуется раз в полгода или в год, в зависимости от интенсивности образования налета и камней на зубах. Многие пациенты уже оценили эту услугу и предпочитают платить за профилактику заболеваний, чем за лечение и протезирование зубов.</p>
						<h1>Художественная реставрация зубов</h1>
						<p>Долгое время люди были практически лишены возможности восстановить утраченные по каким-либо причинам цвет и форму своих зубов, исключая кардинальное протезиование. Кариес на передних зубах, отломы части зуба в результате травмы, осложнения кариеса, пролеченные резорцин-формалиновым методом (который приводит к розовению и хрупкости зубов) почти в 100 % случаев означали невозможность вернуть изначальную белизну, блеск и неповторимость формы зубов.</p>
						<h1>Профессиональное отбеливание зубов</h1>
						<p>Одной разновидностью профессионального отбеливания является отбеливание Zoom. Отбеливание Zoom проводится с помощью лампы Zoom и отбеливающего геля Zoom.</p>
						<p>Свет лампы ZOOM активирует активный ингредиент отбеливающего геля – перекись водорода. Перекись водорода выделяет кислород, который проникает в эмаль и дентин и отбеливает темные пигменты, но в то же время не меняет структуру зуба. Свет лампы ZOOM способствует активированию перекиси водорода и помогает ее проникновению в поверхность зуба. Исследования показывают, что свет лампы ZOOM увеличивает эффективность геля ZOOM на 33% или больше, давая среднее улучшение цвета на восемь оттенков.</p>
						<p>При процедуре ZOOM, как и при любом профессиональном отбеливании изолируются мягкие ткани и десна вокруг зубов. Пациенту надевают зщитные очки. После изолирования мягких тканей полости рта, на передние зубы наносится отбеливающий гель ZOOM и включают лампу ZOOM. Процедура отбеливания зубов ZOOM длится час. Затем после отбеливания на зубы наносятся препараты фтора для устранения чувствительности.</p>
						<p>Процедура ZOOM противопоказана пациентам с повышенной светочувствительностью, включая тех, которые проходят курс лечения PUVA (сорален + ультрафиолетовое излучение) или иной вид фотохимотерапии, а также пациенты с меланомой. Пациентам, которые принимают препараты, вызывающие светочувствительность, необходимо до процедуры проконсультироваться со своим лечащим врачом.</p>
						<p>Побочные эффекты: некоторые пациенты могут испытывать временное повышение чувствительности зубов к холоду во время процесса отбеливания. Эти симптомы исчезают в течении 1-3 дней после прерывания или окончания процедуры.</p>
					</div><!-- #description -->
				</div><!-- #page_content -->
			</div><!-- #content -->
			<br class="clear" />
			<div id="footer">
				<hr>
				<table>
					<tr>
						<td width="500px" align="left"><p>2010 Endohealth</p></td>
						<td width="300px" align="right"><p>2010 Endohealth лечение зубов</p></td>
					</tr>
				</table>
			</div><!-- #footer -->
		</div> <!-- sequ_container -->
	</div>  <!-- div_st -->
</div> <!-- cat_ite_cont_m -->
<?php
   }
?>



<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="index.php?section_id=32&amp;business=1">Категория:</a></div>
</div>
<div class="catalogue_item_cont">
<a href="index.php?section_id=2&amp;business=1">бизнес</a>
 / 
<a href="index.php?section_id=32&amp;business=1">предприятия</a>
 / 
<a href="index.php?section_id=387&amp;business=2">медицина</a>
 / 
<a href="index.php?section_id=513">аптеки</a>
</div>


<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="">Фотогалерея:</a></div>
</div>
<div class="catalogue_item_cont">
</div>
<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="">Контактная информация:</div>
</div>
 <div class="catalogue_item_cont">
 		 <table width="100%">
			<tbody>
 			<tr>
			<!--	<td><img class="main_sec_image" src="" width="60" height="60" border="0" alt="" /></td>-->
				<td>Адрес:</td>
				<td>Телефон:</td>
				<td>Факс:</td>
				<td>E-mail:</td>
				<td>Веб-сайт:</td>
			</tr>
			<tr>
				<td>г. Донецк,  83001<br />
				пл. Ленина, <br />
				ул. Постышева, 129</td>
				<td>062-385-05-15.<br />
				066-979-68-55<br />
				345-2-345</td>
				<td></td>
				<td></td>
				<td></td>

			</tr>
			</tbody> 
		 </table> 		
	 </div>
</div>  


