 <div class="catalogue_item_c">
<style>

html,body{}

.catalogue_item_c a {color: #000000;}

.catalogue_item_cont p {
color:#000000;
text-align:justify;
text-indent:0px;
line-height:20px;
margin:0px; 
}

img.main_sec_image {
border:none;
}
.catalogue_item_cont_m {
background: url("../root/msite/maximum/main_e.png") no-repeat scroll 100% 0 transparent;
background-color:#000000;
border:1px solid lightgray;
color:#000000;
margin:0;
margin:15px 10px 10px;
width:980px;
height:1000px;
}
.catalogue_item_cont {
background-color:#ffffff;
border-top:1px solid lightgray;
margin:0 0 7px 10px;
width:980px;
color:#000000;

}
.catalogue_item_c {
background-color:#F3F3F3;
font-family: century gotic;
}

a.menu_text {color:#858585;
font-family:arial;
font-size:36px;
font-weight:bold;
text-shadow: 0 0 0.15em #851b1b, 0 0 0.15em #851b1b,
        0 0 0.15em #851b1b;}

a.menu_text:hover {text-decoration:none;color:#ee1c24;text-shadow: 0 0 0.15em #ffffff, 0 0 0.15em #ffffff,
        0 0 0.15em #ffffff;}

img.main_sec_image {
height:240px;
padding:0;
width:240px;
}

#mm_menu, #mm_menu_1 {position:relative;left:610px;width:225px;text-align:center;}

#mm_menu_1 {color:#ffffff;
font-family:arial;
font-size:30px;
font-weight:bold;
text-shadow: 0 0 0.25em #ff3333, 0 0 0.25em #ff3333,
        0 0 0.25em #ff3333;}

.catalogue_item_cont a {
color:#000000;
}
.catalogue_item_cont a:hover {
color:#000000;
text-decoration:underline;
}
.catalogue_item_mp_a {
left:3px;
position:relative;
}

.catalogue_pic_l_1 {
width:120px;}

td.ttable {color:#FFF;font-weight:bold;font-size:12px;border:1px solid #ff0000;vertical-align:top;}

td.mtext {background-color:#787878;height: 20px;
color:#222222;
font-size:12px;
max-width:166px;
padding:5px 10px;
text-align:left;
width:166px;
border-bottom:1px solid;}

@media all and (-webkit-min-device-pixel-ratio:10000),
not all and (-webkit-min-device-pixel-ratio:0) {
  a.menu_text {font-size:34px;}
  #mm_menu_1 {font-size:28px;}
}
</style>
<?php
if ($_GET['pm'] == 1) 
{
?>

<div class="catalogue_item_cont_m">
<div id="mm_menu" style="left:70px;top:480px;"><a href="index.php?business_full=402&amp;pm=1"  class="menu_text"><b>PUB</b></a></div>
<div id="mm_menu" style="left:365px;top:439px;"><a href="index.php?business_full=402&amp;pm=2" class="menu_text">BILLIARD</a></div>
<div id="mm_menu" style="left:605px;top:399px;"><a href="index.php?business_full=402&amp;pm=3" class="menu_text">BOWLING</a></div>
<div id="mm_menu_1" style="left:100px;top:415px;">ABOUT US</div>
<table cellspacing="0" cellpadding="0" style="left:133px;position:relative;top:444px;width:700px;">
    <tr><td class="mtext" style="">Table reservation in PUB<br>Bowling lane reservation in bowling center<br>(050) 368-60-66
    </td><td rowspan="3" style="color:#FFFFFF;font-size:12px;line-height:20px;padding:0 0 0 35px;text-align:justify;vertical-align:top;"><font style="font-weight:bold;font-size:18px;color:#666666;">MAXIMUM bowling center</font>
    <br> &nbsp;&nbsp;&nbsp;&nbsp;is the biggest bowling center in Donetsk (12 bowling lanes) with modern Qubika AMF equipment. There are two adjoining functional zones: billiards (American and Russian) and PUB.
        <br>&nbsp;&nbsp;&nbsp;&nbsp;Our staff will create very comfortable and cosy atmosphere for a good rest: barmen will offer a wide choice of fresh beer and queerish cocktails, our chef cook - new delicious dishes. You can watch live broadcasts of sport or music programs.
        <br>&nbsp;&nbsp;&nbsp;&nbsp;You will be surprised by the variety of parties, contests, tournaments and presents.
        <br>&nbsp;&nbsp;&nbsp;&nbsp;Do you want to meet match? Come to our center, take part in professional or amateur competitions, and show paces.
        <br>&nbsp;&nbsp;&nbsp;&nbsp;The arrangements of ingenious staff parties, banquets and birthday parties are at your service. We will come to help together with professional masters of ceremonies, 	DJs and animators. 
        <br><font style="color:#ff3333;font-size:16px;font-weight:bold;">Take the liberty to get maximum rest!</font>
    </td>        
    </tr>
    <tr><td class="mtext">Office <br>(062) 206-62-32</td></tr>
    <tr><td class="mtext">Bowling manager <br>(062) 206-60-66
<br><br><font style="color:#ffffff;">Working with commercial proposals: <br> Art director <br> Yekaterina <br>art-dir@es.olimp.ua
<br><br>How one can find us:
<br>130, Artema street<br>Voroshilovskiy district, <br>Donetsk city
<br><a href="http://www.maximym.dn.ua">www.maximym.dn.ua</a></font></td></tr>
</table>
<div style="left: 110px; position: relative; top: 465px;"><font style="color:#ff3333;font-size:16px;font-weight:bold;">(062)206-60-66</font></div>
</div>
 <?php
}
else
   if ($_GET['pm'] == 2)
   {
?>
<div class="catalogue_item_cont_m">
<div id="mm_menu" style="left:70px;top:480px;"><a href="index.php?business_full=402&amp;pm=1"  class="menu_text"><b>PUB</b></a></div>
<div id="mm_menu" style="left:365px;top:439px;"><a href="index.php?business_full=402&amp;pm=2" class="menu_text">BILLIARD</a></div>
<div id="mm_menu" style="left:605px;top:399px;"><a href="index.php?business_full=402&amp;pm=3" class="menu_text">BOWLING</a></div>
<div id="mm_menu_1" style="left:100px;top:415px;">ABOUT US</div>
<table cellspacing="0" cellpadding="0" style="left:133px;position:relative;top:444px;width:700px;">
    <tr><td class="mtext" style="">Table reservation in PUB<br>Bowling lane reservation in bowling center<br>(050) 368-60-66
    </td><td rowspan="3" style="color:#FFFFFF;font-size:14px;line-height:20px;padding:0 0 0 35px;text-align:justify;vertical-align:top;"><font style="font-weight:bold;font-size:18px;color:#666666;">Billiards</font>
    <br>Number of tables - 2:
    <br>1. Russian pyramid – 48 UAH per hour
    <br>2. Pool (American Billiards) – 39 UAH per hour
    <br>Bar;
    <br>Ordering a menu in PUB;
    </td>
    </tr>
    <tr><td class="mtext">Office <br>(062) 206-62-32</td></tr>
    <tr><td class="mtext">Bowling manager <br>(062) 206-60-66
<br><br><font style="color:#ffffff;">Working with commercial proposals: <br> Art director <br> Yekaterina <br>art-dir@es.olimp.ua
<br><br>How one can find us:
<br>130, Artema street<br>Voroshilovskiy district, <br>Donetsk city
<br><a href="http://www.maximym.dn.ua">www.maximym.dn.ua</a></font></td></tr>
</table>
</div>
 <?php
}
else
   if ($_GET['pm'] == 3)
   {
?>
<div class="catalogue_item_cont_m" style="height:1350px;background: url(../root/msite/maximum/main_1_e.png) no-repeat scroll 100% 0 #000;">
<div id="mm_menu" style="left:70px;top:480px;"><a href="index.php?business_full=402&amp;pm=1"  class="menu_text"><b>PUB</b></a></div>
<div id="mm_menu" style="left:365px;top:439px;"><a href="index.php?business_full=402&amp;pm=2" class="menu_text">BILLIARD</a></div>
<div id="mm_menu" style="left:605px;top:399px;"><a href="index.php?business_full=402&amp;pm=3" class="menu_text">BOWLING</a></div>
<div id="mm_menu_1" style="left:100px;top:415px;">ABOUT US</div>
<table cellspacing="0" cellpadding="0" style="left:136px;position:relative;top:444px;width:700px;">
    <tr><td class="mtext" style="">Table reservation in PUB<br>Bowling lane reservation in bowling center<br>(050) 368-60-66
    </td><td rowspan="4" style="color:#FFFFFF;font-size:14px;line-height:20px;padding:0 0 0 35px;text-align:justify;vertical-align:top;"><font style="font-weight:bold;font-size:18px;color:#666666;">Bowling</font>
    
    <table cellspacing="0" cellpadding="0" style="width:100%;text-align:center;">
        <tr><td class="ttable" colspan="7" style="font-size:16px;">Bowling list price<br> 01.10.10г</td></tr>
        <tr><td class="ttable" colspan="7" style="font-size:16px;">1-12 bowling lane UAH per hour</td></tr>
        <tr><td class="ttable" colspan="7"><br></td></tr>
        <tr style="height:30px;"><td class="ttable">Time</td><td class="ttable">Monday</td><td class="ttable">Tuesday</td><td class="ttable">Wednesday</td><td class="ttable">Thursday</td><td class="ttable">Friday</td><td class="ttable">Saturday,<br> Sunday,<br>Holidays</td></tr>
        <tr style="height:30px;"><td class="ttable"><br></td><td class="ttable"></td><td class="ttable"></td><td class="ttable"></td><td class="ttable"></td><td class="ttable"></td><td class="ttable"></td></tr>
        <tr style="height:30px;"><td class="ttable">(10:00)</td><td class="ttable"></td><td class="ttable"></td><td class="ttable"></td><td class="ttable"></td><td class="ttable"></td><td class="ttable"></td></tr>
        <tr style="height:30px;"><td class="ttable">11:00-<br>19:00</td><td class="ttable">75</td><td class="ttable">75</td><td class="ttable">75</td><td class="ttable">75</td><td class="ttable">75</td><td class="ttable">120</td></tr>
        <tr style="height:30px;"><td class="ttable"></td><td class="ttable">1min-<br>1,25UAH</td><td class="ttable">1min-<br>1,25UAH</td><td class="ttable">1min-<br>1,25UAH</td><td class="ttable">1min-<br>1,25UAH</td><td class="ttable">1min-<br>1,25UAH</td><td class="ttable">1min-<br>2UAH</td></tr>
        <tr style="height:30px;"><td class="ttable"><br></td><td class="ttable"></td><td class="ttable"></td><td class="ttable"></td><td class="ttable"></td><td class="ttable"></td><td class="ttable"></td></tr>
        <tr style="height:30px;"><td class="ttable">19:00-<br>03:00</td><td class="ttable">135</td><td class="ttable">135</td><td class="ttable">135</td><td class="ttable">135</td><td class="ttable">135</td><td class="ttable">165</td></tr>
        <tr style="height:30px;"><td class="ttable">(05:00)</td><td class="ttable"></td><td class="ttable"></td><td class="ttable"></td><td class="ttable"></td><td class="ttable"></td><td class="ttable"></td></tr>
        <tr style="height:30px;"><td class="ttable"></td><td class="ttable">1min-<br>2,25UAH</td><td class="ttable">1min-<br>2,25UAH</td><td class="ttable">1min-<br>2,25UAH</td><td class="ttable">1min-<br>2,25UAH</td><td class="ttable">1min-<br>2,25UAH</td><td class="ttable">1min-<br>2,75UAH</td></tr>
        <tr style="height:30px;"><td class="ttable"><br></td><td class="ttable"></td><td class="ttable"></td><td class="ttable"></td><td class="ttable"></td><td class="ttable"></td><td class="ttable"></td></tr>
        <tr style="height:30px;"><td class="ttable" style="vertical-align:middle;">Pupils Students</td><td class="ttable" colspan="5"></td><td class="ttable">75<br>1min-1,25UAH<br>(до 16:00)</td></tr>
        <tr style="height:30px;"><td class="ttable""></td><td class="ttable" colspan="5" style="vertical-align:middle;font-size:14px;">45</td><td class="ttable"></td></tr>
        <tr style="height:30px;"><td class="ttable""></td><td class="ttable" colspan="5" style="vertical-align:middle;font-size:14px;">1 min - 0,75 UAH</td><td class="ttable"></td></tr>
        <tr style="height:30px;"><td class="ttable""></td><td class="ttable" colspan="5" style="vertical-align:middle;font-size:14px;">(From 11:00 till 19:00)</td><td class="ttable"></td></tr>
        <tr style="height:30px;"><td class="ttable" colspan="6" style="vertical-align:middle;font-size:14px;text-align:left;padding:4px;">ОOne-use bowling socks  – 1,50 UAH/pair</td><td class="ttable"></td></tr>
    </table>
    </td>
    </tr>
    <tr><td class="mtext">Office <br>(062) 206-62-32</td></tr>
    <tr><td class="mtext">Bowling manager <br>(062) 206-60-66
<br><br><font style="color:#ffffff;">Working with commercial proposals: <br> Art director <br> Yekaterina <br>art-dir@es.olimp.ua
<br><br>How one can find us:
<br>130, Artema street<br>Voroshilovskiy district, <br>Donetsk city
<br><a href="http://www.maximym.dn.ua">www.maximym.dn.ua</a></font></td></tr>
     <tr><td><br></td></tr>
</table>
</div>
<?php
   } 
?>



<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="index.php?section_id=32&amp;business=1">Category:</a></div>
</div>
<div class="catalogue_item_cont">
<a href="index.php?section_id=456&amp;business=1">Business</a>
 / 
<a href="index.php?section_id=616&amp;business=1">Enterprises</a>
 / 
<a href="index.php?section_id=619&amp;business=2">Recreation facilities</a>
 / 
<a href="index.php?section_id=685&amp;business=2">Entertainment Complexes</a>
</div>


<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
Gallery:</div>
</div>
<div class="catalogue_item_cont">
<div class="catalogue_pic_l"><a href="root/msite/maximum/gallery/1.jpg" target="_blank"><img src="root/msite/maximum/gallery/1_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/maximum/gallery/2.jpg" target="_blank"><img src="root/msite/maximum/gallery/2_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/maximum/gallery/3.jpg" target="_blank"><img src="root/msite/maximum/gallery/3_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/maximum/gallery/4.jpg" target="_blank"><img src="root/msite/maximum/gallery/4_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/maximum/gallery/5.jpg" target="_blank"><img src="root/msite/maximum/gallery/5_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/maximum/gallery/6.jpg" target="_blank"><img src="root/msite/maximum/gallery/6_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/maximum/gallery/7.jpg" target="_blank"><img src="root/msite/maximum/gallery/7_s.jpg" width="60" height="60" border="0" alt=""></a></div>
</div>
<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
Contacts:</div>
</div>
 <div class="catalogue_item_cont">
 		 <table width="100%">
			<tbody>
 			<tr>
			<!--	<td><img class="main_sec_image" src="" width="60" height="60" border="0" alt="" /></td>-->
				<td>Address:</td>
				<td>Phone:</td>
				<td>Fax:</td>
				<td>E-mail:</td>
				<td>WWW:</td>
			</tr>
			<tr>
				<td>Donetsk city, <br>130, Artema street</td>
				<td>(062)206-60-66</td>
				<td></td>
				<td>maximym@es.olimp.ua</td>
				<td>www.maximym.dn.ua</td>

			</tr>
			</tbody> 
		 </table> 		
	 </div>
</div>  

