<div class="catalogue_item_c">

<style>



<!--

.folding{cursor:hand;font-weight:bold}

-->



.catalogue_item_cont p {

color:#000000;

text-align:justify;

text-indent:0px;

line-height:20px;

margin:0px;

}



.catalogue_item_cont_m {

background-color:#ffffcc;

border:0px solid lightgray;

color:#000000;

margin:0;

margin:15px 10px 10px;

width:980px;

}



.catalogue_item_cont {

background-color:#ffffff;

border-top:1px solid lightgray;

margin:0 0 7px 10px;

width:980px;

color:#000000;

}

.catalogue_item_c {

background-color:#F3F3F3;

}



.catalogue_item_cont a {

color:#000000;

}



.catalogue_item_cont a:hover {

color:#000000;

text-decoration:underline;

}



.catalogue_item_mp_a {

left:3px;

position:relative;

}



#mm_menu {position:relative;left:610px;width:225px;text-align:center;} 



#div_st {padding:0 0px;position:relative;height:955px;}



@media all and (-webkit-min-device-pixel-ratio:10000),

not all and (-webkit-min-device-pixel-ratio:0) {

 #div_st {height:955px;}

}

#div_st2 {padding:0 0px;position:relative;height:6750px;}



@media all and (-webkit-min-device-pixel-ratio:10000),

not all and (-webkit-min-device-pixel-ratio:0) {

 #div_st2 {height:6750px;}

}

#div_st3 {padding:0 0px;position:relative;height:800px;}



@media all and (-webkit-min-device-pixel-ratio:10000),

not all and (-webkit-min-device-pixel-ratio:0) {

 #div_st3 {height:869px;}

}



div {

	display:block;

}



.sequ_container {

	width:100%;

	height:100%;

	margin:0px;

	padding:0px;

}



.background_div {

	width:980px;

	height:950px;

	background-image:url('../root/msite/coffee/background.png');

}



.logo {

	position:absolute;

	float:right;

	right:80px;

	top:70px;

	background-image:url('../root/msite/coffee/logo.png');

	background-repeat:no-repeat;

	width:335px;

	height:168px;

}



.girl {

	position:absolute;

	float:right;

	right:47px;

	top:685px;

	background-image:url('../root/msite/coffee/girl.png');

	width:363px;

	height:201px;

}



.text_r {

	position:relative;

	float:right;

	width:390px;

	right:45px;

	top:265px;

}



#p_adv {

	font-family:Adventure;

	font:Adventure;	

	font-size:10pt;

	font-weight:bold;

	letter-spacing:1px;

	text-align:right;

	color:#775e4b;

}



.cup {

	position:absolute;

	float:left;

	left:10px;

	top:10px;

	background-image:url('../root/msite/coffee/cup.png');

	width:285px;

	height:236px;

}



@font-face {

	font-family:Adventure;

	src:url(http://www.eurodonetsk.com/public_html/root/msite/coffee/adventure_font.ttf);

}



.sil {

	position:relative;

	float:left;

	width:250px;

	left:30px;

	top:400px;

	font-family:Adventure;

	src:url(http://www.eurodonetsk.com/public_html/root/msite/coffee/adventure_font.ttf);

	font:Adventure;	

	font-size:16pt;

	font-weight:bold;

	font-style:bold;

	letter-spacing:1px;

	color:#775e4b;

}



.mid_pho {

	position:absolute;

	float:left;

	left:285px;

	top:120px;

	background-image:url('../root/msite/coffee/mid_pho.png');

	width:276px;

	height:760px;

}



.girl2 {

	position:absolute;

	float:right;

	right:50px;

	top:6485px;

	background-image:url('../root/msite/coffee/girl.png');

	width:363px;

	height:201px;

}



.background_div2 {

	position:relative;

	float:left;

	display:block;

	width:980px;

	height:6750px;

	background-image:url('../root/msite/coffee/menu_bg.png');

}



.menu {

	position:relative;

	float:right;

	width:540px;

	right:45px;

	top:265px;

	font-family:Adventure;

	src:url(http://www.eurodonetsk.com/public_html/root/msite/coffee/adventure_font.ttf);

	font:Adventure;	

	font-size:16pt;

	font-weight:bold;

	font-style:bold;

	letter-spacing:1px;

	color:#775e4b;

}



.tab {

	font-size:12pt;

	text-align:left;

}



.menu_2 {

	position:relative;

	float:right;

	width:594px;

	right:45px;

	top:265px;

	font-family:Adventure;

	src:url(http://www.eurodonetsk.com/public_html/root/msite/coffee/adventure_font.ttf);

	font:Adventure;	

	font-size:16pt;

	font-weight:bold;

	font-style:bold;

	letter-spacing:1px;

	color:#775e4b;

}

.dt_text_h1_style {
	font-family: Verdana, Arial, Helvetica, sans-serif;
	font-size: 30px;
	color: #660000;
	font-weight: bold;
	text-align:left;
}

.dt_text_h2_style {
	font-family: Verdana, Arial, Helvetica, sans-serif;
	font-size: 24px;
	color: #660000;
	text-align:left;
}

.dt_text_h2_2_style {
	font-family: Verdana, Arial, Helvetica, sans-serif;
	font-size: 20px;
	color: #000000;
	text-align:right;
}

.dt_text_h2_3_style {
	font-family: Verdana, Arial, Helvetica, sans-serif;
	font-size: 25px;
	color: #660000;
	text-align:center;
}

.dt_text_menu_style {
	font-family: Georgia, "Times New Roman", Times, serif;
	font-style:italic;
	font-size: 20px;
	color: #ffffff;
}

.dt_text_menu1_style {
	font-family: Georgia, "Times New Roman", Times, serif;
	font-style:italic;
	font-size: 11px;
	color: #660000;
	text-decoration: none;
}

.dt_text_h3_style {
	font-family: Verdana, Arial, Helvetica, sans-serif;
	font-size: 16px;
	color: #660000;
	text-align:left;


</style>

<?php

if ($_GET['pm'] == 1) 

{

?>

<div class="catalogue_item_cont_m"> 

	<table width="990" height="1140" cellpadding="0" cellspacing="0" align="center" border="0">
  <tr>
    <td height="457" colspan="4" background="../root/msite/dt/up.jpg">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="4" background="../root/msite/dt/menu_bg.png" height="81" ><div align="center">
      <table width="980" align="center" border="0">
        <tr>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff" href="index.php?business_full=535&pm=1">О нас</a></td>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff"  href="index.php?business_full=535&pm=2">Статьи</a></td>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff"  href="index.php?business_full=535&pm=6">Услуги</a></td>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff"  href="index.php?business_full=535&pm=7">Контакты</a></td>
          <td width="%">&nbsp;</td>
        </tr>
      </table>
   </div></td>
  </tr>
  <tr>
    <td colspan="4" background="../root/msite/dt/main_bg.jpg" height="962"><table width="100%" height="867" border="0">
      <tr>
        <td width="73" height="50">&nbsp;</td>
        <td width="211">&nbsp;</td>
        <td width="61">&nbsp;</td>
        <td width="552">&nbsp;</td>
        <td width="71">&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td rowspan="3" background="../root/msite/dt/ava.png">&nbsp;</td>
        <td>&nbsp;</td>
        <td rowspan="8" valign="top">
          <p class="dt_text_h2_2_style">Директор <br />
            Профессорской стоматологической клиники<br />
            «Биоинертные технологии Дент-Титан» 		    </p>
          <p class="dt_text_h2_2_style"><strong>Профессор Станислав СУРЖАНСКИЙ</strong><br />
          </p>
          <p class="dt_text_menu1_style">&nbsp;</p>
          <p class="dt_text_h2_3_style"><strong>Дорогие друзья!</strong></p>
		  <p>&nbsp;</p>
          <p class="dt_text_h3_style">Искренне приветствую всех посетителей официального сайта Профессорской стоматологической клиники «Биоинертные технологии Дент-Титан»!</p>
		  <p>&nbsp;</p>
          <p class="dt_text_h3_style"><strong>«Дент-Титан»</strong> – это сплоченный коллектив единомышленников, который по праву считают одним из лидеров отечественной стоматологии.</p>
		  <p>&nbsp;</p>
          <p class="dt_text_h3_style"><strong>«Дент-Титан»</strong>– это мини-научный центр, успешно применяющий на практике последние  разработки в области титанокерамики, титанополимеров и титаноимплантации. </p>
		  <p>&nbsp;</p>
          <p class="dt_text_h3_style"><strong>«Дент-Титан»</strong>– это богатый опыт отечественной и зарубежной стоматологии, который позволяет достичь гарантированных результатов. </p>
		  <p>&nbsp;</p>
          <p class="dt_text_h3_style"><strong>«Дент-Титан»</strong>- это трудолюбивые, талантливые люди, имена многих наших сотрудников известны не только в Украине, но и за ее пределами.</p>
		  <p>&nbsp;</p>
          <p class="dt_text_h3_style">Я, как руководитель стоматологической клиники <strong>«Биоинертные технологии Дент-Титан»</strong>, благодарен Вам за доверие и рад возможности работать для Вас. </p>
		  <p>&nbsp;</p>
          <p class="dt_text_h3_style">Со своей стороны гарантирую Вам открытость в общении. Буду рад, если сайт Профессорской стоматологической клиники «Биоинертные технологии Дент-Титан» поможет Вам получить достоверную и полезную информацию о деятельности клиники, зубном протезировании, перечне услуг, оказываемых <strong>«Дент-Титаном»</strong>.</p>
		  <p>&nbsp;</p>
          <p class="dt_text_h2_2_style">С уважением к Вам,<br />
            <strong>профессор Суржанский С.К.</strong></p></td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="70">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="79">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="69">&nbsp;</td>
        <td align="center" valign="middle">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="67">&nbsp;</td>
        <td align="center" valign="middle">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="65">&nbsp;</td>
        <td align="center" valign="middle">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
    </table></td>
  </tr>
</table>

</div> <!-- cat_ite_cont_m -->

<?php

}

else

   if ($_GET['pm'] == 2)

   {

?>

<div class="catalogue_item_cont_m"> 

	<table width="990" height="1140" cellpadding="0" cellspacing="0" align="center" border="0">
  <tr>
    <td height="457" colspan="4" background="../root/msite/dt/up.jpg">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="4" background="../root/msite/dt/menu_bg.png" height="81" ><div align="center">
      <table width="980" align="center" border="0">
        <tr>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff" href="index.php?business_full=535&pm=1">О нас</a></td>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff"  href="index.php?business_full=535&pm=2">Статьи</a></td>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff"  href="index.php?business_full=535&pm=6">Услуги</a></td>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff"  href="index.php?business_full=535&pm=7">Контакты</a></td>
          <td width="%">&nbsp;</td>
        </tr>
      </table>
    </div></td>
  </tr>
  <tr>
    <td colspan="4" background="../root/msite/dt/main_bg.jpg" height="962"><table width="100%" height="937" border="0">
      <tr>
        <td width="73" height="50">&nbsp;</td>
        <td width="193">&nbsp;</td>
        <td width="79">&nbsp;</td>
        <td width="552">&nbsp;</td>
        <td width="71">&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td background="../root/msite/dt/img_1.jpg">&nbsp;</td>
        <td>&nbsp;</td>
        <td rowspan="8" valign="top">
          <p class="dt_text_h3_style"><img src="../root/msite/dt/foto_s2.png" width="517" height="378" alt="Cтоматологическая клиника Дент-Титан"/></p>
		  <p>&nbsp;</p>
          <p class="dt_text_h3_style"><strong>Полость рта</strong> – это начало энергетического пути человека, где происходят не только механические процессы (раздавливание, разжевывание, формирование пищевого комка) , но и самые важные биохимические ферментативные процессы, нарушение которых ведет к хроническим воспалительным заболеваниям на слизистых в полости рта, а также по всему пути прохождения пищевого комка, начиная с полости рта, пищевода, желудка и т.д. </p>
		  <p>&nbsp;</p>
          <p class="dt_text_h3_style">Сегодня <strong>стоматологическая клиника "Дент-Титан"</strong> имеет  честь  предложить нашим пациентам наиболее эффективный биоинертный материал для <strong>ортопедического лечения</strong> (<strong>зубного протезирования</strong>) – <strong>титан</strong>. Всех, кто заботится о своем здоровье, мы ждем у себя. Гарантируем Вам, что зубные протезы из титанокерамики, титанокомпозитов, титанопластмассы будут абсолютно биоинертны и изготовлены на высочайшем профессиональном уровне. С вами будет работать профессор, доценты, врачи I- ой и высшей категории. Хотим напомнить: «Все в этом мире имеет свою цену, единственное здоровье не имеет цены – оно для каждого из нас – бесценно».</span><br />
          </p>          <p class="dt_text_h3_style">&nbsp;</p></td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="70">&nbsp;</td>
        <td align="center" valign="middle" background="../root/msite/dt/button2.png"><div align="center" class="dt_text_menu1_style"><a style="color: #660000"  href="http://www.eurodonetsk.com/index.php?business_full=535&pm=2">Быть здоровым, <br />
        а не казаться!</a></div></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td background="../root/msite/dt/img_2.jpg">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="69">&nbsp;</td>
        <td align="center" valign="middle" background="../root/msite/dt/button2.png"><div align="center" class="dt_text_menu1_style"><a style="color: #660000"   href="http://www.eurodonetsk.com/index.php?business_full=535&pm=3">Во рту должна быть <br />
          космическая чистота!</a></div></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td background="../root/msite/dt/img_3.jpg">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="67">&nbsp;</td>
        <td align="center" valign="middle" background="../root/msite/dt/button2.png"><div align="center" class="dt_text_menu1_style"><a style="color: #660000"   href="http://www.eurodonetsk.com/index.php?business_full=535&pm=4">Полость рта - <br />
          зеркало желудка!</a></div></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td background="../root/msite/dt/img_4.jpg">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="65">&nbsp;</td>
        <td align="center" valign="middle" background="../root/msite/dt/button2.png"><div align="center" class="dt_text_menu1_style"><a style="color: #660000"   href="http://www.eurodonetsk.com/index.php?business_full=535&pm=5">Абсолютная гармония <br />
          титана с керамикой</a></div></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
    </table></td>
  </tr>
</table>

</div> <!-- cat_ite_cont_m -->

<?php

}

else

   if ($_GET['pm'] == 3)

   {

?>

<div class="catalogue_item_cont_m"> 

	<table width="990" height="1140" cellpadding="0" cellspacing="0" align="center" border="0">
  <tr>
    <td height="457" colspan="4" background="../root/msite/dt/up.jpg">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="4" background="../root/msite/dt/menu_bg.png" height="81" ><div align="center">
      <table width="980" align="center" border="0">
        <tr>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff" href="index.php?business_full=535&pm=1">О нас</a></td>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff"  href="index.php?business_full=535&pm=2">Статьи</a></td>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff"  href="index.php?business_full=535&pm=6">Услуги</a></td>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff"  href="index.php?business_full=535&pm=7">Контакты</a></td>
          <td width="%">&nbsp;</td>
        </tr>
      </table>
    </div></td>
  </tr>
  <tr>
    <td colspan="4" background="../root/msite/dt/main_bg.jpg" height="962"><table width="100%" height="937" border="0">
      <tr>
        <td width="73" height="50">&nbsp;</td>
        <td width="193">&nbsp;</td>
        <td width="79">&nbsp;</td>
        <td width="552">&nbsp;</td>
        <td width="71">&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td background="../root/msite/dt/img_1.jpg">&nbsp;</td>
        <td>&nbsp;</td>
        <td rowspan="8" valign="top">
          <p class="dt_text_h3_style"><img src="../root/msite/dt/foto_s3.png" width="517" height="378" alt="Cтоматологическая клиника Дент-Титан"/></p>
		  <p>&nbsp;</p>
          <p class="dt_text_h3_style">Как известно, зубные несъемные мостовидные  <strong>протезы</strong> и <strong>коронки</strong> изготавливаются из металлического несущего каркаса, который впоследствии облагораживается одним из облицовочных материалов (пластмасса, фотокомпозит, керамика). <strong>Целью</strong> такого <strong>протезирования</strong> является восстановление механической жевательной эффективности зубного ряда человека. </p>
		  <p>&nbsp;</p>
		  <p class="dt_text_h3_style">В таком мостовидном протезе бывает до 13 – 16 элементов таблицы Менделеева, при этом никель, хром, кадмий, кобальт  считаются металлами – ядами и в моноварианте запрещены к применению в  биосреде (человеческом организме). А вот в сплаве, почему-то можно. И в таких сплавах как «Виталиум » Со = 61, 1 %, Сr = 31,6% ; «Витрон - 77» Ni = 70 %,  Cr = 30 %. Вершиной безумия, на наш взгляд, является сплав «Гемини - II», где никеля  - 80, 5 %. Цифры говорят сами за себя. </p>
		  <p>&nbsp;</p>
          <p class="dt_text_h3_style">Фактор многокомпонентности металлов создает условия для возникновения  гальванических токов в полости рта и выхода из сплавов микроэлементов металлов, в том числе и металлов–ядов. При их взаимодействии с высокоактивной ротовой жидкостью и биоферментами, а их в слюне более 60, возникают микротоки, называемые в стоматологии гальванозами . </span><br />
          </p>          <p class="dt_text_h3_style">&nbsp;</p></td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="70">&nbsp;</td>
        <td align="center" valign="middle" background="../root/msite/dt/button2.png"><div align="center" class="dt_text_menu1_style"><a style="color: #660000"  href="http://www.eurodonetsk.com/index.php?business_full=535&pm=2">Быть здоровым, <br />
        а не казаться!</a></div></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td background="../root/msite/dt/img_2.jpg">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="69">&nbsp;</td>
        <td align="center" valign="middle" background="../root/msite/dt/button2.png"><div align="center" class="dt_text_menu1_style"><a style="color: #660000"   href="http://www.eurodonetsk.com/index.php?business_full=535&pm=3">Во рту должна быть <br />
          космическая чистота!</a></div></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td background="../root/msite/dt/img_3.jpg">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="67">&nbsp;</td>
        <td align="center" valign="middle" background="../root/msite/dt/button2.png"><div align="center" class="dt_text_menu1_style"><a style="color: #660000"   href="http://www.eurodonetsk.com/index.php?business_full=535&pm=4">Полость рта - <br />
          зеркало желудка!</a></div></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td background="../root/msite/dt/img_4.jpg">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="65">&nbsp;</td>
        <td align="center" valign="middle" background="../root/msite/dt/button2.png"><div align="center" class="dt_text_menu1_style"><a style="color: #660000"   href="http://www.eurodonetsk.com/index.php?business_full=535&pm=5">Абсолютная гармония <br />
          титана с керамикой</a></div></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
    </table></td>
  </tr>
</table>

</div> <!-- cat_ite_cont_m -->

<?php

}

else

   if ($_GET['pm'] == 4)

   {

?>

<div class="catalogue_item_cont_m"> 

	<table width="990" height="1140" cellpadding="0" cellspacing="0" align="center" border="0">
  <tr>
    <td height="457" colspan="4" background="../root/msite/dt/up.jpg">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="4" background="../root/msite/dt/menu_bg.png" height="81" ><div align="center">
      <table width="980" align="center" border="0">
        <tr>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff" href="index.php?business_full=535&pm=1">О нас</a></td>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff"  href="index.php?business_full=535&pm=2">Статьи</a></td>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff"  href="index.php?business_full=535&pm=6">Услуги</a></td>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff"  href="index.php?business_full=535&pm=7">Контакты</a></td>
          <td width="%">&nbsp;</td>
        </tr>
      </table>
    </div></td>
  </tr>
  <tr>
    <td colspan="4" background="../root/msite/dt/main_bg.jpg" height="962"><table width="100%" height="937" border="0">
      <tr>
        <td width="73" height="50">&nbsp;</td>
        <td width="193">&nbsp;</td>
        <td width="79">&nbsp;</td>
        <td width="552">&nbsp;</td>
        <td width="71">&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td background="../root/msite/dt/img_1.jpg">&nbsp;</td>
        <td>&nbsp;</td>
        <td rowspan="8" valign="top">
          <p class="dt_text_h3_style"><img src="../root/msite/dt/foto_s4.png" width="517" height="378" alt="Cтоматологическая клиника Дент-Титан" /></p>
		  <p>&nbsp;</p>
          <p class="dt_text_h3_style">До сих пор в <strong>ортопедической стоматологии</strong> происходит парадокс – восстанавливая механическую жевательную эффективность, мы, стоматологи, нарушаем биохимические процессы формирования первичного пищевого комка, что для человека недопустимо. Вот почему стоматологическая клиника <strong>Дент-Титан</strong> выступает против многокомпонентности металлических сплавов, кто бы их ни изготавливал  (США, Япония, Германия). Факт остается фактом : они, эти сплавы – враги человеческого организма.</p>
		  <p>&nbsp;</p>
		  <p class="dt_text_h3_style">Это все было. Теперь мы впервые на Украине можем предложить совершенно <strong>биоинертный</strong>, <strong>антикоррозийный</strong>, <strong>противоаллергический</strong>, <strong>антимагнитный</strong>, <strong>легкий</strong> и <strong>прочный</strong> <strong>монометалл</strong> – <strong>титан</strong>.</p>
		  <p>&nbsp;</p>
          <p class="dt_text_h3_style">Сотрудники кафедры стоматологии факультета последипломного образования Донецкого государственного медицинского университета под руководством профессора Суржанского  С. К. совместно со стоматологической клиникой «Дент-Титан» разработали и внедрили новую альтернативную, совершенно безопасную для организма человека технологию изготовления несущих каркасов несъемных <strong>зубных протезов из титана</strong>.
</span><br />
          </p>          <p class="dt_text_h3_style">&nbsp;</p></td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="70">&nbsp;</td>
        <td align="center" valign="middle" background="../root/msite/dt/button2.png"><div align="center" class="dt_text_menu1_style"><a style="color: #660000"  href="http://www.eurodonetsk.com/index.php?business_full=535&pm=2">Быть здоровым, <br />
        а не казаться!</a></div></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td background="../root/msite/dt/img_2.jpg">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="69">&nbsp;</td>
        <td align="center" valign="middle" background="../root/msite/dt/button2.png"><div align="center" class="dt_text_menu1_style"><a style="color: #660000"   href="http://www.eurodonetsk.com/index.php?business_full=535&pm=3">Во рту должна быть <br />
          космическая чистота!</a></div></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td background="../root/msite/dt/img_3.jpg">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="67">&nbsp;</td>
        <td align="center" valign="middle" background="../root/msite/dt/button2.png"><div align="center" class="dt_text_menu1_style"><a style="color: #660000"   href="http://www.eurodonetsk.com/index.php?business_full=535&pm=4">Полость рта - <br />
          зеркало желудка!</a></div></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td background="../root/msite/dt/img_4.jpg">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="65">&nbsp;</td>
        <td align="center" valign="middle" background="../root/msite/dt/button2.png"><div align="center" class="dt_text_menu1_style"><a style="color: #660000"   href="http://www.eurodonetsk.com/index.php?business_full=535&pm=5">Абсолютная гармония <br />
          титана с керамикой</a></div></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
    </table></td>
  </tr>
</table>

</div> <!-- cat_ite_cont_m -->

<?php

}

else

   if ($_GET['pm'] == 5)

   {

?>

<div class="catalogue_item_cont_m"> 

	<table width="990" height="1140" cellpadding="0" cellspacing="0" align="center" border="0">
  <tr>
    <td height="457" colspan="4" background="../root/msite/dt/up.jpg">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="4" background="../root/msite/dt/menu_bg.png" height="81" ><div align="center">
      <table width="980" align="center" border="0">
        <tr>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff" href="index.php?business_full=535&pm=1">О нас</a></td>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff"  href="index.php?business_full=535&pm=2">Статьи</a></td>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff"  href="index.php?business_full=535&pm=6">Услуги</a></td>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff"  href="index.php?business_full=535&pm=7">Контакты</a></td>
          <td width="%">&nbsp;</td>
        </tr>
      </table>
    </div></td>
  </tr>
  <tr>
    <td colspan="4" background="../root/msite/dt/main_bg.jpg" height="962"><table width="100%" height="937" border="0">
      <tr>
        <td width="73" height="50">&nbsp;</td>
        <td width="193">&nbsp;</td>
        <td width="79">&nbsp;</td>
        <td width="552">&nbsp;</td>
        <td width="71">&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td background="../root/msite/dt/img_1.jpg">&nbsp;</td>
        <td>&nbsp;</td>
        <td rowspan="8" valign="top">
          <p class="dt_text_h3_style"><img src="../root/msite/dt/foto_s5.png" width="517" height="378" alt="Cтоматологическая клиника Дент-Титан" /></p>
		  <p>&nbsp;</p>
          <p class="dt_text_h3_style"><strong>Титан</strong> – <strong>монометалл</strong>, начиная с 1950 года широко применяется в качестве эндопротезов в человеческом организме в виде искусственных суставов, штифтов для остеосинтеза, черепных пластин и т.д. <strong>Титан – это неоспоримое преимущество в биоинертности</strong>.</p>
		  <p>&nbsp;</p>
          <p class="dt_text_h3_style">Известно также, что титан обладает бактерицидным эффектом при тесном контакте с микробными культурами и в тоже время индифферентный для микрофлоры полости рта.</p>
		  <p>&nbsp;</p>
          <p class="dt_text_h3_style">Таким образом, проводя ортопедическое лечение пациентов протезами из титана, мы не только восстанавливаем механическую функцию, но и не нарушаем биохимические процессы в полости рта.</p>
		  <p>&nbsp;</p>
		  <p class="dt_text_h3_style">Основываясь на обширном двенадцатилетнем клиническом опыте и результатах проведенных биохимических исследований у больных, мы с полной гарантией утверждаем, что титан является металлом III – го тысячелетия.</p>
		  <p>&nbsp;</p>
          <p class="dt_text_h3_style">По материалам применения титана защищены 2 докторские и 3 кандидатские диссертации. Технология запатентована в Украине. <strong>Стоматологическая клиника</strong> «<strong>Дент-Титан</strong>» является единственным патентообладателем.
</span><br />
          </p>          <p class="dt_text_h3_style">&nbsp;</p></td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="70">&nbsp;</td>
        <td align="center" valign="middle" background="../root/msite/dt/button2.png"><div align="center" class="dt_text_menu1_style"><a style="color: #660000"  href="http://www.eurodonetsk.com/index.php?business_full=535&pm=2">Быть здоровым, <br />
        а не казаться!</a></div></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td background="../root/msite/dt/img_2.jpg">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="69">&nbsp;</td>
        <td align="center" valign="middle" background="../root/msite/dt/button2.png"><div align="center" class="dt_text_menu1_style"><a style="color: #660000"   href="http://www.eurodonetsk.com/index.php?business_full=535&pm=3">Во рту должна быть <br />
          космическая чистота!</a></div></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td background="../root/msite/dt/img_3.jpg">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="67">&nbsp;</td>
        <td align="center" valign="middle" background="../root/msite/dt/button2.png"><div align="center" class="dt_text_menu1_style"><a style="color: #660000"   href="http://www.eurodonetsk.com/index.php?business_full=535&pm=4">Полость рта - <br />
          зеркало желудка!</a></div></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td background="../root/msite/dt/img_4.jpg">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="65">&nbsp;</td>
        <td align="center" valign="middle" background="../root/msite/dt/button2.png"><div align="center" class="dt_text_menu1_style"><a style="color: #660000"   href="http://www.eurodonetsk.com/index.php?business_full=535&pm=5">Абсолютная гармония <br />
          титана с керамикой</a></div></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
    </table></td>
  </tr>
</table>

</div> <!-- cat_ite_cont_m -->

<?php

}

else

   if ($_GET['pm'] == 6)

   {

?>

<div class="catalogue_item_cont_m"> 

	<table width="990" height="1140" cellpadding="0" cellspacing="0" align="center" border="0">
  <tr>
    <td height="457" colspan="4" background="../root/msite/dt/up.jpg">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="4" background="../root/msite/dt/menu_bg.png" height="81" ><div align="center">
      <table width="980" align="center" border="0">
        <tr>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff" href="index.php?business_full=535&pm=1">О нас</a></td>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff"  href="index.php?business_full=535&pm=2">Статьи</a></td>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff"  href="index.php?business_full=535&pm=6">Услуги</a></td>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff"  href="index.php?business_full=535&pm=7">Контакты</a></td>
          <td width="%">&nbsp;</td>
        </tr>
      </table>
    </div></td>
  </tr>
  <tr>
    <td colspan="4" background="../root/msite/dt/main_bg.jpg" height="962"><table width="100%" height="937" border="0">
      <tr>
        <td width="73" height="50">&nbsp;</td>
        <td width="193">&nbsp;</td>
        <td width="79">&nbsp;</td>
        <td width="552">&nbsp;</td>
        <td width="71">&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td background="../root/msite/dt/img_1.jpg">&nbsp;</td>
        <td>&nbsp;</td>
        <td rowspan="8" valign="top">
		<p>&nbsp;</p>
		<p class="dt_text_h1_style">Перечень  услуг:</p>
          <p>&nbsp;</p>
          <p class="dt_text_h2_style">1.  Эндодонтическое лечение (обработка и <br />
            пломбирование корневого канала);</p>
		  <p>&nbsp;</p>
          <p class="dt_text_h2_style">2.  Терапевтическое лечение;</p>
		  <p>&nbsp;</p>
          <p class="dt_text_h2_style">3.  Ортопедическое лечение <br />
            (металлокерамические конструкции);</p>
		  <p>&nbsp;</p>
          <p class="dt_text_h2_style">4.  Косметическое лечение;</p>
		  <p>&nbsp;</p>
          <p class="dt_text_h2_style">5.  Профессиональная гигиена <br />
            (Отбеливание);</p>
		  <p>&nbsp;</p>
          <p class="dt_text_h2_style">6.  Профилактическая чистка зубов;</p>
		  <p>&nbsp;</p>
          <p class="dt_text_h2_style">7.  Эстетическая реставрация зубов <br />
            (Восстановление изначального цвета и <br />
            формы зуба);</p>
			<p>&nbsp;</p>
          <p class="dt_text_h2_style">8.  Лечение кариеса;</p>
		  <p>&nbsp;</p>
          <p class="dt_text_h2_style">9.  Лечение заболеваний пародонта;</p>
		  <p>&nbsp;</p>
          <p class="dt_text_h2_style">10. Украшения для зубов;</p>
		  <p>&nbsp;</p>
          <p class="dt_text_h2_style">11. Аппаратные методы диагностики;</p>
		  <p>&nbsp;</p>
          <p class="dt_text_h2_style">12. Имплантация.</p></td>
		  <p>&nbsp;</p>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="70">&nbsp;</td>
        <td align="center" valign="middle" background="../root/msite/dt/button2.png"><div align="center" class="dt_text_menu1_style"><a style="color: #660000"  href="http://www.eurodonetsk.com/index.php?business_full=535&pm=2">Быть здоровым, <br />
        а не казаться!</a></div></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td background="../root/msite/dt/img_2.jpg">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="69">&nbsp;</td>
        <td align="center" valign="middle" background="../root/msite/dt/button2.png"><div align="center" class="dt_text_menu1_style"><a style="color: #660000"   href="http://www.eurodonetsk.com/index.php?business_full=535&pm=3">Во рту должна быть <br />
          космическая чистота!</a></div></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td background="../root/msite/dt/img_3.jpg">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="67">&nbsp;</td>
        <td align="center" valign="middle" background="../root/msite/dt/button2.png"><div align="center" class="dt_text_menu1_style"><a style="color: #660000"   href="http://www.eurodonetsk.com/index.php?business_full=535&pm=4">Полость рта - <br />
          зеркало желудка!</a></div></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td background="../root/msite/dt/img_4.jpg">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="65">&nbsp;</td>
        <td align="center" valign="middle" background="../root/msite/dt/button2.png"><div align="center" class="dt_text_menu1_style"><a style="color: #660000"   href="http://www.eurodonetsk.com/index.php?business_full=535&pm=5">Абсолютная гармония <br />
          титана с керамикой</a></div></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
    </table></td>
  </tr>
</table>

</div> <!-- cat_ite_cont_m -->

<?php

}

else

   if ($_GET['pm'] == 7)

   {

?>

<div class="catalogue_item_cont_m"> 

	<table width="990" height="1140" cellpadding="0" cellspacing="0" align="center" border="0">
  <tr>
    <td height="457" colspan="4" background="../root/msite/dt/up.jpg">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="4" background="../root/msite/dt/menu_bg.png" height="81" ><div align="center">
      <table width="980" align="center" border="0">
        <tr>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff" href="index.php?business_full=535&pm=1">О нас</a></td>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff"  href="index.php?business_full=535&pm=2">Статьи</a></td>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff"  href="index.php?business_full=535&pm=6">Услуги</a></td>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff"  href="index.php?business_full=535&pm=7">Контакты</a></td>
          <td width="%">&nbsp;</td>
        </tr>
      </table>
    </div></td>
  </tr>
  <tr>
    <td colspan="4" background="../root/msite/dt/main_bg.jpg" height="962"><table width="100%" height="867" border="0">
      <tr>
        <td width="30" height="50">&nbsp;</td>
        <td width="10">&nbsp;</td>
        <td width="53">&nbsp;</td>
        <td width="780">&nbsp;</td>
        <td width="95">&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td rowspan="3">&nbsp;</td>
        <td>&nbsp;</td>
        <td rowspan="8" valign="top">
          <table width="100%" border="0">
            <tr>
              <td>
              <div>

        <script src="http://api-maps.yandex.ru/1.1/index.xml?key=AAmDzUsBAAAARkVWCAIAXzMCgKN58_MQUqB134Sdp-unCH0AAAAAAAAAAACbJlz2mcKc4anRgbxx6LBZ5BHPyg==" type="text/javascript"></script>

    <script type="text/javascript">

        window.onload = function () {

            var map = new YMaps.Map(document.getElementById("YMapsID"));

            map.setCenter(new YMaps.GeoPoint(37.801871,48.010956), 17);



            var content = document.createElement('span');

            content.innerHTML = "Клиника «Дент-Титан»";

            map.openBalloon(new YMaps.GeoPoint(37.801871,48.010956), content);



            map.addControl(new YMaps.ToolBar());

            map.addControl(new YMaps.Zoom());

            map.addControl(new YMaps.MiniMap());

            map.addControl(new YMaps.ScaleLine());

        }

    </script>





	 <div id="YMapsID" style="width:90%; height:500px; position:relative; float:center; top:20px; left:40px; z-index:20; margin-bottom:40px;"></div>

   </div>
              </td>
			  <p align="center" class="dt_text_h2_3_style">Наш адрес:</p>
          <p align="center" class="dt_text_h2_3_style">83055, Украина, г. Донецк</p>
          <p align="center" class="dt_text_h2_3_style">ул. Артема, 88-а<br />
              <br />
              <strong>стоматологическая клиника «Дент-Титан»</strong></p>
          <p align="center" class="dt_text_h2_3_style">тел./факс: +38 (062) 335 – 78 - 76</p>
          </tr>
          </table>
          </td>
        
      </tr>
      <tr>
        <td height="70">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="79">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="69">&nbsp;</td>
        <td align="center" valign="middle">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="67">&nbsp;</td>
        <td align="center" valign="middle">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="65">&nbsp;</td>
        <td align="center" valign="middle">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
    </table></td>
  </tr>
</table>


</div> <!-- cat_ite_cont_m -->

<?php

   } 

?>







<div id="catalogue_item_menu">



<div class="catalogue_item_mp_a">



<a href="index.php?section_id=32&amp;business=1">Категория:</a></div>



</div>



<div class="catalogue_item_cont">



<a href="index.php?section_id=2&amp;business=1">бизнес</a>



 / 



<a href="index.php?section_id=32&amp;business=1">предприятия</a>



 / 



<a href="index.php?section_id=387&amp;business=2">Медицина</a>



 / 



<a href="index.php?section_id=511&business=2">Стоматология</a>



</div>











<div id="catalogue_item_menu">



<div class="catalogue_item_mp_a">



<a href="">Фотогалегея:</a></div>



</div>



<div class="catalogue_item_cont">



</div>



<div id="catalogue_item_menu">



<div class="catalogue_item_mp_a">



<a href="">Контактная информация:</div>



</div>



 <div class="catalogue_item_cont">



 		 <table width="100%">



			<tbody>



 			<tr>



			<!--	<td><img class="main_sec_image" src="" width="60" height="60" border="0" alt="" /></td>-->



				<td>Адрес:</td>



				<td>Телефон:</td>



				<td>Моб.:</td>



				<td>E-mail:</td>



				<td>Веб-сайт:</td>



			</tr>



			<tr>



				<td>г. Донецк, ул. Артема, 88-а</td>



				<td>+38 (062) 335–78-76</td>



				<td></td>



				<td></td>



				<td></td>



			</tr>

			</tbody> 

		 </table> 		

  </div>

</div>  





