<div class="catalogue_item_c">
<style>
.catalogue_item_c{
	background-color:#ff9933;
}
.catalogue_item_cont_m
{
	background-color: #ff9933;
	color: #000000;
	/*border: 1px solid lightgray;
*/	padding: 0;
	width: 990px;
}
#top_all_620{
	background-color: #fff;
	width: 990px;
	height: 90px;
}
#top_620{
	width: 762px;
	height: 90px;
	margin: 0 auto;
}
#menu_620{
	width: 736px;
	height: 58px;
	margin: 0 auto;
	background: url(/root/620_danta/menu.jpg) no-repeat;
}
.menu_text1_620{
	margin: 10px 0px 10px 130px;
	width: 159px;
	float: left;
}
.menu_text2_620{
	margin: 10px 130px 10px 0px;
	width: 159px;
	float: right;
	
}
.menu_text_620{
	font-family: Arial;
	text-align: center;
	font-size: 16px;
	font-weight: bold;
	text-transform: uppercase;
}
.menu_text_620 a{
	text-decoration: none;
	color: #fff;
}
.menu_text2_620 a:hover{
	text-decoration: none;
	color: #00a2ff;
}
.menu_text1_620 a:hover{
	text-decoration: none;
	color: #ffcc00;
}
#content{
	width: 700px;
	margin: 10px auto;
	clear: both;
	background: #ff9933;
}
#three_menu_620{
	margin: 10px auto;
}
a#first_menu_620{
	text-decoration: none;
	font-family: Arial;
	text-align: center;
	font-size: 16px;
	font-weight: bold;
	color: #fff;
	background: url(/root/620_danta/menu2-deact.jpg) no-repeat;
	float: left;
	width: 219px;
	height: 287px;
	margin-right: 20px;
}
p#first_menu_620{
	font-family: Arial;
	text-align: justify;
	font-size: 13px;
	font-weight: bold;
	color: #000;
	margin: 180px 10px 0px 10px;
}
#first_menu_620 a:hover{
	background: url(/root/620_danta/menu2-act.jpg) no-repeat;
}
a#second_menu_620{
	text-decoration: none;
	font-family: Arial;
	text-align: center;
	font-size: 16px;
	font-weight: bold;
	color: #fff;
	background: url(/root/620_danta/menu3-deact.jpg) no-repeat;
	float: left;
	width: 219px;
	height: 287px;
	margin-right: 20px;
}
p#second_menu_620{
	font-family: Arial;
	text-align: justify;
	font-size: 13px;
	font-weight: bold;
	color: #000;
	margin: 180px 10px 0px 10px;
}
#second_menu_620 a:hover{
	background: url(/root/620_danta/menu3-act.jpg) no-repeat;
}
a#third_menu_620{
	text-decoration: none;
	font-family: Arial;
	text-align: center;
	font-size: 16px;
	font-weight: bold;
	color: #fff;
	background: url(/root/620_danta/menu4-deact.jpg) no-repeat;
	float: left;
	width: 219px;
	height: 287px;
}
p#third_menu_620{
	font-family: Arial;
	text-align: justify;
	font-size: 13px;
	font-weight: bold;
	color: #000;
	margin: 180px 10px 0px 10px;
}
#third_menu_620 a:hover{
	background: url(/root/620_danta/menu4-act.jpg) no-repeat;
}
.page_mane_620{
	width: 219px;
	clear: both;
	float: left;
	padding: 200px 0px 0px 0px;
	margin: 0px;
}
.page_mane_620 a{
	text-decoration: none;
	font-family: Arial;
	text-align: center;
	font-size: 16px;
	font-weight: bold;
	color: #000;
	padding: 10px 90px 0px 20px;
}
.page_text_620{
	width: 435px;
	float: left;
	margin: 10px;
	text-align: justify;
	font-family: Arial;
	color: #000;
	font-size: 14px;
	text-indent: 30px;
}
</style>
<?php
if ($_GET['pm'] == 1) 
{
?>
<div class="catalogue_item_cont_m">
        <div id="top_all_620">
            <div id="top_620">
                <img src="/root/620_danta/top.jpg"/>
            </div>
        </div>
        <div id="menu_620">
            <div class="menu_text1_620">
                <p class="menu_text_620"><a href="#" title="Данта - Стоматологический кабинет в Донецке">О нас</a></p>
            </div>
            <div class="menu_text2_620">
                <p class="menu_text_620"><a href="#" title="Контакты - Стоматологический кабинет Данта в Донецке">Контакты</a></p>
            </div>
        </div>
        <div id="content">
            <div id="three_menu_620">
                <div id="first_menu_620">
                    <a href="#" title="Имплантология в Донецке" id="first_menu_620"><p id="first_menu_620">Имплант - искусственный корень из титана, который вживляется в кость челюсти, после этого на нем прочно фиксируются красивые искусственные зубы.</p></a>
                    
                </div>
                <div id="second_menu_620">
                    <a href="#" title="Ортодонтия в Донецке" id="second_menu_620"><p id="second_menu_620"><strong>Ортодонтия</strong> - это раздел стоматологии, занимающийся исправлением и предупреждением нарушения расположения зубов и аномалий прикуса.</p></a>
                </div>
                <div id="third_menu_620">
                    <a href="#" title="Пародонтология в Донецке" id="third_menu_620"><p id="third_menu_620"><strong>Пародонтология</strong> - раздел стоматологии о профилактике и лечении окружающих зуб тканей (пародонта). продукты их жизнедеятельности.</p></a>
                </div>
            </div>
            <div class="page_mane_620">
            	<a href="index.html"title="Данта - Стоматологический кабинет в Донецке">О нас
            		<img alt="Стоматологический кабинет Данта Донецк"  src="/root/620_danta/logo.png">
                </a>           	
            </div>
            <div class="page_text_620">
            <p>Один из первых <strong>в Донецке</strong> <strong>частных стоматологических кабинетов</strong>, <strong>&quot;Данта&quot;</strong> за годы работы заслужил серьезную репутацию в г.Донецке и за его пределами.</p>
             <p>В кабинете ведут прием врачи таких специальностей: ортопед, терапевт, пародонтолог, хирург-имплантолог, врач-гигиенист.</p>
             <p>Стаж работы и квалификация врачей <strong>стоматологического кабинета</strong> <strong>&quot;Данта&quot;</strong> позволяют оказывать помощь по всем сферам <strong>стоматологических услуг</strong>. Ведущий специалист кабинета - Дзюба Владимир Михайлович, имеющий более двадцати лет практики.</p>
             <p>Подготовка <strong>стоматологического кабинета</strong> к работе и стерилизация инструментария проходят в соответствии с нормами, выдвигаемыми СЭС, что полностью исключает возможность заражения пациентов какими-бы то ни было инфекциями.</p>
             <p>Мы поддерживаем тесную связь с <strong>ведущими стоматологическими клиниками</strong> Украины, России, Австрии, Германии. Постоянное участие в медицинских семинарах и международных симпозиумах позволяет нам всегда быть в курсе последних достижений в стоматологии.</p>
             <p>Гибкая <strong>система скидок</strong> <strong>стоматологического кабинета</strong> <strong>&quot;Данта&quot;</strong> гарантирует доступность специализированной стоматологической помощи всем социальным группам населения.</p>
             <p>ИНДИВИДУАЛЬНЫЙ ПОДХОД К КАЖДОМУ КЛИЕНТУ, ВЫСОКАЯ ТЕХНИЧЕСКАЯ ОСНАЩЕННОСТЬ И РАБОТА НАСТОЯЩИХ ПРОФЕССИОНАЛОВ - ЭТО ЗАЛОГ УСПЕШНОГО ЛЕЧЕНИЯ В НАШЕМ КАБИНЕТЕ!</p>
            	
            </div>
        </div>    	
    </div>
<?php
}
?>
</div>
