<div class="catalogue_item_c">

<style>



<!--

.folding{cursor:hand;font-weight:bold}

-->



.catalogue_item_cont p {

color:#000000;

text-align:justify;

text-indent:0px;

line-height:20px;

margin:0px;

}



.catalogue_item_cont_m {

background-color:#FFFFFF;

border:1px solid lightgray;

color:#000000;

margin:0;

margin:15px 10px 10px;

width:980px;

}



.catalogue_item_cont {

background-color:#ffffff;

border-top:1px solid lightgray;

margin:0 0 7px 10px;

width:980px;

color:#000000;

}

.catalogue_item_c {

background-color:#F3F3F3;

}



.catalogue_item_cont a {

color:#000000;

}



.catalogue_item_cont a:hover {

color:#000000;

text-decoration:underline;

}



.catalogue_item_mp_a {

left:3px;

position:relative;

}



#mm_menu {position:relative;left:610px;width:225px;text-align:center;} 



#div_st {padding:0 0px;position:relative;height:1205px;}



@media all and (-webkit-min-device-pixel-ratio:10000),

not all and (-webkit-min-device-pixel-ratio:0) {

 #div_st {height:1205px;}

}

#div_st2 {padding:0 0px;position:relative;height:6750px;}



@media all and (-webkit-min-device-pixel-ratio:10000),

not all and (-webkit-min-device-pixel-ratio:0) {

 #div_st2 {height:6750px;}

}

#div_st3 {padding:0 0px;position:relative;height:800px;}



@media all and (-webkit-min-device-pixel-ratio:10000),

not all and (-webkit-min-device-pixel-ratio:0) {

 #div_st3 {height:869px;}

}



div {

	display:block;

}



.sequ_container {

	width:100%;

	height:100%;

	margin:0px;

	padding:0px;

}



.background_div {

	width:980px;

	height:370px;

	background-image:url('../root/msite/miradent/upper.jpg');

}



.logo {

	position:absolute;

	float:left;

	left:10px;

	top:60px;

	background-image:url('../root/msite/miradent/logo.png');

	background-repeat:no-repeat;

	width:318px;

	height:125px;

}



.info {

	position:absolute;

	left:10px;

	top:185px;

	width:400px;

	height:300px;

}



.content_txt_afr_01 {font-family: "Times New Roman", Times, serif;
					color:#660000;
					font-size: 14px;}
					
.content_txt_afr_02 {font-family: "Times New Roman", Times, serif;
					color:#660000;
					font-weight:bold;
					font-size: 16px;}
.rx_link 			{ text-decoration:none;
					color:#660000;}


</style>

<?php

if ($_GET['pm'] == 1) 

{

?>

<div class="catalogue_item_cont_m"> 

	<table width="990" border="0" align="center" cellpadding="0" cellspacing="0" bgcolor="#ffffcc">
  <tr>
    <td colspan="6" bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2" rowspan="2" bgcolor="#CCCCCC">&nbsp;</td>
    <td height="41" colspan="2" valign="bottom"><div align="center" class="content_txt_afr_02"><a style="color:#660000" href="index.php?business_full=590&pm=1">О нас</a> | <a style="color:#660000" href="index.php?business_full=590&pm=1">Меню</a> | <a style="color:#660000" href="index.php?business_full=590&pm=1">Услуги</a> | <a style="color:#660000" href="index.php?business_full=590&pm=2">Залы</a> | <a style="color:#660000" href="index.php?business_full=590&pm=1">Развлечения</a> | <a style="color:#660000" href="index.php?business_full=590&pm=1">Специальные предложения</a> | <a style="color:#660000" href="index.php?business_full=590&pm=1">Контакты</a></div></td>
    <td colspan="2" rowspan="2" bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
  </tr>
  <tr>
    <td width="56" height="332" bgcolor="#CCCCCC">&nbsp;</td>
    <td colspan="4" background="../root/msite/afrika/logo_af.jpg" bgcolor="#CCCCCC">&nbsp;</td>
    <td width="54" bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
  <tr>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td width="14" bgcolor="#CCCCCC">&nbsp;</td>
    <td colspan="2">&nbsp;</td>
    <td width="14" bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
  <tr>
    <td height="120" bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td width="625" background="../root/msite/afrika/rest.png">&nbsp;</td>
    <td width="227" rowspan="9"><table width="100%" border="0">
      <tr>
        <td><a style="color:#660000" href="index.php?business_full=590&pm=2"><img src="../root/msite/afrika/x1_banket.png" width="227" height="120" /></a></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><a style="color:#660000" href="index.php?business_full=590&pm=1"><img src="../root/msite/afrika/x1_spec.png" width="227" height="120" /></a></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><a style="color:#660000" href="index.php?business_full=590&pm=3"><img src="../root/msite/afrika/x1_keyt.png" width="227" height="120" /></a></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><a style="color:#660000" href="index.php?business_full=590&pm=1"><img src="../root/msite/afrika/x1_strip.png" width="227" height="120" /></a></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><a style="color:#660000" href="index.php?business_full=590&pm=1"><img src="../root/msite/afrika/x1_about.png" width="227" height="120" /></a></td>
      </tr>
    </table></td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
  <tr>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td>&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
  <tr>
    <td height="120" bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td rowspan="6" valign="top"><table width="95%" border="0" align="right">
      <tr>
        <td width="95%" align="center"><div align="center" class="content_txt_afr_01">Современный Донецк трудно представить без ресторана «Африка». Ресторан расположен в центре мегаполиса, но в стороне от городского шума и оживленных магистралей. <br />
            <br />
          Секрет популярности «Африки» в профессиональном подходе ко всем тонкостям ресторанного дела, начиная с интерьера помещений и заканчивая самым главным – меню, в котором широко представлены блюда украинской, европейской, восточной и африканской кухни.<br />
          <br />
          Команда поваров и официантов входит в состав сборной Украины по кулинарному искусству, которая всегда занимает призовые места, в том числе и на престижных международных конкурсах. Было бы несправедливо умолчать о том, что 		«Африка» стала первым заведением в Донецке, предлагающим аутентичную азиатскую кухню, пригласив кулинаров из Таиланда, что может себе позволить далеко не каждый украинский ресторан. <br />
  <br />
          Экзотичный уголок «Африки» в самом сердце Донецка всегда привлекал и продолжает привлекать посетителей своими шоу-программами (включая незабываемый стриптиз) и особой атмосферой. Сегодня «Африка» не стоит на месте и продолжает завоевывать сердца дончан и гостей города. Коллектив ресторана успешно развивает такое направление как «кейтеринг».  Кейтеринг от ресторана 		&quot;Африка&quot; - это именно то, что Вам нужно. Мы предложим Вам нестандартные решения для проведения стандартных мероприятий. Приходите к нам с Вашими мыслями и планами, а мы подарим Вам незабываемые воспоминания. </div></td>
        <td width="5%" align="center">&nbsp;</td>
      </tr>
      </table></td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
  <tr>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
  <tr>
    <td height="119" bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
  <tr>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
  <tr>
    <td height="121" bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
  <tr>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
  <tr>
    <td height="123" bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td rowspan="2" valign="top" background="../root/msite/afrika/cvet_u.jpg"><table width="86%" border="0" align="center">
      <tr>
        <td><div align="right" class="content_txt_afr_01">
          <div align="center"><strong>Ресторан «Африка» идеальное место для проведения:</strong><br />
            1.    Обедов и ужинов<br />
            2.    Банкетов<br />
            3.    Фуршетов<br />
            4.    Свадебных торжеств с регистрацией бракосочетания<br />
            5.    Юбилеев<br />
            6.    Презентаций<br />
            7.    Корпоративных мероприятий<br />
          </div>
        </div></td>
      </tr>
	  <td>&nbsp;</td>
	  <tr>
        <td><div align="right" class="content_txt_afr_02">
          <div align="right"><strong>Ресторан "Африка" -</strong><br />
           - автор Ваших незабываемых воспоминаний. 
          </div>
        </div></td>
      </tr>
    </table>
      </td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
  <tr>
    <td height="127" bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td>&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
  <tr>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
</table>

</div> <!-- cat_ite_cont_m -->

<?php

}

else

   if ($_GET['pm'] == 2)

   {

?>

<div class="catalogue_item_cont_m"> 

	<table width="990" border="0" align="center" cellpadding="0" cellspacing="0" bgcolor="#ffffcc">
  <tr>
    <td colspan="6" bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2" rowspan="2" bgcolor="#CCCCCC">&nbsp;</td>
    <td height="41" colspan="2" valign="bottom"><div align="center" class="content_txt_afr_02"><a style="color:#660000" href="index.php?business_full=590&pm=1">О нас</a> | <a style="color:#660000" href="index.php?business_full=590&pm=1">Меню</a> | <a style="color:#660000" href="index.php?business_full=590&pm=1">Услуги</a> | <a style="color:#660000" href="index.php?business_full=590&pm=2">Залы</a> | <a style="color:#660000" href="index.php?business_full=590&pm=1">Развлечения</a> | <a style="color:#660000" href="index.php?business_full=590&pm=1">Специальные предложения</a> | <a style="color:#660000" href="index.php?business_full=590&pm=1">Контакты</a></div></td>
    <td colspan="2" rowspan="2" bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
  </tr>
  <tr>
    <td width="56" height="332" bgcolor="#CCCCCC">&nbsp;</td>
    <td colspan="4" background="../root/msite/afrika/logo_af.jpg" bgcolor="#CCCCCC">&nbsp;</td>
    <td width="54" bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
  <tr>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td width="14" bgcolor="#CCCCCC">&nbsp;</td>
    <td colspan="2">&nbsp;</td>
    <td width="14" bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
  <tr>
    <td height="120" bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td width="625" background="../root/msite/afrika/rest.png">&nbsp;</td>
    <td width="227" rowspan="9"><table width="100%" border="0">
      <tr>
        <td><a style="color:#660000" href="index.php?business_full=590&pm=2"><img src="../root/msite/afrika/x1_banket.png" width="227" height="120" /></a></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><a style="color:#660000" href="index.php?business_full=590&pm=1"><img src="../root/msite/afrika/x1_spec.png" width="227" height="120" /></a></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><a style="color:#660000" href="index.php?business_full=590&pm=3"><img src="../root/msite/afrika/x1_keyt.png" width="227" height="120" /></a></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><a style="color:#660000" href="index.php?business_full=590&pm=1"><img src="../root/msite/afrika/x1_strip.png" width="227" height="120" /></a></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><a style="color:#660000" href="index.php?business_full=590&pm=1"><img src="../root/msite/afrika/x1_about.png" width="227" height="120" /></a></td>
      </tr>
    </table></td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
  <tr>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td>&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
  <tr>
    <td height="120" bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td rowspan="6" valign="top"><table width="95%" border="0" align="right">
      <tr>
        <td width="96%" align="center"><table width="101%" height="" border="0">
          <tr>
            <td width="35%" height="179"><img src="../root/msite/afrika/x2_banket.png" width="219" height="143" /></td>
            <td colspan="2" class="content_txt_afr_01"> <strong>Банкетный зал.</strong> За круглым столом, в оригинальном интерьере, могут комфортно разместиться до 18 гостей. Интерьер выдержан в этническом стиле. Уютная обстановка позволяет провести торжество в теплой и дружественной атмосфере. Изюминка этого зала – фонтан в центре стола, который удивит и порадует Ваших гостей.</td>
            </tr>
          <tr>
            <td colspan="2"> <div align="right"><span class="content_txt_afr_01"><strong>Большой зал ресторана &quot;Африка&quot;</strong> может принять до 180 посетителей. Он оформлен в стиле &quot;сафари&quot; - пятнистые &quot;шкуры&quot; на столах и креслах, африканские мотивы отразились в рисунках на стене и за сценой. Потолок зала « парит» над вами, потому что его превратили… в лазурное небо с белоснежными облаками. Атмосфера большого зала дышит уютом, и зайдя сюда ненадолго, его не хочется покидать.  </span><br />
            </div></td>
            <td width="30%"><img src="../root/msite/afrika/x2_zal.png" width="219" height="143" /></td>
          </tr>
          <tr>
            <td><img src="../root/msite/afrika/x2_m_zal.png" width="219" height="143" /></td>
            <td colspan="2" class="content_txt_afr_01"><strong>Малый зал</strong> ресторана рассчитан на 30 гостей. Это место для любителей экзотики. Вас ожидает атмосфера таинственного шатра, где можно насладиться изысканными яствами, напитками и кальяном.</td>
            </tr>
          <tr>
            <td colspan="2" class="content_txt_afr_01"><div align="right"><strong>Летняя площадка ресторана «Африка»</strong> расположена на живописном берегу реки Кальмиус. Это самое романтическое место для проведения красивой выездной церемонии бракосочетания. Ее вместимость до 80 человек. Изумительной красоты фейерверки на воде и столь же замечательный салют сделают Ваш праздник незабываемым.</div></td>
            <td><img src="../root/msite/afrika/x2_ulica.png" width="219" height="143" /></td>
          </tr>
        </table></td>
        <td width="4%" align="center">&nbsp;</td>
      </tr>
    </table></td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
  <tr>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
  <tr>
    <td height="119" bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
  <tr>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
  <tr>
    <td height="121" bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
  <tr>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
  <tr>
    <td height="123" bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td rowspan="2" valign="top" background="../root/msite/afrika/cvet_u.jpg"><table width="86%" border="0" align="center">
      <tr>
        <td>&nbsp;</td>
      </tr>
    </table>
      <table width="100%" border="0">
        <tr>
          <td>
          <p align="center" class="content_txt_afr_02">&nbsp;</p>            </td>
        </tr>
      </table>    </td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
  <tr>
    <td height="127" bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td>&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
  <tr>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
</table>

</div> <!-- cat_ite_cont_m -->

<?php

}

else

   if ($_GET['pm'] == 3)

   {

?>

<div class="catalogue_item_cont_m"> 

	<table width="990" border="0" align="center" cellpadding="0" cellspacing="0" bgcolor="#ffffcc">
  <tr>
    <td colspan="6" bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2" rowspan="2" bgcolor="#CCCCCC">&nbsp;</td>
    <td height="41" colspan="2" valign="bottom"><div align="center" class="content_txt_afr_02"><a style="color:#660000" href="index.php?business_full=590&pm=1">О нас</a> | <a style="color:#660000" href="index.php?business_full=590&pm=1">Меню</a> | <a style="color:#660000" href="index.php?business_full=590&pm=1">Услуги</a> | <a style="color:#660000" href="index.php?business_full=590&pm=2">Залы</a> | <a style="color:#660000" href="index.php?business_full=590&pm=1">Развлечения</a> | <a style="color:#660000" href="index.php?business_full=590&pm=1">Специальные предложения</a> | <a style="color:#660000" href="index.php?business_full=590&pm=1">Контакты</a></div></td>
    <td colspan="2" rowspan="2" bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
  </tr>
  <tr>
    <td width="56" height="332" bgcolor="#CCCCCC">&nbsp;</td>
    <td colspan="4" background="../root/msite/afrika/logo_af.jpg" bgcolor="#CCCCCC">&nbsp;</td>
    <td width="54" bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
  <tr>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td width="14" bgcolor="#CCCCCC">&nbsp;</td>
    <td colspan="2">&nbsp;</td>
    <td width="14" bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
  <tr>
    <td height="120" bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td width="625" background="../root/msite/afrika/rest.png">&nbsp;</td>
    <td width="227" rowspan="9"><table width="100%" border="0">
      <tr>
        <td><a style="color:#660000" href="index.php?business_full=590&pm=2"><img src="../root/msite/afrika/x1_banket.png" width="227" height="120" /></a></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><a style="color:#660000" href="index.php?business_full=590&pm=1"><img src="../root/msite/afrika/x1_spec.png" width="227" height="120" /></a></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><a style="color:#660000" href="index.php?business_full=590&pm=3"><img src="../root/msite/afrika/x1_keyt.png" width="227" height="120" /></a></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><a style="color:#660000" href="index.php?business_full=590&pm=1"><img src="../root/msite/afrika/x1_strip.png" width="227" height="120" /></a></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><a style="color:#660000" href="index.php?business_full=590&pm=1"><img src="../root/msite/afrika/x1_about.png" width="227" height="120" /></a></td>
      </tr>
    </table></td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
  <tr>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td>&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
  <tr>
    <td height="120" bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td rowspan="6" valign="top"><table width="95%" border="0" align="right">
      <tr>
        <td width="95%" align="center"><div align="center" class="content_txt_afr_01">
          <p>Кейтеринг (от англ. catering service — банкетное обслуживание) — понятие, появившееся в нашем лексиконе сравнительно недавно, на сегодняшний день успешно завоевывает позиции в ресторанном бизнесе. Если место для банкета хочется выбрать особенное, знайте: с рестораном &quot;Африка&quot; возможно все. Ресторан «Африка» предлагает услуги кейтеринга – обслуживание банкетов на выезде. До 1000 и более персон.</p>
          <p> Важное событие вы можете отметить на даче, берегу реки, лесной поляне или в другом месте.<br />
            При этом меню банкета ничем не будет отличаться от блюд в стенах ресторана. Словно по мановению волшебной палочки на поляне раскинутся шатры, освещенные фонариками и украшенные разноцветными воздушными шарами и цветами. Для пикника на лоне природы повара прямо на ваших глазах приготовят несколько видов барбекю и шашлыка. Если вы предпочитаете шведский стол, вам предложат большой выбор блюд на любой вкус<br />
            В &quot;Африке&quot; успешно практикуют  кейтеринг с 2003 года.</p>
			</p>
            <p><br />
          <p><strong>Наш ресторан оказывает широкий диапозон услуг:</strong><br />
1.    Организация банкетов<br />
2.    Фуршетов<br />
3.    Свадебных торжеств<br />
4.    Барбекю<br />
5.    Презентаций<br />
6.    Корпоративных мероприятий</p>
            <p><br />

        <strong>Секрет нашего успеха:</strong><br />
            1.    Индивидуальный подход<br />
            2.    Оптимальное соотношение цены и качества<br />
            3.    Собственная материальная база<br />
            4.    Большой опыт кейтеринга<br />
            5.    Различные кухни<br />
            6.    Высокий профессиональный уровень персонала<br />
            7.    Комплекс дополнительных услуг (аренда ресторанного оборудования)<br />
          </div></td>
        <td width="5%" align="center">&nbsp;</td>
      </tr>
      </table></td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
  <tr>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
  <tr>
    <td height="119" bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
  <tr>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
  <tr>
    <td height="121" bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
  <tr>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
  <tr>
    <td height="123" bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td rowspan="2" valign="top" background="../root/msite/afrika/cvet_u.jpg"><table width="86%" border="0" align="center">
      <td>&nbsp;</td>
	  <tr>
        <td><div align="right" class="content_txt_afr_02">
          <div align="right"><strong>Ресторан "Африка" -</strong><br />
           - автор Ваших незабываемых воспоминаний. 
          </div>
        </div></td>
      </tr>
    </table>
      </td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
  <tr>
    <td height="127" bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td>&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
  <tr>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
    <td bgcolor="#CCCCCC">&nbsp;</td>
  </tr>
</table>
</div> <!-- cat_ite_cont_m -->

<?php

}

else

   if ($_GET['pm'] == 4)

   {

?>

<div class="catalogue_item_cont_m"> 

	<div id="div_st">

		<div class="sequ_container">

			<div class="background_div">

				<div class="logo"></div>

				<div class="text_r">

					<div id="p_adv">

						<p style="color:#550601; font-size:24px; text-align:center;">

						пр. Гурова 20<br /><br />

						тел. (062) 335-16-39

						</p>

						<div id="div_st4">

						<script src="http://api-maps.yandex.ru/1.1/index.xml?key=AAmDzUsBAAAARkVWCAIAXzMCgKN58_MQUqB134Sdp-unCH0AAAAAAAAAAACbJlz2mcKc4anRgbxx6LBZ5BHPyg==" type="text/javascript"></script>

						<script type="text/javascript">

						window.onload = function () {

							var map = new YMaps.Map(document.getElementById("YMapsID"));

							map.setCenter(new YMaps.GeoPoint(37.800505,48.004238), 16);



							var content = document.createElement('span');

							content.innerHTML = "Кофейня «La Petite France»";

							map.openBalloon(new YMaps.GeoPoint(37.800505,48.004159), content);



							map.addControl(new YMaps.ToolBar());

							map.addControl(new YMaps.Zoom());

							map.addControl(new YMaps.MiniMap());

							map.addControl(new YMaps.ScaleLine());

						}

    </script>





	 <div id="YMapsID" style="width:90%; height:450px; position:relative; float:left; top:20px; left:40px; z-index:20; margin-bottom:40px;"></div>

   </div>

					</div>

				</div>

				<div class="girl"></div>

				<div class="cup"></div>

				<div class="sil">

					<a href="http://eurodonetsk.com/index.php?business_full=408&pm=1" style="color:#775e4b;">

					<p>

					Главная

					</p>

					</a>

				<br />

					<a href="http://eurodonetsk.com/index.php?business_full=408&pm=2" style="color:#775e4b;">

					<p>

					Меню

					</p>

					</a>

				<br />

					<a href="http://eurodonetsk.com/index.php?business_full=408&pm=3" style="color:#775e4b;">

					<p>

					Специальные<br />

					Предложения

					</p>

					</a>

				<br />

					<a href="http://eurodonetsk.com/index.php?business_full=408&pm=4" style="color:#775e4b;">

					<p>

					Контакты

					</p>

					</a>

				</div>

				<div class="mid_pho">

				

				</div>

			</div> <!-- background_div -->

		</div> <!-- sequ_container -->

	</div>  <!-- div_st -->

</div> <!-- cat_ite_cont_m -->

<?php

   } 

?>







<div id="catalogue_item_menu">

<div class="catalogue_item_mp_a">

<a href="index.php?section_id=32&amp;business=1">Категория:</a></div>

</div>

<div class="catalogue_item_cont">

<a href="index.php?section_id=2&amp;business=1">бизнес</a>

 / 

<a href="index.php?section_id=32&amp;business=1">предприятия</a>

 / 

<a href="index.php?section_id=387&amp;business=2">отдых</a>

 / 

<a href="index.php?section_id=512&amp;business=2">кафе и рестораны</a>

</div>





<div id="catalogue_item_menu">

<div class="catalogue_item_mp_a">

<a href="">Фотогалерея:</a></div>

</div>

<div class="catalogue_item_cont">

</div>

<div id="catalogue_item_menu">

<div class="catalogue_item_mp_a">

<a href="">Контактная информация:</div>

</div>

 <div class="catalogue_item_cont">

 		 <table width="100%">

			<tbody>

 			<tr>

			<!--	<td><img class="main_sec_image" src="" width="60" height="60" border="0" alt="" /></td>-->

				<td>Адрес:</td>

				<td>Телефон:</td>

				<td>Факс:</td>

				<td>E-mail:</td>

				<td>Веб-сайт:</td>

			</tr>

			<tr>

				<td>пр. Гурова 20<br /></td>

				<td>тел. (062) 335-16-39</td>

				<td></td>

				<td></td>

				<td></td>



			</tr>

			</tbody> 

		 </table> 		

	 </div>

</div>  





