<div class="catalogue_item_c">
<style>
.catalogue_item_c{
	background-color:#fff;
}
.catalogue_item_cont_m
{
	background: url(/root/600_adriano/fon.jpg) no-repeat #efc173;
	background-color: #fff;
	color: #000000;
	border: 1px solid lightgray;
	margin: 0;
	padding: 0;
	width: 990px;
	height: 1181px;
}
.tel_600{
	color: #66cc00;
	font-family: Arial, Helvetica, sans-serif;
	font-weight: bold;
	font-size: 30px;
	float: left;
	margin: 70px 20px 50px 20px;
	float: left;
	text-shadow: 1px 2px 6px #000;
}
.pizza_600{
	width: 550px;
	height: 430px;
	background: url(/root/600_adriano/pizza.png) no-repeat;
	float: left;
}
.menu_600{
	width: 275px;
	height: 215px;
	margin: 190px 0 0 300px;
	text-align: left;
}
.menu_600 a{
	color: #FF0000;
	font-size: 18px;
	text-transform: uppercase;
	text-decoration: none;
	font-weight: bold;
	text-align: left;
}
.menu_600 a:hover{
	color: #ffff00;
	font-size: 18px;
	text-transform: uppercase;
	text-decoration: none;
	font-weight: bold;
	text-align: left;
}
.menu_in_600 a{
	color: #0d6e00;
	font-size: 18px;
	text-transform: uppercase;
	text-decoration: none;
	font-weight: bold;
}
li{
	list-style: none;
	margin-bottom: 20px;
}
.italian_600{
	color: #66cc00;
	font-family: Arial, Helvetica, sans-serif;
	font-weight: bold;
	font-size: 24px;
	text-transform: uppercase;
	text-shadow: 1px 2px 6px #000;
	text-align: center;
	margin-top: 50px;
}
a.postnoe_600 {
	background: url(/root/600_adriano/postnoe1.png) no-repeat;
	float: right;
	margin-top: -250px;
	width: 187px;
	height: 130px;
}
a.postnoe_600:hover{
	background: url(/root/600_adriano/postnoe2.png) no-repeat;	
}
.adriano_600{
	float: left;
	width: 330px;
	height: 130px;
	background: url(/root/600_adriano/adriano.png) no-repeat;
	margin-top: -120px;
	margin-left: 100px;
}
.pizza_pasta{
	color: #FF0000;
	font-family: Arial, Helvetica, sans-serif;
	font-weight: bold;
	font-size: 26px;
	text-transform: uppercase;
	float: left;
	margin: -20px 0px 0px -300px;
	text-shadow: 1px 2px 6px #fff;
}
.info_adriano{
	width: 900px;
	margin: 30px auto;
	clear: both;
	padding: 30px 0 30px 0;
	overflow:auto;
	height:600px;
	padding-right:10px;
	scrollbar-face-color: #006000;
   scrollbar-highlight-color: #9999999;
   scrollbar-shadow-color: #666666;
   scrollbar-3dlight-color: #666666;
   scrollbar-arrow-color: #ffffff;
   scrollbar-track-color: #e0efe0;
   scrollbar-darkshadow-color: #666666;
}
.foto_adriano_600{
	width: 400px;
	height: 300px;
	border: 3px solid #510000;
	margin: 10px auto;
}
.info_adriano1{
	width: 900px;
	margin: 30px auto;
	clear: both;
	padding: 30px 0 30px 0;
	overflow:auto;
	height:740px;
	padding-right:10px;
}
.info_main_title_600{
	color: #510000;
	font-family: Arial, Helvetica, sans-serif;
	font-size: 20px;
	font-weight: bold;
	text-align: center;
	margin-top: 50px;
}
.info_main_600{
	color: #510000;
	font-family: Arial, Helvetica, sans-serif;
	font-size: 16px;
	font-weight: bold;
	text-align: justify;
	text-indent: 50px;
	margin: 20px 25px;
}
.info_main_600 a{
	color: #ff0000;
	font-family: Arial, Helvetica, sans-serif;
	font-size: 16px;
	font-weight: bold;
	text-decoration: none;
}
.info_menu_title_600{
	color: #510000;
	font-family: Arial;
	font-size: 26px;
	font-weight: bold;
	text-align: center;
	text-transform: uppercase;
	text-shadow: 1px 2px 6px #fff;
	margin: 20px 0 10px 0;
}
.dostavka_600{
	color: #0d6e00;
	font-family: Arial;
	font-size: 22px;
	font-weight: bold;
	text-align: center;
	text-transform: uppercase;
	margin: 20px 0 10px 0;
	text-decoration: none;
}
 a:hover.dostavka_600{
	color: #ff0000;
	text-decoration: none;
}
.info_menu_600{
	width: 800px;
	margin: 10px auto;
}
ul.info_menu_600{
	float: left;
	margin: 10px 20px;
	width: 210px;
	height: 200px;	
}
li.info_menu_600{
	list-style: none;
	margin-bottom: 20px;
}
.info_menu_text_600{
	font-family: Times new roman;
	font-style: italic;
	font-weight: bold;
	color: #fff;
	text-align: center;
	font-size: 22px;
	text-decoration: none;
}
a:hover.info_menu_text_600{
	color: #ff0000;
	text-decoration: none;
}

ul.menu_full_600{
	margin: 20px auto;
	overflow: auto;
	height: 600px;
	padding-right: 10px;
}
li.menu_full_600{
	list-style: none;
}

ul.menu_full_text_600{
	background: #ff0000;
	margin: -25px auto 0 auto;
	padding: 15px 30px 30px 30px;
	list-style: none;
	font-family: Arial;
	color: #fff;
	text-align: justify;
	font-size: 15px;
	width: 564px;
}
li.menu_full_text_600{
	list-style: none;
	margin: 20px;
	clear: both;
	margin: 15px auto;
	width: 624px;
}
.price_600{
	float: right;
	margin-left: 10px;
}
.contacts_600{
	margin: 50px auto;
	width: 600px;
	height: 300px;
	background-color: #ffff99;
	border: 3px solid #510000;
}
.contact_info_600{
	width: 428px;
	height: 176px;
	background-image: url(/root/600_adriano/contacts.jpg);
	margin: 10px auto;
}
.contact_info_text_first_600{
	padding-top: 30px;
	font-family: Arial, Helvetica, sans-serif;
	font-weight: bold;
	text-align: center;
	font-size: 18px;
	color: #990000;
}
.contact_info_text_600{
	font-family: Arial, Helvetica, sans-serif;
	font-weight: bold;
	text-align: center;
	font-size: 16px;
	color: #990000;
	margin: 10px auto;
}
#border_brown{
	border: 3px solid #510000;
}
#text_bold{
	font-weight: bold;
	color: #510000;
}
#text_bold_red{
	font-weight: bold;
	color: #ff0000;
}
</style>
<?php
if ($_GET['pm'] == 1) 
{
?>
<div class="catalogue_item_cont_m">
    <p class="tel_600">(062) 311-59-30</p>
    <div class="pizza_600">
    	<div class="menu_600">
        	<ul>
            	<li class="menu_in_600"> <a href="index.php?business_full=600&amp;pm=1">О нас</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=2">Меню</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=3">Детям</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=4">Доставка</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=5">Адрес</a></li>
            </ul>
        </div>
    </div>
    	<p class="italian_600">Italian restaurant</p>
		<a href="index.php?business_full=600&amp;pm=15" class="postnoe_600"></a>
        <a href="index.php?business_full=600&amp;pm=1"><div class="adriano_600"></div></a>
        <p class="pizza_pasta">pizza and pasta</p>
        <div class="info_adriano">
			<!--<div class="foto_adriano_600">
				<img src="root/600_adriano/5_m.jpg" alt="Шеф-повар">
			</div>-->
        	<p class="info_main_title_600">Итальянский ресторан «Адриано»</p>
            <p class="info_main_600">Сеть итальянских ресторанов «Adriano», как и его создатель – Мистер Чарли воплощают в себе успех и совершенство. Этот влюбленный в жизнь ливанский бизнесмен, покоривший украинских гурманов роскошными блюдами и своим неизменным оптимизмом, артистичностью сумел занять в ресторанном бизнесе Харькова лидирующие позиции. Появление первого сетевого итальянского ресторана «Адриано» в самом центре Донецка стало первой ласточкой нового формата обслуживания в нашем городе.</p>
            <p class="info_main_600">Успех «Adriano» был изначально предречен благодаря философии: любовь к клиентам и своему делу - прежде всего.</p>
            <p class="info_main_600">Мистер Чарли вложил всю душу в развитие своих заведений, создал атмосферу счастья. Может быть, именно поэтому, как магнитом сюда влечет высокопоставленных людей, иностранных гостей, спортсменов, звезд шоу бизнеса,  политиков, культурных деятелей и обычных людей.</p>
            <p class="info_main_600">Дух старинной Италии, в тандеме с потрясающей кухней «Adriano» делают заведение уникальным. Именно здесь, золотыми руками победителя конкурса «Ассоциации кулинаров», готовится ароматная, итальянская пицца, вкуснейшая лазанья, спагетти, фирменный, восхитивший итальянцев крем- суп «Повезе». Кроме того, искушенные гурманы могут отведать блюда из гриль меню, приготовленные в лучших традициях итальянской кухни. Вас очарует вкус пасты, которую именитые кулинары  «Adriano» готовят по старинной технологии. Невозможно удержаться от соблазна попробовать каждую пиццу, приготовленную здесь.</p>
            <p class="info_main_600">Ресторан «Adriano» поддерживает принцип: все лучшее сразу. Поэтому, в меню заведения вы найдете самые известные и уникальные итальянские блюда, фирменные десерты, а выбор вина порадует разнообразием.</p>
            <p class="info_main_600">Забота о каждом клиенте и его детях для  «Adriano» на первом месте. Ваши игривые малыши могут спокойно развлекаться здесь, веселиться, ведь организация детских праздников – наш козырь. Для детей – специальное <a href="index.php?business_full=600&amp;pm=3">детское меню</a>, плюс подарки и сувениры.</p>
            <p class="info_main_600">Что может быть лучше, нежели ароматная, итальянская пицца «Adriano», доставленная на дом или в офис? А теперь, воспользовавшись <a href="index.php?business_full=600&amp;pm=2">меню</a> на нашем сайте Вы сможете заказать <a href="index.php?business_full=600&amp;pm=4">доставку</a> любого блюда. Так как пожелания каждого клиента для нас – закон, Вы можете быть уверенны в качественном исполнении каждого доставляемого блюда.</p>
            <p class="info_main_600">Сеть ресторанов «Adriano», как хорошее вино – попробовав один раз, уже не забудешь богатый вкус. Позвольте себе насладиться уютной атмосферой старинной Италии, влюбиться в потрясающую кухню этой удивительной страны.</p>
            <p class="info_main_600">«Adriano» - Ваш символ хорошего настроения!</p>
            </div> 	
</div>
<?php
}
else
   if ($_GET['pm'] == 2)
   {
?>
<div class="catalogue_item_cont_m">
    <p class="tel_600">(062) 311-59-30</p>
    <div class="pizza_600">
    	<div class="menu_600">
        	<ul>
            	<li> <a href="index.php?business_full=600&amp;pm=1">О нас</a></li>
                <li class="menu_in_600"> <a href="index.php?business_full=600&amp;pm=2">Меню</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=3">Детям</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=4">Доставка</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=5">Адрес</a></li>
            </ul>
        </div>
    </div>
    	<p class="italian_600">Italian restaurant</p>
		<a href="index.php?business_full=600&amp;pm=15" class="postnoe_600"></a>
        <a href="index.php?business_full=600&amp;pm=1"><div class="adriano_600"></div></a>
        <p class="pizza_pasta">pizza and pasta</p>
        <div class="info_adriano1">
        	<p class="info_menu_title_600">Меню</p>
         	<ul class="info_menu_600">
            	<a href="/index.php?business_full=600&amp;pm=6" class="info_menu_text_600">
            	<li>Закуски</li>
                <li><img src="/root/600_adriano/01menu.jpg"></li>
                </a>
            </ul>
            <ul class="info_menu_600">
            	<a href="/index.php?business_full=600&amp;pm=7" class="info_menu_text_600">
            	<li>Салаты</li>
                <li><img src="/root/600_adriano/02menu.jpg"></li>
                </a>
            </ul>
            <ul class="info_menu_600">
            	<a href="/index.php?business_full=600&amp;pm=8" class="info_menu_text_600">
            	<li>Супы</li>
                <li><img src="/root/600_adriano/03menu.jpg"></li>
                </a>
            </ul>
            <ul class="info_menu_600">
            	<a href="/index.php?business_full=600&amp;pm=9" class="info_menu_text_600">
            	<li>Паста</li>
                <li><img src="/root/600_adriano/04menu.jpg"></li>
                </a>
            </ul>
             <ul class="info_menu_600">
            	<a href="/index.php?business_full=600&amp;pm=10" class="info_menu_text_600">
            	<li>Пицца</li>
                <li><img src="/root/600_adriano/05menu.jpg"></li>
                </a>
            </ul>
            <ul class="info_menu_600">
            	<a href="/index.php?business_full=600&amp;pm=11" class="info_menu_text_600">
            	<li>Горячие блюда</li>
                <li><img src="/root/600_adriano/06menu.jpg"></li>
                </a>
            </ul>
            <ul class="info_menu_600">
            	<a href="/index.php?business_full=600&amp;pm=12" class="info_menu_text_600">
            	<li>Морепродукты</li>
                <li><img src="/root/600_adriano/07menu.jpg"></li>
                </a>
            </ul>
            <ul class="info_menu_600">
            	<a href="/index.php?business_full=600&amp;pm=13" class="info_menu_text_600">
            	<li>Десерты</li>
                <li><img src="/root/600_adriano/08menu.jpg"></li>
                </a>
            </ul>
            <ul class="info_menu_600">
            	<a href="/index.php?business_full=600&amp;pm=14" class="info_menu_text_600">
            	<li>Напитки</li>
                <li><img src="/root/600_adriano/09menu.jpg"></li>
                </a>
            </ul>      
         </div> 	
</div>
<?php
}
else
   if ($_GET['pm'] == 3)
   {
?>
<div class="catalogue_item_cont_m">
    <p class="tel_600">(062) 311-59-30</p>
    <div class="pizza_600">
    	<div class="menu_600">
        	<ul>
            	<li> <a href="index.php?business_full=600&amp;pm=1">О нас</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=2">Меню</a></li>
                <li  class="menu_in_600"> <a href="index.php?business_full=600&amp;pm=3">Детям</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=4">Доставка</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=5">Адрес</a></li>
            </ul>
        </div>
    </div>
    	<p class="italian_600">Italian restaurant</p>
		<a href="index.php?business_full=600&amp;pm=15" class="postnoe_600"></a>
        <a href="index.php?business_full=600&amp;pm=1"><div class="adriano_600"></div></a>
        <p class="pizza_pasta">pizza and pasta</p>
        <div class="info_adriano1">
        	<img src="/root/600_adriano/menu_detskoe.png">	
        </div> 	
</div>
<?php
}
else
   if ($_GET['pm'] == 4)
   {
?>
<div class="catalogue_item_cont_m">
    <p class="tel_600">(062) 311-59-30</p>
    <div class="pizza_600">
    	<div class="menu_600">
        	<ul>
            	<li> <a href="index.php?business_full=600&amp;pm=1">О нас</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=2">Меню</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=3">Детям</a></li>
                <li class="menu_in_600"> <a href="index.php?business_full=600&amp;pm=4">Доставка</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=5">Адрес</a></li>
            </ul>
        </div>
    </div>
    	<p class="italian_600">Italian restaurant</p>
		<a href="index.php?business_full=600&amp;pm=15" class="postnoe_600"></a>
        <a href="index.php?business_full=600&amp;pm=1"><div class="adriano_600"></div></a>
        <p class="pizza_pasta">pizza and pasta</p>
        <div class="info_adriano1">
        	<p class="info_menu_title_600">Доставка</p>
            <p class="contact_info_text_600">Заказ доставки по телефону: 062 311-59-30</p>
			<a href="index.php?business_full=600&amp;pm=2" class="dostavka_600">Выбрать блюда</a>           
        	
        </div> 	
</div>
<?php
}
else
   if ($_GET['pm'] == 5)
   {
?>
<div class="catalogue_item_cont_m">
    <p class="tel_600">(062) 311-59-30</p>
    <div class="pizza_600">
    	<div class="menu_600">
        	<ul>
            	<li> <a href="index.php?business_full=600&amp;pm=1">О нас</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=2">Меню</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=3">Детям</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=4">Доставка</a></li>
                <li class="menu_in_600"> <a href="index.php?business_full=600&amp;pm=5">Адрес</a></li>
            </ul>
        </div>
    </div>
    	<p class="italian_600">Italian restaurant</p>
		<a href="index.php?business_full=600&amp;pm=15" class="postnoe_600"></a>
        <a href="index.php?business_full=600&amp;pm=1"><div class="adriano_600"></div></a>
        <p class="pizza_pasta">pizza and pasta</p>
        <div class="info_adriano1">
        	<p class="info_menu_title_600">Контакты</p>
            <div class="contacts_600">
				<script src="http://api-maps.yandex.ru/1.1/index.xml?key=AAmDzUsBAAAARkVWCAIAXzMCgKN58_MQUqB134Sdp-unCH0AAAAAAAAAAACbJlz2mcKc4anRgbxx6LBZ5BHPyg==" type="text/javascript"></script>
    <script type="text/javascript">
        window.onload = function () {
            var map = new YMaps.Map(document.getElementById("YMapsID"));
            map.setCenter(new YMaps.GeoPoint(37.797748,48.023537), 14);

            var content = document.createElement('span');
            content.innerHTML = "«Адриано»";
            map.openBalloon(new YMaps.GeoPoint(37.797748,48.023537), content);
			
            map.addControl(new YMaps.ToolBar());
            map.addControl(new YMaps.Zoom());
            map.addControl(new YMaps.MiniMap());
            map.addControl(new YMaps.ScaleLine());
        }
    </script>
		<div id="YMapsID" style="width:100%;height:100%"></div>
            </div>
            <div class="contact_info_600">
            	<p class="contact_info_text_first_600">Адрес:</p>
                <p class="contact_info_text_600">г. Донецк, ул. Артема, 108</p>
                <p class="contact_info_text_600">тел.: (062) 311-59-30</p>
                <p class="contact_info_text_600">Заказ столиков: (062) 311-59-30</p>
            </div>
        	
        </div> 	
</div>
<?php
}
else
   if ($_GET['pm'] == 6)
   {
?>
<div class="catalogue_item_cont_m">
    <p class="tel_600">(062) 311-59-30</p>
    <div class="pizza_600">
    	<div class="menu_600">
        	<ul>
            	<li> <a href="index.php?business_full=600&amp;pm=1">О нас</a></li>
                <li class="menu_in_600"> <a href="index.php?business_full=600&amp;pm=2">Меню</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=3">Детям</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=4">Доставка</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=5">Адрес</a></li>
            </ul>
        </div>
    </div>
    	<p class="italian_600">Italian restaurant</p>
		<a href="index.php?business_full=600&amp;pm=15" class="postnoe_600"></a>
        <a href="index.php?business_full=600&amp;pm=1"><div class="adriano_600"></div></a>
        <p class="pizza_pasta">pizza and pasta</p>
        <div class="info_adriano1">
        	<p class="info_menu_title_600">Меню</p>
         	<ul class="menu_full_600">
                <li class="menu_full_text_600"><img src="/root/600_adriano/zakys.jpg"></li>
                <ul class="menu_full_text_600">
                	<li><p><b>Crock Adriano...............................................................................100г</b><b class="price_600">8.00 грн.</b></p>
                    	<p>Тосты, итальянский томатный соус, сыр, оливковое масло, итальянские специи.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Mozzarella al fongi.......................................................................200г</b><b class="price_600">25.00 грн.</b></p>
                    	<p>Шампиньоны запеченные с сыром Моцарелла.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Carpaccio di Manzo  .....................................................................150г</b><b class="price_600">45.00 грн.</b></p>
                    	<p>Тонко нарезанное филе телятины, сыр «Пармезан», оливковое масло, специи, лимонный фреш.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Salmon “Adriano”..........................................................................80г</b><b class="price_600">28.00 грн.</b></p>
                    	<p>Фирменная семга рассольная с розмарином.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Mozzarella Al “Promodoro”........................................................200г</b><b class="price_600">32.00 грн.</b></p>
                    	<p>Сыр «Моцарелла», помидоры, оливковое масло, специи.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Сырная тарелка..........................................................................175г</b><b class="price_600">53.00 грн.</b></p>
                    	<p>Сыр Рокфор, Моцарелла, Фета, Пармезан.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Мясная тарелка     ..........................................................................180г</b><b class="price_600">55.00 грн.</b></p>
                    	<p>Хамон, салями, бастурма, ветчина.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Ассорти оливки     ...........................................................................150г</b><b class="price_600">24.00 грн.</b></p></li>
                </ul>
            </ul>
		</div> 	
</div>

<?php
}
else
   if ($_GET['pm'] == 7)
   {
?>

<div class="catalogue_item_cont_m">
    <p class="tel_600">(062) 311-59-30</p>
    <div class="pizza_600">
    	<div class="menu_600">
        	<ul>
            	<li> <a href="index.php?business_full=600&amp;pm=1">О нас</a></li>
                <li  class="menu_in_600"> <a href="index.php?business_full=600&amp;pm=2">Меню</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=3">Детям</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=4">Доставка</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=5">Адрес</a></li>
            </ul>
        </div>
    </div>
    	<p class="italian_600">Italian restaurant</p>
		<a href="index.php?business_full=600&amp;pm=15" class="postnoe_600"></a>
        <a href="index.php?business_full=600&amp;pm=1"><div class="adriano_600"></div></a>
        <p class="pizza_pasta">pizza and pasta</p>
        <div class="info_adriano1">
        	<p class="info_menu_title_600">Меню</p>
         	<ul class="menu_full_600">
                <li class="menu_full_text_600"><img src="/root/600_adriano/salad.jpg"></li>
                <ul class="menu_full_text_600">
                	<li><p><b>Salade “Cesar”..............................................................................250г</b><b class="price_600">32.00 грн.</b></p>
                    	<p>Огурец, помидор, болгарский перец, курица, лук зеленый, сыр, сухарики, соус.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Salade “Cesario”...........................................................................300г</b><b class="price_600">39.00 грн.</b></p>
                    	<p>Теплый салат с курицей и овощами – гриль (баклажаны, цукини, помидоры, грибы) подается с сухариками.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Salade “Mazzo”.............................................................................220г</b><b class="price_600">29.00 грн.</b></p>
                    	<p>Орех грецкий, шампиньоны, курица, яйцо, яблочный сок, огурец, сыр «Пармезан», грибной соус.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Salade “Sicilia”..............................................................................220г</b><b class="price_600">29.00 грн.</b></p>
                    	<p>Яблоко, сельдерей, курица, сладкий перец, лимон, лист салата, оливки, сыр «Пармезан», соус.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Salade “Salute” ............................................................................230г</b><b class="price_600">32.00 грн.</b></p>
                    	<p>Ветчина, курица, перец болгарский, яйцо, лук, маслины, фундук, сыр пармезан, соус, специи.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Salade “Accento”...........................................................................220г</b><b class="price_600">33.00 грн.</b></p>
                    <p>Авокадо, креветки, помидор, лист салата, зелень, оливковое масло, специи, лимон.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Salade “Karavan”...........................................................................250г</b><b class="price_600">37.00 грн.</b></p>
                    <p>Бастурма, ветчина, салями, лист салата.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Salade “Superior”..........................................................................250г</b><b class="price_600">43.00 грн.</b></p>
                    <p>Семга с/с креветки, рис, оливки, огурец, кукуруза, лимон, зелень, пармезан, итальянский соус.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Salade “Frutti di mare”..................................................................220г</b><b class="price_600">45.00 грн.</b></p>
                    <p>Морской коктейль, болгарский перец, пекинская капуста, оливковое масло, лимон.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>“Salade “Buono”   ...........................................................................240г</b><b class="price_600">25.00 грн.</b></p>
                    <p>Кунжут, огурец, лист салата, помидор, перец болгарский, сыр «Фета», масло оливковое, специи, лимон.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Salade “Verdure”  ..........................................................................220г</b><b class="price_600">22.00 грн.</b></p>
                    <p>Огурец, помидор, сладкий перец, зеленый лук, лист салата, морковь, оливковое масло.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Salade “Greek”  .............................................................................250г</b><b class="price_600">29.00 грн.</b></p>
                    <p>Огурец, помидор, болгарский перец, сыр «Фета», масло оливковое, лимон.</p>
                    </li>
                </ul>
            </ul>
		</div> 	
</div>

<?php
}
else
   if ($_GET['pm'] == 8)
   {
?>

<div class="catalogue_item_cont_m">
    <p class="tel_600">(062) 311-59-30</p>
    <div class="pizza_600">
    	<div class="menu_600">
        	<ul>
            	<li> <a href="index.php?business_full=600&amp;pm=1">О нас</a></li>
                <li class="menu_in_600"> <a href="index.php?business_full=600&amp;pm=2">Меню</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=3">Детям</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=4">Доставка</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=5">Адрес</a></li>
            </ul>
        </div>
    </div>
    	<p class="italian_600">Italian restaurant</p>
		<a href="index.php?business_full=600&amp;pm=15" class="postnoe_600"></a>
        <a href="index.php?business_full=600&amp;pm=1"><div class="adriano_600"></div></a>
        <p class="pizza_pasta">pizza and pasta</p>
        <div class="info_adriano1">
        	<p class="info_menu_title_600">Меню</p>
         	<ul class="menu_full_600">
                <li class="menu_full_text_600"><img src="/root/600_adriano/syp.jpg"></li>
                <ul class="menu_full_text_600">
                	<li><p><b>Soup “Italian”..............................................................................300г</b><b class="price_600">26.00 грн.</b></p>
                    	<p>Традиционный итальянский суп с телятиной, яйцом и сыром.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Soup “Adriano”...........................................................................300г</b><b class="price_600">28.00 грн.</b></p>
                    	<p>Фирменный суп с семгой, судаком, овощами, зеленью и специями.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Soup “Fromage”..........................................................................300г</b><b class="price_600">27.00 грн.</b></p>
                    	<p>Сырный суп с пармезаном, моцареллой и мускатным орехом.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Bouillon “Legums”......................................................................300г</b><b class="price_600">19.00 грн.</b></p>
                    	<p>Бульон куриный с овощами.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>“Minestrone”................................................................................300г</b><b class="price_600">25.00 грн.</b></p>
                    	<p>Густой суп с овощами, сыром Пармезан и салями. Подается с тостами. </p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>“Vitello”.........................................................................................300г</b><b class="price_600">25.00 грн.</b></p>
                    <p>Крем-суп телятина. </p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>“Verdure”......................................................................................300г</b><b class="price_600">20.00 грн.</b></p>
                    <p>Крем-суп овощной.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>“Chicken”......................................................................................300г</b><b class="price_600">24.00 грн.</b></p>
                    <p>Крем-суп овощной с курицей.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>“Champignon”..............................................................................300г</b><b class="price_600">22.00 грн.</b></p>
                    <p>Крем-суп грибной.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>“Chicken mushrooms”................................................................300г</b><b class="price_600">24.00 грн.</b></p>
                    <p>Крем-суп грибной с курицей.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>“Frutti di mare”.............................................................................300г</b><b class="price_600">32.00 грн.</b></p>
                    <p>Крем-суп с морепродуктами.</p>
                    </li>
                </ul>
            </ul>
		</div> 	
</div>

<?php
}
else
   if ($_GET['pm'] == 9)
   {
?>

<div class="catalogue_item_cont_m">
    <p class="tel_600">(062) 311-59-30</p>
    <div class="pizza_600">
    	<div class="menu_600">
        	<ul>
            	<li> <a href="index.php?business_full=600&amp;pm=1">О нас</a></li>
                <li class="menu_in_600"> <a href="index.php?business_full=600&amp;pm=2">Меню</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=3">Детям</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=4">Доставка</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=5">Адрес</a></li>
            </ul>
        </div>
    </div>
    	<p class="italian_600">Italian restaurant</p>
		<a href="index.php?business_full=600&amp;pm=15" class="postnoe_600"></a>
        <a href="index.php?business_full=600&amp;pm=1"><div class="adriano_600"></div></a>
        <p class="pizza_pasta">pizza and pasta</p>
        <div class="info_adriano1">
        	<p class="info_menu_title_600">Меню</p>
         	<ul class="menu_full_600">
                <li class="menu_full_text_600"><img src="/root/600_adriano/pasta.jpg"></li>
                <ul class="menu_full_text_600">
                	<li><p><b>Spaghetti “Adriano”......................................................................350г</b><b class="price_600">33.00 грн.</b></p>
                    	<p>Спагетти, белый соус-крем, шампиньоны, ветчина, сыр пармезан, итальянские специи.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Spaghetti “Pollo”...........................................................................350г</b><b class="price_600">34.00 грн.</b></p>
                    	<p>Спагетти, нежное филе курицы, сливки, сыр пармезан, специи.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Spaghetti “Carbonara”..................................................................350г</b><b class="price_600">35.00 грн.</b></p>
                    	<p>Спагетти, бекон, яйцо, соус-крем, сыр пармезан, спец.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Spaghetti “al Ragou”.....................................................................350г</b><b class="price_600">34.00 грн.</b></p>
                    	<p>Спагетти, телятина, итальянский томатный соус, оливки, сыр пармезан, специи.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Spaghetti “Frutti di mare” ............................................................350г</b><b class="price_600">42.00 грн.</b></p>
                    	<p>Спагетти, морской коктейль, белый соус-крем, сыр пармезан, специи.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Spaghetti “Mussels”.....................................................................350г</b><b class="price_600">38.00 грн.</b></p>
                    <p>Спагетти, мидии, сырно-сливочный соус, сыр, итальянские специи.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Spaghetti “Al Pesto”.....................................................................350г</b><b class="price_600">39.00 грн.</b></p>
                    <p>Спагетти, фирменный соус «Al Pesto» (базилик, оливковое масло, кедровые орешки), итальянские специи.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Tagliatelles “Adriano”...................................................................350г</b><b class="price_600">39.00 грн.</b></p>
                    <p>Тальятелле, белый соус-крем, шампиньоны, ветчина, сыр, специи.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Lasagnes “Pollo”...........................................................................300г</b><b class="price_600">34.00 грн.</b></p>
                    <p>Лазанья, курица, грибы, соус «Бешамель», соус «Болньез», сыр.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Lasagnes “Con Spinaci”   ..............................................................300г</b><b class="price_600">45.00 грн.</b></p>
                    <p>Лазанья, шпинат, креветки, семга, соус «Бешамель», сыр.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Lasagnes “Adriano”   ......................................................................300г</b><b class="price_600">35.00 грн.</b></p>
                    <p>Лазанья, ветчина, соус «Бешамель», соус «Болоньез», телятина, сыр.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Lasagnes “al Ragou”   ....................................................................300г</b><b class="price_600">35.00 грн.</b></p>
                    <p>Лазанья, соус «Бешамель», соус «Болоньез», телятина, сыр.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Penne “Livere”   .............................................................................350г</b><b class="price_600">39.00 грн.</b></p>
                    <p>Пенне, печень куриная, соус «Деми Гляс», специи, яйцо перепелиное, сыр.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Penne “Adriano”   ...........................................................................350г</b><b class="price_600">34.00 грн.</b></p>
                    <p>Пенне, итальянский томатный соус, телятина, сыр, итальянские специи.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Penne “Mussel”   ............................................................................350г</b><b class="price_600">35.00 грн.</b></p>
                    <p>Пенне, мидии, сырно-сливочный соус, сыр, итальянские специи.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Penne “Quattro Formaggi”   .........................................................350г</b><b class="price_600">39.00 грн.</b></p>
                    <p>Пенне, сыр Дор-Блю, Сыр Горгонзалла, сыр Моцарелла, сыр Пармезан, сливочный соус.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Фирменные соусы:</b></p></li>
                    <li><p><b>Итальянский (острый)....................................................................50г</b><b class="price_600">7.00 грн.</b></p></li>
                    <li><p><b>Барекю (умеренно острый)..........................................................50г</b><b class="price_600">7.00 грн.</b></p></li>
                    <li><p><b>Шпинатный (не острый).................................................................50г</b><b class="price_600">8.00 грн.</b></p></li>
                    <li><p><b>Сырный Рокфор (мягкий).............................................................50г</b><b class="price_600">9.00 грн.</b></p></li>
                </ul>
                
                
            </ul>
		</div> 	
</div>

<?php
}
else
   if ($_GET['pm'] == 10)
   {
?>

<div class="catalogue_item_cont_m">
    <p class="tel_600">(062) 311-59-30</p>
    <div class="pizza_600">
    	<div class="menu_600">
        	<ul>
            	<li> <a href="index.php?business_full=600&amp;pm=1">О нас</a></li>
                <li class="menu_in_600"> <a href="index.php?business_full=600&amp;pm=2">Меню</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=3">Детям</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=4">Доставка</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=5">Адрес</a></li>
            </ul>
        </div>
    </div>
    	<p class="italian_600">Italian restaurant</p>
		<a href="index.php?business_full=600&amp;pm=15" class="postnoe_600"></a>
        <a href="index.php?business_full=600&amp;pm=1"><div class="adriano_600"></div></a>
        <p class="pizza_pasta">pizza and pasta</p>
        <div class="info_adriano1">
        	<p class="info_menu_title_600">Меню</p>
         	<ul class="menu_full_600">
                <li class="menu_full_text_600"><img src="/root/600_adriano/pizza.jpg"></li>
                <ul class="menu_full_text_600">
                	<li><center><p><b>Выбери свою пиццу!</b></p></center></li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Pizza “Margherita”.......................................................30 cm</b><b class="price_600">29.00 грн.</b><b class="price_600">32.00 грн.</b></p>
                    	<p>Сыр Моцарелла, томатный соус, специи.</p>
                    </li>
                </ul>
                 <ul class="menu_full_text_600">
                	<li><p><b>Pizza “Parma”................................................................30 cm</b><b class="price_600">39.00 грн.</b><b class="price_600">41.00 грн.</b></p>
                    	<p>Пармская ветчина, шампиньоны, сыр Моцарелла, томатный соус, специи, оливковое масло, помидор, болгарский перец.</p>
                    </li>
                </ul>
                 <ul class="menu_full_text_600">
                	<li><p><b>Pizza “Prosciutto”.........................................................30 cm</b><b class="price_600">35.00 грн.</b><b class="price_600">38.00 грн.</b></p>
                    	<p>Ветчина, шампиньоны, сыр Моцарелла, томатный соус, специи, оливковое масло, помидор, болгарский перец.</p>
                    </li>
                </ul>
                 <ul class="menu_full_text_600">
                	<li><p><b>Pizza “ Filetto”................................................................30 cm</b><b class="price_600">42.00 грн.</b><b class="price_600">45.00 грн.</b></p>
                    	<p>Закрытая мясная пицца (свинина, телятина) с сыром, овощами, красным соусом, оливковым маслом и специями.</p>
                    </li>
                </ul>
                 <ul class="menu_full_text_600">
                	<li><p><b>Pizza “Vitello”................................................................30 cm</b><b class="price_600">41.00 грн.</b><b class="price_600">44.00 грн.</b></p>
                    	<p>Телятина, шампиньоны, сыр Моцарелла, томатный соус, специи, оливковое масло, помидор, болгарский перец.</p>
                    </li>
                </ul>
                 <ul class="menu_full_text_600">
                	<li><p><b>Pizza “Carbonara”........................................................30 cm</b><b class="price_600">37.00 грн.</b><b class="price_600">39.00 грн.</b></p>
                    	<p>Свиной окорок, яйцо, сыр Моцарелла, томатный соус, специи, оливковое масло, помидор, болгарский перец.</p>
                    </li>
                </ul>
                 <ul class="menu_full_text_600">
                	<li><p><b>Pizza “Salame”...............................................................30 cm</b><b class="price_600">36.00 грн.</b><b class="price_600">38.00 грн.</b></p>
                    	<p>Салями, шампиньоны, сыр Моцарелла, томатный соус, специи, оливковое масло, помидор, болгарский перец.</p>
                    </li>
                </ul>
                 <ul class="menu_full_text_600">
                	<li><p><b>Pizza “Calzone”................................................................................30 cm</b><b class="price_600">37.00 грн.</b></p>
                    	<p>Закрытая пицца, со свиным окороком, сыром Моцарелла, , яйцом, грибами, специями и зеленью, оливковое масло, помидор, болгарский перец.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Pizza “Caprisiosa”........................................................30 cm</b><b class="price_600">35.00 грн.</b><b class="price_600">38.00 грн.</b></p>
                    	<p>Курица, шампиньоны, сыр Моцарелла, томатный соус, специи, оливковое масло, помидор, болгарский перец.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Pizza “Cornichon”.........................................................30 cm</b><b class="price_600">36.00 грн.</b><b class="price_600">38.00 грн.</b></p>
                    	<p>Корнишоны, бекон, курица, соус «Болоньез», специи, болгарский перец, оливковое масло.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Pizza “Mixed Super”.....................................................30 cm</b><b class="price_600">38.00 грн.</b><b class="price_600">40.00 грн.</b></p>
                    	<p>Ветчина, салями, курица, шампиньоны, сыр Моцарелла, томатный соус, специи, оливковое масло, помидор, болгарский перец.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Pizza “Caprisiosa Hawai”.............................................30 cm</b><b class="price_600">37.00 грн.</b><b class="price_600">39.00 грн.</b></p>
                    	<p>Ананас, курица, шампиньоны, сыр Моцарелла, томатный соус, специи, оливковое масло, помидор, болгарский перец.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Pizza “Frutti di mare”....................................................30 cm</b><b class="price_600">44.00 грн.</b><b class="price_600">47.00 грн.</b></p>
                    	<p>Морской коктейль, шампиньон, сыр Моцарелла, томатный соус, специи, оливковое масло, помидор, болгарский перец.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Pizza “Crevette”............................................................30 cm</b><b class="price_600">46.00 грн.</b><b class="price_600">49.00 грн.</b></p>
                    	<p>Креветки, шампиньоны, сыр Моцарелла, томатный соус, специи, оливковое масло, помидор, болгарский перец.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Pizza “Caviale”..............................................................30 cm</b><b class="price_600">59.00 грн.</b><b class="price_600">61.00 грн.</b></p>
                    	<p>Мидии, икра лосося, лук, сыр, овощи, специи, оливковое масло.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Pizza “Bianka”................................................................30 cm</b><b class="price_600">44.00 грн.</b><b class="price_600">47.00 грн.</b></p>
                    	<p>Семга, оливки, помидоры, болгарский перец, луковый соус, специи, оливковое масло.</p>
                    </li>
                </ul>
                 <ul class="menu_full_text_600">
                	<li><p><b>Pizza “4 seasons”..........................................................30 cm</b><b class="price_600">37.00 грн.</b><b class="price_600">39.00 грн.</b></p>
                    	<p>Салат, кукуруза, помидоры, шампиньоны, сыр Моцарелла, томатный соус, специи, оливковое масло, болгарский перец.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Pizza al’ Fonghi...............................................................30 cm</b><b class="price_600">29.00 грн.</b><b class="price_600">31.00 грн.</b></p>
                    	<p>Шампиньоны, сыр Моцарелла, томатный соус, специи, оливковое масло, помидор, болгарский перец.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Pizza “Adriano” XXL..........................................................................60 cm</b><b class="price_600">98.00 грн.</b></p>
                    	<p>Состоит из 5 пицц: пицца «Гавайи», Пицца «Микс», Пицца «Моцарелла», пицца «4 сезона», пицца «Prsciutto».</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><center><p><b>Острая пицца:</b></p></center></li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Пицца-острая №1...........................................................30 cm</b><b class="price_600">36.00 грн.</b><b class="price_600">38.00 грн.</b></p>
                    	<p>Итальянские колбаски, помидор, сыр Моцарелла, острый соус, специи, оливковое масло, помидор, болгарский перец.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Pizza-Hot №2...................................................................30 cm</b><b class="price_600">42.00 грн.</b><b class="price_600">44.00 грн.</b></p>
                    	<p>Бастурма, помидор, лук, сыр, Моцарелла, острый соус, специи, оливковое масло, помидор, болгарский перец.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><center><p><b>Десертная пицца:</b></p></center></li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Pizza “Frutta” фруктовая пицца....................................................30 cm</b><b class="price_600">34.00 грн.</b></p>
                    	<p>Слоеное тесто с начинкой из яблок, банана, ананаса, груши, вишни, смородины с добавлением фруктового соуса.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><center><p><b>Дополнительная порция:</b></p></center></li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Помидоры</b><b class="price_600">5.00 грн.</b></p></li>
                    <li><p><b>Грибы</b><b class="price_600">6.00 грн.</b></p></li>
                    <li><p><b>Оливки</b><b class="price_600">5.00 грн.</b></p></li>
                    <li><p><b>Сыр</b><b class="price_600">13.00 грн.</b></p></li>
                    <li><p><b>Фирменный соус</b><b class="price_600">5.00 грн.</b></p></li>
                </ul>
                
                <ul class="menu_full_text_600">
                	<li><p><b>Фирменные соусы:</b></p></li>
                    <li><p><b>Итальянский (острый)....................................................................50г</b><b class="price_600">7.00 грн.</b></p></li>
                    <li><p><b>Барекю (умеренно острый)..........................................................50г</b><b class="price_600">7.00 грн.</b></p></li>
                    <li><p><b>Шпинатный (не острый).................................................................50г</b><b class="price_600">8.00 грн.</b></p></li>
                    <li><p><b>Сырный Рокфор (мягкий).............................................................50г</b><b class="price_600">9.00 грн.</b></p></li>
                </ul>       
            </ul>
		</div> 	
</div>

<?php
}
else
   if ($_GET['pm'] == 11)
   {
?>

<div class="catalogue_item_cont_m">
    <p class="tel_600">(062) 311-59-30</p>
    <div class="pizza_600">
    	<div class="menu_600">
        	<ul>
            	<li> <a href="index.php?business_full=600&amp;pm=1">О нас</a></li>
                <li class="menu_in_600"> <a href="index.php?business_full=600&amp;pm=2">Меню</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=3">Детям</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=4">Доставка</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=5">Адрес</a></li>
            </ul>
        </div>
    </div>
    	<p class="italian_600">Italian restaurant</p>
		<a href="index.php?business_full=600&amp;pm=15" class="postnoe_600"></a>
        <a href="index.php?business_full=600&amp;pm=1"><div class="adriano_600"></div></a>
        <p class="pizza_pasta">pizza and pasta</p>
        <div class="info_adriano1">
        	<p class="info_menu_title_600">Меню</p>
         	<ul class="menu_full_600">
                <li class="menu_full_text_600"><img src="/root/600_adriano/hot.jpg"></li>
                <ul class="menu_full_text_600">
                	<li><p><b>Carne di pollo...........................................................................250/150 гр.</b><b class="price_600">49.00 грн.</b></p>
                    	<p>Куриное филе гриль в беконе, овощи, шампиньоны, специи.</p>
                    </li>
                </ul>
                 <ul class="menu_full_text_600">
                	<li><p><b>Buon Mix...................................................................................200/100 гр.</b><b class="price_600">46.00 грн.</b></p>
                    	<p>Семга запеченная в курином филе с зеленью под гранатовым соусом.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Duck “Adriano”........................................................................380/150 гр.</b><b class="price_600">85.00 грн.</b></p>
                    	<p>Утиная ножка с картофелем по-домашнему.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Tagliatta.....................................................................................170/150 гр.</b><b class="price_600">50.00 грн.</b></p>
                    	<p>Медальоны из телятины, Моцарелла, на подушке из микс-салата, соус Порто.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Bovine “Peperoni”..................................................................170/130 гр.</b><b class="price_600">51.00 грн.</b></p>
                    	<p>Кусочки телятины запеченные с овощами под острым соусом.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Steak “Speck”..........................................................................200/100 гр.</b><b class="price_600">51.00 грн.</b></p>
                    	<p>Стейк из телятины, фаршированный беконом и сельдереем. Подается с Дижонской горчицей.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Steak “Marble”........................................................................200/120 гр.</b><b class="price_600">54.00 грн.</b></p>
                    	<p>Стейк из телятины, свинины и куриного филе под соусом «Деми Глясс».</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Steak “Tartufo”.......................................................................200/120 гр.</b><b class="price_600">59.00 грн.</b></p>
                    	<p>Стейк из телятины подается на горке из шампиньонов и Моцареллой под трюфельным соусом.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Aminicia de’veau......................................................................200/100 гр.</b><b class="price_600">53.00 грн.</b></p>
                    	<p>Филе телятины, соус-крем, белое вино.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Steak-grill “Chateau”..............................................................200/100 гр.</b><b class="price_600">69.00 грн.</b></p>
                    	<p>Филе телятины - гриль  с соусом барбекю.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Trio-Mix.....................................................................................300/100 гр.</b><b class="price_600">69.00 грн.</b></p>
                    	<p>Три мини стейка из телятины, куриного филе и свинины с овощами.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Steak “Chief”...........................................................................200/150 гр.</b><b class="price_600">59.00 грн.</b></p>
                    	<p>Фирменной свиной стейк с бастурмой, беконом и соусом.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Pig-grill.......................................................................................200/80 гр.</b><b class="price_600">49.00 грн.</b></p>
                    	<p>Свиная корейка - гриль.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><center><p><b>Гарниры:</b></p></center></li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Rizotto “Adriano”...........................................................................250 гр.</b><b class="price_600">22.00 грн.</b></p>
                    	<p>Итальянский рис, шампиньоны, сыр, специи.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Rizotto “Verdure”...........................................................................250 гр.</b><b class="price_600">24.00 грн.</b></p>
                    	<p>Итальянский рис, овощной коктейль, сыр, специи.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Rizotto “Frutti di mare”.................................................................250 гр.</b><b class="price_600">33.00 грн.</b></p>
                    	<p>Итальянский рис, морской коктейль, сыр, специи.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Grillae vegetables..........................................................................210 гр.</b><b class="price_600">22.00 грн.</b></p>
                    	<p>Болгарский перец, баклажан, шампиньоны, лук, помидоры.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Boiled potatoes..............................................................................200 гр.</b><b class="price_600">24.00 грн.</b></p>
                    	<p>Отварной картофель со шпинатом и кедровыми орешками.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Potatoes frit.....................................................................................150 гр.</b><b class="price_600">12.00 грн.</b></p>
                    	<p>Картофель фри.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Хлеб порция  ......................................................................................1 шт.</b><b class="price_600">1.50 грн.</b></p></li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Булочка фирменная  .......................................................................1 шт.</b><b class="price_600">2.00 грн.</b></p></li>
                </ul>          
            </ul>
		</div> 	
</div>

<?php
}
else
   if ($_GET['pm'] == 12)
   {
?>

<div class="catalogue_item_cont_m">
    <p class="tel_600">(062) 311-59-30</p>
    <div class="pizza_600">
    	<div class="menu_600">
        	<ul>
            	<li> <a href="index.php?business_full=600&amp;pm=1">О нас</a></li>
                <li class="menu_in_600"> <a href="index.php?business_full=600&amp;pm=2">Меню</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=3">Детям</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=4">Доставка</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=5">Адрес</a></li>
            </ul>
        </div>
    </div>
    	<p class="italian_600">Italian restaurant</p>
		<a href="index.php?business_full=600&amp;pm=15" class="postnoe_600"></a>
        <a href="index.php?business_full=600&amp;pm=1"><div class="adriano_600"></div></a>
        <p class="pizza_pasta">pizza and pasta</p>
        <div class="info_adriano1">
        	<p class="info_menu_title_600">Меню</p>
         	<ul class="menu_full_600">
                <li class="menu_full_text_600"><img src="/root/600_adriano/sea.jpg"></li>
                <ul class="menu_full_text_600">
                	<li><p><b>Persico di mare.........................................................................180/150 гр.</b><b class="price_600">53.00 грн.</b></p>
                    	<p>Морской окунь, морской коктейль, сладкий перец, маслины.</p>
                    </li>
                </ul>
                 <ul class="menu_full_text_600">
                	<li><p><b>Persico verdo...........................................................................180/150 гр.</b><b class="price_600">49.00 грн.</b></p>
                    	<p>Филе морского окуня, овощной коктейль, соус «Голандез», сыр «Пармезан», зелень, специи.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Assorti Grill...............................................................................200/100 гр.</b><b class="price_600">57.00 грн.</b></p>
                    	<p>Шашлычки из семги, судака и овощей, приготовленных на гриле.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Grill-Salmon..............................................................................170/100 гр.</b><b class="price_600">69.00 грн.</b></p>
                    	<p>Стейк семги – гриль с соусом «Голандз».</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Pike perch all verdure.............................................................200/150 гр.</b><b class="price_600">54.00 грн.</b></p>
                    	<p>Судак с овощами, сливками, кедровыми орешками.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Baked Catfish...........................................................................200/150 гр.</b><b class="price_600">49.00 грн.</b></p>
                    	<p>Сом запеченный в фольге. Подается с ризотто.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Tiger crevette-grill “Classic”................................................200/100 гр.</b><b class="price_600">95.00 грн.</b></p>
                    	<p>Тигровые креветки – гриль «классические» с соусом.</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Mussel sauce...........................................................................150/100 гр.</b><b class="price_600">47.00 грн.</b></p>
                    	<p>Мидии под сырно - сливочным соусом с икрой лосося.</p>
                    </li>
                </ul>
                
            </ul>
		</div> 	
</div>

<?php
}
else
   if ($_GET['pm'] == 13)
   {
?>

<div class="catalogue_item_cont_m">
    <p class="tel_600">(062) 311-59-30</p>
    <div class="pizza_600">
    	<div class="menu_600">
        	<ul>
            	<li> <a href="index.php?business_full=600&amp;pm=1">О нас</a></li>
                <li class="menu_in_600"> <a href="index.php?business_full=600&amp;pm=2">Меню</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=3">Детям</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=4">Доставка</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=5">Адрес</a></li>
            </ul>
        </div>
    </div>
    	<p class="italian_600">Italian restaurant</p>
		<a href="index.php?business_full=600&amp;pm=15" class="postnoe_600"></a>
        <a href="index.php?business_full=600&amp;pm=1"><div class="adriano_600"></div></a>
        <p class="pizza_pasta">pizza and pasta</p>
        <div class="info_adriano1">
        	<p class="info_menu_title_600">Меню</p>
         	<ul class="menu_full_600">
                <li class="menu_full_text_600"><img src="/root/600_adriano/deserts.jpg"></li>
                <ul class="menu_full_text_600">
                	<li><p><b>Italian Panna Cotta</b><b class="price_600">24.00 грн.</b></p>
                    	<p>(в ассортименте)</p>
                    </li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Тирамису “Adriano”</b><b class="price_600">28.00 грн.</b></p></li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Чизкейк “Adriano”</b><b class="price_600">28.00 грн.</b></p></li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Яблочный пирог</b><b class="price_600">26.00 грн.</b></p></li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Фирменное ромовое парфе “Adriano”</b><b class="price_600">28.00 грн.</b></p></li>                </ul>
                    <ul class="menu_full_text_600">
                		<li><p><b>Gelato “Assorti” with cream</b><b class="price_600">20.00 грн.</b></p></li>
                    	<p>Сливочно – ореховая нуга, ром, ликер «Куантро», соус.</p>
					</ul>
                    <ul class="menu_full_text_600">
                		<li><p><b>Chocolate mou</b><b class="price_600">19.00 грн.</b></p></li>
                    	<p>Шоколадное мороженое, крем по - итальянски.</p>
					</ul>
                    <ul class="menu_full_text_600">
                		<li><p><b>Peach Melba</b><b class="price_600">21.00 грн.</b></p></li>
                    	<p>Персики, мороженое, сливки, орехи, соус.</p>
					</ul>
                    <ul class="menu_full_text_600">
                		<li><p><b>Banana split</b><b class="price_600">21.00 грн.</b></p></li>
                    	<p>Бананы, мороженое, сливки, орешки, соус.</p>
					</ul>
                    <ul class="menu_full_text_600">
                		<li><p><b>Tutti Frutti cup</b><b class="price_600">22.00 грн.</b></p></li>
                    	<p>Фруктовый салат, мороженое, сливки, орехи, шоколадный соус.</p>
					</ul>
                     <ul class="menu_full_text_600">
                		<li><p><b>Malce Donna with cream</b><b class="price_600">23.00 грн.</b></p></li>
                    	<p>Бананы, апельсины, яблоки, персики, ананасы, киви, соус «Exotic».</p>
					</ul>
                    <ul class="menu_full_text_600">
                		<li><p><b>Adriano shake with cream</b><b class="price_600">20.00 грн.</b></p></li>
                    	<p>Strawberry, bananas, milk, “Malibu” liqueur, cream.</p>
					</ul>
                    
                    <ul class="menu_full_text_600">
                		<li><p><center><b>Орешки</b></center></p></li>
					</ul>
                    
                    <ul class="menu_full_text_600">
                		<li><p><b>Арахис</b><b class="price_600">12.00 грн.</b><b class="price_600">80 гр.</b></p></li>
					</ul>
                    <ul class="menu_full_text_600">
                		<li><p><b>Кешью</b><b class="price_600">12.00 грн.</b><b class="price_600">40 гр.</b></p></li>
					</ul>
                    <ul class="menu_full_text_600">
                		<li><p><b>Миндаль</b><b class="price_600">12.00 грн.</b><b class="price_600">40 гр.</b></p></li>
					</ul>
                    <ul class="menu_full_text_600">
                		<li><p><b>Фисташки</b><b class="price_600">16.00 грн.</b><b class="price_600">40 гр.</b></p></li>
					</ul>
                    <ul class="menu_full_text_600">
                		<li><p><center><b>Фрукты</b></center></p></li>
					</ul>
                    <ul class="menu_full_text_600">
                		<li><p><b>Апельсин</b><b class="price_600">16.00 грн.</b><b class="price_600">100 гр.</b></p></li>
					</ul>
                    <ul class="menu_full_text_600">
                		<li><p><b>Банан</b><b class="price_600">3.50 грн.</b><b class="price_600">100 гр.</b></p></li>
					</ul>
                    <ul class="menu_full_text_600">
                		<li><p><b>Киви</b><b class="price_600">7.00 грн.</b><b class="price_600">1 piece</b></p></li>
					</ul>
                    <ul class="menu_full_text_600">
                		<li><p><b>Яблоко</b><b class="price_600">5.00 грн.</b><b class="price_600">100гр.</b></p></li>
					</ul>
                    <ul class="menu_full_text_600">
                		<li><p><b>Груша</b><b class="price_600">6.00 грн.</b><b class="price_600">100гр.</b></p></li>
					</ul>
                    <ul class="menu_full_text_600">
                		<li><p><b>Лимон</b><b class="price_600">5.00 грн.</b><b class="price_600">100гр.</b></p></li>
					</ul>
                    <ul class="menu_full_text_600">
                		<li><p><b>Фреш (Апельсин, грейпфрут)</b><b class="price_600">20.00 грн.</b><b class="price_600">200гр.</b></p></li>
					</ul>
            </ul>
		</div> 	
</div>

<?php
}
else
   if ($_GET['pm'] == 14)
   {
?>

<div class="catalogue_item_cont_m">
    <p class="tel_600">(062) 311-59-30</p>
    <div class="pizza_600">
    	<div class="menu_600">
        	<ul>
            	<li> <a href="index.php?business_full=600&amp;pm=1">О нас</a></li>
                <li class="menu_in_600"> <a href="index.php?business_full=600&amp;pm=2">Меню</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=3">Детям</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=4">Доставка</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=5">Адрес</a></li>
            </ul>
        </div>
    </div>
    	<p class="italian_600">Italian restaurant</p>
		<a href="index.php?business_full=600&amp;pm=15" class="postnoe_600"></a>
        <a href="index.php?business_full=600&amp;pm=1"><div class="adriano_600"></div></a>
        <p class="pizza_pasta">pizza and pasta</p>
        <div class="info_adriano1">
        	<p class="info_menu_title_600">Меню</p>
         	<ul class="menu_full_600">
                <li class="menu_full_text_600"><img src="/root/600_adriano/drinks.jpg"></li>
                <ul class="menu_full_text_600">
                		<li><p><center><b>Горячие напитки</b></center></p></li>
				</ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Кофе итальянский эспрессо</b><b class="price_600">12.90 грн.</b></p></li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Кофе Американо</b><b class="price_600">12.90 грн.</b></p></li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Капуччино</b><b class="price_600">15.00 грн.</b></p></li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Капуччино “Adriano”</b><b class="price_600">17.00 грн.</b></p></li>
                    <p>(Сливки, шоколад)</p>
                </ul>
                 <ul class="menu_full_text_600">
                	<li><p><b>Ирландский кофе</b><b class="price_600">22.00 грн.</b></p></li>
                    <p>(Виски Red Label, сливки)</p>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Кофе Mocca Mexica</b><b class="price_600">20.00 грн.</b></p></li>
                    <p>(с корицей, мускатным орехом, сливками)</p>
                </ul>
                 <ul class="menu_full_text_600">
                	<li><p><b>Кофе Mocca</b><b class="price_600">20.00 грн.</b></p></li>
                    <p>(Ликер «Куантро», сливки)</p>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Холодный кофе «Гляссе»</b><b class="price_600">19.00 грн.</b></p></li>
                    <p>(с мороженым на выбор)</p>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Чай Herbert листовой</b><b class="price_600">12.00 грн.</b></p></li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Чай в ассортименте</b><b class="price_600">14.00 грн.</b></p></li>
                </ul>
                <ul class="menu_full_text_600">
                		<li><p><center><b>Напитки</b></center></p></li>
				</ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Сок Rich</b><b class="price_600">14.00 грн.</b><b class="price_600">0.21 </b></p></li>
                    <p>(в ассортименте)</p>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Натуральный лимонад</b><b class="price_600">8.00 грн.</b><b class="price_600">0.25 </b></p></li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Тоник Schweppes</b><b class="price_600">13.00 грн.</b><b class="price_600">0.5 </b></p></li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Coca-cola, Sprite, Fanta</b><b class="price_600">9.00 грн.</b><b class="price_600">0.25 </b></p></li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Минеральная вода “Bonaqua”</b><b class="price_600">8.00 грн.</b><b class="price_600">0.5 </b></p></li>
                    <p>(газ., негаз.)</p>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Минеральная вода “Narzan”</b><b class="price_600">20.00 грн.</b><b class="price_600">0.5 </b></p></li>
                    <p>(слабогазированная)</p>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Минеральная вода “Borjomi”</b><b class="price_600">22.00 грн.</b><b class="price_600">0.5 </b></p></li>
                    <p>(газ.)</p>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Минеральная вода “Evian”</b><b class="price_600">21.00 грн.</b><b class="price_600">0.33 </b></p></li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Минеральная вода “Morshinska”</b><b class="price_600">9.00 грн.</b><b class="price_600">0.5 </b></p></li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Минеральная вода “Morshinska”</b><b class="price_600">15.00 грн.</b><b class="price_600">0.5 </b></p></li>
                    <p>(стекло)</p>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Холодный чай “Nestea”</b><b class="price_600">15.00 грн.</b><b class="price_600">0.5 </b></p></li>
                </ul>
                <ul class="menu_full_text_600">
                	<li><p><b>Burn</b><b class="price_600">23.00 грн.</b><b class="price_600">0.25 </b></p></li>
                </ul>
                
            </ul>
		</div> 	
</div>
<?php
}
else
   if ($_GET['pm'] == 15)
   {
?>

<div class="catalogue_item_cont_m">
    <p class="tel_600">(062) 311-59-30</p>
    <div class="pizza_600">
    	<div class="menu_600">
        	<ul>
            	<li> <a href="index.php?business_full=600&amp;pm=1">О нас</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=2">Меню</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=3">Детям</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=4">Доставка</a></li>
                <li> <a href="index.php?business_full=600&amp;pm=5">Адрес</a></li>
            </ul>
        </div>
    </div>
    	<p class="italian_600">Italian restaurant</p>
		<a href="index.php?business_full=600&amp;pm=15" class="postnoe_600"></a>
        <a href="index.php?business_full=600&amp;pm=1"><div class="adriano_600"></div></a>
        <p class="pizza_pasta">pizza and pasta</p>
        <div class="info_adriano1">
        	<p class="info_menu_title_600">Акции</p>
	<img src="root/img/banner13_adriano.jpg" id="border_brown">
	
	<p id="text_bold_red">БУДЕМ РАДЫ ВСТРЕТИТЬ ВАС  В ЗАВЕДЕНИИ У НАС !</p>
       </div> 	
</div>

<?php
   } 
?>
<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="index.php?section_id=32&amp;business=1">Категория:</a></div>
</div>
<div class="catalogue_item_cont">
<a href="index.php?section_id=2&amp;business=1">бизнес</a>
 / 
<a href="index.php?section_id=32&amp;business=1">предприятия</a>
 / 
<a href="index.php?section_id=389&amp;business=2">отдых и развлечения</a>
 / 
<a href="index.php?section_id=390&amp;business=2">кафе и рестораны</a>
</div>


<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="">Фотогалерея:</a></div>
</div>
<div class="catalogue_item_cont">
<div class="catalogue_pic_l"><a href="root/600_adriano/gallery/1.jpg" target="_blank"><img src="root/600_adriano/gallery/1_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/600_adriano/gallery/2.jpg" target="_blank"><img src="root/600_adriano/gallery/2_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/600_adriano/gallery/3.jpg" target="_blank"><img src="root/600_adriano/gallery/3_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/600_adriano/gallery/4.jpg" target="_blank"><img src="root/600_adriano/gallery/4_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/600_adriano/gallery/5.jpg" target="_blank"><img src="root/600_adriano/gallery/5_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/600_adriano/gallery/6.jpg" target="_blank"><img src="root/600_adriano/gallery/6_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/600_adriano/gallery/7.jpg" target="_blank"><img src="root/600_adriano/gallery/7_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/600_adriano/gallery/8.jpg" target="_blank"><img src="root/600_adriano/gallery/8_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/600_adriano/gallery/9.jpg" target="_blank"><img src="root/600_adriano/gallery/9_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/600_adriano/gallery/13.jpg" target="_blank"><img src="root/600_adriano/gallery/13_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/600_adriano/gallery/10.jpg" target="_blank"><img src="root/600_adriano/gallery/10_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/600_adriano/gallery/11.jpg" target="_blank"><img src="root/600_adriano/gallery/11_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/600_adriano/gallery/12.jpg" target="_blank"><img src="root/600_adriano/gallery/12_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/600_adriano/gallery/14.jpg" target="_blank"><img src="root/600_adriano/gallery/14_s.jpg" width="60" height="60" border="0" alt=""></a></div>
</div>
<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="">Контактная информация:</div>
</div>
 <div class="catalogue_item_cont">
 		 <table width="100%">
			<tbody>
 			<tr>
			<!--	<td><img class="main_sec_image" src="" width="60" height="60" border="0" alt="" /></td>-->
				<td>Адрес:</td>
				<td>Телефон:</td>
				<td>Факс:</td>
				<td>E-mail:</td>
				<td>Веб-сайт:</td>
			</tr>
			<tr>
				<td>г. Донецк<br> ул. Артема, 108</td>
				<td>(062)311-59-30</td>
				<td></td>
				<td></td>
				<td></td>

			</tr>
			</tbody> 
		 </table> 		
	 </div>
</div>

