 <div class="catalogue_item_c">
<style>

html,body{}

.catalogue_item_c a {color: #000000;}

.catalogue_item_cont p {
color:#000000;
text-align:justify;
text-indent:0px;
line-height:20px;
margin:0px; 
}

img.main_sec_image {
border:none;
}
.catalogue_item_cont_m {
background: url("../root/msite/maximum/main.png") no-repeat scroll 100% 0 transparent;
background-color:#000000;
border:1px solid lightgray;
color:#000000;
margin:0;
margin:15px 10px 10px;
width:980px;
height:1000px;
}
.catalogue_item_cont {
background-color:#ffffff;
border-top:1px solid lightgray;
margin:0 0 7px 10px;
width:980px;
color:#000000;

}
.catalogue_item_c {
background-color:#F3F3F3;
font-family: century gotic;
}

a.menu_text {color:#858585;
font-family:arial;
font-size:36px;
font-weight:bold;
text-shadow: 0 0 0.15em #851b1b, 0 0 0.15em #851b1b,
        0 0 0.15em #851b1b;}

a.menu_text:hover {text-decoration:none;color:#ee1c24;text-shadow: 0 0 0.15em #ffffff, 0 0 0.15em #ffffff,
        0 0 0.15em #ffffff;}

img.main_sec_image {
height:240px;
padding:0;
width:240px;
}

#mm_menu, #mm_menu_1 {position:relative;left:610px;width:225px;text-align:center;}

#mm_menu_1 {color:#ffffff;
font-family:arial;
font-size:30px;
font-weight:bold;
text-shadow: 0 0 0.25em #ff3333, 0 0 0.25em #ff3333,
        0 0 0.25em #ff3333;}

.catalogue_item_cont a {
color:#000000;
}
.catalogue_item_cont a:hover {
color:#000000;
text-decoration:underline;
}
.catalogue_item_mp_a {
left:3px;
position:relative;
}

.catalogue_pic_l_1 {
width:120px;}

td.ttable {color:#FFF;font-weight:bold;font-size:12px;border:1px solid #ff0000;vertical-align:top;}

td.mtext {background-color:#787878;height: 20px;
color:#222222;
font-size:12px;
max-width:166px;
padding:5px 10px;
text-align:left;
width:166px;
border-bottom:1px solid;}

@media all and (-webkit-min-device-pixel-ratio:10000),
not all and (-webkit-min-device-pixel-ratio:0) {
  a.menu_text {font-size:34px;}
  #mm_menu_1 {font-size:28px;}
}
</style>
<?php
if ($_GET['pm'] == 1) 
{
?>

<div class="catalogue_item_cont_m">
<div id="mm_menu" style="left:70px;top:480px;"><a href="index.php?business_full=401&amp;pm=1"  class="menu_text"><b>ПАБ</b></a></div>
<div id="mm_menu" style="left:365px;top:439px;"><a href="index.php?business_full=401&amp;pm=2" class="menu_text">БИЛЬЯРД</a></div>
<div id="mm_menu" style="left:605px;top:399px;"><a href="index.php?business_full=401&amp;pm=3" class="menu_text">БОУЛИНГ</a></div>
<div id="mm_menu_1" style="left:80px;top:415px;">О НАС</div>
<table cellspacing="0" cellpadding="0" style="left:133px;position:relative;top:444px;width:700px;">
    <tr><td class="mtext" style="">Резервирование столиков в пабе и дорожек в боулинге <br>(050) 368-60-66
    </td><td rowspan="3" style="color:#FFFFFF;font-size:12px;line-height:20px;padding:0 0 0 35px;text-align:justify;vertical-align:top;"><font style="font-weight:bold;font-size:18px;color:#666666;">Боулинг центр «Максимум»</font> <br>&nbsp;&nbsp;&nbsp;&nbsp;- это самый крупный боулинг - центр в Донецке (12 дорожек) с современным оборудованием  «Qubika AMF». В боулинг - центре  есть прилегающие функциональные зоны: бильярд («Американка» и «Русский») и ПАБ.
        <br>&nbsp;&nbsp;&nbsp;&nbsp;Наш персонал создаст Вам атмосферу уюта и комфорта для приятного  отдыха: бармены предложат широкий ассортимент свежего пива и оригинальных коктейлей, а Шеф-повар - новые эксклюзивные блюда. Так же Вас ждут прямые трансляция спортивных и музыкальных программ.
        <br>&nbsp;&nbsp;&nbsp;&nbsp;Мы приятно удивим Вас вечеринками, конкурсами, турнирами и подарками.
        <br>&nbsp;&nbsp;&nbsp;&nbsp;Желаете играть с достойными соперниками? - Приходите и участвуйте в профессиональном или любительском турнире и покажите свой класс.
        <br>&nbsp;&nbsp;&nbsp;&nbsp;К вашим услугам  организация оригинальных корпоративов, банкетов или детских дней рождений. Мы придем на помощь вместе с профессиональными ведущими, ди-джеями и аниматорами.
        <br><font style="color:#ff3333;font-size:16px;font-weight:bold;">Позволь себе отдых по - МАКСИМУМу!</font>
    </td>        
    </tr>
    <tr><td class="mtext">Офис <br>(062) 206-62-32</td></tr>
    <tr><td class="mtext">Администратор  боулинга <br>(062) 206-60-66
<br><br><font style="color:#ffffff;">Работа с коммерческими предложениями: Арт-директор Екатерина art-dir@es.olimp.ua
<br><br>Как нас найти:
<br>г.Донецк, Ворошиловский район, ул.Артема 130,
<br>ТРЦ «Донецк Сити», 4 этаж
<br><a href="http://www.maximym.dn.ua">www.maximym.dn.ua</a></font></td></tr>
</table>
<div style="left: 110px; position: relative; top: 465px;"><font style="color:#ff3333;font-size:16px;font-weight:bold;">(062)206-60-66</font></div>
</div>
 <?php
}
else
   if ($_GET['pm'] == 2)
   {
?>
<div class="catalogue_item_cont_m">
<div id="mm_menu" style="left:70px;top:480px;"><a href="index.php?business_full=401&amp;pm=1"  class="menu_text"><b>ПАБ</b></a></div>
<div id="mm_menu" style="left:365px;top:439px;"><a href="index.php?business_full=401&amp;pm=2" class="menu_text">БИЛЬЯРД</a></div>
<div id="mm_menu" style="left:605px;top:399px;"><a href="index.php?business_full=401&amp;pm=3" class="menu_text">БОУЛИНГ</a></div>
<div id="mm_menu_1" style="left:80px;top:415px;">О НАС</div>
<table cellspacing="0" cellpadding="0" style="left:133px;position:relative;top:444px;width:700px;">
    <tr><td class="mtext" style="">Резервирование столиков в пабе и дорожек в боулинге <br>(050) 368-60-66
    </td><td rowspan="3" style="color:#FFFFFF;font-size:14px;line-height:20px;padding:0 0 0 35px;text-align:justify;vertical-align:top;"><font style="font-weight:bold;font-size:18px;color:#666666;">Бильярд</font>
    <br>Количество столов - 2:
    <br>1. Русская Пирамида -  48 грн/час
    <br>2. Пул (американка) -39 грн/час
    <br>Наличие БАРа;
    <br>Заказ меню из ПАБа;
    </td>
    </tr>
    <tr><td class="mtext">Офис <br>(062) 206-62-32</td></tr>
    <tr><td class="mtext">Администратор  боулинга <br>(062) 206-60-66
<br><br><font style="color:#ffffff;">Работа с коммерческими предложениями: Арт-директор Екатерина art-dir@es.olimp.ua
<br><br>Как нас найти:
<br>г.Донецк, Ворошиловский район, ул.Артема 130,
<br>ТРЦ «Донецк Сити», 4 этаж
<br><a href="http://www.maximym.dn.ua">www.maximym.dn.ua</a></font></td></tr>
</table>
</div>
 <?php
}
else
   if ($_GET['pm'] == 3)
   {
?>
<div class="catalogue_item_cont_m" style="height:1500px;background: url(../root/msite/maximum/main_1.png) no-repeat scroll 100% 0 #000;">
<div id="mm_menu" style="left:70px;top:480px;"><a href="index.php?business_full=401&amp;pm=1"  class="menu_text"><b>ПАБ</b></a></div>
<div id="mm_menu" style="left:365px;top:439px;"><a href="index.php?business_full=401&amp;pm=2" class="menu_text">БИЛЬЯРД</a></div>
<div id="mm_menu" style="left:605px;top:399px;"><a href="index.php?business_full=401&amp;pm=3" class="menu_text">БОУЛИНГ</a></div>
<div id="mm_menu_1" style="left:80px;top:415px;">О НАС</div>
<table cellspacing="0" cellpadding="0" style="left:133px;position:relative;top:444px;width:700px;">
    <tr><td class="mtext" style="">Резервирование столиков в пабе и дорожек в боулинге <br>(050) 368-60-66
    </td><td rowspan="4" style="color:#FFFFFF;font-size:14px;line-height:20px;padding:0 0 0 35px;text-align:justify;vertical-align:top;"><font style="font-weight:bold;font-size:18px;color:#666666;">Боулинг</font>
    <ul style="padding-left:15px;">
        <li>12 дорожек ведущей американской компании Qubica АМF</li>
        <li>Помощь  инструктора - бесплатно</li>
        <li>Для Вас постоянно проходят всевозможные вечеринки, акции, розыгрыши и конечно же боулинг -  турниры (как среди любителей так и среди профессионалов)</li>
        <li>У нас Вы можете отпраздновать любой праздник, будь то  День Рождения, корпоративное мероприятие или просто праздник «души»</li>
    </ul><br>
    <table cellspacing="0" cellpadding="0" style="width:100%;text-align:center;">
        <tr><td class="ttable" colspan="8" style="font-size:16px;">Прейскурант цен на игру в боулинг с<br> 15.09.11г</td></tr>
        <tr><td class="ttable" colspan="8" style="font-size:16px;">1-12 дорожка грн./час</td></tr>
        <tr><td class="ttable" colspan="8"><br></td></tr>
        <tr style="height:30px;">
			<td class="ttable">Время</td>
			<td class="ttable">ПН</td>
			<td class="ttable">ВТ</td>
			<td class="ttable">СР</td>
			<td class="ttable">ЧТ</td>
			<td class="ttable">ПТ</td>
			<td class="ttable">СБ,<br>ПРАЗДНИКИ</td>
			<td class="ttable">ВС</td>
		</tr>
        <tr style="height:30px;">
			<td class="ttable" colspan="8"><br></td>
		</tr>
        <tr style="height:30px;">
			<td class="ttable">(10:00)<br><b>11:00-19:00</b></td>
			<td class="ttable">75</td>
			<td class="ttable">75</td>
			<td class="ttable">75</td>
			<td class="ttable">75</td>
			<td class="ttable">75</td>
			<td class="ttable">135</td>
			<td class="ttable">135</td>
		</tr>
        <tr style="height:30px;">
			<td class="ttable"><br></td>
			<td class="ttable">1мин-<br>1,25грн</td>
			<td class="ttable">1мин-<br>1,25грн</td>
			<td class="ttable">1мин-<br>1,25грн</td>
			<td class="ttable">1мин-<br>1,25грн</td>
			<td class="ttable">1мин-<br>1,25грн</td>
			<td class="ttable">1мин-<br>2,25грн</td>
			<td class="ttable">1мин-<br>2,25грн</td>
		</tr>
        <tr style="height:30px;">
			<td class="ttable" colspan="8"><br></td>
		</tr>
        <tr style="height:30px;">
			<td class="ttable"><b>19:00-03:00</b><br><b>(05:00)</b></td>
			<td class="ttable">141</td>
			<td class="ttable">141</td>
			<td class="ttable">141</td>
			<td class="ttable">141</td>
			<td class="ttable">189</td>
			<td class="ttable">189</td>
			<td class="ttable">171</td>
		</tr>
        <tr style="height:30px;">
			<td class="ttable"><br></td>
			<td class="ttable">1мин-<br>2,35грн</td>
			<td class="ttable">1мин-<br>2,35грн</td>
			<td class="ttable">1мин-<br>2,35грн</td>
			<td class="ttable">1мин-<br>2,35грн</td>
			<td class="ttable">1мин-<br>3,15грн</td>
			<td class="ttable">1мин-<br>3,15грн</td>
			<td class="ttable">1мин-<br>2,85грн</td>
		</tr>
        <tr style="height:30px;">
			<td class="ttable" colspan="8"><br></td>
		</tr>
        <tr style="height:30px;">
			<td class="ttable" style="vertical-align:middle;">Школьники и<br>студенты</td>
			<td class="ttable" colspan="6">45<br>1мин-0,75грн<br><b>(С 11:00 – 19:00)</b></td>
			<td class="ttable">75<br>1мин-1,25грн<br><b>(до 16:00)</b></td>
		</tr>
        <tr style="height:30px;">
			<td class="ttable" colspan="8" style="vertical-align:middle;font-size:14px;text-align:left;padding:4px;">Одноразовые носки для боулинга
 – 1,50 грн/пара</td>
 		</tr>
	    </table>
    </td>
    </tr>
    <tr><td class="mtext">Офис <br>(062) 206-62-32</td></tr>
    <tr><td class="mtext">Администратор  боулинга <br>(062) 206-60-66
<br><br><font style="color:#ffffff;">Работа с коммерческими предложениями: Арт-директор Екатерина art-dir@es.olimp.ua
<br><br>Как нас найти:
<br>г.Донецк, Ворошиловский район, ул.Артема 130,
<br>ТРЦ «Донецк Сити», 4 этаж
<br><a href="http://www.maximym.dn.ua">www.maximym.dn.ua</a></font></td></tr>
     <tr><td><br></td></tr>
</table>
</div>
<?php
   } 
?>



<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="index.php?section_id=32&amp;business=1">Категория:</a></div>
</div>
<div class="catalogue_item_cont">
<a href="index.php?section_id=2&amp;business=1">бизнес</a>
 / 
<a href="index.php?section_id=32&amp;business=1">предприятия</a>
 / 
<a href="index.php?section_id=389&amp;business=2">отдых и развлечения</a>
 / 
<a href="index.php?section_id=421&amp;business=2">развлекательные комплексы</a>
</div>


<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
Фотогалерея:</div>
</div>
<div class="catalogue_item_cont">
<div class="catalogue_pic_l"><a href="root/msite/maximum/gallery/1.jpg" target="_blank"><img src="root/msite/maximum/gallery/1_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/maximum/gallery/2.jpg" target="_blank"><img src="root/msite/maximum/gallery/2_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/maximum/gallery/3.jpg" target="_blank"><img src="root/msite/maximum/gallery/3_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/maximum/gallery/4.jpg" target="_blank"><img src="root/msite/maximum/gallery/4_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/maximum/gallery/5.jpg" target="_blank"><img src="root/msite/maximum/gallery/5_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/maximum/gallery/6.jpg" target="_blank"><img src="root/msite/maximum/gallery/6_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/maximum/gallery/7.jpg" target="_blank"><img src="root/msite/maximum/gallery/7_s.jpg" width="60" height="60" border="0" alt=""></a></div>
</div>
<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
Контактная информация:</div>
</div>
 <div class="catalogue_item_cont">
 		 <table width="100%">
			<tbody>
 			<tr>
			<!--	<td><img class="main_sec_image" src="" width="60" height="60" border="0" alt="" /></td>-->
				<td>Адрес:</td>
				<td>Телефон:</td>
				<td>Факс:</td>
				<td>E-mail:</td>
				<td>Веб-сайт:</td>
			</tr>
			<tr>
				<td>г. Донецк, ул.Артема, 130</td>
				<td>(062)206-60-66</td>
				<td></td>
				<td>maximym@es.olimp.ua</td>
				<td>www.maximym.dn.ua</td>

			</tr>
			</tbody> 
		 </table> 		
	 </div>
</div>  

