 <div class="catalogue_item_c">
<style>

html,body{}

.catalogue_item_c a {color: #000000;}

.catalogue_item_cont p {
color:#000000;
text-align:justify;
text-indent:0px;
line-height:20px;
margin:0px; 
}

img.main_sec_image {
border:none;
}
.catalogue_item_cont_m {
background-color:#FFFFFF;
border:1px solid lightgray;
color:#000000;
margin:0;
margin:15px 10px 10px;
width:980px;
}
.catalogue_item_cont {
background-color:#ffffff;
border-top:1px solid lightgray;
margin:0 0 7px 10px;
width:980px;
color:#000000;

}
.catalogue_item_c {
background-color:#F3F3F3;
font-family: century gotic;
}

a.menu_text {font-size:18px;font-weight:bold;color:#ffffff;}

img.main_sec_image {
height:240px;
padding:0;
width:240px;
}

.catalogue_item_cont a {
color:#000000;
}
.catalogue_item_cont a:hover {
color:#000000;
text-decoration:underline;
}
.catalogue_item_mp_a {
left:3px;
position:relative;
}

#m_menuu {left:80px;
position:relative;
top:-197px;
width:100px;}

#m_menuu td {float:left;
height:60px;
line-height:30px;
vertical-align:middle;
width:200px;
text-align:center;}
table.menu_d td a {font-size:16px;font-weight:bold;color:#ffffcc;text-shadow: -1px 0 black, 0 1px black, 1px 0 black, 0 -1px black;font-style:italic;}
table.menu_d td:hover a{text-decoration:underline;}

#gl_table {width:100%;}
#td1, td3{width:100px;}
#td1 {background:url('../root/msite/shubin/left_f.png') no-repeat 100% 0;height:110px;}
#td3 {background:url('../root/msite/shubin/right_f.png') no-repeat 100% 0;height:110px;}
#td2 {width:770px;background-color:#fecb32;text-align:center;font-size:14px;font-style:italic;font-weight:bold;padding-top:40px;}
#td2_2 {background-color:#fecb32;}
#paper {background:url("../root/msite/shubin/paper.png") no-repeat scroll 100% 0 #fecb32;height:584px;margin-left:10px;width:760px;}
#td3_2 {background:url('../root/msite/shubin/right.png') repeat 100% 0;}
#td1_2 {background:url('../root/msite/shubin/left.png') repeat 100% 0;}

td#i_up {font-weight:bold;text-align:left;color:#280200;}
td#i_up1 {font-weight:bold;text-decoration:underline;}
td#i_first, td#i_first_w {width:300px;text-align:left;font-weight:bold;font-size:16px;color:#280200;padding: 10px 0;}
td#i_first_w {padding:0;}
td#i_second {width:100px;font-weight:bold;font-size:14px;color:#280200;text-align:center;padding-left:10px;}
table#i_table tr {}

.catalogue_pic_l_1 {
width:120px;}
</style>
<?php
if ($_GET['pm'] == 1) 
{
?>

<div class="catalogue_item_cont_m">
<div style="height:228px;">
 <img src="root/msite/shubin/logo.png" />
 <table cellpadding="0" cellspacing="0" class="menu_d" id="m_menuu"><tr>
  <td><a href="index.php?business_full=400&pm=1">MAIN</a></td>
  <td><a href="index.php?business_full=400&pm=2">MENU</a></td>
  <td><a href="index.php?business_full=400&pm=3">CONTACTS</a></td> 
 </tr></table> 
</div>
<div>
<table cellpadding="0" cellspacing="0" id="gl_table">
 <tr>
 <td id="td1"></td>
 <td id="td2">Bierkraft private brewery in “Dobriy Shubin” pub & brewery<br/> If you are a Beer Connoisseur, then you should visit our private brewery! </td>
 <td id="td3"></td>
 </tr>
 <tr>
 <td id="td1_2"></td><td id="td2_2" style="text-align:justify;padding:10px;font-size:14px;"><b>&nbsp;&nbsp;&nbsp;&nbsp;“Dobriy Shubin” pub & brewery</b> has three halls: the main hall or “Pub”, “Brewery” and “Hunting hall”.The capacity is <b>80 seats</b>.
 <br>&nbsp;&nbsp;&nbsp;&nbsp;<b>“PUB” The main hall</b><br>&nbsp;&nbsp;&nbsp;&nbsp;On entering this hall you find yourself in classic pub with oak furniture. You can always have a good time here, as we also offer a delightful evenings of live music and different themes parties. Beer is always foaming in a mug, the companion’s eyes twinkle, and in the shade you notice the masked smile of the host (a respectable man in Donetsk) – Dobriy Shubin.
 <br>&nbsp;&nbsp;&nbsp;&nbsp;<b>Brewery</b><br>&nbsp;&nbsp;&nbsp;&nbsp;Beer is supposed to be one of the most man’s favorite drinks.<br>&nbsp;&nbsp;&nbsp;&nbsp;For centuries the ancient drink had been brewed by our ancestor. Today you stand a great chance to see the beer brewing process, as mini brewery is situated in this hall and you can observe beer making and then taste this nectarous drink. However, beer tasting has its peculiarity: you’ll have an opportunity to pour as much beer, as you can drink.
 <br>&nbsp;&nbsp;&nbsp;&nbsp;<b>Hunting hall (Non-smoking Section)</b><br>&nbsp;&nbsp;&nbsp;&nbsp;This hall has a very relaxed atmosphere, with soft live music, Trophy Hunter on the wall . However, you have only to say a word and the atmosphere will be transformed: the tables are groaned with food and you celebrate the holiday with your friends and relatives. <b>Seating Capacity: 25 seats.</b>
 <br>
 <img src="root/msite/shubin/mm_logo.png" style="padding:10px;" />
 </td><td id="td3_2"></td>
 </tr>
 <tr>
 <td id="td1_2"></td><td id="td2_2"><div id="paper"><span style="color:#280200;font-size:16px;font-weight:bold;"><br><br><br><br><i>The fairy-tale: How Beer strength conquered Military strength<br>Or<br>What is the origin of our beer name? “Bierkraft” –Beer strength</i></span>
 <br><div style="color:#280200;font-size:14px;padding:10px 70px;text-align:justify;">&nbsp;&nbsp;&nbsp;&nbsp;At all tames the Slavs have been glorious by heroic power and maiden beauty. Even in North Country of strong Teutons and Normans people knew about the strict Scythian laws and unearthly beauty of their Slavic girls.
 <br>&nbsp;&nbsp;&nbsp;&nbsp;Once Germanic chief decided to win the heart of obstinate girl with dark blond plait and heart of the warrior. He wanted to win considerable respect of the tribe with the help of a sword, but the local bogatyrs were stronger. He tried to assert his rights in fisticuff, but his strength betrayed him. Than he decided to get top with the help of ginger drink that stood high in Teuton’s esteem. 
 <br>&nbsp;&nbsp;&nbsp;&nbsp;The Rhenish warrior brewed foam beer and started to treat Slavic bogatyrs, but they didn’t become tipsy. Although they liked the bitterish taste of this drink, and rumors began to ooze out that the Teuton was as weak as his drink. Then the enraged warrior promised to show the real Beer Strength. He spilt the drink on the oak bench and filled the empty mugs. And bogatyrs couldn’t rise to their feets, the beer strength didn’t let them get under way. Since that time beer became the most favourite drink of our ancestors; people started to check strength and quality of beer in such a way: <b>“strong beer sticks to pants”. “Bierkraft”</b>, - said once the oversea warrior to his Slavic wife; <b>“the real beer strength”, -</b> say we today.
 <br>&nbsp;&nbsp;&nbsp;&nbsp;It's up to you to decide,whether it is a fairytale or a true story. The only thing is that the best brewers even today conceal the gingery gleam in their hair, and the secret of brewing in their hearts. 
 </div>
 </div></td><td id="td3_2"></td>
 </tr>
</table>
</div>
</div>
 <?php
}
else
   if ($_GET['pm'] == 2)
   {
?>
<div class="catalogue_item_cont_m">
<div style="height:228px;">
 <img src="root/msite/shubin/logo.png" />
 <table cellpadding="0" cellspacing="0" class="menu_d" id="m_menuu"><tr>
  <td><a href="index.php?business_full=400&pm=1">MAIN</a></td>
  <td><a href="index.php?business_full=400&pm=2">MENU</a></td>
  <td><a href="index.php?business_full=400&pm=3">CONTACTS</a></td> 
 </tr></table> 
</div>
<div>
<table cellpadding="0" cellspacing="0" id="gl_table">
 <tr>
 <td id="td1_2"></td><td id="td2_2" style="text-align:justify;padding:10px;width:760px;">
 <br>
<table style="width:750px;padding:0 20px;" id="i_table">
    <tr>
        <td id="i_first"></td>
        <td id="i_second">WEIGHT, g</td>
        <td id="i_second">PRICE, UAH</td>
    </tr>
    <tr>
        <td id="i_first">Beer “Crispy” platter <font style="font-size:10px;"><i>NEW!</i></font><font style="font-size:12px;"><br>(cheese, mushrooms, chicken wings
au gratin with spices)</font></td>
        <td id="i_second">540/100</td>
        <td id="i_second">110-00</td>
    </tr>
    <tr>
        <td id="i_first">«Hopping»<font style="font-size:12px;"><br>(A big platter with fried pork-loin, vegetables,  cole-slaw, onion, fries, pickled sweet pepper,  grilled mushrooms, grilled zucchini, eggplants.  Served with sauce.)  </font></td>
        <td id="i_second">500/740/1 unit/100/15</td>
        <td id="i_second">190-00</td>
    </tr>
    <tr>
        <td id="i_first">«Guy's party»<font style="font-size:12px;"><br> (Lots of roasted marinated Pork Loin with                                                                                                                                     Fried onion, Marinated Garlic) </font></td>
        <td id="i_second">1000/200/100/10</td>
        <td id="i_second">340-00</td>
    </tr>
    <tr>
     <td colspan=3><img src="root/msite/shubin/menu_1.png"></td>
     </tr>
    <tr>
        <td id="i_first">«Slavic Tradition»<font style="font-size:12px;"><br> (Marinated pork neck stuffed with garlic and carrot.                                                                                              Served with baked potato and bacon)</font></td>
        <td id="i_second">1100/800/50/50</td>
        <td id="i_second">310-00</td>
    </tr>
    <tr>
        <td id="i_first">Frankfurters with sauerkraut <font style="font-size:12px;"><br>(The dish is prepared in keeping with the best German                                                                                                  traditions: Mixed Sausages, 3 kind if sauces, sauerkraut)</font></td>
        <td id="i_second">580/150/200</td>
        <td id="i_second">160-00</td>
    </tr>
    <tr>
     <td colspan=3><img src="root/msite/shubin/menu_2.png"></td>
     </tr>
    <tr>
        <td id="i_first">Duck with spicy glaze<font style="font-size:12px;"><br>(Served with sauerkraut ) </font></td>
        <td id="i_second">1 portion/ 2 portions/150</td>
        <td id="i_second">220-00</td>
    </tr>
    <tr>
        <td id="i_first">Meat Mix for three<font style="font-size:12px;"><br> (Three kinds of meat steaks: chicken fillet,                                                                                                         veal loin,pork loin, roasted in beer-batter. Served with onion and fresh tomatoes,adjika sauce and mustard )</font></td>
        <td id="i_second">450/60/112/100</td>
        <td id="i_second">120-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:22px;padding:15px 0;">SALADS<br></td></tr>
    <tr>
        <td id="i_first">Greek salad<font style="font-size:12px;"><br>(Fresh tomatoes, cucumber, sweet pepper, cheese, olives,
   red onions, mixed salad, olive sauce)</font></td>
        <td id="i_second">215</td>
        <td id="i_second">32-00</td>
    </tr>
    <tr>
        <td id="i_first">Vegetable salad<font style="font-size:12px;"><br>(Fresh cucumbers, sweet pepper, tomatoes, salad oil)</font></td>
        <td id="i_second">200</td>
        <td id="i_second">16-00</td>
    </tr>
    <tr>
        <td id="i_first">Salad with fried shrimps<font style="font-size:10px;"><i>NEW!!!</i></font><font style="font-size:12px;"><br> (Mix of lettuce, tomatoes, fried shrimps with breadcrumbs 
and dressing) </font></td>
        <td id="i_second">180</td>
        <td id="i_second">43-00</td>
    </tr>
        <tr>
        <td id="i_first">Sea – breeze salad<font style="font-size:12px;"><br>(Cuttlefish, shrimp meat, mussels, fresh tomatoes, cucumbers,
   Onions, olive oil)</font></td>
        <td id="i_second">150</td>
        <td id="i_second">40-00</td>
    </tr>
            <tr>
        <td id="i_first">Crispy Salad<font style="font-size:12px;"><br> (Nappa cabbage, smoked chicken fillet, croutons
   Sweet pepper, mayonnaise sauce)</font></td>
        <td id="i_second">195</td>
        <td id="i_second">20-00</td>
    </tr>
                <tr>
        <td id="i_first">Sesame Chicken Salad<font style="font-size:12px;"><br>(Fried sesame chicken, served with salad,                                                                                                                      fresh tomatoes and cucumbers. Dressed with olive oil)  </font></td>
        <td id="i_second">230</td>
        <td id="i_second">34-00</td>
    </tr>
                    <tr>
        <td id="i_first">Beer Baron <font style="font-size:12px;"><br> (Boiled chicken fillet, fried mushrooms, herring , tomatoes,                   
    Pickled cucumber, cheese, mayonnaise sauce)  </font></td>
        <td id="i_second">200</td>
        <td id="i_second">25-00</td>
    </tr>
        <tr>
        <td id="i_first">Caesar Salad<font style="font-size:12px;"><br> (chicken fillet, croutons,  eggs, ham, cheese,  tomatoes, 
     mayonnaise sauce,lettuce)</font></td>
        <td id="i_second">250</td>
        <td id="i_second">42-00</td>
    </tr>
    <tr>
        <td id="i_first">Prussian Salad<font style="font-size:12px;"><br>(Fried pork, tomatoes, cucumber, sweet pepper, Feta cheese, 
    Red onion, lettuce, olive oil)</font></td>
        <td id="i_second">240</td>
        <td id="i_second">40-00</td>
    </tr>
        <tr>
        <td id="i_first">Bogatyr Salad<font style="font-size:12px;"><br>(chicken fillet, ham, boiled tongue, mushrooms , cucumbers,                                                                                                mayonnaise sauce)</font></td>
        <td id="i_second">250</td>
        <td id="i_second">32-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:22px;padding:15px 0;">First courses<br></td></tr>
    <tr>
        <td id="i_first">Solyanka</td>
        <td id="i_second">300/20</td>
        <td id="i_second">20-00</td>
    </tr>
    <tr>
        <td id="i_first">Quail Soup</td>
        <td id="i_second">300/0,5unit</td>
        <td id="i_second">29-00</td>
    </tr>
    <tr>
        <td id="i_first">Chicken bouillon with giblets<font style="font-size:10px;"><i>New!!!</i></font><font style="font-size:12px;"><br>(chicken hearts, gizzards)</font></td>
        <td id="i_second">300/10/2unit</td>
        <td id="i_second">13-00</td>
    </tr>
    <tr>
        <td id="i_first">Country Soup<font style="font-size:12px;"><br> (Spicy soup with minced meat balls, beans and roast bacon)</font></td>
        <td id="i_second">380</td>
        <td id="i_second">20-00</td>
    </tr>
    <tr>
        <td id="i_first">Traditional Ukranian Borsch<font style="font-size:12px;"><br>(Served with sour cream, bacon and garlic)</font></td>
        <td id="i_second">350/25/10</td>
        <td id="i_second">25-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:22px;padding:15px 0;">Meat dishes<br></td></tr>
    <tr>
        <td id="i_first">Sudarushka Chicken<font style="font-size:12px;"><br> (Chicken fillet with paprika and tomatoes is baked                                                                                                            with cheese and mayonnaise sauce )</font></td>
        <td id="i_second">230</td>
        <td id="i_second">38-00</td>
    </tr>
    <tr>
        <td id="i_first">«Fried quail»</td>
        <td id="i_second">2/50</td>
        <td id="i_second">86-00</td>
    </tr>
    <tr>
        <td id="i_first">Veal Steak<font style="font-size:12px;"><br> ( Served on a toast with fried courgettes) </font></td>
        <td id="i_second">150/170/1unit/40</td>
        <td id="i_second">64-00</td>
    </tr>
    <tr>
        <td id="i_first">Veal with crispy onions</font></td>
        <td id="i_second">175/100</td>
        <td id="i_second">61-00</td>
    </tr>
    <tr>
        <td id="i_first">Peppery  Veal<font style="font-size:12px;"><br>(Veal medallions with spicy oil, served with baked
       vegetables)</font></td>
        <td id="i_second">150/130/2</td>
        <td id="i_second">69-00</td>
    </tr>
    <tr>
        <td id="i_first">Lamb Ribs with flavoring herbs</td>
        <td id="i_second">300/10</td>
        <td id="i_second">73-00</td>
    </tr>
    <tr>
        <td id="i_first">Lamb ribs with vegetables<font style="font-size:12px;"><br>(Marinated lamb chop, stewed in red sauce                                                                                                                                                                   Served with fried vegetables)</font></td>
        <td id="i_second">250/100/10</td>
        <td id="i_second">93-00</td>
    </tr>
    <tr>
        <td id="i_first">Pork ribs with garlic-cream sour sauce<font style="font-size:12px;"><br> (Baked pork ribs, marinated with flavoring herbs.
        Served with sauce and fried onion)</font></td>
        <td id="i_second">250/50/2</td>
        <td id="i_second">62-00</td>
    </tr>
    <tr>
        <td id="i_first">Foreshank<font style="font-size:12px;"><br>(Baked pork ribs, served with spicy carrot and cabbage)</font></td>
        <td id="i_second">1unit/60/250</td>
        <td id="i_second">102-00</td>
    </tr>
    <tr>
        <td id="i_first">Tiagi</td>
        <td id="i_second">175/50/50</td>
        <td id="i_second">54-00</td>
    </tr>
    <tr>
        <td id="i_first">Duet<font style="font-size:12px;"><br> (Grilled pork-loin, dressed with Sesame and mustard
        Served with spicy eggplants tomatoes and lettuce)</font></td>
        <td id="i_second">170/140</td>
        <td id="i_second">56-00</td>
    </tr>
    <tr>
        <td id="i_first">Special steak with bones! <font style="font-size:12px;"><br>  (two bone-in steaks, stuffed with bacon and onion) </font></td>
        <td id="i_second">360/50</td>
        <td id="i_second">83-00</td>
    </tr>
    <tr>
        <td id="i_first">Timeout<font style="font-size:12px;"><br> (Pork loin, fillets of beef, stewed with eggplants. served with fries and onion )</font></td>
        <td id="i_second">360</td>
        <td id="i_second">70-00</td>
    </tr>
    <tr>
        <td id="i_first">Meat Cake<font style="font-size:10px;"><i>New!</i></font><font style="font-size:12px;"><br>( Pork -loin roll with bacon, served with grilled vegetables and potato cakes)</font></td>
        <td id="i_second">200/170/70</td>
        <td id="i_second">62-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:22px;padding:15px 0;">Vegetable and Fish Dishes<br></td></tr>
    <tr>
        <td id="i_first">Mixed vegetables<font style="font-size:12px;"><br>   (Stewed vegetables: eggplants, zucchini, sweet pepper,                                                                                                                                 mushrooms, onions) </font></td>
        <td id="i_second">200</td>
        <td id="i_second">29-00</td>
    </tr>
    <tr>
        <td id="i_first"> Natural Sea Beauty<font style="font-size:12px;"><br> (Baked red-finned mullet fillet with zucchini and carrot)  </font></td>
        <td id="i_second">220</td>
        <td id="i_second">35-00</td>
    </tr>
    <tr>
        <td id="i_first">Fried  goatfish<font style="font-size:10px;"><i>New!</i></font></td>
        <td id="i_second">400/50</td>
        <td id="i_second">69-00</td>
    </tr>
    <tr>
        <td id="i_first">Salmon  steak with vegetables<font style="font-size:12px;"><br> (Grilled Big Salmon Steak served with vegetables) </font></td>
        <td id="i_second">200/130/30/30/6</td>
        <td id="i_second">98-00</td>
    </tr>
    <tr>
        <td id="i_first">Grilled halibut with vegetables<font style="font-size:12px;"><br>(Grilled halibut steak, marinated in spices                                                                                                                      and lemon juice. Served with vegetables and lemon)</font></td>
        <td id="i_second">130/100/30</td>
        <td id="i_second">85-00</td>
    </tr>
    <tr>
        <td id="i_first">«Fish blues»<font style="font-size:12px;"><br>(Baked Halibut steak with seafoods.                                                                                                                            Served with vegetables)</font></td>
        <td id="i_second">290/30</td>
        <td id="i_second">88-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:22px;padding:15px 0;">Cold appetizers<br></td></tr>
    <tr>
        <td id="i_first_w"> Beer straw</td>
        <td id="i_second">100</td>
        <td id="i_second">17-00</td>
    </tr>
    <tr>
        <td id="i_first_w">Boiled shrimps</td>
        <td id="i_second">180/20</td>
        <td id="i_second">45-00</td>
    </tr>
    <tr>
        <td id="i_first_w">Fried shrimps</td>
        <td id="i_second">180/20</td>
        <td id="i_second">45-00</td>
    </tr>
    <tr>
        <td id="i_first_w">Salty salmon</td>
        <td id="i_second">100/30</td>
        <td id="i_second">49-00</td>
    </tr>
    <tr>
        <td id="i_first_w">smoked  humpback salmon</td>
        <td id="i_second">100/10</td>
        <td id="i_second">33-00</td>
    </tr>
    <tr>
        <td id="i_first_w">Oily fish</td>
        <td id="i_second">80/20</td>
        <td id="i_second">26-00</td>
    </tr>
    <tr>
        <td id="i_first_w">Makhan (horse meat sausages)</td>
        <td id="i_second">100</td>
        <td id="i_second">42-00</td>
    </tr>
    <tr>
        <td id="i_first_w">Spicy horse slices</td>
        <td id="i_second">100</td>
        <td id="i_second">44-00</td>
    </tr>
    <tr>
        <td id="i_first_w">Beef Jerky</td>
        <td id="i_second">100</td>
        <td id="i_second">31-00</td>
    </tr>
    <tr>
        <td id="i_first_w">Toasts with herring</td>
        <td id="i_second">50/50</td>
        <td id="i_second">10-00</td>
    </tr>
    <tr>
        <td id="i_first_w">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;with salted bacon</td>
        <td id="i_second">50/50</td>
        <td id="i_second">10-00</td>
    </tr>
    <tr>
        <td id="i_first_w">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; smoked bacon</td>
        <td id="i_second">50/50</td>
        <td id="i_second">10-00</td>
    </tr>
    <tr>
        <td id="i_first_w">smoked cheese</td>
        <td id="i_second">100</td>
        <td id="i_second">22-00</td>
    </tr>
    <tr>
        <td id="i_first_w">hunter sausages</td>
        <td id="i_second">100</td>
        <td id="i_second">23-00</td>
    </tr>
    <tr>
        <td id="i_first_w">Kuban  roach </td>
        <td id="i_second">1portion</td>
        <td id="i_second">60-00</td>
    </tr>
    <tr>
        <td id="i_first_w">Caspian roach with hard roe</td>
        <td id="i_second">1portion</td>
        <td id="i_second">40-00</td>
    </tr>
    <tr>
        <td id="i_first_w">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;without hard roe</td>
        <td id="i_second">1portion</td>
        <td id="i_second">30-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:22px;padding:15px 0;">Other cold appetizers<br></td></tr>
    <tr>
        <td id="i_first_w">Overbank<font style="font-size:10px;"><i>NEW!</i></font><font style="font-size:12px;"><br> (blintzes with salmon with cheese)  </font></td>
        <td id="i_second">150/35</td>
        <td id="i_second">31-00</td>
    </tr>
    <tr>
        <td id="i_first_w">Herring</td>
        <td id="i_second">115/70/30</td>
        <td id="i_second">17-00</td>
    </tr>
    <tr>
        <td id="i_first_w">Cheese platter<font style="font-size:12px;"><br> (DorBlue, Gauda, Ramzes cheeses)</font></td>
        <td id="i_second">75/75/75/ 14</td>
        <td id="i_second">60-00</td>
    </tr>
    <tr>
        <td id="i_first_w">Boiled tongue with mayonnaise sauce</font></td>
        <td id="i_second">100/30/20/20</td>
        <td id="i_second">35-00</td>
    </tr>
    <tr>
        <td id="i_first"><font style="font-size:18px;">Chief's Menu:</font><font style="font-size:12px;">(advance order)</font></td>
        <td id="i_second"></td>
        <td id="i_second"></td>
    </tr>
    <tr>
        <td id="i_first_w">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Homemade baked ham</td>
        <td id="i_second">100/30</td>
        <td id="i_second">33-00</td>
    </tr>
    <tr>
        <td id="i_first_w">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Chicken sausage</td>
        <td id="i_second">120/30</td>
        <td id="i_second">29-00</td>
    </tr>
    <tr>
        <td id="i_first_w">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Homemade Sausage</td>
        <td id="i_second">100/30</td>
        <td id="i_second">33-00</td>
    </tr>
    <tr>
        <td id="i_first_w">Lemon with sugar </td>
        <td id="i_second">35/15</td>
        <td id="i_second">2-00</td>
    </tr>
    <tr>
        <td id="i_first_w">Olives (portion)</td>
        <td id="i_second">75/10</td>
        <td id="i_second">19-00</td>
    </tr>
    <tr>
        <td id="i_first_w">Vegetables:(tomato, cucumber, sweet pepper) </td>
        <td id="i_second">100</td>
        <td id="i_second">6-00</td>
    </tr>
    <tr>
        <td id="i_first_w">Greens</td>
        <td id="i_second">50</td>
        <td id="i_second">15-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:22px;padding:15px 0;">Hot Appetizers<br></td></tr>
      <tr>
        <td id="i_first">Mixed sausages<font style="font-size:12px;"><br>Two kinds of sausages: chicken and pork.                                                                                                               Served with different kinds of sauces and marinated vegetables )</font></td>
        <td id="i_second">320/150/95</td>
        <td id="i_second">73-00</td>
    </tr>
    <tr>
        <td id="i_first">Spicy sausages<font style="font-size:12px;"><br>  (Served with potato and pickled tomato) </font></td>
        <td id="i_second">200/100/100/50</td>
        <td id="i_second">69-00</td>
    </tr>
    <tr>
        <td id="i_first">Onion rings</td>
        <td id="i_second">110/30/30</td>
        <td id="i_second">38-00</td>
    </tr>
    <tr>
        <td id="i_first">Tiger shrimps<font style="font-size:12px;"><br> (Fried tiger shrimps with garlic and 	spices)</font></td>
        <td id="i_second">5unit/30/35</td>
        <td id="i_second">98-00</td>
    </tr>
    <tr>
        <td id="i_first">“Dobriy Shubin” Wings <font style="font-size:12px;"><br>(Fried Marinated chicken wings) </font></td>
        <td id="i_second">250/50</td>
        <td id="i_second">29-00</td>
    </tr>
    <tr>
        <td id="i_first">«Crazy Wings»<font style="font-size:12px;"><br> ( Barbecued Chicken wings ,dipped in mustard,  marinated in herbs)</font></td>
        <td id="i_second">200/50</td>
        <td id="i_second">29-00</td>
    </tr>
    <tr>
        <td id="i_first">Cool Wings<font style="font-size:12px;"><br> ( Fried Spicy Wings with Paprichi
Sauce, sprinkled with bread crumbs)</font></td>
        <td id="i_second">250/50</td>
        <td id="i_second">29-00</td>
    </tr>
    <tr>
        <td id="i_first">Splendid Wings<font style="font-size:12px;"><br> ( Fried Chicken wings with adjika sauce and Chili sauce)</font></td>
        <td id="i_second">250/100</td>
        <td id="i_second">29-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:22px;padding:15px 0;">Smoked dishes<br></td></tr>
    <tr>
        <td id="i_first">Piggy scream<font style="font-size:12px;"><br> Smoked  Pig's ears</font></td>
        <td id="i_second">1unit</td>
        <td id="i_second">28-00</td>
    </tr>
    <tr>
        <td id="i_first">Meat fan<font style="font-size:12px;"><br> smoked ribs</font></td>
        <td id="i_second">300/30/30</td>
        <td id="i_second">58-00</td>
    </tr>
 </table>
 </td><td id="td3_2"></td>
 </tr> 
</table>
</div>
</div>
<?php
}
else
   if ($_GET['pm'] == 3)
   {
?>

<div class="catalogue_item_cont_m">
<div style="height:228px;">
 <img src="root/msite/shubin/logo.png" />
 <table cellpadding="0" cellspacing="0" class="menu_d" id="m_menuu"><tr>
  <td><a href="index.php?business_full=400&pm=1">MAIN</a></td>
  <td><a href="index.php?business_full=400&pm=2">MENU</a></td>
  <td><a href="index.php?business_full=400&pm=3">CONTACTS</a></td> 
 </tr></table> 
</div>
<div>
<table cellpadding="0" cellspacing="0" id="gl_table">
 <tr>
 <td id="td1"></td><td id="td2" style="font-size:11px;padding:15px 0 0 10px;text-align:justify;">Adress: Donetsk city, Marii Ulianovoi St. 65a<br>Phone: (0622) 95-15-58<br>Working hours: 12.00-23.00<br></td><td id="td3"></td>
 </tr>
 <tr>
 <td id="td1_2"></td><td id="td2_2"><div id="YMapsID" style="height:450px;margin-left:10px;width:760px;"></div></td><td id="td3_2"></td> 
 </tr>
</table>
</div>

<script src="http://api-maps.yandex.ru/1.1/index.xml?key=AAmDzUsBAAAARkVWCAIAXzMCgKN58_MQUqB134Sdp-unCH0AAAAAAAAAAACbJlz2mcKc4anRgbxx6LBZ5BHPyg==" type="text/javascript"></script>
    <script type="text/javascript">
        window.onload = function () {
            var map = new YMaps.Map(document.getElementById("YMapsID"));
            map.setCenter(new YMaps.GeoPoint(37.840335,48.004222), 14);

            var content = document.createElement('span');
            content.innerHTML = "«Dobriy Shubin»";
            map.openBalloon(new YMaps.GeoPoint(37.840335,48.004222), content);

            map.addControl(new YMaps.ToolBar());
            map.addControl(new YMaps.Zoom());
            map.addControl(new YMaps.MiniMap());
            map.addControl(new YMaps.ScaleLine());
        }
    </script>


	 
</div>  
    

<?php
   } 
?>



<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="index.php?section_id=32&amp;business=1">Category:</a></div>
</div>
<div class="catalogue_item_cont">
<a href="index.php?section_id=456&amp;business=1">Business</a>
 / 
<a href="index.php?section_id=616&amp;business=1">Enterprises</a>
 / 
<a href="index.php?section_id=619&amp;business=2">Recreation facilities</a>
 / 
<a href="index.php?section_id=622&amp;business=2">Restaurants, cafes, pubs</a>
</div>


<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
Gallery:</div>
</div>
<div class="catalogue_item_cont">
<div class="catalogue_pic_l"><a href="root/msite/shubin/gallery/1.jpg" target="_blank"><img src="root/msite/shubin/gallery/1_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/shubin/gallery/2.jpg" target="_blank"><img src="root/msite/shubin/gallery/2_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/shubin/gallery/3.jpg" target="_blank"><img src="root/msite/shubin/gallery/3_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l catalogue_pic_l_1"><a href="root/msite/shubin/gallery/7.jpg" target="_blank"><img src="root/msite/shubin/gallery/7_s.jpg" width="120" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l catalogue_pic_l_1"><a href="root/msite/shubin/gallery/8.jpg" target="_blank"><img src="root/msite/shubin/gallery/8_s.jpg" width="120" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/shubin/gallery/15.jpg" target="_blank"><img src="root/msite/shubin/gallery/15_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/shubin/gallery/16.jpg" target="_blank"><img src="root/msite/shubin/gallery/16_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/shubin/gallery/17.jpg" target="_blank"><img src="root/msite/shubin/gallery/17_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/shubin/gallery/18.jpg" target="_blank"><img src="root/msite/shubin/gallery/18_s.jpg" width="60" height="60" border="0" alt=""></a></div>
</div>
<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
Contacts:</div>
</div>
 <div class="catalogue_item_cont">
 		 <table width="100%">
			<tbody>
 			<tr>
			<!--	<td><img class="main_sec_image" src="" width="60" height="60" border="0" alt="" /></td>-->
				<td>Adress:</td>
				<td>Telephone:</td>
				<td>Fax:</td>
				<td>E-mail:</td>
				<td>Website:</td>
			</tr>
			<tr>
				<td>Donetsk city,<br>Marii Ulianovoi St. 65a</td>
				<td>(0622) 95-15-58</td>
				<td></td>
				<td></td>
				<td></td>

			</tr>
			</tbody> 
		 </table> 		
	 </div>
</div>  

