<style type="text/css">
<!--
.стиль1 {font-weight: bold}
-->
</style>
<div class="catalogue_item_c">

<style>



<!--

.folding{cursor:hand;font-weight:bold}

-->



img {

border:none;	

}



b {

	

}



.acc {

}

#acc {

	list-style: none outside none;

    margin: 0 auto 40px;

    width: 480px;

}



.acc-section {

background: white;

margin: 0px;

overflow: hidden;

}



#acc .acc-content {

    border-style: none solid solid;

}



element.style {

height: 0px;

}



div {

	display:block;

}



p {

	font-family:Arial, Helvetica, sans-serif;

	font:Arial, Helvetica, sans-serif;

}



h3 {

display:block;

}



a {

	text-decoration:none;

	border:none;

}



.sequ_conteiner{

	width:100%;

}



.sequ_up { 

height:105 px;

width:100%;

position:relative;

float:left;

margin:0;

background:#264c7b;

}



.sequ_p_up_2 {

	color:#FFF;

	font-size:20 px;

	text-align:justify;

	line-height: 1 px;

	letter-spacing: 2 px;

}



.sequ_p_up_3 {

	color:#FFF;

	font-size:16 px;

	text-align:justify;

	line-height: 1 px;

	letter-spacing: 5 px;

}



.sequ_stroke {

width: 100%;

background-color:#edecea;

height:33px;

text-align:right;

padding:0;

position:relative;

float:left;

margin: -10 0 0 0;

}



.sequ_main_menu {

	position:relative;

	float:left;

	min-height:458;

	max-height:458;

	height:100%;

	background-color:#264c7b;

	padding:5px;

}

/*onas*/

.sequ_a_1 {

	width:135px;

	position:relative;

	float:right;

	margin-right:6px;

}

/*uslu*/

.sequ_a_2 {

	width:135px;

	position:relative;

	float:right;

	margin-right:6px;

	

}

/*kont*/

.sequ_a_3 {

	width:135px;

	position:relative;

	float:right;

	

}



.sequ_podmain{

width:955px;

height:20px;

position:relative;

float:left;

left:20px;

padding:5px;

background-color:#264c7b;

color:#FFF;

font-family:Arial, Helvetica, sans-serif;

font-size:13px;

text-align:center;

}



.sequ_text {

	width:100%;

	position:relative;

	float:left;

	text-indent: 20px;

}



.sequ_footer {

	width:990px;

	height:35;

	position:relative;

	float:left;

	background-color:#264c7b;

	color:#000;

	font-family:Tahoma, Geneva, sans-serif;

	font-size:14px;

	text-align:right;

	padding:5px;

}

#logo_laska {
				width:976px;
				height:160px;
				background-repeat:no-repeat;
				margin:0 auto 0 auto;
			}		
#logo_laska p {padding:0; margin:0;} 


#onas_laska    {
				margin:30px auto 0 auto;
				width:900px;				
				}
#onas_laska p {
				font-size:18px;
				font-family:Helvetica;
				margin:5px 5px 10px 0;
				text-align:justify;
				}
#onas_laska a {font-family:Helvetica; color:#06F; font-size:20px;}				
#onas_laska a:hover {font-family:Helvetica; color:#06F; text-decoration:none; font-size:20px;}	

#uslugi_laska_1 {
					width:900px; 
					background-color:#e0d5ca; 
					margin:15px auto 10px auto; 
					overflow:hidden;
				}
#uslugi_laska_1 p {padding:25px 0 10px 15px;}
#uslugi_laska_1 a {text-decoration:none; color:#000;}
#uslugi_laska_1 a:hover {text-decoration:underline;}
#display_laska_1 {display:none;}
#display_laska_1 p {padding:3px 15px 10px 10px; text-align:justify; font-size:18px;}

#uslugi_laska_2    {
					margin:10px 0 0 0; 
					width:900px; 
					background-color:#e0d5ca; 
					margin:15px auto 10px auto; 
					overflow:hidden;
					}					
#uslugi_laska_2 a {text-decoration:none; color:#000;}
#uslugi_laska_2 a:hover {text-decoration:underline;}
#uslugi_laska_2 p {padding:25px 0 10px 15px;}
#display_laska_2 {display:none;}
#display_laska_2 p {padding:3px 15px 10px 10px; text-align:justify; font-size:18px;}

.стиль1 {
	font-size: 13px;
	font-weight: bold;
	color: #FFFFFF;
}

.стиль4 {
	font-size: 24px;
	font-weight: bold;
}

</style>

<?php

if ($_GET['pm'] == 1) 

{

?>

<script language="javascript" type="text/javascript">
	function show_hide(objectID){
		var object=document.getElementById(objectID);
		if (object.style.display=='none')
			object.style.display='block';
			else
			object.style.display='none';
			return;
	}
</script>

<div class="catalogue_item_cont_m"> 

<table width="1000" height="280" border="0" align="center" cellpadding="0" cellspacing="0" background="../root/msite/laska/top.png">
  <tr>
    <td height="166" colspan="2" valign="top"><div align="right">
      <table width="434" border="0">
          <tr>
            <td width="428" height="121" valign="top"><table width="383" border="0" cellpadding="0" cellspacing="0" align="center">
              <tr>
                <td width="387"><div align="center"><span class="стиль1">&nbsp;<br />
				  Работаем:<br />
                  в будние дни: с 9:00 до 20:00<br />
                  суббота, воскресенье<br />
                  и праздничные дни: с 9:00 - до 15:00<br />
                  Адрес: Донецк, ул. Панфилова, 6 <br />
                  Телефон: (062) 345-56-71, 348-16-59 <br />
                  моб.: - (095)258-73-31</span></div></td>
              </tr>
            </table>              
              <p align="center" class="стиль1"></td>
          </tr>
          </table>
    </div></td>
    <td height="166" valign="top"><div align="right" class="стиль1"> “ Люди с хорошими зубами всё находят смешным” *    
      О. де Бальзак  *</div></td>
  </tr>
  <tr>
    <td width="272"><table width="272" height="104" border="0">
      <tr>
        <td background="../root/msite/laska/about.png"><div align="center"><span class="стиль4"><a href="index.php?business_full=520&pm=1">О НАС</span></div></td>
      </tr>
    </table></td>
    <td width="357">
      <div align="right">
        <table width="272" height="104" border="0">
            <tr>
              <td background="../root/msite/laska/serv.png"><div align="center" class="стиль4"><a href="index.php?business_full=520&pm=2">УСЛУГИ</div></td>
            </tr>
                  </table>
      </div></td>
    <td width="351"><div align="right">
      <table width="272" height="104" border="0">
          <tr>
            <td background="../root/msite/laska/sale.png"><div align="center" class="стиль4">
              <p>АКЦИИ</p>
              </div></td>
          </tr>
          </table>
    </div></td>
  </tr>
</table>
                    
                   
                    <div style="margin:0 auto 0 auto; width:990px; border:3px solid #85aef9; background-color:#fff4e9; background-image:url(../root/msite/laska/content_bg_laska.jpg); background-position:bottom; background-repeat:no-repeat;" >
                    	<div id="onas_laska">
                        <img src="../root/msite/laska/onaspic_laska.jpg" style="float:left; margin-right:20px; border:2px solid #85aef9;" alt="Приватная стоматология ласка. ПС Ласка. Донецк"/>
                        <p>«<strong>ПС ЛАСКА</strong>» <strong>стоматологическая клиника в Донецке</strong> одна из самых крупных  успешно осуществляет свою деятельность с 1990 года. Все эти годы клиника динамично развивается и накапливает опыт, неизменно совершенствуя свои технологии.</p>
<p>
Сегодня <strong>приватная стоматология Ласка</strong> это многопрофильная  <strong>стоматологическая клиника в Донецке</strong>, оснащенная современным оборудованием ведущих фирм производителей мира (DUR DENTAL, BIEN-AIR CATTANI,FARO),что дает возможность замкнуть всю технологическую цепочку от компьютерной диагностики до конечного результата. Здесь всегда окажут квалифицированную помощь. <strong>Детская стоматология</strong>, <strong>лечение кариеса</strong> (фотополимерные пломбы, серебряная и золотая амальгама), <strong>удаление зубов</strong> и <strong>имплантация зубов</strong>, <strong>безметалловая керамика</strong>,<strong> керамические виниры</strong>   и <strong>ортопедические конструкции</strong> из циркония, <strong>лечение пародонтоза</strong>, <strong>брекет</strong> - система, <strong>отбеливание зубов</strong>, вот не полный перечень наших возможностей.</p>
<p>Мы говорим по-английски, что позволяет общаться с иностранными пациентами без посторонней помощи.</p>
                        </div>
                        
                        <div id="uslugi_laska_1">
                        
                        		<div style="float:left; height:120px; width:300px; text-align:center; font-size:18px; font-family:Helvetica;">
                                	<a href="javascript:show_hide('display_laska_1')"><img src="../root/msite/laska/pic_laska_1.jpg" style="padding:10px 5px 10px 5px; float:left; " border="0" alt="Имплантация зубов в Донецке. Приватная стоматология ЛАСКА" /></a> 
                                	<br /><h3><a href="javascript:show_hide('display_laska_1')">Имплантация<br /> зубов в<br /> Донецке</a></h3>
                        		</div>
                               <div style="float:left; height:120px; width:300px; text-align:center; font-size:18px; font-family:Helvetica;">
                                	<a href="javascript:show_hide('display_laska_1')"><img src="../root/msite/laska/pic_laska_2.jpg" style="padding:10px 5px 10px 5px; float:left; " border="0"  alt=">Консультация профессионалов. Приватная стоматология ЛАСКА" /></a> 
                                	<h3 style="padding-top:35px;"><a href="javascript:show_hide('display_laska_1')">Консультация<br />Профессионалов</a></h3>
                               </div>
                                <div style="float:left; height:120px; width:300px; text-align:center; font-size:18px; font-family:Helvetica;">
                                	<a href="javascript:show_hide('display_laska_1')"><img src="../root/msite/laska/pic_laska_3.jpg" style="padding:10px 5px 10px 5px; float:left; " border="0" alt=">Пародонтология. Приватная стоматология ЛАСКА. Донецк" /></a> 
                                	<h3 style="padding-top:45px;"><a href="javascript:show_hide('display_laska_1')">Пародонтология</a></h3>
                                </div>
                            
                             <div id="display_laska_1">
                             	 <div style="float:left; width:300px;">
                                 <p><strong>Имплантация зубов в Донецке</strong> активно развивается.</p> 
                                 <p>«<strong>ПС Ласка</strong>» имеет оснащенный самым современным оборудованием хирургический кабинет. Прием ведет ассистент кафедры хирургической стоматологии челюстно-лицевой хирург. Сегодня в арсенале хирурга стоматолога огромный выбор имплантатов различных производителей (VITAPLANT, U-IMPL-Украина, MIS- Израиль, ANKILOS-Германия, BIOGORIZONT-Америка). Помочь разобраться и сделать правильный выбор вам помогут в нашей клинике. По Вашему желанию мы можем пригласить любого хирурга имплантолога, которому Вы доверяете. Гибкая ценовая политика  <strong>приватной стоматологии</strong> "<strong>ЛАСКА</strong>" даст возможность подобрать оптимальное лечение для Вас. Бережное удаление зубов и любая амбулаторная операция будет проведена быстро и качественно. </p>
                            	</div>
                                <div style="float:left; width:300px;">
                                <p>Понимая возложенную на нас ответственность, мы тщательно следим за соблюдением всех технологий и специфики используемых нами материалов. Важнейшим принципом работы является Ваша безопасность. Мы гарантируем инфекционный контроль. В «<strong>ПС Ласка</strong>» работают высококлассные специалисты, которые регулярно проходят курсы повышения квалификации, как на Украине, так и за рубежом. Кроме этого мы приглашаем ведущих специалистов из других стран для консультаций наших пациентов и проведения мастер-класса для наших докторов. Так в 2007 году в стоматологической клинике "<strong>Ласка</strong>" вел консультативный прием врач пародонтолог из Голландии Д-р Ян Ва Хойве. В 2008 году наши пациенты имели возможность получить консультацию доктора ортопеда  высшей категории из Израиля Бориса Фридмана.</p>
                            	</div>
                                <div style="float:left; width:300px;">
                               <p><strong>Пародонтология в Донецке</strong>. Одна из самых распространенных проблем  у современного человека это пародонтоз (пародонтит). «<strong>ПС Ласка</strong>» с 1990 года занимается изучением и лечением этого грозного заболевания. Доктора нашей стоматологической клиники принимали активное участие в разработке  ополаскивателей и гелей  фирмы «БИОКОН» на основе пиявки для <strong>лечения пародонтоза</strong>. Мы имеем огромный опыт ведения пациентов с проблемами пародонтоза и  отработанные годами специальные методики лечения различных видов этого заболевания. <strong>Приватная стоматология « Ласка</strong>» использует хирургические и не хирургические методы лечения. Современный аппарат ВЕКТОР позволяет повысить эффективность лечения и сохранить даже те зубы, которые раньше считались безнадежными.</p>
                            	</div>	
                             </div>               
                    
                        
                        
                   
					
 </div>
  				  <div id="uslugi_laska_2">
                        
                        		<div style="float:left; height:120px; width:300px; text-align:center; font-size:18px; font-family:Helvetica;">
                                	<a href="javascript:show_hide('display_laska_2')"><img src="../root/msite/laska/pic_laska_4.jpg" style="padding:10px 5px 10px 5px; float:left; " border="0" alt="Детская стоматология в Донецке. Приватная стоматология ЛАСКА. Донецк"/></a> 
                                	<br /><h3><a href="javascript:show_hide('display_laska_2')">Детская<br />стоматология<br />в Донецке</a></h3>
                        		</div>
                               <div style="float:left; height:120px; width:300px; text-align:center; font-size:18px; font-family:Helvetica;">
                                	<a href="javascript:show_hide('display_laska_2')"><img src="../root/msite/laska/pic_laska_5.jpg" style="padding:10px 5px 10px 5px; float:left; " border="0" alt="Ортодонтия в Донецке. Приватная стоматология ЛАСКА. Донецк" /></a> 
                                	<h3 style="padding-top:35px;"><a href="javascript:show_hide('display_laska_2')">Ортодонтия<br />в Донецке</a></h3>
                               </div>
                                <div style="float:left; height:120px; width:300px; text-align:center; font-size:18px; font-family:Helvetica;">
                                	<a href="javascript:show_hide('display_laska_2')"><img src="../root/msite/laska/pic_laska_6.jpg" style="padding:10px 5px 10px 5px; float:left; " border="0" alt="Эстетическая реставрация. Приватная стоматология ЛАСКА. Донецк" /></a> 
                                	<h3 style="padding-top:35px;"><a href="javascript:show_hide('display_laska_2')">Эстетическая<br />реставрация</a></h3>
                                </div>
                            
                             <div id="display_laska_2">
                             	 <div style="float:left; width:300px;">
                                 <p> В <strong>приватной стоматологии «ЛАСКА»</strong> работает нежный и ласковый детский стоматолог, который сразу же располагает к себе ребенка. Ведь самое главное доверие. Современные методики и материалы для детей позволяют быстро и качественно полечить больной зубик. Профилактика стоматологических заболеваний основное направление <strong>детской стоматологии</strong> в «ПС ЛАСКА». Мы любим детей. Каждый ребенок получает подарок, что делает его поход в стоматологию приятным. </p>
                            	</div>
                                <div style="float:left; width:300px;">
                                <p><strong>Ортодонтия в Донецке</strong> очень важное направление. «<strong>ПС ЛАСКА</strong>» одна из первых начала использовать <strong>брекеты</strong> в Донецке (с 1992 года) для исправления прикуса и неправильного положения зубов. Врачи - ортодонты  нашей клиники успешно владеют методиками коррекции неправильного положения зубов и прикуса. При этом используется съемные аппараты - пластинки и несъемные – брекет - системы. Мы имеем опыт лечения пациентов с ретенированными зубами (которые не прорезались самостоятельно). «<strong>ПС ЛАСКА</strong>» сотрудничает с кафедрой хирургической стоматологии, что позволяет совместить  хирургическое стационарное лечение с ортодонтическим лечением. В сложных случаях у нас есть возможность проконсультироваться с ведущими специалистами мира с помощью телемедицины.</p>
                            	</div>
                                <div style="float:left; width:300px;">
                               <p><strong>Эстетическая (художественная) реставрация зубов</strong> позволяет врачу откорректировать «ошибки природы» т.е. улучшить или изменить ваши родные зубы. При этом снимается минимальное количество тканей зуба, снижается себестоимость лечения и количество визитов. В арсенале врача стоматолога в настоящее время огромное количество современных материалов. Мы используем материалы ведущих производителей мира: VOCO, KERR, 3M, IVOCLAR и т.д.</p>                             
<p>90% зубов удаляются в результате не качественного лечения корневых каналов. Зная эту проблему, в «<strong>ПС ЛАСКА</strong>» выделены врачи – <strong>эндодонтисты</strong>, которые занимаются исключительно <strong>лечением корневых каналов</strong>. В результате чего закрываются свищи и заживают гранулемы. Это ювелирная работа, Врач эндодонтист имеет специальное образование и  оборудование (Эндодонтичекие наконечники, апекс – локаторы, обтураторы и т.д.).</p>
                            	</div>	
                             </div>             
 						</div>
                        <div style="margin:15px auto 160px auto; text-align:center; font-family:Helvetica; font-size:16px; color:#e72365; font-weight:bold;">ДОБРОЖЕЛАТЕЛЬНОЕ ОТНОШЕНИЕ И ПРОФЕССИОНАЛИЗМ ПОЗВОЛИТ СДЕЛАТЬ ВАШ ВИЗИТ КОМФОРТНЫМ!</div>
 </div>
</div>

<?php

}

else

   if ($_GET['pm'] == 2)

   {

?>

<script language="javascript" type="text/javascript">
	function show_hide(objectID){
		var object=document.getElementById(objectID);
		if (object.style.display=='none')
			object.style.display='block';
			else
			object.style.display='none';
			return;
	}
</script>

<div class="catalogue_item_cont_m"> 

<table width="1000" height="280" border="0" align="center" cellpadding="0" cellspacing="0" background="../root/msite/laska/top.png">
  <tr>
    <td height="166" colspan="2" valign="top"><div align="right">
      <table width="434" border="0">
          <tr>
            <td width="428" height="121" valign="top"><table width="383" border="0" cellpadding="0" cellspacing="0" align="center">
              <tr>
                <td width="387"><div align="center"><span class="стиль1">&nbsp;<br />
				  Работаем:<br />
                  в будние дни: с 9:00 до 20:00<br />
                  суббота, воскресенье<br />
                  и праздничные дни: с 9:00 - до 15:00<br />
                  Адрес: Донецк, ул. Панфилова, 6 <br />
                  Телефон: (062) 345-56-71, 348-16-59 <br />
                  моб.: - (095)258-73-31</span></div></td>
              </tr>
            </table>              
              <p align="center" class="стиль1"></td>
          </tr>
          </table>
    </div></td>
    <td height="166" valign="top"><div align="right" class="стиль1"> “ Люди с хорошими зубами всё находят смешным” *    
      О. де Бальзак  *</div></td>
  </tr>
  <tr>
    <td width="272"><table width="272" height="104" border="0">
      <tr>
        <td background="../root/msite/laska/about.png"><div align="center"><span class="стиль4"><a href="index.php?business_full=520&pm=1">О НАС</span></div></td>
      </tr>
    </table></td>
    <td width="357">
      <div align="right">
        <table width="272" height="104" border="0">
            <tr>
              <td background="../root/msite/laska/serv.png"><div align="center" class="стиль4"><a href="index.php?business_full=520&pm=2">УСЛУГИ</div></td>
            </tr>
                  </table>
      </div></td>
    <td width="351"><div align="right">
      <table width="272" height="104" border="0">
          <tr>
            <td background="../root/msite/laska/sale.png"><div align="center" class="стиль4">
              <p>АКЦИИ</p>
              </div></td>
          </tr>
          </table>
    </div></td>
  </tr>
</table>
                    
                   
                   <div style="margin:0 auto 0 auto; width:990px; border:3px solid #85aef9; background-color:#fff4e9; background-image:url(../root/msite/laska/content_bg_laska.jpg); background-position:bottom; background-repeat:no-repeat;" >
                    	<div id="onas_laska">
                        <img src="../root/msite/laska/onaspic_laska.jpg" style="float:left; margin-right:20px; border:2px solid #85aef9;" />
                       <a href="#">Протезирование</a>
<p><strong>Протезирование зубов</strong> - искусственное восстановление потерянных зубов. При необходимости в сложном стоматологическом лечении по восстановлению эстетического вида зубов, мы рекомендуем обратиться за помощью к нашим специалистам по протезированию. Вместе с ними вы сможете беспрепятственно получить рекомендации о состоянии вашего зубного аппарата и установить <strong>коронки</strong>, <strong>мосты</strong> либо <strong>протезы</strong>.</p>

<a href="#">Парадонтология</a>
<p><strong>Пародонтит</strong> - это воспаление опорного аппарата зуба, вызываемое отложениями бактериальных налетов (бляшек) на зубах и на деснах. Если эти налеты не устранять систематически и основательно при чистке зубов, то на них образуется зубной камень, упрочняющийся со временем и "прорастающий" в глубину десен. Возникают зубодесневые карманы, в которых могут беспрепятственно размножаться бактерии, поскольку эти места недостижимы для зубной щетки. </p>

<a href="#">Ортодонтия</a>
<p><strong>Ортодонтия</strong> - раздел стоматологии, занимающийся исправлением положения зубов и аномалиями прикуса. Пройдя лечение врача-ортодонта в приватной стоматологии ЛАСКА, вы получите не только красивую гармоничную улыбку, но и в ряде случаев значительное улучшение профиля лица и дикции.</p>

<a href="#">Отбеливание</a>
<p>Секрет обаятельного человека - в его сияющей улыбке. А секрет улыбки - в <strong>профессиональном отбеливании</strong>, которое Вы можете сделать в <strong>приватной стоматологии ЛАСКА</strong>. </p>

<a href="#">Имплантология</a>
<p><strong>Имплантология</strong> - это одно из самых современных направлений стоматологии, которое успешно развивается более тридцати лет. На сегодняшний день детальная имплантация получила широкое распространение во всех развитых странах мира.</p>

<a href="#">Эндодонтия</a>
<p><strong>Эндодонтия</strong> – направление в стоматологии относительно новое. Возникло в начале 70-х годов прошлого века, занимается изучением, лечением и предотвращением заболеваний (и их возможных осложнений) мягкой ткани (пульпы) внутри зубов. </p>

<a href="#">Хирургия</a>
<p>При невозможности сохранения зуба, возникает необходимость его удаления. При потере зуба, в следствие болезни или травмы, специалисты нашей приватной стоматологии ЛАСКА порекомендуют установить имплант, который будет выглядеть очень естественно. </p>

<a href="#">Детская стоматология</a>
<p>У нас особое отношение к детям. Перед тем, как начать осмотр, специалист стоматолгической клиники ЛАСКА проведет для маленького пациента экскурсию по клинике, врачи стоматологии ЛАСКА, во время приема создают для детей комфортную и непринужденную атмосферу, покажут, что визит к зубному врачу – это увлекательное приключение, которого можно не бояться.</p>
                        </div>
                        
                        <div style="margin:15px auto 160px auto; text-align:center; font-family:Helvetica; font-size:16px; color:#e72365; font-weight:bold;">ДОБРОЖЕЛАТЕЛЬНОЕ ОТНОШЕНИЕ И ПРОФЕССИОНАЛИЗМ ПОЗВОЛИТ СДЕЛАТЬ ВАШ ВИЗИТ КОМФОРТНЫМ!</div>
 </div>
 
</div>



<?php

   } 

?>



<p>&nbsp;</p>



<div id="catalogue_item_menu">

<div class="catalogue_item_mp_a">

<a href="index.php?section_id=32&amp;business=1">Категория:</a></div>

</div>

<div class="catalogue_item_cont">

<a href="index.php?section_id=2&amp;business=1">бизнес</a>

 / 

<a href="index.php?section_id=32&amp;business=1">предприятия</a>

 / 

<a href="index.php?section_id=387&amp;business=2">Медицина</a>

 / 

<a href="index.php?section_id=511&business=2">Стоматология</a>

</div>





<div id="catalogue_item_menu">

<div class="catalogue_item_mp_a">

<a href="">Фотогалегея:</a></div>

</div>

<div class="catalogue_item_cont">

</div>

<div id="catalogue_item_menu">

<div class="catalogue_item_mp_a">

<a href="">Контактная информация:</div>

</div>

 <div class="catalogue_item_cont">

 		 <table width="100%">

			<tbody>

 			<tr>

			<!--	<td><img class="main_sec_image" src="" width="60" height="60" border="0" alt="" /></td>-->

				<td>Адрес:</td>

				<td>Телефон:</td>

				<td>Моб.:</td>

				<td>E-mail:</td>

				<td>Веб-сайт:</td>

			</tr>

			<tr>

				<td>Донецк, ул. Панфилова, 6</td>

				<td>+38 (062)345-56-71, 348-16-59</td>

				<td>+38 (095)258-73-31</td>

				<td></td>

				<td></td>



			</tr>

			</tbody> 

		 </table> 		

	 </div>

</div>  





