<div class="catalogue_item_c">



<style>







<!--



.folding{cursor:hand;font-weight:bold}



-->







.catalogue_item_cont p {



color:#000000;



text-align:justify;



text-indent:0px;



line-height:20px;



margin:0px;



}







.catalogue_item_cont_m {



background-color:#FFFFFF;



border:1px solid lightgray;



color:#000000;



margin:0;



margin:15px 10px 10px;



width:980px;



}







.catalogue_item_cont {



background-color:#ffffff;



border-top:1px solid lightgray;



margin:0 0 7px 10px;



width:980px;



color:#000000;



}



.catalogue_item_c {



background-color:#F3F3F3;



}







.catalogue_item_cont a {



color:#000000;



}







.catalogue_item_cont a:hover {



color:#000000;



text-decoration:underline;



}







.catalogue_item_mp_a {



left:3px;



position:relative;



}







#mm_menu {position:relative;left:610px;width:225px;text-align:center;} 







#div_st {padding:0 0px;position:relative;height:955px;}







@media all and (-webkit-min-device-pixel-ratio:10000),



not all and (-webkit-min-device-pixel-ratio:0) {



 #div_st {height:955px;}



}



#div_st2 {padding:0 0px;position:relative;height:6750px;}







@media all and (-webkit-min-device-pixel-ratio:10000),



not all and (-webkit-min-device-pixel-ratio:0) {



 #div_st2 {height:6750px;}



}



#div_st3 {padding:0 0px;position:relative;height:800px;}







@media all and (-webkit-min-device-pixel-ratio:10000),



not all and (-webkit-min-device-pixel-ratio:0) {



 #div_st3 {height:869px;}



}







div {



	display:block;



}







.sequ_container {



	width:100%;



	height:100%;



	margin:0px;



	padding:0px;



}







.background_div {



	width:980px;



	height:950px;



	background-image:url('../root/msite/coffee/background.png');



}







.logo {



	position:absolute;



	float:right;



	right:80px;



	top:70px;



	background-image:url('../root/msite/coffee/logo.png');



	background-repeat:no-repeat;



	width:335px;



	height:168px;



}







.girl {



	position:absolute;



	float:right;



	right:47px;



	top:685px;



	background-image:url('../root/msite/coffee/girl.png');



	width:363px;



	height:201px;



}







.text_r {



	position:relative;



	float:right;



	width:390px;



	right:45px;



	top:265px;



}







#p_adv {



	font-family:Adventure;



	font:Adventure;	



	font-size:10pt;



	font-weight:bold;



	letter-spacing:1px;



	text-align:right;



	color:#775e4b;



}







.cup {



	position:absolute;



	float:left;



	left:10px;



	top:10px;



	background-image:url('../root/msite/coffee/cup.png');



	width:285px;



	height:236px;



}







@font-face {



	font-family:Adventure;



	src:url(http://www.eurodonetsk.com/public_html/root/msite/coffee/adventure_font.ttf);



}







.sil {



	position:relative;



	float:left;



	width:250px;



	left:30px;



	top:400px;



	font-family:Adventure;



	src:url(http://www.eurodonetsk.com/public_html/root/msite/coffee/adventure_font.ttf);



	font:Adventure;	



	font-size:16pt;



	font-weight:bold;



	font-style:bold;



	letter-spacing:1px;



	color:#775e4b;



}







.mid_pho {



	position:absolute;



	float:left;



	left:285px;



	top:120px;



	background-image:url('../root/msite/coffee/mid_pho.png');



	width:276px;



	height:760px;



}







.girl2 {



	position:absolute;



	float:right;



	right:50px;



	top:6485px;



	background-image:url('../root/msite/coffee/girl.png');



	width:363px;



	height:201px;



}







.background_div2 {



	position:relative;



	float:left;



	display:block;



	width:980px;



	height:6750px;



	background-image:url('../root/msite/coffee/menu_bg.png');



}







.menu {



	position:relative;



	float:right;



	width:540px;



	right:45px;



	top:265px;



	font-family:Adventure;



	src:url(http://www.eurodonetsk.com/public_html/root/msite/coffee/adventure_font.ttf);



	font:Adventure;	



	font-size:16pt;



	font-weight:bold;



	font-style:bold;



	letter-spacing:1px;



	color:#775e4b;



}







.tab {





	font-size:12pt;



	text-align:left;



}







.menu_2 {



	position:relative;



	float:right;



	width:594px;



	right:45px;



	top:265px;



	font-family:Adventure;



	src:url(http://www.eurodonetsk.com/public_html/root/msite/coffee/adventure_font.ttf);



	font:Adventure;	



	font-size:16pt;



	font-weight:bold;



	font-style:bold;



	letter-spacing:1px;



	color:#775e4b;



}

.dt_text_h1_style {
	font-family: Verdana, Arial, Helvetica, sans-serif;
	font-size: 30px;
	color: #660000;
	font-weight: bold;
	text-align:left;
}

.dt_text_h2_style {
	font-family: Verdana, Arial, Helvetica, sans-serif;
	font-size: 24px;
	color: #660000;
	text-align:left;
}

.dt_text_h2_2_style {
	font-family: Verdana, Arial, Helvetica, sans-serif;
	font-size: 20px;
	color: #000000;
	text-align:right;
}

.dt_text_h2_3_style {
	font-family: Verdana, Arial, Helvetica, sans-serif;
	font-size: 25px;
	color: #660000;
	text-align:center;
}

.dt_text_menu_style {
	font-family: Georgia, "Times New Roman", Times, serif;
	font-style:italic;
	font-size: 20px;
	color: #ffffff;
}

.dt_text_menu1_style {
	font-family: Georgia, "Times New Roman", Times, serif;
	font-style:italic;
	font-size: 11px;
	color: #660000;
	text-decoration: none;
}

.dt_text_h3_style {
	font-family: Verdana, Arial, Helvetica, sans-serif;
	font-size: 16px;
	color: #660000;
	text-align:left;


</style>

<?php

if ($_GET['pm'] == 1) 

{

?>

<div class="catalogue_item_cont_m"> 

	<table width="990" height="1140" cellpadding="0" cellspacing="0" align="center" border="0">
  <tr>
    <td height="457" colspan="4" background="../root/msite/dt/up_en.jpg">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="4" background="../root/msite/dt/menu_bg.png" height="81" ><div align="center">
      <table width="980" align="center" border="0">
        <tr>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff" href="index.php?business_full=536&pm=1">About us</a></td>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff"  href="index.php?business_full=536&pm=2">Articles</a></td>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff"  href="index.php?business_full=536&pm=6">Service</a></td>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff"  href="index.php?business_full=536&pm=7">Contacts</a></td>
          <td width="%">&nbsp;</td>
        </tr>
      </table>
   </div></td>
  </tr>
  <tr>
    <td colspan="4" background="../root/msite/dt/main_bg.jpg" height="962"><table width="100%" height="867" border="0">
      <tr>
        <td width="73" height="50">&nbsp;</td>
        <td width="211">&nbsp;</td>
        <td width="61">&nbsp;</td>
        <td width="552">&nbsp;</td>
        <td width="71">&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td rowspan="3" background="../root/msite/dt/ava.png">&nbsp;</td>
        <td>&nbsp;</td>
        <td rowspan="8" valign="top">
          <p class="dt_text_h2_2_style">Director<br />
            of  Professional Dental Clinic<br />
            «Bioinert technology Dent Titan»</p>
          <p class="dt_text_h2_2_style"><strong>professor Stanislaw Surzhansky</strong><br />
          </p>
          <p class="dt_text_menu1_style">&nbsp;</p>
          <p class="dt_text_h2_3_style"><strong>Dear friends!</strong></p>
		  <p>&nbsp;</p>
		  <p>&nbsp;</p>
          <p class="dt_text_h3_style">Sincerely welcome all visitors to the official website of Professional Dental Clinic namely «Bioinert technology Dent Titan»!</p>
		  <p>&nbsp;</p>
          <p class="dt_text_h3_style"><strong>“Dent Titan”</strong> is a solidary group of like-minded person which is rightfully considered to be one of the leaders in the native dentistry.</p>
		  <p>&nbsp;</p>
          <p class="dt_text_h3_style"><strong>“Dent Titan”</strong> is mini-scientific center which has successfully put into practice the latest developments in titanoceramic, titanopolymer and titanoimplantation.</p>
		  <p>&nbsp;</p>
          <p class="dt_text_h3_style"><strong>“Dent Titan”</strong> has rich experience of domestic and foreign dentistry which allows achieve guaranteed results.</p>
		  <p>&nbsp;</p>
          <p class="dt_text_h3_style"><strong>“Dent Titan”</strong> has hardworking, talented employees who are known not only in Ukraine but also abroad.</p>
		  <p>&nbsp;</p>
          <p class="dt_text_h3_style">As the head of Professional Dental Clinic  <strong>«Bioinert technology Dent Titan»</strong>, I thank you for your trust and welcome the opportunity to work for you. </p>
		  <p>&nbsp;</p>
          <p class="dt_text_h3_style">From my hand open communication is guaranteed. I would be pleased if the site of Professional Dental Clinic “Bioinertnye technology Dent Titan” will help you to obtain necessary, reliable and useful information about the activities of clinic, make the acquaintance of staff and list of services rendered by "Dent Titan”.</p>
		  <p>&nbsp;</p>
		  <p>&nbsp;</p>
          <p class="dt_text_h2_2_style">Yours faithfully,<br />
            <strong> professor Stanislaw Surzhansky</strong></p></td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="70">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="79">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="69">&nbsp;</td>
        <td align="center" valign="middle">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="67">&nbsp;</td>
        <td align="center" valign="middle">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="65">&nbsp;</td>
        <td align="center" valign="middle">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
    </table></td>
  </tr>
</table>

</div> <!-- cat_ite_cont_m -->

<?php

}

else

   if ($_GET['pm'] == 2)

   {

?>

<div class="catalogue_item_cont_m"> 

	<table width="990" height="1140" cellpadding="0" cellspacing="0" align="center" border="0">
  <tr>
    <td height="457" colspan="4" background="../root/msite/dt/up_en.jpg">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="4" background="../root/msite/dt/menu_bg.png" height="81" ><div align="center">
      <table width="980" align="center" border="0">
        <tr>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff" href="index.php?business_full=536&pm=1">About us</a></td>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff"  href="index.php?business_full=536&pm=2">Articles</a></td>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff"  href="index.php?business_full=536&pm=6">Service</a></td>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff"  href="index.php?business_full=536&pm=7">Contacts</a></td>
          <td width="%">&nbsp;</td>
        </tr>
      </table>
    </div></td>
  </tr>
  <tr>
    <td colspan="4" background="../root/msite/dt/main_bg.jpg" height="962"><table width="100%" height="937" border="0">
      <tr>
        <td width="73" height="50">&nbsp;</td>
        <td width="193">&nbsp;</td>
        <td width="79">&nbsp;</td>
        <td width="552">&nbsp;</td>
        <td width="71">&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td background="../root/msite/dt/img_1.jpg">&nbsp;</td>
        <td>&nbsp;</td>
        <td rowspan="8" valign="top">
          <p class="dt_text_h3_style"><img src="../root/msite/dt/foto_s2.png" width="517" height="378" /></p>
		  <p>&nbsp;</p>
          <p class="dt_text_h3_style">Oral cavity is the start of energetic towards person where there is not only mechanical processes (crushing, mastication, the formation of bolus), but the most important biochemical enzymatic processes the violation of which leads to chronic inflammatory diseases of the mucous in the oral cavity, as well as throughout path of the bolus, starting with the oral cavity, esophagus, stomach, etc. </p>
		  <p>&nbsp;</p>
          <p class="dt_text_h3_style">Today we are honored to offer our patients the most effective bioinert material for orthopedic treatment (dental prosthetics) - titanium. We are waiting in our clinic everyone who cares about health. We guarantee that dental prosthesis made of titan-ceramics, titan-composites, titan-plastic will be absolutely bioinert and manufactured on the highest professional level. Professor, associate professors, doctors of the I-st and the highest category will work with you. We’d like to remind you that "Everything in this world has its price, just the health is priceless - it is for all of us - priceless."</span><br />
          </p>          <p class="dt_text_h3_style">&nbsp;</p></td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="70">&nbsp;</td>
        <td align="center" valign="middle" background="../root/msite/dt/button2.png"><div align="center" class="dt_text_menu1_style"><a style="color: #660000"  href="http://www.eurodonetsk.com/index.php?business_full=536&pm=2">Fo be healthy <br />
        not to seem!</a></div></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td background="../root/msite/dt/img_2.jpg">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="69">&nbsp;</td>
        <td align="center" valign="middle" background="../root/msite/dt/button2.png"><div align="center" class="dt_text_menu1_style"><a style="color: #660000"   href="http://www.eurodonetsk.com/index.php?business_full=536&pm=3">There should be space <br />
          clearance in oral cavity</a></div></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td background="../root/msite/dt/img_3.jpg">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="67">&nbsp;</td>
        <td align="center" valign="middle" background="../root/msite/dt/button2.png"><div align="center" class="dt_text_menu1_style"><a style="color: #660000"   href="http://www.eurodonetsk.com/index.php?business_full=536&pm=4">Oral cavity is the <br />
          mirror of stomach!</a></div></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td background="../root/msite/dt/img_4.jpg">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="65">&nbsp;</td>
        <td align="center" valign="middle" background="../root/msite/dt/button2.png"><div align="center" class="dt_text_menu1_style"><a style="color: #660000"   href="http://www.eurodonetsk.com/index.php?business_full=536&pm=5">Absolute harmony <br />
          titanium with ceramic</a></div></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
    </table></td>
  </tr>
</table>

</div> <!-- cat_ite_cont_m -->

<?php

}

else

   if ($_GET['pm'] == 3)

   {

?>

<div class="catalogue_item_cont_m"> 

	<table width="990" height="1140" cellpadding="0" cellspacing="0" align="center" border="0">
  <tr>
    <td height="457" colspan="4" background="../root/msite/dt/up_en.jpg">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="4" background="../root/msite/dt/menu_bg.png" height="81" ><div align="center">
      <table width="980" align="center" border="0">
        <tr>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff" href="index.php?business_full=536&pm=1">About us</a></td>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff"  href="index.php?business_full=536&pm=2">Articles</a></td>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff"  href="index.php?business_full=536&pm=6">Service</a></td>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff"  href="index.php?business_full=536&pm=7">Contacts</a></td>
          <td width="%">&nbsp;</td>
        </tr>
      </table>
    </div></td>
  </tr>
  <tr>
    <td colspan="4" background="../root/msite/dt/main_bg.jpg" height="962"><table width="100%" height="937" border="0">
      <tr>
        <td width="73" height="50">&nbsp;</td>
        <td width="193">&nbsp;</td>
        <td width="79">&nbsp;</td>
        <td width="552">&nbsp;</td>
        <td width="71">&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td background="../root/msite/dt/img_1.jpg">&nbsp;</td>
        <td>&nbsp;</td>
        <td rowspan="8" valign="top">
          <p class="dt_text_h3_style"><img src="../root/msite/dt/foto_s3.png" width="517" height="378" /></p>
		  <p>&nbsp;</p>
          <p class="dt_text_h3_style">As it known, dental fixed dental bridge and crowns are made of metal load-bearing frame which was subsequently ennobled with one of the facing materials (plastic, photocomposition and ceramics). The purpose of this prosthesis is to restore the mechanical masticatory efficiency of human dentition. Such bridges have up to 13 - 16 elements of the periodic table, with nickel, chromium, cadmium, cobalt are metals by poisons and monovariant banned for use in biological environment (human body). But in the alloy, for some reason it is possible. And in such alloys as Vitalium "Co = 61, 1%, Cr = 31.6%;" Vitron - 77 »Ni = 70%, Cr = 30%. In our opinion the peak of insanity is a fusion of "Gemini - II», where the nickel - 80, 5%. The figures speak for themselves.  </p>
		  <p>&nbsp;</p>
          <p class="dt_text_h3_style">Factor of metal multi-component creates conditions for the occurrence of galvanic currents in the oral cavity and leaving alloys trace metals, including metals- poisons. In their interaction with oral highly fluid and bioferment (there are more than 60 in saliva), there appeared micro currents that called dental galvanosis.</span><br />
          </p>          <p class="dt_text_h3_style">&nbsp;</p></td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="70">&nbsp;</td>
        <td align="center" valign="middle" background="../root/msite/dt/button2.png"><div align="center" class="dt_text_menu1_style"><a style="color: #660000"  href="http://www.eurodonetsk.com/index.php?business_full=536&pm=2">Fo be healthy <br />
        not to seem!</a></div></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td background="../root/msite/dt/img_2.jpg">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="69">&nbsp;</td>
        <td align="center" valign="middle" background="../root/msite/dt/button2.png"><div align="center" class="dt_text_menu1_style"><a style="color: #660000"   href="http://www.eurodonetsk.com/index.php?business_full=536&pm=3">There should be space <br />
          clearance in oral cavity</a></div></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td background="../root/msite/dt/img_3.jpg">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="67">&nbsp;</td>
        <td align="center" valign="middle" background="../root/msite/dt/button2.png"><div align="center" class="dt_text_menu1_style"><a style="color: #660000"   href="http://www.eurodonetsk.com/index.php?business_full=536&pm=4">Oral cavity is the <br />
          mirror of stomach!</a></div></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td background="../root/msite/dt/img_4.jpg">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="65">&nbsp;</td>
        <td align="center" valign="middle" background="../root/msite/dt/button2.png"><div align="center" class="dt_text_menu1_style"><a style="color: #660000"   href="http://www.eurodonetsk.com/index.php?business_full=536&pm=5">Absolute harmony <br />
          titanium with ceramic</a></div></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
    </table></td>
  </tr>
</table>

</div> <!-- cat_ite_cont_m -->

<?php

}

else

   if ($_GET['pm'] == 4)

   {

?>

<div class="catalogue_item_cont_m"> 

	<table width="990" height="1140" cellpadding="0" cellspacing="0" align="center" border="0">
  <tr>
    <td height="457" colspan="4" background="../root/msite/dt/up_en.jpg">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="4" background="../root/msite/dt/menu_bg.png" height="81" ><div align="center">
      <table width="980" align="center" border="0">
        <tr>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff" href="index.php?business_full=536&pm=1">About us</a></td>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff"  href="index.php?business_full=536&pm=2">Articles</a></td>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff"  href="index.php?business_full=536&pm=6">Service</a></td>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff"  href="index.php?business_full=536&pm=7">Contacts</a></td>
          <td width="%">&nbsp;</td>
        </tr>
      </table>
    </div></td>
  </tr>
  <tr>
    <td colspan="4" background="../root/msite/dt/main_bg.jpg" height="962"><table width="100%" height="937" border="0">
      <tr>
        <td width="73" height="50">&nbsp;</td>
        <td width="193">&nbsp;</td>
        <td width="79">&nbsp;</td>
        <td width="552">&nbsp;</td>
        <td width="71">&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td background="../root/msite/dt/img_1.jpg">&nbsp;</td>
        <td>&nbsp;</td>
        <td rowspan="8" valign="top">
          <p class="dt_text_h3_style"><img src="../root/msite/dt/foto_s4.png" width="517" height="378" /></p>
		  <p>&nbsp;</p>
          <p class="dt_text_h3_style">Until now, prosthodontics is a paradox - restoring the mechanical efficiency of mastication the dentists destroy the biochemical processes formation of the primary bolus that is inadmissible to person. That is why we are against multi-component metal alloys from whatever produced (U.S., Japan, Germany). The fact remains: these alloys - the enemies of the human body.</p>
		  <p>&nbsp;</p>
          <p class="dt_text_h3_style">That was all. Now we are for the first time in Ukraine can offer a completely bioinert, anti-corrosion, anti allergic, anti-magnetic, lightweight and durable monometallic - titanium. Employees of Dentistry Department, Faculty of Postgraduate Education of Donetsk State Medical University, led by Professor Surzhanskiy S.K. together with the firm of Dent - Titan developed and implemented a new alternative that is safe for human body technology of manufacturing load-bearing frame of fixed dental prosthesis made of titanium.
</span><br />
          </p>          <p class="dt_text_h3_style">&nbsp;</p></td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="70">&nbsp;</td>
        <td align="center" valign="middle" background="../root/msite/dt/button2.png"><div align="center" class="dt_text_menu1_style"><a style="color: #660000"  href="http://www.eurodonetsk.com/index.php?business_full=536&pm=2">Fo be healthy <br />
        not to seem!</a></div></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td background="../root/msite/dt/img_2.jpg">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="69">&nbsp;</td>
        <td align="center" valign="middle" background="../root/msite/dt/button2.png"><div align="center" class="dt_text_menu1_style"><a style="color: #660000"   href="http://www.eurodonetsk.com/index.php?business_full=536&pm=3">There should be space <br />
          clearance in oral cavity</a></div></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td background="../root/msite/dt/img_3.jpg">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="67">&nbsp;</td>
        <td align="center" valign="middle" background="../root/msite/dt/button2.png"><div align="center" class="dt_text_menu1_style"><a style="color: #660000"   href="http://www.eurodonetsk.com/index.php?business_full=536&pm=4">Oral cavity is the <br />
          mirror of stomach!</a></div></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td background="../root/msite/dt/img_4.jpg">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="65">&nbsp;</td>
        <td align="center" valign="middle" background="../root/msite/dt/button2.png"><div align="center" class="dt_text_menu1_style"><a style="color: #660000"   href="http://www.eurodonetsk.com/index.php?business_full=536&pm=5">Absolute harmony <br />
          titanium with ceramic</a></div></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
    </table></td>
  </tr>
</table>

</div> <!-- cat_ite_cont_m -->

<?php

}

else

   if ($_GET['pm'] == 5)

   {

?>

<div class="catalogue_item_cont_m"> 

	<table width="990" height="1140" cellpadding="0" cellspacing="0" align="center" border="0">
  <tr>
    <td height="457" colspan="4" background="../root/msite/dt/up_en.jpg">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="4" background="../root/msite/dt/menu_bg.png" height="81" ><div align="center">
      <table width="980" align="center" border="0">
        <tr>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff" href="index.php?business_full=536&pm=1">About us</a></td>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff"  href="index.php?business_full=536&pm=2">Articles</a></td>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff"  href="index.php?business_full=536&pm=6">Service</a></td>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff"  href="index.php?business_full=536&pm=7">Contacts</a></td>
          <td width="%">&nbsp;</td>
        </tr>
      </table>
    </div></td>
  </tr>
  <tr>
    <td colspan="4" background="../root/msite/dt/main_bg.jpg" height="962"><table width="100%" height="937" border="0">
      <tr>
        <td width="73" height="50">&nbsp;</td>
        <td width="193">&nbsp;</td>
        <td width="79">&nbsp;</td>
        <td width="552">&nbsp;</td>
        <td width="71">&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td background="../root/msite/dt/img_1.jpg">&nbsp;</td>
        <td>&nbsp;</td>
        <td rowspan="8" valign="top">
          <p class="dt_text_h3_style"><img src="../root/msite/dt/foto_s5.png" width="517" height="378" /></p>
		  <p>&nbsp;</p>
          <p class="dt_text_h3_style">Titan - monometallic, since 1950 is widely used as implants in the human body such as artificial joints, pins for osteosynthesis, cranial plates, etc. Titan is unquestionable advantage in bioinertness. </p>
		  <p>&nbsp;</p>
          <p class="dt_text_h3_style">It is also known that titanium has a bactericidal effect in close contact with germ cultures and at the same time indifferent to the micro flora of oral cavity.</p>
		  <p>&nbsp;</p>
          <p class="dt_text_h3_style">Thus, conducting orthopedic treatment with prosthesis made of titanium, we are not just restoring the mechanical function, but do not destroy the biochemical processes in the oral cavity during the formation of initial bolus.</p>
		  <p>&nbsp;</p>
		  <p class="dt_text_h3_style">Based on an extensive twelve-year clinical experience and results of biochemical studies in patients with a full guarantee we affirm that titanium is a metal of third millennium.</p>
		  <p>&nbsp;</p>
          <p class="dt_text_h3_style">It is defended 2 doctoral and 3 master's theses based on the use of titanium. The technology is patented in Ukraine. Firm "Dent - Titan is the only patent holder.
</span><br />
          </p>          <p class="dt_text_h3_style">&nbsp;</p></td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="70">&nbsp;</td>
        <td align="center" valign="middle" background="../root/msite/dt/button2.png"><div align="center" class="dt_text_menu1_style"><a style="color: #660000"  href="http://www.eurodonetsk.com/index.php?business_full=536&pm=2">Fo be healthy <br />
        not to seem!</a></div></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td background="../root/msite/dt/img_2.jpg">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="69">&nbsp;</td>
        <td align="center" valign="middle" background="../root/msite/dt/button2.png"><div align="center" class="dt_text_menu1_style"><a style="color: #660000"   href="http://www.eurodonetsk.com/index.php?business_full=536&pm=3">There should be space <br />
          clearance in oral cavity</a></div></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td background="../root/msite/dt/img_3.jpg">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="67">&nbsp;</td>
        <td align="center" valign="middle" background="../root/msite/dt/button2.png"><div align="center" class="dt_text_menu1_style"><a style="color: #660000"   href="http://www.eurodonetsk.com/index.php?business_full=536&pm=4">Oral cavity is the <br />
          mirror of stomach!</a></div></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td background="../root/msite/dt/img_4.jpg">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="65">&nbsp;</td>
        <td align="center" valign="middle" background="../root/msite/dt/button2.png"><div align="center" class="dt_text_menu1_style"><a style="color: #660000"   href="http://www.eurodonetsk.com/index.php?business_full=536&pm=5">Absolute harmony <br />
          titanium with ceramic</a></div></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
    </table></td>
  </tr>
</table>

</div> <!-- cat_ite_cont_m -->

<?php

}

else

   if ($_GET['pm'] == 6)

   {

?>

<div class="catalogue_item_cont_m"> 

	<table width="990" height="1140" cellpadding="0" cellspacing="0" align="center" border="0">
  <tr>
    <td height="457" colspan="4" background="../root/msite/dt/up_en.jpg">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="4" background="../root/msite/dt/menu_bg.png" height="81" ><div align="center">
      <table width="980" align="center" border="0">
        <tr>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff" href="index.php?business_full=536&pm=1">About us</a></td>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff"  href="index.php?business_full=536&pm=2">Articles</a></td>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff"  href="index.php?business_full=536&pm=6">Service</a></td>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff"  href="index.php?business_full=536&pm=7">Contacts</a></td>
          <td width="%">&nbsp;</td>
        </tr>
      </table>
    </div></td>
  </tr>
  <tr>
    <td colspan="4" background="../root/msite/dt/main_bg.jpg" height="962"><table width="100%" height="937" border="0">
      <tr>
        <td width="73" height="50">&nbsp;</td>
        <td width="193">&nbsp;</td>
        <td width="79">&nbsp;</td>
        <td width="552">&nbsp;</td>
        <td width="71">&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td background="../root/msite/dt/img_1.jpg">&nbsp;</td>
        <td>&nbsp;</td>
        <td rowspan="8" valign="top">
		<p>&nbsp;</p>
		<p class="dt_text_h1_style">List of service:</p>
          <p>&nbsp;</p>
          <p class="dt_text_h2_style">1. Endodontic treatment (treatment  <br />
            and filling of root canal);</p>
		  <p>&nbsp;</p>
          <p class="dt_text_h2_style">2. Therapeutic treatment;</p>
		  <p>&nbsp;</p>
          <p class="dt_text_h2_style">3. Orthopedic treatment <br />
            (metal-ceramic frame);</p>
		  <p>&nbsp;</p>
          <p class="dt_text_h2_style">4. Cosmetic treatment;</p>
		  <p>&nbsp;</p>
          <p class="dt_text_h2_style">5. Occupational hygiene <br />
            (bleaching);</p>
		  <p>&nbsp;</p>
          <p class="dt_text_h2_style">6. Preventive tooth brushing;</p>
		  <p>&nbsp;</p>
          <p class="dt_text_h2_style">7. Aesthetic tooth restoration <br />
            (Restoration of initial  <br />
            tooth color and shape);</p>
			<p>&nbsp;</p>
          <p class="dt_text_h2_style">8. Caries treatment;</p>
		  <p>&nbsp;</p>
          <p class="dt_text_h2_style">9. Treatment of parodentium;</p>
		  <p>&nbsp;</p>
          <p class="dt_text_h2_style">10. Dental decoration;</p>
		  <p>&nbsp;</p>
          <p class="dt_text_h2_style">11. Hardware methods <br />
		  of diagnostics;</p>
		  <p>&nbsp;</p>
          <p class="dt_text_h2_style">12. Implantation.</p></td>
		  <p>&nbsp;</p>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="70">&nbsp;</td>
        <td align="center" valign="middle" background="../root/msite/dt/button2.png"><div align="center" class="dt_text_menu1_style"><a style="color: #660000"  href="http://www.eurodonetsk.com/index.php?business_full=536&pm=2">Fo be healthy <br />
        not to seem!</a></div></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td background="../root/msite/dt/img_2.jpg">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="69">&nbsp;</td>
        <td align="center" valign="middle" background="../root/msite/dt/button2.png"><div align="center" class="dt_text_menu1_style"><a style="color: #660000"   href="http://www.eurodonetsk.com/index.php?business_full=536&pm=3">There should be space <br />
          clearance in oral cavity</a></div></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td background="../root/msite/dt/img_3.jpg">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="67">&nbsp;</td>
        <td align="center" valign="middle" background="../root/msite/dt/button2.png"><div align="center" class="dt_text_menu1_style"><a style="color: #660000"   href="http://www.eurodonetsk.com/index.php?business_full=536&pm=4">Oral cavity is the <br />
          mirror of stomach!</a></div></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td background="../root/msite/dt/img_4.jpg">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="65">&nbsp;</td>
        <td align="center" valign="middle" background="../root/msite/dt/button2.png"><div align="center" class="dt_text_menu1_style"><a style="color: #660000"   href="http://www.eurodonetsk.com/index.php?business_full=536&pm=5">Absolute harmony <br />
          titanium with ceramic</a></div></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
    </table></td>
  </tr>
</table>

</div> <!-- cat_ite_cont_m -->

<?php

}

else

   if ($_GET['pm'] == 7)

   {

?>

<div class="catalogue_item_cont_m"> 

	<table width="990" height="1140" cellpadding="0" cellspacing="0" align="center" border="0">
  <tr>
    <td height="457" colspan="4" background="../root/msite/dt/up_en.jpg">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="4" background="../root/msite/dt/menu_bg.png" height="81" ><div align="center">
      <table width="980" align="center" border="0">
        <tr>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff" href="index.php?business_full=536&pm=1">About us</a></td>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff"  href="index.php?business_full=536&pm=2">Articles</a></td>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff"  href="index.php?business_full=536&pm=6">Service</a></td>
          <td width="%">&nbsp;</td>
          <td width="150" height="62" align="center" background="../root/msite/dt/button.jpg" class="dt_text_menu_style"><a style="text-decoration:none; color: #ffffff"  href="index.php?business_full=536&pm=7">Contacts</a></td>
          <td width="%">&nbsp;</td>
        </tr>
      </table>
    </div></td>
  </tr>
  <tr>
    <td colspan="4" background="../root/msite/dt/main_bg.jpg" height="962"><table width="100%" height="867" border="0">
      <tr>
        <td width="30" height="50">&nbsp;</td>
        <td width="10">&nbsp;</td>
        <td width="53">&nbsp;</td>
        <td width="780">&nbsp;</td>
        <td width="95">&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td rowspan="3">&nbsp;</td>
        <td>&nbsp;</td>
        <td rowspan="8" valign="top">
          <table width="100%" border="0">
            <tr>
              <td>
              <div>

        <script src="http://api-maps.yandex.ru/1.1/index.xml?key=AAmDzUsBAAAARkVWCAIAXzMCgKN58_MQUqB134Sdp-unCH0AAAAAAAAAAACbJlz2mcKc4anRgbxx6LBZ5BHPyg==" type="text/javascript"></script>

    <script type="text/javascript">

        window.onload = function () {

            var map = new YMaps.Map(document.getElementById("YMapsID"));

            map.setCenter(new YMaps.GeoPoint(37.801871,48.010956), 17);



            var content = document.createElement('span');

            content.innerHTML = "Dent-Titan";

            map.openBalloon(new YMaps.GeoPoint(37.801871,48.010956), content);



            map.addControl(new YMaps.ToolBar());

            map.addControl(new YMaps.Zoom());

            map.addControl(new YMaps.MiniMap());

            map.addControl(new YMaps.ScaleLine());

        }

    </script>





	 <div id="YMapsID" style="width:90%; height:500px; position:relative; float:center; top:20px; left:40px; z-index:20; margin-bottom:40px;"></div>

   </div>
              </td>
			  <p align="center" class="dt_text_h2_3_style">Address:</p>
          <p align="center" class="dt_text_h2_3_style">83055, Ukraine, Donetsk city,</p>
          <p align="center" class="dt_text_h2_3_style">Artema Street, 88-а,<br />
              <br />
              <strong>«Dent-Titan»</strong></p>
          <p align="center" class="dt_text_h2_3_style">Tel/Fax: +38 (062) 335 – 78 - 76</p>
          </tr>
          </table>
          </td>
        
      </tr>
      <tr>
        <td height="70">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="79">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="69">&nbsp;</td>
        <td align="center" valign="middle">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="67">&nbsp;</td>
        <td align="center" valign="middle">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="149">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td height="65">&nbsp;</td>
        <td align="center" valign="middle">&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
    </table></td>
  </tr>
</table>


</div> <!-- cat_ite_cont_m -->

<?php

   } 

?>







<div id="catalogue_item_menu">



<div class="catalogue_item_mp_a">



<a href="index.php?section_id=32&amp;business=1">Категория:</a></div>



</div>



<div class="catalogue_item_cont">



<a href="index.php?section_id=2&amp;business=1">бизнес</a>



 / 



<a href="index.php?section_id=32&amp;business=1">предприятия</a>



 / 



<a href="index.php?section_id=387&amp;business=2">Медицина</a>



 / 



<a href="index.php?section_id=511&business=2">Стоматология</a>



</div>











<div id="catalogue_item_menu">



<div class="catalogue_item_mp_a">



<a href="">Фотогалегея:</a></div>



</div>



<div class="catalogue_item_cont">



</div>



<div id="catalogue_item_menu">



<div class="catalogue_item_mp_a">



<a href="">Контактная информация:</div>



</div>



 <div class="catalogue_item_cont">



 		 <table width="100%">



			<tbody>



 			<tr>



			<!--	<td><img class="main_sec_image" src="" width="60" height="60" border="0" alt="" /></td>-->



				<td>Адрес:</td>



				<td>Телефон:</td>



				<td>Моб.:</td>



				<td>E-mail:</td>



				<td>Веб-сайт:</td>



			</tr>



			<tr>



				<td>г. Донецк, ул. Артема, 88-а</td>



				<td>+38 (062) 335–78-76</td>



				<td></td>



				<td></td>



				<td></td>



			</tr>

			</tbody> 

		 </table> 		

	 </div>

</div>  





