 <div class="catalogue_item_c">
<style>

html,body{}

.catalogue_item_c a {color: #000000;}

.catalogue_item_cont p {
color:#000000;
text-align:justify;
text-indent:0px;
line-height:20px;
margin:0px; 
}

img.main_sec_image {
border:none;
}
.catalogue_item_cont_m {
background-color:#FFFFFF;
border:1px solid lightgray;
color:#000000;
margin:0;
margin:15px 10px 10px;
width:980px;
}
.catalogue_item_cont {
background-color:#ffffff;
border-top:1px solid lightgray;
margin:0 0 7px 10px;
width:980px;
color:#000000;

}
.catalogue_item_c {
background-color:#F3F3F3;
font-family: century gotic;
}

a.menu_text {font-size:18px;font-weight:bold;color:#ffffff;}

img.main_sec_image {
height:240px;
padding:0;
width:240px;
}

.catalogue_item_cont a {
color:#000000;
}
.catalogue_item_cont a:hover {
color:#000000;
text-decoration:underline;
}
.catalogue_item_mp_a {
left:3px;
position:relative;
}

#m_menuu {margin:3px 0 10px 25px;}
table.menu_d td{height:30px;min-width:133px;text-align:center;}
table.menu_d td a {font-size:12px;font-weight:bold;color:#000000;}
table.menu_d td:hover a{text-decoration:none;color:#FFFFFF;}
table.menu_d td:hover{background:url('../root/msite/aurora/m_under.png') no-repeat 100% 0;}

#left_c_ms {width:225px;padding:0 20px 0 25px;vertical-align:top;}
#right_c_ms {vertical-align:top;line-height:20px;font-size:14px;}

#conf_table tr td {width:150px;}
</style>
<?php
if ($_GET['pm'] == 1) 
{
?>

<div class="catalogue_item_cont_m">
<div>
 <table cellpadding="0" cellspacing="0" class="menu_d" id="m_menuu"><tr>
  <td><a href="index.php?business_full=397&pm=1">ГЛАВНАЯ</a></td>
  <td><a href="index.php?business_full=397&pm=2">НОМЕРА</a></td>
  <td><a href="index.php?business_full=397&pm=3">КАФЕ</a></td>
  <td><a href="">МЕНЮ</a></td>
  <td width="155" style="min-width:165px;"><a href="index.php?business_full=397&pm=4">КОНФЕРЕНЦ УСЛУГИ</a></td>
  <td><a href="index.php?business_full=397&pm=5">КОНТАКТЫ</a></td>
 </tr></table> 
</div>
<table cellpadding="0" cellspacing="0">
 <tr>
 <td id="left_c_ms"><div><img src="../root/msite/aurora/logo.png"/ style="margin-bottom:5px;"><a href="http://www.auroradonetsk.com"><img src="../root/msite/aurora/logo3.png" width="225"/></a></div></td>
 <td  id="right_c_ms"><div><img src="../root/msite/aurora/logo2.png" width="700"/>
 <div style="font-size:20px;font-weight:bold;margin:25px 0;">Добро пожаловать!</div>
 <div style="text-align:left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;К услугам гостей <font color="#990000">Отеля «Аврора»:</font></div>
 <img src="../root/msite/aurora/first.png" style="margin:10px 0;width:695px;" />
 <div style="text-align:justify;width:695px;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;38 комфортабельных гостиничных номеров, которые соответствуют европейским стандартам. 1-но, 2-х, 3-х местные номера со всеми удобствами, вежливый обслуживающий персонал обеспечат вам достойное пребывание вне дома. Проживающим - бесплатная парковка для автомобилей.</div>
 <br>
 <div style="text-align:justify;width:695px;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#990000">Кафе «Орфей»</font> - уютная атмосфера, изысканный дизайн интерьера, блюда европейской кухни, зал на 35 персон.</div>
 <img src="../root/msite/aurora/second.png" style="margin:10px 0;width:695px;" />
 <div style="text-align:justify;width:695px;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#990000">Конфереренц-зал</font> для проведения деловых встреч, оснащенный современным оборудование.</div>
 <br>
 <div style="text-align:justify;width:695px;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Безпроводной доступ к Интернету (WiFi)</div>
 <br>
 <div style="text-align:justify;width:695px;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#990000">Гостиница «Аврора»</font> предоставляет широкий спектр возможностей в организации конференций, семинаров. Соответствующий уровень комфорта и сервиса, безупречное обслуживание, настроит Вас на хороший отдых и успешное проведение деловых мероприятий.</div>
 <br><br>
</td>
 </tr>
</table>
</div>
 <?php
}
else
   if ($_GET['pm'] == 2)
   {
?>
<div class="catalogue_item_cont_m">
<div>
 <table cellpadding="0" cellspacing="0" class="menu_d" id="m_menuu"><tr>
  <td><a href="index.php?business_full=397&pm=1">ГЛАВНАЯ</a></td>
  <td><a href="index.php?business_full=397&pm=2">НОМЕРА</a></td>
  <td><a href="index.php?business_full=397&pm=3">КАФЕ</a></td>
  <td><a href="">МЕНЮ</a></td>
  <td width="155" style="min-width:165px;"><a href="index.php?business_full=397&pm=4">КОНФЕРЕНЦ УСЛУГИ</a></td>
  <td><a href="index.php?business_full=397&pm=5">КОНТАКТЫ</a></td>
 </tr></table> 
</div>
<table cellpadding="0" cellspacing="0">
 <tr>
 <td id="left_c_ms"><div><img src="../root/msite/aurora/logo.png"/ style="margin-bottom:5px;"><a href="http://www.auroradonetsk.com"><img src="../root/msite/aurora/logo3.png" width="225"/></a></div></td>
 <td  id="right_c_ms"><div><img src="../root/msite/aurora/logo2.png" width="700" style="float: left;"/> </div>
 <div style="text-align:left;margin-top:370px;"><b><font color="#990000">Одноместный стандартный номер - <font style="font-size:24px;">370</font> грн</font></b></div>
 <br>
 <table>
  <tr>
   <td style="vertical-align:top;"><img src="../root/msite/aurora/n1.png"/ style=""></td>
   <td style="vertical-align:top;padding-left:10px;text-align:left;">Жилая площадь номера 17 кв.м <br>
      Размер кровати - 90x190 см <br>
      Рабочий стол <br>
      Внутренняя телефонная линия <br>
      Совмещённый санузел <br>
      Душевая кабина <br>
      Туалетные принадлежности <br>
      Телевизор <br>
      Кондиционер <br>
      Холодильник <br>
      Минеральная вода (1 бутылка) <br>
      Завтрак   
   </td>
  </tr>
 </table>
 <br>
 <div style="text-align:left;"><b><font color="#990000">Одноместный номер повышенной комфортности <br> &nbsp;&nbsp;&nbsp; - одноместное размещение <font style="font-size:24px;">390</font> грн<br> &nbsp;&nbsp;&nbsp; - двухместное размещение <font style="font-size:24px;">440</font> грн</font></b></div>
  <br>
 <table>
  <tr>
   <td style="vertical-align:top;"><img src="../root/msite/aurora/n2.png"/ style=""></td>
   <td style="vertical-align:top;padding-left:10px;text-align:left;">Жилая площадь номера 17 кв.м <br>
      Размер кровати - 120x200 см <br>
      Рабочий стол <br>
      Внутренняя телефонная линия <br>
      Совмещённый санузел <br>
      Душевая кабина <br>
      Туалетные принадлежности <br>
      Телевизор <br>
      Кондиционер <br>
      Холодильник <br>
      Минеральная вода (1 бутылка) <br>
      Завтрак (при двухмесном размещении завтрак на 2 персоны)  
   </td>
  </tr>
 </table>
 <br>
 <div style="text-align:left;"><b><font color="#990000">Двухместный двухкомнатный номер с двуспальной кроватью - <font style="font-size:24px;">480</font> грн</font></b></div>
 <br>
 <table>
  <tr>
   <td style="vertical-align:top;"><img src="../root/msite/aurora/n3.png"/ style=""></td>
   <td style="vertical-align:top;padding-left:10px;text-align:left;">Жилая площадь номера 30 кв.м <br>
      Размер кровати - 160x200 см <br>
      Диван <br>
      Внутренняя телефонная линия <br>
      Совмещённый санузел <br>
      Душевая кабина <br>
      Туалетные принадлежности <br>
      Телевизор <br>
      Кондиционер <br>
      Холодильник <br>
      Минеральная вода (2 бутылки) <br>
      Завтрак на 2 персоны  
   </td>
  </tr>
 </table>
 <br>
 <div style="text-align:left;"><b><font color="#990000">Двухместный двухкомнатный номер - <font style="font-size:24px;">480</font> грн</font></b></div>
 <br>
 <table>
  <tr>
   <td style="vertical-align:top;"><img src="../root/msite/aurora/n4.png"/ style=""></td>
   <td style="vertical-align:top;padding-left:10px;text-align:left;">Жилая площадь номера 30 кв.м <br>
      Размер кровати - 90х190 см<br>
      Диван <br>
      Внутренняя телефонная линия <br>
      Совмещённый санузел <br>
      Душевая кабина <br>
      Туалетные принадлежности <br>
      Телевизор <br>
      Кондиционер <br>
      Холодильник <br>
      Минеральная вода (2 бутылки) <br>
      Завтрак на 2 персоны  
   </td>
  </tr>
 </table>
 <br>
 <div style="text-align:left;"><b><font color="#990000">Трехместный двухкомнатный номер - <font style="font-size:24px;">600</font> грн</font></b></div>
 <br>
 <table>
  <tr>
   <td style="vertical-align:top;"><img src="../root/msite/aurora/n5.png"/ style=""></td>
   <td style="vertical-align:top;padding-left:10px;text-align:left;">Жилая площадь номера 30 кв.м <br>
      Размер кровати - 90х190 см<br>
      Рабочий стол <br>
      Внутренняя телефонная линия <br>
      Совмещённый санузел <br>
      Душевая кабина <br>
      Туалетные принадлежности <br>
      Телевизор <br>
      Кондиционер <br>
      Холодильник <br>
      Минеральная вода (3 бутылки) <br>
      Завтрак на 3 персоны  
   </td>
  </tr>
 </table>
 <br>
 <div style="text-align:left;"><b><font color="#990000">Люкс - <font style="font-size:24px;">650</font> грн</font></b></div>
 <br>
 <table>
  <tr>
   <td style="vertical-align:top;"><img src="../root/msite/aurora/n6.png"/ style=""></td>
   <td style="vertical-align:top;padding-left:10px;text-align:left;">Жилая площадь номера 30 кв.м <br>
      Размер кровати - 160х200 см<br>
      Внутренняя телефонная линия <br>
      Совмещённый санузел <br>
      Туалетные принадлежности <br>
      Душевая кабина <br>
      Халат, тапочки <br>
      Фен <br>      
      ЖК телевизор 32" <br>
      DVD-проигрыватель <br>
      Кондиционер <br>
      Холодильник <br>
      Чайник, набор посуды <br>
      Мини бар <br>
      Минеральная вода (2 бутылки) <br>
      Завтрак на 2 персоны  
   </td>
  </tr>
 </table>
</td>
 </tr>
</table>
</div>

<?php
}
else
   if ($_GET['pm'] == 3)
   {
?>
<div class="catalogue_item_cont_m">
<div>
 <table cellpadding="0" cellspacing="0" class="menu_d" id="m_menuu"><tr>
  <td><a href="index.php?business_full=397&pm=1">ГЛАВНАЯ</a></td>
  <td><a href="index.php?business_full=397&pm=2">НОМЕРА</a></td>
  <td><a href="index.php?business_full=397&pm=3">КАФЕ</a></td>
  <td><a href="">МЕНЮ</a></td>
  <td width="155" style="min-width:165px;"><a href="index.php?business_full=397&pm=4">КОНФЕРЕНЦ УСЛУГИ</a></td>
  <td><a href="index.php?business_full=397&pm=5">КОНТАКТЫ</a></td>
 </tr></table> 
</div>
<table cellpadding="0" cellspacing="0">
 <tr>
 <td id="left_c_ms"><div><img src="../root/msite/aurora/logo.png"/ style="margin-bottom:5px;"><a href="http://www.auroradonetsk.com"><img src="../root/msite/aurora/logo3.png" width="225"/></a></div></td>
 <td  id="right_c_ms"><div><img src="../root/msite/aurora/logo2.png" width="700" style="float: left;"/> </div>
 <div style="text-align:center;margin-top:370px;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#990000">Кафе «Орфей»</font> приглашает Вас насладиться изысканными блюдами европейской кухни! Элегантный, уютный интерьер зала, высокий уровень обслуживания распологает как к деловой встрече, так и к романтическому ужину на двоих.</div>
 <br>
 <div style="text-align:center"><b>Режим работы:<br><font color="#990000">c 7.30 - 22.00<br>без выходных<br><br>завтраки, обеды, ужины, кофе-паузы, банкеты, фуршеты</font></b></div>
 <img src="../root/msite/aurora/cafe.png" style="margin:10px 0;width:695px;" />
 <br><br>
</td>
 </tr>
</table>
</div>
<?php
}
else
   if ($_GET['pm'] == 4)
   {
?>
<div class="catalogue_item_cont_m">
<div>
 <table cellpadding="0" cellspacing="0" class="menu_d" id="m_menuu"><tr>
  <td><a href="index.php?business_full=397&pm=1">ГЛАВНАЯ</a></td>
  <td><a href="index.php?business_full=397&pm=2">НОМЕРА</a></td>
  <td><a href="index.php?business_full=397&pm=3">КАФЕ</a></td>
  <td><a href="">МЕНЮ</a></td>
  <td width="155" style="min-width:165px;"><a href="index.php?business_full=397&pm=4">КОНФЕРЕНЦ УСЛУГИ</a></td>
  <td><a href="index.php?business_full=397&pm=5">КОНТАКТЫ</a></td>
 </tr></table> 
</div>
<table cellpadding="0" cellspacing="0">
 <tr>
 <td id="left_c_ms"><div><img src="../root/msite/aurora/logo.png"/ style="margin-bottom:5px;"><a href="http://www.auroradonetsk.com"><img src="../root/msite/aurora/logo3.png" width="225"/></a></div></td>
 <td  id="right_c_ms"><div><img src="../root/msite/aurora/logo2.png" width="700" style="float: left;"/> </div>
 <div style="text-align:justify;margin-top:370px;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Для проведения официальных встреч, деловых переговоров, семинаров, пресс-конференций и тренингов гостиница «Аврора» предлагает Вам воспользоваться услугами нашего конференц-зала.</div>
 <img src="../root/msite/aurora/conf.png" style="margin:10px 0;width:695px;" />
 <div style="text-align:justify;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Общая площадь конференц-зала отеля "Аврора" (Донецк) - 47 м2. 
<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Вместимость конференц-зала до 40 человек
<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Варианты расстановок: «класс», «театр», «круглый стол» и др. по Вашему желанию.</div>
<br>
<div style="text-align:justify;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#990000"><b>Оборудование конференц-зала</b></font> </div>
<div style="text-align:justify;">
 <ul style="padding-left:35px;width:665px;text-align:left;">
  <li>Конференц-зал оснащен системой центральной вентиляции и двумя раздельными кондиционерами</li>
  <li>Затемнение зала светонепроницаемыми шторами BLACK-OUT (затемнение 100%)</li>
  <li>Конференц-зал оборудован моторизованным проекционным экраном, мультимедийным проектором</li>
  <li>Установлен AV - процессор/усилитель и система озвучивания, DVD - проигрыватель</li>
  <li>Возможность подключения компьютера и другой аудио/видео техники</li>
  <li>Напольный флипчарт (магнитно-маркерная доска) размером 100х65 см</li>
  <li>Две настенные пробковые доски размерами 120х90 см., для развешивания информационных и наглядных материалов</li>
 </ul>
 <br>
</div>
<div style="text-align:justify;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#990000"><b>Стоимость аренды конференц-зала г. Донецк:</b></font> </div>
<table style="border:1px solid gray;" cellpadding="0" cellspacing="0" id="conf_table">
 <tr>
  <td style="border:1px solid gray;">Первый час <br>грн.</td><td style="border:1px solid gray;">Последующий час <br>грн.</td><td style="border:1px solid gray;">Полный день  <br>(с 9.00 до 18.00) <br>грн.</td>
 </tr>
 <tr>
  <td style="border:1px solid gray;">150</td><td style="border:1px solid gray;">100</td><td style="border:1px solid gray;">800</td>
 </tr>
</table>
<br>
 <ul style="padding-left:35px;width:665px;text-align:left;">
  <li>Оборудование, входящее в стоимость аренды зала: WiFi, моторизованный проекционный экран, флип чарт.</li> 
 </ul>
 <br>
  <div style="text-align:justify;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#990000"><b>Дополнительное оборудования:</b></font> </div>
  <ul style="padding-left:35px;width:665px;text-align:left;">
  <li>мультимедийный проектор - 350 грн/день </li>
  <li>DVD проигрыватель – 150 грн/день</li> 
 </ul>
  <br>
   <div style="text-align:justify;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Организацию кофе-брейков, обедов, ужинов, банкетов и фуршетов возьмет на себя вежливый и ответственный персонал кафе «Орфей».</div>
 <br><br>
</td>
 </tr>
</table>
</div>
<?php
}
else
   if ($_GET['pm'] == 5)
   {
?>

<div class="catalogue_item_cont_m">
<div>
 <table cellpadding="0" cellspacing="0" class="menu_d" id="m_menuu"><tr>
  <td><a href="index.php?business_full=397&pm=1">ГЛАВНАЯ</a></td>
  <td><a href="index.php?business_full=397&pm=2">НОМЕРА</a></td>
  <td><a href="index.php?business_full=397&pm=3">КАФЕ</a></td>
  <td><a href="">МЕНЮ</a></td>
  <td width="155" style="min-width:165px;"><a href="index.php?business_full=397&pm=4">КОНФЕРЕНЦ УСЛУГИ</a></td>
  <td><a href="index.php?business_full=397&pm=5">КОНТАКТЫ</a></td>
 </tr></table> 
</div>
<table cellpadding="0" cellspacing="0">
 <tr>
 <td id="left_c_ms"><div><img src="../root/msite/aurora/logo.png" width="225" style="margin-bottom:5px;"/><img src="../root/msite/aurora/logo4.png" width="225"/></div></td>
 <td  id="right_c_ms"><div><img src="../root/msite/aurora/logo2.png" width="700"/>
 <div style="text-align:left;margin-left:25px;"><b>Наш адрес:</b>
<br>
83008, Донецкая область, г.Донецк, ул.Югославская 36-Г
<br><br>
<a href="http://www.auroradonetsk.com">http://www.auroradonetsk.com</a>
<br>
hotel@auroradonetsk.com
<br><br>
<b>Администратор: </b> 
<br>
&nbsp;&nbsp;&nbsp;+38 (062) 310-15-95
<br>
&nbsp;&nbsp;&nbsp;+38 (050) 764-41-61
<br>
т/ф. +38 (062) 310-15-96
<br>
skype hotelaurora.ua
<br>
e-mail hotel@auroradonetsk.com
<br><br>
<b>Конференц-сервис:</b>
<br>
&nbsp;&nbsp;&nbsp;+38 (062) 310-15-95
<br>
&nbsp;&nbsp;&nbsp;+38 (095) 016-51-65
<br>
e-mail conference@auroradonetsk.com
</div>
<br><br>
</td>
 </tr>
</table> 

<script src="http://api-maps.yandex.ru/1.1/index.xml?key=AAmDzUsBAAAARkVWCAIAXzMCgKN58_MQUqB134Sdp-unCH0AAAAAAAAAAACbJlz2mcKc4anRgbxx6LBZ5BHPyg==" type="text/javascript"></script>
    <script type="text/javascript">
        window.onload = function () {
            var map = new YMaps.Map(document.getElementById("YMapsID"));
            map.setCenter(new YMaps.GeoPoint(37.748537,48.00529), 14);

            var content = document.createElement('span');
            content.innerHTML = "«Аврора»";
            map.openBalloon(new YMaps.GeoPoint(37.748537,48.00529), content);

            map.addControl(new YMaps.ToolBar());
            map.addControl(new YMaps.Zoom());
            map.addControl(new YMaps.MiniMap());
            map.addControl(new YMaps.ScaleLine());
        }
    </script>


	 <div id="YMapsID" style="height:450px;margin:0 0 0 25px;width:943px;"></div>
</div>  
    

<?php
   } 
?>



<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="index.php?section_id=32&amp;business=1">Категория:</a></div>
</div>
<div class="catalogue_item_cont">
<a href="index.php?section_id=2&amp;business=1">бизнес</a>
 / 
<a href="index.php?section_id=32&amp;business=1">предприятия</a>
 / 
<a href="index.php?section_id=389&amp;business=2">отдых и развлечения</a>
 / 
<a href="index.php?section_id=327&amp;business=2">гостиницы</a>
</div>


<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="">Фотогалерея:</a></div>
</div>
<div class="catalogue_item_cont">
<div class="catalogue_pic_l"><a href="root/msite/aurora/gallery/1.jpg" target="_blank"><img src="root/msite/aurora/gallery/1_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/aurora/gallery/2.jpg" target="_blank"><img src="root/msite/aurora/gallery/2_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/aurora/gallery/3.jpg" target="_blank"><img src="root/msite/aurora/gallery/3_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/aurora/gallery/4.jpg" target="_blank"><img src="root/msite/aurora/gallery/4_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/aurora/gallery/5.jpg" target="_blank"><img src="root/msite/aurora/gallery/5_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/aurora/gallery/6.jpg" target="_blank"><img src="root/msite/aurora/gallery/6_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/aurora/gallery/7.jpg" target="_blank"><img src="root/msite/aurora/gallery/7_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/aurora/gallery/8.jpg" target="_blank"><img src="root/msite/aurora/gallery/8_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/aurora/gallery/9.jpg" target="_blank"><img src="root/msite/aurora/gallery/9_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/aurora/gallery/10.jpg" target="_blank"><img src="root/msite/aurora/gallery/10_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/aurora/gallery/11.jpg" target="_blank"><img src="root/msite/aurora/gallery/11_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/aurora/gallery/12.jpg" target="_blank"><img src="root/msite/aurora/gallery/12_s.jpg" width="60" height="60" border="0" alt=""></a></div>
</div>
<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="">Контактная информация:</div>
</div>
 <div class="catalogue_item_cont">
 		 <table width="100%">
			<tbody>
 			<tr>
			<!--	<td><img class="main_sec_image" src="" width="60" height="60" border="0" alt="" /></td>-->
				<td>Адрес:</td>
				<td>Телефон:</td>
				<td>Факс:</td>
				<td>E-mail:</td>
				<td>Веб-сайт:</td>
			</tr>
			<tr>
				<td>83008, г. Донецк<br> ул.Югославская 36-Г</td>
				<td>(062) 310-15-95<br>(050) 764-4161</td>
				<td>(062) 310-15-96</td>
				<td>hotel@auroradonetsk.com</td>
				<td>http://www.auroradonetsk.com</td>

			</tr>
			</tbody> 
		 </table> 		
	 </div>
</div>  

