 <div class="catalogue_item_c">
<style>

html,body{}

.catalogue_item_c a {color: #000000;}

.catalogue_item_cont p {
color:#000000;
text-align:justify;
text-indent:0px;
line-height:20px;
margin:0px; 
}

img.main_sec_image {
border:none;
}
.catalogue_item_cont_m {
background-color:#FFFFFF;
border:1px solid lightgray;
color:#000000;
margin:0;
margin:15px 10px 10px;
width:980px;
}
.catalogue_item_cont {
background-color:#ffffff;
border-top:1px solid lightgray;
margin:0 0 7px 10px;
width:980px;
color:#000000;

}
.catalogue_item_c {
background-color:#F3F3F3;
font-family: century gotic;
}

a.menu_text {font-size:18px;font-weight:bold;color:#ffffff;}

img.main_sec_image {
height:240px;
padding:0;
width:240px;
}

.catalogue_item_cont a {
color:#000000;
}
.catalogue_item_cont a:hover {
color:#000000;
text-decoration:underline;
}
.catalogue_item_mp_a {
left:3px;
position:relative;
}

#m_menuu {margin:3px 0 10px 25px;}
table.menu_d td{height:30px;min-width:133px;text-align:center;}
table.menu_d td a {font-size:12px;font-weight:bold;color:#000000;}
table.menu_d td:hover a{text-decoration:none;color:#FFFFFF;}
table.menu_d td:hover{background:url('../root/msite/aurora/m_under.png') no-repeat 100% 0;}

#left_c_ms {width:225px;padding:0 20px 0 25px;vertical-align:top;}
#right_c_ms {vertical-align:top;line-height:20px;font-size:14px;}

#conf_table tr td {width:150px;}
</style>
<?php
if ($_GET['pm'] == 1) 
{
?>

<div class="catalogue_item_cont_m">
<div>
 <table cellpadding="0" cellspacing="0" class="menu_d" id="m_menuu"><tr>
  <td><a href="index.php?business_full=398&pm=1">MAIN</a></td>
  <td><a href="index.php?business_full=398&pm=2">ROOMS</a></td>
  <td><a href="index.php?business_full=398&pm=3">CAFE</a></td>
  <td><a href="">MENU</a></td>
  <td width="155" style="min-width:165px;"><a href="index.php?business_full=398&pm=4">CONFERENCE SERVICES</a></td>
  <td><a href="index.php?business_full=398&pm=5">CONTACTS</a></td>
 </tr></table> 
</div>
<table cellpadding="0" cellspacing="0">
 <tr>
 <td id="left_c_ms"><div><img src="../root/msite/aurora/logo_e.png"/ style="margin-bottom:5px;"><a href="http://www.auroradonetsk.com"><img src="../root/msite/aurora/logo3_e.png" width="225"/></a></div></td>
 <td  id="right_c_ms"><div><img src="../root/msite/aurora/logo2_e.png" width="700"/>
 <div style="font-size:20px;font-weight:bold;margin:25px 0;">WELCOME!</div>
 <div style="text-align:left">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#990000">AURORA Hotel offers its guests:</font></div>
 <img src="../root/msite/aurora/first.png" style="margin:10px 0;width:695px;" />
 <div style="text-align:justify;width:695px;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;38 comfortable hotel rooms, which meet all European standards. Single, Double and  Triple rooms are equipped with all the latest comforts and services. Professional, attentive staff truly committed to do everything possible to satisfy our guests. Free parking.</div>
 <br>
 <div style="text-align:justify;width:695px;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#990000">“Orpheus” Café</font> provides a comfortable atmosphere, exquisite design, European cuisine, Hall for 35 Seats. </div>
 <img src="../root/msite/aurora/second.png" style="margin:10px 0;width:695px;" />
 <div style="text-align:justify;width:695px;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;You can book our <font color="#990000">conference room</font> and focus on your business activity.</div>
 <br>
 <div style="text-align:justify;width:695px;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Wi-Fi Internet Access is available in our café.</div>
 <br>
 <div style="text-align:justify;width:695px;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#990000">Aurora Hotel</font> is equipped with all the necessary for holding business meetings, seminars and conferences. The caring personnel is going to help you to find yourself in the pleasant homelike environment and to manage that business meetings to be surrounded with care!</div>
 <br><br>
</td>
 </tr>
</table>
</div>
 <?php
}
else
   if ($_GET['pm'] == 2)
   {
?>
<div class="catalogue_item_cont_m">
<div>
 <table cellpadding="0" cellspacing="0" class="menu_d" id="m_menuu"><tr>
  <td><a href="index.php?business_full=398&pm=1">MAIN</a></td>
  <td><a href="index.php?business_full=398&pm=2">ROOMS</a></td>
  <td><a href="index.php?business_full=398&pm=3">CAFE</a></td>
  <td><a href="">MENU</a></td>
  <td width="155" style="min-width:165px;"><a href="index.php?business_full=398&pm=4">CONFERENCE SERVICES</a></td>
  <td><a href="index.php?business_full=398&pm=5">CONTACTS</a></td>
 </tr></table> 
</div>
<table cellpadding="0" cellspacing="0">
 <tr>
 <td id="left_c_ms"><div><img src="../root/msite/aurora/logo_e.png"/ style="margin-bottom:5px;"><a href="http://www.auroradonetsk.com"><img src="../root/msite/aurora/logo3_e.png" width="225"/></a></div></td>
 <td  id="right_c_ms"><div><img src="../root/msite/aurora/logo2_e.png" width="700" style="float: left;"/> </div>
 <div style="text-align:left;margin-top:370px;"><b><font color="#990000">Standard single room - <font style="font-size:24px;">370</font> UAH</font></b></div>
 <br>
 <table>
  <tr>
   <td style="vertical-align:top;"><img src="../root/msite/aurora/n1.png"/ style=""></td>
   <td style="vertical-align:top;padding-left:10px;text-align:left;">Living space: 17 sq.m<br>
      One single bed - 90х190 cm<br>
      Worktable<br>
      Local telephone network <br>
      Bathroom unit<br>
      Shower cabin<br>
      Toiletware<br>
      TV <br>
      Air conditioner <br>
      Refrigerator <br>
      Mineral water (1 bottle) <br>
      The price of the room includes breakfast    
   </td>
  </tr>
 </table>
 <br>
 <div style="text-align:left;"><b><font color="#990000">Single comfort <br> &nbsp;&nbsp;&nbsp; - Price for single accomodation <font style="font-size:24px;">390</font> UAH<br> &nbsp;&nbsp;&nbsp; - Price for double accommodation <font style="font-size:24px;">440</font> UAH</font></b></div>
  <br>
 <table>
  <tr>
   <td style="vertical-align:top;"><img src="../root/msite/aurora/n2.png"/ style=""></td>
   <td style="vertical-align:top;padding-left:10px;text-align:left;">Living space:  17 sq.m<br>
      Bed - 120х200 cm <br>
      Worktable<br>
      Local telephone network<br>
      Bathroom unit<br>
      Shower cabin<br>
      Toiletware <br>
      TV <br>
      Air conditioner <br>
      Refrigerator <br>
      Mineral water (1 bottle)  <br>
      The price of the room includes breakfast  
   </td>
  </tr>
 </table>
 <br>
 <div style="text-align:left;"><b><font color="#990000">Two – room double - <font style="font-size:24px;">480</font> UAH</font></b></div>
 <br>
 <table>
  <tr>
   <td style="vertical-align:top;"><img src="../root/msite/aurora/n3.png"/ style=""></td>
   <td style="vertical-align:top;padding-left:10px;text-align:left;">Living space  30 sq.m <br>
      Bed  - 160х200 см <br>
      Sofa <br>
      Local telephone network <br>
      Bathroom unit  <br>
      Shower cabin <br>
      Toiletware<br>
      TV <br>
      Air conditioner <br>
      Refrigerator <br>
      Mineral water (2 bottles)  <br>
      Breakfast for two persons  
   </td>
  </tr>
 </table>
 <br>
 <div style="text-align:left;"><b><font color="#990000">Two – Room twin - <font style="font-size:24px;">480</font> UAH</font></b></div>
 <br>
 <table>
  <tr>
   <td style="vertical-align:top;"><img src="../root/msite/aurora/n4.png"/ style=""></td>
   <td style="vertical-align:top;padding-left:10px;text-align:left;">Living space  30 sq.m <br>
      Bed - 90х190 см <br>
      Sofa <br>
      Local telephone network <br>
      Bathroom unit  <br>
      Shower cabin <br>
      Toiletware<br>
      TV <br>
      Air conditioner <br>
      Refrigerator <br>
      Mineral water (2 bottles)  <br>
      Breakfast for two persons  
   </td>
  </tr>
 </table>
 <br>
 <div style="text-align:left;"><b><font color="#990000">Two roms triple - <font style="font-size:24px;">600</font> UAH</font></b></div>
 <br>
 <table>
  <tr>
   <td style="vertical-align:top;"><img src="../root/msite/aurora/n5.png"/ style=""></td>
   <td style="vertical-align:top;padding-left:10px;text-align:left;">Living space  30 sq.m <br>
      Bed - 90х190 см <br>
      Worktable <br>
      Local telephone network <br>
      Bathroom unit  <br>
      Shower cabin <br>
      Toiletware<br>
      TV <br>
      Air conditioner <br>
      Refrigerator <br>
      Mineral water (3 bottles)  <br>
      Breakfast for three  persons  
   </td>
  </tr>
 </table>
 <br>
 <div style="text-align:left;"><b><font color="#990000">Suite - <font style="font-size:24px;">650</font> UAH</font></b></div>
 <br>
 <table>
  <tr>
   <td style="vertical-align:top;"><img src="../root/msite/aurora/n6.png"/ style=""></td>
   <td style="vertical-align:top;padding-left:10px;text-align:left;">Living space  30 sq.m <br>
      Bed size - 160х200 cm<br>
      Local telephone network <br>
      Bathroom unit  <br>
      Shower cabin <br>
      Toiletware<br>
      Bathrobe and slippers <br>
      Hair dryer <br>      
      LCD television  <br>
      DVD <br>
      Air conditioner <br>
      Refrigerator <br>
      Teapot, dining set  <br>
      Mini bar <br>
      Mineral water (2 bottles) <br>
      Breakfast for two  persons 
   </td>
  </tr>
 </table>
</td>
 </tr>
</table>
</div>

<?php
}
else
   if ($_GET['pm'] == 3)
   {
?>
<div class="catalogue_item_cont_m">
<div>
 <table cellpadding="0" cellspacing="0" class="menu_d" id="m_menuu"><tr>
  <td><a href="index.php?business_full=398&pm=1">MAIN</a></td>
  <td><a href="index.php?business_full=398&pm=2">ROOMS</a></td>
  <td><a href="index.php?business_full=398&pm=3">CAFE</a></td>
  <td><a href="">MENU</a></td>
  <td width="155" style="min-width:165px;"><a href="index.php?business_full=398&pm=4">CONFERENCE SERVICES</a></td>
  <td><a href="index.php?business_full=398&pm=5">CONTACTS</a></td>
 </tr></table> 
</div>
<table cellpadding="0" cellspacing="0">
 <tr>
 <td id="left_c_ms"><div><img src="../root/msite/aurora/logo_e.png"/ style="margin-bottom:5px;"><a href="http://www.auroradonetsk.com"><img src="../root/msite/aurora/logo3_e.png" width="225"/></a></div></td>
 <td  id="right_c_ms"><div><img src="../root/msite/aurora/logo2_e.png" width="700" style="float: left;"/> </div>
 <div style="text-align:center;margin-top:370px;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#990000">Orpheus café</font> invites you to taste dainty dishes of European cuisine! Elegant, cosy interior design and high- level service create a contemporary environment that is perfect for a romantic tête-a-tête in the evening or relaxed business lunch.</div>
 <br>
 <div style="text-align:center"><b>Hours:<br><font color="#990000">Monday-Friday 7.30 AM to 10.00 PM<br>Service available any time of the day 24/7<br><br>Breakfasts, dinners, lunches, coffee breaks, banquets, stand – up – meals</font></b></div>
 <img src="../root/msite/aurora/cafe.png" style="margin:10px 0;width:695px;" />
 <br><br>
</td>
 </tr>
</table>
</div>
<?php
}
else
   if ($_GET['pm'] == 4)
   {
?>
<div class="catalogue_item_cont_m">
<div>
 <table cellpadding="0" cellspacing="0" class="menu_d" id="m_menuu"><tr>
  <td><a href="index.php?business_full=398&pm=1">MAIN</a></td>
  <td><a href="index.php?business_full=398&pm=2">ROOMS</a></td>
  <td><a href="index.php?business_full=398&pm=3">CAFE</a></td>
  <td><a href="">MENU</a></td>
  <td width="155" style="min-width:165px;"><a href="index.php?business_full=398&pm=4">CONFERENCE SERVICES</a></td>
  <td><a href="index.php?business_full=398&pm=5">CONTACTS</a></td>
 </tr></table> 
</div>
<table cellpadding="0" cellspacing="0">
 <tr>
 <td id="left_c_ms"><div><img src="../root/msite/aurora/logo_e.png"/ style="margin-bottom:5px;"><a href="http://www.auroradonetsk.com"><img src="../root/msite/aurora/logo3_e.png" width="225"/></a></div></td>
 <td  id="right_c_ms"><div><img src="../root/msite/aurora/logo2_e.png" width="700" style="float: left;"/> </div>
 <div style="text-align:justify;margin-top:370px;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;AURORA Hotel offers a Conference room for holding of conferences, seminars, presentations and business meetings.</div>
 <img src="../root/msite/aurora/conf.png" style="margin:10px 0;width:695px;" />
 <div style="text-align:justify;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Area:  47 sq.m 
<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Capacity: up to 40 people
<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Style: Theatre, Classroom, Boardroom</div>
<br>
<div style="text-align:justify;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#990000"><b>Room Facilities:</b></font> </div>
<div style="text-align:justify;">
 <ul style="padding-left:35px;width:665px;text-align:left;">
  <li>Central ventilation and two air conditionings </li>
  <li>Black out blinds (100%)</li>
  <li>Projection screen and multimedia projector</li>
  <li>AV equipment - Amplifier and sound system, DVD Player</li>
  <li>Computer and audio/video connection</li>
  <li>Flipchart (100х65 cm)</li>
  <li>Two boards (120х90 cm)</li>
 </ul>
 <br>
</div>
<div style="text-align:justify;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#990000"><b> Conference room rental:</b></font> </div>
<table style="border:1px solid gray;" cellpadding="0" cellspacing="0" id="conf_table">
 <tr>
  <td style="border:1px solid gray;">First Hour <br>UAH</td><td style="border:1px solid gray;">Next hour <br>UAH</td><td style="border:1px solid gray;">The whole day<br>(from 9.00 AM till 6.00 PM) <br>UAH</td>
 </tr>
 <tr>
  <td style="border:1px solid gray;">150</td><td style="border:1px solid gray;">100</td><td style="border:1px solid gray;">800</td>
 </tr>
</table>
<br>
 <ul style="padding-left:35px;width:665px;text-align:left;">
  <li>Equipment, included in the meeting room rental rate: WiFi, Projecting screen, Flipchart</li> 
 </ul>
 <br>
  <div style="text-align:justify;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#990000"><b>Optional equipment:</b></font> </div>
  <ul style="padding-left:35px;width:665px;text-align:left;">
  <li>Multimedia projector  - 350 UAH/per day </li>
  <li>DVD player – 150 UAH/per day</li> 
 </ul>
  <br>
   <div style="text-align:justify;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Banquets, dinners, lunches, coffee breaks  and stand-up meals will organise “Orpheus” cafe </div>
 <br><br>
</td>
 </tr>
</table>
</div>
<?php
}
else
   if ($_GET['pm'] == 5)
   {
?>

<div class="catalogue_item_cont_m">
<div>
 <table cellpadding="0" cellspacing="0" class="menu_d" id="m_menuu"><tr>
  <td><a href="index.php?business_full=398&pm=1">MAIN</a></td>
  <td><a href="index.php?business_full=398&pm=2">ROOMS</a></td>
  <td><a href="index.php?business_full=398&pm=3">CAFE</a></td>
  <td><a href="">MENU</a></td>
  <td width="155" style="min-width:165px;"><a href="index.php?business_full=398&pm=4">CONFERENCE SERVICES</a></td>
  <td><a href="index.php?business_full=398&pm=5">CONTACTS</a></td>
 </tr></table> 
</div>
<table cellpadding="0" cellspacing="0">
 <tr>
 <td id="left_c_ms"><div><img src="../root/msite/aurora/logo_e.png" width="225" style="margin-bottom:5px;"/><img src="../root/msite/aurora/logo4_e.png" width="225"/></div></td>
 <td  id="right_c_ms"><div><img src="../root/msite/aurora/logo2_e.png" width="700"/>
 <div style="text-align:left;margin-left:25px;"><b>Contacts:</b>
<br>
36G, Yugoslavskaya Street, Donetsk city, Ukraine, 83008
<br><br>
<a href="http://www.auroradonetsk.com">http://www.auroradonetsk.com</a>
<br>
hotel@auroradonetsk.com
<br><br>
<b>Manager: </b> 
<br>
&nbsp;&nbsp;&nbsp;+38 (062) 310-15-95
<br>
&nbsp;&nbsp;&nbsp;+38 (050) 764-41-61
<br>
т/ф. +38 (062) 310-15-96
<br>
skype hotelaurora.ua
<br>
e-mail hotel@auroradonetsk.com
<br><br>
<b>Conference Services:</b>
<br>
&nbsp;&nbsp;&nbsp;+38 (062) 310-15-95
<br>
&nbsp;&nbsp;&nbsp;+38 (095) 016-51-65
<br>
e-mail conference@auroradonetsk.com
</div>
<br><br>
</td>
 </tr>
</table> 

<script src="http://api-maps.yandex.ru/1.1/index.xml?key=AAmDzUsBAAAARkVWCAIAXzMCgKN58_MQUqB134Sdp-unCH0AAAAAAAAAAACbJlz2mcKc4anRgbxx6LBZ5BHPyg==" type="text/javascript"></script>
    <script type="text/javascript">
        window.onload = function () {
            var map = new YMaps.Map(document.getElementById("YMapsID"));
            map.setCenter(new YMaps.GeoPoint(37.748537,48.00529), 14);

            var content = document.createElement('span');
            content.innerHTML = "«Aurora»";
            map.openBalloon(new YMaps.GeoPoint(37.748537,48.00529), content);

            map.addControl(new YMaps.ToolBar());
            map.addControl(new YMaps.Zoom());
            map.addControl(new YMaps.MiniMap());
            map.addControl(new YMaps.ScaleLine());
        }
    </script>


	 <div id="YMapsID" style="height:450px;margin:0 0 0 25px;width:943px;"></div>
</div>  
    

<?php
   } 
?>



<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="index.php?section_id=456&amp;business=1">Category:</a></div>
</div>
<div class="catalogue_item_cont">
<a href="index.php?section_id=456&amp;business=1">Business</a>
 / 
<a href="index.php?section_id=616&amp;business=1">Enterprises</a>
 / 
<a href="index.php?section_id=619&amp;business=2">Recreation facilities</a>
 / 
<a href="index.php?section_id=686&amp;business=2">Hotels</a>
</div>


<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="">Gallery:</a></div>
</div>
<div class="catalogue_item_cont">
<div class="catalogue_pic_l"><a href="root/msite/aurora/gallery/1.jpg" target="_blank"><img src="root/msite/aurora/gallery/1_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/aurora/gallery/2.jpg" target="_blank"><img src="root/msite/aurora/gallery/2_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/aurora/gallery/3.jpg" target="_blank"><img src="root/msite/aurora/gallery/3_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/aurora/gallery/4.jpg" target="_blank"><img src="root/msite/aurora/gallery/4_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/aurora/gallery/5.jpg" target="_blank"><img src="root/msite/aurora/gallery/5_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/aurora/gallery/6.jpg" target="_blank"><img src="root/msite/aurora/gallery/6_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/aurora/gallery/7.jpg" target="_blank"><img src="root/msite/aurora/gallery/7_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/aurora/gallery/8.jpg" target="_blank"><img src="root/msite/aurora/gallery/8_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/aurora/gallery/9.jpg" target="_blank"><img src="root/msite/aurora/gallery/9_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/aurora/gallery/10.jpg" target="_blank"><img src="root/msite/aurora/gallery/10_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/aurora/gallery/11.jpg" target="_blank"><img src="root/msite/aurora/gallery/11_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/aurora/gallery/12.jpg" target="_blank"><img src="root/msite/aurora/gallery/12_s.jpg" width="60" height="60" border="0" alt=""></a></div>
</div>
<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="">Contacts:</div>
</div>
 <div class="catalogue_item_cont">
 		 <table width="100%">
			<tbody>
 			<tr>
			<!--	<td><img class="main_sec_image" src="" width="60" height="60" border="0" alt="" /></td>-->
				<td>Address:</td>
				<td>Phone:</td>
				<td>Fax:</td>
				<td>E-mail:</td>
				<td>WWW:</td>
			</tr>
			<tr>
				<td>36G, Yugoslavskaya Street<br> Donetsk city, Ukraine, 83008</td>
				<td>(062) 310-15-95<br>(050) 764-4161</td>
				<td>(062) 310-15-96</td>
				<td>hotel@auroradonetsk.com</td>
				<td>http://www.auroradonetsk.com</td>

			</tr>
			</tbody> 
		 </table> 		
	 </div>
</div>  

