 <div class="catalogue_item_c">
<style>

html,body{}

.catalogue_item_c a {color: #000000;}

.catalogue_item_cont p {
color:#000000;
text-align:justify;
text-indent:0px;
line-height:20px;
margin:0px; 
}

img.main_sec_image {
border:none;
}
.catalogue_item_cont_m {
background-color:#FFFFFF;
border:1px solid lightgray;
color:#000000;
margin:0;
margin:15px 10px 10px;
width:980px;
}
.catalogue_item_cont {
background-color:#ffffff;
border-top:1px solid lightgray;
margin:0 0 7px 10px;
width:980px;
color:#000000;

}
.catalogue_item_c {
background-color:#F3F3F3;
font-family: century gotic;
}

a.menu_text {font-size:18px;font-weight:bold;color:#ffffff;}

img.main_sec_image {
height:240px;
padding:0;
width:240px;
}

.catalogue_item_cont a {
color:#000000;
}
.catalogue_item_cont a:hover {
color:#000000;
text-decoration:underline;
}
.catalogue_item_mp_a {
left:3px;
position:relative;
}

#m_menuu {left:80px;
position:relative;
top:-197px;
width:100px;}

#m_menuu td {float:left;
height:60px;
line-height:30px;
vertical-align:middle;
width:200px;
text-align:center;}
table.menu_d td a {font-size:16px;font-weight:bold;color:#ffffcc;text-shadow: -1px 0 black, 0 1px black, 1px 0 black, 0 -1px black;font-style:italic;}
table.menu_d td:hover a{text-decoration:underline;}

#gl_table {width:100%;}
#td1, td3{width:100px;}
#td1 {background:url('../root/msite/shubin/left_f.png') no-repeat 100% 0;height:110px;}
#td3 {background:url('../root/msite/shubin/right_f.png') no-repeat 100% 0;height:110px;}
#td2 {width:770px;background-color:#fecb32;text-align:center;font-size:14px;font-style:italic;font-weight:bold;padding-top:40px;}
#td2_2 {background-color:#fecb32;}
#paper {background:url("../root/msite/shubin/paper.png") no-repeat scroll 100% 0 #fecb32;height:584px;margin-left:10px;width:760px;}
#td3_2 {background:url('../root/msite/shubin/right.png') repeat 100% 0;}
#td1_2 {background:url('../root/msite/shubin/left.png') repeat 100% 0;}

td#i_up {font-weight:bold;text-align:left;color:#280200;}
td#i_up1 {font-weight:bold;text-decoration:underline;}
td#i_first, td#i_first_w {width:300px;text-align:left;font-weight:bold;font-size:16px;color:#280200;padding: 10px 0;}
td#i_first_w {padding:0;}
td#i_second {width:100px;font-weight:bold;font-size:14px;color:#280200;text-align:center;padding-left:10px;}
table#i_table tr {}

.catalogue_pic_l_1 {
width:120px;}
</style>
<?php
if ($_GET['pm'] == 1) 
{
?>

<div class="catalogue_item_cont_m">
<div style="height:228px;">
 <img src="root/msite/shubin/logo.png" />
 <table cellpadding="0" cellspacing="0" class="menu_d" id="m_menuu"><tr>
  <td><a href="index.php?business_full=399&pm=1">ГЛАВНАЯ</a></td>
  <td><a href="index.php?business_full=399&pm=2">МЕНЮ</a></td>
  <td><a href="index.php?business_full=399&pm=3">КОНТАКТЫ</a></td> 
 </tr></table> 
</div>
<div>
<table cellpadding="0" cellspacing="0" id="gl_table">
 <tr>
 <td id="td1"></td>
 <td id="td2">Частная пивоварня «Bierkraft» в трактире «Добрый Шубин»<br/> Настоящие ценители пива - Вам сюда!</td>
 <td id="td3"></td>
 </tr>
 <tr>
 <td id="td1_2"></td><td id="td2_2" style="text-align:justify;padding:10px;font-size:14px;"><b>&nbsp;&nbsp;&nbsp;&nbsp;Трактир пивоварня «Добрый Шубин»</b> состоит из трёх залов, расчитанных <b>на 80 персон:</b> центрального зала - «трактира», «пивоварни» и «охотничьего зала»
 <br>&nbsp;&nbsp;&nbsp;&nbsp;<b>Зал центральный - «трактир»</b><br>&nbsp;&nbsp;&nbsp;&nbsp;С порога Вы попадаете в атмосферу классического трактира с дубовой мебелью. Здесь всегда можно отдохнуть и весело провести время, т.к. именно здесь по вечерам играет живая музыка, и регулярно проводятся тематические вечеринки. В кружке всегда пенится пиво, глаза собеседника зажигаются весёлыми огоньками, а из полумрака Вам таинственно улыбается «хозяин» этого зала - уважаемый в шахтёрском крае - Добрый Шубин.
 <br>&nbsp;&nbsp;&nbsp;&nbsp;<b>Зал пивоварня.</b><br>&nbsp;&nbsp;&nbsp;&nbsp;Пиво - один из самых любимых напитков человечества.<br>&nbsp;&nbsp;&nbsp;&nbsp;Веками древний напиток варился нашими предками. А сегодня у Вас есть исключительная возможность увидеть весь процесс пивоварения, т.к. мини-пивоварня, расположена в этом зале так, что можно самостоятельно наблюдать за действиями пивовара и потом дегустировать этот волшебный напиток - пиво. А при дегустации так же есть своя изюминка - Вы сами можете налить себе столько пива, сколько сможете выпить. Система налива пива расположена прямо на столах.
 <br>&nbsp;&nbsp;&nbsp;&nbsp;<b>Зал «охотничий» (зал для некурящих)</b><br>&nbsp;&nbsp;&nbsp;&nbsp;В этом зале царит атмосфера, подходящая для неторопливой беседы в спокойной обстановке с тихой, приятной музыкой, охотничьими трофеями на стенах. Одно Ваше желание - и обстановка преображается: столы ломятся от яств, а Вы отмечаете свой праздник в кругу близких и друзей. <b>Зал расчитан на 25 персон.</b>
 <br>
 <img src="root/msite/shubin/mm_logo.png" style="padding:10px;" />
 </td><td id="td3_2"></td>
 </tr>
 <tr>
 <td id="td1_2"></td><td id="td2_2"><div id="paper"><span style="color:#280200;font-size:16px;font-weight:bold;"><br><br><br><br><i>Сказ о том, как пивная сила победила силу ратную<br>или<br>Откуда пошло название нашего пива - «Bierkraft»-пивная сила.</i></span>
 <br><div style="color:#280200;font-size:14px;padding:10px 70px;text-align:justify;">&nbsp;&nbsp;&nbsp;&nbsp;Славяне издавна славились богатырской силой молодецкой и красотой девичьей. Даже в северной стране могучих германцев и норманнов знали о суровых скифских законах и неземной красоте степных красавиц.
 <br>&nbsp;&nbsp;&nbsp;&nbsp;Решил как-то германский вождь покорить сердце строптивой девушки с русой косой и сердцем воина. Хотел он мечом завоевать уважение племени, но сильнее оказались богатыри местные. В бою кулачном пытался отстоять своё право, но и здесь силы подвели его. Тогда надумал верх взять силою золоченного напитка, что в почёте был у германцев.
 <br>&nbsp;&nbsp;&nbsp;&nbsp;Изварил рейнский воин хмельное питьё с пышной пеной, стал угощать славянских богатырей, но не хмелели они. Хоть и нравился им горьковатый вкус из дубовой кружки, стали говорить, что германец слаб, как и его напиток. Тогда разгневанный воин пообещал показать настоящую силу напитка, пролил свой кубок на скамью пудовую, и наполнил опустевшие богатырские кружки. И не смогли подняться богатыри земли русской, пивная сила держала их на лавках. С тех пор пиво стало любимым напитком наших предков, а могучую силу и качество стали проверять именно так: <b>«сильное пиво к штанам липнет». «Bierkraft», - </b>сказал когда-то заморский воин своей славянской жене, <b>«настоящая пивная сила», -</b> говорим сегодня мы друзьям!
 <br>&nbsp;&nbsp;&nbsp;&nbsp;Сказка это или быль - судить Вам. Одно только правда - лучшие пивовары и сегодня скрывают рыжеватые отблески в волосах, а тайну пивоварения - в своём сердце, а пивная сила <b>(Bierkraft) - покоряет сердца.</b>
 </div>
 </div></td><td id="td3_2"></td>
 </tr>
</table>
</div>
</div>
 <?php
}
else
   if ($_GET['pm'] == 2)
   {
?>
<div class="catalogue_item_cont_m">
<div style="height:228px;">
 <img src="root/msite/shubin/logo.png" />
 <table cellpadding="0" cellspacing="0" class="menu_d" id="m_menuu"><tr>
  <td><a href="index.php?business_full=399&pm=1">ГЛАВНАЯ</a></td>
  <td><a href="index.php?business_full=399&pm=2">МЕНЮ</a></td>
  <td><a href="index.php?business_full=399&pm=3">КОНТАКТЫ</a></td> 
 </tr></table> 
</div>
<div>
<table cellpadding="0" cellspacing="0" id="gl_table">
 <tr>
 <td id="td1_2"></td><td id="td2_2" style="text-align:justify;padding:10px;width:760px;">
 <br>
<table style="width:750px;padding:0 20px;" id="i_table">
    <tr>
        <td id="i_first"></td>
        <td id="i_second">Выход</td>
        <td id="i_second">Цена (грн)</td>
    </tr>
    <tr>
        <td id="i_first">«Хрустящая» тарелка к пиву <font style="font-size:10px;"><i>Новинка!</i></font><font style="font-size:12px;"><br>(сыр, грибы,лук, крылышкии нежное мясо – все в хрустящей панировке 
       со специями и ароматными добавками)</font></td>
        <td id="i_second">540/100</td>
        <td id="i_second">110-00</td>
    </tr>
    <tr>
        <td id="i_first">«Сельский праздник» <font style="font-size:12px;"><br>(Большое блюдо с жаренной свиной вырезкой  и
      разными овощами,салат из капусты ,лук,золотистые дольки жареного картофеля,
       маринованный перец, грибочки-гриль , цукини гриль, пикантные рулетики из баклажан .
       Подается с соусами) </font></td>
        <td id="i_second">500/740/1 шт/100/15</td>
        <td id="i_second">190-00</td>
    </tr>
    <tr>
        <td id="i_first">«Веселый мальчишник»<font style="font-size:12px;"><br> (Много  обжаренной  маринованной корейки на косточке 
        с запеченым лучком,  маринованным чесночком и маринованной сливкой. 
         Что еще надо  для хорошей компании да под хорошее пивко???) </font></td>
        <td id="i_second">1000/200/100/10</td>
        <td id="i_second">340-00</td>
    </tr>
    <tr>
     <td colspan=3><img src="root/msite/shubin/menu_1.png"></td>
     </tr>
    <tr> 
        <td id="i_first">«Славянская традиция»<font style="font-size:12px;"><br> (Большой кусок запеченной  маринованной  шеи, шпигованной 
      чесноком и морковкой. А еще картошечка, запеченная с салом!
      Все в лучших славянских традициях)</font></td>
        <td id="i_second">1100/800/50/50</td>
        <td id="i_second">310-00</td>
    </tr>
    <tr>
        <td id="i_first">Большая тарелка колбасок<font style="font-size:12px;"><br>(Блюдо в лучших немецких традициях: ассорти из 4-х видов колбасок,
        3 вида соуса и ,конечно же, тушеная капуста)</font></td>
        <td id="i_second">580/150/200</td>
        <td id="i_second">160-00</td>
    </tr>
    <tr>
     <td colspan=3><img src="root/msite/shubin/menu_2.png"></td>
     </tr>
    <tr>
        <td id="i_first">Утка в острой глазури<font style="font-size:12px;"><br>(Подается с квашеной капустой, маринованным перцем,зеленью) </font></td>
        <td id="i_second">1шт/2шт/150</td>
        <td id="i_second">220-00</td>
    </tr>
    <tr>
        <td id="i_first">Мясной микс «На троих»<font style="font-size:12px;"><br> (Три вида мясных стейков :филе цыпленка, телятина вырезка,
                                свинина корейка, обжареных в пивном кляре. 
                              Подаются с золотистым лучком и свежими помидорами, острой аджикой и горчицей)</font></td>
        <td id="i_second">450/60/112/100</td>
        <td id="i_second">120-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:22px;padding:15px 0;">Разные салатные кушанья<br></td></tr>
    <tr>
        <td id="i_first"></td>
        <td id="i_second">Выход</td>
        <td id="i_second">Цена (грн)</td>
    </tr>
    <tr>
        <td id="i_first">Салат «Греческий» <font style="font-size:12px;">с салатным миксом</font><font style="font-size:12px;"><br>(свежие помидор, огурец, перец болгарский, сыр, маслины,
    лук  крымский, салатный микс,  оливковое масло)</font></td>
        <td id="i_second">215</td>
        <td id="i_second">32-00</td>
    </tr>
    <tr>
        <td id="i_first">Салат «Овощной»<font style="font-size:12px;"><br>(свежие огурец, помидор, перец болгарский, масло растительное)</font></td>
        <td id="i_second">200</td>
        <td id="i_second">16-00</td>
    </tr>
    <tr>
        <td id="i_first">Салат с жареными креветками<font style="font-size:10px;"><i>Новинка!</i></font><font style="font-size:12px;"><br> (Легкий микс из листового салата, помидоров, 
     креветок, обжаренных с чесночком, ржаными сухариками 
     с ароматной салатной заправкой ) </font></td>
        <td id="i_second">180</td>
        <td id="i_second">43-00</td>
    </tr>
        <tr>
        <td id="i_first">Салат «Морской бриз»<font style="font-size:12px;"><br>(кальмары, мясо креветки, мидии, рапаны, помидор св.,
     огурец св.,лук зелен., масло оливковое)</font></td>
        <td id="i_second">150</td>
        <td id="i_second">40-00</td>
    </tr>
            <tr>
        <td id="i_first">Салат «Хрустящий»<font style="font-size:12px;"><br> (сочная  пекинская капуста, копченое филе цыпленка, крутоны, 
   болгарский перец, майонез)</font></td>
        <td id="i_second">195</td>
        <td id="i_second">20-00</td>
    </tr>
                <tr>
        <td id="i_first">Салат c курицей в кунжуте<font style="font-size:12px;"><br>( жареное  в кунжуте куриное филе, подается на салатном миксе
     со свежими помидорами иогурцами. Заправляется соусом на
        основе оливкового масла ) </font></td>
        <td id="i_second">230</td>
        <td id="i_second">34-00</td>
    </tr>
                    <tr>
        <td id="i_first">Салат «Пивной барон» <font style="font-size:12px;"><br> (филе куриное отв, грибы жарен, сельдь, св помидор,                   
    огурец маринованный, сыр, майонез) </font></td>
        <td id="i_second">200</td>
        <td id="i_second">25-00</td>
    </tr>
        <tr>
        <td id="i_first">Салат «Цезарь»<font style="font-size:12px;"><br>(филе куриное, крутоны,  яйцо, ветчина, сыр,  
     помидор св., майонез, лист салата )</font></td>
        <td id="i_second">250</td>
        <td id="i_second">42-00</td>
    </tr>
    <tr>
        <td id="i_first">Салат «Прусский»<font style="font-size:12px;"><br>(свинина жар., помидор, огурец, перец болгарский, сыр Фета,
    лук крым., лист салата, масло оливковое)</font></td>
        <td id="i_second">240</td>
        <td id="i_second">40-00</td>
    </tr>
        <tr>
        <td id="i_first">Салат «Богатырский»<font style="font-size:12px;"><br>(куриное филе, ветчина, язык отв, шампин.св, огурцы св, майонез)</font></td>
        <td id="i_second">250</td>
        <td id="i_second">32-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:22px;padding:15px 0;">Жидкие блюда<br></td></tr>
    <tr>
        <td id="i_first"></td>
        <td id="i_second">Выход</td>
        <td id="i_second">Цена (грн)</td>
    </tr>
    <tr>
        <td id="i_first">Солянка сборная</td>
        <td id="i_second">300/20</td>
        <td id="i_second">20-00</td>
    </tr>
    <tr>
        <td id="i_first">Суп перепелиный</td>
        <td id="i_second">300/0,5шт</td>
        <td id="i_second">29-00</td>
    </tr>
    <tr>
        <td id="i_first">Бульон куриный с потрошками<font style="font-size:10px;"><i>Новинка!</i></font><font style="font-size:12px;"><br>(сердечки, пупики.  Шеф-повар рекомендует как «лекарство  второго дня»)</font></td>
        <td id="i_second">300/10/2шт</td>
        <td id="i_second">13-00</td>
    </tr>
    <tr>
        <td id="i_first">Суп крестьянский<font style="font-size:12px;"><br>( остренький с мясными фрикадельками, фасолью и жареным .беконом)</font></td>
        <td id="i_second">380</td>
        <td id="i_second">20-00</td>
    </tr>
    <tr>
        <td id="i_first">Борщ по-украински<font style="font-size:12px;"><br>( подается со сметаной, салом и чесноком)</font></td>
        <td id="i_second">350/25/10</td>
        <td id="i_second">25-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:22px;padding:15px 0;">Блюда из птицы, говядины, баранины, свинины<br></td></tr>
    <tr>
        <td id="i_first">Курочка-сударушка<font style="font-size:12px;"><br>(Нежное куриное филе в сочетании с паприкой и помидорами, 
     запекается  под сырно-майонезной «шапкой»)</font></td>
        <td id="i_second">230</td>
        <td id="i_second">38-00</td>
    </tr>
    <tr>
        <td id="i_first">«Перепела табака»</td>
        <td id="i_second">2шт/50</td>
        <td id="i_second">86-00</td>
    </tr>
    <tr>
        <td id="i_first">Стейк из телятины  «Ужин шефа»<font style="font-size:12px;"><br> (Натуральный стейк из говяжьей вырезки подается на картофельных оладиках с луком - фри!) </font></td>
        <td id="i_second">150/170/1шт/40</td>
        <td id="i_second">64-00</td>
    </tr>
    <tr>
        <td id="i_first">Телятина с хрустящим лучком</font></td>
        <td id="i_second">175/100</td>
        <td id="i_second">61-00</td>
    </tr>
    <tr>
        <td id="i_first">Перечная телятина с овощным гарниром<font style="font-size:12px;"><br>( Медальоны из говяжьей вырезки жареные в смеси перцев и зерен кинзы с паприкой,   
         Подается с шампиньонами и стручковой фасолью,жареными на гриле)</font></td>
        <td id="i_second">150/130/2</td>
        <td id="i_second">69-00</td>
    </tr>
    <tr>
        <td id="i_first">Бараньи ребрышки в пряных травах</td>
        <td id="i_second">300/10</td>
        <td id="i_second">73-00</td>
    </tr>
    <tr>
        <td id="i_first">Каре ягненка с овощами<font style="font-size:12px;"><br>( маринованная отбивная из баранины на косточке, тушеная в красном
          соусе и специях. Подается с жареными овощами)</font></td>
        <td id="i_second">250/100/10</td>
        <td id="i_second">93-00</td>
    </tr>
    <tr>
        <td id="i_first">Свиные ребрышки под 
        чесночно-сметанным соусом<font style="font-size:12px;"><br>(запеченные свиные ребрышки , замаринованные в смеси пряных трав. 
       Нежные и ароматные. Подаются с оригинальным соусом и жареным лучком )</font></td>
        <td id="i_second">250/50/2</td>
        <td id="i_second">62-00</td>
    </tr>
    <tr>
        <td id="i_first">Румяная рулечка<font style="font-size:12px;"><br>(запеченная  свиная рулька 
        Подается с тушеной капустой,  остренькой морковкой., соусами)</font></td>
        <td id="i_second">1шт/60/250</td>
        <td id="i_second">102-00</td>
    </tr>
    <tr>
        <td id="i_first">«Тяги»<font style="font-size:12px;"><br>( Сдались поросята – белые стяги ,
      Шеф-повар на кухне обжаривал тяги) </font></td>
        <td id="i_second">175/50/50</td>
        <td id="i_second">54-00</td>
    </tr>
    <tr>
        <td id="i_first">Свинина «Дуэт»<font style="font-size:12px;"><br> (Свиная вырезка, жареная на гриле. Горчичка и кунжут добавляют пикантности. 
      Подается с острыми рулетиками из баклажан с аджикой, помидорчиком и салатом )</font></td>
        <td id="i_second">170/140</td>
        <td id="i_second">56-00</td>
    </tr>
    <tr>
        <td id="i_first">Стейк«Фермерский» на косточке<font style="font-size:12px;"><br> (Два стейка на косточке, фаршированные беконом и лучком, жареные на гриле. 
        Хорошее блюдо для двоих) </font></td>
        <td id="i_second">360/50</td>
        <td id="i_second">83-00</td>
    </tr>
    <tr>
        <td id="i_first">«Тайм-Аут» <font style="font-size:10px;"><i>Новинка!</i></font><font style="font-size:12px;"><br>( Ломтики свиной корейки и нежной говяжьей вырезки, обжаренные на гриле,
     протушеные с баклажаном, подаются с картофелем фри и луком фри) </font></td>
        <td id="i_second">360</td>
        <td id="i_second">70-00</td>
    </tr>
    <tr>
        <td id="i_first">Мясной торт <font style="font-size:10px;"><i>Новинка!</i></font><font style="font-size:12px;"><br>( Сочный рулетик из свиной вырезки с беконом в неожиданном виде в сочетании с 
      картофельными оладиками и жареными овощами)</font></td>
        <td id="i_second">200/170/70</td>
        <td id="i_second">62-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:22px;padding:15px 0;">Кушанья из овощей и рыбы<br></td></tr>
    <tr>
        <td id="i_first">Овощной микс<font style="font-size:12px;"><br> (Тушеные овощи: баклажаны, цукини, болгарский перец, грибы, лук в натуральном соку) </font></td>
        <td id="i_second">200</td>
        <td id="i_second">29-00</td>
    </tr>
    <tr>
        <td id="i_first">Морская красавица<font style="font-size:12px;"><br> (Нежное сочетание запеченого филе пелингаса с :цукини и морковью) </font></td>
        <td id="i_second">220</td>
        <td id="i_second">35-00</td>
    </tr>
    <tr>
        <td id="i_first">Барабуля жареная с золотистым луком<font style="font-size:10px;"><i>Новинка!</i></font><font style="font-size:12px;"><br>черноморская барабуля,  жаренная во фритюре</font></td>
        <td id="i_second">400/50</td>
        <td id="i_second">69-00</td>
    </tr>
    <tr>
        <td id="i_first">Стейк из семги «Гранд» на 
                      ароматных овощах<font style="font-size:12px;"><br>(большой стейк из семги, обжаренный на барбекю.
     Подается на «подушке»  из обжаренной  цветной капусты, помидора и струч фасоли 
       с фирменным соусом «Тар-тар» </font></td>
        <td id="i_second">200/130/30/30/6</td>
        <td id="i_second">98-00</td>
    </tr>
    <tr>
        <td id="i_first">Палтус на гриле с овощами<font style="font-size:12px;"><br>(Стейк палтуса, замаринованый в специях и соке лимона, жареный на решетке.
         Подается с овощами гриль, зеленью и лимоном )</font></td>
        <td id="i_second">130/100/30</td>
        <td id="i_second">85-00</td>
    </tr>
    <tr>
        <td id="i_first">«Рыбный блюз»<font style="font-size:12px;"><br>(Стейк палтуса, запеченый с морепродуктами под нежным соусом.
        Подается с овощным миксом)</font></td>
        <td id="i_second">290/30</td>
        <td id="i_second">88-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:22px;padding:15px 0;">Холодные яства  к пиву<br></td></tr>
    <tr>
        <td id="i_first_w">«Пивная» соломка</td>
        <td id="i_second">100</td>
        <td id="i_second">17-00</td>
    </tr>
    <tr>
        <td id="i_first_w">Креветки отварные</td>
        <td id="i_second">180/20</td>
        <td id="i_second">45-00</td>
    </tr>
    <tr>
        <td id="i_first_w">Креветки жареные <font style="font-size:12px;">(на сливочном масле)</font></td>
        <td id="i_second">180/20</td>
        <td id="i_second">45-00</td>
    </tr>
    <tr>
        <td id="i_first_w">Семгушка соленая</td>
        <td id="i_second">100/30</td>
        <td id="i_second">49-00</td>
    </tr>
    <tr>
        <td id="i_first_w">Горбуша копченая</td>
        <td id="i_second">100/10</td>
        <td id="i_second">33-00</td>
    </tr>
    <tr>
        <td id="i_first_w">Рыбка Масляная нежная <font style="font-size:10px;">х/к</font></td>
        <td id="i_second">80/20</td>
        <td id="i_second">26-00</td>
    </tr>
    <tr>
        <td id="i_first_w">Махан</td>
        <td id="i_second">100</td>
        <td id="i_second">42-00</td>
    </tr>
    <tr>
        <td id="i_first_w">Конские ломтики остренькие</td>
        <td id="i_second">100</td>
        <td id="i_second">44-00</td>
    </tr>
    <tr>
        <td id="i_first_w">Бастурма</td>
        <td id="i_second">100</td>
        <td id="i_second">31-00</td>
    </tr>
    <tr>
        <td id="i_first_w">Гренки с сельдью</td>
        <td id="i_second">50/50</td>
        <td id="i_second">10-00</td>
    </tr>
    <tr>
        <td id="i_first_w">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;с салом соленым</td>
        <td id="i_second">50/50</td>
        <td id="i_second">10-00</td>
    </tr>
    <tr>
        <td id="i_first_w">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;с салом копченым</td>
        <td id="i_second">50/50</td>
        <td id="i_second">10-00</td>
    </tr>
    <tr>
        <td id="i_first_w">Сыр копченый</td>
        <td id="i_second">100</td>
        <td id="i_second">22-00</td>
    </tr>
    <tr>
        <td id="i_first_w">Сосиски «Охотничьи в огне»</td>
        <td id="i_second">100</td>
        <td id="i_second">23-00</td>
    </tr>
    <tr>
        <td id="i_first_w">Тарань кубанская </td>
        <td id="i_second">1шт</td>
        <td id="i_second">60-00</td>
    </tr>
    <tr>
        <td id="i_first_w">Тарань с икрой</td>
        <td id="i_second">1шт</td>
        <td id="i_second">40-00</td>
    </tr>
    <tr>
        <td id="i_first_w">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;без икры</td>
        <td id="i_second">1шт</td>
        <td id="i_second">30-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:22px;padding:15px 0;">Прочие холодные яства<br></td></tr>
    <tr>
        <td id="i_first_w">«Крутые виражи»<font style="font-size:10px;"><i>Новинка!</i></font><font style="font-size:12px;"><br> (нежные блинчики с семгой ,сырком и зеленью) </font></td>
        <td id="i_second">150/35</td>
        <td id="i_second">31-00</td>
    </tr>
    <tr>
        <td id="i_first_w">Сельдь по-русски</td>
        <td id="i_second">115/70/30</td>
        <td id="i_second">17-00</td>
    </tr>
    <tr>
        <td id="i_first_w">Сырное плато<font style="font-size:12px;"><br> ( сыр «ДорБлю»,  «Гауда», « Рамзес»)</font></td>
        <td id="i_second">75/75/75/ 14</td>
        <td id="i_second">60-00</td>
    </tr>
    <tr>
        <td id="i_first_w">Язык отварной с майонезом и овощами</font></td>
        <td id="i_second">100/30/20/20</td>
        <td id="i_second">35-00</td>
    </tr>
    <tr>
        <td id="i_first"><font style="font-size:18px;">предложение от шеф-повара:</font><font style="font-size:12px;">(по предварительному заказу)</font></td>
        <td id="i_second"></td>
        <td id="i_second"></td>
    </tr>
    <tr>
        <td id="i_first_w">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Буженина домашняя</td>
        <td id="i_second">100/30</td>
        <td id="i_second">33-00</td>
    </tr>
    <tr>
        <td id="i_first_w">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Колбаска куриная</td>
        <td id="i_second">120/30</td>
        <td id="i_second">29-00</td>
    </tr>
    <tr>
        <td id="i_first_w">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Колбаска «Домашняя»</td>
        <td id="i_second">100/30</td>
        <td id="i_second">33-00</td>
    </tr>
    <tr>
        <td id="i_first_w">Лимон с сахаром</td>
        <td id="i_second">35/15</td>
        <td id="i_second">2-00</td>
    </tr>
    <tr>
        <td id="i_first_w">Маслины, оливки (порциями)</td>
        <td id="i_second">75/10</td>
        <td id="i_second">19-00</td>
    </tr>
    <tr>
        <td id="i_first_w">Овощи свежие на выбор:(помидор,огурец,перец)</td>
        <td id="i_second">100</td>
        <td id="i_second">6-00</td>
    </tr>
    <tr>
        <td id="i_first_w">Зелень св.</td>
        <td id="i_second">50</td>
        <td id="i_second">15-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:22px;padding:15px 0;">Горячие<br></td></tr>
    <tr>
        <td id="i_first"><font style="font-size:12px;">Что за пиво без фирменных колбасок?!</font></td>
        <td id="i_second"></td>
        <td id="i_second"></td>
    </tr>
    <tr>
        <td id="i_first"></td>
        <td id="i_second">Выход</td>
        <td id="i_second">Цена (грн)</td>
    </tr>
    <tr>
        <td id="i_first">Колбасное ассорти<font style="font-size:12px;"><br>3 вида колбасок: куриные и свиная. Разнообразные соусы и  маринованные 
        овощи дополнят их оригинальный вкус. И, как положено, квашеная капуста.
         Это все на одной большой тарелке. )</font></td>
        <td id="i_second">320/150/95</td>
        <td id="i_second">73-00</td>
    </tr>
    <tr>
        <td id="i_first"> Колбаски острые к пиву<font style="font-size:12px;"><br> (Свино-говяжие колбаски, Подаются с картофелем и соленым помидорчикрм)</font></td>
        <td id="i_second">200/100/100/50</td>
        <td id="i_second">69-00</td>
    </tr>
    <tr>
        <td id="i_first">Луковые кольца</td>
        <td id="i_second">110/30/30</td>
        <td id="i_second">38-00</td>
    </tr>
    <tr>
        <td id="i_first">Хрустящие тигровые креветки<font style="font-size:12px;"><br>(жареные тигровые креветки с чесночком  и специями в сливочном масле)</font></td>
        <td id="i_second">5шт/30/35</td>
        <td id="i_second">98-00</td>
    </tr>
    <tr>
        <td id="i_first"> Крылья «Добрый Шубин» с соусом<font style="font-size:12px;"><br>(аппетитные маринованные  куриные плечики в кляре, жареные во фритюре. </font></td>
        <td id="i_second">250/50</td>
        <td id="i_second">29-00</td>
    </tr>
    <tr>
        <td id="i_first">«Бешеные крылья»<font style="font-size:12px;"><br> ( Хочется  остренького? Тогда эти крылья будут вам по вкусу. Вымоченные
     в специях и обмазанные горчицей,  нанизанные на шпажки и томимые на 
     решетках  барбекю, эдакие куриные шашлычки. Огонь, который зажжет в 
     вас это блюдо,  может быть  погашен только бочкой доброго пива.)</font></td>
        <td id="i_second">200/50</td>
        <td id="i_second">29-00</td>
    </tr>
    <tr>
        <td id="i_first">Крылья «Улет»<font style="font-size:12px;"><br>( Любителям   экстрима  - рекомендуется! Острые куриные плечики, посыпанные
   особыми сухариками и  обжаренные во фритюре с соусом «Паприччи».
   Вас оторвет от земли и подбросит в небо,  поэтому перед  употреблением 
   проверьте – все ли в порядке с парашютом?) </font></td>
        <td id="i_second">250/50</td>
        <td id="i_second">29-00</td>
    </tr>
    <tr>
        <td id="i_first">Крылья «Лепота»<font style="font-size:12px;"><br> ( Куриные  плечики,  жареные  во фритюре  с добавлением  аджики  и чесно-
    ка ,  с соусом «Чили». Одолев это блюдо, некоторое время вы сможете выго-
    варивать  только одно слово: «… Лепота,  лепота! …»)</font></td>
        <td id="i_second">250/100</td>
        <td id="i_second">29-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:22px;padding:15px 0;">Копченые<br></td></tr>
    <tr>
        <td id="i_first">Поросячий визг<font style="font-size:12px;"><br> Копченые поросячие уши. А вы еще не пробовали..?</font></td>
        <td id="i_second">1шт</td>
        <td id="i_second">28-00</td>
    </tr>
    <tr>
        <td id="i_first">Радость мясоеда<font style="font-size:12px;"><br>Аппетитные копченые ребрышки. В отдельной рекламе не нуждаются</font></td>
        <td id="i_second">300/30/30</td>
        <td id="i_second">58-00</td>
    </tr>
 </table>
 </td><td id="td3_2"></td>
 </tr> 
</table>
</div>
</div>
<?php
}
else
   if ($_GET['pm'] == 3)
   {
?>

<div class="catalogue_item_cont_m">
<div style="height:228px;">
 <img src="root/msite/shubin/logo.png" />
 <table cellpadding="0" cellspacing="0" class="menu_d" id="m_menuu"><tr>
  <td><a href="index.php?business_full=399&pm=1">ГЛАВНАЯ</a></td>
  <td><a href="index.php?business_full=399&pm=2">МЕНЮ</a></td>
  <td><a href="index.php?business_full=399&pm=3">КОНТАКТЫ</a></td> 
 </tr></table> 
</div>
<div>
<table cellpadding="0" cellspacing="0" id="gl_table">
 <tr>
 <td id="td1"></td><td id="td2" style="font-size:11px;padding:15px 0 0 10px;text-align:justify;">Адрес: Донецк, ул.Марии Ульяновой 65а<br>тел.: (0622) 95-15-58<br>Время работы: 12.00-23.00<br><br>Как проехать:<br>Калининский р-н, пересечение ул. Марии Ульяновой и пр. Ильича</td><td id="td3"></td>
 </tr>
 <tr>
 <td id="td1_2"></td><td id="td2_2"><div id="YMapsID" style="height:450px;margin-left:10px;width:760px;"></div></td><td id="td3_2"></td> 
 </tr>
</table>
</div>

<script src="http://api-maps.yandex.ru/1.1/index.xml?key=AAmDzUsBAAAARkVWCAIAXzMCgKN58_MQUqB134Sdp-unCH0AAAAAAAAAAACbJlz2mcKc4anRgbxx6LBZ5BHPyg==" type="text/javascript"></script>
    <script type="text/javascript">
        window.onload = function () {
            var map = new YMaps.Map(document.getElementById("YMapsID"));
            map.setCenter(new YMaps.GeoPoint(37.840335,48.004222), 14);

            var content = document.createElement('span');
            content.innerHTML = "«Добрый Шубин»";
            map.openBalloon(new YMaps.GeoPoint(37.840335,48.004222), content);

            map.addControl(new YMaps.ToolBar());
            map.addControl(new YMaps.Zoom());
            map.addControl(new YMaps.MiniMap());
            map.addControl(new YMaps.ScaleLine());
        }
    </script>


	 
</div>  
    

<?php
   } 
?>



<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="index.php?section_id=32&amp;business=1">Категория:</a></div>
</div>
<div class="catalogue_item_cont">
<a href="index.php?section_id=2&amp;business=1">бизнес</a>
 / 
<a href="index.php?section_id=32&amp;business=1">предприятия</a>
 / 
<a href="index.php?section_id=389&amp;business=2">отдых и развлечения</a>
 / 
<a href="index.php?section_id=390&amp;business=2">рестораны, кафе, ночные клубы</a>
</div>


<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
Фотогалерея:</div>
</div>
<div class="catalogue_item_cont">
<div class="catalogue_pic_l"><a href="root/msite/shubin/gallery/1.jpg" target="_blank"><img src="root/msite/shubin/gallery/1_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/shubin/gallery/2.jpg" target="_blank"><img src="root/msite/shubin/gallery/2_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/shubin/gallery/3.jpg" target="_blank"><img src="root/msite/shubin/gallery/3_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l catalogue_pic_l_1"><a href="root/msite/shubin/gallery/7.jpg" target="_blank"><img src="root/msite/shubin/gallery/7_s.jpg" width="120" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l catalogue_pic_l_1"><a href="root/msite/shubin/gallery/8.jpg" target="_blank"><img src="root/msite/shubin/gallery/8_s.jpg" width="120" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/shubin/gallery/15.jpg" target="_blank"><img src="root/msite/shubin/gallery/15_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/shubin/gallery/16.jpg" target="_blank"><img src="root/msite/shubin/gallery/16_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/shubin/gallery/17.jpg" target="_blank"><img src="root/msite/shubin/gallery/17_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/msite/shubin/gallery/18.jpg" target="_blank"><img src="root/msite/shubin/gallery/18_s.jpg" width="60" height="60" border="0" alt=""></a></div>
</div>
<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
Контактная информация:</div>
</div>
 <div class="catalogue_item_cont">
 		 <table width="100%">
			<tbody>
 			<tr>
			<!--	<td><img class="main_sec_image" src="" width="60" height="60" border="0" alt="" /></td>-->
				<td>Адрес:</td>
				<td>Телефон:</td>
				<td>Факс:</td>
				<td>E-mail:</td>
				<td>Веб-сайт:</td>
			</tr>
			<tr>
				<td>г. Донецк, ул.Марии Ульяновой, 65а</td>
				<td>(0622) 95-15-58</td>
				<td></td>
				<td></td>
				<td></td>

			</tr>
			</tbody> 
		 </table> 		
	 </div>
</div>  

