<div class="catalogue_item_c">
<style>

<!--
.folding{cursor:hand;font-weight:bold}
-->

img {
border:none;	
}

div {
	display:block;
}

p {
	font-family:Arial, Helvetica, sans-serif;
	font:Arial, Helvetica, sans-serif;
}

a {
	text-decoration:none;
	border:none;
}

.sequ_conteiner{
	width:100%;
}

.sequ_up { 
height:105 px;
width:100%;
position:relative;
float:left;
margin:0;
background:#264c7b;
}

.sequ_p_up_2 {
	color:#FFF;
	font-size:20 px;
	text-align:justify;
	line-height: 1 px;
	letter-spacing: 2 px;
}

.sequ_p_up_3 {
	color:#FFF;
	font-size:16 px;
	text-align:justify;
	line-height: 1 px;
	letter-spacing: 5 px;
}

.sequ_stroke {
width: 100%;
background-color:#edecea;
height:33px;
text-align:right;
padding:0;
position:relative;
float:left;
margin: -10 0 0 0;
}

.sequ_main_menu {
	position:relative;
	float:left;
	min-height:458;
	max-height:458;
	height:100%;
	background-color:#264c7b;
	padding:5px;
}
/*onas*/
.sequ_a_1 {
	width:135px;
	position:relative;
	float:right;
	margin-right:6px;
}
/*uslu*/
.sequ_a_2 {
	width:135px;
	position:relative;
	float:right;
	margin-right:6px;
	
}
/*kont*/
.sequ_a_3 {
	width:135px;
	position:relative;
	float:right;
	
}

.sequ_podmain{
width:955px;
height:20px;
position:relative;
float:left;
left:20px;
padding:5px;
background-color:#264c7b;
color:#FFF;
font-family:Arial, Helvetica, sans-serif;
font-size:13px;
text-align:center;
}

.sequ_text {
	width:100%;
	position:relative;
	float:left;
	text-indent: 20px;
}

.sequ_footer {
	width:990px;
	height:35;
	position:relative;
	float:left;
	background-color:#264c7b;
	color:#000;
	font-family:Tahoma, Geneva, sans-serif;
	font-size:14px;
	text-align:right;
	padding:5px;
}
</style>
<?php
if ($_GET['pm'] == 1) 
{
?>
<div class="catalogue_item_cont_m"> 
<div class="sequ_conteiner">
    <div class="sequ_up">
		<div style="position:relative; float:left; padding:10px; top:10px; left:50px;"><img src="../root/msite/kardio/ser.png"/></div>
		<div style="position:relative; float:left; left:80px; top:48px; color:#FFF;	font-size:20px; text-align:justify; line-height:1px; letter-spacing:5px;">Personal medical appointment</div>
		<div style="position:relative; float:left; left:190px; top:50px; color:#FFF;	font-size:12px;  line-height:1.2; text-align:right;"><span>Tel.: (066) 907-94-66</span><br />
<div style="color:#95b7e2;">14-E, Iliicha Avenue, Kalininskiy district, Donetsk city <br />
<div style="letter-spacing:2px;">(DOCTMO, Kalinina Hospital),</div>
GERTS Medical centre, 7th floor, 715 room</div></div>
		<div style="position:relative; float:left; clear:left; left:190px; top:-32px; color:#FFF;	font-size:20px; text-align:justify; line-height:1px; letter-spacing:1px; text-transform:uppercase;"><b>with cardiologist- therapeutist</b></div>
		<div style="position:relative; float:left; clear:left; left:190px; top:-17px; color:#FFF; margin-bottom:10px;	font-size:16px; text-align:justify; line-height:1px; letter-spacing:12px;">GERTS Medical centre</div>
    	<!--
		<div style="position:relative; float:left; clear:left; margin-bottom:10; padding:0; left:20; width:100%;"><img src="../root/msite/kardio/up.png" align="left" width="100%" height="105" /></div>
		-->
    </div>
    <div class="sequ_stroke"> 
        <div style="padding:6px; bottom: -10px; color:#264c7b; font-family:'Times New Roman', Times, serif; font-size:20px;">
        Listen to your heart!</div>
        </div>
    <div class="sequ_main_menu">
    	<div style="background: url(../root/msite/kardio/neb.jpg); width:100%; height:452px; position:relative; float:left;">
        	<div style="position:relative; float:left; left:25; width:370;"><img src="../root/msite/kardio/dev.png" align="left" width="367" height="450" /></div>
			<div style="position:relative; float:right; padding:0px;">
				<div class="sequ_a_3"><a href="http://eurodonetsk.com/index.php?business_full=405&pm=3"><img src="../root/msite/kardio/ko_en.jpg" width="135" height="36" /></a></div>
				<div class="sequ_a_2"><a href="http://eurodonetsk.com/index.php?business_full=405&pm=2"><img src="../root/msite/kardio/se_en.jpg" width="135" height="36" /></a></div>
				<div class="sequ_a_1"><a href="http://eurodonetsk.com/index.php?business_full=405&pm=1"><img src="../root/msite/kardio/us_en_on.jpg" width="135" height="36" /></a></div>
			</div>
            
            <div style="padding-top: 100; text-align:left; font-style:italic; color:#264c7b; font:Tahoma, Geneva, sans-serif; font-family:Tahoma, Geneva, sans-serif; font-size:22px; line-height:1.4; padding-left:390; margin-top:100;"><br /><br />Our life and our health 
directly depend on it. That’s why the <br />risk of getting heart disease is supposed to be one of the most widespread and great fear of the person. If you have any complaints of chest pain, 
you should see cardiologist to clarify the reasons of complaints and take stock of the situation.
			</div>       
        </div>
    </div>
    <div class="sequ_podmain">
    	<b>In our centre you can have full diagnostic tests of the Cardiovascular System.</b>
    </div>
	
	<!-- Основной текст -->
	
    <div class="sequ_text">
    	<div style="position:relative; float:left; width:100%;">
			<div id="left_block_sequ_text" style="position:relative; float:left; width:48%; padding:6px;">
				<div style="position:relative; float:left; width:100%; text-align:left; font-family:'Trebuchet MS', Arial, Helvetica, sans-serif; line-height:1; font-style:italic; font-size:18px; margin-bottom:15px; margin-top:20px;"><b>Our centre<br /> is fitted up with modern medical equipment, which makes it more exactly to detect pathology, to make precise diagnosis, and to prescribe proper treatment. <br /></b>
				</div>
                <div style="position:relative; float:left; width:100%; text-align:left; text-indent: 20; font-family:'Trebuchet MS', Arial, Helvetica, sans-serif; line-height:1; font-style:italic; font-size:18px; color:#900; margin-bottom:15px;"><b>Our specialists <br />
work under modern international and domestic standards and protocols of diagnostics, treatment and prevention of cardiovascular diseases, based on evidentiary medicine. <br /></b>
           		</div>
                <div style="position:relative; float:left;  width:100%; border:1px; ">
					<img src="../root/msite/kardio/en_left.png" width="290" height="300" />
                </div>
			</div>
            <div id="right_block_sequ_text" style="position:relative; float:right; width:48%; padding:6px;">
				<div style="position:relative; float:left; margin-top:-512; color:#900; font-size:24px; text-align=:left;">10 reasons to make a cardiologist appointment:</div>
					<b><div style="position:relative; float:left; font-size:24px; text-align=:left; font-size:11px; text-align:left;">
						
					1. If you are suffering from heart pain on exercise or without it.<br />
					<img src="../root/msite/kardio/uhi.jpg" width="150" height="113"; align="right" />
					2. If you are suffering from exertional dyspnea, edema of shin and podedema. <br />
					 
					3. If you have tachycardia or cardiac work intermission <br />
					 
					4. If you have rapid (more than 90 beats per minute) or slow (less than 55 beats per minute) pulse. <br />
					 
					5. If you have periodically or constant high pressure more than 140/90 millimeters of mercury.<br />
					
					6. You’re more than 40 years old, and you have never seen cardiologist.  <br />
					 
					7. You’re suffering from diabetes mellitus or from thyroid disease. <br />
					 
					8. If you had apoplexy <br />
					 
					9. If you are smoking <br />
					 
					10. У Вас избыточная масса тела.<br /><br />
					</div>
					
            
            
			<div style="position:relative; float:left; clear:left; margin-top:-512; padding-right:30; padding-top: 5; font-size:24px; text-align=:left; font-size:11px; text-align:left;"> Cardiologist consultation is necessary for pathology detection of cardiovascular system, activity test and clinical staging, forehead medication prescription and for measures to prevent disease progression and its complications.
 <br /><br />

Primary inspection of the cardiologist 
includes gathering and specification  of patient's complaints, examination (percussion, auscultation,  taking the pulse and blood pressure, history taking), investigation of earlier studies (ECG, cardiac ultrasound, blood test, etc.), prescription of additional examination, making a diagnosis, therapy institution.
<br /><br />

Repeated inspection of the cardiologist 
includes making of final diagnosis on the ground  of physical examination and research data, treatment effectiveness control and therapy correction, if it is needed.
<br /><br />

Free final consultation 
includes the same things as repeated examination. The main task of the final consultation is to control the following of medical advice, treatment effectiveness control and its correction.

                </div></b>
                
        </div>
     </div>
       
    </div>
</div>

</div>
<?php
}
else
   if ($_GET['pm'] == 2)
   {
?>
<div class="catalogue_item_cont_m"> 
<div class="sequ_conteiner">
    <div class="sequ_up">
		<div style="position:relative; float:left; padding:10px; top:10px; left:50px;"><img src="../root/msite/kardio/ser.png"/></div>
		<div style="position:relative; float:left; left:80px; top:48px; color:#FFF;	font-size:20px; text-align:justify; line-height:1px; letter-spacing:5px;">Personal medical appointment</div>
		<div style="position:relative; float:left; left:190px; top:50px; color:#FFF;	font-size:12px;  line-height:1.2; text-align:right;"><span>Tel.: (066) 907-94-66</span><br />
<div style="color:#95b7e2;">14-E, Iliicha Avenue, Kalininskiy district, Donetsk city <br />
<div style="letter-spacing:2px;">(DOCTMO, Kalinina Hospital),</div>
GERTS Medical centre, 7th floor, 715 room</div></div>
		<div style="position:relative; float:left; clear:left; left:190px; top:-32px; color:#FFF;	font-size:20px; text-align:justify; line-height:1px; letter-spacing:1px; text-transform:uppercase;"><b>with cardiologist- therapeutist</b></div>
		<div style="position:relative; float:left; clear:left; left:190px; top:-17px; color:#FFF; margin-bottom:10px;	font-size:16px; text-align:justify; line-height:1px; letter-spacing:12px;">GERTS Medical centre</div>
    	<!--
		<div style="position:relative; float:left; clear:left; margin-bottom:10; padding:0; left:20; width:100%;"><img src="../root/msite/kardio/up.png" align="left" width="100%" height="105" /></div>
		-->
    </div>
    <div class="sequ_stroke"> 
        <div style="padding:6px; bottom: -10px; color:#264c7b; font-family:'Times New Roman', Times, serif; font-size:20px;">
        Listen to your heart!</div>
        </div>
    <div class="sequ_main_menu">
    	<div style="background: url(../root/msite/kardio/neb.jpg); width:100%; height:452px; position:relative; float:left;">
        	<div style="position:relative; float:left; left:25; width:370;"><img src="../root/msite/kardio/dev.png" align="left" width="367" height="450" /></div>
			<div style="position:relative; float:right; padding:0px;">
				<div class="sequ_a_3"><a href="http://eurodonetsk.com/index.php?business_full=405&pm=3"><img src="../root/msite/kardio/ko_en.jpg" width="135" height="36" /></a></div>
				<div class="sequ_a_2"><a href="http://eurodonetsk.com/index.php?business_full=405&pm=2"><img src="../root/msite/kardio/se_en_on.jpg" width="135" height="36" /></a></div>
				<div class="sequ_a_1"><a href="http://eurodonetsk.com/index.php?business_full=405&pm=1"><img src="../root/msite/kardio/us_en.jpg" width="135" height="36" /></a></div>
			</div>
            
            <div style="padding-top: 100; text-align:left; font-style:italic; color:#264c7b; font:Tahoma, Geneva, sans-serif; font-family:Tahoma, Geneva, sans-serif; font-size:22px; line-height:1.4; padding-left:390; margin-top:100;"><br /><br />Our life and our health 
directly depend on it. That’s why the <br />risk of getting heart disease is supposed to be one of the most widespread and great fear of the person. If you have any complaints of chest pain, 
you should see cardiologist to clarify the reasons of complaints and take stock of the situation.
			</div>       
        </div>
    </div>
    <div class="sequ_podmain">
    	<b>In our centre you can have full diagnostic tests of the Cardiovascular System.</b>
    </div>
	
	<!-- Основной текст -->
	
    <div class="sequ_text">
    	<div style="position:relative; float:left; width:100%;">
			<div id="cenyt_block1_sequ_text" style="position:relative; float:left; width:95%; padding:6px; left:25px;">
				<div style="position:relative; float:left; width:100%; text-align:left; font-family:'Trebuchet MS', Arial, Helvetica, sans-serif; line-height:1; font-style:italic; font-size:15px; padding-bottom:15px;"><b>Our specialists will help you to examine the status of your cardiovascular system, prevent heart disorders, provide prophylaxis and treatment of diseases and its complications. </b>
				</div>
                <div style="position:relative; float:left; width:100%; text-align:left; text-indent: 20; font-family:'Trebuchet MS', Arial, Helvetica, sans-serif; line-height:1; font-style:italic; font-size:15px; color:#264c7b;"><b>On the basis of our centre one can be carefully examined, using modern professional medical equipment by qualified specialists. </b>
           		</div>
			</div>
			<div id="left_block_sequ_text" style="position:relative; float:left; text-align:left; text-indent: 20px; font-family:'Trebuchet MS', Arial, Helvetica, sans-serif; line-height:1; font-style:italic; font-size:16px; color:#264c7b; width:20%; left:30px;">
			At our centre you can have your cardiovascular system carefully examined: 
				<div style="color:black; font-size:12px; padding:15px; line-height:1.8;">
				<ul type="disc">
					<li>- Electrocardiogram (ECG);</li>
					<li>- 24-hour (Holter) monitoring ECG;</li>
					<li>- Cardiac ultrasound; </li>
					<li>- Exercise ECG testing; </li>
					<li>- Laboratory examination. </li>
				</ul>
				</div>
				<div style="position:relative; float:left;  width:40%; left:-20px; top:80px;">
              		<img src="../root/msite/kardio/en_left2.png" width="186" height="140" />
                </div>
			</div>
			<div id="centr_block_sequ_text" style="position:relative; float:left; text-align:left; text-indent:20px; font-family:'Trebuchet MS', Arial, Helvetica, sans-serif; line-height:1; font-style:italic; font-size:12px; color:#264c7b; width:30%; left:30px;">
			<table width="100%" cellpadding="50" cellspacing="0" border="2">
			<tbody>
				<tr style=" text-align:center;">
					<td width="70%">
						Services
					</td>
					<td width="30%" style="text-align:center;">
						Price, UAH
					</td>
				</tr>
				<tr>
					<td>
						Calling a doctor (doctor's advice + ECG)
					</td>
					<td style="text-align:center;">
						350
					</td>
				</tr>	
				<tr>
					<td>
						First appointment with the  cardiologist family doctor 
					</td>
					<td style="text-align:center;">
						150
					</td>
				</tr>   
				<tr>
					<td>
						Repeated appointment with the  cardiologist family doctor
					</td>
					<td style="text-align:center;">
						100
					</td>
				</tr>
				<tr>
					<td>
						Control consultation by treatment results  	 
					</td>
					<td style="text-align:center;">
						Free
					</td>
				</tr>   
				<tr>
					<td>
						First appointment with the  therapist-cardiologist, Candidate of Medical Science, associate professor 	         	 
					</td>
					<td style="text-align:center;">
						250
					</td>
				</tr>    
				<tr>
					<td>
						Repeated appointment with the  therapist-cardiologist, Candidate of Medical Science, associate professor  	         	 
					</td>
					<td style="text-align:center;">
						175
					</td>
				</tr>
				<tr>
					<td>
						Electrocardiogram, ECG with explanation       	 
					</td>
					<td style="text-align:center;">
						50
					</td>
				</tr> 
				<tr>
					<td>
						Holter monitoring ECG 	        	 
					</td>
					<td style="text-align:center;">
						250
					</td>
				</tr>           
			</tbody>
			</table>
				<b>		
				<div style="font-style:normal; padding-top:16px;"><b style="color:#900; font-size:18px;"><img src="../root/msite/kardio/heart.png" width="20px" height="20px" />Calling a doctor</b>
					<div style="color:black; font-size:12px; padding:5px;">
					<p>Paid house call doctor is the perfect alternative of state medical care, when you need medical specialist with house call service. Use this service and our specialist (therapeutist or cardiologist) will come to you at a predetermined time.<br />
Our centre provides the following medical services:</p>
	<ul style="padding:15px; text-indent:0px;">
		<li>Medical consultation (therapeutist or cardiologist)</li>
		<li>Medical examination</li>
		<li>ECG test</li>
		<li>Holter monitoring ECG</li>
		<li>Establishing the diagnosis</li>
		<li>Treatment Prescription</li>
	</ul>
   					</div>
				</div>
				</b>
				
				
			</div>
			<div id="right_block_sequ_text" style="position:relative; float:left; text-align:left; text-indent: 10px; font-family:'Trebuchet MS', Arial, Helvetica, sans-serif; line-height:1.2; font-style:italic; font-size:13px; color:#900; width:45%; left:35px; top:-15px;">
			<b>
			<div style="font-style:normal; padding-top:16px;"><b style="color:#900; font-size:18px;"><img src="../root/msite/kardio/heart.png" width="20px" height="20px" />Electrocardiography (ECG)</b>
					<div style="color:black; font-size:12px; padding:5px;">
					<p>
					 Electrocardiography (ECG) - is a transthoracic interpretation of the electrical activity of the heart over time captured and externally recorded by skin electrodes. Electrocardiography is an essential tool in diagnosing cardiac disorders.
 Advantages of ECG are: it's painless, noninvasive, safe, inexpensive, and easy to perform. The necessary equipment is widely available.</p>

   <p>Electrocardiography belongs to compulsory diagnostic method. The exercise ECG test is the most widely used method of diagnosing coronary heart disease (CHD) and its manifestations: stenocardia and myocardial infarction. Such method is a great help in diagnosis of electrolyte imbalance (calcium and potassium dysbolism) and extra cardiac pathology, for example, pulmonary disease. 24-hour monitoring  ECG, veloergometry, treadmill test  are used for increasing the effectiveness of this method. </p>

					</div>
				</div>
				<div style="font-style:normal; padding-top:16px;"><b style="color:#900; font-size:18px;"><img src="../root/msite/kardio/heart.png" width="20px" height="20px" /> Holter monitoring (ECG)</b>
					<div style="color:black; font-size:12px; padding:5px;">
					<p>
					Holter monitor is a portable device for continuously monitoring various electrical activity of the central nervous system for at least 24 hours. Its extended recording period is sometimes useful for observing occasional cardiac arrhythmias or epileptic events which would be difficult to identify in a shorter period of time. For patients having more transient symptoms, a cardiac event monitor which can be worn for a month or more can be used.
The Holter monitor can record heart rate and rhythm when you feel chest pain or symptoms of an irregular heartbeat (called arrhythmia). Your doctor can then look at the time when you noticed your symptoms.</p><p>
What is the concept of using a Holter monitor?</p><p>
The Holter monitor will continuously document and save a record of your heart rhythm (ECG).  Any episodes of abnormal or irregular heart rhythms will be documented on the recording.   By examining this recording, the physician will be able to determine if your symptoms and heart activity are related.  An important aspect of Holter monitoring is keeping a detailed diary that notes exact symptoms, time of symptoms and what your activity was during the symptoms.</p>

					</div>
				</div>
			</b>
		</div>
     </div>
       
    </div>
</div>
<?php
}
else
   if ($_GET['pm'] == 3)
   {
?>
<div class="catalogue_item_cont_m"> 
<div class="sequ_conteiner">
    <div class="sequ_up">
		<div style="position:relative; float:left; padding:10px; top:10px; left:50px;"><img src="../root/msite/kardio/ser.png"/></div>
		<div style="position:relative; float:left; left:80px; top:48px; color:#FFF;	font-size:20px; text-align:justify; line-height:1px; letter-spacing:5px;">Personal medical appointment</div>
		<div style="position:relative; float:left; left:190px; top:50px; color:#FFF;	font-size:12px;  line-height:1.2; text-align:right;"><span>Tel.: (066) 907-94-66</span><br />
<div style="color:#95b7e2;">14-E, Iliicha Avenue, Kalininskiy district, Donetsk city <br />
<div style="letter-spacing:2px;">(DOCTMO, Kalinina Hospital),</div>
GERTS Medical centre, 7th floor, 715 room</div></div>
		<div style="position:relative; float:left; clear:left; left:190px; top:-32px; color:#FFF;	font-size:20px; text-align:justify; line-height:1px; letter-spacing:1px; text-transform:uppercase;"><b>with cardiologist- therapeutist</b></div>
		<div style="position:relative; float:left; clear:left; left:190px; top:-17px; color:#FFF; margin-bottom:10px;	font-size:16px; text-align:justify; line-height:1px; letter-spacing:12px;">GERTS Medical centre</div>
    	<!--
		<div style="position:relative; float:left; clear:left; margin-bottom:10; padding:0; left:20; width:100%;"><img src="../root/msite/kardio/up.png" align="left" width="100%" height="105" /></div>
		-->
    </div>
    <div class="sequ_stroke"> 
        <div style="padding:6px; bottom: -10px; color:#264c7b; font-family:'Times New Roman', Times, serif; font-size:20px;">
        Listen to your heart!</div>
        </div>
    <div class="sequ_main_menu">
    	<div style="background: url(../root/msite/kardio/neb.jpg); width:100%; height:452px; position:relative; float:left;">
        	<div style="position:relative; float:left; left:25; width:370;"><img src="../root/msite/kardio/dev.png" align="left" width="367" height="450" /></div>
			<div style="position:relative; float:right; padding:0px;">
				<div class="sequ_a_3"><a href="http://eurodonetsk.com/index.php?business_full=405&pm=3"><img src="../root/msite/kardio/ko_en_on.jpg" width="135" height="36" /></a></div>
				<div class="sequ_a_2"><a href="http://eurodonetsk.com/index.php?business_full=405&pm=2"><img src="../root/msite/kardio/se_en.jpg" width="135" height="36" /></a></div>
				<div class="sequ_a_1"><a href="http://eurodonetsk.com/index.php?business_full=405&pm=1"><img src="../root/msite/kardio/us_en.jpg" width="135" height="36" /></a></div>
			</div>
            
            <div style="padding-top: 100; text-align:left; font-style:italic; color:#264c7b; font:Tahoma, Geneva, sans-serif; font-family:Tahoma, Geneva, sans-serif; font-size:22px; line-height:1.4; padding-left:390; margin-top:100;"><br /><br />Our life and our health 
directly depend on it. That’s why the <br />risk of getting heart disease is supposed to be one of the most widespread and great fear of the person. If you have any complaints of chest pain, 
you should see cardiologist to clarify the reasons of complaints and take stock of the situation.
			</div>       
        </div>
    </div>
    <div class="sequ_podmain">
    	<b>In our centre you can have full diagnostic tests of the Cardiovascular System.</b>
    </div>
	
	<!-- Основной текст -->
	
    <div class="sequ_text">
    	<div style="position:relative; float:left; width:100%;">
			<div id="left_block_sequ_text" style="position:relative; float:left; width:50%; padding:16px; left:25px; text-align:left; font-style:normal; color:black; font:Tahoma, Geneva, sans-serif; font-family:Tahoma, Geneva, sans-serif; font-size:20px; text-indent:0px;">
			<b style="line-height:1.7;">
			14E, Iliicha Avenue, <br />
			Kalininskyi district, Donetsk city,  <br />
			(DOCTMO, Kalinina Hospital ) <br />
			GERTS Medical centre, <br />
			7th floor, 715 room <br />
			<b style="color:#900;">http://www.cardiology.at.ua</b> <br />
			<br />
			<br />
			Working hours <br />
			Daily from 8:00 till 16:00 <br />
			Tel. :+38 066-907-94-66. <br />
			</b>
			</div>
			
		<div id="photo_sequ_bottom" style="position:relative; float:left; margin-top:15px; left:50px;"><img src="../root/msite/kardio/photo.jpg" width="365px" height="484px" align="right" /></div>
		
			<div id="div_st">
        <script src="http://api-maps.yandex.ru/1.1/index.xml?key=AAmDzUsBAAAARkVWCAIAXzMCgKN58_MQUqB134Sdp-unCH0AAAAAAAAAAACbJlz2mcKc4anRgbxx6LBZ5BHPyg==" type="text/javascript"></script>
    <script type="text/javascript">
        window.onload = function () {
            var map = new YMaps.Map(document.getElementById("YMapsID"));
            map.setCenter(new YMaps.GeoPoint(37.824874,48.002321), 17);

            var content = document.createElement('span');
            content.innerHTML = "«GERTS» Medical centre";
            map.openBalloon(new YMaps.GeoPoint(37.824174,48.002221), content);

            map.addControl(new YMaps.ToolBar());
            map.addControl(new YMaps.Zoom());
            map.addControl(new YMaps.MiniMap());
            map.addControl(new YMaps.ScaleLine());
        }
    </script>


	 <div id="YMapsID" style="width:90%; height:450px; position:relative; float:left; top:20px; left:40px; z-index:20; margin-bottom:40px;"></div>
   </div>


			
			
			
			
			
        </div>
    </div>
       
    </div>
</div>

<?php
   } 
?>



<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="index.php?section_id=32&amp;business=1">Category:</a></div>
</div>
<div class="catalogue_item_cont">
<a href="index.php?section_id=2&amp;business=1">Business</a>
 / 
<a href="index.php?section_id=32&amp;business=1">Enterprises</a>
 / 
<a href="index.php?section_id=387&amp;business=2">Medicine</a>
 / 
<a href="index.php?section_id=512&amp;business=2">Cardiology</a>
</div>


<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="">Gallery:</a></div>
</div>
<div class="catalogue_item_cont">
</div>
<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="">Contacts:</div>
</div>
 <div class="catalogue_item_cont">
 		 <table width="100%">
			<tbody>
 			<tr>
			<!--	<td><img class="main_sec_image" src="" width="60" height="60" border="0" alt="" /></td>-->
				<td>Address:</td>
				<td>Phone:</td>
				<td>Fax:</td>
				<td>E-mail:</td>
				<td>WWW:</td>
			</tr>
			<tr>
				<td>14-E, Iliicha Avenue<br /> Kalininskiy district<br /> Donetsk city<br />(DOCTMO, Kalinina Hospital ) <br />
			GERTS Medical centre, <br />
			7th floor, 715 room</td>
				<td>+38 066-907-94-66.</td>
				<td></td>
				<td></td>
				<td></td>

			</tr>
			</tbody> 
		 </table> 		
	 </div>
</div>  


