 <div class="catalogue_item_c">
<style>
.catalogue_item_cont p {
color:#000000;
text-align:justify;
text-indent:0px;
line-height:20px;
margin:0px;
}

img.main_sec_image {
border:none;
}
.catalogue_item_cont_m {
background-color:#FFFFFF;
border:1px solid lightgray;
color:#000000;
margin:0;
margin:15px 10px 10px;
width:980px;
}
.catalogue_item_cont {
background-color:#ffffff;
border-top:1px solid lightgray;
margin:0 0 7px 10px;
width:980px;
color:#000000;
}
.catalogue_item_c {
background-color:#F3F3F3;
}

a.menu_text {font-size:18px;font-weight:bold;color:#ffffff;}

img.main_sec_image {
height:240px;
padding:0;
width:240px;
}
#main_text {float:left;
height:700px;
line-height:20px;
padding-right:20px;
text-align:justify;
width:580px;}

.catalogue_item_cont a {
color:#000000;
}
.catalogue_item_cont a:hover {
color:#000000;
text-decoration:underline;
}
.catalogue_item_mp_a {
left:3px;
position:relative;
}

#mm_menu {position:relative;left:610px;width:225px;text-align:center;} 

#div_st {padding:0 50px;position:relative;height:800px;}

@media all and (-webkit-min-device-pixel-ratio:10000),
not all and (-webkit-min-device-pixel-ratio:0) {
 #div_st {height:869px;}
}
td#i_up {font-weight:bold;text-align:center;}
td#i_up1 {font-weight:bold;text-decoration:underline;}
td#i_first {width:510px;text-align:left;font-size:16px;}
td#i_second {width:75px;font-size:14px;}
td#i_third {width:50px;font-size:14px;}
table#i_table tr {height:35px;}
</style>
<?php
if ($_GET['pm'] == 1) 
{
?>

<div class="catalogue_item_cont_m"> 
<img src="root/st_h/up.png" alt="" style="width: 100%;" />
<div id="div_st">
<p>
<div id="mm_menu" style="top:-205px;"><a href="index.php?business_full=396&amp;pm=1"  class="menu_text"><b>MAIN</b></a></div>
<div id="mm_menu" style="top:-190px;"><a href="index.php?business_full=396&amp;pm=2" class="menu_text">MENU</a></div>
<div id="mm_menu" style="top:-175px;"><a href="index.php?business_full=396&amp;pm=3" class="menu_text">CONTACTS</a></div>
</p>
<br>
<div id="main_text">
<p><b>Steak House Cafe</b> is famous for its appetizing meat and fish steaks.
Various menu, excellent service and convenient location of our café attract as Donetsk citizens, so the guests of our city.</p>
<br>
<p><u>Menu:</u><br>
In the ”Steak House” menu one can find dishes of European and home cuisines. Special offer is Lenten menu.</p>
<br>
<p><u>Special services:</u><br>
arrangement of banquets, banquets – stand – up meal (catering), holding of corporate events, marriages and anniversaries.</p>
<br>
<p><u>Halls:</u><br>
- The main hall is for 80 seats,<br>- banquet hall – for 15 seats,<br>- outdoor ground – 25 seats.</p>
<br>
<p><u>Payment:</u><br>
cash, credit cards and non-cash payment</p>
<br>
<p><u>Bonuses:</u><br>
Discount cards for regular guests.</p>
<br>
<p><u>Location of the Café:</u><br>
<b>Steak House Cafe </b> is situated in the center of Donetsk.<br>. It will take 5 minutes to get to our cafe from the Lenin square, <br>and 10 minutes from “Donbass Arena” stadium. </p>
<br>
<p><u>Working hours:</u> <b>24 hours</b><br>
Donetsk city,Teatralniy Avenue, 28 <br>Tel. (062)335-23-68</p>
</div>
<div>
<img class="main_sec_image" src="root/st_h/01.png" alt="" style="float: left;" /><img class="main_sec_image" src="root/st_h/02.png" alt="" style="float: left;" />
<img class="main_sec_image" src="root/st_h/03.png" alt="" style="float: left;" /><br><br>
</div>
<br>
<br>
</div>
</div>
<?php
}
else
   if ($_GET['pm'] == 2)
   {
?>
<div class="catalogue_item_cont_m"> 
<img src="root/st_h/up.png" alt="" style="width: 100%;" />
<div id="div_st" style="height: 15290px;">
<p>
<div id="mm_menu" style="top:-205px;"><a href="index.php?business_full=396&amp;pm=1"  class="menu_text"><b>MAIN</b></a></div>
<div id="mm_menu" style="top:-190px;"><a href="index.php?business_full=396&amp;pm=2" class="menu_text">MENU</a></div>
<div id="mm_menu" style="top:-175px;"><a href="index.php?business_full=396&amp;pm=3" class="menu_text">CONTACTS</a></div>
<br>
<table style="width:870px;" id="i_table">
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><i> Cold starters</i><br><br><br></td></tr>    
    <tr>
        <td id="i_first"><b>vegetable crudities</b><font style="font-size:14px;"><br>(fresh tomatoes,  cucumbers,   bell peppers, greens)</font></td>
        <td id="i_second" colspan="2">250</td>
        <td id="i_second" colspan="2">17-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Pickled cucumbers</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">8-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Pickled tomatoes</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">8-00</td>
    </tr>
    <tr>
        <td id="i_first"><b> Cold cuts</b><font style="font-size:14px;"><br( "Darnitskyi" balyk, ham,  uncooked smoked sausage,)</font></td>
        <td id="i_second" colspan="2">250</td>
        <td id="i_second" colspan="2">36-00</td>
    </tr>
    <tr>
        <td id="i_first"><b> Cheese platter</b><font style="font-size:14px;"><br>(Radomer cheese, Russian cheese)</font></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">30-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Homemade bacon (Salo)</b><font style="font-size:14px;"><br>(salted bacon, served with garlic cloves)</font></td>
        <td id="i_second" colspan="2">100/43</td>
        <td id="i_second" colspan="2">14-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Ox Tongue</b><font style="font-size:14px;"><br>(boiled Ox tongue, served with mayonnaise sauce )</font></td>
        <td id="i_second" colspan="2">100/30</td>
        <td id="i_second" colspan="2">25-00</td>
    </tr>
    <tr>
        <td id="i_first"><b> Light-salted salmon</b><font style="font-size:14px;"><br>(salmon fillet, served with butter)</font></td>
        <td id="i_second" colspan="2">95/45</td>
        <td id="i_second" colspan="2">32-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Vinegar pickled mushrooms</b><font style="font-size:14px;"><br>(Vinegar pickled champignons with green onion)</font></td>
        <td id="i_second" colspan="2">100</td>
        <td id="i_second" colspan="2">16-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Olives</b><font style="font-size:14px;"><br>(pitted olives or whole olives)</font></td>
        <td id="i_second" colspan="2">100</td>
        <td id="i_second" colspan="2">16-00</td>
    
    </tr>
    <tr>
        <td id="i_first"><b>  Lemon with sugar</b></td>
        <td id="i_second" colspan="2">50/20</td>
        <td id="i_second" colspan="2">4-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Butter</b></td>
        <td id="i_second" colspan="2">50</td>
        <td id="i_second" colspan="2">3-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>  Sandwich with red caviar</b></td>
        <td id="i_second" colspan="2">40</td>
        <td id="i_second" colspan="2">16-00</td>
    </tr>
    <tr>
        <td id="i_first"><b> Boiled shrimps</b></td>
        <td id="i_second" colspan="2">100/20</td>
        <td id="i_second" colspan="2">17-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Fried vegetable marrows</b><font style="font-size:14px;"><br>(Fried vegetable marrows served with mayonnaise sauce and garlic)</font></td>
        <td id="i_second" colspan="2">280</td>
        <td id="i_second" colspan="2">25-00</td>
    </tr>
      <tr>
        <td id="i_first"><b>Fried eggplants</b><font style="font-size:14px;"><br>(Fried eggplants served with tomatoes, mayonnaise sauce and garlic)</font></td>
        <td id="i_second" colspan="2">280</td>
        <td id="i_second" colspan="2">25-00</td>
    </tr>
       <tr>
        <td id="i_first"><b>Appetite herring</b></td>
        <td id="i_second" colspan="2">150</td>
        <td id="i_second" colspan="2">15-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><br><br><i>Salads</i><br></td></tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>*** Seafood Salads ***</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Neptune Salad</b><font style="font-size:14px;"><br>(crab sticks, cucumber, eggs,  cheese,  corn)</font></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">20-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Sea Fantasy Salad</b><font style="font-size:14px;"><br>(squid,  mussels,shrimps,lettuce,tomatoes, salad-oil, olive oil,  vinegar)</font></td>
        <td id="i_second" colspan="2">175</td>
        <td id="i_second" colspan="2">30-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Lagoon Island Salad</b><font style="font-size:14px;"><br>(eggs, salmon, cucumbers, apple, mayonnaise sauce)</font></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">25-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Sea Pearl Salad</b><font style="font-size:14px;"><br>(eggs,tomatoes, shrimps, squids,mayonnaise sauce, garlic,  lemon)</font></td>
        <td id="i_second" colspan="2">220</td>
        <td id="i_second" colspan="2">28-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Hot Salad with  salmon</b><font style="font-size:14px;"><br>(fried salmon, tomatoes, cucumbers, olives,  lettuce,vinegar,salad-oil)</font></td>
        <td id="i_second" colspan="2">220</td>
        <td id="i_second" colspan="2">35-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>***meat salads ***</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Transylvania Salad</b><font style="font-size:14px;"><br>(napa  cabbage (Headed Chinese Cabbage), tomatoes, cucumbers,  ham,sesame, fried chicken fillet and  fillet of veal )</font></td>
        <td id="i_second" colspan="2">215</td>
        <td id="i_second" colspan="2">30-00</td>
    </tr>
    <tr>
        <td id="i_first"><b> Chinese Salad</b><font style="font-size:14px;"><br>( omelette, cucumber, carrot,  napa  cabbage, boiled beef, soy sauce,mayonnaise sauce)</font></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">20-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>English Salad</b><font style="font-size:14px;"><br>(chicken, roasted mushrooms,pickled cucumbers, mayonnaise sauce, mustard))</font></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">20-00</td>
    </tr>
    <tr>
        <td id="i_first"><b> Bremen Salad</b><font style="font-size:14px;"><br>(fresh  champignons, chicken fillet, tomatoes,lettuce,toasts, dressing)</font></td>
        <td id="i_second" colspan="2">210</td>
        <td id="i_second" colspan="2">25-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Metropolitan Salad</b><font style="font-size:14px;"><br>(Classic Recipe with  boiled fowl)</font></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">17-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Caesaron Salad</b><font style="font-size:14px;"><br>(chicken fillet,  ham, lettuce, toasts, cheese, mayonnaise sauce,  mustard)</font></td>
        <td id="i_second" colspan="2">250</td>
        <td id="i_second" colspan="2">30-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Chicken Caesar Salad</b><font style="font-size:14px;"><br>(Classic salad with CAESAR DRESSING and Parmesan cheese)</font></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">30-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Potato  Boom Salad</b><font style="font-size:14px;"><br>(chicken fillet, ham, vinegar pickled mushrooms,  fried potatoes, eggs,cheese, mayonnaise sauce, garlic)</font></td>
        <td id="i_second" colspan="2">230</td>
        <td id="i_second" colspan="2">30-00</td>
    </tr>
   <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>*** with Ox tongue ***</i><br></td></tr>
    <tr>
        <td id="i_first"><b> Special Salad</b><font style="font-size:14px;"><br>(Ox tongue,  roasted mushrooms, carrot, mayonnaise sauce)</font></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">25-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>***vegetable salads***</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Greek Salad</b><font style="font-size:14px;"><br>(tomatoes,cucumbers,olives, sweet pepper, cheese,olive oil,walnut,lemon juice )</font></td>
        <td id="i_second" colspan="2">225</td>
        <td id="i_second" colspan="2">20-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Spring Salad</b><font style="font-size:14px;"><br>(Lollo Rosso Salad, Iceberg salad, tomatoes, cucumbers,  small radish, sweet pepper, champignons, fennel, olive oil, vinegar)</font></td>
        <td id="i_second" colspan="2">250</td>
        <td id="i_second" colspan="2">25-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Vinigret Salad</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">18-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Sour cabbage salad</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">14-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Fresh cabbage Salad dressed with mayonnaise sauce</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">14-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Fresh cabbage Salad dressed with salad oil</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">14-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Garden salad</b><font style="font-size:14px;"><br>(tomatoes, cucumbers,green onion, salad-oi)</font></td>
        <td id="i_second" colspan="2">250</td>
        <td id="i_second" colspan="2">14-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><br><br><br><i> Hot starters</i><br><br><br></td></tr>
    <tr>
        <td id="i_first"><b>Cheese straws with Tartar sauce</b></td>
        <td id="i_second" colspan="2">170/50</td>
        <td id="i_second" colspan="2">24-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Barbecue Chicken Wings</b></td>
        <td id="i_second" colspan="2">210/60</td>
        <td id="i_second" colspan="2">27-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Chicken and Mushroom Julienne</b></td>
        <td id="i_second" colspan="2">150</td>
        <td id="i_second" colspan="2">18-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Tomato and Cheese Omelette</b></td>
        <td id="i_second" colspan="2">220/50</td>
        <td id="i_second" colspan="2">15-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Bacon and eggs</b></td>
        <td id="i_second" colspan="2">130</td>
        <td id="i_second" colspan="2">10-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Homemade fried mushrooms</b></td>
        <td id="i_second" colspan="2">150</td>
        <td id="i_second" colspan="2">15-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Roasted Cauliflower with sour cream</b></td>
        <td id="i_second" colspan="2">210/50</td>
        <td id="i_second" colspan="2">20-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><br><br><br><i>Pizza</i><br><br><br></td></tr>
    <tr>
        <td id="i_first"><b>Espanola</b><font style="font-size:14px;"><br>(shrimps, chicken,  uncooked smoked sausage,tomatoes, cheese) </font></td>
        <td id="i_second" colspan="2">450</td>
        <td id="i_second" colspan="2">40-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Sea Star</b><font style="font-size:14px;"><br>(salmon, shrimps, tomatoes, cheese)</font></td>
        <td id="i_second" colspan="2">560</td>
        <td id="i_second" colspan="2">60-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Steak House</b><font style="font-size:14px;"><br>(ham, balyk, sweet pepper, tomatoes, cheese) </font></td>
        <td id="i_second" colspan="2">500</td>
        <td id="i_second" colspan="2">45-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Salami</b><font style="font-size:14px;"><br>(sausage, mushrooms, cheese,   sauce)</font></td>
        <td id="i_second" colspan="2">440</td>
        <td id="i_second" colspan="2">38-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Gourmet</b><font style="font-size:14px;"><br>(beef, mushrooms, tomatoes, cheese, sauce )</font></td>
        <td id="i_second" colspan="2">570</td>
        <td id="i_second" colspan="2">40-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Spicy</b><font style="font-size:14px;"><br>(pork, mushrooms, tomatoes, cheese, garlic, sauce)</font></td>
        <td id="i_second" colspan="2">510</td>
        <td id="i_second" colspan="2">40-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Italian Taste</b><font style="font-size:14px;"><br>(chicken, tomatoes, cheese, mushrooms, sauce) </font></td>
        <td id="i_second" colspan="2">500</td>
        <td id="i_second" colspan="2">44-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Hunting</b><font style="font-size:14px;"><br>(ox's tongue, sausages, olives, sweet pepper, cheese) </font></td>
        <td id="i_second" colspan="2">460</td>
        <td id="i_second" colspan="2">44-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Neopolitano</b><font style="font-size:14px;"><br>(smoked chicken, broccoli, mushrooms, cheese)</font></td>
        <td id="i_second" colspan="2">500</td>
        <td id="i_second" colspan="2">38-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Solyanka</b><font style="font-size:14px;"><br>(beef,pork, sausages,pickled cucumbers,capers, mushrooms,cheese, garlic)</font></td>
        <td id="i_second" colspan="2">550</td>
        <td id="i_second" colspan="2">45-00</td>
    </tr>
     <tr><td colspan="3" id="i_up" style="font-size:16px;"><br><br><br><i>First courses</i><br><br><br></td></tr>
     <tr>
        <td id="i_first"><b>Bozbash Soup</b><font style="font-size:14px;"><br>(Lamb Meatballs with vegetables)</font></td>
        <td id="i_second" colspan="2">400</td>
        <td id="i_second" colspan="2">27-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Vegetable soup</b></td>
        <td id="i_second" colspan="2">400</td>
        <td id="i_second" colspan="2">14-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Ukha</b></td>
        <td id="i_second" colspan="2">400</td>
        <td id="i_second" colspan="2">24-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Borscht (Beetroot and cabbage soup with  sour cream, onion and garlic)</b></td>
        <td id="i_second" colspan="2">400/20/35</td>
        <td id="i_second" colspan="2">17-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Solyanka with meat</b></td>
        <td id="i_second" colspan="2">400</td>
        <td id="i_second" colspan="2">20-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Chicken soup with egg and  toasts</b></td>
        <td id="i_second" colspan="2">240/50</td>
        <td id="i_second" colspan="2">14-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Calf Cream soup with mushrooms</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">17-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Okroshka</b><font style="font-size:14px;"><br>(A cold soup based on kvas, green onion, herbs and spices such as black pepper, mustard or horse radish</font></td>
        <td id="i_second" colspan="2">400</td>
        <td id="i_second" colspan="2">17-00</td>
    </tr>
     <tr><td colspan="3" id="i_up" style="font-size:16px;"><br><br><i>Main Courses</i><br></td></tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>*** Fish dishes ***</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Salmon Steak with red caviar sauce</b><font style="font-size:14px;"><br>Filleted salmon cooked on the grill served  with red caviar sauce</font></td>
        <td id="i_second" colspan="2">150/75/39</td>
        <td id="i_second" colspan="2">62-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Poached Salmon Steak</b><font style="font-size:14px;"><br>Poached Salmon Steak  served with rice</font></td>
        <td id="i_second" colspan="2">150/150/39</td>
        <td id="i_second" colspan="2">60-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Common sole</b><font style="font-size:14px;"><br>Pangasius fillet served with sauce</font></td>
        <td id="i_second" colspan="2">175/35</td>
        <td id="i_second" colspan="2">30-00</td>
    </tr>
    <tr>
       
        <td id="i_first"><b> Baked Pangasius</b><font style="font-size:14px;"><br>Pangasius fillet, potatoes, tomatoes baked with cheese</font></td>
        <td id="i_second" colspan="2">300/39</td>
        <td id="i_second" colspan="2">30-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Fried Fish with Tartar Sauce</b><font style="font-size:14px;"><br>Pangasius breaded fillet served with Tartar Sauce and lettuce</font></td>
        <td id="i_second" colspan="2">165/50/39</td>
        <td id="i_second" colspan="2">30-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>*** Meat dish ***</i><br></td></tr>
    <tr>
        <td id="i_first"><b>"Steak House" Steak </b><font style="font-size:14px;"><br>Brisket pork, chicken fillet baked with cheese and vegetables</font></td>
        <td id="i_second" colspan="2">500/50</td>
        <td id="i_second" colspan="2">55-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Fajitas</b><font style="font-size:14px;"><br>Filets of beef, pork-loin, chicken fillet, roasted with bulb onion , sweet pepper. Served with vegetables</font></td>
        <td id="i_second" colspan="2">200/50</td>
        <td id="i_second" colspan="2">34-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Donbass style cutlet</b></td>
        <td id="i_second" colspan="2">200/50</td>
        <td id="i_second" colspan="2">22-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>*** Mutton dish ***</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Roast mutton with Rice & Vegetables</b></td>
        <td id="i_second" colspan="2">250/150</td>
        <td id="i_second" colspan="2">60-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>***Beef dish ***</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Spanish Style Beef</b><font style="font-size:14px;"><br>Filets of beef, sweet pepper, Yard Long Bean, served with vegetables</font></td>
        <td id="i_second" colspan="2">195/50</td>
        <td id="i_second" colspan="2">35-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Beef Steak</b><font style="font-size:14px;"><br>Grilled Beef Steak with spices, served with vegetables</font></td>
        <td id="i_second" colspan="2">130/50</td>
        <td id="i_second" colspan="2">35-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>"Round" Steak</b><font style="font-size:14px;"><br>Beef Steak served with vegetables</font></td>
        <td id="i_second" colspan="2">200/50</td>
        <td id="i_second" colspan="2">50-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>*** Pork Dishes ***</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Nakovsky Steak</b><font style="font-size:14px;"><br>Pork Steak baked with cheese, served with vegetables</font></td>
        <td id="i_second" colspan="2">280/50</td>
        <td id="i_second" colspan="2">38-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Bone-in pork Steak</b><font style="font-size:14px;"><br>Grilled bone-in pork loin with spices</font></td>
        <td id="i_second" colspan="2">150/50</td>
        <td id="i_second" colspan="2">35-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>The Yummy dish!!!</b><font style="font-size:14px;"><br>Pork roll stuffed with mushrooms and tomatoes,baked with cheese served with vegetables and sauce</font></td>
        <td id="i_second" colspan="2">240/50</td>
        <td id="i_second" colspan="2">40-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Quail Nest</b><font style="font-size:14px;"><br>Pork chop baked with mushrooms and eggs, served with vegetables</font></td>
        <td id="i_second" colspan="2">175/50</td>
        <td id="i_second" colspan="2">30-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Battered Pork Chop</b></td>
        <td id="i_second" colspan="2">130/50</td>
        <td id="i_second" colspan="2">25-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Homemade Hot Pot</b></td>
        <td id="i_second" colspan="2">420</td>
        <td id="i_second" colspan="2">30-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>French style meat</b></td>
        <td id="i_second" colspan="2">190/50</td>
        <td id="i_second" colspan="2">30-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>*** Chicken Dishes ***</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Chicken Steak à la Sauce Mornay</b><font style="font-size:14px;"><br>Chicken fillet with mushrooms baked with cheese à la Sauce Mornay</font></td>
        <td id="i_second" colspan="2">300</td>
        <td id="i_second" colspan="2">32-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Chicken fillet  stuffed  with mushrooms and cheese</b></td>
        <td id="i_second" colspan="2">260/50</td>
        <td id="i_second" colspan="2">32-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>European zrazy</b><font style="font-size:14px;"><br>Meat balls stuffed with rice</font></td>
        <td id="i_second" colspan="2">130/50</td>
        <td id="i_second" colspan="2">14-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Kiev style chicken</b><font style="font-size:14px;"><br>A dish of boneless chicken breast pounded and rolled around cold unsalted butter, then breaded and fried</font></td>
        <td id="i_second" colspan="2">300/50</td>
        <td id="i_second" colspan="2">140/50</td>
        <td id="i_second" colspan="2">20-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Irish  vegetable stew with chicken fillet</b><font style="font-size:14px;"><br>chicken fillet  fried with   broccoli sprout,  Brussel sprouts,yardlong bean, tomatoes, sweet pepper, potatoes</font></td>
        <td id="i_second" colspan="2">300/50</td>
        <td id="i_second" colspan="2">30-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><br><br><br><i>Farinaceous dish</i><br><br></td></tr>
    <tr>
        <td id="i_first"><b>Dumplings  (Vareniki) with mashed potatoes</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">15-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Dumplings (Vareniki) with sour cabbage</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">15-00</td>
    </tr>
    <tr>
        <td id="i_first"><b> Meat pockets (Pelmeni)</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">20-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Seafood Pasta</b><font style="font-size:14px;"><br> Durum Wheat Spaghetti with seafood products</font></td>
        <td id="i_second" colspan="2">260</td>
        <td id="i_second" colspan="2">45-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><br><br><br><i>Garnishes</i><br><br></td></tr>
    <tr>
        <td id="i_first"><b>Fries</b></td>
        <td id="i_second" colspan="2">100</td>
        <td id="i_second" colspan="2">12-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Fried potatoes with mushrooms</b></td>
        <td id="i_second" colspan="2">175</td>
        <td id="i_second" colspan="2">15-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Mashed Potatoes</b></td>
        <td id="i_second" colspan="2">160</td>
        <td id="i_second" colspan="2">8-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Boiled New Potatoes  with fennel</b></td>
        <td id="i_second" colspan="2">180</td>
        <td id="i_second" colspan="2">8-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Potatoe Croquettes</b></td>
        <td id="i_second" colspan="2">120</td>
        <td id="i_second" colspan="2">10-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Boiled rice</b></td>
        <td id="i_second" colspan="2">160</td>
        <td id="i_second" colspan="2">7-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Rice with vegetables</b></td>
        <td id="i_second" colspan="2">150</td>
        <td id="i_second" colspan="2">10-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Rice with egg and shrimps</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">22-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><br><br><br><i>Blinis</i><br><br></td></tr>
    <tr>
        <td id="i_first"><b>Blinis with butter and honey</b></td>
        <td id="i_second" colspan="2">221/50</td>
        <td id="i_second" colspan="2">18-00</td>
    </tr>
    <tr>
        <td id="i_first"><b> Blinis with   red caviar</b></td>
        <td id="i_second" colspan="2">161</td>
        <td id="i_second" colspan="2">25-50</td>
    </tr>
    <tr>
        <td id="i_first"><b>Blinis with meat and Sour cream</b></td>
        <td id="i_second" colspan="2">280</td>
        <td id="i_second" colspan="2">25-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Blinis with cream cheese and trawberry jam</b></td>
        <td id="i_second" colspan="2">252</td>
        <td id="i_second" colspan="2">25-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Blinis with strawberry and dairy cream</b></td>
        <td id="i_second" colspan="2">350</td>
        <td id="i_second" colspan="2">25-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><br><br><br><i> Desserts</i><br><br></td></tr>
    <tr>
        <td id="i_first"><b>Panna Cotta Dessert</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">15-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Fruit Salad</b><font style="font-size:14px;"><br>/Apple,Orange,Kiwi,Banan,Grape and dairy cream/</font></td>
        <td id="i_second" colspan="2">350</td>
        <td id="i_second" colspan="2">22-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>"Steak House" Ice cream</b></td>
        <td id="i_second" colspan="2">250</td>
        <td id="i_second" colspan="2">22-00</td>
    </tr>
    <tr>
        <td id="i_first"><b> Ice cream in  pineapple</b></td>
        <td id="i_second" colspan="2">500</td>
        <td id="i_second" colspan="2">27-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Ice cream</b><font style="font-size:14px;"><br>/full-cream ice, coffee ice cream/</font></td>
        <td id="i_second" colspan="2">50</td>
        <td id="i_second" colspan="2">5-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>Order to dessert:</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Almond nut</b></td>
        <td id="i_second" colspan="2">25</td>
        <td id="i_second" colspan="2">4-50</td>
    </tr>
    <tr>
        <td id="i_first"><b>English walnut</b></td>
        <td id="i_second" colspan="2">25</td>
        <td id="i_second" colspan="2">2-50</td>
    </tr>
    <tr>
        <td id="i_first"><b>Raisins</b></td>
        <td id="i_second" colspan="2">25</td>
        <td id="i_second" colspan="2">2-50</td>
    </tr>
    <tr>
        <td id="i_first"><b>Dairy cream</b></td>
        <td id="i_second" colspan="2">50</td>
        <td id="i_second" colspan="2">2-50</td>
    </tr>
    <tr>
        <td id="i_first"><b>Crude chocolate</b></td>
        <td id="i_second" colspan="2">25</td>
        <td id="i_second" colspan="2">2-50</td>
    </tr>
    <tr>
        <td id="i_first"><b>Strawberry jam</b></td>
        <td id="i_second" colspan="2">25</td>
        <td id="i_second" colspan="2">2-50</td>
    </tr>
    <tr>
        <td id="i_first"><b> Chocolate jam</b></td>
        <td id="i_second" colspan="2">25</td>
        <td id="i_second" colspan="2">2-50</td>
    </tr>
    <tr>
        <td id="i_first"><b>Kiwi jam</b></td>
        <td id="i_second" colspan="2">25</td>
        <td id="i_second" colspan="2">2-50</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><br><br><i>Lenten Menu</i><br></td></tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>Cold starters</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Pickled cucumbers</b></td>
        <td id="i_second" colspan="2">100</td>
        <td id="i_second" colspan="2">7-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Pickled tomatoes</b></td>
        <td id="i_second" colspan="2">100</td>
        <td id="i_second" colspan="2">7-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Vinegar pickled mushrooms</b></td>
        <td id="i_second" colspan="2">105</td>
        <td id="i_second" colspan="2">14-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Olives</b></td>
        <td id="i_second" colspan="2">100</td>
        <td id="i_second" colspan="2">14-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Lemon with sugar</b></td>
        <td id="i_second" colspan="2">50/20</td>
        <td id="i_second" colspan="2">4-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Specialty Plated Appetizer</b></td>
        <td id="i_second" colspan="2">290</td>
        <td id="i_second" colspan="2">25-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>Salads</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Spring salad</b><font style="font-size:14px;"><br>(Lollo Rosso Salad, Iceberg salad, tomatoes, cucumbers,  small radish sweet pepper,champignons, fennel, olive oil, vinegar)</font></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">25-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Vinigret Salad</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">14-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Salad with nappa cabbage</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">14-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Salad with  sour cabbage</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">14-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Fresh cabbage Salad dressed with salad oil</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">14-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Garden salad</b><font style="font-size:14px;"><br>(tomatoes, cucumbers,green onion, salad-oil)</font></td>
        <td id="i_second" colspan="2">250</td>
        <td id="i_second" colspan="2">14-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>First courses</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Vegetable soup</b></td>
        <td id="i_second" colspan="2">400</td>
        <td id="i_second" colspan="2">12-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Cream soup with mushrooms</b></td>
        <td id="i_second" colspan="2">400</td>
        <td id="i_second" colspan="2">12-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Lentil soup with eggplants</b></td>
        <td id="i_second" colspan="2">400</td>
        <td id="i_second" colspan="2">15-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Lavash</b></td>
        <td id="i_second" colspan="2">50</td>
        <td id="i_second" colspan="2">1-50</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i> Main Courses/ Garnishes</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Home style fried mushrooms</b></td>
        <td id="i_second" colspan="2">150</td>
        <td id="i_second" colspan="2">15-00</td>
    </tr>
    <tr>
        <td id="i_first"><b> Mix vegetable</b></td>
        <td id="i_second" colspan="2">180</td>
         <td id="i_second" colspan="2">15-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Lobio</b><font style="font-size:14px;"><br>(Beans, mushrooms,coriander)</font></td>
        <td id="i_second" colspan="2">155</td>
         <td id="i_second" colspan="2">15-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Vegetable stew with mushrooms</b><font style="font-size:14px;"><br>(broccoli,carrot, tomatoes,sweet pepper,potatoes)</font></td>
        <td id="i_second" colspan="2"></td>
        <td id="i_second" colspan="2">15-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Dumplings  (Vareniki) with mashed potatoes</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">10-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Dumplings (Vareniki) with sour cabbage</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">10-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Baked potatoes</b></td>
        <td id="i_second" colspan="2">325</td>
        <td id="i_second" colspan="2">15-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Boiled buckwheat with mushrooms</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">8-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Vegetable pilau</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">10-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Fries</b></td>
        <td id="i_second" colspan="2">100</td>
        <td id="i_second" colspan="2">9-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Fried potatoes with mushrooms</b></td>
        <td id="i_second" colspan="2">175</td>
        <td id="i_second" colspan="2">15-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Boiled New Potatoes  with fennel</b></td>
        <td id="i_second" colspan="2">180</td>
        <td id="i_second" colspan="2">6-00</td>
    </tr>
    <tr>
        <td id="i_first"><b> Potatoe Croquettes</b></td>
        <td id="i_second" colspan="2">120</td>
        <td id="i_second" colspan="2">8-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Boiled rice</b></td>
        <td id="i_second" colspan="2">160</td>
        <td id="i_second" colspan="2">6-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Rice with vegetables</b></td>
        <td id="i_second" colspan="2">150</td>
        <td id="i_second" colspan="2">8-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>Desserts</i><br></td></tr>
    <tr>
        <td id="i_first"> Apples, Oranges,Bananas,grapefruit<b></b></td>
        <td id="i_second" colspan="2">100</td>
        <td id="i_second" colspan="2">4-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Kiwi</b></td>
        <td id="i_second" colspan="2">1 шт.</td>
        <td id="i_second" colspan="2">4-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Grapes</b></td>
        <td id="i_second" colspan="2">100</td>
        <td id="i_second" colspan="2">8-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Baked apple</b></td>
        <td id="i_second" colspan="2">160</td>
        <td id="i_second" colspan="2">10-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Almond</b></td>
        <td id="i_second" colspan="2">25</td>
        <td id="i_second" colspan="2">4-50</td>
    </tr>
    <tr>
        <td id="i_first"><b>Circassian walnut</b></td>
        <td id="i_second" colspan="2">25</td>
        <td id="i_second" colspan="2">2-20</td>
    </tr>
    <tr>
        <td id="i_first"><b>Raisins</b></td>
        <td id="i_second" colspan="2">25</td>
        <td id="i_second" colspan="2">1-50</td>
    </tr>
    <tr>
        <td id="i_first"><b>Blinis with fruits</b></td>
        <td id="i_second" colspan="2" colspan="2">280</td>
        <td id="i_second" colspan="2" colspan="2">18-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><br><br><br><i>Alcoholic drinks</i><br><br><br></td></tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><i>Vodka</i><br></td></tr>
    <tr>
        <td id="i_first"><i><center>Name</center></i></td>
        <td id="i_third"><font style="font-size:12px;">Bottle capacity</font></td>
        <td id="i_third"><font style="font-size:12px;">Bottle Price UAH</font></td>
        <td id="i_third"><font style="font-size:12px;">Price 100 ml</font></td>
        <td id="i_third"><font style="font-size:12px;">Price 50 ml</font></td>
    </tr>
    <tr>
        <td id="i_first"><b>Russian Standard</b></td>
        <td id="i_third">0,5</td>
        <td id="i_third">150-00</td>
        <td id="i_third">30-00</td>
        <td id="i_third">15-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Khortytsa</b><font style="font-size:14px;"><br>/VIP CLUB Platinum,VIP Club/</font></td>
        <td id="i_third">0,7</td>
        <td id="i_third">154-00</td>
        <td id="i_third">22-00</td>
        <td id="i_third">11-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Pulse</b><font style="font-size:14px;"><br>/Ice, Power/</font></td>
        <td id="i_third">0,5</td>
        <td id="i_third">55-00</td>
        <td id="i_third">11-00</td>
        <td id="i_third">5-50</td>
    </tr>
    <tr>
        <td id="i_first"><b>Пульс</b><font style="font-size:14px;"><br>/Aktive, Elite/</font></td>
        <td id="i_third">0,5</td>
        <td id="i_third">50-00</td>
        <td id="i_third">10-00</td>
        <td id="i_third">5-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Khortytsa</b><font style="font-size:14px;"><br>/Silver,Platinum,Classic,Gold,Premium/</font></td>
        <td id="i_third">0,5</td>
        <td id="i_third">55-00</td>
        <td id="i_third">11-00</td>
        <td id="i_third">5-50</td>
    </tr>
    <tr>
        <td id="i_first"><b>BLAGOFF</b><font style="font-size:14px;"><br>/зGreen apple,Premium,Original/</font></td>
        <td id="i_third">0,5</td>
        <td id="i_third">50-00</td>
        <td id="i_third">10-00</td>
        <td id="i_third">5-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Khlebniy dar</b></td>
        <td id="i_third">0,5</td>
        <td id="i_third">50-00</td>
        <td id="i_third">10-00</td>
        <td id="i_third">5-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><i>Tequila </i><br></td></tr>
    <tr>
        <td id="i_first"><b>Olmeca Tequila </b></td>
        <td id="i_third">1,0</td>
        <td id="i_third">400-00</td>
        <td id="i_third">40-00</td>
        <td id="i_third">20-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><i>Liqueur</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Xenta absinthe</b></td>
        <td id="i_third">1,0</td>
        <td id="i_third">550-00</td>
        <td id="i_third">55-00</td>
        <td id="i_third">27-50</td>
    </tr>
    <tr>
        <td id="i_first"><b>Becherovka</b></td>
        <td id="i_third">1,0</td>
        <td id="i_third">250-00</td>
        <td id="i_third">25-00</td>
        <td id="i_third">12-50</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><i>Gin</i><br></td></tr>
    <tr>
        <td id="i_first"><b>BEEFEATER</b></td>
        <td id="i_third">1,0</td>
        <td id="i_third">400-00</td>
        <td id="i_third">40-00</td>
        <td id="i_third">20-00</td>
    </tr>
     <tr><td colspan="3" id="i_up" style="font-size:16px;"><i>Rum</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Bacardi black</b></td>
        <td id="i_third">1,0</td>
        <td id="i_third">400-00</td>
        <td id="i_third">40-00</td>
        <td id="i_third">20-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Bacardi Blanka</b></td>
        <td id="i_third">1,0</td>
        <td id="i_third">400-00</td>
        <td id="i_third">40-00</td>
        <td id="i_third">20-00</td>
    </tr>
     <tr><td colspan="3" id="i_up" style="font-size:16px;"><i>Whisky</i><br></td></tr>
    <tr>
        <td id="i_first"><b>J.WALKER.BLACK</b></td>
        <td id="i_third">1,0</td>
        <td id="i_third">700-00</td>
        <td id="i_third">70-00</td>
        <td id="i_third">35-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>J.WALKER.RED</b></td>
        <td id="i_third">1,0</td>
        <td id="i_third">350-00</td>
        <td id="i_third">35-00</td>
        <td id="i_third">17-50</td>
    </tr>
     <tr>
        <td id="i_first"><b>Hankey Bannister</b></td>
        <td id="i_third">1,0</td>
        <td id="i_third">300-00</td>
        <td id="i_third">30-00</td>
        <td id="i_third">15-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><i>Cognac</i><br></td></tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>France</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Hennessy XO</b></td>
        <td id="i_third">0,7</td>
        <td id="i_third">2100-00</td>
        <td id="i_third">300-00</td>
        <td id="i_third">150-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Hennessy VS</b></td>
        <td id="i_third">0,7</td>
        <td id="i_third">770-00</td>
        <td id="i_third">110-00</td>
        <td id="i_third">55-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>Armenia</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Ararat 5* </b></td>
        <td id="i_third">0,5</td>
        <td id="i_third">210-00</td>
        <td id="i_third">42-00</td>
        <td id="i_third">21-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Ararat 3* </b></td>
        <td id="i_third">0,5</td>
        <td id="i_third">180-00</td>
        <td id="i_third">36-00</td>
        <td id="i_third">18-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i> Ukraine </i><br></td></tr>
    <tr>
        <td id="i_first"><b>Askania ХО</b></td>
        <td id="i_third">0,7</td>
        <td id="i_third">364-00</td>
        <td id="i_third">52-00</td>
        <td id="i_third">26-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Georgievskiy Kavaler</b></td>
        <td id="i_third">0,7</td>
        <td id="i_third">273-00</td>
        <td id="i_third">39-00</td>
        <td id="i_third">19-50</td>
    </tr>
     <tr>
        <td id="i_first"><b>Alex Platinum</b></td>
        <td id="i_third">0,5</td>
        <td id="i_third">300-00</td>
        <td id="i_third">60-00</td>
        <td id="i_third">30-00</td>
    </tr>
      <tr>
        <td id="i_first"><b>Alex Gold</b></td>
        <td id="i_third">0,5</td>
        <td id="i_third">225-00</td>
        <td id="i_third">45-00</td>
        <td id="i_third">22-50</td>
    </tr>
       <tr>
        <td id="i_first"><b>Alex Silver</b></td>
        <td id="i_third">0,5</td>
        <td id="i_third">180-00</td>
        <td id="i_third">36-00</td>
        <td id="i_third">18-00</td>
    </tr>
        <tr>
        <td id="i_first"><b>Klinkov VS</b></td>
        <td id="i_third">0,5</td>
        <td id="i_third">185-00</td>
        <td id="i_third">37-00</td>
        <td id="i_third">18-50</td>
    </tr>
         <tr>
        <td id="i_first"><b>Shustov ECTE V,S,O,P</b></td>
        <td id="i_third">0,5</td>
        <td id="i_third">220-00</td>
        <td id="i_third">44-00</td>
        <td id="i_third">22-00</td>
    </tr>
          <tr>
        <td id="i_first"><b>Shustov ECTE V,V,S,O,P</b></td>
        <td id="i_third">0,5</td>
        <td id="i_third">260-00</td>
        <td id="i_third">52-00</td>
        <td id="i_third">26-00</td>
    </tr>
           <tr>
        <td id="i_first"><b>Shustov ECTE X,O,</b></td>
        <td id="i_third">0,5</td>
        <td id="i_third">330-00</td>
        <td id="i_third">66-00</td>
        <td id="i_third">33-00</td>
    </tr>
            <tr>
        <td id="i_first"><b>Kahovka VS /3 years/</b></td>
        <td id="i_third">0,5</td>
        <td id="i_third">70-00</td>
        <td id="i_third">14-00</td>
        <td id="i_third">7-00</td>
    </tr>
             <tr>
        <td id="i_first"><b>Borisfen /4 years/</b></td>
        <td id="i_third">0,5</td>
        <td id="i_third">80-00</td>
        <td id="i_third">16-00</td>
        <td id="i_third">8-00</td>
    </tr>
              <tr>
        <td id="i_first"><b>Shustov 5*</b></td>
        <td id="i_third">0,5</td>
        <td id="i_third">110-00</td>
        <td id="i_third">22-00</td>
        <td id="i_third">11-00</td>
    </tr>
               <tr>
        <td id="i_first"><b>Shustov 4*</b></td>
        <td id="i_third">0,5</td>
        <td id="i_third">90-00</td>
        <td id="i_third">18-00</td>
        <td id="i_third">9-00</td>
    </tr>
                <tr>
        <td id="i_first"><b>Shustov 3*</b></td>
        <td id="i_third">0,5</td>
        <td id="i_third">80-00</td>
        <td id="i_third">16-00</td>
        <td id="i_third">8-00</td>
    </tr>
                 <tr>
        <td id="i_first"><b>Desna 4*</b></td>
        <td id="i_third">0,5</td>
        <td id="i_third">80-00</td>
        <td id="i_third">16-00</td>
        <td id="i_third">8-00</td>
    </tr>
                  <tr>
        <td id="i_first"><b>Odesskyi 3*</b></td>
        <td id="i_third">0,5</td>
        <td id="i_third">70-00</td>
        <td id="i_third">14-00</td>
        <td id="i_third">7-00</td>
    </tr>
                   <tr>
        <td id="i_first"><b>BUCHACH 5*</b></td>
        <td id="i_third">0,61</td>
        <td id="i_third">122-00</td>
        <td id="i_third">20-00</td>
        <td id="i_third">10-00</td>
    </tr>
         <tr>
        <td id="i_first"><b>Greenwich 5*</b></td>
        <td id="i_third">0,5</td>
        <td id="i_third">90-00</td>
        <td id="i_third">18-00</td>
        <td id="i_third">9-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Greenwich 4*</b></td>
        <td id="i_third">0,5</td>
        <td id="i_third">80-00</td>
        <td id="i_third">16-00</td>
        <td id="i_third">8-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><i>Liqueur</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Sambuca</b></td>
        <td id="i_third">1,0</td>
        <td id="i_third">400-00</td>
        <td id="i_third">40-00</td>
        <td id="i_third">20-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Baileys</b></td>
        <td id="i_third">1,0</td>
        <td id="i_third">400-00</td>
        <td id="i_third">40-00</td>
        <td id="i_third">20-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Cointreau</b></td>
        <td id="i_third">1,0</td>
        <td id="i_third">400-00</td>
        <td id="i_third">40-00</td>
        <td id="i_third">20-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Malibu</b></td>
        <td id="i_third">1,0</td>
        <td id="i_third">400-00</td>
        <td id="i_third">40-00</td>
        <td id="i_third">20-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Kahlua</b></td>
        <td id="i_third">1,0</td>
        <td id="i_third">400-00</td>
        <td id="i_third">40-00</td>
        <td id="i_third">20-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>De Kuyper</b> /Crème de Menthe/Blue Curaçao/Melon/Peach Tree/green banana/</td>
        <td id="i_third">0,7</td>
        <td id="i_third">280-00</td>
        <td id="i_third">40-00</td>
        <td id="i_third">20-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><i>Champagne</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Crimea</b> /White semi-sec/</td>
        <td id="i_third">0,75</td>
        <td id="i_third">80-00</td>
        <td id="i_third"></td>
        <td id="i_third"></td>
    </tr>
    <tr>
        <td id="i_first"><b>Crimea</b> /Red medium-sweet/</td>
        <td id="i_third">0,75</td>
        <td id="i_third">90-00</td>
        <td id="i_third"></td>
        <td id="i_third"></td>
    </tr>
    <tr>
        <td id="i_first"><b>Artemovskoe</b> /white medium-sweet/</td>
        <td id="i_third">0,75</td>
        <td id="i_third">70-00</td>
        <td id="i_third"></td>
        <td id="i_third"></td>
    </tr>
    <tr>
        <td id="i_first"><b>For lovers</b> /white medium-sweet/</td>
        <td id="i_third">0,75</td>
        <td id="i_third">50-00</td>
        <td id="i_third"></td>
        <td id="i_third"></td>
    </tr>
    <tr>
        <td id="i_first"><b>Oreanda</b> red Semi Sweet</td>
        <td id="i_third">0,75</td>
        <td id="i_third">60-00</td>
        <td id="i_third"></td>
        <td id="i_third"></td>
    </tr>
    <tr>
        <td id="i_first"><b>Oreanda</b> white Semi Sweet</td>
        <td id="i_third">0,75</td>
        <td id="i_third">55-00</td>
        <td id="i_third"></td>
        <td id="i_third"></td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><i>Vermouth</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Campari</b></td>
        <td id="i_third">1,0</td>
        <td id="i_third">320-00</td>
        <td id="i_third">32-00</td>
        <td id="i_third">16-00</td>
    </tr>
    <tr>
        <td id="i_first"><b> Extra dry martini</b></td>
        <td id="i_third">1,0</td>
        <td id="i_third">200-00</td>
        <td id="i_third">20-00</td>
        <td id="i_third">10-00</td>
    </tr>
    <tr>
        <td id="i_first"><b> Martini Rosso</b></td>
        <td id="i_third">1,0</td>
        <td id="i_third">200-00</td>
        <td id="i_third">20-00</td>
        <td id="i_third">10-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Martini Bianco</b></td>
        <td id="i_third">1,0</td>
        <td id="i_third">200-00</td>
        <td id="i_third">20-00</td>
        <td id="i_third">10-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><i>Wine</i><br></td></tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i> Crimea mark wine /Ukraine/</i><br></td></tr>
     <tr>
        <td id="i_first"><b>Cabernet</b> /Oreanda reserve/red/dry/</td>
        <td id="i_third">0,75</td>
        <td id="i_third">95-00</td>
        <td id="i_third"></td>
        <td id="i_third"></td>
    </tr>
     <tr>
        <td id="i_first"><b>Chardonnay</b> /Oreanda reserve/white dry/</td>
        <td id="i_third">0,75</td>
        <td id="i_third">90-00</td>
        <td id="i_third"></td>
        <td id="i_third"></td>
    </tr>
     <tr>
        <td id="i_first"><b>Crimea red</b> /semi-sweet red/</td>
        <td id="i_third">0,75</td>
        <td id="i_third">60-00</td>
        <td id="i_third">8-00</td>
        <td id="i_third">4-00</td>
    </tr>
    <tr>
        <td id="i_first"><b> Feodosiya Merlot</b> / red demi-sec mark wine/</td>
        <td id="i_third">0,75</td>
        <td id="i_third">60-00</td>
        <td id="i_third">8-00</td>
        <td id="i_third">4-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Chardonnay</b> semi-sweet white, mark/</td>
        <td id="i_third">0,75</td>
        <td id="i_third">60-00</td>
        <td id="i_third">8-00</td>
        <td id="i_third">4-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>"Inkerman"/Ukraine/</i><br></td></tr>
     <tr>
        <td id="i_first"><b>Pearl of Inkerman</b> white/dry</td>
        <td id="i_third">0,75</td>
        <td id="i_third">60-00</td>
        <td id="i_third"></td>
        <td id="i_third"></td>
    </tr>
      <tr>
        <td id="i_first"><b>Chersonese's Ruby</b> red/ dry</td>
        <td id="i_third">0,75</td>
        <td id="i_third">60-00</td>
        <td id="i_third"></td>
        <td id="i_third"></td>
    </tr>
       <tr>
        <td id="i_first"><b>Inkerman</b> red/demi-sec</td>
        <td id="i_third">0,75</td>
        <td id="i_third">60-00</td>
        <td id="i_third"></td>
        <td id="i_third"></td>
    </tr>
        <tr>
        <td id="i_first"><b>Inkerman</b> white/ demi-sec</td>
        <td id="i_third">0,75</td>
        <td id="i_third">60-00</td>
        <td id="i_third"></td>
        <td id="i_third"></td>
    </tr>
         <tr>
        <td id="i_first"><b>Inkerman legend</b> white/semi-sweet</td>
        <td id="i_third">0,75</td>
        <td id="i_third">60-00</td>
        <td id="i_third"></td>
        <td id="i_third"></td>
    </tr>
          <tr>
        <td id="i_first"><b>Pinot Noir</b> red/semi-sweet</td>
        <td id="i_third">0,75</td>
        <td id="i_third">60-00</td>
        <td id="i_third"></td>
        <td id="i_third"></td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>Golitsin wines/Ukraine/</i><br></td></tr>
     <tr>
        <td id="i_first"><b>Bastardo Jubilee </b> red/ dessert</td>
        <td id="i_third">0,75</td>
        <td id="i_third">46-00</td>
        <td id="i_third"></td>
        <td id="i_third"></td>
    </tr>
      <tr>
        <td id="i_first"><b>Cabernet </b> red/dry</td>
        <td id="i_third">0,75</td>
        <td id="i_third">43-00</td>
        <td id="i_third"></td>
        <td id="i_third"></td>
    </tr>
       <tr>
        <td id="i_first"><b>Muscat Tavricheskiy</b> white/dessert</td>
        <td id="i_third">0,75</td>
        <td id="i_third">46-00</td>
        <td id="i_third"></td>
        <td id="i_third"></td>
    </tr>
        <tr>
        <td id="i_first"><b>Pinot-Franc</b> red/ semi-sweet</td>
        <td id="i_third">0,75</td>
        <td id="i_third">41-00</td>
        <td id="i_third"></td>
        <td id="i_third"></td>
    </tr>
         <tr>
        <td id="i_first"><b>Sauvignon</b> white/dry</td>
        <td id="i_third">0,75</td>
        <td id="i_third">35-00</td>
        <td id="i_third"></td>
        <td id="i_third"></td>
    </tr>
          <tr>
        <td id="i_first"><b>Chardonnay</b> white/semi-sweet</td>
        <td id="i_third">0,75</td>
        <td id="i_third">39-00</td>
        <td id="i_third"></td>
        <td id="i_third"></td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>"Kartuli  Vazi"/Georgia/</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Alazanskaya dolina</b> semi-sweet white</td>
        <td id="i_third">0,75</td>
        <td id="i_third">120-00</td>
        <td id="i_third">16-00</td>
        <td id="i_third">8-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Alazanskaya dolina</b> semi-sweet red</td>
        <td id="i_third">0,75</td>
        <td id="i_third">135-00</td>
        <td id="i_third">18-00</td>
        <td id="i_third">9-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Kindzmarauli</b> red/semi-sweet</td>
        <td id="i_third">0,75</td>
        <td id="i_third">300-00</td>
        <td id="i_third">40-00</td>
        <td id="i_third">20-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Merani</b> white/semi-sec</td>
        <td id="i_third">0,75</td>
       <td id="i_third">135-00</td>
        <td id="i_third">18-00</td>
        <td id="i_third">9-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Pirosmani </b> demi-sec red</td>
        <td id="i_third">0,75</td>
        <td id="i_third">135-00</td>
        <td id="i_third">18-00</td>
        <td id="i_third">9-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Saperavi</b> red dry</td>
        <td id="i_third">0,75</td>
        <td id="i_third">120-00</td>
        <td id="i_third">16-00</td>
        <td id="i_third">8-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Tvishi</b> white/semi-sweet</td>
        <td id="i_third">0,75</td>
        <td id="i_third">195-00</td>
        <td id="i_third">26-00</td>
        <td id="i_third">13-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Khvanchkara</b> red/ semi-sweet</td>
        <td id="i_third">0,75</td>
        <td id="i_third">322-50</td>
        <td id="i_third">43-00</td>
        <td id="i_third">21-50</td>
    </tr>
    <tr>
        <td id="i_first"><b>Tsinandali</b> white/dry</td>
        <td id="i_third">0,75</td>
        <td id="i_third">120-00</td>
        <td id="i_third">16-00</td>
        <td id="i_third">8-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>Lozano /Spain/</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Lozano</b> red/dry</td>
        <td id="i_third">0,75</td>
        <td id="i_third">75-00</td>
        <td id="i_third">10-00</td>
        <td id="i_third">5-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Caballeros de la Rossa</b></td>
        <td id="i_third">0,75</td>
        <td id="i_third">75-00</td>
        <td id="i_third">10-00</td>
        <td id="i_third">5-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Blanco</b> white/semi-sweet</td>
        <td id="i_third">0,75</td>
        <td id="i_third">75-00</td>
        <td id="i_third">10-00</td>
        <td id="i_third">5-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><br><br><br><i>Cocktails</i><br><br><br></td></tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><i>short drinks</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Steak House</b><font style="font-size:14px;"><br>Baileys, Cointreau,De Kuyper Blue Curacao, De Kuyper Mentol</font></td>
        <td id="i_second" colspan="2">110</td>
        <td id="i_second" colspan="2">47-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>В-52</b><font style="font-size:14px;"><br>Kaluha, Baileys, Cointreau</font></td>
        <td id="i_second" colspan="2">60</td>
        <td id="i_second" colspan="2">26-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Hiroshima</b><font style="font-size:14px;"><br>sambuca, Baileys, absinth, Grenadine</font></td>
        <td id="i_second" colspan="2">50</td>
        <td id="i_second" colspan="2">23-50</td>
    </tr>
    <tr>
        <td id="i_first"><b>Vasya</b><font style="font-size:14px;"><br>Grenadine, lime,vodka</font></td>
        <td id="i_second" colspan="2">60</td>
        <td id="i_second" colspan="2">12-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>death on the 3d floor</b><font style="font-size:14px;"><br>sambuca, absinth, Grenadine, lemon fresh</font></td>
        <td id="i_second" colspan="2">65</td>
        <td id="i_second" colspan="2">26-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Green Mexican</b><font style="font-size:14px;"><br> liquer, lemon juice, Tequila</font></td>
        <td id="i_second" colspan="2">60</td>
        <td id="i_second" colspan="2">23-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Lamborghini</b><font style="font-size:14px;"><br>absinth, Grenadine,Baileys, De Kuyper,Cointreau,Tequila,cream</font></td>
        <td id="i_second" colspan="2">100</td>
        <td id="i_second" colspan="2">31-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Comatose state</b><font style="font-size:14px;"><br>Gin «Beefeater», absinth, sambuca, Cointreau</font></td>
        <td id="i_second" colspan="2">80</td>
        <td id="i_second" colspan="2">37-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>basketball</b><font style="font-size:14px;"><br>cognac, Cointreau</font></td>
        <td id="i_second" colspan="2">50</td>
        <td id="i_second" colspan="2">25-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><i>long drinks</i><br></td></tr>
     <tr>
        <td id="i_first"><b>Long island</b><font style="font-size:14px;"><br>rum, tequila, gin, vodka, Cointreau, lemon juice, cola</font></td>
        <td id="i_second" colspan="2">230</td>
        <td id="i_second" colspan="2">30-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Melon ball</b><font style="font-size:14px;"><br>vodka,  De Kuyper melon, orange juice, cherry, orange</font></td>
        <td id="i_second" colspan="2">230</td>
        <td id="i_second" colspan="2">24-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Cocoon</b><font style="font-size:14px;"><br>Sambuca, lemon fresh, cola</font></td>
        <td id="i_second" colspan="2">220</td>
        <td id="i_second" colspan="2">28-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>PINA COLADA</b><font style="font-size:14px;"><br>Rum, malibu,cream, pineapple juice,cherry</font></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">35-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Sex on the Beach</b><font style="font-size:14px;"><br>vodka, peach liqueur, orange juice, and cranberry juice.</font></td>
        <td id="i_second" colspan="2">260</td>
        <td id="i_second" colspan="2">31-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Blue Lagoon</b><font style="font-size:14px;"><br>Sprite, Curacao Blue, Malibu, vodka, orange</font></td>
        <td id="i_second" colspan="2">180</td>
        <td id="i_second" colspan="2">30-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Caribbean miracle</b><font style="font-size:14px;"><br>De Kuyper melon liqueur, pineapple juice, Baccardi rum</font></td>
        <td id="i_second" colspan="2">135</td>
        <td id="i_second" colspan="2">18-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Mojito</b><font style="font-size:14px;"><br>Rum Bacardi Blanca,Sprite, lime, mint, liqueur</font></td>
        <td id="i_second" colspan="2">400</td>
        <td id="i_second" colspan="2">36-00</td>
    </tr>
     <tr><td colspan="3" id="i_up" style="font-size:16px;"><i>hot drinks</i><br></td></tr>
     <tr>
        <td id="i_first"><b>Red Glintwein </b><font style="font-size:14px;"><br> Shardone red wine, cognac, orange, lemon, cinnamon)</font></td>
        <td id="i_second" colspan="2">230</td>
        <td id="i_second" colspan="2">28-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>White Glintwein</b><font style="font-size:14px;"><br>Shardone white wine, cognac, orange, lemon, cinnamon)</font></td>
        <td id="i_second" colspan="2">230</td>
        <td id="i_second" colspan="2">28-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Apple grog</b><font style="font-size:14px;"><br>rum, apple juice, cinammon, cloves, lemon, orange, apple</font></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">25-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Baileys coffee</b><font style="font-size:14px;"><br>hot coffee with Baileys </font></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">18-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Kahlua coffee</b><font style="font-size:14px;"><br>hot coffee with  Kahlua liqueur and cream</font></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">18-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Whisky coffee</b><font style="font-size:14px;"><br>hot coffee with whisky and cream</font></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">18-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Alexander coffee</b><font style="font-size:14px;"><br>hot coffee with cognac, rum and cream</font></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">18-00</td>
    </tr>
     <tr><td colspan="3" id="i_up" style="font-size:16px;"><br><br><br><i>Chocolate</i><br><br><br></td></tr>
     <tr>
        <td id="i_first"><b>“Raffaello” sweets</b></td>
        <td id="i_second" colspan="2">1 шт.</td>
        <td id="i_second" colspan="2">3-00</td>
    </tr>
     <tr>
        <td id="i_first"><b> "Korona"chocolate </b></td>
        <td id="i_second" colspan="2">100</td>
        <td id="i_second" colspan="2">15-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Honey</b></td>
        <td id="i_second" colspan="2">50</td>
        <td id="i_second" colspan="2">5-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Grenadine syrup</b></td>
        <td id="i_second" colspan="2">100</td>
        <td id="i_second" colspan="2">15-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Lime syrup</b></td>
        <td id="i_second" colspan="2">100</td>
        <td id="i_second" colspan="2">15-00</td>
    </tr>
     <tr><td colspan="3" id="i_up" style="font-size:16px;"><br><br><br><i>Tea in assortment</i><br><br><br></td></tr>
     <tr>
        
    </tr>
     <tr><td colspan="3" id="i_up" style="font-size:16px;"><br><br><br><i>Coffee in assortment </i><br><br><br></td></tr>
    <tr>
        
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><br><br><br><i>mineral water and drinks in assortment</i><br><br><br></td></tr>
    <tr>
        
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><br><br><br><i>non-alcoholic cocktails</i><br><br><br></td></tr>
    <tr>
        <td id="i_first"><b>Cat's Paws</b><font style="font-size:14px;"><br>(orange,grapefruit,pineapple juices,grenadine)</font></td>
        <td id="i_second" colspan="2">170</td>
        <td id="i_second" colspan="2">7-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Ice-cream</b><font style="font-size:14px;"><br>(juice, ice-cream)</font></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">8-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Milk shake</b><font style="font-size:14px;"><br>(milk,ice-cream,cream, grenadine)</font></td>
        <td id="i_second" colspan="2">320</td>
        <td id="i_second" colspan="2">16-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Milk shake with juice</b><font style="font-size:14px;"><br>(ice-cream, milk,juice)</font></td>
        <td id="i_second" colspan="2">320</td>
        <td id="i_second" colspan="2">16-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Mojito  б/а</b><font style="font-size:14px;"><br>(Sprite,syrup,mint,lime,ice)</font></td>
        <td id="i_second" colspan="2">400</td>
        <td id="i_second" colspan="2">25-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><br><br><br><i>Beer appetizer</i><br><br><br></td></tr>
    <tr>
        <td id="i_first"><b>dried calamaries ,Dried squid rings </b></td>
        <td id="i_second" colspan="2">40</td>
        <td id="i_second" colspan="2">12-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Dried fish</b></td>
        <td id="i_second" colspan="2">40</td>
        <td id="i_second" colspan="2">14-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Chips</b></td>
        <td id="i_second" colspan="2">25</td>
        <td id="i_second" colspan="2">5-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Pistachios</b></td>
        <td id="i_second" colspan="2">80</td>
        <td id="i_second" colspan="2">23-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Peanuts</b></td>
        <td id="i_second" colspan="2">125</td>
        <td id="i_second" colspan="2">18-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Cruts</b></td>
        <td id="i_second" colspan="2">40</td>
        <td id="i_second" colspan="2">4-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><br><br><br><i>Beer</i><br><br><br></td></tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><i>Draft Keg beer:</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Chernigovskoye light</b></td>
        <td id="i_second" colspan="2">0,5</td>
        <td id="i_second" colspan="2">8-00</td>
    </tr>
    <tr>
        <td id="i_first"><b></b></td>
        <td id="i_second" colspan="2">0,33</td>
        <td id="i_second" colspan="2">5-28</td>
    </tr>
    <tr>
        <td id="i_first"><b>Chernigovskoye White</b></td>
        <td id="i_second" colspan="2">0,5</td>
        <td id="i_second" colspan="2">9-00</td>
    </tr>
    <tr>
        <td id="i_first"><b></b></td>
        <td id="i_second" colspan="2">0,33</td>
        <td id="i_second" colspan="2">5-94</td>
    </tr>
     <tr>
        <td id="i_first"><b>Staropramen</b></td>
        <td id="i_second" colspan="2">0,5</td>
        <td id="i_second" colspan="2">11-00</td>
    </tr>
    <tr>
        <td id="i_first"><b></b></td>
        <td id="i_second" colspan="2">0,33</td>
        <td id="i_second" colspan="2">7-26</td>
    </tr>
     <tr>
        <td id="i_first"><b>Stella Artois</b></td>
        <td id="i_second" colspan="2">0,5</td>
        <td id="i_second" colspan="2">12-00</td>
    </tr>
    <tr>
        <td id="i_first"><b></b></td>
        <td id="i_second" colspan="2">0,33</td>
        <td id="i_second" colspan="2">7-92</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><i>Bottle Beer:</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Löwenbräu</b><font style="font-size:14px;"><br>Light</font></td>
        <td id="i_second" colspan="2">0,33</td>
        <td id="i_second" colspan="2">17-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Hoegaarden</b><font style="font-size:14px;"><br>non-filtered </font></td>
        <td id="i_second" colspan="2">0,33</td>
        <td id="i_second" colspan="2">17-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Leffe</b><font style="font-size:14px;"><br>light,dark</font></td>
        <td id="i_second" colspan="2">0,33</td>
        <td id="i_second" colspan="2">17-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><i>Non-alcoholic Beer:</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Stella Artois N/А</b></td>
        <td id="i_second" colspan="2">0,5</td>
        <td id="i_second" colspan="2">12-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><br><br><br><i>Low-alcohol beverages</i><br><br><br></td></tr>    
    <tr>
        <td id="i_first"><b>Extreme</b></td>
        <td id="i_second" colspan="2">0,5</td>
        <td id="i_second" colspan="2">15-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Go</b></td>
        <td id="i_second" colspan="2">0,5</td>
        <td id="i_second" colspan="2">15-00</td>
    </tr>
</table>
</div>
</div>
<?php
}
else
   if ($_GET['pm'] == 3)
   {
?>

   <div class="catalogue_item_cont_m"> 
<img src="root/st_h/up.png" alt="" style="width: 100%;" />
<div id="div_st" style="height:550px;">
<p>
<div id="mm_menu" style="top:-205px;"><a href="index.php?business_full=396&amp;pm=1"  class="menu_text"><b>MAIN</b></a></div>
<div id="mm_menu" style="top:-190px;"><a href="index.php?business_full=396&amp;pm=2" class="menu_text">MENU</a></div>
<div id="mm_menu" style="top:-175px;"><a href="index.php?business_full=396&amp;pm=3" class="menu_text">CONTACTS</a></div>
</p>
<br>

        <script src="http://api-maps.yandex.ru/1.1/index.xml?key=AAmDzUsBAAAARkVWCAIAXzMCgKN58_MQUqB134Sdp-unCH0AAAAAAAAAAACbJlz2mcKc4anRgbxx6LBZ5BHPyg==" type="text/javascript"></script>
    <script type="text/javascript">
        window.onload = function () {
            var map = new YMaps.Map(document.getElementById("YMapsID"));
            map.setCenter(new YMaps.GeoPoint(37.80947,48.006209), 14);

            var content = document.createElement('span');
            content.innerHTML = "«Steak House»";
            map.openBalloon(new YMaps.GeoPoint(37.80947,48.006209), content);

            map.addControl(new YMaps.ToolBar());
            map.addControl(new YMaps.Zoom());
            map.addControl(new YMaps.MiniMap());
            map.addControl(new YMaps.ScaleLine());
        }
    </script>


	 <div id="YMapsID" style="width:100%;height:450px"></div>
   </div>
</div>
<?php
   } 
?>



<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="index.php?section_id=456&amp;business=1">Category:</a></div>
</div>
<div class="catalogue_item_cont">
<a href="index.php?section_id=456&amp;business=1">Business</a>
 / 
<a href="index.php?section_id=616&amp;business=1">Enterprises</a>
 / 
<a href="index.php?section_id=619&amp;business=2">Recreation facilities</a>
 / 
<a href="index.php?section_id=622&amp;business=2">Restaurants, cafes, pubs</a>
</div>


<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="">Gallery:</a></div>
</div>
<div class="catalogue_item_cont">
<div class="catalogue_pic_l"><a href="root/st_h/gallery/1.jpg" target="_blank"><img src="root/st_h/gallery/1_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/st_h/gallery/2.jpg" target="_blank"><img src="root/st_h/gallery/2_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/st_h/gallery/3.jpg" target="_blank"><img src="root/st_h/gallery/3_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/st_h/gallery/4.jpg" target="_blank"><img src="root/st_h/gallery/4_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/st_h/gallery/5.jpg" target="_blank"><img src="root/st_h/gallery/5_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/st_h/gallery/6.jpg" target="_blank"><img src="root/st_h/gallery/6_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/st_h/gallery/7.jpg" target="_blank"><img src="root/st_h/gallery/7_s.jpg" width="60" height="60" border="0" alt=""></a></div>
</div>
<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="">Contacts:</a></div>
</div>
 <div class="catalogue_item_cont">
 		 <table width="100%">
			<tbody>
 			<tr>
			<!--	<td><img class="main_sec_image" src="" width="60" height="60" border="0" alt="" /></td>-->
				<td>Adress:</td>
				<td>Telephone:</td>
				<td>Fax:</td>
				<td>E-mail:</td>
				<td>Website:</td>
			</tr>
			<tr>
				<td>Donetsk city,<br> Teatralniy Avenue, 28</td>
				<td>(062)335-23-68</td>
				<td></td>
				<td></td>
				<td></td>

			</tr>
			</tbody> 
		 </table> 		
	 </div>
</div>  

