<div class="catalogue_item_c">

<style>



<!--

.folding{cursor:hand;font-weight:bold}

-->



.catalogue_item_cont p {

color:#000000;

text-align:justify;

text-indent:0px;

line-height:20px;

margin:0px;

}



.catalogue_item_cont_m {

background-color:#FFFFFF;

border:1px solid lightgray;

color:#000000;

margin:0;

margin:15px 10px 10px;

width:980px;

}



.catalogue_item_cont {

background-color:#ffffff;

border-top:1px solid lightgray;

margin:0 0 7px 10px;

width:980px;

color:#000000;

}

.catalogue_item_c {

background-color:#F3F3F3;

}



.catalogue_item_cont a {

color:#000000;

}



.catalogue_item_cont a:hover {

color:#000000;

text-decoration:underline;

}



.catalogue_item_mp_a {

left:3px;

position:relative;

}



#mm_menu {position:relative;left:610px;width:225px;text-align:center;} 



#div_st {padding:0 0px;position:relative;height:955px;}



@media all and (-webkit-min-device-pixel-ratio:10000),

not all and (-webkit-min-device-pixel-ratio:0) {

 #div_st {height:955px;}

}

#div_st2 {padding:0 0px;position:relative;height:6750px;}



@media all and (-webkit-min-device-pixel-ratio:10000),

not all and (-webkit-min-device-pixel-ratio:0) {

 #div_st2 {height:6750px;}

}

#div_st3 {padding:0 0px;position:relative;height:800px;}



@media all and (-webkit-min-device-pixel-ratio:10000),

not all and (-webkit-min-device-pixel-ratio:0) {

 #div_st3 {height:869px;}

}



div {

	display:block;

}



.sequ_container {

	width:100%;

	height:100%;

	margin:0px;

	padding:0px;

}



.background_div {

	width:980px;

	height:950px;

	background-image:url('../root/msite/coffee/background.png');

}



.logo {

	position:absolute;

	float:right;

	right:80px;

	top:70px;

	background-image:url('../root/msite/coffee/logo.png');

	background-repeat:no-repeat;

	width:335px;

	height:168px;

}



.girl {

	position:absolute;

	float:right;

	right:47px;

	top:685px;

	background-image:url('../root/msite/coffee/girl.png');

	width:363px;

	height:201px;

}



.text_r {

	position:relative;

	float:right;

	width:390px;

	right:45px;

	top:265px;

}



#p_adv {

	font-family:Adventure;

	font:Adventure;	

	font-size:10pt;

	font-weight:bold;

	letter-spacing:1px;

	text-align:right;

	color:#775e4b;

}



.cup {

	position:absolute;

	float:left;

	left:10px;

	top:10px;

	background-image:url('../root/msite/coffee/cup.png');

	width:285px;

	height:236px;

}



@font-face {

	font-family:Adventure;

	src:url(http://www.eurodonetsk.com/public_html/root/msite/coffee/adventure_font.ttf);

}



.sil {

	position:relative;

	float:left;

	width:250px;

	left:30px;

	top:400px;

	font-family:Adventure;

	src:url(http://www.eurodonetsk.com/public_html/root/msite/coffee/adventure_font.ttf);

	font:Adventure;	

	font-size:16pt;

	font-weight:bold;

	font-style:bold;

	letter-spacing:1px;

	color:#775e4b;

}



.mid_pho {

	position:absolute;

	float:left;

	left:285px;

	top:120px;

	background-image:url('../root/msite/coffee/mid_pho.png');

	width:276px;

	height:760px;

}



.girl2 {

	position:absolute;

	float:right;

	right:50px;

	top:6485px;

	background-image:url('../root/msite/coffee/girl.png');

	width:363px;

	height:201px;

}



.background_div2 {

	position:relative;

	float:left;

	display:block;

	width:980px;

	height:6750px;

	background-image:url('../root/msite/coffee/menu_bg.png');

}



.menu {

	position:relative;

	float:right;

	width:540px;

	right:45px;

	top:265px;

	font-family:Adventure;

	src:url(http://www.eurodonetsk.com/public_html/root/msite/coffee/adventure_font.ttf);

	font:Adventure;	

	font-size:16pt;

	font-weight:bold;

	font-style:bold;

	letter-spacing:1px;

	color:#775e4b;

}



.tab {

	font-size:12pt;

	text-align:left;

}



.menu_2 {

	position:relative;

	float:right;

	width:594px;

	right:45px;

	top:265px;

	font-family:Adventure;

	src:url(http://www.eurodonetsk.com/public_html/root/msite/coffee/adventure_font.ttf);

	font:Adventure;	

	font-size:16pt;

	font-weight:bold;

	font-style:bold;

	letter-spacing:1px;

	color:#775e4b;

}

.style_text_menu1 {
	color: #140a00;
	font-weight: bold;
}
.style_text_main {
	font-family: "Times New Roman", Times, serif;
	font-size: 16px;
	color: #B16A2C;
}


.R1 {
	width: 700px;
	height: 480px;
	float:right;
	padding-right: 35px;
}

.R2 {
	width: 700px;
	height: 460px;
	float:right;
	padding-right: 35px;
	padding-top: 45px;
}

a:link {
	color: #1F0601;
}
a:visited {
	color: #0F0400;
}

</style>

<?php

if ($_GET['pm'] == 1) 

{

?>

<div class="catalogue_item_cont_m"> 

	<table width="990" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
    <td height="248" colspan="2" background="../root/msite/rekviem/up_eng.jpg">&nbsp;</td>
  </tr>
  <tr>
      <td height="31" colspan="2" background="../root/msite/rekviem/up2.jpg"><div align="center" class="style_text_menu1"><a href="http://www.eurodonetsk.com/index.php?business_full=481&pm=1">Services</a> | <a href="http://www.eurodonetsk.com/index.php?business_full=481&pm=2">Vip-services</a> | <a href="http://www.eurodonetsk.com/index.php?business_full=481&pm=3">Cargo 200</a> | <a href="http://www.eurodonetsk.com/index.php?business_full=481&pm=4">Grave care</a> | <a href="http://www.eurodonetsk.com/index.php?business_full=481&pm=5">Awards</a> | <a href="http://www.eurodonetsk.com/index.php?business_full=481&pm=6">Contacts</a></div></td>
  </tr>
  <tr>
     <td width="221"  height="510" background="../root/msite/rekviem/right.jpg" ><table width="200" align="right"  cellpadding="0" cellspacing="0" border="0">
      <tr>
        <td class="style_text_main"><p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
		  <p align="center">&nbsp;</p>
		  <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
		  <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
		  <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
          <p align="center" class="стиль2">+38(062) 382-63-01<br />
            +38(062) 333-50-80<br />
            +38(062) 330-50-02<br />
            +38(050) 328-19-10</p></td>
      </tr>
    </table>
      <p class="style_text_main">&nbsp;</p>
    </td>
    <td width="769" background="../root/msite/rekviem/main.jpg">
      <p align="center"  class="style_text_main"></p>
      <div class="R2">
        <p align="center" class="style_text_main">&nbsp;</p>
        <p align="center" class="style_text_main">Evacuation and transportation of the dead person in  the Pathology Center;</p>
        <p align="center" class="style_text_main">Acceptance of the order and conclusion of contract for  funeral arrangements (burial or cremation);</p>
        <p align="center" class="style_text_main">VIP- service;</p>
        <p align="center" class="style_text_main">Arms design certificate of death;</p>
        <p align="center" class="style_text_main">Embalming services, sanitary and cosmetic treatment of  the dead;</p>
        <p align="center" class="style_text_main">Allocation of funeral halls for a civil funeral rites;</p>
        <p align="center" class="style_text_main">Manufacturing tombstone of natural stone;</p>
        <p align="center" class="style_text_main">Coffins of various modifications, wreaths and baskets  of artificial and natural flowers, mourning bands;</p>
        <p align="center" class="style_text_main">Complete set of transport services;</p>
        <p align="center" class="style_text_main">Organization of religious ceremony;</p>
        <p align="center" class="style_text_main">Execution of documents and transportation of  dead person to another city;</p>
      </div>   
      <p align="center" class="style_text_main">&nbsp;</p>
    </td>
  </tr>
</table>

</div> <!-- cat_ite_cont_m -->

<?php

}

else

   if ($_GET['pm'] == 2)

   {

?>

<div class="catalogue_item_cont_m"> 

	<table width="990" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
    <td height="248" colspan="2" background="../root/msite/rekviem/up_eng.jpg">&nbsp;</td>
  </tr>
  <tr>
      <td height="31" colspan="2" background="../root/msite/rekviem/up2.jpg"><div align="center" class="style_text_menu1"><a href="http://www.eurodonetsk.com/index.php?business_full=481&pm=1">Services</a> | <a href="http://www.eurodonetsk.com/index.php?business_full=481&pm=2">Vip-services</a> | <a href="http://www.eurodonetsk.com/index.php?business_full=481&pm=3">Cargo 200</a> | <a href="http://www.eurodonetsk.com/index.php?business_full=481&pm=4">Grave care</a> | <a href="http://www.eurodonetsk.com/index.php?business_full=481&pm=5">Awards</a> | <a href="http://www.eurodonetsk.com/index.php?business_full=481&pm=6">Contacts</a></div></td>
  </tr>
  <tr>
     <td width="221"  height="510" background="../root/msite/rekviem/right.jpg" ><table width="200" align="right"  cellpadding="0" cellspacing="0" border="0">
      <tr>
        <td class="style_text_main"><p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
		  <p align="center">&nbsp;</p>
		  <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
		  <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
		  <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
          <p align="center" class="стиль2">+38(062) 382-63-01<br />
            +38(062) 333-50-80<br />
            +38(062) 330-50-02<br />
            +38(050) 328-19-10</p></td>
      </tr>
    </table>
      <p class="style_text_main">&nbsp;</p>
    </td>
    <td width="769" background="../root/msite/rekviem/main.jpg">
      <p align="center"  class="style_text_main"></p>
      <div class="R2">
        <p align="center" class="style_text_main">&nbsp;</p>
        <p align="center" class="style_text_main"><strong>Funeral arrangements of VIP  level</strong> </p>
        <p align="center" class="style_text_main">Apart from traditional  funerals, we are ready to perform the ritual and to provide funeral services at  higher level. Full range of funeral services is implemented by funeral team  servicing. Our staff will arrange a visit to the cemetery and buried with the  lift device for lowering the coffin into the grave. The staff of ritual agency  will decorate graves with wreaths (of artificial or natural flowers), will make  wall hangings of graves etc.</p>
      </div>      
      <p align="center" class="style_text_main">&nbsp;</p>
    </td>
  </tr>
</table>

</div> <!-- cat_ite_cont_m -->

<?php

}

else

   if ($_GET['pm'] == 3)

   {

?>

<div class="catalogue_item_cont_m"> 

	<table width="990" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
    <td height="248" colspan="2" background="../root/msite/rekviem/up_eng.jpg">&nbsp;</td>
  </tr>
  <tr>
      <td height="31" colspan="2" background="../root/msite/rekviem/up2.jpg"><div align="center" class="style_text_menu1"><a href="http://www.eurodonetsk.com/index.php?business_full=481&pm=1">Services</a> | <a href="http://www.eurodonetsk.com/index.php?business_full=481&pm=2">Vip-services</a> | <a href="http://www.eurodonetsk.com/index.php?business_full=481&pm=3">Cargo 200</a> | <a href="http://www.eurodonetsk.com/index.php?business_full=481&pm=4">Grave care</a> | <a href="http://www.eurodonetsk.com/index.php?business_full=481&pm=5">Awards</a> | <a href="http://www.eurodonetsk.com/index.php?business_full=481&pm=6">Contacts</a></div></td>
  </tr>
  <tr>
     <td width="221"  height="510" background="../root/msite/rekviem/right.jpg" ><table width="200" align="right"  cellpadding="0" cellspacing="0" border="0">
      <tr>
        <td class="style_text_main"><p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
		  <p align="center">&nbsp;</p>
		  <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
		  <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
		  <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
          <p align="center" class="стиль2">+38(062) 382-63-01<br />
            +38(062) 333-50-80<br />
            +38(062) 330-50-02<br />
            +38(050) 328-19-10</p></td>
      </tr>
    </table>
      <p class="style_text_main">&nbsp;</p>
    </td>
    <td width="769" background="../root/msite/rekviem/main.jpg">
      <p align="center"  class="style_text_main"></p>
      <div class="R2">
        <p align="center" class="style_text_main"><strong>Transfer and Delivery of Departed Persone's body </strong><strong>&quot;Cargo 200&quot;</strong><br />
          One of the most important  direction of  service «Requiem» is dead  body repatriation. Our professionally trained ritual agents execute and prepare  all necessary documents to send the dead in another city or country. Solve all  the problems associated with transportation (by airlines, carriage by rail or  provide a comfortable ritual vehicle to transport the body of the deceased and  accompanying person to destination). Will supervise the loading and will draw  customs clearance (when crossing the state border cargo 200 ).<br />
          We are ready to receive cargo  200 round-the-clock from any part of Ukraine and near abroad.<br />
        We can afford zinc coffin of  any necessary form.</p>
        <p align="center" class="style_text_main"><strong>Our agents work all over Ukraine  and near abroad!</strong></p>
        <p align="center" class="style_text_main">The term “Cargo 200” in ritual  business means the corpse transportation from the place of death to the place  of burial in container. For better preservation of the corpse containers are  sealed hermetically. History of the term comes from Afghan companies when it  designated the transportation of dead soldiers to their homeland.  The term acclimatized and has migrated to our  life today. Why 200? It turns out that much about weighing the container with  the placed dead person. Transportation of a deceased person rather troublesome and  not a simple matter, which has its own specifics in each country.</p>
      </div>      
      <p align="center" class="style_text_main">&nbsp;</p>
    </td>
  </tr>
</table>

</div> <!-- cat_ite_cont_m -->

<?php

}

else

   if ($_GET['pm'] == 4)

   {

?>

<div class="catalogue_item_cont_m"> 

	<table width="990" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
    <td height="248" colspan="2" background="../root/msite/rekviem/up_eng.jpg">&nbsp;</td>
  </tr>
  <tr>
      <td height="31" colspan="2" background="../root/msite/rekviem/up2.jpg"><div align="center" class="style_text_menu1"><a href="http://www.eurodonetsk.com/index.php?business_full=481&pm=1">Services</a> | <a href="http://www.eurodonetsk.com/index.php?business_full=481&pm=2">Vip-services</a> | <a href="http://www.eurodonetsk.com/index.php?business_full=481&pm=3">Cargo 200</a> | <a href="http://www.eurodonetsk.com/index.php?business_full=481&pm=4">Grave care</a> | <a href="http://www.eurodonetsk.com/index.php?business_full=481&pm=5">Awards</a> | <a href="http://www.eurodonetsk.com/index.php?business_full=481&pm=6">Contacts</a></div></td>
  </tr>
  <tr>
     <td width="221"  height="510" background="../root/msite/rekviem/right.jpg" ><table width="200" align="right"  cellpadding="0" cellspacing="0" border="0">
      <tr>
        <td class="style_text_main"><p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
		  <p align="center">&nbsp;</p>
		  <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
		  <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
		  <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
          <p align="center" class="стиль2">+38(062) 382-63-01<br />
            +38(062) 333-50-80<br />
            +38(062) 330-50-02<br />
            +38(050) 328-19-10</p></td>
      </tr>
    </table>
      <p class="style_text_main">&nbsp;</p>
    </td>
    <td width="769" background="../root/msite/rekviem/main.jpg">
      <p align="center"  class="style_text_main"></p>
      <div class="R2">
         <p align="center" class="style_text_main">&nbsp;</p>
        <p align="center" class="style_text_main"><strong>Improvement</strong><br />
        <strong>(Grave  care)</strong></p>
        <p align="center" class="style_text_main">Care for a burial place and  improvement of territory.<br />
          In case you are very busy and  you don't have enough time or you are far from native land Ukraine... and you  fill fault as you have no opportunity to improve the graves of deceased  relatives: to renew tombstone, to make  preventive maintenance or just put flowers and light memorial candle. Our company will take on your  worries. Do you want to order a one-time cleaning or regular? Are monuments and  fences need cleaning and restoration? Do you need to reconstruct the  inscriptions on the tombstone, to manufacture or install a cross and sign?  Would you like to put rubble tiles and regularize the track and gate etc.Full range of services to care  for burial places of your relatives and intimates people in cemeteries of  Donetsk (Ukraine).</p>
        <p align="center" class="style_text_main">High quality at obtainable  price is guaranteed.</p>
        <p align="center" class="style_text_main">Graves care in the Donetsk  region by agreement.</p>
        <p align="center" class="style_text_main">Submits the photocount before  and after work.</p>
        <p align="center" class="style_text_main">Telephone number: +38(062)  382-63-01, +38 (062) 333-50-80, +38 (050) 328 19 10</p>
      </div>     
      <p align="center" class="style_text_main">&nbsp;</p>
    </td>
  </tr>
</table>


</div> <!-- cat_ite_cont_m -->

<?php

}

else

   if ($_GET['pm'] == 5)

   {

?>

<div class="catalogue_item_cont_m"> 

	<table width="990" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
    <td height="248" colspan="2" background="../root/msite/rekviem/up_eng.jpg">&nbsp;</td>
  </tr>
  <tr>
      <td height="31" colspan="2" background="../root/msite/rekviem/up2.jpg"><div align="center" class="style_text_menu1"><a href="http://www.eurodonetsk.com/index.php?business_full=481&pm=1">Services</a> | <a href="http://www.eurodonetsk.com/index.php?business_full=481&pm=2">Vip-services</a> | <a href="http://www.eurodonetsk.com/index.php?business_full=481&pm=3">Cargo 200</a> | <a href="http://www.eurodonetsk.com/index.php?business_full=481&pm=4">Grave care</a> | <a href="http://www.eurodonetsk.com/index.php?business_full=481&pm=5">Awards</a> | <a href="http://www.eurodonetsk.com/index.php?business_full=481&pm=6">Contacts</a></div></td>
  </tr>
  <tr>
    <td width="221"  height="510" background="../root/msite/rekviem/right.jpg" ><table width="200" align="right"  cellpadding="0" cellspacing="0" border="0">
      <tr>
        <td class="style_text_main"><p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
		  <p align="center">&nbsp;</p>
		  <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
		  <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
		  <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
          <p align="center" class="стиль2">+38(062) 382-63-01<br />
            +38(062) 333-50-80<br />
            +38(062) 330-50-02<br />
            +38(050) 328-19-10</p></td>
      </tr>
    </table>
      <p class="style_text_main">&nbsp;</p>
    </td>
    <td width="769" background="../root/msite/rekviem/main_nag.jpg">
      <p align="center"  class="style_text_main"></p>
      <div class="R2">
        <p align="center" class="style_text_main">&nbsp;</p>
      </div>      
    </td>
  </tr>
</table>


</div> <!-- cat_ite_cont_m -->

<?php

}

else

   if ($_GET['pm'] == 6)

   {

?>

<div class="catalogue_item_cont_m"> 

	<table width="990" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
    <td height="248" colspan="2" background="../root/msite/rekviem/up_eng.jpg">&nbsp;</td>
  </tr>
  <tr>
      <td height="31" colspan="2" background="../root/msite/rekviem/up2.jpg"><div align="center" class="style_text_menu1"><a href="http://www.eurodonetsk.com/index.php?business_full=481&pm=1">Services</a> | <a href="http://www.eurodonetsk.com/index.php?business_full=481&pm=2">Vip-services</a> | <a href="http://www.eurodonetsk.com/index.php?business_full=481&pm=3">Cargo 200</a> | <a href="http://www.eurodonetsk.com/index.php?business_full=481&pm=4">Grave care</a> | <a href="http://www.eurodonetsk.com/index.php?business_full=481&pm=5">Awards</a> | <a href="http://www.eurodonetsk.com/index.php?business_full=481&pm=6">Contacts</a></div></td>
  </tr>
  <tr>
    <td width="221"  height="510" background="../root/msite/rekviem/right.jpg" ><table width="200" align="right"  cellpadding="0" cellspacing="0" border="0">
      <tr>
        <td class="style_text_main"><p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
		  <p align="center">&nbsp;</p>
		  <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
		  <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
		  <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
          <p align="center">&nbsp;</p>
          <p align="center" class="стиль2">+38(062) 382-63-01<br />
            +38(062) 333-50-80<br />
            +38(062) 330-50-02<br />
            +38(050) 328-19-10</p></td>
      </tr>
    </table>
      <p class="style_text_main">&nbsp;</p>
    </td>
    <td width="769" background="../root/msite/rekviem/main.jpg">
      <p align="center"  class="style_text_main"></p>
      <div class="R2">
        <p align="center" class="style_text_main">&nbsp;</p>
        <p align="center" class="style_text_main">Contacts: Address:  Ukraine, 83086, Donetsk, Postysheva street, 21.<br />
          Telephone  number/fax: +38(062)-382-68-52.<br />
          Telephone  numbers of ritual agents:<br />
          +38(062) 382-63-01,  +38(062) 333-50-80, +38(062) 330-50-02,  +38(050) 328-19-10<br />
          E-mail: rekviem-donetsk@yandex.ru</a></p>
		<div id="div_st4">

						<script src="http://api-maps.yandex.ru/1.1/index.xml?key=AAmDzUsBAAAARkVWCAIAXzMCgKN58_MQUqB134Sdp-unCH0AAAAAAAAAAACbJlz2mcKc4anRgbxx6LBZ5BHPyg==" type="text/javascript"></script>

						<script type="text/javascript">

						window.onload = function () {

							var map = new YMaps.Map(document.getElementById("YMapsID"));

							map.setCenter(new YMaps.GeoPoint(37.80588,47.988885), 16);



							var content = document.createElement('span');

							content.innerHTML = "Funeral service «Requiem»";

							map.openBalloon(new YMaps.GeoPoint(37.80588,47.988885), content);



							map.addControl(new YMaps.ToolBar());

							map.addControl(new YMaps.Zoom());

							map.addControl(new YMaps.MiniMap());

							map.addControl(new YMaps.ScaleLine());

						}

    </script>





	 <div id="YMapsID" style="width:60%; height:300px; position:relative; float:centr; top:20px; left: 140px; z-index:20; margin-bottom:40px;"></div>

   </div>
		<p align="center" class="style_text_main">&nbsp;</p>
      </div>      
      <p align="center" class="style_text_main">&nbsp;</p>
    </td>
  </tr>
</table>


</div> <!-- cat_ite_cont_m -->

<?php

   } 

?>







<div id="catalogue_item_menu">

<div class="catalogue_item_mp_a">

<a href="index.php?section_id=32&amp;business=1">Category:</a></div>

</div>

<div class="catalogue_item_cont">

<a href="index.php?section_id=2&amp;business=1">business</a>

 / 

<a href="index.php?section_id=32&amp;business=1">company</a>

 / 

<a href="index.php?section_id=368&business=2">service</a>

 / 

<a href="index.php?section_id=507&business=2">funeral service</a>

</div>





<div id="catalogue_item_menu">

<div class="catalogue_item_mp_a">

<a href="">Photo gallery:</a></div>

</div>

<div class="catalogue_item_cont">

</div>

<div id="catalogue_item_menu">

<div class="catalogue_item_mp_a">

<a href="">Contacts:</div>

</div>

 <div class="catalogue_item_cont">

 		 <table width="100%">

			<tbody>

 			<tr>

			<!--	<td><img class="main_sec_image" src="" width="60" height="60" border="0" alt="" /></td>-->

				<td>Address:</td>

				<td>Telephone:</td>

				<td>Fax:</td>

				<td>E-mail:</td>

				<td>Web site:</td>

			</tr>

			<tr>

				<td>Ukraine, 83086, Donetsk, Postysheva street, 21<br /></td>

				<td>+38(062)-382-63-01</td>

				<td>+38(062)-382-68-52</td>

				<td>rekviem-donetsk@yandex.ru</td>

				<td>http://rekviem.dn.ua</td>



			</tr>

			</tbody> 

		 </table> 		

	 </div>

</div>  





