<!-- start footer -->
<div id="main_footer">
<!-- Yandex.Metrika -->
<script src="//mc.yandex.ru/metrika/watch.js" type="text/javascript"></script>
<div style="display:none;"><script type="text/javascript">
try { var yaCounter1116405 = new Ya.Metrika(1116405); } catch(e){}
</script></div>
<noscript><div style="position:absolute"><img src="//mc.yandex.ru/watch/1116405" alt="" /></div></noscript>
<!-- /Yandex.Metrika -->
<div id="footer_menu">
 <div>
 

<?php
    echo footer_menu();
 ?>
 </div>
</div>
<div id="footer_table">


<table border="0" width="1000px">	
	<tr>
	      <td class="footer_table"><p><?php echo get_localization_string('contacts_address') ?></p></td>
	      <td class="footer_table"><p><?php echo get_localization_string('contacts_phone') ?></p></td>
	      <td class="footer_table"><p><?php echo get_localization_string('contacts_email') ?></p></td>
	</tr>
<tr>





<td class="footer_table">
<!-- I.UA counter image --><a href="http://www.i.ua/" target="_blank" onclick="this.href='http://i.ua/r.php?86742';" title="Rated by I.UA">
<img src="http://r.i.ua/s?u86742&p155&l1" border="0" width="88" height="31" /></a><!-- End of I.UA counter image -->
</td>





<td class="footer_table"><p>&copy 2004-2010 "EuroDonetsk.com", all rights reserved.</p>
<!--LiveInternet logo--><a href="http://www.liveinternet.ru/click"
target="_blank"><img src="//counter.yadro.ru/logo?14.10"
title="LiveInternet: number of pageviews for 24 hours, of visitors for 24 hours and for today is shown"
alt="" border="0" width="88" height="31"/></a><!--/LiveInternet-->
</td>



<td class="footer_table">
<!--bigmir)net TOP 100 Part 2-->
<script type="text/javascript" language="javascript"><!--
function BM_Draw(oBM_STAT){
document.write('<table cellpadding="0" cellspacing="0" border="0" style="display:inline;margin-right:4px;"><tr><td><div style="margin:0px;padding:0px;font-size:1px;width:88px;"><div style="background:url(\'http://i.bigmir.net/cnt/samples/diagonal/b60_top.gif\') no-repeat bottom;">&nbsp;</div><div style="font:10px Tahoma;background:url(\'http://i.bigmir.net/cnt/samples/diagonal/b60_center.gif\');"><div style="text-align:center;"><a href="http://www.bigmir.net/" target="_blank" style="color:#0000ab;text-decoration:none;font:10px Tahoma;">bigmir<span style="color:#ff0000;">)</span>net</a></div><div style="margin-top:3px;padding: 0px 6px 0px 6px;color:#426ed2;"><div style="float:left;font:10px Tahoma;">'+oBM_STAT.hosts+'</div><div style="float:right;font:10px Tahoma;">'+oBM_STAT.hits+'</div></div><br clear="all"/></div><div style="background:url(\'http://i.bigmir.net/cnt/samples/diagonal/b60_bottom.gif\') no-repeat top;">&nbsp;</div></div></td></tr></table>');
}
//-->
</script>
<script type="text/javascript" language="javascript" src="http://c.bigmir.net/?s16858853&t0&l1&o1"></script>
<noscript>
<a href="http://www.bigmir.net/" target="_blank"><img src="http://c.bigmir.net/?v16858853&s16858853&t2&l1" width="88" height="31" alt="bigmir)net TOP 100" title="bigmir)net TOP 100" border="0" /></a>
</noscript>
<!--bigmir)net TOP 100 Part 2-->
</td>
	</tr>	





</table>
</div>
</div>
<!-- end footer -->