<!-- start footer -->

<div id="main_footer" style="margin-bottom:0px;">
<!-- Yandex.Metrika -->
<script src="//mc.yandex.ru/metrika/watch.js" type="text/javascript"></script>
<div style="display:none;"><script type="text/javascript">
try { var yaCounter1116405 = new Ya.Metrika(1116405); } catch(e){}
</script></div>
<noscript><div style="position:absolute"><img src="//mc.yandex.ru/watch/1116405" alt="" /></div></noscript>
<!-- /Yandex.Metrika -->
<div id="footer_menu">
 <div>
 

<?php
    echo footer_menu();
 ?>
 </div>
</div>

<div id="sequ_pod-footer" style="position:relative; float:left; left:7px; top:-3px; width:989px; height:67px; background:url('http://www.eurodonetsk.com/images/grad_foot.jpg');">

<div style="position:relative; float:left; padding:13px; font-family:Arial, Tahoma; color:white;">
<!--LiveInternet logo--><a href="http://www.liveinternet.ru/click"
target="_blank"><img src="//counter.yadro.ru/logo?22.1"
title="LiveInternet: hits & hosts"
alt="LiveInternet: hits & hosts" border="0" width="88" height="31"/></a><!--/LiveInternet-->
</div>
<div>
<a href="http://s08.flagcounter.com/more/xUlw"><img src="http://s08.flagcounter.com/count/xUlw/bg=FFFFFF/txt=000000/border=CCCCCC/columns=2/maxflags=12/viewers=0/labels=1/pageviews=1/" alt="free counters" border="0"></a>
</div>
<div style="position:relative; float:left; top:0px; padding:12px; font-family:Arial, Tahoma; color:white;">
<b>
<p style=" text-align:left;"><?php echo get_localization_string('contacts_address') ?></p>
<p style=" text-align:left;"><?php echo get_localization_string('contacts_email') ?></p>
</b>
</div>

<div style="position:relative; float:left; top:27px; padding:15px; font-family:Arial, Tahoma; color:white;">
<p>&copy 2004-2010 "EuroDonetsk.com", all rights reserved.</p>

<!--/<a href="http://www.liveinternet.ru/stat/eurodonetsk.com/" target="_blank">Detailed stats</a>-->
</div>

<div style="position:relative; float:left; left:50px; padding:12px; font-family:Arial, Tahoma; color:white;"><b>
<p style=" text-align:left;">&nbsp;&nbsp;&nbsp;<?php echo get_localization_string('contacts_phone') ?></p>
</b></div>

<div style="position:relative; width:100%; height:19px; top:0px;">
	<div style="background:url('http://www.eurodonetsk.com/images/left_down.png'); position:absolute; left:0px; top:47px; width:19px; height:20px; z-index:20;">&nbsp;</div>
	<div style="background:url('http://www.eurodonetsk.com/images/right_down.png'); position:absolute; right:0px; top:47px; width:19px; height:20px; z-index:20;">&nbsp;</div>
</div>

</div> <!-- sequ_footer -->

</div>
</div>
</div>

<!-- end footer -->
