<div class="catalogue_item_c">
<style>

<!--
.folding{cursor:hand;font-weight:bold}
-->

.catalogue_item_cont p {
color:#000000;
text-align:justify;
text-indent:0px;
line-height:20px;
margin:0px;
}

.catalogue_item_cont_m {
background-color:#FFFFFF;
border:1px solid lightgray;
color:#000000;
margin:0;
margin:15px 10px 10px;
width:980px;
}

.catalogue_item_cont {
background-color:#ffffff;
border-top:1px solid lightgray;
margin:0 0 7px 10px;
width:980px;
color:#000000;
}
.catalogue_item_c {
background-color:#F3F3F3;
}

.catalogue_item_cont a {
color:#000000;
}

.catalogue_item_cont a:hover {
color:#000000;
text-decoration:underline;
}

.catalogue_item_mp_a {
left:3px;
position:relative;
}

#mm_menu {position:relative;left:610px;width:225px;text-align:center;} 

#div_st {padding:0 0px;position:relative;height:955px;}

@media all and (-webkit-min-device-pixel-ratio:10000),
not all and (-webkit-min-device-pixel-ratio:0) {
 #div_st {height:955px;}
}
#div_st2 {padding:0 0px;position:relative;height:6750px;}

@media all and (-webkit-min-device-pixel-ratio:10000),
not all and (-webkit-min-device-pixel-ratio:0) {
 #div_st2 {height:6750px;}
}
#div_st3 {padding:0 0px;position:relative;height:800px;}

@media all and (-webkit-min-device-pixel-ratio:10000),
not all and (-webkit-min-device-pixel-ratio:0) {
 #div_st3 {height:869px;}
}

div {
	display:block;
}

.sequ_container {
	width:100%;
	height:100%;
	margin:0px;
	padding:0px;
}

.background_div {
	width:980px;
	height:950px;
	background-image:url('../root/msite/coffee/background.png');
}

.logo {
	position:absolute;
	float:right;
	right:80px;
	top:70px;
	background-image:url('../root/msite/coffee/logo.png');
	background-repeat:no-repeat;
	width:335px;
	height:168px;
}

.girl {
	position:absolute;
	float:right;
	right:47px;
	top:685px;
	background-image:url('../root/msite/coffee/girl.png');
	width:363px;
	height:201px;
}

.text_r {
	position:relative;
	float:right;
	width:390px;
	right:45px;
	top:265px;
}

#p_adv {
	font-family:Adventure;
	font:Adventure;	
	font-size:10pt;
	font-weight:bold;
	letter-spacing:1px;
	text-align:right;
	color:#775e4b;
}

.cup {
	position:absolute;
	float:left;
	left:10px;
	top:10px;
	background-image:url('../root/msite/coffee/cup.png');
	width:285px;
	height:236px;
}

@font-face {
	font-family:Adventure;
	src:url(http://www.eurodonetsk.com/public_html/root/msite/coffee/adventure_font.ttf);
}

.sil {
	position:relative;
	float:left;
	width:250px;
	left:30px;
	top:400px;
	font-family:Adventure;
	src:url(http://www.eurodonetsk.com/public_html/root/msite/coffee/adventure_font.ttf);
	font:Adventure;	
	font-size:16pt;
	font-weight:bold;
	font-style:bold;
	letter-spacing:1px;
	color:#775e4b;
}

.mid_pho {
	position:absolute;
	float:left;
	left:285px;
	top:120px;
	background-image:url('../root/msite/coffee/mid_pho.png');
	width:276px;
	height:760px;
}

.girl2 {
	position:absolute;
	float:right;
	right:50px;
	top:6485px;
	background-image:url('../root/msite/coffee/girl.png');
	width:363px;
	height:201px;
}

.background_div2 {
	position:relative;
	float:left;
	display:block;
	width:980px;
	height:6750px;
	background-image:url('../root/msite/coffee/menu_bg.png');
}

.menu {
	position:relative;
	float:right;
	width:540px;
	right:45px;
	top:265px;
	font-family:Adventure;
	src:url(http://www.eurodonetsk.com/public_html/root/msite/coffee/adventure_font.ttf);
	font:Adventure;	
	font-size:16pt;
	font-weight:bold;
	font-style:bold;
	letter-spacing:1px;
	color:#775e4b;
}

.tab {
	font-size:12pt;
	text-align:left;
}

.menu_2 {
	position:relative;
	float:right;
	width:594px;
	right:45px;
	top:265px;
	font-family:Adventure;
	src:url(http://www.eurodonetsk.com/public_html/root/msite/coffee/adventure_font.ttf);
	font:Adventure;	
	font-size:16pt;
	font-weight:bold;
	font-style:bold;
	letter-spacing:1px;
	color:#775e4b;
}

</style>
<?php
if ($_GET['pm'] == 1) 
{
?>
<div class="catalogue_item_cont_m"> 
	<div id="div_st">
		<div class="sequ_container">
			<div class="background_div">
				<div class="logo"></div>
				<div class="text_r">
					<div id="p_adv">
						<p>
						Классическая французская кофейня «La Petite France» гостеприимно открыта для своих гостей<br /> с 8-00 до 22-00.
						</p>
						<br />
						<p>
						Своим посетителям кофейня «La Petite France»  предлагает большой выбор кофе, десерты, настоящую французскую выпечку, изысканные напитки, а также отличный сервис и романтическую обстановку, в которой всегда  приятно проводить время.
						</p>
						<br />
						<p>
						В любое время года, в любую погоду здесь, забыв о городской суете, вы найдете настоящий  уют, комфорт, отменное кофейное меню и все условия для отдыха.
						</p>
						<br />
						<p>
						Каждый наш клиент – особый и вправе рассчитывать на особое отношение к себе и к своим пожеланиям.
						</p>
						<br />
						<p>
						Мы стараемся сделать так, чтобы наши гости становились нашими постоянными клиентами, несмотря на большое количество заведений – конкурентов. 
						</p>
						<p>
						Здесь нет случайных людей.
						</p>
						<br />
						<p>
						Всех наших посетителей объединяет любовь к хорошему кофе и любовь к утонченному французскому стилю.sssssssssssssssssssssssssssssssssssssss
						</p>
						<br />
						<p>
						Мы уверены в том, что время, проведенное в кофейне «La Petite France» будет всегда приятным и оставит самые лучшие впечатления и воспоминания у каждого, кто хоть раз здесь побывал.
						</p>
					</div>
				</div>
				<div class="girl"></div>
				<div class="cup"></div>
				<div class="sil">
					<a href="http://eurodonetsk.com/index.php?business_full=408&pm=1" style="color:#775e4b;">
					<p>
					Главная
					</p>
					</a>
				<br />
					<a href="http://eurodonetsk.com/index.php?business_full=408&pm=2" style="color:#775e4b;">
					<p>
					Меню
					</p>
					</a>
				<br />
					<a href="http://eurodonetsk.com/index.php?business_full=408&pm=3" style="color:#775e4b;">
					<p>
					Специальные<br />
					Предложения
					</p>
					</a>
				<br />
					<a href="http://eurodonetsk.com/index.php?business_full=408&pm=4" style="color:#775e4b;">
					<p>
					Контакты
					</p>
					</a>
				</div>
				<div class="mid_pho">
				
				</div>
			</div> <!-- background_div -->
		</div> <!-- sequ_container -->
	</div>  <!-- div_st -->
</div> <!-- cat_ite_cont_m -->
<?php
}
else
   if ($_GET['pm'] == 2)
   {
?>
<div class="catalogue_item_cont_m"> 
	<div id="div_st2">
		<div class="sequ_container">
			<div class="background_div2">
				<div class="logo"></div>
				<div class="sil">
					<a href="http://eurodonetsk.com/index.php?business_full=408&pm=1" style="color:#775e4b;">
					<p>
					Главная
					</p>
					</a>
				<br />
					<a href="http://eurodonetsk.com/index.php?business_full=408&pm=2" style="color:#775e4b;">
					<p>
					Меню
					</p>
					</a>
				<br />
					<a href="http://eurodonetsk.com/index.php?business_full=408&pm=3" style="color:#775e4b;">
					<p>
					Специальные<br />
					Предложения
					</p>
					</a>
				<br />
					<a href="http://eurodonetsk.com/index.php?business_full=408&pm=4" style="color:#775e4b;">
					<p>
					Контакты
					</p>
					</a>
				</div>
					<div class="menu">
						<table class="tab" width="100%" height="100%" cellpadding="0" cellspacing="0">
						<thead>
							 <b style="font-size:19pt;">МЕНЮ</b>
						</thead>
								<tr>
									<td colspan="2"><p style="color:#7f491b; text-align:center;">Кофейная карта</p></td>
								</tr>
								<tr>
									<td width="70%">&nbsp;</td>
									<td width="15%" align="center">Выход</td>
									<td align="center">Цена,грн.</td>
								</tr>
								<tr>
									<td>Ристретто *<br />
									(кофе на один глоток )</td>
									<td align="center">15 мл</td>
									<td align="center">15,00</td>
								</tr>
								<tr>
									<td>Капучино Торо</td>
									<td align="center">160 мл</td>
									<td align="center">28,00</td>
								</tr>
								<tr>
									<td>Греко оригинале</td>
									<td align="center">120 мл</td>
									<td align="center">30,00</td>
								</tr>
								<tr>
									<td>Аффогато миндальное</td>
									<td align="center">120 мл</td>
									<td align="center">32,00</td>
								</tr>
								<tr>
									<td>Доппио</td>
									<td align="center">30 мл</td>
									<td align="center">30,00</td>
								</tr>
								<tr>
									<td>Mandarine Plaza</td>
									<td align="center">40 мл</td>
									<td align="center">40,00</td>
								</tr>
								<tr>
									<td>Эспрессо *<br />
									(ароматный, крепкий кофе)</td>
									<td align="center">30 мл</td>
									<td align="center">15,00</td>
								</tr>
								<tr>
									<td>Американо *<br />(менее крепкий и концентрированный ,чем эспрессо)</td>
									<td align="center">120 мл</td>
									<td align="center">15,00</td>
								</tr>
								<tr>
									<td>Эспрессо Макиато*<br />(крепкий кофе, с молочной пеной)</td>
									<td align="center">35 мл</td>
									<td align="center">18,00</td>
								</tr>
								<tr>
									<td>Капучино Классическое *<br />(гармоничное сочетание кофе и взбитого молока)</td>
									<td align="center">35 мл</td>
									<td align="center">18,00</td>
								</tr>
								<tr>
									<td>Капучино с сиропом *<br />(гармоничное сочетание кофе, взбитого молока и сиропа по Вашему вкусу)</td>
									<td align="center">160 мл</td>
									<td align="center">25,00</td>
								</tr>													
						</table>
					</div>
					<div class="menu_2">
					<br />
						<table class="tab" width="100%" height="100%" cellpadding="0" cellspacing="0">
							<tr>
								<td width="73%">Латте *<br />(слоистый коктейль состоящий из эспрессо, молока и пены)</td>
								<td align="center">200 мл</td>
								<td align="center">25,00</td>
							</tr>
							<tr>
								<td>Латте  с сиропом*<br />(слоистый коктейль состоящий из эспрессо, молока и пеныс сиропом на выбор)</td>
								<td align="center">200 мл</td>
								<td align="center">30,00</td>
							</tr>
							<tr>
								<td>Моккачино *<br />(кофе, шоколадный сироп, молочная пена)</td>
								<td align="center">200 мл</td>
								<td align="center">28,00</td>
							</tr>
							<tr>
								<td>Гляссе *<br />(прохладный кофейный коктель-десерт с мороженым)</td>
								<td align="center">170 мл</td>
								<td align="center">24,00</td>
							</tr>
							<tr>
								<td>Гляссе с сиропом<br />(прохладный кофейный коктель-десерт с мороженым и сиропом)</td>
								<td align="center">170 мл</td>
								<td align="center">30,00</td>
							</tr>
							<tr>
								<td>Фраппе *<br />(холодный кофе, с легкой пеной)</td>
								<td align="center">150 мл</td>
								<td align="center">20,00</td>
							</tr>
							<tr>
								<td>Фраппе  с сиропом<br />(холодный кофе, с легкой пеной и сиропом)</td>
								<td align="center">150 мл</td>
								<td align="center">25,00</td>
							</tr>
							<tr>
								<td>Кофе по-ирландски<br />(американо с Ballantines Finest и сливками)</td>
								<td align="center">180 мл</td>
								<td align="center">30,00</td>
							</tr>
							<tr>
								<td>Кофе Бейлиз<br />(американо со сливочно-карамельным ликером)</td>
								<td align="center">150 мл</td>
								<td align="center">30,00</td>
							</tr>
							<tr>
								<td>Кофе по-венски<br />(американо со сливками)</td>
								<td align="center">150 мл</td>
								<td align="center">30,00</td>
							</tr>
							<tr>
								<td>Кофе по-ямайски<br />(американо с черным ромом и сливками)</td>
								<td align="center">150 мл</td>
								<td align="center">55,00</td>
							</tr>
							<tr>
								<td>Кофе по-французски<br />(доппио с коньяком)</td>
								<td align="center">120 мл</td>
								<td align="center">30,00</td>
							</tr>
							<tr>
								<td>Кофе по-парижски<br />(доппио с ликером Amarula)</td>
								<td align="center">120 мл</td>
								<td align="center">40,00</td>
							</tr>
							<tr>
								<td>Кофе Special Coffe<br />(эспрессо с молоком ,ликером , Kahlua, Baileys)</td>
								<td align="center">120 мл</td>
								<td align="center">43,00</td>
							</tr>
							<tr>
								<td>Горячий шоколад</td>
								<td align="center">140 мл</td>
								<td align="center">35,00</td>
							</tr>
							<tr>
								<td>Молоко</td>
								<td align="center">50 мл</td>
								<td align="center">3,00</td>
							</tr>
							<tr>
								<td>Сливки</td>
								<td align="center">50 мл</td>
								<td align="center">4,00</td>
							</tr>
							<tr>
								<td colspan="2"><p style="font-size:10pt; color:#7f491f;">* по вашему желанию, напиток можно приготовить  "без кофеина"</p></td>
							</tr>
							<tr>
									<td colspan="2"><p style="color:#7f491b; text-align:center;">Десертная карта</p></td>
							</tr>
							<tr>
									<td >&nbsp;</td>
									<td align="center">Выход</td>
									<td align="center">Цена,грн.</td>
							</tr>
							<tr>
								<td>Шоколадный торт «Захер»<br />(нежный бисквит,пропитанный коньячным сиропом,шоколадным кремом,покрытый глазурью из французского шоколада Караиб)</td>
								<td align="center">150/50 мл</td>
								<td align="center">35,00</td>
							</tr>
							<tr>
								<td>Наполеон<br />(любимый торт в лучших французских традициях)</td>
								<td align="center">150/50 мл</td>
								<td align="center">28,00</td>
							</tr>
							<tr>
								<td>Пироженое «Экзотика»<br />(Бисквитный корж, сливочное суфле с кусочками тропических фруктов)</td>
								<td align="center">150/50 мл</td>
								<td align="center">20,00</td>
							</tr>
							<tr>
								<td>Парфе из черного шоколада<br />(Нежный  шоколадный бисквит с муссом из черного французского шоколада)</td>
								<td align="center">150 мл</td>
								<td align="center">26,00</td>
							</tr>
							<tr>
								<td>Клубничное суфле<br />(легкое воздушное суфле со сливочным соусом и йогуртом)</td>
								<td align="center">80 мл</td>
								<td align="center">22,00</td>
							</tr>
							<tr>
								<td>Профитроли<br />(Французская выпечка с нежным кремом со вкусом  фисташки)</td>
								<td align="center">120 мл</td>
								<td align="center">20,00</td>
							</tr>
							<tr>
								<td>Суфле из белого шоколада<br />(нежное суфле с белым шоколадом и ромом)</td>
								<td align="center">150 мл</td>
								<td align="center">30,00</td>
							</tr>
							<tr>
								<td>Круассан сливочный</td>
								<td align="center">1 шт</td>
								<td align="center">9,00</td>
							</tr>
							<tr>
								<td>Круассан сырный</td>
								<td align="center">1 шт</td>
								<td align="center">13,00</td>
							</tr>
							<tr>
								<td>Круассан шоколадный</td>
								<td align="center">1 шт</td>
								<td align="center">13,00</td>
							</tr>
							<tr>
								<td>Яблочное искушение<br />(яблоко запеченное в слоеном тесте с изюмом и грецким орехом)</td>
								<td align="center">1 шт</td>
								<td align="center">30,00</td>
							</tr>
							<tr>
								<td>Штрудель с маком<br />(воздушная слойка с маковой начинкой)</td>
								<td align="center">170/50</td>
								<td align="center">23,00</td>
							</tr>
							<tr>
								<td>Штрудель Венский<br />(Классическая Венская выпечка с яблоками и корицей\вишней подается с мороженым)</td>
								<td align="center">170/50</td>
								<td align="center">27,00</td>
							</tr>
							<tr>
								<td>Шоколадный бум<br />(Кекс с горячим шоколадом, подается  с шариком ванильного мороженого)</td>
								<td align="center">150/50/50</td>
								<td align="center">28,00</td>
							</tr>
							<tr>
								<td>Чиз-кейк<br />(известный десерт на основе сливочного сыра «Букко»)</td>
								<td align="center">150/50</td>
								<td align="center">40,00</td>
							</tr>
							<tr>
								<td>Тирамису<br />(сочетание сыра «Маскарпоне» кофе и нежных кусочков бисквита пропитанных коньяком)</td>
								<td align="center">170</td>
								<td align="center">42,00</td>
							</tr>
							<tr>
								<td>Панна-котта<br />(Молочное желе со вкусом ванили с соусом на выбор)</td>
								<td align="center">90</td>
								<td align="center">22,00</td>
							</tr>
							<tr>
								<td>Желе «Ягодная фантазия»<br />(желе ягодное/молоко)</td>
								<td align="center">150</td>
								<td align="center">15,00</td>
							</tr>
							<tr>
								<td>Желе «Ванильная свежесть»<br />(мятное желе, ванильный мусс)</td>
								<td align="center">150</td>
								<td align="center">20,00</td>
							</tr>
							<tr>
									<td colspan="2"><p style="color:#7f491b; text-align:center;">Завтраки</p></td>
							</tr>
							<tr>
									<td >&nbsp;</td>
									<td align="center">Выход</td>
									<td align="center">Цена,грн.</td>
							</tr>
							<tr>
								<td>Канапе с семгой</td>
								<td align="center">1 шт</td>
								<td align="center">12,00</td>
							</tr>
							<tr>
								<td>Канапе с креветкой</td>
								<td align="center">1 шт</td>
								<td align="center">9,00</td>
							</tr>
							<tr>
								<td>Канапе с паштетом</td>
								<td align="center">1 шт</td>
								<td align="center">4,00</td>
							</tr>
							<tr>
								<td>Канапе с сыром Камамбер и виноградом</td>
								<td align="center">1 шт</td>
								<td align="center">9,00</td>
							</tr>
							<tr>
								<td>Брускетта и помидорами</td>
								<td align="center">1 шт</td>
								<td align="center">7,00</td>
							</tr>
							<tr>
								<td>Сырное шато<br />(камамбер, шевру,дор-блю, эминталь, пармезан)</td>
								<td align="center">40/40/40/40/40</td>
								<td align="center">80,00</td>
							</tr>
							<tr>
								<td>Овсянка на молоке с цукатами</td>
								<td align="center">200</td>
								<td align="center">13,00</td>
							</tr>
							<tr>
								<td>Мюсли на молоке с фруктами</td>
								<td align="center">200</td>
								<td align="center">10,00</td>
							</tr>
							<tr>
								<td>Классический омлет
								<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;с сыром
								<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;с беконом
								<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;с грибами</td>
								<td align="center">&nbsp;150
								<br />30
								<br />30
								<br />30</td>
								<td align="center">&nbsp;17,00
								<br />12
								<br />25
								<br />15</td>
							</tr>
							<tr>
								<td>Грисини с базиликом, сыром, кунжутом</td>
								<td align="center">3шт</td>
								<td align="center">12,00</td>
							</tr>
							<tr>
								<td>Сырники со сметаной</td>
								<td align="center">250/100</td>
								<td align="center">18,00</td>
							</tr>
							<tr>
									<td colspan="2"><p style="color:#7f491b; text-align:center;">Супы</p></td>
							</tr>
							<tr>
								<td>Суп-крем из шампиньонов</td>
								<td align="center">250</td>
								<td align="center">28,00</td>
							</tr>
							<tr>
								<td>Французский луковый суп</td>
								<td align="center">250</td>
								<td align="center">30,00</td>
							</tr>
							<tr>
								<td>Бульон с крутонами и зеленью</td>
								<td align="center">250/50</td>
								<td align="center">18,00</td>
							</tr>
							<tr>
									<td colspan="2"><p style="color:#7f491b; text-align:center;">Блинная карта</p></td>
							</tr>
							<tr>
								<td>Блинчики с семгой</td>
								<td align="center">200</td>
								<td align="center">55,00</td>
							</tr>
							<tr>
								<td>Блинчики с моцареллой и зеленью</td>
								<td align="center">200</td>
								<td align="center">35,00</td>
							</tr>
							<tr>
								<td>Блинчики с грибами</td>
								<td align="center">200</td>
								<td align="center">24,00</td>
							</tr>
							<tr>
								<td>Блинчики с творогом</td>
								<td align="center">150/100</td>
								<td align="center">20,00</td>
							</tr>
							<tr>
								<td>Блинчики с ягодами</td>
								<td align="center">150/100</td>
								<td align="center">22,00</td>
							</tr>
							<tr>
								<td>Блинчики с маком</td>
								<td align="center">150/100</td>
								<td align="center">20,00</td>
							</tr>
							<tr>
								<td>Блинчики классические</td>
								<td align="center">200</td>
								<td align="center">15,00</td>
							</tr>
							<tr>
									<td colspan="2"><p style="color:#7f491b; text-align:center;">Мороженое</p></td>
							</tr>
							<tr>
									<td >&nbsp;</td>
									<td align="center">Выход</td>
									<td align="center">Цена,грн.</td>
							</tr>
							<tr>
								<td>Мороженое с ягодами</td>
								<td align="center">150/50</td>
								<td align="center">25,00</td>
							</tr>
							<tr>
								<td>Мороженое с орехами</td>
								<td align="center">150/30</td>
								<td align="center">23,00</td>
							</tr>
							<tr>
								<td>Мороженое  с ананасом, апельсином, яблоками и виноградом</td>
								<td align="center">150/50</td>
								<td align="center">25,00</td>
							</tr>
							<tr>
								<td>Мороженое шоколадное</td>
								<td align="center">150/25</td>
								<td align="center">25,00</td>
							</tr>
							<tr>
								<td>Мороженое ассорти<br />(на выбор ванильное, шоколадное, клубничное и персиковое)</td>
								<td align="center">150</td>
								<td align="center">20,00</td>
							</tr>
							<tr>
									<td colspan="2"><p style="color:#7f491b; text-align:center;">Фрукты</p></td>
							</tr>
							<tr>
								<td>Ананас</td>
								<td align="center">100гр</td>
								<td align="center">15,00</td>
							</tr>
							<tr>
								<td>Апельсин</td>
								<td align="center">100гр</td>
								<td align="center">7,00</td>
							</tr>
							<tr>
								<td>Банан</td>
								<td align="center">100гр</td>
								<td align="center">7,00</td>
							</tr>
							<tr>
								<td>Виноград</td>
								<td align="center">100гр</td>
								<td align="center">15,00</td>
							</tr>
							<tr>
								<td>Грейфрут</td>
								<td align="center">100гр</td>
								<td align="center">9,00</td>
							</tr>
							<tr>
								<td>Киви</td>
								<td align="center">100гр</td>
								<td align="center">10,00</td>
							</tr>
							<tr>
								<td>Лимон</td>
								<td align="center">100гр</td>
								<td align="center">9,00</td>
							</tr>
							<tr>
								<td>Яблоко</td>
								<td align="center">100гр</td>
								<td align="center">8,00</td>
							</tr>
							<tr>
									<td colspan="2"><p style="color:#7f491b; text-align:center;">Соусы</p></td>
							</tr>
							<tr>
								<td>Ванильный</td>
								<td align="center">50 мл</td>
								<td align="center">9,00</td>
							</tr>
							<tr>
								<td>Клубничный</td>
								<td align="center">50 мл</td>
								<td align="center">8,00</td>
							</tr>
							<tr>
								<td>Вишневый</td>
								<td align="center">50 мл</td>
								<td align="center">8,00</td>
							</tr>
							<tr>
								<td>Ягодный</td>
								<td align="center">50 мл</td>
								<td align="center">10,00</td>
							</tr>
							<tr>
								<td>Бейлиз</td>
								<td align="center">50 мл</td>
								<td align="center">10,00</td>
							</tr>
							<tr>
								<td>Шоколадный</td>
								<td align="center">50 мл</td>
								<td align="center">9,00</td>
							</tr>
							<tr>
								<td>Карамель</td>
								<td align="center">50 мл</td>
								<td align="center">8,00</td>
							</tr>
							<tr>
								<td>Мед</td>
								<td align="center">50 мл</td>
								<td align="center">5,00</td>
							</tr>
							<tr>
								<td>Сметана</td>
								<td align="center">50 мл</td>
								<td align="center">5,00</td>
							</tr>
							<tr>
									<td colspan="2"><p style="color:#7f491b; text-align:center;">Минеральная вода</p></td>
							</tr>
							<tr>
									<td >&nbsp;</td>
									<td align="center">Выход</td>
									<td align="center">Цена,грн.</td>
							</tr>
							<tr>
								<td>Боржоми</td>
								<td align="center">330 мл</td>
								<td align="center">20,00</td>
							</tr>
							<tr>
								<td>Моршинская с\г</td>
								<td align="center">500 мл</td>
								<td align="center">8,00</td>
							</tr>
							<tr>
								<td>Evian</td>
								<td align="center">330 мл</td>
								<td align="center">22,00</td>
							</tr>
							<tr>
								<td>Моршинская б\г</td>
								<td align="center">500 мл</td>
								<td align="center">8,00</td>
							</tr>
							<tr>
									<td colspan="2"><p style="color:#7f491b; text-align:center;">Газированные напитки</p></td>
							</tr>
							<tr>
								<td>Бонаква</td>
								<td align="center">500 мл</td>
								<td align="center">8,00</td>
							</tr>
							<tr>
								<td>Сoca-Cola, Fanta, Sprite</td>
								<td align="center">500 мл</td>
								<td align="center">9,00</td>
							</tr>
							<tr>
									<td colspan="2"><p style="color:#7f491b; text-align:center;">Соки</p></td>
							</tr>
							<tr>
								<td>Соки «Sandora» в ассортименте</td>
								<td align="center">250 мл</td>
								<td align="center">8,00</td>
							</tr>
							<tr>
									<td colspan="2"><p style="color:#7f491b; text-align:center;">Свежевыжатые соки</p></td>
							</tr>
							<tr>
								<td>яблочный</td>
								<td align="center">250 мл</td>
								<td align="center">25,00</td>
							</tr>
							<tr>
								<td>апельсиновый</td>
								<td align="center">250 мл</td>
								<td align="center">25,00</td>
							</tr>
							<tr>
								<td>грейпфрутовый</td>
								<td align="center">250 мл</td>
								<td align="center">30,00</td>
							</tr>
							<tr>
								<td>морковный</td>
								<td align="center">250 мл</td>
								<td align="center">20,00</td>
							</tr>
							<tr>
								<td>ананасовый</td>
								<td align="center">250 мл</td>
								<td align="center">55,00</td>
							</tr>
							<tr>
								<td>сельдереевый</td>
								<td align="center">250 мл</td>
								<td align="center">50,00</td>
							</tr>
							<tr>
								<td>лимонный</td>
								<td align="center">250 мл</td>
								<td align="center">45,00</td>
							</tr>
							<tr>
									<td colspan="2"><p style="color:#7f491b; text-align:center;">Молочные коктейли</p></td>
							</tr>
							<tr>
								<td>Молочный<br />(на основе молока с добавлением мороженого)</td>
								<td align="center">250 мл</td>
								<td align="center">20,00</td>
							</tr>
							<tr>
								<td>Ванильный<br />(на основе молока с добавлением мороженого и фирменного соуса)</td>
								<td align="center">250 мл</td>
								<td align="center">25,00</td>
							</tr>
							<tr>
								<td>Клубничный<br />(на основе молока с добавлением мороженого и фирменного соуса)</td>
								<td align="center">250 мл</td>
								<td align="center">25,00</td>
							</tr>
							<tr>
								<td>Вишневый<br />(на основе молока с добавлением мороженого и фирменного соуса)</td>
								<td align="center">250 мл</td>
								<td align="center">25,00</td>
							</tr>
							<tr>
								<td>Карамельный<br />(на основе молока с добавлением мороженого и фирменного соуса)</td>
								<td align="center">250 мл</td>
								<td align="center">28,00</td>
							</tr>
							<tr>
								<td>Гренадин<br />(молочно-кофейный коктейль, с добавлением клубники и гренадина)</td>
								<td align="center">300 мл</td>
								<td align="center">30,00</td>
							</tr>
							<tr>
									<td colspan="2"><p style="color:#7f491b; text-align:center;">Горячие напитки</p></td>
							</tr>
							<tr>
								<td>Глинтвейн<br />(горячий напиток на основе красного сухого вина, цитрусовых, пряностей)</td>
								<td align="center">200 мл</td>
								<td align="center">25,00</td>
							</tr>
							<tr>
								<td>Грог<br />(горячий чайный напиток с добавлением рома  меда, лимона)</td>
								<td align="center">200 мл</td>
								<td align="center">25,00</td>
							</tr>
							<tr>
								<td>Грог вишневый<br />(горячий  напиток с вишневым вкусом)</td>
								<td align="center">200 мл</td>
								<td align="center">25,00</td>
							</tr>
							<tr>
								<td>Грог мятный	<br />(горячий  напиток с мятным вкусом)</td>
								<td align="center">200 мл</td>
								<td align="center">27,00</td>
							</tr>
							<tr>
									<td colspan="2"><p style="color:#7f491b; text-align:center;">Короткие коктейли</p></td>
							</tr>
							<tr>
								<td>Кофемолка<br />(кофе эспрессо, Kahlya,Absinthe)</td>
								<td align="center">70 мл</td>
								<td align="center">30,00</td>
							</tr>
							<tr>
								<td>BMW<br />(ликер Malibu,Red Leber, Baileys)</td>
								<td align="center">75 мл</td>
								<td align="center">45,00</td>
							</tr>
							<tr>
								<td>Б - 52<br />(Kahlua, Baileys, Triple Sec)</td>
								<td align="center">75 мл</td>
								<td align="center">50,00</td>
							</tr>
							<tr>
								<td>Champs Elysees<br />(коктейль из Kahlya, Amarula и черного рома)</td>
								<td align="center">75 мл</td>
								<td align="center">50,00</td>
							</tr>
							<tr>
									<td colspan="2"><p style="color:#7f491b; text-align:center;">Длинные коктейли</p></td>
							</tr>
							<tr>
								<td>Лонг Айленд Айс- Ти<br />(на основе Triple Sec, водка, джин,ром, лимонный фреш и кока-кола)</td>
								<td align="center">350 мл</td>
								<td align="center">45,00</td>
							</tr>
							<tr>
								<td>Лонг Бич  Айс- Ти<br />(на основе Triple Sec, водка, джин,ром, лимонный фреш и клюквенный морс)</td>
								<td align="center">350 мл</td>
								<td align="center">45,00</td>
							</tr>
							<tr>
								<td>Малибу Dream<br />(Malibu, Martini, соки ананаса и апельсина)</td>
								<td align="center">200 мл</td>
								<td align="center">25,00</td>
							</tr>
							<tr>
								<td>Cosmopolitаn<br />(Triple Sec, клюквенный морс, водка)</td>
								<td align="center">150 мл</td>
								<td align="center">25,00</td>
							</tr>
							<tr>
								<td>Инфинити<br />(джин Gordon`s, Mandarine Napoleon, сироп Гренадин,грейфрутовый сок)</td>
								<td align="center">135 мл</td>
								<td align="center">45,00</td>
							</tr>
							<tr>
								<td>Light CHERRI<br />(мартини Bianco,Triple Sec,вишневый сок)</td>
								<td align="center">175 мл</td>
								<td align="center">40,00</td>
							</tr>
							<tr>
								<td>Пино-Колада<br />(Bacardi,сливки,ананасовый сок, Malibu)</td>
								<td align="center">200 мл</td>
								<td align="center">60,00</td>
							</tr>
							<tr>
								<td>Ирландский коктейль<br />(Beliys,Red Leber,молоко)</td>
								<td align="center">200 мл</td>
								<td align="center">60,00</td>
							</tr>
							<tr>
								<td>Сливочный Бум<br />( Beliys, Malibu, сливки, анансовый сок)</td>
								<td align="center">200 мл</td>
								<td align="center">40,00</td>
							</tr>
							<tr>
								<td>Мохито безалкогольный<br />(спрайта, с освежающими нотками мяты и лайма)</td>
								<td align="center">400 мл</td>
								<td align="center">23,00</td>
							</tr>
							<tr>
								<td>Маргарита кофейная<br />( кофе Эспрессо, текилы, Triple Sec, лайм)</td>
								<td align="center">110 мл</td>
								<td align="center">50,00</td>
							</tr>
							<tr>
								<td>Мохито<br />(ром,  мята,  лайм, сироп и спрайт)</td>
								<td align="center">400 мл</td>
								<td align="center">35,00</td>
							</tr>		
						</table>
						<table class="tab" width="100%" height="100%" cellpadding="0" cellspacing="0">
							<tr>
									<td colspan="3"><p style="color:#7f491b; text-align:center;">Алкогольные напитки</p></td>
							</tr>
							<tr>
								<td width="65%">
									&nbsp;
								</td>
								<td>
									50мл
								</td>
								<td>
									100мл
								</td>
								<td>
									750мл
								</td>
							</tr>
							<tr>
								<td colspan="3">
								<p style="text-align:center; color:#7f491f;">
									Игристые вина<br/>			
                                         Италия 
								</p>
								</td>
							</tr>
							<tr>
								<td>
									Canti Asti бел. сух.
								</td>
								<td>
									&nbsp;
								</td>
								<td>
									&nbsp;
								</td>
								<td>
									200,00
								</td>
							</tr>
							<tr>
								<td>
									Canti Rose  роз. сух.
								</td>
								<td>
									&nbsp;
								</td>
								<td>
									&nbsp;
								</td>
								<td>
									250,00
								</td>
							</tr>
							<tr>
								<td colspan="3">
								<p style="text-align:center; color:#7f491f;">
											
                                         Украина 
								</p>
								</td>
							</tr>
							<tr>
								<td>
									Артемовское бел/полусух
								</td>
								<td>
									&nbsp;
								</td>
								<td>
									&nbsp;
								</td>
								<td>
									65,00
								</td>
							</tr>
							<tr>
								<td>
									Артемовское       бел/полусл 
								</td>
								<td>
									&nbsp;
								</td>
								<td>
									&nbsp;
								</td>
								<td>
									65,00
								</td>
							</tr>
							<tr>
								<td colspan="3">
								<p style="text-align:center;">
											
                                         Виски 
								</p>
								</td>
							</tr>
							<tr>
								<td>
									Johnnie walker red label 
								</td>
								<td>
									27,00
								</td>
								<td>
									54,00
								</td>
								<td>
									&nbsp;
								</td>
							</tr>
							<tr>
								<td>
									Вallantines finest 
								</td>
								<td>
									25,00
								</td>
								<td>
									50,00
								</td>
								<td>
									&nbsp;
								</td>
							</tr>
							<tr>
								<td>
									&nbsp;
								</td>
								<td>
									&nbsp;
								</td>
								<td>
									&nbsp;
								</td>
								<td>
									&nbsp;
								</td>
							</tr>
							<tr>
								<td>
									Jameson
								</td>
								<td>
									25,00
								</td>
								<td>
									50,00
								</td>
								<td>
									&nbsp;
								</td>
							</tr>
							<tr>
								<td colspan="3">
								<p style="text-align:center;">
											
                                         Коньяк 
								</p>
								</td>
							</tr>
							<tr>
								<td>
									Hennessy V.S  0,5
								</td>
								<td>
									50,00
								</td>
								<td>
									100,00
								</td>
								<td>
									&nbsp;
								</td>
							</tr>
							<tr>
								<td>
									Hennessy V.S.O.P. 0,7
								</td>
								<td>
									75,00
								</td>
								<td>
									150,00
								</td>
								<td>
									&nbsp;
								</td>
							</tr>
							<tr>
								<td>
									Hennessy X.O. 0,35
								</td>
								<td>
									240,00
								</td>
								<td>
									480,00
								</td>
								<td>
									&nbsp;
								</td>
							</tr>
							<tr>
								<td>
									Ной Классик 7л    0,7
								</td>
								<td>
									35,00
								</td>
								<td>
									70,00
								</td>
								<td>
									&nbsp;
								</td>
							</tr>
							<tr>
								<td>
									Ной Классик 15л  0,7 
								</td>
								<td>
									75,00
								</td>
								<td>
									150,00
								</td>
								<td>
									&nbsp;
								</td>
							</tr>
							<tr>
								<td>
									Клинков V. S  0.5  
								</td>
								<td>
									20,00
								</td>
								<td>
									40,00
								</td>
								<td>
									&nbsp;
								</td>
							</tr>
							<tr>
								<td>
									Асканели 
								</td>
								<td>
									20,00
								</td>
								<td>
									40,00
								</td>
								<td>
									&nbsp;
								</td>
							</tr>
							<tr>
								<td colspan="3">
								<p style="text-align:center;">
											
                                         Джин 
								</p>
								</td>
							</tr>
							<tr>
								<td>
									Gordon`s 
								</td>
								<td>
									25,00
								</td>
								<td>
									50,00
								</td>
								<td>
									&nbsp;
								</td>
							</tr>
							<tr>
								<td colspan="3">
								<p style="text-align:center;">
											
                                         Ликеры 
								</p>
								</td>
							</tr>
							<tr>
								<td>
									Ramazzotti Sambuka
								</td>
								<td>
									25,00
								</td>
								<td>
									50,00
								</td>
								<td>
									&nbsp;
								</td>
							</tr>
							<tr>
								<td>
									Amarula
								</td>
								<td>
									20,00
								</td>
								<td>
									40,00
								</td>
								<td>
									&nbsp;
								</td>
							</tr>
							<tr>
								<td>
									Baileys
								</td>
								<td>
									25,00
								</td>
								<td>
									50,00
								</td>
								<td>
									&nbsp;
								</td>
							</tr>
							<tr>
								<td>
									Kahlua
								</td>
								<td>
									25,00
								</td>
								<td>
									50,00
								</td>
								<td>
									&nbsp;
								</td>
							</tr>
							<tr>
								<td>
									Malibu
								</td>
								<td>
									20,00
								</td>
								<td>
									40,00
								</td>
								<td>
									&nbsp;
								</td>
							</tr>
							<tr>
								<td>
									Mandarine Napoleon
								</td>
								<td>
									45,00
								</td>
								<td>
									90,00
								</td>
								<td>
									&nbsp;
								</td>
							</tr>
							<tr>
								<td>
									MB Triple Sec
								</td>
								<td>
									30,00
								</td>
								<td>
									60,00	
								</td>
								<td>
									&nbsp;
								</td>
							</tr>
							<tr>
									<td colspan="3"><p style="color:#7f491f; text-align:center;">Вина Франции</p></td>
							</tr>
							<tr>
								<td width="65%">
									&nbsp;
								</td>
								<td>
									50мл
								</td>
								<td>
									100мл
								</td>
								<td>
									750мл
								</td>
							</tr>
							<tr>
								<td>
									Lucienne Michel Chablis  (бел. сух)
								</td>
								<td>
									30,00
								</td>
								<td>
									60,00	
								</td>
								<td>
									365,00
								</td>
							</tr>
							<tr>
								<td>
									PP Sauvignon (бел. сух)
								</td>
								<td>
									16,00
								</td>
								<td>
									32,00	
								</td>
								<td>
									200,00
								</td>
							</tr>
							<tr>
								<td>
									PP Chardonnay ( бел. сух)
								</td>
								<td>
									16,00
								</td>
								<td>
									32,00	
								</td>
								<td>
									200,00
								</td>
							</tr>
							<tr>
								<td>
									PP Cabernet  Sauvignon (кр. сух)
								</td>
								<td>
									16,00
								</td>
								<td>
									32,00	
								</td>
								<td>
									200,00
								</td>
							</tr>
							<tr>
								<td>
									PP Merlot (кр. сух)
								</td>
								<td>
									16,00
								</td>
								<td>
									32,00	
								</td>
								<td>
									200,00
								</td>
							</tr>
							<tr>
								<td>
									Calvet Bordeaux Sauvignon Blanc (бел. сух)
								</td>
								<td>
									11,00
								</td>
								<td>
									22,00	
								</td>
								<td>
									150,00
								</td>
							</tr>
							<tr>
								<td>
									Calvet Bordeaux Merlot-Cabernet  (кр. сух)
								</td>
								<td>
									11,00
								</td>
								<td>
									22,00	
								</td>
								<td>
									150,00
								</td>
							</tr>
							<tr>
									<td colspan="3"><p style="color:#7f491f; text-align:center;"> Вина Италии</p></td>
							</tr>
							<tr>
								<td width="65%">
									Toscano Bianco (бел. сух)
								</td>
								<td>
									8,00
								</td>
								<td>
									16,00
								</td>
								<td>
									110,00
								</td>
							</tr>
							<tr>
								<td width="65%">
									Toscano Rosse ( кр. сух)
								</td>
								<td>
									8,00
								</td>
								<td>
									16,00
								</td>
								<td>
									110,00
								</td>
							</tr>
							<tr>
									<td colspan="3"><p style="color:#7f491f; text-align:center;">Вина Чили</p></td>
							</tr>
							<tr>
								<td width="65%">
									Mar Del Sur (кр. п/сл)
								</td>
								<td>
									7,00	
								</td>
								<td>
									14,00
								</td>
								<td>
									90,00
								</td>
							</tr>
							<tr>
								<td width="65%">
									Мар дель Сур п/сл. красное 
								</td>
								<td>
									7,00	
								</td>
								<td>
									14,00
								</td>
								<td>
									90,00
								</td>
							</tr>
							<tr>
								<td width="65%">
									Вермут мартини Bianco 
								</td>
								<td>
									17,00	
								</td>
								<td>
									34,00
								</td>
								<td>
									&nbsp;
								</td>
							</tr>
							<tr>
								<td width="65%">
									Ром Bacardi Black 
								</td>
								<td>
									35,00
								</td>
								<td>
									70,00
								</td>
								<td>
									&nbsp;
								</td>
							</tr>
							<tr>
								<td width="65%">
									Текила Oimtca Blanco
								</td>
								<td>
									30,00
								</td>
								<td>
									60,00
								</td>
								<td>
									&nbsp;
								</td>
							</tr>
							<tr>
								<td width="65%">
									Настойка Absent Винсент 
								</td>
								<td>
									25,00
								</td>
								<td>
									50,00
								</td>
								<td>
									&nbsp;
								</td>
							</tr>
						</table>
					</div>
				<div class="girl2"></div>
				<div class="cup"></div>
			</div> <!-- background_div -->
		</div> <!-- sequ_container -->
	</div>  <!-- div_st -->
</div> <!-- cat_ite_cont_m -->
<?php
}
else
   if ($_GET['pm'] == 3)
   {
?>
<div class="catalogue_item_cont_m"> 
	<div id="div_st">
		<div class="sequ_container">
			<div class="background_div">
				<div class="logo"></div>
				<div class="text_r">
					<div id="p_adv">
						<p>
						Каждый наш клиент – особый и вправе рассчитывать на особое отношение к себе и к своим пожеланиям. 
						</p>
						<br />
						<p>
						Мы уверены в том, что время, проведенное в кофейне «La Petite France» будет всегда приятным и оставит самые лучшие впечатления и воспоминания у каждого, кто хоть раз здесь побывал. 
						</p>
						<br />
						<p style="text-align:center; color:#550601; font-size:18px;">
						Акция: Пора согреться! Скидка на  глинтвейн   20%!
						</p>
						<br />
						<p style="text-align:center; color:#550601; font-size:16px;">
						Специальное предложение на завтраки.<br />С 8-00 до 11-00 
						</p>
						<p>
						&nbsp;Кофе (на выбор эспрессо или американо) + круассан = 20,00 грн
						</p>
						<br />
						<p>
						Чай (черный или зеленый) + блинчики с медом или сметаной = 20,00 грн
						</p>
						<br />
						<p>
						Кофе, кофе с молоком, чай (на выбор) Сок + омлет, омлет с сыром, овсянка с фруктами, мюсли, слойка с фруктами (на выбор) = 30,00 грн.
						</p>
						<br />
						<p>
						<b style="color:#55060f;">Каждую пятницу вечер маленького черного платья.</b> Девушкам пришедшим в таком платье предоставляется скидка <b style="color:#55060f;">20 %</b> на ужин для двоих. Всегда рады видеть Вас в нашей маленькой Франции.
						</p>
					</div>
				</div>
				<div class="girl"></div>
				<div class="cup"></div>
				<div class="sil">
					<a href="http://eurodonetsk.com/index.php?business_full=408&pm=1" style="color:#775e4b;">
					<p>
					Главная
					</p>
					</a>
				<br />
					<a href="http://eurodonetsk.com/index.php?business_full=408&pm=2" style="color:#775e4b;">
					<p>
					Меню
					</p>
					</a>
				<br />
					<a href="http://eurodonetsk.com/index.php?business_full=408&pm=3" style="color:#775e4b;">
					<p>
					Специальные<br />
					Предложения
					</p>
					</a>
				<br />
					<a href="http://eurodonetsk.com/index.php?business_full=408&pm=4" style="color:#775e4b;">
					<p>
					Контакты
					</p>
					</a>
				</div>
				<div class="mid_pho">
				
				</div>
			</div> <!-- background_div -->
		</div> <!-- sequ_container -->
	</div>  <!-- div_st -->
</div> <!-- cat_ite_cont_m -->
<?php
}
else
   if ($_GET['pm'] == 4)
   {
?>
<div class="catalogue_item_cont_m"> 
	<div id="div_st">
		<div class="sequ_container">
			<div class="background_div">
				<div class="logo"></div>
				<div class="text_r">
					<div id="p_adv">
						<p style="color:#550601; font-size:24px; text-align:center;">
						пр. Гурова 20<br /><br />
						тел. (062) 335-16-39
						</p>
						<div id="div_st4">
						<script src="http://api-maps.yandex.ru/1.1/index.xml?key=AAmDzUsBAAAARkVWCAIAXzMCgKN58_MQUqB134Sdp-unCH0AAAAAAAAAAACbJlz2mcKc4anRgbxx6LBZ5BHPyg==" type="text/javascript"></script>
						<script type="text/javascript">
						window.onload = function () {
							var map = new YMaps.Map(document.getElementById("YMapsID"));
							map.setCenter(new YMaps.GeoPoint(37.800505,48.004238), 16);

							var content = document.createElement('span');
							content.innerHTML = "Кофейня «La Petite France»";
							map.openBalloon(new YMaps.GeoPoint(37.800505,48.004159), content);

							map.addControl(new YMaps.ToolBar());
							map.addControl(new YMaps.Zoom());
							map.addControl(new YMaps.MiniMap());
							map.addControl(new YMaps.ScaleLine());
						}
    </script>
	


	 <div id="YMapsID" style="width:90%; height:450px; position:relative; float:left; top:20px; left:40px; z-index:20; margin-bottom:40px;"></div>
   </div>
					</div>
				</div>
				<div class="girl"></div>
				<div class="cup"></div>
				<div class="sil">
					<a href="http://eurodonetsk.com/index.php?business_full=408&pm=1" style="color:#775e4b;">
					<p>
					Главная
					</p>
					</a>
				<br />
					<a href="http://eurodonetsk.com/index.php?business_full=408&pm=2" style="color:#775e4b;">
					<p>
					Меню
					</p>
					</a>
				<br />
					<a href="http://eurodonetsk.com/index.php?business_full=408&pm=3" style="color:#775e4b;">
					<p>
					Специальные<br />
					Предложения
					</p>
					</a>
				<br />
					<a href="http://eurodonetsk.com/index.php?business_full=408&pm=4" style="color:#775e4b;">
					<p>
					Контакты
					</p>
					</a>
				</div>
				<div class="mid_pho">
				
				</div>
			</div> <!-- background_div -->
		</div> <!-- sequ_container -->
	</div>  <!-- div_st -->
</div> <!-- cat_ite_cont_m -->
<?php
   } 
?>



<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="index.php?section_id=32&amp;business=1">Категория:</a></div>
</div>
<div class="catalogue_item_cont">
<a href="index.php?section_id=2&amp;business=1">бизнес</a>
 / 
<a href="index.php?section_id=32&amp;business=1">предприятия</a>
 / 
<a href="index.php?section_id=387&amp;business=2">отдых</a>
 / 
<a href="index.php?section_id=512&amp;business=2">кафе и рестораны</a>
</div>


<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="">Фотогалегея:</a></div>
</div>
<div class="catalogue_item_cont">
<div class="catalogue_pic_l"><a href="../root/msite/coffee/gallery/1.jpg" target="_blank"><img src="../root/msite/coffee/gallery/1_s.jpg" width="60" height="40" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="../root/msite/coffee/gallery/2.jpg" target="_blank"><img src="../root/msite/coffee/gallery/2_s.jpg" width="60" height="40" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="../root/msite/coffee/gallery/3.jpg" target="_blank"><img src="../root/msite/coffee/gallery/3_s.jpg" width="60" height="40" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="../root/msite/coffee/gallery/4.jpg" target="_blank"><img src="../root/msite/coffee/gallery/4_s.jpg" width="60" height="40" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="../root/msite/coffee/gallery/5.jpg" target="_blank"><img src="../root/msite/coffee/gallery/5_s.jpg" width="60" height="40" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="../root/msite/coffee/gallery/6.jpg" target="_blank"><img src="../root/msite/coffee/gallery/6_s.jpg" width="60" height="40" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="../root/msite/coffee/gallery/7.jpg" target="_blank"><img src="../root/msite/coffee/gallery/7_s.jpg" width="60" height="40" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="../root/msite/coffee/gallery/8.jpg" target="_blank"><img src="../root/msite/coffee/gallery/8_s.jpg" width="60" height="40" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="../root/msite/coffee/gallery/9.jpg" target="_blank"><img src="../root/msite/coffee/gallery/9_s.jpg" width="60" height="40" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="../root/msite/coffee/gallery/10.jpg" target="_blank"><img src="../root/msite/coffee/gallery/10_s.jpg" width="60" height="40" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="../root/msite/coffee/gallery/11.jpg" target="_blank"><img src="../root/msite/coffee/gallery/11_s.jpg" width="60" height="40" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="../root/msite/coffee/gallery/12.jpg" target="_blank"><img src="../root/msite/coffee/gallery/12_s.jpg" width="60" height="40" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="../root/msite/coffee/gallery/13.jpg" target="_blank"><img src="../root/msite/coffee/gallery/13_s.jpg" width="60" height="40" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="../root/msite/coffee/gallery/14.jpg" target="_blank"><img src="../root/msite/coffee/gallery/14_s.jpg" width="60" height="40" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="../root/msite/coffee/gallery/15.jpg" target="_blank"><img src="../root/msite/coffee/gallery/15_s.jpg" width="60" height="40" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="../root/msite/coffee/gallery/16.jpg" target="_blank"><img src="../root/msite/coffee/gallery/16_s.jpg" width="60" height="40" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="../root/msite/coffee/gallery/17.jpg" target="_blank"><img src="../root/msite/coffee/gallery/17_s.jpg" width="60" height="40" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="../root/msite/coffee/gallery/18.jpg" target="_blank"><img src="../root/msite/coffee/gallery/18_s.jpg" width="60" height="40" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="../root/msite/coffee/gallery/19.jpg" target="_blank"><img src="../root/msite/coffee/gallery/19_s.jpg" width="60" height="40" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="../root/msite/coffee/gallery/20.jpg" target="_blank"><img src="../root/msite/coffee/gallery/20_s.jpg" width="60" height="40" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="../root/msite/coffee/gallery/21.jpg" target="_blank"><img src="../root/msite/coffee/gallery/21_s.jpg" width="60" height="40" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="../root/msite/coffee/gallery/22.jpg" target="_blank"><img src="../root/msite/coffee/gallery/22_s.jpg" width="60" height="40" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="../root/msite/coffee/gallery/23.jpg" target="_blank"><img src="../root/msite/coffee/gallery/23_s.jpg" width="60" height="40" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="../root/msite/coffee/gallery/24.jpg" target="_blank"><img src="../root/msite/coffee/gallery/24_s.jpg" width="60" height="40" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="../root/msite/coffee/gallery/25.jpg" target="_blank"><img src="../root/msite/coffee/gallery/25_s.jpg" width="60" height="40" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="../root/msite/coffee/gallery/26.jpg" target="_blank"><img src="../root/msite/coffee/gallery/26_s.jpg" width="60" height="40" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="../root/msite/coffee/gallery/27.jpg" target="_blank"><img src="../root/msite/coffee/gallery/27_s.jpg" width="60" height="40" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="../root/msite/coffee/gallery/28.jpg" target="_blank"><img src="../root/msite/coffee/gallery/28_s.jpg" width="60" height="40" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="../root/msite/coffee/gallery/29.jpg" target="_blank"><img src="../root/msite/coffee/gallery/29_s.jpg" width="60" height="40" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="../root/msite/coffee/gallery/30.jpg" target="_blank"><img src="../root/msite/coffee/gallery/30_s.jpg" width="60" height="40" border="0" alt=""></a></div>
</div>
<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="">Контактная информация:</div>
</div>
 <div class="catalogue_item_cont">
 		 <table width="100%">
			<tbody>
 			<tr>
			<!--	<td><img class="main_sec_image" src="" width="60" height="60" border="0" alt="" /></td>-->
				<td>Адрес:</td>
				<td>Телефон:</td>
				<td>Факс:</td>
				<td>E-mail:</td>
				<td>Веб-сайт:</td>
			</tr>
			<tr>
				<td>пр. Гурова 20<br /></td>
				<td>тел. (062) 335-16-39</td>
				<td></td>
				<td></td>
				<td></td>

			</tr>
			</tbody> 
		 </table> 		
	 </div>
</div>  


