 document.write("<div class='rolover'>");
document.write("<div id='photos' class='galleryview'>");
  document.write("<div class='panel'>");
    document.write("<img class='gwu_image' src='root/img/001.jpg' /> ");
     document.write("<div class='panel-overlay-block'>");
     document.write("</div>");
    document.write("<div class='panel-overlay'>");
      document.write("<h2>ТУРИСТУ</h2>");
      document.write("<p>Туристическая Украина - нам есть, что показать! - Сергей Тигипко. Государственная поддержка позволит туристической отрасли  </a> ... <a href='index.php?section_id=83&id_page=491' target='_blank'>Подробнее >>> </a></p>");
    document.write("</div>");
  document.write("</div>");
  document.write("<div class='panel'>");
     document.write("<img class='gwu_image' src='root/img/002.jpg' /> ");
         document.write("<div class='panel-overlay-block'>");
     document.write("</div>");
    document.write("<div class='panel-overlay'>");
      document.write("<h2>ДОНЧАНИНУ</h2>");
      document.write("<p>Свадебный переполох. Официальный представитель свадебных и вечерних платьев VIP-класса известнейших европейских фирм</a> ... <a href='index.php?section_id=504' target='_blank'>Подробнее >>> </a></p>");
    document.write("</div>");
  document.write("</div>");
  document.write("<div class='panel'>");
     document.write("<img class='gwu_image' src='root/img/003.jpg' /> ");
         document.write("<div class='panel-overlay-block'>");
     document.write("</div>");
    document.write("<div class='panel-overlay'>");
      document.write("<h2>БИЗНЕС</h2>");
      document.write("<p>Председатель Донецкого  облсовета  А.В. Шишацкий в своем обращении бизнес-аудитории осветил на актуальные вопросы</a> ... <a href='index.php?section_id=348&id_page=494' target='_blank'>Подробнее</a> >>> </p>");
    document.write("</div>");
  document.write("</div>");
  document.write("<div class='panel'>");
     document.write("<img class='gwu_image' src='root/img/04.jpg' /> ");
          document.write("<div class='panel-overlay-block'>");
     document.write("</div>");
    document.write("<div class='panel-overlay'>");
      document.write("<h2>'Euro 2012' will be the 14th EFC...</h2>");
      document.write("<p>The tournament will be held by Ukraine and Poland... </a>.  More <a href='index.php?section_id=468' target='_blank'>here</a>.</p>");
    document.write("</div>");
  document.write("</div>");
  document.write("<div class='panel'>");
     document.write("<img class='gwu_image' src='root/img/06.jpg' /> ");
          document.write("<div class='panel-overlay-block'>");
     document.write("</div>");
    document.write("<div class='panel-overlay'>");
      document.write("<h2>Travelling</h2>");
      document.write("<p>Getting around Ukraine...</a>.  More <a href='index.php?section_id=512' target='_blank'>here</a>.</p>");
    document.write("</div>");
  document.write("</div>");
  document.write("<div class='panel'>");
     document.write("<img class='gwu_image' src='root/img/05.jpg' /> ");
          document.write("<div class='panel-overlay-block'>");
     document.write("</div>");
    document.write("<div class='panel-overlay'>");
      document.write("<h2>Architecture</h2>");
      document.write("<p>Parks, Theaters, Cultural buildings...</a>.  More <a href='index.php?section_id=535' target='_blank'>here</a>.</p>");
    document.write("</div>");
  document.write("</div>");
  document.write("<div class='panel'>");
     document.write("<img class='gwu_image' src='root/img/07.jpg' /> ");
          document.write("<div class='panel-overlay-block'>");
     document.write("</div>");
    document.write("<div class='panel-overlay'>");
      document.write("<h2>History of Donetsk</h2>");
      document.write("<p>Jhon James Hughes</a>.  More <a href='index.php?section_id=530' target='_blank'>here</a>.</p>");
    document.write("</div>");
  document.write("</div>");
  document.write("<div class='panel'>");
     document.write("<img class='gwu_image' src='root/img/08.jpg' /> ");
          document.write("<div class='panel-overlay-block'>");
     document.write("</div>");
    document.write("<div class='panel-overlay'>");
      document.write("<h2>Business</h2>");
      document.write("<p>City development...</a>.  More <a href='index.php?section_id=486' target='_blank'>here</a>.</p>");
    document.write("</div>");
  document.write("</div>");
  document.write("<ul class='filmstrip'>");
    document.write("<li><img src='root/img/frame2-001.jpg' alt='Slide' title='Slide' /></li>");
    document.write("<li><img src='root/img/frame2-002.jpg' alt='Slide' title='Slide' /></li>");
    document.write("<li><img src='root/img/frame2-003.jpg' alt='Slide' title='Slide' /></li>");
    document.write("<li><img src='root/img/frame2-04.jpg' alt='Slide' title='Slide' /></li>");
    document.write("<li><img src='root/img/frame2-06.jpg' alt='Slide' title='Slide' /></li>");
    document.write("<li><img src='root/img/frame2-05.jpg' alt='Slide' title='Slide' /></li>");
    document.write("<li><img src='root/img/frame2-07.jpg' alt='Slide' title='Slide' /></li>");
    document.write("<li><img src='root/img/frame2-08.jpg' alt='Slide' title='Slide' /></li>");
  document.write("</ul>");
document.write("</div>");
document.write("</div>");