<!-- start footer -->
<div id="main_footer">

<div id="footer_menu">
 <div>
 

<?php
    echo footer_menu();
 ?>
 </div>
</div>
<div id="footer_table">

<table border="0" width="1000px" style="padding-bottom:3px;">	
	<tr>
	      <td class="footer_table"><p><?php echo get_localization_string('contacts_address') ?></p></td>
	      <td class="footer_table"><p><?php echo get_localization_string('contacts_phone') ?></p></td>
	      <td class="footer_table"><p><?php echo get_localization_string('contacts_email') ?></p></td>
	</tr>
	<tr>
		<td class="footer_table">


		</td>
		<td class="footer_table">
<!-- Yandex.Metrika informer -->
<a href="http://metrika.yandex.ru/stat/?id=1116405&amp;from=informer"
target="_blank" rel="nofollow"><img src="//bs.yandex.ru/informer/1116405/2_0_B0FF3CFF_90E41CFF_1_visits"
style="width:80px; height:31px; border:0;" alt="Visits" title="Visits today" /></a>
<!-- /Yandex.Metrika informer -->

<!-- Yandex.Metrika counter -->
<script type="text/javascript">
var ya_params = {/*Здесь параметры визита*/};
</script>

<div style="display:none;"><script type="text/javascript">
(function(w, c) {
    (w[c] = w[c] || []).push(function() {
        try {
            w.yaCounter1116405 = new Ya.Metrika({id:1116405, enableAll: true,params:window.ya_params||{ }});
        }
        catch(e) { }
    });
})(window, "yandex_metrika_callbacks");
</script></div>
<script src="//mc.yandex.ru/metrika/watch.js" type="text/javascript" defer="defer"></script>
<noscript><div><img src="//mc.yandex.ru/watch/1116405" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->
		</td>
		<td class="footer_table">
		
		


		</td>
		</tr>	
</table>

</div>
</div>
</div>
<!-- end footer -->