<!-- start footer -->
<div id="main_footer">
<!-- Yandex.Metrika -->
<script src="//mc.yandex.ru/metrika/watch.js" type="text/javascript"></script>
<div style="display:none;"><script type="text/javascript">
try { var yaCounter1116405 = new Ya.Metrika(1116405); } catch(e){}
</script></div>
<noscript><div style="position:absolute"><img src="//mc.yandex.ru/watch/1116405" alt="" /></div></noscript>
<!-- /Yandex.Metrika -->
<div id="footer_menu">
 <div>
 

<?php
    echo footer_menu();
 ?>
 </div>
</div>
<div id="footer_table">


<table border="0" width="1000px" style="padding-bottom:3px;">	
	<tr>
	      <td class="footer_table"><p><?php echo get_localization_string('contacts_address') ?></p></td>
	      <td class="footer_table"><p><?php echo get_localization_string('contacts_phone') ?></p></td>
	      <td class="footer_table"><p><?php echo get_localization_string('contacts_email') ?></p></td>
	</tr>
<tr>





<td class="footer_table">
<!-- I.UA counter image --><a href="http://www.i.ua/" target="_blank" onclick="this.href='http://i.ua/r.php?86742';" title="Rated by I.UA">
<img src="http://i.i.ua/r/3_1_3.png" border="0" width="88" height="31" /></a><!-- End of I.UA counter image -->
<!-- End of I.UA counter image -->
<br>
<a href="http://catalog.i.ua/catalog/811/?r=10000&q=&d=&s=0&r1=10601" target="_blank">Top Rating</a>
</td>





<td class="footer_table">
<!--LiveInternet logo--><a href="http://www.liveinternet.ru/click"
target="_blank"><img src="//counter.yadro.ru/logo?22.1"
title="LiveInternet: hits & hosts"
alt="LiveInternet: hits & hosts" border="0" width="88" height="31"/></a><!--/LiveInternet-->


<p>&copy 2004-2010 "EuroDonetsk.com", all rights reserved.</p>
<!--/<a href="http://www.liveinternet.ru/stat/eurodonetsk.com/" target="_blank">Detailed stats</a>-->

</td>



<td class="footer_table">
<!--bigmir)net TOP 100 Part 2-->
<a href="http://www.bigmir.net/" target="_blank" onClick='img=new Image();img.src="http://www.bigmir.net/?cl=16858853";'><img src="http://i.bigmir.net/cnt/b01.png" width="88" height="31" border="0" alt="bigmir)net TOP 100" title="bigmir)net TOP 100"></a>
<!--bigmir)net TOP 100 Part 2-->
<br>
<a href="http://top.bigmir.net/report/16858853/" target="_blank">Stats</a>
</td>
	</tr>	





</table>
</div>
</div>
<!-- end footer -->