<?php
 page_xml_init();
 $w_t=date('d.m.Y');
?>
<div class="main_page"> 
 <div id="main_left_column">
  <div id="slide_show">
  <script type="text/javascript">
	$(document).ready(function(){
		$('#photos').galleryView({
			panel_width: 480,
			panel_height: 300,
			frame_width: 70,
			frame_height: 42,
			transition_speed: 1200,
			background_color: '#222',
			border: '1px solid #005713',
			easing: 'easeInOutBack',
		        pause_on_hover: true,
			nav_theme: 'custom'
		});
	});
  </script>
  <script language="JavaScript">
    document.write("<div class=\"rolover\">");
document.write("<div id=\"photos\" class=\"galleryview\">");
  document.write("<div class=\"panel\">");
     document.write("<img class=\"gwu_image\" src=\"root/img/01.jpg\" /> ");
     document.write("<div class=\"panel-overlay-block\">");
     document.write("</div>");
    document.write("<div class=\"panel-overlay\">");
      document.write("<h2>Euro2012 in Donetsk...</h2>");
      document.write("<p>Donbass arena welcome guests...</a>.  More <a href=\"index.php?section_id=478\" target=\"_blank\">here</a>.</p>");
    document.write("</div>");
  document.write("</div>");
  document.write("<div class=\"panel\">");
     document.write("<img class=\"gwu_image\" src=\"root/img/02.jpg\" /> ");
         document.write("<div class=\"panel-overlay-block\">");
     document.write("</div>");
    document.write("<div class=\"panel-overlay\">");
      document.write("<h2>Economy</h2>");
      document.write("<p>Donetsk is one of the most largest cities in Ukraine...</a>.  More <a href=\"index.php?section_id=539&id_page=391\" target=\"_blank\">here</a>.</p>");
    document.write("</div>");
  document.write("</div>");
  document.write("<div class=\"panel\">");
     document.write("<img class=\"gwu_image\" src=\"root/img/03.jpg\" /> ");
         document.write("<div class=\"panel-overlay-block\">");
     document.write("</div>");
    document.write("<div class=\"panel-overlay\">");
      document.write("<h2>Donetsk today</h2>");
      document.write("<p>Modern Donetsk is the largest economic complex...</a>.  More <a href=\"index.php?section_id=529\" target=\"_blank\">here</a>.</p>");
    document.write("</div>");
  document.write("</div>");
  document.write("<div class=\"panel\">");
     document.write("<img class=\"gwu_image\" src=\"root/img/04.jpg\" /> ");
          document.write("<div class=\"panel-overlay-block\">");
     document.write("</div>");
    document.write("<div class=\"panel-overlay\">");
      document.write("<h2>\"Euro 2012\" will be the 14th EFC...</h2>");
      document.write("<p>The tournament will be held by Ukraine and Poland... </a>.  More <a href=\"index.php?section_id=468\" target=\"_blank\">here</a>.</p>");
    document.write("</div>");
  document.write("</div>");
  document.write("<div class=\"panel\">");
     document.write("<img class=\"gwu_image\" src=\"root/img/06.jpg\" /> ");
          document.write("<div class=\"panel-overlay-block\">");
     document.write("</div>");
    document.write("<div class=\"panel-overlay\">");
      document.write("<h2>Travelling</h2>");
      document.write("<p>Getting around Ukraine...</a>.  More <a href=\"index.php?section_id=512\" target=\"_blank\">here</a>.</p>");
    document.write("</div>");
  document.write("</div>");
  document.write("<div class=\"panel\">");
     document.write("<img class=\"gwu_image\" src=\"root/img/05.jpg\" /> ");
          document.write("<div class=\"panel-overlay-block\">");
     document.write("</div>");
    document.write("<div class=\"panel-overlay\">");
      document.write("<h2>Architecture</h2>");
      document.write("<p>Parks, Theaters, Cultural buildings...</a>.  More <a href=\"index.php?section_id=535\" target=\"_blank\">here</a>.</p>");
    document.write("</div>");
  document.write("</div>");
  document.write("<div class=\"panel\">");
     document.write("<img class=\"gwu_image\" src=\"root/img/07.jpg\" /> ");
          document.write("<div class=\"panel-overlay-block\">");
     document.write("</div>");
    document.write("<div class=\"panel-overlay\">");
      document.write("<h2>History of Donetsk</h2>");
      document.write("<p>Jhon James Hughes</a>.  More <a href=\"index.php?section_id=530\" target=\"_blank\">here</a>.</p>");
    document.write("</div>");
  document.write("</div>");
  document.write("<div class=\"panel\">");
     document.write("<img class=\"gwu_image\" src=\"root/img/08.jpg\" /> ");
          document.write("<div class=\"panel-overlay-block\">");
     document.write("</div>");
    document.write("<div class=\"panel-overlay\">");
      document.write("<h2>Business</h2>");
      document.write("<p>City development...</a>.  More <a href=\"index.php?section_id=486\" target=\"_blank\">here</a>.</p>");
    document.write("</div>");
  document.write("</div>");
  document.write("<ul class=\"filmstrip\">");
    document.write("<li><img src=\"root/img/frame2-01.jpg\" alt=\"Slide\" title=\"Slide\" /></li>");
    document.write("<li><img src=\"root/img/frame2-02.jpg\" alt=\"Slide\" title=\"Slide\" /></li>");
    document.write("<li><img src=\"root/img/frame2-03.jpg\" alt=\"Slide\" title=\"Slide\" /></li>");
    document.write("<li><img src=\"root/img/frame2-04.jpg\" alt=\"Slide\" title=\"Slide\" /></li>");
    document.write("<li><img src=\"root/img/frame2-06.jpg\" alt=\"Slide\" title=\"Slide\" /></li>");
    document.write("<li><img src=\"root/img/frame2-05.jpg\" alt=\"Slide\" title=\"Slide\" /></li>");
    document.write("<li><img src=\"root/img/frame2-07.jpg\" alt=\"Slide\" title=\"Slide\" /></li>");
    document.write("<li><img src=\"root/img/frame2-08.jpg\" alt=\"Slide\" title=\"Slide\" /></li>");
  document.write("</ul>");
document.write("</div>");
document.write("</div>");
  </script>
  <noscript><img src="root/img/01.jpg" /><div>Please enable javascript!</div></noscript> 
 </div>
 <div class="boxes_title"><div class="boxes_image"></div><div class="boxes_text"><?=get_localization_string('article_title_string')?></div></div>
      <div class="block_me">
	  <div class="img_for_me">
             <a href="index.php?section_id=479"><img border="0" width="220" height="170" src="root/public_images/index_en/fc_in_don.jpg"></a>
	  </div>
	  <div class="txt_block_for_me">
	  <div class="txt_pod_me">
	     Donetsk is a City with High football culture. For  residents there was nothing that can compete with the sport in case of  popularity. The local football club "Shakhtar" exists since 1936 (the  first ten years of its existence it was called "Stakhanovets"), and  all this time it finds its fervent support among the citizens. Away team at the  stadium in Donetsk have a really hard time - the famous football player and  commentator Vladimir Maslachenko once said that... <a href="index.php?section_id=479" class="link_more">>></a>
	  </div>
	  </div>
     </div>
 <div id="news"> 
 <?php echo get_main_news_preview(148,100,"width:148px;padding:0px 12px 0px 0;","width:148px;padding:0px 7px;","width:148px;padding:0px 0px 0px 12px;"); ?>
 </div> 
 </div>
 <div id="main_center_column">
  <div class="boxes_title"><div class="boxes_image"></div><div class="boxes_text"><?=get_localization_string('weather_title_string')?></div></div>
   <div id="date_block">    
    <div id="header_for_weather">
     <?php echo $weather_xml->city->name.', '.$w_t;
     echo '</div>';
     echo '<div id="weather_info">';
     echo '<div id="weather_pict"><img src="images/weather_clipart/'. $weather_xml->current->pict .'" width="44" height="52" /></div>';
     echo '<div id="weather_t">'.$weather_xml->current->t.'&deg;</div>';
     echo '<div id="weather_other">Wind: '.$weather_xml->current->w.'mps<br /> Pressure: '.$weather_xml->current->p.'мм<br /> Humidity: '.$weather_xml->current->h.'% </div>';
     ?>
     </div>     
   </div>
    <div id="banner_2">
     <img border="0" width="236" height="250" alt="" src="root/banners/Dominic-Banner-250x250pxl.jpg">
    </div>
        <div class="boxes_title"><div class="boxes_image"></div><div class="boxes_text">ARTICLE</div></div>
    <div style="width:236px; height:430px; text-align:justify;"><img width="236" height="130" alt="" style="padding: 7px 0;" src="/root/1AboutDonetsk/Donetsk-Ukraine-map.png">
    City Donetsk is located in the centre of the Donbass, southern part of upland, called the Donetsk ridge. Total area of the city is 358 km ². The total extent of Donetsk from the east to west is 55 km and from north to south 38 km.

Besides that Donetsk is located in the steppe zone, more exactly in the upper reaches of the river Kalmius. Regional centre surrounded by small hills, rivers, lakes and forests. And along with all nearby cities, the capital of Donbass is a part of the Donetsk metropolitan area (Donetsk - Makeevka - Khartsizk). The Azov seas is 95 km south of Donetsk and is popular recreational area for those living in Donetsk. Furthermore, in Donetsk, there are two reservoirs: Donetsk sea area (138 ha) and ... <a href="index.php?section_id=531" class="link_more">>></a>     
    </div>
 </div>
 <div id="main_right_column">
   <div class="boxes_title"><div class="boxes_image"></div><div class="boxes_text"><?=get_localization_string('search_title_string')?></div></div>
   <div id="search_block_m">    
    <form method="get" action="index.php" id="search">    
    <div id="block_pod_input">
	<input type="text" class="search_field" name="search_str">
    </div> 
    <div id="search_buttoon">
        <input type="image" src="images/search/search_en.gif" name="search" value=" " class="button_searsh">
    </div>       
    </form>    
    <form method="get" action="index.php" id="add_business">
      <input type="hidden" name="business" value="1">
      <input type="hidden" name="section_id" value="616">
      <input type="hidden" name="lang" value="en">  
      <input type="image" src="images/search/add_company_en.gif" class="button_add_business">      
    </form>
   </div>
   <div id="tags_box">
     <div id="tags_text"></div>
     <div id="tags">
     <?php
          $tags = get_tags(10);
     ?>
     Для корректного отображения этого элемента вам необходимо установить FlashPlayer и включить в браузере Java Script.
     <script type="text/javascript">
     var rnumber = Math.floor(Math.random()*9999999);
     var widget_so = new SWFObject("scripts/tagcloud.swf?r="+rnumber, "tagcloudflash", "234", "200", "10", "#ffffff");
     widget_so.addParam("allowScriptAccess", "always");widget_so.addVariable("tcolor", "0x333333");
     widget_so.addVariable("tspeed", "115");
     widget_so.addVariable("distr", "true");
     widget_so.addVariable("mode", "tags");
     widget_so.addVariable("tagcloud", "<?php echo urlencode($tags); ?>");
     widget_so.write("tags");</script> 
     </div>
   </div>
   <div class="boxes_title"><div class="boxes_text"></div></div>
   <img border="0" width="236" height="236" src="/root/m2.png" style="padding: 12px 0pt;">
 </div>
</div>
