 <div class="catalogue_item_c">
<style>
.catalogue_item_cont p {
color:#F0EF95;
margin:10px;
text-align:justify;
text-indent:0px;
line-height:20px;
}
.catalogue_item_cont {
background-color:#b21d17;
border-top:1px solid lightgray;
margin:0 0 7px 4px;
width:99%;
color:#f0ef95;
}
.catalogue_item_c {
background-color:#FFFFFF;
}
img.main_sec_image {
padding:0px;
width:250px;
height:160px;
}
.catalogue_item_cont a {
color:#F0EF95;
}
.catalogue_item_cont a:hover {
color:#FFFFFF;
text-decoration:underline;
}
.catalogue_item_mp_a {
left:-3px;
position:relative;
}
#div_st {padding:0 85px;position:relative;top:-160px;height:794px;}

@media all and (-webkit-min-device-pixel-ratio:10000),
not all and (-webkit-min-device-pixel-ratio:0) {
 #div_st {height:834px;}
}
td#i_up {font-weight:bold;text-align:left;}
td#i_up1 {font-weight:bold;text-decoration:underline;}
td#i_first {width:450px;text-align:left;font-weight:bold;}
td#i_second {width:100px;font-weight:bold;}
table#i_table tr {height:35px;}
</style>
<?php
if ($_GET['pm'] == 1) 
{
?>

<div class="catalogue_item_cont"> 
<img src="root/seul/i_up.png" alt="" style="width: 100%;" />
<div id="div_st">
<p>
<a href="index.php?business_full=394&amp;pm=1" style="font-size:16px;left:200px;position:relative;top:-40px;float:left;color:#f0ef95;"><i><b>Restaurant</b></i></a>
<a href="index.php?business_full=394&amp;pm=2" style="font-size:16px;left:250px;position:relative;top:-40px;;float:left;color:#f0ef95;"><i><b>Menu</b></i></a>
<a href="index.php?business_full=394&amp;pm=3" style="font-size:16px;left:300px;position:relative;top:-40px;float:left;color:#f0ef95;"><i><b>Contacts</b></i></a>
</p>
<br>
<p>&nbsp;&nbsp;&nbsp;&nbsp;<b>“Seoul” restaurant</b> is one of the first restaurants with <b>Japanese & Korean Cuisines</b> in Donetsk. In the restaurant there works <b>a family</b>, who venerates national traditions and each visitor becomes a welcome guest. The main cuisines are <b>Japanese and Korean</b>. <b>European and Uzbek cuisines</b> are inscribed in banquet menu in accordance with your desire.
</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;A cult of food reigns in Korea, its cuisine is more complicated and various, recipes are based on many culinary secrets, which allow adding an east flavor to usual vegetable salads, meat and fish appetizers. That’s why special attention is devoted to cooking and dishes are cooked according to <b>national traditions by the Korean chef</b>. Traditional Japanese and Korean choice is completed with specialty desserts. </p>
<img class="main_sec_image" src="root/seul/e1.jpg" alt="" style="float: left;margin-left:20px;" /><img class="main_sec_image" src="root/seul/e2.jpg" alt="" style="float: left;" />
<img class="main_sec_image" src="root/seul/e3.jpg" alt="" style="float: left;" /><br><br>
<p style="margin-top: 170px;"><center><font style="text-decoration:underline;font-size:14px;font-weight:bold;">SPECIAL OFFERS:</font></center>
</p><br>
<p>
<ul style="font-weight:bold;line-height:30px;padding:0 0 0 90px;text-align:left;">
<li>There is a discount while holding grand events, ordering banquets and stand-up parties.
</li>
<li>At weddings: decoration with balloons, live tropical butterflies, traditional Chinese lights!
</li>
<li>Free food delivery to Voroshylovskiy district!
</li>
<li>Discounts 5%, 10%!
</li>
<li>Business lunch – 11:00-16:00
</li>
</ul>
</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;“Seoul” Restaurant is very convenient for holding banquets, stand-up parties, weddings, birthday parties, different meetings, business meals and negotiations.
</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;The main hall has 40 seats, VIP has 10 seats. And there is a separate VIP-room for confidential conversations or lovers, who want to have a romantic evening.
</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;In the main hall, designed in soft malachite colors, the records of national variety songs, concerts, and football matches are shown. The live music is played in the evening. There are plasma screens in the banquet halls and a real fire-place brings a feeling of comfort and warmth. Delicate sakura branches supplement the restaurant atmosphere.
</p>
<br>
<br>
<img src="root/seul/i_slogan.png" alt="" />
<img src="root/seul/uzor.png" alt="" />
</div>
</div>
<?php
}
else
   if ($_GET['pm'] == 2)
   {
?>
<div class="catalogue_item_cont"> 
<img src="root/seul/i_up.png" alt="" style="width: 100%;" />
<div id="div_st" style="padding:0 145px;height:11730px;">
<p>
<a href="index.php?business_full=394&amp;pm=1" style="font-size:16px;left:140px;position:relative;top:-40px;float:left;color:#f0ef95;"><i><b>Restaurant</b></i></a>
<a href="index.php?business_full=394&amp;pm=2" style="font-size:16px;left:190px;position:relative;top:-40px;;float:left;color:#f0ef95;"><i><b>Menu</b></i></a>
<a href="index.php?business_full=394&amp;pm=3" style="font-size:16px;left:240px;position:relative;top:-40px;float:left;color:#f0ef95;"><i><b>Contacts</b></i></a>
</p>
<br>
<table style="width:750px;" id="i_table">
    <tr><td colspan="3" id="i_up" style="font-size:16px;">Korean Cuisine<br></td></tr>    
    <tr><td colspan="3" id="i_up1">- SALADS -</td></tr>
<tr>
        <td id="i_first"></td>
        <td id="i_second">Weight</td>
        <td id="i_second">Price, UAH</td>
    </tr>
    <tr>
        <td id="i_first">CALAMARI<br><img src="root/seul/menu/1.jpg" width="130" height="80"></td>
        <td id="i_second">150/50</td>
        <td id="i_second">56-00</td>
    </tr>
        <tr>
        <td id="i_first">YUKHI<br>(VEAL IN SOY SAUCE)<br><img src="root/seul/menu/2.jpg" width="130" height="80"></td>
        <td id="i_second">150/50</td>
        <td id="i_second">48-00</td>
    </tr>
    <tr>
        <td id="i_first">HOE OF BLUE BREAM<br>(A PIQUANT TASTE OF MARINATED FISH)<br><img src="root/seul/menu/3.jpg" width="130" height="80"></td>
        <td id="i_second">150/50</td>
        <td id="i_second">45-00</td>
    </tr>
        <tr>
        <td id="i_first">VECHO<br>(A TASTE OF STEWED CUCUMBER WITH VEAL)<br><img src="root/seul/menu/4.jpg" width="130" height="80"></td>
        <td id="i_second">200/50</td>
        <td id="i_second">46-00</td>
    </tr>
    <tr>
        <td id="i_first">JAPANESE SALAD<br>(A COMBINATION OF VEGETABLES 
WITH A DELICATE SWEET-SOUR TASTE)<br><img src="root/seul/menu/5.jpg" width="130" height="80"></td>
        <td id="i_second">250/50</td>
        <td id="i_second">35-00</td>
    </tr>
    <tr>
        <td id="i_first">BEAR’S ONION<br><img src="root/seul/menu/6.jpg" width="130" height="80"></td>
        <td id="i_second">200</td>
        <td id="i_second">35-00</td>
    </tr>
    <tr>
        <td id="i_first">FAR EAST AGARIC HONEY<br><img src="root/seul/menu/7.jpg" width="130" height="80"></td>
        <td id="i_second">150</td>
        <td id="i_second">48-00</td>
    </tr>
    <tr>
        <td id="i_first">ASPARAGUS<br>(A PULSE PLANT BRINGS A TASTE 
OF SAPPY CHICKEN FILLET)<br><img src="root/seul/menu/8.jpg" width="130" height="80"></td>
        <td id="i_second">150</td>
        <td id="i_second">38-00</td>
    </tr>
    <tr>
        <td id="i_first">ROYAL SEA MUSHROOM<br><img src="root/seul/menu/9.jpg" width="130" height="80"></td>
        <td id="i_second">150</td>
        <td id="i_second">38-00</td>
    </tr>
    <tr><td colspan="3" id="i_up1">- MEAT DISH -</td></tr>
    <tr>
        <td id="i_first">SEOUL MEAT<br>(PORK, RISE WITH GREEN PEAS)<br><img src="root/seul/menu/10.jpg" width="130" height="80"></td>
        <td id="i_second">150/100</td>
        <td id="i_second">87-00</td>
    </tr>
    <tr>
        <td id="i_first">PUL-KOHI<br>(VEAL, NAPA CABBAGE WITH VEGETABLES)<br><img src="root/seul/menu/11.jpg" width="130" height="80"></td>
        <td id="i_second">150/150</td>
        <td id="i_second">85-00</td>
    </tr>
    <tr>
        <td id="i_first">TAL KOHI-KHE<br>(CHICKEN WINGS)<br><img src="root/seul/menu/12.jpg" width="130" height="80"></td>
        <td id="i_second">250/60</td>
        <td id="i_second">68-00</td>
    </tr>
    <tr>
        <td id="i_first">KITYL-KOHI<br>(RISE, PORK EARS)<br><img src="root/seul/menu/13.jpg" width="130" height="80"></td>
        <td id="i_second">150/100</td>
        <td id="i_second">58-00</td>
    </tr>
    <tr>
        <td id="i_first">NEM STICK<br>(PORK FORCEMEAT, SCALLOP, FUNCHESA, RISE LEAVES)<br><img src="root/seul/menu/14.jpg" width="130" height="80"></td>
        <td id="i_second">150/50</td>
        <td id="i_second">55-00</td>
    </tr>
    <tr>
        <td id="i_first">DEEP-FRIED DUMPLINGS<br>(PORK FORCEMEAT, PUFF PASTE)<br><img src="root/seul/menu/15.jpg" width="130" height="80"></td>
        <td id="i_second">200/4 PC</td>
        <td id="i_second">72-00</td>
    </tr>
    <tr>
        <td id="i_first">SYAMI<br>(BOILED VEAL, FRIED EGG, RISE, POKUMI, SOY-BEAN PASTE)<br><img src="root/seul/menu/16.jpg" width="130" height="80"></td>
        <td id="i_second">340/100/50</td>
        <td id="i_second">140-00</td>
    </tr>
<tr>
        <td id="i_first">FUNCHOSA<br>(RISE NOODLES, VEAL, CUCUMBER)<br><img src="root/seul/menu/17.jpg" width="130" height="80"></td>
        <td id="i_second">150/100</td>
        <td id="i_second">55-00</td>
    </tr>
<tr>
        <td id="i_first">EAST MUTTON IN NAKHAT SAUCE<br><img src="root/seul/menu/21.jpg" width="130" height="80"></td>
        <td id="i_second">250/100</td>
        <td id="i_second">185-00</td>
    </tr>
<tr>
        <td id="i_first">BOILED PORK WITH SOY-BEAN SAUCE<br><img src="root/seul/menu/22.jpg" width="130" height="80"></td>
        <td id="i_second">250/250</td>
        <td id="i_second">123-00</td>
    </tr>
<tr><td colspan="3" id="i_up1">- FISH. SEAFOOD -</td></tr>
<tr>
        <td id="i_first">SALMON IN A SESAME SAUCE<br><img src="root/seul/menu/29.jpg" width="130" height="80"></td>
        <td id="i_second">200/100</td>
        <td id="i_second">125-00</td>
    </tr>
<tr>
        <td id="i_first">SHRIMPS IN A TEMPURA BATTER<br><img src="root/seul/menu/30.jpg" width="130" height="80"></td>
        <td id="i_second">100/25/25</td>
        <td id="i_second">68-00</td>
    </tr>
<tr>
        <td id="i_first">TROUT IN A SWEET-SOUR SAUCE<br><img src="root/seul/menu/31.jpg" width="130" height="80"></td>
        <td id="i_second">450/150/50</td>
        <td id="i_second">117-00</td>
    </tr>
<tr>
        <td id="i_first">SEOUL CARP<br><img src="root/seul/menu/32.jpg" width="130" height="80"></td>
        <td id="i_second">600/100</td>
        <td id="i_second">150-00</td>
    </tr>
<tr>
        <td id="i_first">STURGEON FLESH IN A SOY SAUCE<br><img src="root/seul/menu/33.jpg" width="130" height="80"></td>
        <td id="i_second">200/150</td>
        <td id="i_second">105-00</td>
    </tr>
<tr><td colspan="3" id="i_up1">- SOUPS -</td></tr>
<tr>
        <td id="i_first">TYBY-TYAY WITH RISE<br>(PRESSED SOY-BEANS, RISE, VEAL, SOY-BEAN PASTE)<br><img src="root/seul/menu/34.jpg" width="130" height="80"></td>
        <td id="i_second">300/100</td>
        <td id="i_second">52-00</td>
    </tr>
<tr>
        <td id="i_first">KUK-SU<br>(BEEF/SOY BROTH, NOODLES POKUMI)<br><img src="root/seul/menu/35.jpg" width="130" height="80"></td>
        <td id="i_second">200/300</td>
        <td id="i_second">65-00</td>
    </tr>
<tr>
        <td id="i_first">KYAD-ZHAN<br>(VEAL, BROTH, GREEN VEGETABLES, KOCHI-TERIMI, RISE)<br><img src="root/seul/menu/36.jpg" width="130" height="80"></td>
        <td id="i_second">200/50/50</td>
        <td id="i_second">48-00</td>
    </tr>
<tr>
        <td id="i_first">TINHAY<br>(SMOKED SALMON, LAMINARIA, POTATOES,
 GREEN VEGETABLES, RISE)<br><img src="root/seul/menu/37.jpg" width="130" height="80"></td>
        <td id="i_second">350</td>
        <td id="i_second">55-00</td>
    </tr>
<tr><td colspan="3" id="i_up"  style="font-size:16px;"><br><br><br><br><br><br><br><br><br>Japanese Cuisine<br></td></tr>
<tr><td colspan="3" id="i_up1">- SHIP -</td></tr>
<tr>
        <td id="i_first">HESSEN «SEOUL»<br><img src="root/seul/menu/38.jpg" width="130" height="80"></td>
        <td id="i_second">725/50/100</td>
        <td id="i_second">405-00</td>
    </tr>
<tr><td colspan="3" id="i_up1">- ASSORTMENT -</td></tr>
<tr>
        <td id="i_first">UME<br>(SALMON, TUNA, PERCH, 
TIGER SHRIMP, CALAMARI, 
SCALLOP)<br><img src="root/seul/menu/39.jpg" width="130" height="80"></td>
        <td id="i_second">210/40/50</td>
        <td id="i_second">78-00</td>
    </tr>
<tr>
        <td id="i_first">TAKE<br>(SALMON, TUNA, PERCH, 
TIGER SHRIMP, OCTOPUS.
SWEET SHRIMP, RUDDERFISH, 
MOLLUSK, CALAMARI, SCALLOP)<br><img src="root/seul/menu/40.jpg" width="130" height="80"></td>
        <td id="i_second">350/60/50</td>
        <td id="i_second">118-00</td>
    </tr>
<tr><td colspan="3" id="i_up1">- SUSHI -</td></tr>
<tr>
        <td id="i_first">MAHURO<br>(TUNA)<br><img src="root/seul/menu/41.jpg" width="130" height="80"></td>
        <td id="i_second">35/45/50</td>
        <td id="i_second">17-00</td>
    </tr>
<tr>
        <td id="i_first">TAY<br>(PERCH)<br><img src="root/seul/menu/42.jpg" width="130" height="80"></td>
        <td id="i_second">35/45/50</td>
        <td id="i_second">12-00</td>
    </tr>
<tr>
        <td id="i_first">SHAKE<br>(SALMON)<br><img src="root/seul/menu/43.jpg" width="130" height="80"></td>
        <td id="i_second">35/45/50</td>
        <td id="i_second">14-00</td>
    </tr>
<tr>
        <td id="i_first">UNAHI<br>(EEL)<br><img src="root/seul/menu/44.jpg" width="130" height="80"></td>
        <td id="i_second">35/45/50</td>
        <td id="i_second">15-00</td>
    </tr>
<tr>
        <td id="i_first">KHAMACHI<br>(RUDDERFISH)<br><img src="root/seul/menu/45.jpg" width="130" height="80"></td>
        <td id="i_second">35/45/50</td>
        <td id="i_second">16-00</td>
    </tr>
<tr>
        <td id="i_first">KHOHIKAY<br>(MOLLUSK)<br><img src="root/seul/menu/46.jpg" width="130" height="80"></td>
        <td id="i_second">35/45/50</td>
        <td id="i_second">18-00</td>
    </tr>
<tr>
        <td id="i_first">IKA<br>(CALAMARI)<br><img src="root/seul/menu/47.jpg" width="130" height="80"></td>
        <td id="i_second">35/45/50</td>
        <td id="i_second">13-00</td>
    </tr>
<tr>
        <td id="i_first">EBI<br>(TIGER SHRIMP)<br><img src="root/seul/menu/48.jpg" width="130" height="80"></td>
        <td id="i_second">35/45/50</td>
        <td id="i_second">15-00</td>
    </tr>
<tr>
        <td id="i_first">АМА-EBI<br>(SWEET SHRIMP)<br><img src="root/seul/menu/49.jpg" width="130" height="80"></td>
        <td id="i_second">35/45/50</td>
        <td id="i_second">15-00</td>
    </tr>
<tr>
        <td id="i_first">KHOTATE<br>(SEA SCALLOP)<br><img src="root/seul/menu/50.jpg" width="130" height="80"></td>
        <td id="i_second">35/45/50</td>
        <td id="i_second">15-00</td>
    </tr>
<tr>
        <td id="i_first">TAKO</td>
        <td id="i_second">35/45/50</td>
        <td id="i_second">16-00</td>
    </tr>
<tr>
        <td id="i_first">KHOTATE<br>(FELIX)</td>
        <td id="i_second">35/45/50</td>
        <td id="i_second">20-00</td>
    </tr>
<tr>
        <td id="i_first">KANI<br>(CRAB)</td>
        <td id="i_second">35/45/50</td>
        <td id="i_second">28-00</td>
    </tr>
<tr>
        <td id="i_first">IKURA<br>(RED CAVIAR)</td>
        <td id="i_second">35/45/50</td>
        <td id="i_second">22-00</td>
    </tr>
<tr>
        <td id="i_first">TOBIKO<br>(FLYING FISH CAVIAR)</td>
        <td id="i_second">35/45/50</td>
        <td id="i_second">20-00</td>
    </tr>
<tr><td colspan="3" id="i_up1">- SASHIMI -</td></tr>
<tr>
        <td id="i_first">MAHURO<br>(TUNA)<br>(OCTOPUS)<br><img src="root/seul/menu/51.jpg" width="130" height="80"></td>
        <td id="i_second">50/105/50</td>
        <td id="i_second">47-00</td>
    </tr>
<tr>
        <td id="i_first">SHAKE<br>(SALMON)</td>
        <td id="i_second">50/105/50</td>
        <td id="i_second">37-00</td>
    </tr>
<tr>
        <td id="i_first">IKA<br>(CALAMARI)</td>
        <td id="i_second">50/106/50</td>
        <td id="i_second">37-00</td>
    </tr>
<tr>
        <td id="i_first">TAY<br>(PERCH)</td>
        <td id="i_second">50/105/50</td>
        <td id="i_second">36-00</td>
    </tr>
<tr>
        <td id="i_first">KHOTATE<br>(SEA SCALLOP)</td>
        <td id="i_second">50/105/50</td>
        <td id="i_second">42-00</td>
    </tr>
<tr>
        <td id="i_first">EBI<br>(TIGER SHRIMP)</td>
        <td id="i_second">50/105/50</td>
        <td id="i_second">47-00</td>
    </tr>
<tr>
        <td id="i_first">АМА-EBI<br>(SWEET SHRIMP)</td>
        <td id="i_second">50/105/50</td>
        <td id="i_second">47-00</td>
    </tr>
<tr>
        <td id="i_first">TAKO<br>(OCTOPUS)</td>
        <td id="i_second">50/110/50</td>
        <td id="i_second">45-00</td>
    </tr>
<tr>
        <td id="i_first">UNAHI<br>(EEL)</td>
        <td id="i_second">50/112/50</td>
        <td id="i_second">42-00</td>
    </tr>
<tr>
        <td id="i_first">KHOHIKAY<br>(MOLLUSK)</td>
        <td id="i_second">50/105/50</td>
        <td id="i_second">47-00</td>
    </tr>
<tr>
        <td id="i_first">KANI<br>(CRAB)</td>
        <td id="i_second">50/105/50</td>
        <td id="i_second">105-00</td>
    </tr>
<tr>
        <td id="i_first">KHAMACHI<br>(RUDDERFISH)</td>
        <td id="i_second">50/150/50</td>
        <td id="i_second">47-00</td>
    </tr>
<tr>
        <td id="i_first">IKURA<br>(RED CAVIAR)</td>
        <td id="i_second">45/45/50</td>
        <td id="i_second">65-00</td>
    </tr>
<tr>
        <td id="i_first">TOBIKO<br>(FLYING FISH CAVIAR)</td>
        <td id="i_second">45/45/50</td>
        <td id="i_second">60-00</td>
    </tr>
<tr><td colspan="3" id="i_up1">- CALIFORNIA -</td></tr>
<tr><td colspan="3" id="i_up">IN CAVIAR WITH A CUCUMBER:</td></tr>
<tr>
        <td id="i_first">TUNA<br>(OCTOPUS)<br><img src="root/seul/menu/52.jpg" width="130" height="80"></td>
        <td id="i_second">180</td>
        <td id="i_second">60-00</td>
    </tr>
<tr>
        <td id="i_first">SALMON<br><img src="root/seul/menu/52.jpg" width="130" height="80"></td>
        <td id="i_second">180</td>
        <td id="i_second">55-00</td>
    </tr>
<tr>
        <td id="i_first">EEL<br><img src="root/seul/menu/52.jpg" width="130" height="80"></td>
        <td id="i_second">180</td>
        <td id="i_second">58-00</td>
    </tr>
<tr>
        <td id="i_first">CRAB<br><img src="root/seul/menu/52.jpg" width="130" height="80"></td>
        <td id="i_second">180</td>
        <td id="i_second">76-00</td>
    </tr>
<tr><td colspan="3" id="i_up">IN SESAME WITH A CUCUMBER:</td></tr>
<tr>
        <td id="i_first">TUNA</td>
        <td id="i_second">180180</td>
        <td id="i_second">52-00</td>
    </tr>
<tr>
        <td id="i_first">SALMON</td>
        <td id="i_second">180</td>
        <td id="i_second">42-00</td>
    </tr>
<tr>
        <td id="i_first">EEL</td>
        <td id="i_second">180</td>
        <td id="i_second">46-00</td>
    </tr>
<tr>
        <td id="i_first">CRAB</td>
        <td id="i_second">180</td>
        <td id="i_second">74-00</td>
    </tr>
<tr><td colspan="3" id="i_up1">- HOLIDAY ROLLS -</td></tr>
<tr>
        <td id="i_first">KUNASHIR<br>(CRAB, TOBIKA, AVOCADO,
COVERED WITH SALMON, SALMON CAVIAR)<br><img src="root/seul/menu/53.jpg" width="130" height="80"></td>
        <td id="i_second">190/30/50</td>
        <td id="i_second">74-00</td>
    </tr>
<tr>
        <td id="i_first">HAWAIIAN<br>(TUNA, CHEESE, LOLA-ROSSA, 
MAYONNAISE SAUCE)<br><img src="root/seul/menu/54.jpg" width="130" height="80"></td>
        <td id="i_second">200-30-50</td>
        <td id="i_second">73-00</td>
    </tr>
<tr>
        <td id="i_first">KHANABI<br><img src="root/seul/menu/55.jpg" width="130" height="80"></td>
        <td id="i_second">175/30/50</td>
        <td id="i_second">64-00</td>
    </tr>
<tr>
        <td id="i_first">FUTO MAKI<br><img src="root/seul/menu/68.jpg" width="130" height="80"></td>
        <td id="i_second">200</td>
        <td id="i_second">68-00</td>
    </tr>
<tr>
        <td id="i_first">SHAKE<br><img src="root/seul/menu/69.jpg" width="130" height="80"></td>
        <td id="i_second">200</td>
        <td id="i_second">67-00</td>
    </tr>
<tr>
        <td id="i_first">GOLDEN DRAGON<br><img src="root/seul/menu/70.jpg" width="130" height="80"></td>
        <td id="i_second">220</td>
        <td id="i_second">65-00</td>
    </tr>
<tr>
        <td id="i_first">FELIX MIX<br><img src="root/seul/menu/74.jpg" width="130" height="80"></td>
        <td id="i_second">200</td>
        <td id="i_second">52-00</td>
    </tr>
<tr>
        <td id="i_first">ROLL WITH EEL<br><img src="root/seul/menu/75.jpg" width="130" height="80"></td>
        <td id="i_second">220</td>
        <td id="i_second">64-00</td>
    </tr>
<tr>
        <td id="i_first">BLACK SAMURAI<br><img src="root/seul/menu/76.jpg" width="130" height="80"></td>
        <td id="i_second">220</td>
        <td id="i_second">74-00</td>
    </tr>
<tr>
        <td id="i_first">RED DRAGON<br>(TIGER SHRIMP, 
GREEN TOBIKA, CUCUMBER, 
COVERED WITH SALMON)<br><img src="root/seul/menu/56.jpg" width="130" height="80"></td>
        <td id="i_second">200/30/50</td>
        <td id="i_second">74-00</td>
    </tr>
<tr>
        <td id="i_first">GREEN DRAGON<br>(EEL, TOBIKA, COVERED WITH AVOCADO)<br><img src="root/seul/menu/57.jpg" width="130" height="80"></td>
        <td id="i_second">200/30/50</td>
        <td id="i_second">85-00</td>
    </tr>
<tr>
        <td id="i_first">AMA-EBI<br><img src="root/seul/menu/58.jpg" width="130" height="80"></td>
        <td id="i_second">200/30/50</td>
        <td id="i_second">105-00</td>
    </tr>
<tr>
        <td id="i_first">BALTIMORE<br>(CRAB, AVOCADO,
TOBICA, LIME, COVERED WITH SALMON)<br><img src="root/seul/menu/59.jpg" width="130" height="80"></td>
        <td id="i_second">245/30/50</td>
        <td id="i_second">91-00</td>
    </tr>
<tr>
        <td id="i_first">NINJA<br>(CRAB, CUCUMBER, TOBIKA, SALMON, TUNA.
COVERED WITH AVOCADO)<br><img src="root/seul/menu/60.jpg" width="130" height="80"></td>
        <td id="i_second">240/30/50</td>
        <td id="i_second">92-00</td>
    </tr>
<tr>
        <td id="i_first">HONSHU<br><img src="root/seul/menu/61.jpg" width="130" height="80"></td>
        <td id="i_second">220/30/50</td>
        <td id="i_second">84-00</td>
    </tr>
<tr>
        <td id="i_first">PHILADELPHIA<br>(CRAB, SALMON, CHEESE, 
AVOCADO, TOBIKA)<br><img src="root/seul/menu/62.jpg" width="130" height="80"></td>
        <td id="i_second">240/30/50</td>
        <td id="i_second">112-00</td>
    </tr>
<tr>
        <td id="i_first">MAHURA<br>(TUNA, SIVID,  
AVOCADO, CUCUMBER)<br><img src="root/seul/menu/63.jpg" width="130" height="80"></td>
        <td id="i_second">250/30/50</td>
        <td id="i_second">105-00</td>
    </tr>
<tr>
        <td id="i_first">UNAHI<br><img src="root/seul/menu/64.jpg" width="130" height="80"></td>
        <td id="i_second">215/30/50</td>
        <td id="i_second">98-00</td>
    </tr>
<tr>
        <td id="i_first">«SEOUL»<br>(CRAB, EEL, TOBIKA,
AVOCADO, MAYONNAISE SAUCE)<br><img src="root/seul/menu/65.jpg" width="130" height="80"></td>
        <td id="i_second">300/30/50</td>
        <td id="i_second">122-00</td>
    </tr>
<tr>
        <td id="i_first">LOS-ANGELES<br>(EEL, SALMON, LOLA-ROSSA,
PINEAPPLE, CHEESE)<br><img src="root/seul/menu/66.jpg" width="130" height="80"></td>
        <td id="i_second">255/30/50</td>
        <td id="i_second">112-00</td>
    </tr>
<tr>
        <td id="i_first">RAINBOW<br>(TUNE, RUDDERFISH, PERCH,
SALMON, FLYING FISH CAVIAR, CUCUMBER)<br><img src="root/seul/menu/67.jpg" width="130" height="80"></td>
        <td id="i_second">230/30/50</td>
        <td id="i_second">117-00</td>
    </tr>
<tr><td colspan="3" id="i_up1">- VEGETARIAN MENU -</td></tr>
<tr>
        <td id="i_first">SEOUL<br>(PEPPER, CARROT, AVOCADO,
CUCUMBER, COVERED WITH FRIED 
AUBERGINE)<br><img src="root/seul/menu/71.jpg" width="130" height="80"></td>
        <td id="i_second">200/30/50</td>
        <td id="i_second">42-00</td>
    </tr>
<tr>
        <td id="i_first">VEGETABLE DRAGON<br>(PEPPER, CARROT, CUCUMBER.
COVERED WITH AVOCADO)<br><img src="root/seul/menu/72.jpg" width="130" height="80"></td>
        <td id="i_second">230/30/50</td>
        <td id="i_second">42-00</td>
    </tr>
<tr>
        <td id="i_first">SPRING<br><img src="root/seul/menu/73.jpg" width="130" height="80"></td>
        <td id="i_second">200/30/50</td>
        <td id="i_second">22-00</td>
    </tr>
<tr>
        <td id="i_first">GREEN<br>(PEPPER, CARROT,
CUCUMBER, COVERED WITH DILL)</td>
        <td id="i_second">200/30/50</td>
        <td id="i_second">22-00</td>
    </tr>
<tr>
        <td id="i_first">AVOCADO</td>
        <td id="i_second">35/45/50</td>
        <td id="i_second">8-00</td>
    </tr>
<tr>
        <td id="i_first">MELON</td>
        <td id="i_second">35/35/50</td>
        <td id="i_second">8-00</td>
    </tr>
<tr>
        <td id="i_first">SIVID</td>
        <td id="i_second">35/35/50</td>
        <td id="i_second">8-00</td>
    </tr>
<tr>
        <td id="i_first">SHIITAKE</td>
        <td id="i_second">35/35/50</td>
        <td id="i_second">8-00</td>
    </tr>
<tr><td colspan="3" id="i_up1">- SALADS -</td></tr>
<tr>
        <td id="i_first">SPICE MAHURO<br><img src="root/seul/menu/77.jpg" width="130" height="80"></td>
        <td id="i_second">100/20</td>
        <td id="i_second">70-00</td>
    </tr>
<tr>
        <td id="i_first">SARADO TAKO BABI<br><img src="root/seul/menu/78.jpg" width="130" height="80"></td>
        <td id="i_second">100/20</td>
        <td id="i_second">68-00</td>
    </tr>
<tr>
        <td id="i_first">SARADO IKA<br><img src="root/seul/menu/79.jpg" width="130" height="80"></td>
        <td id="i_second">100/20</td>
        <td id="i_second">57-00</td>
    </tr>
<tr>
        <td id="i_first">SIVID<br><img src="root/seul/menu/80.jpg" width="130" height="80"></td>
        <td id="i_second">100/20/50</td>
        <td id="i_second">46-00</td>
    </tr>
<tr>
        <td id="i_first">VAKAMI<br><img src="root/seul/menu/81.jpg" width="130" height="80"></td>
        <td id="i_second">100/50</td>
        <td id="i_second">36-00</td>
    </tr>
<tr><td colspan="3" id="i_up1">- SOUPS -</td></tr>
<tr>
        <td id="i_first">TRADITIONAL MISSO</td>
        <td id="i_second">230</td>
        <td id="i_second">28-00</td>
    </tr>
<tr>
        <td id="i_first">MISSO-UNAHI (EEL)</td>
        <td id="i_second">220/24</td>
        <td id="i_second">3-00</td>
    </tr>
<tr>
        <td id="i_first">MISSO-KANI (CRAB)</td>
        <td id="i_second">220/20</td>
        <td id="i_second">62-00</td>
    </tr>
<tr><td colspan="3" id="i_up1">- HOT DISHES -</td></tr>
<tr>
        <td id="i_first">FRIED RISE WITH VEGETABLES</td>
        <td id="i_second">150</td>
        <td id="i_second">39-00</td>
    </tr>
<tr>
        <td id="i_first">FRIED RISE WITH SEAFOOD</td>
        <td id="i_second">150</td>
        <td id="i_second">59-00</td>
    </tr>
<tr>
        <td id="i_first">BUCKWHEAT NOODLES UDON<br><img src="root/seul/menu/82.jpg" width="130" height="80"></td>
        <td id="i_second">100/150/50</td>
        <td id="i_second">66-00</td>
    </tr>
<tr><td colspan="3" id="i_up1">- SHASHLYK -</td></tr>
<tr>
        <td id="i_first">TUNA<br><img src="root/seul/menu/83.jpg" width="130" height="80"></td>
        <td id="i_second">50/25/50</td>
        <td id="i_second">65-00</td>
    </tr>
<tr>
        <td id="i_first">CHICKEN FILLET</td>
        <td id="i_second">50/25/50</td>
        <td id="i_second">48-00</td>
    </tr>
<tr>
        <td id="i_first">CHICKEN HEART</td>
        <td id="i_second">50/25/50</td>
        <td id="i_second">42-00</td>
    </tr>
<tr>
        <td id="i_first">TIGER SHRIMP</td>
        <td id="i_second">50/25/50</td>
        <td id="i_second">56-00</td>
    </tr>
<tr><td colspan="3" id="i_up1">- KHOSSOMAKI -</td></tr>
<tr>
        <td id="i_first">SHAKE<br>(SALMON)<br>(ЛОСОСЬ)<br><img src="root/seul/menu/84.jpg" width="130" height="80"></td>
        <td id="i_second">105/25/50</td>
        <td id="i_second">32-00</td>
    </tr>
<tr>
        <td id="i_first">UNAHI<br>(EEL)</td>
        <td id="i_second">105/25/50</td>
        <td id="i_second">38-00</td>
    </tr>
<tr>
        <td id="i_first">MAHURO<br>(TUNA)</td>
        <td id="i_second">105/25/50</td>
        <td id="i_second">42-00</td>
    </tr>
<tr>
        <td id="i_first">KHOTATE<br>(SEA SCALLOP)</td>
        <td id="i_second">105/25/50</td>
        <td id="i_second">40-00</td>
    </tr>
<tr>
        <td id="i_first">KANI<br>(CRAB)</td>
        <td id="i_second">105/25/50</td>
        <td id="i_second">47-00</td>
    </tr>
<tr>
        <td id="i_first">AVOCADO</td>
        <td id="i_second">105/25/50</td>
        <td id="i_second">28-00</td>
    </tr>
<tr>
        <td id="i_first">CUCUMBER</td>
        <td id="i_second">105/25/50</td>
        <td id="i_second">22-00</td>
    </tr>
<tr><td colspan="3" id="i_up1">- TEMAKI -</td></tr>
<tr>
        <td id="i_first">SHAKE (SALMON)<br><img src="root/seul/menu/85.jpg" width="130" height="80"></td>
        <td id="i_second">90/25/50</td>
        <td id="i_second">37-00</td>
    </tr>
<tr>
        <td id="i_first">UNAHI (EEL)</td>
        <td id="i_second">90/25/50</td>
        <td id="i_second">39-00</td>
    </tr>
<tr>
        <td id="i_first">MAHURO (TUNA)</td>
        <td id="i_second">90/25/50</td>
        <td id="i_second">42-00</td>
    </tr>
<tr>
        <td id="i_first">EBI (TIGER SHRIMP)</td>
        <td id="i_second">90/25/50</td>
        <td id="i_second">40-00</td>
    </tr>
<tr>
        <td id="i_first">SPICE KHOTATE (SCALLOP)</td>
        <td id="i_second">90/25/50</td>
        <td id="i_second">44-00</td>
    </tr>
<tr>
        <td id="i_first">SHIP<br><img src="root/seul/menu/86.jpg" width="130" height="80"></td>
        <td id="i_second">390</td>
        <td id="i_second">88-00</td>
    </tr>
<tr>
        <td id="i_first">SHIP</td>
        <td id="i_second">550</td>
        <td id="i_second">76-00</td>
    </tr>
<tr>
        <td id="i_first">SET<br><img src="root/seul/menu/87.jpg" width="130" height="80"></td>
        <td id="i_second">250</td>
        <td id="i_second">64-00</td>
    </tr>
<tr><td colspan="3" id="i_up1">- SET-MEAL -</td></tr>
<tr>
        <td id="i_first">SET-MEAL<br><img src="root/seul/menu/88.jpg" width="130" height="80"></td>
        <td id="i_second"></td>
        <td id="i_second">63-00</td>
    </tr>
<tr>
        <td id="i_first">TYBY-TAY<br>DUMMPLINGS<br>VECHO SALAD</td>
        <td id="i_second"></td>
        <td id="i_second">52-00</td>
    </tr>
<tr>
        <td id="i_first">SEA SOUP<br>JAPANESE SALSD<br>NEM STICKS</td>
        <td id="i_second"></td>
        <td id="i_second">54-00</td>
    </tr>
<tr><td colspan="3" id="i_up1">- DESSERTS -</td></tr>
<tr>
        <td id="i_first">FRUITS ROLL<br>(PINEAPPLE, STRAWBERRY, KIWI,
BANANAS, APPLE)<br><img src="root/seul/menu/89.jpg" width="130" height="80"></td>
        <td id="i_second">270/50</td>
        <td id="i_second">78-00</td>
    </tr>
<tr>
        <td id="i_first">BANANAS IN TEMPURA SOFT DOUGH<br><img src="root/seul/menu/90.jpg" width="130" height="80"></td>
        <td id="i_second">200/100</td>
        <td id="i_second">42-00</td>
    </tr>
<tr>
        <td id="i_first">CHEESE IN TEMPURA BATTER<br><img src="root/seul/menu/91.jpg" width="130" height="80"></td>
        <td id="i_second">150/50</td>
        <td id="i_second">65-00</td>
    </tr>
</table>
</div>
</div>
<?php
}
else
   if ($_GET['pm'] == 3)
   {
?>

   <div class="catalogue_item_cont"> 
<img src="root/seul/i_up.png" alt="" style="width: 100%;" />
<div id="div_st" style="padding:0 145px;height:400px;">
<p>
<a href="index.php?business_full=394&amp;pm=1" style="font-size:16px;left:140px;position:relative;top:-40px;float:left;color:#f0ef95;"><i><b>Restaurant</b></i></a>
<a href="index.php?business_full=394&amp;pm=2" style="font-size:16px;left:190px;position:relative;top:-40px;;float:left;color:#f0ef95;"><i><b>Menu</b></i></a>
<a href="index.php?business_full=394&amp;pm=3" style="font-size:16px;left:240px;position:relative;top:-40px;float:left;color:#f0ef95;"><i><b>Contacts</b></i></a>
</p>
<br>
        <script src="http://api-maps.yandex.ru/1.1/index.xml?key=AAmDzUsBAAAARkVWCAIAXzMCgKN58_MQUqB134Sdp-unCH0AAAAAAAAAAACbJlz2mcKc4anRgbxx6LBZ5BHPyg==" type="text/javascript"></script>
    <script type="text/javascript">
        window.onload = function () {
            var map = new YMaps.Map(document.getElementById("YMapsID"));
            map.setCenter(new YMaps.GeoPoint(37.804821,48.006259), 14);

            var content = document.createElement('span');
            content.innerHTML = "«Seoul»";
            map.openBalloon(new YMaps.GeoPoint(37.804821,48.006259), content);

            map.addControl(new YMaps.ToolBar());
            map.addControl(new YMaps.Zoom());
            map.addControl(new YMaps.MiniMap());
            map.addControl(new YMaps.ScaleLine());
        }
    </script>


	 <div id="YMapsID" style="width:100%;height:450px"></div>
   </div>
</div>
<?php
   } 
?>



<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="">Категория:</a></div>
</div>
<div class="catalogue_item_cont">
<a href="index.php?section_id=616&amp;business=1">companies</a>
 / 
<a href="index.php?section_id=619&amp;business=2">rest</a>
 / 
<a href="index.php?section_id=622&amp;business=2">cafe</a>
</div>


<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="">Фотогалерея:</a></div>
</div>
<div class="catalogue_item_cont">
<div class="catalogue_pic_l"><a href="root/seul/gallery/1.jpg" target="_blank"><img src="root/seul/gallery/1_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/seul/gallery/2.jpg" target="_blank"><img src="root/seul/gallery/2_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/seul/gallery/3.jpg" target="_blank"><img src="root/seul/gallery/3_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/seul/gallery/4.jpg" target="_blank"><img src="root/seul/gallery/4_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/seul/gallery/5.jpg" target="_blank"><img src="root/seul/gallery/5_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/seul/gallery/6.jpg" target="_blank"><img src="root/seul/gallery/6_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/seul/gallery/7.jpg" target="_blank"><img src="root/seul/gallery/7_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/seul/gallery/8.jpg" target="_blank"><img src="root/seul/gallery/8_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/seul/gallery/9.jpg" target="_blank"><img src="root/seul/gallery/9_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/seul/gallery/10.jpg" target="_blank"><img src="root/seul/gallery/10_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/seul/gallery/11.jpg" target="_blank"><img src="root/seul/gallery/11_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/seul/gallery/12.jpg" target="_blank"><img src="root/seul/gallery/12_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/seul/gallery/13.jpg" target="_blank"><img src="root/seul/gallery/13_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/seul/gallery/14.jpg" target="_blank"><img src="root/seul/gallery/14_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/seul/gallery/15.jpg" target="_blank"><img src="root/seul/gallery/15_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/seul/gallery/16.jpg" target="_blank"><img src="root/seul/gallery/16_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/seul/gallery/17.jpg" target="_blank"><img src="root/seul/gallery/17_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/seul/gallery/18.jpg" target="_blank"><img src="root/seul/gallery/18_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/seul/gallery/19.jpg" target="_blank"><img src="root/seul/gallery/19_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/seul/gallery/20.jpg" target="_blank"><img src="root/seul/gallery/20_s.jpg" width="60" height="60" border="0" alt=""></a></div>
</div>
<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="">Контактная информация:</div>
</div>
 <div class="catalogue_item_cont">
 		 <table width="100%">
			<tbody>
 			<tr>
			<!--	<td><img class="main_sec_image" src="" width="60" height="60" border="0" alt="" /></td>-->
				<td>Address:</td>
				<td>Phone:</td>
				<td>Fax:</td>
				<td>E-mail:</td>
				<td>WWW:</td>
			</tr>
			<tr>
				<td>Donetsk city<br> Artem street, 125</td>
				<td>(062) 304-33-60<br> 099-947-54-80</td>
				<td></td>
				<td></td>
				<td></td>

			</tr>
			</tbody> 
		 </table> 		
	 </div>
</div>  

