 <div class="catalogue_item_c">
<style>
.catalogue_item_cont p {
color:#F0EF95;
margin:10px;
text-align:justify;
text-indent:0px;
line-height:20px;
}
.catalogue_item_cont {
background-color:#b21d17;
border-top:1px solid lightgray;
margin:0 0 7px 4px;
width:99%;
color:#f0ef95;
}
.catalogue_item_c {
background-color:#FFFFFF;
}
img.main_sec_image {
padding:0px;
width:250px;
height:160px;
}
.catalogue_item_cont a {
color:#F0EF95;
}
.catalogue_item_cont a:hover {
color:#FFFFFF;
text-decoration:underline;
}
.catalogue_item_mp_a {
left:-3px;
position:relative;
}
#div_st {padding:0 85px;position:relative;top:-160px;height:770px;}

@media all and (-webkit-min-device-pixel-ratio:10000),
not all and (-webkit-min-device-pixel-ratio:0) {
 #div_st {height:807px;}
}
td#i_up {font-weight:bold;text-align:left;}
td#i_up1 {font-weight:bold;text-decoration:underline;}
td#i_first {width:450px;text-align:left;font-weight:bold;}
td#i_second {width:100px;font-weight:bold;}
table#i_table tr {height:35px;}
</style>
<?php
if ($_GET['pm'] == 1) 
{
?>

<div class="catalogue_item_cont"> 
<img src="root/seul/menu.png" alt="" style="width: 100%;" />
<div id="div_st">
<p>
<a href="index.php?business_full=393&amp;pm=1" style="font-size:16px;left:200px;position:relative;top:-40px;float:left;color:#f0ef95;"><i><b>Ресторан</b></i></a>
<a href="index.php?business_full=393&amp;pm=2" style="font-size:16px;left:250px;position:relative;top:-40px;;float:left;color:#f0ef95;"><i><b>Меню</b></i></a>
<a href="index.php?business_full=393&amp;pm=3" style="font-size:16px;left:300px;position:relative;top:-40px;float:left;color:#f0ef95;"><i><b>Контакты</b></i></a>
</p>
<br>
<p>&nbsp;&nbsp;&nbsp;&nbsp;<b>Ресторан «Сеул»</b> - один из первых ресторанов <b>японско-корейской кухни</b> в Донецке. В ресторане <b>работает семья</b>, которая чтит национальные традиции, и каждый посетитель здесь становится желанным гостем! В ресторане «Сеул» основными являются <b>японская и корейская</b> кухни. В банкетное меню по желанию включается <b>европейская и узбекская</b>.
</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;В Корее царит культ еды, корейская кухня сложнее и разнообразнее, рецепты построены на знании множества кулинарных секретов, позволяющих придавать восточный вкус обычным салатам из овощей, мясным и рыбным закускам. Поэтому приготовлению блюд в ресторане «Сеул» уделяется особое внимание и выполнены они <b>по национальным рецептам поваром-корейцем</b>. Выбор традиционных японских и корейских блюд дополнен фирменными десертами.</p>
<img class="main_sec_image" src="root/seul/e1.jpg" alt="" style="float: left;margin-left:20px;" /><img class="main_sec_image" src="root/seul/e2.jpg" alt="" style="float: left;" />
<img class="main_sec_image" src="root/seul/e3.jpg" alt="" style="float: left;" /><br><br>
<p style="margin-top: 170px;"><center><font style="text-decoration:underline;font-size:14px;font-weight:bold;">СПЕЦИАЛЬНЫЕ ПРЕДЛОЖЕНИЯ:</font></center>
</p><br>
<p>
<ul style="font-weight:bold;line-height:30px;padding:0 0 0 90px;text-align:left;">
<li>При проведении торжественных мероприятий, заказе банкета, фуршета – скидка от ресторана!
</li>
<li>На свадьбах: оформление воздушными шарами, живые тропические бабочки, небесные фонарики!
</li>
<li>Доставка еды по Ворошиловскому району бесплатно!
</li>
<li>Дисконт – 5%, 10%!
</li>
<li>Бизнес-ланчи – 11:00-16:00
</li>
</ul>
</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;Ресторан "Сеул" очень удобен для проведения банкетов, фуршетов, свадеб, дней рождений, различного рода мероприятий, а также деловых обедов и переговоров. Основной зал вмещает до 50 человек. Банкетный зал – до 40 человек, VIP – зал на 10 человек и предусмотрена отдельная VIP – комната – для конфиденциальных переговоров или  влюбленных, желающих провести романтический вечер
</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;В основном зале, выполненном в мягких малахитовых тонах, днем на проекторе транслируются записи национальных эстрадных песен и концертов, а также футбольных матчей. Вечером играет живая музыка. В банкетных залах установлены плазменные экраны, а настоящий камин дарит ощущение уюта и тепла. Атмосферу ресторана поддерживают нежные ветви цветущей сакуры. 
</p>
<br>
<br>
<img src="root/seul/slogan.png" alt="" />
<img src="root/seul/uzor.png" alt="" />
</div>
</div>
<?php
}
else
   if ($_GET['pm'] == 2)
   {
?>
<div class="catalogue_item_cont"> 
<img src="root/seul/menu.png" alt="" style="width: 100%;" />
<div id="div_st" style="padding:0 15%;height:11730px;">
<p>
<a href="index.php?business_full=393&amp;pm=1" style="font-size:16px;left:140px;position:relative;top:-40px;float:left;color:#f0ef95;"><i><b>Ресторан</b></i></a>
<a href="index.php?business_full=393&amp;pm=2" style="font-size:16px;left:190px;position:relative;top:-40px;;float:left;color:#f0ef95;"><i><b>Меню</b></i></a>
<a href="index.php?business_full=393&amp;pm=3" style="font-size:16px;left:240px;position:relative;top:-40px;float:left;color:#f0ef95;"><i><b>Контакты</b></i></a>
</p>
<br>
<table style="width:750px;" id="i_table">
    <tr><td colspan="3" id="i_up" style="font-size:16px;">МЕНЮ КОРЕЙСКОЙ КУХНИ<br></td></tr>    
    <tr><td colspan="3" id="i_up1">- САЛАТЫ -</td></tr>
<tr>
        <td id="i_first"></td>
        <td id="i_second">Выход</td>
        <td id="i_second">Цена (грн)</td>
    </tr>
    <tr>
        <td id="i_first">КАЛЬМАРЫ<br><img src="root/seul/menu/1.jpg" width="130" height="80"></td>
        <td id="i_second">150/50</td>
        <td id="i_second">56-00</td>
    </tr>
        <tr>
        <td id="i_first">ЮХИ<br>(ТЕЛЯТИНА В СОЕВОМ СОУСЕ)<br><img src="root/seul/menu/2.jpg" width="130" height="80"></td>
        <td id="i_second">150/50</td>
        <td id="i_second">48-00</td>
    </tr>
    <tr>
        <td id="i_first">ХЕ ИЗ СИНЦА<br>(ОСТРЫЙ ПИКАНТНЫЙ ВКУС
МАРИНОВАНОЙ РЫБЫ)<br><img src="root/seul/menu/3.jpg" width="130" height="80"></td>
        <td id="i_second">150/50</td>
        <td id="i_second">45-00</td>
    </tr>
        <tr>
        <td id="i_first">ВЕЧО<br>(ВКУС ТУШЕНОГО ОГУРЦА
С ТЕЛЯТИНОЙ)<br><img src="root/seul/menu/4.jpg" width="130" height="80"></td>
        <td id="i_second">200/50</td>
        <td id="i_second">46-00</td>
    </tr>
    <tr>
        <td id="i_first">ЯПОНСКИЙ САЛАТ<br>(СОЧЕТАНИЕ ОВОЩЕЙ
С ИЗЫСКАННЫМ КИСЛО-СЛАДКИМ ВКУСОМ)<br><img src="root/seul/menu/5.jpg" width="130" height="80"></td>
        <td id="i_second">250/50</td>
        <td id="i_second">35-00</td>
    </tr>
    <tr>
        <td id="i_first">ЧЕРЕМША<br><img src="root/seul/menu/6.jpg" width="130" height="80"></td>
        <td id="i_second">200</td>
        <td id="i_second">35-00</td>
    </tr>
    <tr>
        <td id="i_first">ОПЯТА ДАЛЬНЕВОСТОЧНЫЕ<br><img src="root/seul/menu/7.jpg" width="130" height="80"></td>
        <td id="i_second">150</td>
        <td id="i_second">48-00</td>
    </tr>
    <tr>
        <td id="i_first">СПАРЖА<br>(БОБОВОЕ РАСТЕНИЕ ПРИДАЕТ
 ВКУС СОЧНОГО КУРИНОГО ФИЛЕ)<br><img src="root/seul/menu/8.jpg" width="130" height="80"></td>
        <td id="i_second">150</td>
        <td id="i_second">38-00</td>
    </tr>
    <tr>
        <td id="i_first">КОРОЛЕВСКИЙ МОРСКОЙ ГРИБ<br><img src="root/seul/menu/9.jpg" width="130" height="80"></td>
        <td id="i_second">150</td>
        <td id="i_second">38-00</td>
    </tr>
    <tr><td colspan="3" id="i_up1">- МЯСНЫЕ БЛЮДА -</td></tr>
    <tr>
        <td id="i_first">МЯСО ПО-СЕУЛЬСКИ<br>(СВИНИНА, РИС С ЗЕЛЕНЫМ ГОРОШКОМ)<br><img src="root/seul/menu/10.jpg" width="130" height="80"></td>
        <td id="i_second">150/100</td>
        <td id="i_second">87-00</td>
    </tr>
    <tr>
        <td id="i_first">ПУЛЬ-КОГИ<br>(ТЕЛЯТИНА, ПЕКИНСКАЯ КАПУСТА
С ОВОЩАМИ)<br><img src="root/seul/menu/11.jpg" width="130" height="80"></td>
        <td id="i_second">150/150</td>
        <td id="i_second">85-00</td>
    </tr>
    <tr>
        <td id="i_first">ТАЛЬ КОГИ-ХЕ<br>(КУРИНЫЕ КРЫЛЫШКИ)<br><img src="root/seul/menu/12.jpg" width="130" height="80"></td>
        <td id="i_second">250/60</td>
        <td id="i_second">68-00</td>
    </tr>
    <tr>
        <td id="i_first">КИТЫЛЬ-КОГИ<br>(РИС, СВИНЫЕ УШКИ)<br><img src="root/seul/menu/13.jpg" width="130" height="80"></td>
        <td id="i_second">150/100</td>
        <td id="i_second">58-00</td>
    </tr>
    <tr>
        <td id="i_first">НЭМ ПАЛОЧКИ<br>(СВИНОЙ ФАРШ, ГРЕБЕШКИ,
ФУНЧЕЗА, РИСОВЫЕ ЛИСТЬЯ)<br><img src="root/seul/menu/14.jpg" width="130" height="80"></td>
        <td id="i_second">150/50</td>
        <td id="i_second">55-00</td>
    </tr>
    <tr>
        <td id="i_first">МАНТУ ВО ФРИТЮРЕ<br>(СВИНОЙ ФАРШ, СЛОЕНОЕ ТЕСТО)<br><img src="root/seul/menu/15.jpg" width="130" height="80"></td>
        <td id="i_second">200/4 PC</td>
        <td id="i_second">72-00</td>
    </tr>
    <tr>
        <td id="i_first">СЯМИ<br>(ОТВАРНАЯ ТЕЛЯТИНА, ЯЙЦО ЖАРЕНОЕ,
РИС, ПОКУМИ, СОЕВАЯ ПАСТА)<br><img src="root/seul/menu/16.jpg" width="130" height="80"></td>
        <td id="i_second">340/100/50</td>
        <td id="i_second">140-00</td>
    </tr>
<tr>
        <td id="i_first">ФУНЧОЗА<br>(РИСОВАЯ ЛАПША, ТЕЛЯТИНА,
ОГУРЕЦ)<br><img src="root/seul/menu/17.jpg" width="130" height="80"></td>
        <td id="i_second">150/100</td>
        <td id="i_second">55-00</td>
    </tr>
<tr>
        <td id="i_first">БАРАНИНА ПО-ВОСТОЧНОМУ 
В СОУСЕ НАХАТ<br><img src="root/seul/menu/21.jpg" width="130" height="80"></td>
        <td id="i_second">250/100</td>
        <td id="i_second">185-00</td>
    </tr>
<tr>
        <td id="i_first">СВИНИНА ОТВАРНАЯ 
С СОЕВЫМ СОУСОМ<br><img src="root/seul/menu/22.jpg" width="130" height="80"></td>
        <td id="i_second">250/250</td>
        <td id="i_second">123-00</td>
    </tr>
<tr><td colspan="3" id="i_up1">- РЫБА. МОРЕПРОДУКТЫ -</td></tr>
<tr>
        <td id="i_first">СЕМГА В КУНЖУТНОМ СОУСЕ<br><img src="root/seul/menu/29.jpg" width="130" height="80"></td>
        <td id="i_second">200/100</td>
        <td id="i_second">125-00</td>
    </tr>
<tr>
        <td id="i_first">КРЕВЕТКИ В ТЕМПУРНОМ КЛЯРЕ<br><img src="root/seul/menu/30.jpg" width="130" height="80"></td>
        <td id="i_second">100/25/25</td>
        <td id="i_second">68-00</td>
    </tr>
<tr>
        <td id="i_first">ФОРЕЛЬ В КИСЛО-СЛАДКОМ СОУСЕ<br><img src="root/seul/menu/31.jpg" width="130" height="80"></td>
        <td id="i_second">450/150/50</td>
        <td id="i_second">117-00</td>
    </tr>
<tr>
        <td id="i_first">КАРП ПО-СЕУЛЬСКИ<br><img src="root/seul/menu/32.jpg" width="130" height="80"></td>
        <td id="i_second">600/100</td>
        <td id="i_second">150-00</td>
    </tr>
<tr>
        <td id="i_first">ОСЕТРИНА ПОД СОЕВЫМ СОУСОМ<br><img src="root/seul/menu/33.jpg" width="130" height="80"></td>
        <td id="i_second">200/150</td>
        <td id="i_second">105-00</td>
    </tr>
<tr><td colspan="3" id="i_up1">- СУПЫ -</td></tr>
<tr>
        <td id="i_first">ТЫБИ – ТЯЙ С РИСОМ<br>(ПРЕСОВАННЫЕ СОЕВЫЕ БОБЫ, 
РИС, ТЕЛЯТИНА, СОЕВАЯ ПАСТА)<br><img src="root/seul/menu/34.jpg" width="130" height="80"></td>
        <td id="i_second">300/100</td>
        <td id="i_second">52-00</td>
    </tr>
<tr>
        <td id="i_first">КУК-СУ<br>(ГОВЯЖИЙ БУЛЬОН/СОЕВЫЙ БУЛЬОН,
ЛАПША, ПОКУМИ)<br><img src="root/seul/menu/35.jpg" width="130" height="80"></td>
        <td id="i_second">200/300</td>
        <td id="i_second">65-00</td>
    </tr>
<tr>
        <td id="i_first">КЯД-ЖАН<br>(ТЕЛЯТИНА, БУЛЬОН,
ЗЕЛЕНЬ, КОЧИ-ТЕРИМИ, РИС)<br><img src="root/seul/menu/36.jpg" width="130" height="80"></td>
        <td id="i_second">200/50/50</td>
        <td id="i_second">48-00</td>
    </tr>
<tr>
        <td id="i_first">ТИНГАЙ<br>(КОПЧЕНАЯ СЕМГА, МОРСКАЯ КАПУСТА,
КАРТОФЕЛЬ, ЗЕЛЕНЬ, РИС)<br><img src="root/seul/menu/37.jpg" width="130" height="80"></td>
        <td id="i_second">350</td>
        <td id="i_second">55-00</td>
    </tr>
<tr><td colspan="3" id="i_up" style="font-size:16px;"><br><br><br><br><br><br><br><br><br>МЕНЮ ЯПОНСКОЙ КУХНИ<br></td></tr>
<tr><td colspan="3" id="i_up1">- КОРАБЛЬ -</td></tr>
<tr>
        <td id="i_first">ГЕСЕН «СЕУЛ»<br><img src="root/seul/menu/38.jpg" width="130" height="80"></td>
        <td id="i_second">725/50/100</td>
        <td id="i_second">405-00</td>
    </tr>
<tr><td colspan="3" id="i_up1">- АССОРТИ -</td></tr>
<tr>
        <td id="i_first">УМЕ<br>(ЛОСОСЬ, ТУНЕЦ, ОКУНЬ, 
ТИГРОВАЯ КРЕВЕТКА, КАЛЬМАР, 
ГРЕБЕШОК)<br><img src="root/seul/menu/39.jpg" width="130" height="80"></td>
        <td id="i_second">210/40/50</td>
        <td id="i_second">78-00</td>
    </tr>
<tr>
        <td id="i_first">ТАКЕ<br>(ЛОСОСЬ, ТУНЕЦ, ОКУНЬ, 
ТИГРОВАЯ КРЕВЕТКА, ОСЬМИНОГ.
СЛАДКАЯ КРЕВЕТКА, ЛАКЕДРА, 
МОЛЛЮСК, КАЛЬМАР, ГРЕБЕШОК)<br><img src="root/seul/menu/40.jpg" width="130" height="80"></td>
        <td id="i_second">350/60/50</td>
        <td id="i_second">118-00</td>
    </tr>
<tr><td colspan="3" id="i_up1">- СУШИ -</td></tr>
<tr>
        <td id="i_first">МАГУРО<br>(ТУНЕЦ)<br><img src="root/seul/menu/41.jpg" width="130" height="80"></td>
        <td id="i_second">35/45/50</td>
        <td id="i_second">17-00</td>
    </tr>
<tr>
        <td id="i_first">ТАЙ<br>(ОКУНЬ)<br><img src="root/seul/menu/42.jpg" width="130" height="80"></td>
        <td id="i_second">35/45/50</td>
        <td id="i_second">12-00</td>
    </tr>
<tr>
        <td id="i_first">ШАКЕ<br>(ЛОСОСЬ)<br><img src="root/seul/menu/43.jpg" width="130" height="80"></td>
        <td id="i_second">35/45/50</td>
        <td id="i_second">14-00</td>
    </tr>
<tr>
        <td id="i_first">УНАГИ<br>(УГОРЬ)<br><img src="root/seul/menu/44.jpg" width="130" height="80"></td>
        <td id="i_second">35/45/50</td>
        <td id="i_second">15-00</td>
    </tr>
<tr>
        <td id="i_first">ХАМАЧИ<br>(ЛАКЕДРА)<br><img src="root/seul/menu/45.jpg" width="130" height="80"></td>
        <td id="i_second">35/45/50</td>
        <td id="i_second">16-00</td>
    </tr>
<tr>
        <td id="i_first">ХОКИГАЙ<br>(МОЛЮСК)<br><img src="root/seul/menu/46.jpg" width="130" height="80"></td>
        <td id="i_second">35/45/50</td>
        <td id="i_second">18-00</td>
    </tr>
<tr>
        <td id="i_first">ИКА<br>(КАЛЬМАР)<br><img src="root/seul/menu/47.jpg" width="130" height="80"></td>
        <td id="i_second">35/45/50</td>
        <td id="i_second">13-00</td>
    </tr>
<tr>
        <td id="i_first">ЭБИ<br>(КРЕВЕТКА ТИГРОВАЯ)<br><img src="root/seul/menu/48.jpg" width="130" height="80"></td>
        <td id="i_second">35/45/50</td>
        <td id="i_second">15-00</td>
    </tr>
<tr>
        <td id="i_first">АМА-ЭЬИ<br>(СЛАДКАЯ КРЕВЕТКА)<br><img src="root/seul/menu/49.jpg" width="130" height="80"></td>
        <td id="i_second">35/45/50</td>
        <td id="i_second">15-00</td>
    </tr>
<tr>
        <td id="i_first">ХОТАТЕ<br>(МОРСКОЙ ГРЕБЕШОК)<br><img src="root/seul/menu/50.jpg" width="130" height="80"></td>
        <td id="i_second">35/45/50</td>
        <td id="i_second">15-00</td>
    </tr>
<tr>
        <td id="i_first">ТАКО<br>(ОСЬМИНОГ)</td>
        <td id="i_second">35/45/50</td>
        <td id="i_second">16-00</td>
    </tr>
<tr>
        <td id="i_first">ХОТАТЕ<br>(ФЕЛИКС)</td>
        <td id="i_second">35/45/50</td>
        <td id="i_second">20-00</td>
    </tr>
<tr>
        <td id="i_first">КАНИ<br>(КРАБ)</td>
        <td id="i_second">35/45/50</td>
        <td id="i_second">28-00</td>
    </tr>
<tr>
        <td id="i_first">ИКУРА<br>(ИКРА КРАСНАЯ)</td>
        <td id="i_second">35/45/50</td>
        <td id="i_second">22-00</td>
    </tr>
<tr>
        <td id="i_first">ТОБИКО<br>(ИКРА ЛЕТУЧЕЙ РЫБЫ)</td>
        <td id="i_second">35/45/50</td>
        <td id="i_second">20-00</td>
    </tr>
<tr><td colspan="3" id="i_up1">- САШИМИ -</td></tr>
<tr>
        <td id="i_first">МАГУРО<br>(ТУНЕЦ)<br><img src="root/seul/menu/51.jpg" width="130" height="80"></td>
        <td id="i_second">50/105/50</td>
        <td id="i_second">47-00</td>
    </tr>
<tr>
        <td id="i_first">ШАКЕ<br>(ЛОСОСЬ)</td>
        <td id="i_second">50/105/50</td>
        <td id="i_second">37-00</td>
    </tr>
<tr>
        <td id="i_first">ИКА<br>(КАЛЬМАР)</td>
        <td id="i_second">50/106/50</td>
        <td id="i_second">37-00</td>
    </tr>
<tr>
        <td id="i_first">ТАЙ<br>(ОКУНЬ)</td>
        <td id="i_second">50/105/50</td>
        <td id="i_second">36-00</td>
    </tr>
<tr>
        <td id="i_first">ХОТАТЕ<br>(МОРСКОЙ ГРЕБЕШОК)</td>
        <td id="i_second">50/105/50</td>
        <td id="i_second">42-00</td>
    </tr>
<tr>
        <td id="i_first">ЭБИ<br>(ТИГРОВАЯ КРЕВЕТКА)</td>
        <td id="i_second">50/105/50</td>
        <td id="i_second">47-00</td>
    </tr>
<tr>
        <td id="i_first">АМА-ЭБИ<br>(СЛАДКАЯ КРЕВЕТКА)</td>
        <td id="i_second">50/105/50</td>
        <td id="i_second">47-00</td>
    </tr>
<tr>
        <td id="i_first">ТАКО<br>(ОСЬМИНОГ)</td>
        <td id="i_second">50/110/50</td>
        <td id="i_second">45-00</td>
    </tr>
<tr>
        <td id="i_first">УНАГИ<br>(УГОРЬ)</td>
        <td id="i_second">50/112/50</td>
        <td id="i_second">42-00</td>
    </tr>
<tr>
        <td id="i_first">ХОГИКАЙ<br>(МОЛЮСК)</td>
        <td id="i_second">50/105/50</td>
        <td id="i_second">47-00</td>
    </tr>
<tr>
        <td id="i_first">КАНИ<br>(КРАБ)</td>
        <td id="i_second">50/105/50</td>
        <td id="i_second">105-00</td>
    </tr>
<tr>
        <td id="i_first">ХАМАЧИ<br>(ЛАКЕДРА)</td>
        <td id="i_second">50/150/50</td>
        <td id="i_second">47-00</td>
    </tr>
<tr>
        <td id="i_first">ИКУРА<br>(КРАСНАЯ ИКРА)</td>
        <td id="i_second">45/45/50</td>
        <td id="i_second">65-00</td>
    </tr>
<tr>
        <td id="i_first">ТОБИКО<br>(ИКРА ЛЕТУЧЕЙ РЫБЫ)</td>
        <td id="i_second">45/45/50</td>
        <td id="i_second">60-00</td>
    </tr>
<tr><td colspan="3" id="i_up1">- КАЛИФОРНИЯ -</td></tr>
<tr><td colspan="3" id="i_up">В ИКРЕ С ОГУРЦОМ:</td></tr>
<tr>
        <td id="i_first">ТУНЕЦ<br><img src="root/seul/menu/52.jpg" width="130" height="80"></td>
        <td id="i_second">180</td>
        <td id="i_second">60-00</td>
    </tr>
<tr>
        <td id="i_first">ЛОСОСЬ<br><img src="root/seul/menu/52.jpg" width="130" height="80"></td>
        <td id="i_second">180</td>
        <td id="i_second">55-00</td>
    </tr>
<tr>
        <td id="i_first">УГОРЬ<br><img src="root/seul/menu/52.jpg" width="130" height="80"></td>
        <td id="i_second">180</td>
        <td id="i_second">58-00</td>
    </tr>
<tr>
        <td id="i_first">КРАБ<br><img src="root/seul/menu/52.jpg" width="130" height="80"></td>
        <td id="i_second">180</td>
        <td id="i_second">76-00</td>
    </tr>
<tr><td colspan="3" id="i_up">В КУНЖУТЕ С ОГУРЦОМ:</td></tr>
<tr>
        <td id="i_first">ТУНЕЦ</td>
        <td id="i_second">180180</td>
        <td id="i_second">52-00</td>
    </tr>
<tr>
        <td id="i_first">ЛОСОСЬ</td>
        <td id="i_second">180</td>
        <td id="i_second">42-00</td>
    </tr>
<tr>
        <td id="i_first">УГОРЬ</td>
        <td id="i_second">180</td>
        <td id="i_second">46-00</td>
    </tr>
<tr>
        <td id="i_first">КРАБ</td>
        <td id="i_second">180</td>
        <td id="i_second">74-00</td>
    </tr>
<tr><td colspan="3" id="i_up1">- ПРАЗДНИЧНЫЕ РОЛЫ -</td></tr>
<tr>
        <td id="i_first">КУНАШИР<br>(КРАБ,  ТОБИКА, АВОКАДО,
СВЕРХУ ЛОСОСЬ, ИКРА ЛОСОСЯ)<br><img src="root/seul/menu/53.jpg" width="130" height="80"></td>
        <td id="i_second">190/30/50</td>
        <td id="i_second">74-00</td>
    </tr>
<tr>
        <td id="i_first">ГАВАЙСКИЙ<br>(ТУНЕЦ, СЫР, ЛОЛА-РОССА,
МАЙОНЕЗ)<br><img src="root/seul/menu/54.jpg" width="130" height="80"></td>
        <td id="i_second">200-30-50</td>
        <td id="i_second">73-00</td>
    </tr>
<tr>
        <td id="i_first">ХАНАБИ<br><img src="root/seul/menu/55.jpg" width="130" height="80"></td>
        <td id="i_second">175/30/50</td>
        <td id="i_second">64-00</td>
    </tr>
<tr>
        <td id="i_first">ФУТО МАКИ<br><img src="root/seul/menu/68.jpg" width="130" height="80"></td>
        <td id="i_second">200</td>
        <td id="i_second">68-00</td>
    </tr>
<tr>
        <td id="i_first">ШАКЕ<br><img src="root/seul/menu/69.jpg" width="130" height="80"></td>
        <td id="i_second">200</td>
        <td id="i_second">67-00</td>
    </tr>
<tr>
        <td id="i_first">ЗОЛОТОЙ ДРАКОН<br><img src="root/seul/menu/70.jpg" width="130" height="80"></td>
        <td id="i_second">220</td>
        <td id="i_second">65-00</td>
    </tr>
<tr>
        <td id="i_first">ФЕЛИКСОВАЯ СМЕСЬ<br><img src="root/seul/menu/74.jpg" width="130" height="80"></td>
        <td id="i_second">200</td>
        <td id="i_second">52-00</td>
    </tr>
<tr>
        <td id="i_first">РОЛЛ  С УГРЕМ<br><img src="root/seul/menu/75.jpg" width="130" height="80"></td>
        <td id="i_second">220</td>
        <td id="i_second">64-00</td>
    </tr>
<tr>
        <td id="i_first">ЧЕРНЫЙ САМУРАЙ<br><img src="root/seul/menu/76.jpg" width="130" height="80"></td>
        <td id="i_second">220</td>
        <td id="i_second">74-00</td>
    </tr>
<tr>
        <td id="i_first">КРАСНЫЙ ДРАКОН<br>(ТИГРОВАЯ КРЕВЕТКА, 
ТОБИКА ЗЕЛЕНАЯ, ОГУРЕЦ, 
ЛОСОСЬ СВЕРХУ)<br><img src="root/seul/menu/56.jpg" width="130" height="80"></td>
        <td id="i_second">200/30/50</td>
        <td id="i_second">74-00</td>
    </tr>
<tr>
        <td id="i_first">ЗЕЛЕНЫЙ ДРАКОН<br>(УГОРЬ. ТОБИКА, АВОКАДО
СВЕРХУ)<br><img src="root/seul/menu/57.jpg" width="130" height="80"></td>
        <td id="i_second">200/30/50</td>
        <td id="i_second">85-00</td>
    </tr>
<tr>
        <td id="i_first">АМА-ЭБИ<br><img src="root/seul/menu/58.jpg" width="130" height="80"></td>
        <td id="i_second">200/30/50</td>
        <td id="i_second">105-00</td>
    </tr>
<tr>
        <td id="i_first">БАЛТИМОР<br>(КРАБ, АВОКАДО,
ТОБИКА, ЛАЙМ, ЛОСОСЬ
СВЕРХУ)<br><img src="root/seul/menu/59.jpg" width="130" height="80"></td>
        <td id="i_second">245/30/50</td>
        <td id="i_second">91-00</td>
    </tr>
<tr>
        <td id="i_first">НИНДЗЯ<br>(КРАБ, ОГУРЕЦ, ТОБИКА.
ЛОСОСЬ, ТУНЕЦ. АВОКАДО
СВЕРХУ)<br><img src="root/seul/menu/60.jpg" width="130" height="80"></td>
        <td id="i_second">240/30/50</td>
        <td id="i_second">92-00</td>
    </tr>
<tr>
        <td id="i_first">ХОНСЮ<br><img src="root/seul/menu/61.jpg" width="130" height="80"></td>
        <td id="i_second">220/30/50</td>
        <td id="i_second">84-00</td>
    </tr>
<tr>
        <td id="i_first">ФИЛАДЕЛЬФИЯ<br>(КРАБ, ЛОСОСЬ, СЫР,
АВОКАДО, ТОБИКА)<br><img src="root/seul/menu/62.jpg" width="130" height="80"></td>
        <td id="i_second">240/30/50</td>
        <td id="i_second">112-00</td>
    </tr>
<tr>
        <td id="i_first">МАГУРА<br>(ТУНЕЦ, СИВИД, 
АВОКАДО, ОГУРЕЦ)<br><img src="root/seul/menu/63.jpg" width="130" height="80"></td>
        <td id="i_second">250/30/50</td>
        <td id="i_second">105-00</td>
    </tr>
<tr>
        <td id="i_first">УНАГИ<br><img src="root/seul/menu/64.jpg" width="130" height="80"></td>
        <td id="i_second">215/30/50</td>
        <td id="i_second">98-00</td>
    </tr>
<tr>
        <td id="i_first">«СЕУЛ»<br>(КРАБ, УГОРЬ, ТОБИКА
АВОКАДО, МАЙОНЕЗ)<br><img src="root/seul/menu/65.jpg" width="130" height="80"></td>
        <td id="i_second">300/30/50</td>
        <td id="i_second">122-00</td>
    </tr>
<tr>
        <td id="i_first">ЛОС-АНЖЕЛЕС<br>(УГОРЬ, ЛОСОСЬ, ЛОЛА-РОССА,
АНАНАС, СЫР)<br><img src="root/seul/menu/66.jpg" width="130" height="80"></td>
        <td id="i_second">255/30/50</td>
        <td id="i_second">112-00</td>
    </tr>
<tr>
        <td id="i_first">РАДУГА<br>(ТУНЕЦ, ЛАКЕДРА, ОКУНЬ,
ЛОСОСЬ, ИКРА ЛЕТУЧЕЙ РЫБЫ, ОГУРЕЦ)<br><img src="root/seul/menu/67.jpg" width="130" height="80"></td>
        <td id="i_second">230/30/50</td>
        <td id="i_second">117-00</td>
    </tr>
<tr><td colspan="3" id="i_up1">- ВЕГЕТАРИАНСКОЕ МЕНЮ -</td></tr>
<tr>
        <td id="i_first">СЕУЛ<br>(ПЕРЕЦ, МОРКОВЬ, АВОКАДО,
ОГУРЕЦ, ЖАРЕНЫЙ БАКЛАЖАН 
СВЕРХУ)<br><img src="root/seul/menu/71.jpg" width="130" height="80"></td>
        <td id="i_second">200/30/50</td>
        <td id="i_second">42-00</td>
    </tr>
<tr>
        <td id="i_first">ОВОЩНОЙ ДРАКОН<br>(ПЕРЕЦ, МОРКОВЬ, ОГУРЕЦ.
АВОКАДО СВЕРХУ)<br><img src="root/seul/menu/72.jpg" width="130" height="80"></td>
        <td id="i_second">230/30/50</td>
        <td id="i_second">42-00</td>
    </tr>
<tr>
        <td id="i_first">ВЕСЕННИЙ<br><img src="root/seul/menu/73.jpg" width="130" height="80"></td>
        <td id="i_second">200/30/50</td>
        <td id="i_second">22-00</td>
    </tr>
<tr>
        <td id="i_first">ЗЕЛЕНЫЙ<br>(ПЕРЕЦ, МОРКОВЬ,
ОГУРЕЦ, УКРОП СВЕРХУ)</td>
        <td id="i_second">200/30/50</td>
        <td id="i_second">22-00</td>
    </tr>
<tr>
        <td id="i_first">АВОКАДО</td>
        <td id="i_second">35/45/50</td>
        <td id="i_second">8-00</td>
    </tr>
<tr>
        <td id="i_first">ДЫНЯ</td>
        <td id="i_second">35/35/50</td>
        <td id="i_second">8-00</td>
    </tr>
<tr>
        <td id="i_first">СИВИД</td>
        <td id="i_second">35/35/50</td>
        <td id="i_second">8-00</td>
    </tr>
<tr>
        <td id="i_first">ШИТАКИ</td>
        <td id="i_second">35/35/50</td>
        <td id="i_second">8-00</td>
    </tr>
<tr><td colspan="3" id="i_up1">- САЛАТЫ -</td></tr>
<tr>
        <td id="i_first">СПАЙС МАГУРО<br><img src="root/seul/menu/77.jpg" width="130" height="80"></td>
        <td id="i_second">100/20</td>
        <td id="i_second">70-00</td>
    </tr>
<tr>
        <td id="i_first">САРАДО ТАКО БЕБИ<br><img src="root/seul/menu/78.jpg" width="130" height="80"></td>
        <td id="i_second">100/20</td>
        <td id="i_second">68-00</td>
    </tr>
<tr>
        <td id="i_first">САРАДО ИКА<br><img src="root/seul/menu/79.jpg" width="130" height="80"></td>
        <td id="i_second">100/20</td>
        <td id="i_second">57-00</td>
    </tr>
<tr>
        <td id="i_first">СИВИД<br><img src="root/seul/menu/80.jpg" width="130" height="80"></td>
        <td id="i_second">100/20/50</td>
        <td id="i_second">46-00</td>
    </tr>
<tr>
        <td id="i_first">ВАКАМИ<br><img src="root/seul/menu/81.jpg" width="130" height="80"></td>
        <td id="i_second">100/50</td>
        <td id="i_second">36-00</td>
    </tr>
<tr><td colspan="3" id="i_up1">- СУПЫ -</td></tr>
<tr>
        <td id="i_first">МИСО ТРАДИЦИОННЫЙ</td>
        <td id="i_second">230</td>
        <td id="i_second">28-00</td>
    </tr>
<tr>
        <td id="i_first">МИСО-УНАГИ (УГОРЬ)</td>
        <td id="i_second">220/24</td>
        <td id="i_second">3-00</td>
    </tr>
<tr>
        <td id="i_first">МИСО-КАНИ (КРАБ)</td>
        <td id="i_second">220/20</td>
        <td id="i_second">62-00</td>
    </tr>
<tr><td colspan="3" id="i_up1">- ГОРЯЧЕЕ -</td></tr>
<tr>
        <td id="i_first">РИС ЖАРЕНЫЙ С ОВОЩАМИ</td>
        <td id="i_second">150</td>
        <td id="i_second">39-00</td>
    </tr>
<tr>
        <td id="i_first">РИС ЖАРЕНЫЙ С МОРЕПРОДУКТАМИ</td>
        <td id="i_second">150</td>
        <td id="i_second">59-00</td>
    </tr>
<tr>
        <td id="i_first">ЛАПША ГРЕЧНЕВАЯ УДОН<br><img src="root/seul/menu/82.jpg" width="130" height="80"></td>
        <td id="i_second">100/150/50</td>
        <td id="i_second">66-00</td>
    </tr>
<tr><td colspan="3" id="i_up1">- ШАШЛЫЧКИ -</td></tr>
<tr>
        <td id="i_first">ТУНЕЦ<br><img src="root/seul/menu/83.jpg" width="130" height="80"></td>
        <td id="i_second">50/25/50</td>
        <td id="i_second">65-00</td>
    </tr>
<tr>
        <td id="i_first">КУРИНОЕ ФИЛЕ</td>
        <td id="i_second">50/25/50</td>
        <td id="i_second">48-00</td>
    </tr>
<tr>
        <td id="i_first">КУРИНОЕ СЕРДЦЕ</td>
        <td id="i_second">50/25/50</td>
        <td id="i_second">42-00</td>
    </tr>
<tr>
        <td id="i_first">ТИГРОВАЯ КРЕВЕТКА</td>
        <td id="i_second">50/25/50</td>
        <td id="i_second">56-00</td>
    </tr>
<tr><td colspan="3" id="i_up1">- ХОСОМАКИ -</td></tr>
<tr>
        <td id="i_first">ШАКЕ<br>(ЛОСОСЬ)<br><img src="root/seul/menu/84.jpg" width="130" height="80"></td>
        <td id="i_second">105/25/50</td>
        <td id="i_second">32-00</td>
    </tr>
<tr>
        <td id="i_first">УНАГИ<br>(УГОРЬ)</td>
        <td id="i_second">105/25/50</td>
        <td id="i_second">38-00</td>
    </tr>
<tr>
        <td id="i_first">МАГУРО<br>(ТУНЕЦ)</td>
        <td id="i_second">105/25/50</td>
        <td id="i_second">42-00</td>
    </tr>
<tr>
        <td id="i_first">ХОТАТЕ<br>(МОРСКОЙ ГРЕБЕШОК)</td>
        <td id="i_second">105/25/50</td>
        <td id="i_second">40-00</td>
    </tr>
<tr>
        <td id="i_first">КАНИ<br>(КРАБ)</td>
        <td id="i_second">105/25/50</td>
        <td id="i_second">47-00</td>
    </tr>
<tr>
        <td id="i_first">АВОКАДО</td>
        <td id="i_second">105/25/50</td>
        <td id="i_second">28-00</td>
    </tr>
<tr>
        <td id="i_first">ОГУРЕЦ</td>
        <td id="i_second">105/25/50</td>
        <td id="i_second">22-00</td>
    </tr>
<tr><td colspan="3" id="i_up1">- ТЕМАКИ -</td></tr>
<tr>
        <td id="i_first">ШАКЕ (ЛОСОСЬ)<br><img src="root/seul/menu/85.jpg" width="130" height="80"></td>
        <td id="i_second">90/25/50</td>
        <td id="i_second">37-00</td>
    </tr>
<tr>
        <td id="i_first">УНАГИ (УГОРЬ)</td>
        <td id="i_second">90/25/50</td>
        <td id="i_second">39-00</td>
    </tr>
<tr>
        <td id="i_first">МАГУРО (ТУНЕЦ)</td>
        <td id="i_second">90/25/50</td>
        <td id="i_second">42-00</td>
    </tr>
<tr>
        <td id="i_first">ЭБИ (ТИГРОВАЯ КРВЕТКА)</td>
        <td id="i_second">90/25/50</td>
        <td id="i_second">40-00</td>
    </tr>
<tr>
        <td id="i_first">СПАЙС ХОТАТЕ (ГРЕБЕШОК)</td>
        <td id="i_second">90/25/50</td>
        <td id="i_second">44-00</td>
    </tr>
<tr>
        <td id="i_first">КОРАБЛИ<br><img src="root/seul/menu/86.jpg" width="130" height="80"></td>
        <td id="i_second">390</td>
        <td id="i_second">88-00</td>
    </tr>
<tr>
        <td id="i_first">КОРАБЛИ</td>
        <td id="i_second">550</td>
        <td id="i_second">76-00</td>
    </tr>
<tr>
        <td id="i_first">НАБОР<br><img src="root/seul/menu/87.jpg" width="130" height="80"></td>
        <td id="i_second">250</td>
        <td id="i_second">64-00</td>
    </tr>
<tr><td colspan="3" id="i_up1">- КОМПЛЕКСНЫЕ ОБЕДЫ -</td></tr>
<tr>
        <td id="i_first">КОМПЛЕКСНЫЕ ОБЕДЫ<br><img src="root/seul/menu/88.jpg" width="130" height="80"></td>
        <td id="i_second"></td>
        <td id="i_second">63-00</td>
    </tr>
<tr>
        <td id="i_first">ТЫБЫ-ТЯЙ<br>МАНТУ<br>САЛАТ ВЕЧО</td>
        <td id="i_second"></td>
        <td id="i_second">52-00</td>
    </tr>
<tr>
        <td id="i_first">МОРСКОЙ СУП<br>САЛАТ ЯПОНСКИЙ<br>НЭМ ПАЛОЧКИ</td>
        <td id="i_second"></td>
        <td id="i_second">54-00</td>
    </tr>
<tr><td colspan="3" id="i_up1">- ДЕСЕРТЫ -</td></tr>
<tr>
        <td id="i_first">ФРУКТОВЫЙ РОЛЛ<br>(АНАНАС, КЛУБНИКА, КИВИ,
БАНАН, ЯБЛОКО)<br><img src="root/seul/menu/89.jpg" width="130" height="80"></td>
        <td id="i_second">270/50</td>
        <td id="i_second">78-00</td>
    </tr>
<tr>
        <td id="i_first">БАНАН В ТЕМПУРНОМ КЛЯРЕ<br><img src="root/seul/menu/90.jpg" width="130" height="80"></td>
        <td id="i_second">200/100</td>
        <td id="i_second">42-00</td>
    </tr>
<tr>
        <td id="i_first">СЫР В ТЕМПУРНОМ КЛЯРЕ<br><img src="root/seul/menu/91.jpg" width="130" height="80"></td>
        <td id="i_second">150/50</td>
        <td id="i_second">65-00</td>
    </tr>
</table>
</div>
</div>
<?php
}
else
   if ($_GET['pm'] == 3)
   {
?>

    <div class="catalogue_item_cont"> 
<img src="root/seul/menu.png" alt="" style="width: 100%;" />
<div id="div_st" style="padding:0 145px;height:400px;">
<p>
<a href="index.php?business_full=393&amp;pm=1" style="font-size:16px;left:140px;position:relative;top:-40px;float:left;color:#f0ef95;"><i><b>Ресторан</b></i></a>
<a href="index.php?business_full=393&amp;pm=2" style="font-size:16px;left:190px;position:relative;top:-40px;;float:left;color:#f0ef95;"><i><b>Меню</b></i></a>
<a href="index.php?business_full=393&amp;pm=3" style="font-size:16px;left:240px;position:relative;top:-40px;float:left;color:#f0ef95;"><i><b>Контакты</b></i></a>
</p>
<br>

        <script src="http://api-maps.yandex.ru/1.1/index.xml?key=AAmDzUsBAAAARkVWCAIAXzMCgKN58_MQUqB134Sdp-unCH0AAAAAAAAAAACbJlz2mcKc4anRgbxx6LBZ5BHPyg==" type="text/javascript"></script>
    <script type="text/javascript">
        window.onload = function () {
            var map = new YMaps.Map(document.getElementById("YMapsID"));
            map.setCenter(new YMaps.GeoPoint(37.804821,48.006259), 14);

            var content = document.createElement('span');
            content.innerHTML = "«Сеул»";
            map.openBalloon(new YMaps.GeoPoint(37.804821,48.006259), content);

            map.addControl(new YMaps.ToolBar());
            map.addControl(new YMaps.Zoom());
            map.addControl(new YMaps.MiniMap());
            map.addControl(new YMaps.ScaleLine());
        }
    </script>


	 <div id="YMapsID" style="width:100%;height:450px"></div>
   </div>
</div>
<?php
   } 
?>



<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="index.php?section_id=32&amp;business=1">Категория:</a></div>
</div>
<div class="catalogue_item_cont">
<a href="index.php?section_id=2&amp;business=1">бизнес</a>
 / 
<a href="index.php?section_id=32&amp;business=1">предприятия</a>
 / 
<a href="index.php?section_id=389&amp;business=2">отдых и развлечения</a>
 / 
<a href="index.php?section_id=390&amp;business=2">кафе и рестораны</a>
</div>


<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="">Фотогалерея:</a></div>
</div>
<div class="catalogue_item_cont">
<div class="catalogue_pic_l"><a href="root/seul/gallery/1.jpg" target="_blank"><img src="root/seul/gallery/1_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/seul/gallery/2.jpg" target="_blank"><img src="root/seul/gallery/2_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/seul/gallery/3.jpg" target="_blank"><img src="root/seul/gallery/3_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/seul/gallery/4.jpg" target="_blank"><img src="root/seul/gallery/4_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/seul/gallery/5.jpg" target="_blank"><img src="root/seul/gallery/5_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/seul/gallery/6.jpg" target="_blank"><img src="root/seul/gallery/6_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/seul/gallery/7.jpg" target="_blank"><img src="root/seul/gallery/7_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/seul/gallery/8.jpg" target="_blank"><img src="root/seul/gallery/8_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/seul/gallery/9.jpg" target="_blank"><img src="root/seul/gallery/9_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/seul/gallery/10.jpg" target="_blank"><img src="root/seul/gallery/10_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/seul/gallery/11.jpg" target="_blank"><img src="root/seul/gallery/11_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/seul/gallery/12.jpg" target="_blank"><img src="root/seul/gallery/12_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/seul/gallery/13.jpg" target="_blank"><img src="root/seul/gallery/13_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/seul/gallery/14.jpg" target="_blank"><img src="root/seul/gallery/14_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/seul/gallery/15.jpg" target="_blank"><img src="root/seul/gallery/15_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/seul/gallery/16.jpg" target="_blank"><img src="root/seul/gallery/16_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/seul/gallery/17.jpg" target="_blank"><img src="root/seul/gallery/17_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/seul/gallery/18.jpg" target="_blank"><img src="root/seul/gallery/18_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/seul/gallery/19.jpg" target="_blank"><img src="root/seul/gallery/19_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/seul/gallery/20.jpg" target="_blank"><img src="root/seul/gallery/20_s.jpg" width="60" height="60" border="0" alt=""></a></div>
</div>
<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="">Контактная информация:</div>
</div>
 <div class="catalogue_item_cont">
 		 <table width="100%">
			<tbody>
 			<tr>
			<!--	<td><img class="main_sec_image" src="" width="60" height="60" border="0" alt="" /></td>-->
				<td>Адрес:</td>
				<td>Телефон:</td>
				<td>Факс:</td>
				<td>E-mail:</td>
				<td>Веб-сайт:</td>
			</tr>
			<tr>
				<td>г. Донецк<br> ул. Артёма, 125</td>
				<td>(062) 304-33-60<br> 099-947-54-80</td>
				<td></td>
				<td></td>
				<td></td>

			</tr>
			</tbody> 
		 </table> 		
	 </div>
</div>  

