 <div class="catalogue_item_c">
<style>
.catalogue_item_cont p {
color:#000000;
text-align:justify;
text-indent:0px;
line-height:20px;
margin:0px;
}

img.main_sec_image {
border:none;
}
.catalogue_item_cont_m {
background-color:#FFFFFF;
border:1px solid lightgray;
color:#000000;
margin:0;
margin:15px 10px 10px;
width:980px;
}
.catalogue_item_cont {
background-color:#ffffff;
border-top:1px solid lightgray;
margin:0 0 7px 10px;
width:980px;
color:#000000;
}
.catalogue_item_c {
background-color:#F3F3F3;
}

a.menu_text {font-size:18px;font-weight:bold;color:#ffffff;}

img.main_sec_image {
height:240px;
padding:0;
width:240px;
}
#main_text {float:left;
height:700px;
line-height:20px;
padding-right:20px;
text-align:justify;
width:580px;}

.catalogue_item_cont a {
color:#000000;
}
.catalogue_item_cont a:hover {
color:#000000;
text-decoration:underline;
}
.catalogue_item_mp_a {
left:3px;
position:relative;
}

#mm_menu {position:relative;left:610px;width:225px;text-align:center;} 

#div_st {padding:0 50px;position:relative;height:800px;}

@media all and (-webkit-min-device-pixel-ratio:10000),
not all and (-webkit-min-device-pixel-ratio:0) {
 #div_st {height:869px;}
}
td#i_up {font-weight:bold;text-align:center;}
td#i_up1 {font-weight:bold;text-decoration:underline;}
td#i_first {width:510px;text-align:left;font-size:16px;}
td#i_second {width:75px;font-size:14px;}
td#i_third {width:50px;font-size:14px;}
table#i_table tr {height:35px;}
</style>
<?php
if ($_GET['pm'] == 1) 
{
?>

<div class="catalogue_item_cont_m"> 
<img src="root/st_h/up.png" alt="" style="width: 100%;" />
<div id="div_st">
<p>
<div id="mm_menu" style="top:-205px;"><a href="index.php?business_full=395&amp;pm=1"  class="menu_text"><b>ГЛАВНАЯ</b></a></div>
<div id="mm_menu" style="top:-190px;"><a href="index.php?business_full=395&amp;pm=2" class="menu_text">МЕНЮ КАФЕ</a></div>
<div id="mm_menu" style="top:-175px;"><a href="index.php?business_full=395&amp;pm=3" class="menu_text">КОНТАКТЫ</a></div>
</p>
<br>
<div id="main_text">
<p>Кафе <b>«Стейк-Хауз»</b> славится  аппетитными стейками из различных видов мяса и рыбы.
Разнообразное меню, качественное обслуживание и удобство расположения кафе привлекает как дончан, так и гостей города.</p>
<br>
<p><u>МЕНЮ:</u><br>
в меню «Стейк-Хауз» представлены блюда европейской и домашней кухни. Специальное предложение – постное меню.</p>
<br>
<p><u>МЕРОПРИЯТИЯ:</u><br>
организация банкетов, банкетов-фуршетов на выезд (кейтеринг), проведение корпоративных мероприятий, свадеб и юбилеев.</p>
<br>
<p><u>ЗАЛЫ:</u><br>
- основной зал рассчитан  на 80 посадочных мест, <br>- банкетный зал – на 15 посадочных мест, <br>- летняя площадка – на 25 посадочных мест.</p>
<br>
<p><u>ФОРМА ОПЛАТЫ:</u><br>
наличными, кредитными картами и по безналичному расчету.</p>
<br>
<p><u>БОНУСЫ:</u><br>
дисконтные карты для постоянных клиентов.</p>
<br>
<p><u>РАСПОЛОЖЕНИЕ КАФЕ:</u><br>
<b>кафе «Стейк-хауз»</b> расположено в центре города, <br>в 5 мин езды от центральной площади Донецка – площади им. Ленина <br>и 10 мин от стадиона «Донбасс Арена» </p>
<br>
<p><u>ГРАФИК РАБОТЫ:</u> <b>КРУГЛОСУТОЧНО</b><br>
г.Донецк, пр.Театральный, 28 <br>тел. (062)335-23-68</p>
</div>
<div>
<img class="main_sec_image" src="root/st_h/01.png" alt="" style="float: left;" /><img class="main_sec_image" src="root/st_h/02.png" alt="" style="float: left;" />
<img class="main_sec_image" src="root/st_h/03.png" alt="" style="float: left;" /><br><br>
</div>
<br>
<br>
</div>
</div>
<?php
}
else
   if ($_GET['pm'] == 2)
   {
?>
<div class="catalogue_item_cont_m"> 
<img src="root/st_h/up.png" alt="" style="width: 100%;" />
<div id="div_st" style="height: 18290px;">
<p>
<div id="mm_menu" style="top:-205px;"><a href="index.php?business_full=395&amp;pm=1"  class="menu_text"><b>ГЛАВНАЯ</b></a></div>
<div id="mm_menu" style="top:-190px;"><a href="index.php?business_full=395&amp;pm=2" class="menu_text">МЕНЮ КАФЕ</a></div>
<div id="mm_menu" style="top:-175px;"><a href="index.php?business_full=395&amp;pm=3" class="menu_text">КОНТАКТЫ</a></div>
<br>
<table style="width:870px;" id="i_table">
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><i>ХОЛОДНЫЕ ЗАКУСКИ</i><br><br><br></td></tr>    
    <tr>
        <td id="i_first"><b>Ассорти из свежих овощей</b><font style="font-size:14px;"><br>(Свежие помидоры, огурцы, перец болгарский, зелень)</font></td>
        <td id="i_second" colspan="2">250</td>
        <td id="i_second" colspan="2">17-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Огурцы соленые, маринованные</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">8-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Помидоры соленые, маринованные</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">8-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Ассорти мясное</b><font style="font-size:14px;"><br>(Балык "Дарницкий", ветчина, колбаса с/к, колбаса в/к)</font></td>
        <td id="i_second" colspan="2">250</td>
        <td id="i_second" colspan="2">36-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Ассорти из сыров</b><font style="font-size:14px;"><br>(Сыр "Радомер", сыр  "Российский")</font></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">30-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Сало "по-домашнему"</b><font style="font-size:14px;"><br>(солёное сало с прорезью, подаётся с дольками чеснока и репчатого лука)</font></td>
        <td id="i_second" colspan="2">100/43</td>
        <td id="i_second" colspan="2">14-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Язык</b><font style="font-size:14px;"><br>(отварной говяжий язык, подается с майонезом)</font></td>
        <td id="i_second" colspan="2">100/30</td>
        <td id="i_second" colspan="2">25-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Лосось слабосолёный</b><font style="font-size:14px;"><br>(филе слабосолёного лосося, подается со сливочным маслом)</font></td>
        <td id="i_second" colspan="2">95/45</td>
        <td id="i_second" colspan="2">32-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Грибы маринованные</b><font style="font-size:14px;"><br>(Маринованые шампиньоны с зелёным луком)</font></td>
        <td id="i_second" colspan="2">100</td>
        <td id="i_second" colspan="2">16-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Оливки, маслины</b><font style="font-size:14px;"><br>(По желанию Вы можете заказать маслины или оливки с косточкой или без косточки)</font></td>
        <td id="i_second" colspan="2">100</td>
        <td id="i_second" colspan="2">16-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Лимон с сахаром</b></td>
        <td id="i_second" colspan="2">50/20</td>
        <td id="i_second" colspan="2">4-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Лимон с сахаром</b></td>
        <td id="i_second" colspan="2">50/20</td>
        <td id="i_second" colspan="2">4-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Масло сливочное</b></td>
        <td id="i_second" colspan="2">50</td>
        <td id="i_second" colspan="2">3-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Бутерброд с красной икрой</b></td>
        <td id="i_second" colspan="2">40</td>
        <td id="i_second" colspan="2">16-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Креветки отварные</b></td>
        <td id="i_second" colspan="2">100/20</td>
        <td id="i_second" colspan="2">17-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Кабачки жареные</b><font style="font-size:14px;"><br>(кабачки жареные подаются с  майонезом,чесноком)</font></td>
        <td id="i_second" colspan="2">280</td>
        <td id="i_second" colspan="2">25-00</td>
    </tr>
      <tr>
        <td id="i_first"><b>Баклажаны жареные</b><font style="font-size:14px;"><br>(баклажаны жареные подаются с помидорами, майонезом,чесноком)</font></td>
        <td id="i_second" colspan="2">280</td>
        <td id="i_second" colspan="2">25-00</td>
    </tr>
       <tr>
        <td id="i_first"><b>Сельдь по-русски</b></td>
        <td id="i_second" colspan="2">150</td>
        <td id="i_second" colspan="2">15-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><br><br><i>САЛАТЫ</i><br></td></tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>*** с морепродуктами***</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Салат "Нептун"</b><font style="font-size:14px;"><br>(крабовые палочки, огурец, кукуруза, яйцо, сыр, майонез)</font></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">20-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Салат "Морской каприз"</b><font style="font-size:14px;"><br>(Кальмары, мидии, креветки, листья салата, помидор, масло растительное, масло оливковое, уксус "Бальзамик")</font></td>
        <td id="i_second" colspan="2">175</td>
        <td id="i_second" colspan="2">30-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Салат "Коралловый остров"</b><font style="font-size:14px;"><br>(яйцо, лосось с/с,огурец,яблоко, майонез)</font></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">25-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Салат "Жемчужина моря"</b><font style="font-size:14px;"><br>(яйцо, помидор, креветки, кальмары, майонез,чеснок,маслина,лимон)</font></td>
        <td id="i_second" colspan="2">220</td>
        <td id="i_second" colspan="2">28-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Салат горячий с лососем</b><font style="font-size:14px;"><br>(жареные кусочки лосося, помидоры,огурцы, оливки, маслины, салат "Айсберг", "Латук" заправлен уксусом "Бальзамик", раст маслом)</font></td>
        <td id="i_second" colspan="2">220</td>
        <td id="i_second" colspan="2">35-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>*** мясные***</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Салат “Трансильвания”</b><font style="font-size:14px;"><br>( пекинская капуста, помидоры, огурцы, балыковая ветчина, кунжут, сыр, обжареные в специальной панировке филе курицы и телятины)</font></td>
        <td id="i_second" colspan="2">215</td>
        <td id="i_second" colspan="2">30-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Салат “Китайский”</b><font style="font-size:14px;"><br>( омлет, огурец, морковь, пекинская капуста, говядина отварная, соевый соус, майонез)</font></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">20-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Салат "Английский"</b><font style="font-size:14px;"><br>(курица,обжареные шампиньоны, соленый огурец,майонез,горчица)</font></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">20-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Салат "Бременский"</b><font style="font-size:14px;"><br>(Свежие шампиньоны, куринное филе, помидоры, салат, чесночные тосты, дрессин "Бальзамико")</font></td>
        <td id="i_second" colspan="2">210</td>
        <td id="i_second" colspan="2">25-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Салат "Столичный"</b><font style="font-size:14px;"><br>(Салат приготовлен по  классическому рецепту  с отварной курицей)</font></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">17-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Салат "Цезарон"</b><font style="font-size:14px;"><br>(Куриное филе, ветчина, листья салата,тосты,сыр,майонез,горчица)</font></td>
        <td id="i_second" colspan="2">250</td>
        <td id="i_second" colspan="2">30-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Салат "Цезарь" с курицей</b><font style="font-size:14px;"><br>(Классический салат, с оригинальным соусом "Цезарь" и сыром пармезан)</font></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">30-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Салат "Картофельный бум"</b><font style="font-size:14px;"><br>(Куриное филе, ветчина, грибы маринованные,жареный картофель, яйцо,сыр, майонез, чеснок)</font></td>
        <td id="i_second" colspan="2">230</td>
        <td id="i_second" colspan="2">30-00</td>
    </tr>
   <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>*** с языком***</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Салат "Особый"</b><font style="font-size:14px;"><br>(язык говяжий, обжареные шампиньоны,морковь по-корейски, майонез)</font></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">25-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>*** овощные***</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Салат "Греческий"</b><font style="font-size:14px;"><br>(Свежие помидоры, огурцы, маслины б/к, болгарский перец, сыр "Фета", оливковое масло, грецкий орех, сок лимона)</font></td>
        <td id="i_second" colspan="2">225</td>
        <td id="i_second" colspan="2">20-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Салат "Весенний"</b><font style="font-size:14px;"><br>(Салат "Айсберг", "Лолло-Россо", помидоры, огурцы, редис, перец, болгарский, шампиньоны, укроп, растительное масло,оливковое, масло, уксус "Бальзамик")</font></td>
        <td id="i_second" colspan="2">250</td>
        <td id="i_second" colspan="2">25-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Винегрет</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">18-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Салат из квашеной капусты с маслом</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">14-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Салат из свежей капусты с майонезом</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">14-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Салат из свежей капусты с маслом</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">14-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Салат из свежих помидоров и огурцов</b><font style="font-size:14px;"><br>(Свежие помидоры, огурцы с зелёным луком, заправленные, нерафинированным растительным маслом.)</font></td>
        <td id="i_second" colspan="2">250</td>
        <td id="i_second" colspan="2">14-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><br><br><br><i>ГОРЯЧИЕ  ЗАКУСКИ</i><br><br><br></td></tr>
    <tr>
        <td id="i_first"><b>Сырные ромбики с соусом "Тар-Тар"</b></td>
        <td id="i_second" colspan="2">170/50</td>
        <td id="i_second" colspan="2">24-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Крылышки «Барбекю» с соусом</b></td>
        <td id="i_second" colspan="2">210/60</td>
        <td id="i_second" colspan="2">27-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Жюльен с курицей и грибами</b></td>
        <td id="i_second" colspan="2">150</td>
        <td id="i_second" colspan="2">18-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Омлет с  помидорами и сыром</b></td>
        <td id="i_second" colspan="2">220/50</td>
        <td id="i_second" colspan="2">15-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Яичница с салом</b></td>
        <td id="i_second" colspan="2">130</td>
        <td id="i_second" colspan="2">10-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Грибы жареные по-домашнему</b></td>
        <td id="i_second" colspan="2">150</td>
        <td id="i_second" colspan="2">15-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Капуста цветная в кляре со сметаной</b></td>
        <td id="i_second" colspan="2">210/50</td>
        <td id="i_second" colspan="2">20-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><br><br><br><i>ПИЦЦЫ</i><br><br><br></td></tr>
    <tr>
        <td id="i_first"><b>Пицца "Эспаньолла"</b><font style="font-size:14px;"><br>(креветки, курица, колбаса с/к, помидоры, перец, сыр) </font></td>
        <td id="i_second" colspan="2">450</td>
        <td id="i_second" colspan="2">40-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Пицца "Морская звезда"</b><font style="font-size:14px;"><br>(лосось,  креветки,  помидоры,  сыр, соус)</font></td>
        <td id="i_second" colspan="2">560</td>
        <td id="i_second" colspan="2">60-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Пицца "Стейк-хауз"</b><font style="font-size:14px;"><br>(ветчина, балык, перец болгарский, помидор, сыр, соус) </font></td>
        <td id="i_second" colspan="2">500</td>
        <td id="i_second" colspan="2">45-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Пицца “Салями”</b><font style="font-size:14px;"><br>(колбаса в/к,  грибы,  сыр, соус)</font></td>
        <td id="i_second" colspan="2">440</td>
        <td id="i_second" colspan="2">38-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Пицца “Гурмэ”</b><font style="font-size:14px;"><br>(говядина,  грибы,  помидор, сыр, соус )</font></td>
        <td id="i_second" colspan="2">570</td>
        <td id="i_second" colspan="2">40-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Пицца “Пикантная”</b><font style="font-size:14px;"><br>(свинина,  грибы, помидор,  сыр,  чеснок, соус)</font></td>
        <td id="i_second" colspan="2">510</td>
        <td id="i_second" colspan="2">40-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Пицца “Вкус Италии”</b><font style="font-size:14px;"><br>(курица,  грибы,  помидоры, сыр, соус) </font></td>
        <td id="i_second" colspan="2">500</td>
        <td id="i_second" colspan="2">44-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Пицца “Охотничья”</b><font style="font-size:14px;"><br>(говяжий язык,колбаски "Охотничьи",оливки,перец болгарский, сыр) </font></td>
        <td id="i_second" colspan="2">460</td>
        <td id="i_second" colspan="2">44-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Пицца "Неополитано"</b><font style="font-size:14px;"><br>(копченая курица, брокколи, грибы, сыр)</font></td>
        <td id="i_second" colspan="2">500</td>
        <td id="i_second" colspan="2">38-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Пицца "Украинская солянка"</b><font style="font-size:14px;"><br>(говядина , свинина,  колбаски  "Охотничьи" , солёный огурец, каперсы, шапмпиньоны, сыр, чеснок)</font></td>
        <td id="i_second" colspan="2">550</td>
        <td id="i_second" colspan="2">45-00</td>
    </tr>
     <tr><td colspan="3" id="i_up" style="font-size:16px;"><br><br><br><i>ПЕРВЫЕ БЛЮДА</i><br><br><br></td></tr>
     <tr>
        <td id="i_first"><b>Бозбаш</b><font style="font-size:14px;"><br>(суп с бараньими фрикадельками и овощами)</font></td>
        <td id="i_second" colspan="2">400</td>
        <td id="i_second" colspan="2">27-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Суп овощной</b></td>
        <td id="i_second" colspan="2">400</td>
        <td id="i_second" colspan="2">14-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Уха "по-царски"</b></td>
        <td id="i_second" colspan="2">400</td>
        <td id="i_second" colspan="2">24-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Борщ "Украинский"  со сметаной,луком,чесноком</b></td>
        <td id="i_second" colspan="2">400/20/35</td>
        <td id="i_second" colspan="2">17-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Солянка сборная мясная</b></td>
        <td id="i_second" colspan="2">400</td>
        <td id="i_second" colspan="2">20-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Куриный бульон с яйцом и гренками</b></td>
        <td id="i_second" colspan="2">240/50</td>
        <td id="i_second" colspan="2">14-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Суп сливочный с телятиной и шампиньонами</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">17-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Окрошка</b></td>
        <td id="i_second" colspan="2">400</td>
        <td id="i_second" colspan="2">17-00</td>
    </tr>
     <tr><td colspan="3" id="i_up" style="font-size:16px;"><br><br><i>ВТОРЫЕ БЛЮДА</i><br></td></tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>*** из рыбы ***</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Стейк из лосося под "Икорным" соусом</b><font style="font-size:14px;"><br>Стейк из лосося на косточке, жареный на гриле, с нежным икорно-сливочным соусом</font></td>
        <td id="i_second" colspan="2">150/75/39</td>
        <td id="i_second" colspan="2">62-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Стейк из лосося отварной</b><font style="font-size:14px;"><br>Стейк из лосося на косточке отварной, подается с рисом</font></td>
        <td id="i_second" colspan="2">150/150/39</td>
        <td id="i_second" colspan="2">60-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Морские язычки</b><font style="font-size:14px;"><br>Филе пангасиуса в кляре подается с соусом</font></td>
        <td id="i_second" colspan="2">175/35</td>
        <td id="i_second" colspan="2">30-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Пеленгас в льезоне с луком "Фри"</b></td>
        <td id="i_second" colspan="2">140/25/39</td>
        <td id="i_second" colspan="2">30-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Пангасиус запеченый</b><font style="font-size:14px;"><br>Филе пангасиуса, картофель, помидоры, запеченые под сыром</font></td>
        <td id="i_second" colspan="2">300/39</td>
        <td id="i_second" colspan="2">30-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Рыбка под соусом Тар-тар</b><font style="font-size:14px;"><br>Филе пангасиуса в панировке, с соусом Тар-тар, листьями салатов</font></td>
        <td id="i_second" colspan="2">165/50/39</td>
        <td id="i_second" colspan="2">30-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>*** из нескольких видов мяса ***</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Стейк "Стейк- хауз"</b><font style="font-size:14px;"><br>Свинная корейка, куриное филе,запечённые под сыром с овощами</font></td>
        <td id="i_second" colspan="2">500/50</td>
        <td id="i_second" colspan="2">55-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Фахитас</b><font style="font-size:14px;"><br>Кусочки говяжьей вырезки, свинины и куриного филе обжареные с репчатым луком, болгарским перцем подаются с овощами</font></td>
        <td id="i_second" colspan="2">200/50</td>
        <td id="i_second" colspan="2">34-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Котлета по-донбасски</b></td>
        <td id="i_second" colspan="2">200/50</td>
        <td id="i_second" colspan="2">22-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>*** из баранины***</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Баранина с овощами и рисом</b></td>
        <td id="i_second" colspan="2">250/150</td>
        <td id="i_second" colspan="2">60-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>*** из говядины***</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Говядина "по-испански"</b><font style="font-size:14px;"><br>Вырезка из говядины,  сладкий перец, спаржевая фасоль жареные подается с овощами</font></td>
        <td id="i_second" colspan="2">195/50</td>
        <td id="i_second" colspan="2">35-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Стейк из телятины</b><font style="font-size:14px;"><br>Стейк из говядины со специями жареный на гриле, подается с овощами</font></td>
        <td id="i_second" colspan="2">130/50</td>
        <td id="i_second" colspan="2">35-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Стейк "Раунд"</b><font style="font-size:14px;"><br>Стейк из говядины, подается с овощами</font></td>
        <td id="i_second" colspan="2">200/50</td>
        <td id="i_second" colspan="2">50-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>*** из свинины***</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Стейк "Наковский"</b><font style="font-size:14px;"><br>Стейк из свинины запеченый под сыром, подается с овощами</font></td>
        <td id="i_second" colspan="2">280/50</td>
        <td id="i_second" colspan="2">38-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Стейк из свинины на кости</b><font style="font-size:14px;"><br>Свинная корейка на кости со специями жареная на гриле</font></td>
        <td id="i_second" colspan="2">150/50</td>
        <td id="i_second" colspan="2">35-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>"Пальчики оближешь!!!"</b><font style="font-size:14px;"><br>Рулетики из свинины фаршированные начинкой с грибами и помидорами, запеченые под сыром, подаются с соусом и овощами</font></td>
        <td id="i_second" colspan="2">240/50</td>
        <td id="i_second" colspan="2">40-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Перепелиное гнездо</b><font style="font-size:14px;"><br>Отбивная запеченая с грибами и яйцом, подается с овощами</font></td>
        <td id="i_second" colspan="2">175/50</td>
        <td id="i_second" colspan="2">30-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Отбивная из свинины в кляре</b></td>
        <td id="i_second" colspan="2">130/50</td>
        <td id="i_second" colspan="2">25-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Жаркое "по-домашнему"</b></td>
        <td id="i_second" colspan="2">420</td>
        <td id="i_second" colspan="2">30-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Мясо по-французски</b></td>
        <td id="i_second" colspan="2">190/50</td>
        <td id="i_second" colspan="2">30-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>*** из курицы***</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Стейк из курицы под соусом "Морней"</b><font style="font-size:14px;"><br>Кусочки куриного филе с  шампиньонами запеченые под сыром в сливочно-винном соусе "Морней"</font></td>
        <td id="i_second" colspan="2">300</td>
        <td id="i_second" colspan="2">32-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Куриное филе фаршированное грибами и сыром</b></td>
        <td id="i_second" colspan="2">260/50</td>
        <td id="i_second" colspan="2">32-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Зразы по-европейски</b></td>
        <td id="i_second" colspan="2">130/50</td>
        <td id="i_second" colspan="2">14-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Котлета "по-киевски"</b></td>
        <td id="i_second" colspan="2">140/50</td>
        <td id="i_second" colspan="2">20-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Ирландское овощное рагу с куриным филе</b><font style="font-size:14px;"><br>Кусочки куриного филе обжареные с  капустой брокколи, цветной, брюссельской, спаржевой фасолью, помидорами,перцем,картофелем</font></td>
        <td id="i_second" colspan="2">300/50</td>
        <td id="i_second" colspan="2">30-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><br><br><br><i>МУЧНЫЕ БЛЮДА</i><br><br></td></tr>
    <tr>
        <td id="i_first"><b>Вареники с картофелем</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">15-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Вареники с капустой</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">15-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Пельмени домашние</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">20-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Паста "Дары моря"</b><font style="font-size:14px;"><br>макароны из твердых сортов пшеницы с морским коктейлем</font></td>
        <td id="i_second" colspan="2">260</td>
        <td id="i_second" colspan="2">45-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><br><br><br><i>ГАРНИРЫ</i><br><br></td></tr>
    <tr>
        <td id="i_first"><b>Картофель "Фри"</b></td>
        <td id="i_second" colspan="2">100</td>
        <td id="i_second" colspan="2">12-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Картофель жаренный с грибами</b></td>
        <td id="i_second" colspan="2">175</td>
        <td id="i_second" colspan="2">15-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Картофельное пюре</b></td>
        <td id="i_second" colspan="2">160</td>
        <td id="i_second" colspan="2">8-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Картофель отварной с зеленью</b></td>
        <td id="i_second" colspan="2">180</td>
        <td id="i_second" colspan="2">8-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Крокеты картофельные</b></td>
        <td id="i_second" colspan="2">120</td>
        <td id="i_second" colspan="2">10-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Рис отварной</b></td>
        <td id="i_second" colspan="2">160</td>
        <td id="i_second" colspan="2">7-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Рис с овощами</b></td>
        <td id="i_second" colspan="2">150</td>
        <td id="i_second" colspan="2">10-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Рис с яйцом и креветками</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">22-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><br><br><br><i>БЛИНЧИКИ</i><br><br></td></tr>
    <tr>
        <td id="i_first"><b>Блинчики со сливочным маслом и медом</b></td>
        <td id="i_second" colspan="2">221/50</td>
        <td id="i_second" colspan="2">18-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Блинчики  с красной икрой</b></td>
        <td id="i_second" colspan="2">161</td>
        <td id="i_second" colspan="2">25-50</td>
    </tr>
    <tr>
        <td id="i_first"><b>Блинчики с мясом и сметаной</b></td>
        <td id="i_second" colspan="2">280</td>
        <td id="i_second" colspan="2">25-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Блинчики с творогом и клубничным соусом</b></td>
        <td id="i_second" colspan="2">252</td>
        <td id="i_second" colspan="2">25-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Блинчики с клубникой и сливками</b></td>
        <td id="i_second" colspan="2">350</td>
        <td id="i_second" colspan="2">25-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><br><br><br><i>ДЕСЕРТЫ</i><br><br></td></tr>
    <tr>
        <td id="i_first"><b>Десерт "Панна Котта"</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">15-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Салат фруктовый</b><font style="font-size:14px;"><br>/яблоко, апельсин, киви, банан, виноград, взбитые сливки/</font></td>
        <td id="i_second" colspan="2">350</td>
        <td id="i_second" colspan="2">22-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Мороженое "Стейк-Хауз"</b></td>
        <td id="i_second" colspan="2">250</td>
        <td id="i_second" colspan="2">22-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Мороженое в ананасе</b></td>
        <td id="i_second" colspan="2">500</td>
        <td id="i_second" colspan="2">27-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Мороженое</b><font style="font-size:14px;"><br>/пломбир, пломбир кофейный/</font></td>
        <td id="i_second" colspan="2">50</td>
        <td id="i_second" colspan="2">5-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>закажите к десерту:</i><br></td></tr>
    <tr>
        <td id="i_first"><b>орех миндальный</b></td>
        <td id="i_second" colspan="2">25</td>
        <td id="i_second" colspan="2">4-50</td>
    </tr>
    <tr>
        <td id="i_first"><b>орех грецкий</b></td>
        <td id="i_second" colspan="2">25</td>
        <td id="i_second" colspan="2">2-50</td>
    </tr>
    <tr>
        <td id="i_first"><b>изюм</b></td>
        <td id="i_second" colspan="2">25</td>
        <td id="i_second" colspan="2">2-50</td>
    </tr>
    <tr>
        <td id="i_first"><b>сливки</b></td>
        <td id="i_second" colspan="2">50</td>
        <td id="i_second" colspan="2">2-50</td>
    </tr>
    <tr>
        <td id="i_first"><b>шоколад тертый</b></td>
        <td id="i_second" colspan="2">25</td>
        <td id="i_second" colspan="2">2-50</td>
    </tr>
    <tr>
        <td id="i_first"><b>соус клубничный</b></td>
        <td id="i_second" colspan="2">25</td>
        <td id="i_second" colspan="2">2-50</td>
    </tr>
    <tr>
        <td id="i_first"><b>соус шоколадный</b></td>
        <td id="i_second" colspan="2">25</td>
        <td id="i_second" colspan="2">2-50</td>
    </tr>
    <tr>
        <td id="i_first"><b>соус киви</b></td>
        <td id="i_second" colspan="2">25</td>
        <td id="i_second" colspan="2">2-50</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><br><br><i>ПОСТНОЕ МЕНЮ</i><br></td></tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>ХОЛОДНЫЕ  ЗАКУСКИ</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Маринованные, соленые огурцы</b></td>
        <td id="i_second" colspan="2">100</td>
        <td id="i_second" colspan="2">7-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Маринованные, соленые помидоры</b></td>
        <td id="i_second" colspan="2">100</td>
        <td id="i_second" colspan="2">7-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Грибы маринованные</b></td>
        <td id="i_second" colspan="2">105</td>
        <td id="i_second" colspan="2">14-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Оливки, маслины</b></td>
        <td id="i_second" colspan="2">100</td>
        <td id="i_second" colspan="2">14-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Лимон с сахаром</b></td>
        <td id="i_second" colspan="2">50/20</td>
        <td id="i_second" colspan="2">4-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Закуска деликатесная</b></td>
        <td id="i_second" colspan="2">290</td>
        <td id="i_second" colspan="2">25-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>САЛАТЫ</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Салат "Весенний"</b><font style="font-size:14px;"><br>(Салат "Айсберг", "Лолло-Россо", помидоры, огурцы, перец болгарский, шампиньоны, укроп,масло растительное,оливковое,уксус "Бальзамик")</font></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">25-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Винегрет</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">14-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Салат из пекинской капусты</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">14-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Салат из квашеной капусты с маслом</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">14-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Салат из свежей капусты с маслом</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">14-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Салат из свежих помидоров и огурцов</b><font style="font-size:14px;"><br>(Свежие помидоры, огурцы с зелёным луком, заправленные нерафинированным растительным маслом.)</font></td>
        <td id="i_second" colspan="2">250</td>
        <td id="i_second" colspan="2">14-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>ПЕРВЫЕ БЛЮДА</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Суп овощной</b></td>
        <td id="i_second" colspan="2">400</td>
        <td id="i_second" colspan="2">12-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Суп-пюре с грибами</b></td>
        <td id="i_second" colspan="2">400</td>
        <td id="i_second" colspan="2">12-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Суп с чечевицей и баклажанами</b></td>
        <td id="i_second" colspan="2">400</td>
        <td id="i_second" colspan="2">15-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Лаваш</b></td>
        <td id="i_second" colspan="2">50</td>
        <td id="i_second" colspan="2">1-50</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>ВТОРЫЕ БЛЮДА/ГАРНИРЫ</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Грибы жареные по-домашнему</b></td>
        <td id="i_second" colspan="2">150</td>
        <td id="i_second" colspan="2">15-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Овощной микс</b></td>
        <td id="i_second" colspan="2">180</td>
         <td id="i_second" colspan="2">15-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Лобио</b><font style="font-size:14px;"><br>(фасоль,грибы,кинза)</font></td>
        <td id="i_second" colspan="2">155</td>
         <td id="i_second" colspan="2">15-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Овощное рагу с грибами</b><font style="font-size:14px;"><br>(Брокколи,морковь,помидор,перец болгарский,картофель)</font></td>
        <td id="i_second" colspan="2"></td>
        <td id="i_second" colspan="2">15-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Вареники с картофелем</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">10-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Вареники с капустой</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">10-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Картофель запеченый по-монастырски</b></td>
        <td id="i_second" colspan="2">325</td>
        <td id="i_second" colspan="2">15-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Каша гречневая с грибами</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">8-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Плов овощной</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">10-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Картофель "Фри"</b></td>
        <td id="i_second" colspan="2">100</td>
        <td id="i_second" colspan="2">9-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Картофель жаренный с грибами</b></td>
        <td id="i_second" colspan="2">175</td>
        <td id="i_second" colspan="2">15-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Картофель отварной с зеленью постный</b></td>
        <td id="i_second" colspan="2">180</td>
        <td id="i_second" colspan="2">6-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Крокеты картофельные</b></td>
        <td id="i_second" colspan="2">120</td>
        <td id="i_second" colspan="2">8-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Рис отварной постный</b></td>
        <td id="i_second" colspan="2">160</td>
        <td id="i_second" colspan="2">6-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Рис с овощами</b></td>
        <td id="i_second" colspan="2">150</td>
        <td id="i_second" colspan="2">8-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>ДЕСЕРТЫ</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Апельсины, бананы, яблоки, грейпфрут</b></td>
        <td id="i_second" colspan="2">100</td>
        <td id="i_second" colspan="2">4-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Киви</b></td>
        <td id="i_second" colspan="2">1 шт.</td>
        <td id="i_second" colspan="2">4-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Виноград</b></td>
        <td id="i_second" colspan="2">100</td>
        <td id="i_second" colspan="2">8-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Яблоко запеченое</b></td>
        <td id="i_second" colspan="2">160</td>
        <td id="i_second" colspan="2">10-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Орех миндальный</b></td>
        <td id="i_second" colspan="2">25</td>
        <td id="i_second" colspan="2">4-50</td>
    </tr>
    <tr>
        <td id="i_first"><b>Орех грецкий</b></td>
        <td id="i_second" colspan="2">25</td>
        <td id="i_second" colspan="2">2-20</td>
    </tr>
    <tr>
        <td id="i_first"><b>Изюм</b></td>
        <td id="i_second" colspan="2">25</td>
        <td id="i_second" colspan="2">1-50</td>
    </tr>
    <tr>
        <td id="i_first"><b>Блинчики фруктовые</b></td>
        <td id="i_second" colspan="2" colspan="2">280</td>
        <td id="i_second" colspan="2" colspan="2">18-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><br><br><br><i>АЛКОГОЛЬНЫЕ НАПИТКИ</i><br><br><br></td></tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><i>ВОДКА</i><br></td></tr>
    <tr>
        <td id="i_first"><i><center>Наименование</center></i></td>
        <td id="i_third"><font style="font-size:12px;">Объем мл</font></td>
        <td id="i_third"><font style="font-size:12px;">Цена за бутылку</font></td>
        <td id="i_third"><font style="font-size:12px;">Цена за 100 мл</font></td>
        <td id="i_third"><font style="font-size:12px;">Цена за 50 мл</font></td>
    </tr>
    <tr>
        <td id="i_first"><b>Русский стандарт</b></td>
        <td id="i_third">0,5</td>
        <td id="i_third">150-00</td>
        <td id="i_third">30-00</td>
        <td id="i_third">15-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Хортица</b><font style="font-size:14px;"><br>/Ви Ай Пи Клуб Платинум,Ви Ай Пи Клуб/</font></td>
        <td id="i_third">0,7</td>
        <td id="i_third">154-00</td>
        <td id="i_third">22-00</td>
        <td id="i_third">11-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Пульс</b><font style="font-size:14px;"><br>/Айс, Пауер/</font></td>
        <td id="i_third">0,5</td>
        <td id="i_third">55-00</td>
        <td id="i_third">11-00</td>
        <td id="i_third">5-50</td>
    </tr>
    <tr>
        <td id="i_first"><b>Пульс</b><font style="font-size:14px;"><br>/Актив, Элит/</font></td>
        <td id="i_third">0,5</td>
        <td id="i_third">50-00</td>
        <td id="i_third">10-00</td>
        <td id="i_third">5-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Хортица</b><font style="font-size:14px;"><br>/Серебрянная,Платинум,Классическая,Золотая,Премиум/</font></td>
        <td id="i_third">0,5</td>
        <td id="i_third">55-00</td>
        <td id="i_third">11-00</td>
        <td id="i_third">5-50</td>
    </tr>
    <tr>
        <td id="i_first"><b>Благов</b><font style="font-size:14px;"><br>/зеленое яблоко,премиум,оригинал/</font></td>
        <td id="i_third">0,5</td>
        <td id="i_third">50-00</td>
        <td id="i_third">10-00</td>
        <td id="i_third">5-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Хлебный дар</b></td>
        <td id="i_third">0,5</td>
        <td id="i_third">50-00</td>
        <td id="i_third">10-00</td>
        <td id="i_third">5-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><i>ТЕКИЛА</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Текила-Olmeca</b></td>
        <td id="i_third">1,0</td>
        <td id="i_third">400-00</td>
        <td id="i_third">40-00</td>
        <td id="i_third">20-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><i>НАСТОЙКА</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Абсент Ксента</b></td>
        <td id="i_third">1,0</td>
        <td id="i_third">550-00</td>
        <td id="i_third">55-00</td>
        <td id="i_third">27-50</td>
    </tr>
    <tr>
        <td id="i_first"><b>Бехеровка</b></td>
        <td id="i_third">1,0</td>
        <td id="i_third">250-00</td>
        <td id="i_third">25-00</td>
        <td id="i_third">12-50</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><i>ДЖИН</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Бифитер</b></td>
        <td id="i_third">1,0</td>
        <td id="i_third">400-00</td>
        <td id="i_third">40-00</td>
        <td id="i_third">20-00</td>
    </tr>
     <tr><td colspan="3" id="i_up" style="font-size:16px;"><i>РОМ</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Бакарди Блек</b></td>
        <td id="i_third">1,0</td>
        <td id="i_third">400-00</td>
        <td id="i_third">40-00</td>
        <td id="i_third">20-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Бакарди Карта Бланка</b></td>
        <td id="i_third">1,0</td>
        <td id="i_third">400-00</td>
        <td id="i_third">40-00</td>
        <td id="i_third">20-00</td>
    </tr>
     <tr><td colspan="3" id="i_up" style="font-size:16px;"><i>ВИСКИ</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Джон Уокер "Блек лейбл"</b></td>
        <td id="i_third">1,0</td>
        <td id="i_third">700-00</td>
        <td id="i_third">70-00</td>
        <td id="i_third">35-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Джон Уокер "Ред лейбл"</b></td>
        <td id="i_third">1,0</td>
        <td id="i_third">350-00</td>
        <td id="i_third">35-00</td>
        <td id="i_third">17-50</td>
    </tr>
     <tr>
        <td id="i_first"><b>Ханки Баннистер</b></td>
        <td id="i_third">1,0</td>
        <td id="i_third">300-00</td>
        <td id="i_third">30-00</td>
        <td id="i_third">15-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><i>КОНЬЯК</i><br></td></tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>Франция</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Хеннесси XO</b></td>
        <td id="i_third">0,7</td>
        <td id="i_third">2100-00</td>
        <td id="i_third">300-00</td>
        <td id="i_third">150-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Хеннесси VSOP</b></td>
        <td id="i_third">0,7</td>
        <td id="i_third">770-00</td>
        <td id="i_third">110-00</td>
        <td id="i_third">55-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>Армения</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Арарат *****</b></td>
        <td id="i_third">0,5</td>
        <td id="i_third">210-00</td>
        <td id="i_third">42-00</td>
        <td id="i_third">21-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Арарат ***</b></td>
        <td id="i_third">0,5</td>
        <td id="i_third">180-00</td>
        <td id="i_third">36-00</td>
        <td id="i_third">18-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>Украина</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Аскания ХО</b></td>
        <td id="i_third">0,7</td>
        <td id="i_third">364-00</td>
        <td id="i_third">52-00</td>
        <td id="i_third">26-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Георгиевский кавалер</b></td>
        <td id="i_third">0,7</td>
        <td id="i_third">273-00</td>
        <td id="i_third">39-00</td>
        <td id="i_third">19-50</td>
    </tr>
     <tr>
        <td id="i_first"><b>Алекс Платинум</b></td>
        <td id="i_third">0,5</td>
        <td id="i_third">300-00</td>
        <td id="i_third">60-00</td>
        <td id="i_third">30-00</td>
    </tr>
      <tr>
        <td id="i_first"><b>Алекс Голд</b></td>
        <td id="i_third">0,5</td>
        <td id="i_third">225-00</td>
        <td id="i_third">45-00</td>
        <td id="i_third">22-50</td>
    </tr>
       <tr>
        <td id="i_first"><b>Алекс Сильвер</b></td>
        <td id="i_third">0,5</td>
        <td id="i_third">180-00</td>
        <td id="i_third">36-00</td>
        <td id="i_third">18-00</td>
    </tr>
        <tr>
        <td id="i_first"><b>Клинков VS</b></td>
        <td id="i_third">0,5</td>
        <td id="i_third">185-00</td>
        <td id="i_third">37-00</td>
        <td id="i_third">18-50</td>
    </tr>
         <tr>
        <td id="i_first"><b>Шустов ECTE V,S,O,P</b></td>
        <td id="i_third">0,5</td>
        <td id="i_third">220-00</td>
        <td id="i_third">44-00</td>
        <td id="i_third">22-00</td>
    </tr>
          <tr>
        <td id="i_first"><b>Шустов ECTE V,V,S,O,P</b></td>
        <td id="i_third">0,5</td>
        <td id="i_third">260-00</td>
        <td id="i_third">52-00</td>
        <td id="i_third">26-00</td>
    </tr>
           <tr>
        <td id="i_first"><b>Шустов ECTE X,O,</b></td>
        <td id="i_third">0,5</td>
        <td id="i_third">330-00</td>
        <td id="i_third">66-00</td>
        <td id="i_third">33-00</td>
    </tr>
            <tr>
        <td id="i_first"><b>Каховский VS /3 года/</b></td>
        <td id="i_third">0,5</td>
        <td id="i_third">70-00</td>
        <td id="i_third">14-00</td>
        <td id="i_third">7-00</td>
    </tr>
             <tr>
        <td id="i_first"><b>Борисфен /4 года/</b></td>
        <td id="i_third">0,5</td>
        <td id="i_third">80-00</td>
        <td id="i_third">16-00</td>
        <td id="i_third">8-00</td>
    </tr>
              <tr>
        <td id="i_first"><b>Шустов 5*</b></td>
        <td id="i_third">0,5</td>
        <td id="i_third">110-00</td>
        <td id="i_third">22-00</td>
        <td id="i_third">11-00</td>
    </tr>
               <tr>
        <td id="i_first"><b>Шустов 4*</b></td>
        <td id="i_third">0,5</td>
        <td id="i_third">90-00</td>
        <td id="i_third">18-00</td>
        <td id="i_third">9-00</td>
    </tr>
                <tr>
        <td id="i_first"><b>Шустов 3*</b></td>
        <td id="i_third">0,5</td>
        <td id="i_third">80-00</td>
        <td id="i_third">16-00</td>
        <td id="i_third">8-00</td>
    </tr>
                 <tr>
        <td id="i_first"><b>Десна 4*</b></td>
        <td id="i_third">0,5</td>
        <td id="i_third">80-00</td>
        <td id="i_third">16-00</td>
        <td id="i_third">8-00</td>
    </tr>
                  <tr>
        <td id="i_first"><b>Одесский 3*</b></td>
        <td id="i_third">0,5</td>
        <td id="i_third">70-00</td>
        <td id="i_third">14-00</td>
        <td id="i_third">7-00</td>
    </tr>
                   <tr>
        <td id="i_first"><b>Бучач 5*</b></td>
        <td id="i_third">0,61</td>
        <td id="i_third">122-00</td>
        <td id="i_third">20-00</td>
        <td id="i_third">10-00</td>
    </tr>
         <tr>
        <td id="i_first"><b>Гринвич 5*</b></td>
        <td id="i_third">0,5</td>
        <td id="i_third">90-00</td>
        <td id="i_third">18-00</td>
        <td id="i_third">9-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Гринвич 4*</b></td>
        <td id="i_third">0,5</td>
        <td id="i_third">80-00</td>
        <td id="i_third">16-00</td>
        <td id="i_third">8-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><i>ЛИКЕРЫ</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Самбука</b></td>
        <td id="i_third">1,0</td>
        <td id="i_third">400-00</td>
        <td id="i_third">40-00</td>
        <td id="i_third">20-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Бэйлис</b></td>
        <td id="i_third">1,0</td>
        <td id="i_third">400-00</td>
        <td id="i_third">40-00</td>
        <td id="i_third">20-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Куантро</b></td>
        <td id="i_third">1,0</td>
        <td id="i_third">400-00</td>
        <td id="i_third">40-00</td>
        <td id="i_third">20-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Малибу</b></td>
        <td id="i_third">1,0</td>
        <td id="i_third">400-00</td>
        <td id="i_third">40-00</td>
        <td id="i_third">20-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Калуа кофейный</b></td>
        <td id="i_third">1,0</td>
        <td id="i_third">400-00</td>
        <td id="i_third">40-00</td>
        <td id="i_third">20-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Де Кайпер</b> /мятный/блю-кюрасао/дыня/персик/зеленый банан/</td>
        <td id="i_third">0,7</td>
        <td id="i_third">280-00</td>
        <td id="i_third">40-00</td>
        <td id="i_third">20-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><i>ШАМПАНСКОЕ</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Крым</b> /белое полусухое/</td>
        <td id="i_third">0,75</td>
        <td id="i_third">80-00</td>
        <td id="i_third"></td>
        <td id="i_third"></td>
    </tr>
    <tr>
        <td id="i_first"><b>Крым</b> /красное полусладкое/</td>
        <td id="i_third">0,75</td>
        <td id="i_third">90-00</td>
        <td id="i_third"></td>
        <td id="i_third"></td>
    </tr>
    <tr>
        <td id="i_first"><b>Артемовское</b> /белое полусладкое/</td>
        <td id="i_third">0,75</td>
        <td id="i_third">70-00</td>
        <td id="i_third"></td>
        <td id="i_third"></td>
    </tr>
    <tr>
        <td id="i_first"><b>Для Влюбленных</b> /бел п/сл/</td>
        <td id="i_third">0,75</td>
        <td id="i_third">50-00</td>
        <td id="i_third"></td>
        <td id="i_third"></td>
    </tr>
    <tr>
        <td id="i_first"><b>Ореанда</b> кр/п/сл</td>
        <td id="i_third">0,75</td>
        <td id="i_third">60-00</td>
        <td id="i_third"></td>
        <td id="i_third"></td>
    </tr>
    <tr>
        <td id="i_first"><b>Ореанда</b> бел/п/сл</td>
        <td id="i_third">0,75</td>
        <td id="i_third">55-00</td>
        <td id="i_third"></td>
        <td id="i_third"></td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><i>ВЕРМУТ</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Кампари</b></td>
        <td id="i_third">1,0</td>
        <td id="i_third">320-00</td>
        <td id="i_third">32-00</td>
        <td id="i_third">16-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Мартини "Экстра драй"</b></td>
        <td id="i_third">1,0</td>
        <td id="i_third">200-00</td>
        <td id="i_third">20-00</td>
        <td id="i_third">10-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Мартини "Россо"</b></td>
        <td id="i_third">1,0</td>
        <td id="i_third">200-00</td>
        <td id="i_third">20-00</td>
        <td id="i_third">10-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Мартини "Бьянко"</b></td>
        <td id="i_third">1,0</td>
        <td id="i_third">200-00</td>
        <td id="i_third">20-00</td>
        <td id="i_third">10-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><i>ВИНО</i><br></td></tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>"Крымское марочное" /Украина/</i><br></td></tr>
     <tr>
        <td id="i_first"><b>Каберне</b> /ореанда резерв/сух крас/</td>
        <td id="i_third">0,75</td>
        <td id="i_third">95-00</td>
        <td id="i_third"></td>
        <td id="i_third"></td>
    </tr>
     <tr>
        <td id="i_first"><b>Шардоне</b> /ореанда резерв/сух бел/</td>
        <td id="i_third">0,75</td>
        <td id="i_third">90-00</td>
        <td id="i_third"></td>
        <td id="i_third"></td>
    </tr>
     <tr>
        <td id="i_first"><b>Крымское красное</b> /кр.п/сл марочное/</td>
        <td id="i_third">0,75</td>
        <td id="i_third">60-00</td>
        <td id="i_third">8-00</td>
        <td id="i_third">4-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Мерло Феодосийское</b> / кр. п/сух марочное/</td>
        <td id="i_third">0,75</td>
        <td id="i_third">60-00</td>
        <td id="i_third">8-00</td>
        <td id="i_third">4-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Шардоне Крымское</b> /бел п/сл марочное/</td>
        <td id="i_third">0,75</td>
        <td id="i_third">60-00</td>
        <td id="i_third">8-00</td>
        <td id="i_third">4-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>"Инкерман"/Украина/</i><br></td></tr>
     <tr>
        <td id="i_first"><b>Жемчужина Инкермана</b> бел/сух</td>
        <td id="i_third">0,75</td>
        <td id="i_third">60-00</td>
        <td id="i_third"></td>
        <td id="i_third"></td>
    </tr>
      <tr>
        <td id="i_first"><b>Рубин Херсонеса</b> кр/сух</td>
        <td id="i_third">0,75</td>
        <td id="i_third">60-00</td>
        <td id="i_third"></td>
        <td id="i_third"></td>
    </tr>
       <tr>
        <td id="i_first"><b>Инкерман</b> кр/п/сух</td>
        <td id="i_third">0,75</td>
        <td id="i_third">60-00</td>
        <td id="i_third"></td>
        <td id="i_third"></td>
    </tr>
        <tr>
        <td id="i_first"><b>Инкерман</b> бел/п/сух</td>
        <td id="i_third">0,75</td>
        <td id="i_third">60-00</td>
        <td id="i_third"></td>
        <td id="i_third"></td>
    </tr>
         <tr>
        <td id="i_first"><b>Легенда Инкермана</b> бел/п/сл</td>
        <td id="i_third">0,75</td>
        <td id="i_third">60-00</td>
        <td id="i_third"></td>
        <td id="i_third"></td>
    </tr>
          <tr>
        <td id="i_first"><b>Пино Нуар Крымский</b> кр/п/сл</td>
        <td id="i_third">0,75</td>
        <td id="i_third">60-00</td>
        <td id="i_third"></td>
        <td id="i_third"></td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>"Голицинские вина"/Украина/</i><br></td></tr>
     <tr>
        <td id="i_first"><b>Бастардо Юбилейное</b> кр/ дес</td>
        <td id="i_third">0,75</td>
        <td id="i_third">46-00</td>
        <td id="i_third"></td>
        <td id="i_third"></td>
    </tr>
      <tr>
        <td id="i_first"><b>Каберне</b> кр/сух</td>
        <td id="i_third">0,75</td>
        <td id="i_third">43-00</td>
        <td id="i_third"></td>
        <td id="i_third"></td>
    </tr>
       <tr>
        <td id="i_first"><b>Мускат таврический</b> бел/дес</td>
        <td id="i_third">0,75</td>
        <td id="i_third">46-00</td>
        <td id="i_third"></td>
        <td id="i_third"></td>
    </tr>
        <tr>
        <td id="i_first"><b>Пино-Фран</b> кр/ п/сл</td>
        <td id="i_third">0,75</td>
        <td id="i_third">41-00</td>
        <td id="i_third"></td>
        <td id="i_third"></td>
    </tr>
         <tr>
        <td id="i_first"><b>Совиньон</b> бел/сух</td>
        <td id="i_third">0,75</td>
        <td id="i_third">35-00</td>
        <td id="i_third"></td>
        <td id="i_third"></td>
    </tr>
          <tr>
        <td id="i_first"><b>Шардоне</b> бел/п/сл</td>
        <td id="i_third">0,75</td>
        <td id="i_third">39-00</td>
        <td id="i_third"></td>
        <td id="i_third"></td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>"Картули Вази"/Грузия/</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Алазанская долина</b> бел/п/сл</td>
        <td id="i_third">0,75</td>
        <td id="i_third">120-00</td>
        <td id="i_third">16-00</td>
        <td id="i_third">8-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Алазанская долина</b> кр/п/сл</td>
        <td id="i_third">0,75</td>
        <td id="i_third">135-00</td>
        <td id="i_third">18-00</td>
        <td id="i_third">9-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Киндзмараули</b> кр/п/сл</td>
        <td id="i_third">0,75</td>
        <td id="i_third">300-00</td>
        <td id="i_third">40-00</td>
        <td id="i_third">20-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Мерани</b> бел/п/сух</td>
        <td id="i_third">0,75</td>
       <td id="i_third">135-00</td>
        <td id="i_third">18-00</td>
        <td id="i_third">9-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Пиросмани</b> кр/п/сух</td>
        <td id="i_third">0,75</td>
        <td id="i_third">135-00</td>
        <td id="i_third">18-00</td>
        <td id="i_third">9-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Саперави</b> кр/сух</td>
        <td id="i_third">0,75</td>
        <td id="i_third">120-00</td>
        <td id="i_third">16-00</td>
        <td id="i_third">8-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Твиши</b> бел/п/сл</td>
        <td id="i_third">0,75</td>
        <td id="i_third">195-00</td>
        <td id="i_third">26-00</td>
        <td id="i_third">13-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Хванчкара</b> кр п/сл</td>
        <td id="i_third">0,75</td>
        <td id="i_third">322-50</td>
        <td id="i_third">43-00</td>
        <td id="i_third">21-50</td>
    </tr>
    <tr>
        <td id="i_first"><b>Цинандали</b> б/сух</td>
        <td id="i_third">0,75</td>
        <td id="i_third">120-00</td>
        <td id="i_third">16-00</td>
        <td id="i_third">8-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:14px;"><i>"Лозано" /Испания/</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Лозано</b> кр/сух</td>
        <td id="i_third">0,75</td>
        <td id="i_third">75-00</td>
        <td id="i_third">10-00</td>
        <td id="i_third">5-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Кабальерос де ла Роса</b></td>
        <td id="i_third">0,75</td>
        <td id="i_third">75-00</td>
        <td id="i_third">10-00</td>
        <td id="i_third">5-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Бланко</b> б/п/сл</td>
        <td id="i_third">0,75</td>
        <td id="i_third">75-00</td>
        <td id="i_third">10-00</td>
        <td id="i_third">5-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><br><br><br><i>КОКТЕЙЛИ</i><br><br><br></td></tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><i>short drinks</i><br></td></tr>
    <tr>
        <td id="i_first"><b>Стейк-Хауз</b><font style="font-size:14px;"><br>белис, куантро,ликер де-кайпер блю кюрасао, де ментол</font></td>
        <td id="i_second" colspan="2">110</td>
        <td id="i_second" colspan="2">47-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>В-52</b><font style="font-size:14px;"><br>калуа, бейлис, куантро</font></td>
        <td id="i_second" colspan="2">60</td>
        <td id="i_second" colspan="2">26-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Хиросима</b><font style="font-size:14px;"><br>самбука, бейлис, абсент, гренадин</font></td>
        <td id="i_second" colspan="2">50</td>
        <td id="i_second" colspan="2">23-50</td>
    </tr>
    <tr>
        <td id="i_first"><b>Дядя Вася</b><font style="font-size:14px;"><br>гренадин, лайм,водка</font></td>
        <td id="i_second" colspan="2">60</td>
        <td id="i_second" colspan="2">12-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Смерть на 3 этаже</b><font style="font-size:14px;"><br>самбука, абсент, гренадин, лимонный фреш</font></td>
        <td id="i_second" colspan="2">65</td>
        <td id="i_second" colspan="2">26-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Зеленый мексиканец</b><font style="font-size:14px;"><br>ликер зеленый банан, лимонный фреш, текила</font></td>
        <td id="i_second" colspan="2">60</td>
        <td id="i_second" colspan="2">23-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Ломбарджини</b><font style="font-size:14px;"><br>абсент, гренадин,бейлис, де кайпер,куантро,текила,сливки</font></td>
        <td id="i_second" colspan="2">100</td>
        <td id="i_second" colspan="2">31-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Коматоз</b><font style="font-size:14px;"><br>джин Бифитер, абсент, самбука, куантро</font></td>
        <td id="i_second" colspan="2">80</td>
        <td id="i_second" colspan="2">37-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Баскетбол</b><font style="font-size:14px;"><br>коньяк, куантро</font></td>
        <td id="i_second" colspan="2">50</td>
        <td id="i_second" colspan="2">25-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><i>long drinks</i><br></td></tr>
     <tr>
        <td id="i_first"><b>Лонг Айленд</b><font style="font-size:14px;"><br>ром, текила, джин, водка, куантро, лимон джус, кола</font></td>
        <td id="i_second" colspan="2">230</td>
        <td id="i_second" colspan="2">30-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Дынный шар</b><font style="font-size:14px;"><br>водка, ликер Де Кайпер дыня, апельсиновый сок, вишня, апельсин</font></td>
        <td id="i_second" colspan="2">230</td>
        <td id="i_second" colspan="2">24-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Кокон</b><font style="font-size:14px;"><br>Самбука, лимонный фреш, кола-кола,  сироп лимона</font></td>
        <td id="i_second" colspan="2">220</td>
        <td id="i_second" colspan="2">28-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Пина Колада</b><font style="font-size:14px;"><br>ром Баккарди Карта Бланка, ананасовый сок, ликер Малибу, сливки, вишня</font></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">35-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Секс на пляже</b><font style="font-size:14px;"><br>водка, л-р персиковый, апельсиновый сок, гренадин,апельсин, вишня</font></td>
        <td id="i_second" colspan="2">260</td>
        <td id="i_second" colspan="2">31-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Голубая лагуна</b><font style="font-size:14px;"><br>спрайт, блю кюрасао, малибу, водка, апельсин, вишня</font></td>
        <td id="i_second" colspan="2">180</td>
        <td id="i_second" colspan="2">30-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Карибское чудо</b><font style="font-size:14px;"><br>л-р Де Кайпер дыня, сок ананасовый, ром Баккарди Блек</font></td>
        <td id="i_second" colspan="2">135</td>
        <td id="i_second" colspan="2">18-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Мохито</b><font style="font-size:14px;"><br>ром Баккарди Карта Бланка,спрайт, лайм, сироп, мята, ликер</font></td>
        <td id="i_second" colspan="2">400</td>
        <td id="i_second" colspan="2">36-00</td>
    </tr>
     <tr><td colspan="3" id="i_up" style="font-size:16px;"><i>hot drinks</i><br></td></tr>
     <tr>
        <td id="i_first"><b>Глинтвейн красный</b><font style="font-size:14px;"><br>вино Крымское красное,ром Баккарди Блек,апельсин,лимон,мед,корица,гвоздика</font></td>
        <td id="i_second" colspan="2">230</td>
        <td id="i_second" colspan="2">28-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Глинтвейн белый</b><font style="font-size:14px;"><br>вино Шардоне Крымское ,ром Баккарди Блек,апельсин,лимон,мед,корица,гвоздика</font></td>
        <td id="i_second" colspan="2">230</td>
        <td id="i_second" colspan="2">28-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Грог яблочный</b><font style="font-size:14px;"><br>ром, яблочный сок, корица, гвоздика, лимон, апельсин, яблоко</font></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">25-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Кофе "Белис"</b><font style="font-size:14px;"><br>горячий кофе с ликером белис и сливками</font></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">18-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Кофе "Калуа"</b><font style="font-size:14px;"><br>горячий кофе с ликером калуа и сливками</font></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">18-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Кофе "Виски"</b><font style="font-size:14px;"><br>горячий кофе с виски и сливками</font></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">18-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Кофе "Александр"</b><font style="font-size:14px;"><br>горячий кофе с коньяком, ромом, сливками</font></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">18-00</td>
    </tr>
     <tr><td colspan="3" id="i_up" style="font-size:16px;"><br><br><br><i>ШОКОЛАД</i><br><br><br></td></tr>
     <tr>
        <td id="i_first"><b>Конфеты “Raffaello”</b></td>
        <td id="i_second" colspan="2">1 шт.</td>
        <td id="i_second" colspan="2">3-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Шоколад "Корона"</b></td>
        <td id="i_second" colspan="2">100</td>
        <td id="i_second" colspan="2">15-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Мёд</b></td>
        <td id="i_second" colspan="2">50</td>
        <td id="i_second" colspan="2">5-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Сироп Гренадин</b></td>
        <td id="i_second" colspan="2">100</td>
        <td id="i_second" colspan="2">15-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Сироп Лайм</b></td>
        <td id="i_second" colspan="2">100</td>
        <td id="i_second" colspan="2">15-00</td>
    </tr>
     <tr><td colspan="3" id="i_up" style="font-size:16px;"><br><br><br><i>ЧАЙ</i><br><br><br></td></tr>
     <tr>
        <td id="i_first"><b>Чай черный заварной:</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">10-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>"Ассам"</b><font style="font-size:14px;"><br>черный индийский чай из штата Ассам, с острым крепким вкусом и терпким ароматом</font></td>
        <td id="i_second" colspan="2"></td>
        <td id="i_second" colspan="2"></td>
    </tr>
     <tr>
        <td id="i_first"><b>Чай зеленый заварной:</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">10-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>"Гавайский букет"</b><font style="font-size:14px;"><br>чай зеленый Шуи Ли,цветки чайной хризантемы,лепестки подсолнуха, со вкусом сливок</font></td>
        <td id="i_second" colspan="2"></td>
        <td id="i_second" colspan="2"></td>
    </tr>
    <tr>
        <td id="i_first"><b>"Жасмин-Молихуа"</b><font style="font-size:14px;"><br>крупнолистовой отборный зеленый чай, цветки жасмина</font></td>
        <td id="i_second" colspan="2"></td>
        <td id="i_second" colspan="2"></td>
    </tr>
    <tr>
        <td id="i_first"><b>"Саусеп"</b><font style="font-size:14px;"><br>зеленый чай с экзотическим фруктом саусеп</font></td>
        <td id="i_second" colspan="2"></td>
        <td id="i_second" colspan="2"></td>
    </tr>
     <tr>
        <td id="i_first"><b>Чай травяной:</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">10-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>"Энергия жизни"</b><font style="font-size:14px;"><br>натуральная смесь, состоящая из ройбуша, кусочков яблок, корня женьшеня и имбиря,  листьев лимонника и омелы, бобовых,корицы, гвоздики, кардамона, черного перца и цедры лимона</font></td>
        <td id="i_second" colspan="2"></td>
        <td id="i_second" colspan="2"></td>
    </tr>
    <tr>
        <td id="i_first"><b>Чай фруктовый заварной:</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">10-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>"Наглый фрукт" </b><font style="font-size:14px;"><br>кусочки яблок,  папайи, гибискус, смородина, шиповник, бузина, голубика, ароматизатор ежевики</font></td>
        <td id="i_second" colspan="2"></td>
        <td id="i_second" colspan="2"></td>
    </tr>
    <tr>
        <td id="i_first"><b>"Вишневый сад" </b><font style="font-size:14px;"><br> каркаде, кусочки шиповника, яблока и вишни, цедра апельсина и лимона, лепестки розы и сафлора</font></td>
        <td id="i_second" colspan="2"></td>
        <td id="i_second" colspan="2"></td>
    </tr>
     <tr>
        <td id="i_first"><b>"Айс-ти"</b></td>
        <td id="i_second" colspan="2">300</td>
        <td id="i_second" colspan="2">16-00</td>
    </tr>
     <tr><td colspan="3" id="i_up" style="font-size:16px;"><br><br><br><i>КОФЕ</i><br><br><br></td></tr>
    <tr>
        <td id="i_first"><b>"Кофе-айс"</b><font style="font-size:14px;"><br>холодный кофе</font></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">16-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Кофе "POLI"</b><font style="font-size:14px;"><br>эспрессо, американо</font></td>
        <td id="i_second" colspan="2">50</td>
        <td id="i_second" colspan="2">10-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Кофе "Буонди"</b> (зерно)<font style="font-size:14px;"><br>эспрессо, американо</font></td>
        <td id="i_second" colspan="2">50</td>
        <td id="i_second" colspan="2">10-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Капучино "Буонди"</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">12-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Кофе "Латте Буонди"</b><font style="font-size:14px;"><br>с сиропом: шоколад, ваниль, амаретто</font></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">15-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Кофе  "Гляссе Буонди"</b><font style="font-size:14px;"><br>горячий кофе с мороженым</font></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">12-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Горячий шоколад</b></td>
        <td id="i_second" colspan="2">75</td>
        <td id="i_second" colspan="2">10-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><br><br><br><i>НАПИТКИ НЕСТЛЕ</i><br><br><br></td></tr>
    <tr>
        <td id="i_first"><b>Кофе Ристретто</b></td>
        <td id="i_second" colspan="2">110</td>
        <td id="i_second" colspan="2">4-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Кофе Ристретто с молоком</b></td>
        <td id="i_second" colspan="2">110</td>
        <td id="i_second" colspan="2">5-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Американо Ристретто</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">6-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Американо Ристретто с молоком</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">8-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Капучино Ристретто</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">10-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Латте Ристретто</b></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">12-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Мокачино</b></td>
        <td id="i_second" colspan="2">110</td>
        <td id="i_second" colspan="2">8-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Шоколадный напиток</b></td>
        <td id="i_second" colspan="2">110</td>
        <td id="i_second" colspan="2">6-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><br><br><br><i>МИНЕРАЛЬНАЯ ВОДА, НАПИТКИ</i><br><br><br></td></tr>
    <tr>
        <td id="i_first"><b>Ессентуки</b> /№2, №4, №17/</td>
        <td id="i_second" colspan="2">0,5</td>
        <td id="i_second" colspan="2">14-00</td>
    </tr>
     <tr>
        <td id="i_first"><b>Боржоми</b> /газированная/</td>
        <td id="i_second" colspan="2">0,5</td>
        <td id="i_second" colspan="2">16-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Бонаква</b> /газированная, негазированная/</td>
        <td id="i_second" colspan="2">0,5</td>
        <td id="i_second" colspan="2">7-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Бонаква</b> /газированная, негазированная/</td>
        <td id="i_second" colspan="2">0,25</td>
        <td id="i_second" colspan="2">6-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Тоник</b> /Швепс/</td>
        <td id="i_second" colspan="2">0,5</td>
        <td id="i_second" colspan="2">8-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Кока-кола</b></td>
        <td id="i_second" colspan="2">0,5</td>
        <td id="i_second" colspan="2">8-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Фанта</b></td>
        <td id="i_second" colspan="2">0,5</td>
        <td id="i_second" colspan="2">8-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Спрайт</b></td>
        <td id="i_second" colspan="2">0,5</td>
        <td id="i_second" colspan="2">8-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Кока-кола , фанта, спрайт</b></td>
        <td id="i_second" colspan="2">0,25</td>
        <td id="i_second" colspan="2">6-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Энергетический напиток "Burn"</b></td>
        <td id="i_second" colspan="2">0,25</td>
        <td id="i_second" colspan="2">17-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><br><br><br><i>СОК</i><br><br><br></td></tr>
    <tr>
        <td id="i_first"><b>Сок "Rich"вишневый,ананасовый,апельсиновый</b></td>
        <td id="i_second" colspan="2">1,00</td>
        <td id="i_second" colspan="2">20-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Сок "Rich" мультифрукт, экзотик, зеленое, красное яблоко, клюква, виноград красный, белый, томатный, банан-клубника, манго</b></td>
        <td id="i_second" colspan="2">0,2</td>
        <td id="i_second" colspan="2">5-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><br><br><br><i>СОК-ФРЕШ</i><br><br><br></td></tr>
    <tr>
        <td id="i_first"><b>Апельсиновый</b></td>
        <td id="i_second" colspan="2">250</td>
        <td id="i_second" colspan="2">20-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Грейпфрутовый</b></td>
        <td id="i_second" colspan="2">250</td>
        <td id="i_second" colspan="2">20-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Грейпфрутово-апельсиновый</b></td>
        <td id="i_second" colspan="2">250</td>
        <td id="i_second" colspan="2">20-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Лимонный</b></td>
        <td id="i_second" colspan="2">250</td>
        <td id="i_second" colspan="2">20-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Яблочный</b></td>
        <td id="i_second" colspan="2">250</td>
        <td id="i_second" colspan="2">20-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Морковный</b></td>
        <td id="i_second" colspan="2">250</td>
        <td id="i_second" colspan="2">20-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Яблочно-морковный</b></td>
        <td id="i_second" colspan="2">250</td>
        <td id="i_second" colspan="2">20-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Свекольно-яблочно-морковный</b></td>
        <td id="i_second" colspan="2">250</td>
        <td id="i_second" colspan="2">20-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Киви</b></td>
        <td id="i_second" colspan="2">250</td>
        <td id="i_second" colspan="2">22-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><br><br><br><i>БЕЗАЛКОГОЛЬНЫЕ КОКТЕЙЛИ</i><br><br><br></td></tr>
    <tr>
        <td id="i_first"><b>Киськины лапки</b><font style="font-size:14px;"><br>(апельсин,грейпфрут,ананас соки,гренадин)</font></td>
        <td id="i_second" colspan="2">170</td>
        <td id="i_second" colspan="2">7-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Айс-Крим</b><font style="font-size:14px;"><br>(сок,мороженое)</font></td>
        <td id="i_second" colspan="2">200</td>
        <td id="i_second" colspan="2">8-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Коктейль молочный</b><font style="font-size:14px;"><br>(молоко,мороженое,сливки,гренадин)</font></td>
        <td id="i_second" colspan="2">320</td>
        <td id="i_second" colspan="2">16-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Коктейль молочный с соком</b><font style="font-size:14px;"><br>(мороженое,сок,сливки)</font></td>
        <td id="i_second" colspan="2">320</td>
        <td id="i_second" colspan="2">16-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Мохито  б/а</b><font style="font-size:14px;"><br>(спрайт,сироп,мята,лайм,лед)</font></td>
        <td id="i_second" colspan="2">400</td>
        <td id="i_second" colspan="2">25-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><br><br><br><i>ЗАКУСКА К ПИВУ</i><br><br><br></td></tr>
    <tr>
        <td id="i_first"><b>Кальмары сушеные ,кольца кальмара</b></td>
        <td id="i_second" colspan="2">40</td>
        <td id="i_second" colspan="2">12-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Рыбка к пиву</b></td>
        <td id="i_second" colspan="2">40</td>
        <td id="i_second" colspan="2">14-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Чипсы</b></td>
        <td id="i_second" colspan="2">25</td>
        <td id="i_second" colspan="2">5-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Фисташки</b></td>
        <td id="i_second" colspan="2">80</td>
        <td id="i_second" colspan="2">23-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Арахис соленый</b></td>
        <td id="i_second" colspan="2">125</td>
        <td id="i_second" colspan="2">18-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Сухарики ржаные</b></td>
        <td id="i_second" colspan="2">40</td>
        <td id="i_second" colspan="2">4-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><br><br><br><i>ПИВО</i><br><br><br></td></tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><i>Пиво-Кег разливное:</i><br></td></tr>
    <tr>
        <td id="i_first"><b>"Черниговское Светлое"</b></td>
        <td id="i_second" colspan="2">0,5</td>
        <td id="i_second" colspan="2">8-00</td>
    </tr>
    <tr>
        <td id="i_first"><b></b></td>
        <td id="i_second" colspan="2">0,33</td>
        <td id="i_second" colspan="2">5-28</td>
    </tr>
    <tr>
        <td id="i_first"><b>"Белое Черниговское”</b></td>
        <td id="i_second" colspan="2">0,5</td>
        <td id="i_second" colspan="2">9-00</td>
    </tr>
    <tr>
        <td id="i_first"><b></b></td>
        <td id="i_second" colspan="2">0,33</td>
        <td id="i_second" colspan="2">5-94</td>
    </tr>
     <tr>
        <td id="i_first"><b>"Старопрамен"</b></td>
        <td id="i_second" colspan="2">0,5</td>
        <td id="i_second" colspan="2">11-00</td>
    </tr>
    <tr>
        <td id="i_first"><b></b></td>
        <td id="i_second" colspan="2">0,33</td>
        <td id="i_second" colspan="2">7-26</td>
    </tr>
     <tr>
        <td id="i_first"><b>"Стела Артуа"</b></td>
        <td id="i_second" colspan="2">0,5</td>
        <td id="i_second" colspan="2">12-00</td>
    </tr>
    <tr>
        <td id="i_first"><b></b></td>
        <td id="i_second" colspan="2">0,33</td>
        <td id="i_second" colspan="2">7-92</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><i>Пиво бутылочное:</i><br></td></tr>
    <tr>
        <td id="i_first"><b>“Левенбрау”</b><font style="font-size:14px;"><br>светлое</font></td>
        <td id="i_second" colspan="2">0,33</td>
        <td id="i_second" colspan="2">17-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>"Хугарден"</b><font style="font-size:14px;"><br>нефильтрованное</font></td>
        <td id="i_second" colspan="2">0,33</td>
        <td id="i_second" colspan="2">17-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>“Лёфф”</b><font style="font-size:14px;"><br>светлое, темное</font></td>
        <td id="i_second" colspan="2">0,33</td>
        <td id="i_second" colspan="2">17-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><i>Пиво безалкогольное:</i><br></td></tr>
    <tr>
        <td id="i_first"><b>"Стела Артуа" Б/А</b></td>
        <td id="i_second" colspan="2">0,5</td>
        <td id="i_second" colspan="2">12-00</td>
    </tr>
    <tr><td colspan="3" id="i_up" style="font-size:16px;"><br><br><br><i>СЛАБОАЛКОГОЛЬНЫЕ  НАПИТКИ</i><br><br><br></td></tr>    
    <tr>
        <td id="i_first"><b>Экстрим</b></td>
        <td id="i_second" colspan="2">0,5</td>
        <td id="i_second" colspan="2">15-00</td>
    </tr>
    <tr>
        <td id="i_first"><b>Гоу</b></td>
        <td id="i_second" colspan="2">0,5</td>
        <td id="i_second" colspan="2">15-00</td>
    </tr>
</table>
</div>
</div>
<?php
}
else
   if ($_GET['pm'] == 3)
   {
?>

   <div class="catalogue_item_cont_m"> 
<img src="root/st_h/up.png" alt="" style="width: 100%;" />
<div id="div_st" style="height:550px;">
<p>
<div id="mm_menu" style="top:-205px;"><a href="index.php?business_full=395&amp;pm=1"  class="menu_text"><b>ГЛАВНАЯ</b></a></div>
<div id="mm_menu" style="top:-190px;"><a href="index.php?business_full=395&amp;pm=2" class="menu_text">МЕНЮ КАФЕ</a></div>
<div id="mm_menu" style="top:-175px;"><a href="index.php?business_full=395&amp;pm=3" class="menu_text">КОНТАКТЫ</a></div>
</p>
<br>

        <script src="http://api-maps.yandex.ru/1.1/index.xml?key=AAmDzUsBAAAARkVWCAIAXzMCgKN58_MQUqB134Sdp-unCH0AAAAAAAAAAACbJlz2mcKc4anRgbxx6LBZ5BHPyg==" type="text/javascript"></script>
    <script type="text/javascript">
        window.onload = function () {
            var map = new YMaps.Map(document.getElementById("YMapsID"));
            map.setCenter(new YMaps.GeoPoint(37.80947,48.006209), 14);

            var content = document.createElement('span');
            content.innerHTML = "«Стейк-Хауз»";
            map.openBalloon(new YMaps.GeoPoint(37.80947,48.006209), content);

            map.addControl(new YMaps.ToolBar());
            map.addControl(new YMaps.Zoom());
            map.addControl(new YMaps.MiniMap());
            map.addControl(new YMaps.ScaleLine());
        }
    </script>


	 <div id="YMapsID" style="width:100%;height:450px"></div>
   </div>
</div>
<?php
   } 
?>



<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="index.php?section_id=32&amp;business=1">Категория:</a></div>
</div>
<div class="catalogue_item_cont">
<a href="index.php?section_id=2&amp;business=1">бизнес</a>
 / 
<a href="index.php?section_id=32&amp;business=1">предприятия</a>
 / 
<a href="index.php?section_id=389&amp;business=2">отдых и развлечения</a>
 / 
<a href="index.php?section_id=390&amp;business=2">кафе и рестораны</a>
</div>


<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="">Фотогалегея:</a></div>
</div>
<div class="catalogue_item_cont">
<div class="catalogue_pic_l"><a href="root/st_h/gallery/1.jpg" target="_blank"><img src="root/st_h/gallery/1_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/st_h/gallery/2.jpg" target="_blank"><img src="root/st_h/gallery/2_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/st_h/gallery/3.jpg" target="_blank"><img src="root/st_h/gallery/3_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/st_h/gallery/4.jpg" target="_blank"><img src="root/st_h/gallery/4_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/st_h/gallery/5.jpg" target="_blank"><img src="root/st_h/gallery/5_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/st_h/gallery/6.jpg" target="_blank"><img src="root/st_h/gallery/6_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/st_h/gallery/7.jpg" target="_blank"><img src="root/st_h/gallery/7_s.jpg" width="60" height="60" border="0" alt=""></a></div>
</div>
<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="">Контактная информация:</div>
</div>
 <div class="catalogue_item_cont">
 		 <table width="100%">
			<tbody>
 			<tr>
			<!--	<td><img class="main_sec_image" src="" width="60" height="60" border="0" alt="" /></td>-->
				<td>Адрес:</td>
				<td>Телефон:</td>
				<td>Факс:</td>
				<td>E-mail:</td>
				<td>Веб-сайт:</td>
			</tr>
			<tr>
				<td>г. Донецк<br> пр.Театральный, 28</td>
				<td>(062)335-23-68</td>
				<td></td>
				<td></td>
				<td></td>

			</tr>
			</tbody> 
		 </table> 		
	 </div>
</div>  

