 <div class="catalogue_item_c">
<style>
.catalogue_item_cont p {
color:black;
margin:10px;
text-align:justify;
text-indent:0px;
}
.catalogue_item_cont {
background-color:#EBEBEB;
border-top:1px solid lightgray;
margin:0 0 7px 4px;
width:99%;
}
.catalogue_item_c {
background-color:#FFFFFF;
}
img.main_sec_image {
padding:0px;
width:250px;
height:160px;
}
.catalogue_item_cont a {
color:#10154F;
}
.catalogue_item_cont a:hover {
color:#FFFFFF;
}
.catalogue_item_mp_a {
left:-3px;
position:relative;
}

</style>
<?php
if ($_GET['pm'] == 1) 
{
?>

<div class="catalogue_item_cont"> 
<img src="root/evakuatory/up.png" alt="" style="width: 100%;" />
<div style="padding: 0pt 35px;">
<a href="index.php?business_full=392&amp;pm=1" style="font-size:16px;left:380px;position:relative;top:-340px;">Главная</a>
<a href="index.php?business_full=392&amp;pm=2" style="font-size:16px;left:200px;position:relative;top:-305px;">Техническая помощь<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; и эвакуаторы</a>
<a href="index.php?business_full=392&amp;pm=3" style="font-size:16px;left:105px;position:relative;top:-270px;">Контакты</a>
<p>Служба <font color="red"><b>“Техпомощь на дороге. Эвакуаторы”</b></font> основана в июне 1998 года. На текущий год служба насчитывает десять специально оборудованных автомобилей грузоподъемностью от 2,5 до 5 тонн. Также имеется спецмашина по перевозке одновременно 3-х автомобилей.</p>
<p>Служба имеет свою круглосуточную диспетчерскую.</p>
<p>Служба работает за наличный и безналичный расчет. Перевозки осуществляются по г. Донецку, Донецкой области, Украине, а также ближнему зарубежью.</p>
<img class="main_sec_image" src="root/evakuatory/e3.jpg" alt="" style="float: right;" /><br><br><p>Заказать эвакуатор можно круглосуточно, без выходных по телефону :
<br>С ГОРОДСКОГО, ДЛЯ АБОНЕНТОВ МТС и КИЕВСТАР ЕДИНЫЙ НОМЕР <font color="red" size="3">385-05-05</font>
<br>8(062)-385-05-05
<br>8(050)-385-05-05
<br>8(067)-385-05-05
<br>+38 (063) 333-09-90
<br>Факс +38 (062) 389-01-17</p><br>
<p>Для удобства клиентов заключены договора о сотрудничестве со многими страховыми кампаниями, а также станциями технического обслуживания автомобилей.</p>
<p>Эвакуатор можно заказать в любое место, в удобное для вас время. Специалисты службы окажут вам квалифицированную помощь.
</p>
<p>Мы ценим каждого клиента, но первоочередность в предоставлении наших услуг имеют компании, которые заключили с нами долгосрочный договор - эти компании получают постоянную скидку на все виды услуг.
</p>
<p>Для Вас мы можем включить в договор дополнительный пункт о вознаграждении (% от суммы заказа оплаченного Вашим клиентам).
</p>
<p><font color="red"><b>Мы рады Вам помочь!</b></font>
</p>
<p>Техпомощь на дороге Донецк, эвакуатор в Донецке, услуги эвакуатора, вызов эвакуатора, эвакуация авто, помощь на дорогах, эвакуация автомобилей Донецк.
</p>
<p>&nbsp;</p>
<table width="100%" style="padding:15px;">
			<tbody>
			<tr>
				<td>Украина, г.Донецк-100<br>ул.Профессоров Богославских, 49</td>
				<td>(062) 385-05-05 (многоканальный)<br>(062) 389-01-17</td>
				<td>evakuator@dn.farlep.net<br>www.avtosos.eurodonetsk.com</td>

			</tr>
			</tbody> 
		 </table> 
</div>
</div>

<?php
}
else
   if ($_GET['pm'] == 2)
   {
?>
<div class="catalogue_item_cont"> 
<img src="root/evakuatory/up.png" alt="" style="width: 100%;" />
<div style="padding: 0pt 35px;">
<a href="index.php?business_full=392&amp;pm=1" style="font-size:16px;left:380px;position:relative;top:-340px;">Главная</a>
<a href="index.php?business_full=392&amp;pm=2" style="font-size:16px;left:200px;position:relative;top:-305px;">Техническая помощь<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; и эвакуаторы</a>
<a href="index.php?business_full=392&amp;pm=3" style="font-size:16px;left:105px;position:relative;top:-270px;">Контакты</a>
<p><font color="red"><b>АВТОМОБИЛЬНАЯ ТЕХПОМОЩЬ НА ДОРОГЕ</b></font></p>
<p>На дороге случается всякое. Кто из нас не испытывал огорчение от долгих попыток завести свой безнадежно заглохший автомобиль. Сбои в электрике, поломка бензонасоса, обрыв ремня, блокировка сигнализации - со всем этим автомобилисты сталкиваются на дороге.</p>
<p>Главное не паниковать!</p>
<p>Мы готовы помочь Вам в любой ситуации. 24 часа в сутки без выходных и праздников. Мы можем предложить Вам, услуги по ремонту на месте или эвакуации автомобиля. Так как не всегда Вы можете оценить серьезность поломки и возможность ее устранения на месте, наш диспетчер поможет Вам решить, какая именно услуга Вам необходима.
</p><img class="main_sec_image" src="root/evakuatory/e1.jpg" alt="" style="float: right;height:130px;width:200px;" />
<ul style="list-style:none outside none;
margin-left:40px;
text-align:left;">
<li>- Разблокировка замка зажигания
</li>
<li>- Замена замка зажигания
</li>
<li>- Замена топливного насоса без съема бака
</li>
<li>- Замена топливного насоса со съемом бака
</li>
<li>- Замена колеса
</li>
<li>- Открытие заблокированных дверей без повреждения облицовки
</li>
<li>- Открытие багажника
</li>
<li>- Открытие капота
</li>
<li>- Работа с системой Худ-Лок
</li>
<li>- Замена АКБ
</li>
<li>- Подзарядка АКБ
</li>
<li>- Замена топливного фильтра
</li>
<li>- Замена шаровой опоры
</li>
<li>- Замена ремня ГРМ на иномарках
</li>
<li>- Работа с секретными и сорванными болтами на колесе
</li>
<li>- Работы с системой противоугонной сигнализации
</li>
</ul><img class="main_sec_image" src="root/evakuatory/e2.jpg" alt="" style="float: right;height:130px;width:200px;position:relative;top:-80px;" />
<p><p><font color="red"><b>ТРАНСПОРТИРОВКА АВАРИЙНЫХ И НЕИСПРАВНЫХ АВТО</b></font></p>
<p>К сожалению, не каждая, даже выглядящая на первый взгляд таковой, поломка, может быть устранена в полевых условиях.Мы это прекрасно знаем и поэтому наша служба техпомощи работает в тесной связке с эвакуатором.
</p>
<p>На Ваш вызов выезжает эвакуатор с техником, который и занимается ремонтом Вашего авто.
</p>
<p>Если же устранить поломку подручными средствами не представляется возможным, Вы можете сразу же воспользоваться услугами нашего эвакуатора.
</p>
<table width="100%" style="padding:15px;">
			<tbody>
			<tr>
				<td>Украина, г.Донецк-100<br>ул.Профессоров Богославских, 49</td>
				<td>(062) 385-05-05 (многоканальный)<br>(062) 389-01-17</td>
				<td>evakuator@dn.farlep.net<br>www.avtosos.eurodonetsk.com</td>

			</tr>
			</tbody> 
		 </table> 
</div>
</div>
<?php
}
else
   if ($_GET['pm'] == 3)
   {
?>

    <div class="catalogue_item_cont">
   <img src="root/evakuatory/up.png" alt="" style="width: 100%;" />
<a href="index.php?business_full=392&amp;pm=1" style="font-size:16px;left:380px;position:relative;top:-340px;">Главная</a>
<a href="index.php?business_full=392&amp;pm=2" style="font-size:16px;left:200px;position:relative;top:-305px;">Техническая помощь<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; и эвакуаторы</a>
<a href="index.php?business_full=392&amp;pm=3" style="font-size:16px;left:105px;position:relative;top:-270px;">Контакты</a>
        <script src="http://api-maps.yandex.ru/1.1/index.xml?key=AAmDzUsBAAAARkVWCAIAXzMCgKN58_MQUqB134Sdp-unCH0AAAAAAAAAAACbJlz2mcKc4anRgbxx6LBZ5BHPyg==" type="text/javascript"></script>
    <script type="text/javascript">
        window.onload = function () {
            var map = new YMaps.Map(document.getElementById("YMapsID"));
            map.setCenter(new YMaps.GeoPoint(37.768736,47.991943), 14);

            var content = document.createElement('span');
            content.innerHTML = "«Эвакуаторы»";
            map.openBalloon(new YMaps.GeoPoint(37.768736,47.991943), content);

            map.addControl(new YMaps.ToolBar());
            map.addControl(new YMaps.Zoom());
            map.addControl(new YMaps.MiniMap());
            map.addControl(new YMaps.ScaleLine());
        }
    </script>


	 <div id="YMapsID" style="width:100%;height:450px"></div>
   </div>

<?php
   } 
?>



<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="index.php?section_id=32&amp;business=1">Категория:</a></div>
</div>
<div class="catalogue_item_cont">
<a href="index.php?section_id=2&amp;business=1">бизнес</a>
 / 
<a href="index.php?section_id=32&amp;business=1">предприятия</a>
 / 
<a href="index.php?section_id=368&amp;business=2">услуги</a>
 / 
<a href="index.php?section_id=375&amp;business=2">транспорт, перевозки, логистика</a>
</div>

<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="">Фотогалерея:</a></div>
</div>
<div class="catalogue_item_cont">
<div class="catalogue_pic_l"><a href="root/evakuatory/gallery/1.jpg" target="_blank"><img src="root/evakuatory/gallery/1_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/evakuatory/gallery/2.jpg" target="_blank"><img src="root/evakuatory/gallery/2_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/evakuatory/gallery/3.jpg" target="_blank"><img src="root/evakuatory/gallery/3_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/evakuatory/gallery/4.jpg" target="_blank"><img src="root/evakuatory/gallery/4_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/evakuatory/gallery/5.jpg" target="_blank"><img src="root/evakuatory/gallery/5_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/evakuatory/gallery/6.JPG" target="_blank"><img src="root/evakuatory/gallery/6_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/evakuatory/gallery/7.JPG" target="_blank"><img src="root/evakuatory/gallery/7_s.jpg" width="60" height="60" border="0" alt=""></a></div>
<div class="catalogue_pic_l"><a href="root/evakuatory/gallery/8.JPG" target="_blank"><img src="root/evakuatory/gallery/8_s.jpg" width="60" height="60" border="0" alt=""></a></div>

</div>
<div id="catalogue_item_menu">
<div class="catalogue_item_mp_a">
<a href="">Контактная информация:</div>
</div>
 <div class="catalogue_item_cont">
 		 <table width="100%">
			<tbody>
 			<tr>
			<!--	<td><img class="main_sec_image" src="" width="60" height="60" border="0" alt="" /></td>-->
				<td>Адрес:</td>
				<td>Телефон:</td>
				<td>Факс:</td>
				<td>E-mail:</td>
				<td>Веб-сайт:</td>
			</tr>
			<tr>
				<td>Украина, г.Донецк-100<br> ул.Профессоров Богославских, 49</td>
				<td>(062) 385-05-05 (многоканальный)</td>
				<td>(062) 389-01-17</td>
				<td>evakuator@dn.farlep.net</td>
				<td>www.avtosos.eurodonetsk.com</td>

			</tr>
			</tbody> 
		 </table> 		
	 </div>
</div>  

